- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.css
- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.html
Converted ability rolls to use custom roll parsing to be able to accurately calculate successes and complications.  Reformatted the roll template used for these rolls.
> Achtung cthulhu 2d20 covert rolls to custom roll parsing

- Girl By Moonlight/GBM.css
Adjusted the display grid for the cursed fates map for Under a Rotting Sky after user reported spacing issues.
> [Girl By Moonlight] Minor CSS Update (bugfix)

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
> [Star Wars Saga Edition] Repeating crew field bugfix

- 3DeT_VICTORY/3detvictory.css
- 3DeT_VICTORY/3detvictory.html
-> Added Advantage and Disavantage boxes
-> Added Skill Box
-> Added Techine Box
-> Updated the Sheet Look
> [3detVictory][New Feature] Added Advantage, Disavantage boxes, Skill Box, Techine Box

- TheWitcher/witchersheet.html
> [TheWitcher] fix typo in crit text

- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.css
- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.html
Added attack rolls and damage rolls to the weapons section using custom roll parsing.
> Achtung Cthulhu 2d20 New Features - Add attack and damage rolls

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/translation.json
- [ x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) …
> Mongoose Traveller 2E - Dark mode CSS and whisper toggle

- SalvageUnion/SalvageUnion.html
> [SalvageUnion] add more one click importer

- SalvageUnion/SalvageUnion.html
> [SalvageUnion] first batch of mech parts

- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.css
- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.html
Re-organized the spell section.  Add buttons for rolling spell casting and spell damage (stress).  Added generic skill check and damage dice buttons at the top of the character sheet.
> Achtung Cthulhu 2d20 New Features

- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Added support for Force Regimens, which do not use DCs with multiples of 5. Also added support for over/under DCs with no intermediate intervals.
> [Star Wars Saga Edition] Added Force Regimen support

- Shadowrun5th/Shadowrun5th.html
Fixed the physical and stun tracks for use with token bars (now including modifiers)
Added Headers for the weapon tables in main&equipment tab
> Fix for Shadowrun 5th Edition (Advanced)

- Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
Updated to V1.4 of ruleset
Added Aegis under Ranged/Melee Modifications.
Added Aegis to Ranged Weapon Form Dropdown
Removed Gyrostabilizers.
Updated to V1.4 of ruleset
Added Aegis under Ranged/Melee Modifications.
Added Aegis to Ranged Weapon Form Dropdown
Removed Gyrostabilizers.
> Update Paradigm's RWBY TTRPG.html to V1.4 New Feature

- Hexxen-1733-Ulisses-Spiele(Official)/hexxen.html
- Hexxen-1733-Ulisses-Spiele(Official)/src/html/character/roles.html
- Hexxen-1733-Ulisses-Spiele(Official)/src/html/character/roles.pug
- Hexxen-1733-Ulisses-Spiele(Official)/translation.json
I added the recently published role of parazoologist (translations only in german).
> Hexxen-1733-Ulisses-Spiele(Official) - New Feature (new role: parazoologist)

- Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
Hotfix for Aegis Damage modifier.
Hotfix for Aegis Damage modifier.
> Bugfix for Paradigm's RWBY TTRPG.html

- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.css
- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.html
V4.0 Fixlist
🟩 2 Allow the sheet to calculate natural healing
🟩 3 Full compendium integration
🟩 4 Relink images to R20 Git repo
🟩 5 Movement not adding mythic_AGI
🟩 6 STR add not adding to weight calculation
🟩 7 Token mod now needs to use DR instead of armor as armor no longer exists
🟩 8 Lower armor display fields do not match top. (head = chest)
🟩 9 str to melee buttons copied wrong, need their math updated.
🟩 10 Add worn checkmark to armor display in equipment
🟩 11 Make faction training a repeating field
🟩 12 Make weapons training a …
> Official_100DOS_Mythic_by_100DOS New Feature/Bugfix

- GURPS/gurps.css
- GURPS/gurps.html
- GURPS/translation.json
- On character load. The roll modifier toolbox for each section is cleared out, ready for a clean start.
- Ranged Calculator Tool. Added a checkbox for Bracing your weapon.
- List of minor changes: success/fail notes in chat updated to use correct font. Updated warning text for effective Defense Score of 0 or less.
> [GURPS] 2.9.12

- Mork Borg/morkborgsheet.html
- Mork Borg/morkborgstyle.css
- Mork Borg/sheet.json
I've made some changes to the sheet to move away from Legacy for facilitating Dark Mode usage (as I know many MB players will want that) and to change the pixel-based arrangement to a flex display setup.
> [Mork Borg] new feature/aesthetic: updating sheet from Legacy for dark mode

- Cthulhu Awakens/cthulhu_awakens.html
Small fix: Tweak the compendium drop handler after new rake (which renamed one of the categories)
> [Cthulhu Awakens] Fix: Tweak the compendium drop handler after new rake

- Sword World/sheet.css
- Sword World/sheet.html
- Bug: Magic Power raw rolls displaying incorrectly
> [Sword World 2.5] Bug fix

- Ordem Paranormal - Oficial Jambo Editora/ordemparanormal.html
- Ordem Paranormal - Oficial Jambo Editora/translation.json
Fixed Rolls in Ritual
Fixed Crime skill calculation
Added Ritual Bonus fields.
> [BugFix][Ordem Paranormal]Fixed Rolls in Rituals

- Hyperborea/hyperborea.html
Values of CH between 7 and 8 where did not compute the correct reaction modifier. This change corrects this behavior.
> [Hyperborea] Fix CH stat modifier bug.

- LND/legendsneverdie.css
- LND/legendsneverdie.html
- LND/sheet.json
Modify sheet.json to add custom sheet options. Some minor sheet changes.
Added User Options, and added the Wealth attribute to the cheet. Some minor CSS stle updates.
> Legends Never Die: User Options

- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.css
- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.html
- Official_100DOS_Mythic_by_100DOS/sheet.json
Updated Compendium drag and drop handling
> Official_100DOS_Mythic_by_100DOS Update

- SalvageUnion/SalvageUnion.html
> [SalvageUnion] add current cargo + minor improvements

- 3DX/3dx.css
- 3DX/sheet.json
Solved size and padding problems on some columns when using the fullscreen sheet. Updated roll template layout and global sizes.
- The publisher of this game is: <Victor Ballogh and Gabriel Almeida> _(i.e. Wizards of the Coast, Evil Hat)_
> 3DX: Fix padding problems on fullscreen, updated layout

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Character sheet
- Situation modifiers
- New option : ask for checks DC
- New option : target attack rolls (DEF / DEP)
- Gear list JSON import (from Export COMob Web App)
- Profile family JSON import (from Export COMob Web App)
- HP & LP computed based on profile family
- Added a button to display a chat message explaining buffs syntax
- Added a button to display a chat message explaining gear properties syntax
- Mech and Starship sheet
- All referenes to MOD script "COlib" replaced by "COGCrew"
> ChroniquesGalactiques V4.3.0

- DCC/DCC.html
- DCC/README.md
This replaces `disabled="true"` for `readonly` on `<input>` elements to fix buttons not working on parent `<button>` elements per a user request.
> DCC: fixes disabled buttons that have child inputs

- LND/legendsneverdie.css
- LND/legendsneverdie.html
- LND/sheet.json
Discovered an error in the wiki - for Text and Number options, the default value was incorrect.
Also found chrome styling was different to firefox, so corrected that.
> [Legends Never Die] Default Sheet Settings

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
> Inventory Adjustment - Fallout V&D

- GURPS/gurps.css
- GURPS/gurps.html
- GURPS/translation.json
- Melee and Ranged attack tables. Added a "Duplicate" button. Click the button to duplicate the attack, useful for quickly creating alternate attacks based on ammo type or something similar.
- Traits Tab. Disadvantages table. Added a checkbox labeled "Check to make the results a whisper to GM only." If checked, the control roll will be whispered to you and the GM.
> [GURPS] 2.9.13

- Mongoose_Traveller2e/MongooseTraveller.html
Minor fix to add change callback when user changes tons to sell in speculative trade so P/L updates properly
> Mongoose Traveller 2E - Added P/L update when user selects tons to sell

- DCC/DCC.css
- DCC/DCC.html
- DCC/README.md
- opts for using roll buttons without nested inputs to satisfy HTML standards and to fix buttons not working
- formatting fixes to introduce new roll buttons
- adds sources for gnome, ranger, paladin, and bard classes
- adds agility to initiative roll
- adds field to set initiative die to d16 for two handed weapons
- updates class radio input tabs to a dropdown menu
- a few label updates
- update changelog
> DCC: fixes  buttons, adds descriptors, adds agi to init

- NoReturn_2E/noreturn.css
- NoReturn_2E/noreturn.html
- NoReturn_2E/src/html/page-one/block-three-third-row.pug
- NoReturn_2E/src/html/page-two/block-one.pug
- NoReturn_2E/src/html/rolltemplates.pug
> [NoReturn_2E] Bugfix - Images

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/translation.json
- [] This sheet has been made on behalf of, or by, the game's publisher.
- [] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
Added missing Diplomat skill back in!
> Mongoose Traveller 2E - Fixed Missing Diplomat Skill And Added Animal Sheet

- GURPS/gurps.css
- GURPS/gurps.html
CSS fix to allow entering values for these attributes.
> [GURPS] 2.9.14.1 URGENT

- Emberwind/emberwind.css
- Emberwind/emberwind.html
-  added condition tracking for heroes and multiple foes
- added character image to sheet
- customized repeating section buttons
> Emberwind [New Feature] Add Condition Tracker

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn FASA Official - V315 - Bug Fixes and New Features

- Hyperborea/hyperborea.html
Fix variable typos causing DX and CN checks to display the wrong thresholds.
> [Hyperborea] Fix DX and CN tests.

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- JSON profile import
- Added attacks base, hit dice, initiative
- Added support for weapons and gear
- Added calculation for level 1 hit points and luck points
- Corrected a bug when creatin a weapon attack via gear properties (ATD:xxx property now parsed as expected)
- Added chat help messages for the BUFFs and gear properties syntax
> ChroniquesOublieesContemporain Version 3.16.0

- Trail of Cthulhu/sheet.css
- Trail of Cthulhu/sheet.html
- Trail of Cthulhu/translation.json
I add some spaces to define the lenguages that the character knowns, following the example of the oficial character sheet. Also, I add some space to write the objects that the invetigator own.
> [Trail of Cthulhu] New Feature -  Add lenguage scpaces and inventory

- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn FASA Official - v315b - patch

- Trinity_Continuum_2ed/TC2e.html
> bugFix - Anima Sheet

- Pathfinder Community/pathfinder_community.css
- markdown fix for roll templates.  Combined multiple @import url lines into one statement.
> Pathfinder Community Sheet - markdown fix for roll templates

- Pathfinder Community/pathfinder_community.css
- Pathfinder Community/pathfinder_community.html
- Fix font-size of roll templates when chat is popped out.
> Pathfinder Community Sheet - font fix for popped out chat

- Beacon by PGG/beacon.html
- Adds the ability for users to edit tags
- Fixes bugs
> Beacon by PGG - New Feature: Adding ability to change tags by user

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Replaces the buttons that ask for queries with ones that don't in the following sections: 
Vehicle attacks and grapple
Vehicle skills
> [Star Wars Saga Edition] Added setting to remove query on rolls

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Adding options to quickly set NPC skills in Settings
Every roll on the sheet which queries for Other Modifiers should now have an option to turn that off.
> [Star Wars Saga Edition] Completed Other Modifiers toggle feature

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
Adds an extra section to the Hybrid-style character details section at the top of the character page sheet, intended for filling in the Advanced Class for any Pokémon Class characters.
This is backed by an additional attribute that isn't used anywhere else, for now.
> [PokemonTabletopAdventures_v3]: New Feature - Adds advanced class to hybrid character details

- Forbidden_Lands/Forbidden_Lands.css
- fix for tab and logo placement
> Forbidden Lands - header fix

- WOIN/WOIN.html
Updated weapon section for sheet block 1, added functionality to show how many dice were rolled for combat
> Woin sheet updatesv2

- 3DX/3dx.css
- 3DX/3dx.html
A field was added at the end of the page that shows the total points invested in the character.
> 3DX New Feature: Added a field with the sum of points

- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn FASA Official V317 - Bug Fixes

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Added default values. Was not able to add the settings which depend on sheetworkers.
> [Star Wars Saga Edition] Added default sheet options

- Sword World/sheet.css
- Sword World/sheet.html
- Fellow sheet w/ expanded and rolls
- Fellow sheet autocalc switch
- Enhancements for stats (MP/HP/Abilities/etc.) that can be added on top of calc
- Work skills (toggle on in settings)
- Improved monster section name style
- Bug: declared action icon on monster sheet
- Roll button for token actions with context sensitivity
- Bug: alchemist cards show on 0
> [Sword World 2.5] New features

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/translation.json
- Change for slide-in animation
> Mongoose Traveller 2e - Bug Fixes, Repeating Sensors, All/Trained Skill & Slide-In Animation

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/sheet.json
- Mongoose_Traveller2e/translation.json
This is the first phase of adding charactermancer functionality to the Mongoose Traveller 2e sheet.
I'm using this to make sure I have the Roll20 workflow correct.
> [Mongoose traveller 2e] New Feature: stat rolling

- 3DX/3dx.css
- 3DX/3dx.html
The field showing total points has been placed in an appropriate location.
> 3DX: Small change in layout. The points field has been repositioned

- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn FASA v 318- Bug clean

- ShadowbaneInquisition/Shadowbane.html
fixed typos, and removed a bug about redundant roll queries
> [ShadowBane Inquisition] bug fix and typos

- NHKS/Historie.txt
- NHKS/NHKS.html
- NHKS/NHKS.pug
- NHKS/src/html/main-tab.pug
- NHKS/src/html/rolltemplates.pug
- NHKS/src/html/skill-list.pug
- NHKS/src/html/weapon-tab.pug
- NHKS/src/js/sheetworker.js
Rollenfertigkeiten korrekt berechnen
Rollenfertigkeiten korrekt berechnen
> [NHKS] Bugfix

- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Armor section on PC sheet was added as a setting, which completely hides that section (and armor in equipment list) on the sheet.
Moved updated message and wiki link to Settings tab only
Removed line breaks in headers to enable easier translation support
Minor CSS changes
> [Star Wars Saga Edition] New setting: Armor on PC sheet

- Harn Master Gold/harnsheet.html
Kick and Punch ML on the Character tab can now be edited.
> HarnMaster Gold, bugfix: kick and punch ML are now editable

- root/root.css
- root/root.html
Updating url images to magpiegames
- The name of this game is: <Root: The Roleplaying Game>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Magpiegames> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Powered by the Apocalypse> _(i.e. Dungeons & Dragons, FATE)_
> [root]-Bugfix-Updating url images

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Added additional boxes to help keep track of things with multiple Arms and Legs.
> Health Box Update - Fallout V&D

- ICRPG-MasterEdition/ICRPG_ME.css
> ICRPG ME - Enhancement: Expanding loot and ability input boxes for better usability 

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Fixed the names of the roll buttons for INT, WIS and CHA checks on the NPC sheet
> ChroniquesOublieesContemporain Version 3.16.1 (bugfix)

- Qin Warring States/Qin.css
- Qin Warring States/Qin.html
- updated url's of the sheet images to link to the repo's images.
- changed sheet roll button img and logo to background-image
> Qin - updated image urls to repo

- Earthdawn (FASA Official)/Earthdawn.html
- Earthdawn (FASA Official)/sheet.json
> Earthdawn (FASA) Edv319

- Forbidden_Lands/Forbidden_Lands.css
- Forbidden_Lands/Forbidden_Lands.html
- barely perceptible chat dice border-radius aberration fix.
> Forbidden Lands - chat dice aberration fix

- Star Wars Saga Edition/sheet.json
For work done in May and June of 2022
> [Star Wars Saga Edition] Added credit for contributor

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
Added a missing */ at the end of the sheetworker code
As a result, the Roll20 engine did not find the closing </script> element and was not executing any of the sheet-worker code
**Please pull this fix to the sheets library as soon as possible**
> ChroniquesGalactiques Version 4.4.1 (BUGFIX)

- Qin Warring States/Qin.css
- updated logo but forgot to update the url
> Qin - updated new logo url

- Darkness Of The Demimonde/darknessofthedemimonde.css
- Darkness Of The Demimonde/darknessofthedemimonde.html
Corrected the archetype descriptions.
Added an initiative button that sends results to the tracker.
Tweaked the CSS displaying the stress buttons so it doesn't wrap at different zoom levels.
Added CSS for highlighting crits and fumbles.
Added crit and fumble descriptors to the dice rolls so it correctly only marks double 1s or double 6s.
> Darkness of the Demimonde: new initiative button, critical highlighting and corrected archetype descriptions

- inSANe auto cal/inSANe.css
- inSANe auto cal/inSANe.html
- Removed some error images in inSANe sheet
> [inSANe / inSANe auto cal] remove inSANe sheet error image

- DIE/die.html
Raised NPC Stat Limits and updated Image URLs
> DIE Character Sheet NPC Stat Bugfix

- D6_Space/D6Space.html
- Fix incorrect attribute name on D6 Space sheet
> D6 Space bugfix

- WOIN/WOIN.html
> WOIN - [Bugfixes] Fixed old skill dice, status track, trade dmg d6, psionic v magic

- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.css
- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.html
V5.0 Fixlist:
:green_square: New auto damage macro
:green_square: Make Compendium ranged weapons show min and max reload rate like melee attacks
:green_square: GM sheet wont allow users to add more than one repeating row
:green_square: add perceptive range to the top bar
Compendium Fixlist: 
:green_square: Civilians dont have abilities which causes the sheet to search for a non existing array
> Bugfix100DOS mythic by 100DOS

- Ten candles/ten-candles.css
- Ten candles/ten-candles.html
- Rolltemplate Darkmode implement
- Cleaning code
- Image link to Roll20 github instead personnal github
- Flex attribut for futur translation champs
> [TEN CANDLES] UPDATE - Darkmode rolltemplate / Cleaning code and CSS adjustement

- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.css
- Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.html
Added new setting "Type of Sheet" with Character and Vehicle options.
Character option continues to show the current tabs for characters and npcs.
Vehicle options shows new tab for vehicle specific attributes and rolls.
> Achtung Cthullu 2d20 - New Feature

- Glitter Hearts/glitterhearts.css
- change images urls from local to absolute
- fix bug causes in multiline move sections: add and modify buttons were rendered outside the move section due to the height of the header block.
> [Glitter Hearts] Bugfix:  update images urls, fix move-header height

- Glitter Hearts/glitterhearts.css
The original author is using`background-image: image` which looks correct but doesn't work. Fixed to `background-image: url`
> [Glitter Hearts] Bugfix: invalid css property usage: 'image'

- Paranoia Perfect Edition Official/Official Mongoose Publishing Paranoia Character Sheet.css
- Paranoia Perfect Edition Official/Official Mongoose Publishing Paranoia Character Sheet.html
- Paranoia Perfect Edition Official/README.md
- Paranoia Perfect Edition Official/sheet.json
- The name of this game is: < Paranoia  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  Mongoose Publishing > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <  Paranoia > _(i.e. Dungeons & Dragons, FATE)_
Changed the image URLs to look into this repository
Overridden the Default RollTemplate CSS
> Paranoia Perfect Edition Official v1.01.00 - Updated Image URLs, Updated RollTemplate Default CSS

- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
* Section for describing armors, helmets and shields in more details
* Support for wearing a given armor or helmet
* Support for what is in both hands
> ChroniquesOubliees: added support for worn items

- Knight/knight.html
- Knight/pug/js/_functionsWeapons.js
- Knight/pug/js/rolls/pj/combatContact.js
- Knight/pug/js/rolls/pj/combatDistance.js
- Knight/pug/js/rolls/pj/combatGrenade.js
- Knight/pug/js/rolls/pj/combatImprovise.js
- Knight/pug/js/rolls/pj/mechaArmure.js
> [Knight] Bugfix "Tir en Sécurité".

- ProjectMoonTRPG/ProjectMoonTRPG.html
-Evd Power was referencing Justice instead of Insight; fixed.
> [Project Moon TRPG] Tiny bug fix

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Inventory now auto adds itself when you add a new entry. Thank you Oni for the gift.
> Inventory Auto Calculation - Fallout V&D

- World Wide Wrestling 2nd Ed/wwwrpg.css
- World Wide Wrestling 2nd Ed/wwwrpg.html
Due to some changes on the base character sheet .css, some color have switch from black to grey on this sheet. This pull request sets them back to their intended colors.
> World Wide Wresting 2E - Fix field label and background colors

- Call_of_Cthulhu/Call_of_Cthulhu.css
- Call_of_Cthulhu/Call_of_Cthulhu.html
Just adding a simple rolltemplate and the changes that go along with it. A little bit of extra work and making things more user friendly, otherwise the sheet is mostly unchanged.
> [Call of Cthulhu 5e] Add a roll template and some basic styles

- 3DX/3dx.css
- 3DX/3dx.html
Fixed layout bug in the total points field on firefox , added new fields: level, personal goal and benefits.
> 3DX: Bugfix and added new fields (level, personal goal)

- ProjectMoonTRPG/ProjectMoonTRPG.html
-Fixed a Weapon Uses issue
-Adjustment to Advantage/Disadvantage processing
> [Project Moon TRPG] Bug fix

- 3DX/3dx.css
- 3DX/3dx.html
Added a margin at the end of the sheet
Added more lines for skills and a bug in Firefox and Chrome regarding the size of the boxes was fixed.
> 3DX: Added a margin and lines. Bugfix on firefox/chrome

- Nephilim-Legende/nephilim-legende.html
- Nephilim-Legende/src/pug/abstracts/mixins.pug
- Nephilim-Legende/src/pug/components/chute.pug
- Nephilim-Legende/src/pug/tabs/tab1-nephilim.pug
- Nephilim-Legende/src/pug/tabs/tab6-kabbale.pug
Fixes:
- The "metamorphose_name" field had disappeared
- The "chutes" fields (khaiba, narcose, ombre) where broken due to bad args in the +cbButton mixin call
- The "kabb-monde" attribute was broken, missing attr_
- The "kabb-invoc-monde" attribute in fieldset was broken
- The "kabb-invoc-X" checkboxes in fieldset were broken
> [Nephilim-Legende] Fix some typos which caused minor bugs in the sheet

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
added Spells Per Day automatic calculations
added advanced spell options -
this is for when spells have a higher DC than normal added save success options for spells
added advanced weapon options -
this is for when a character has weapon grand master cleaned up some CSS
cleaned up some JS
some typos corrected
> Table Top Defined added new features

- BESM4eExtras/BESM4eExtras.html
Added "portal" to setAttrDuration since the game mentions picking this enhancement when "USING PORTAL ON OTHERS" on page 112 of version 1.4.3-1 of the besm 4e rulebook pdf
> BESM4eExtras.html - Fixed missing enhancement by adding "portal" value to object in setAttrDuration

- Dirty System/dirty.css
Adjusted the tab layout to increase the length of the text which was a bit short.
> [Dirty System] Wrapper adjustement

- Maleghast/Maleghast.css
- Maleghast/Maleghast.html
> Maleghast Sheet Update New Feature

- Draci doupe II/DrD2.css
- Draci doupe II/DrD2.html
- Added popup window for sheet options
- Sheet worker code readability
- Field for in-game date
> Draci doupe II – options popup window

- NoReturn_2E/README.md
- NoReturn_2E/noreturn.css
- NoReturn_2E/noreturn.html
- NoReturn_2E/noreturn.pug
- NoReturn_2E/src/js/sheetworker.js
> [NoReturn 2E] Hotfix

- Draci doupe II/DrD2.css
"\00BB" or "»" in content property breaks roll template for some reason
> Draci doupe II – Roll template bugfix

- 3DX/3dx.html
Improved the clarity of the warning, as some players had difficulties interpreting it.
> 3DX: correction of the skills tab warning.

- 3DX/3dx.css
- 3DX/3dx.html
The colors in the rolltemplate were difficult to see due to the background color imposed by the roll 20 chat in dark mode.
> 3DX: Change in roll template color due to dark mode

- AnimeWasAMistake/AWaM.css
- AnimeWasAMistake/AWaM.html
- Hide radio button on dice scores and replace with highlighting.
- Change spare tab to XP, to track XP expanses.
- Change spare tab to notes.
> [AnimeWasAMistake] graphic update and new tab

- 3DX/3dx.css
Correcting the dimensions of roll template
> 3DX: correcting the dimensions of roll template

- Exalted2e/exalted2e.html
Corrected error introduced in last patch, which isolated Advantages to Mortals only. Advantages should now appear for all Exalt Types as normal.
Added a missing div end tag to prevent Mortals from having all the Advantages.
> Exalted 2e - Advantages Error Bugfix 2

- root/root.html
> [Root] Update root.html

- BREAK!!/BREAK.html
This change only adds attr_ prefix to the ability fieldset.
> BREAK!! FIX abilities not saved

- AvatarLegendsMagpie/avatarlegends.html
Translations for Stats, Conditions and Statuses
> update avatar.html (by magpie)

- AvatarLegendsMagpie/translation.json
Add translations for "conditions" and "stats"
> Update translation.json (avatar by magpie)

- root/translation.json
add translations for "The Arbiter" playbook
> Update translation.json (root)

- BREAK!!/BREAK.css
- BREAK!!/BREAK.html
- Removed useless sheet opened calls.
- Add Rank quick check on stat tab.
- Add character size and automatically set values based on size.
- Add repeating_section for weapons, to facilitate multiple weapon usage.
- Add automatic damage computation with pure roll parsing (no worker). Warning : it will go crazy with negative values and other usually unobtainable values.
- Add the rolltemplate that goes with it
- Change all "sub-titles" from span to h6
- Add whisper roll to attack
- Move Quirk
- Fix abilities (again)
- Add social bonds
- Add Outfit to Gear (previously Inventory)
- FINALLY add foldable sections (based on -Alastor's Fabula Ultima's way to do it)
> BREAK!! New features and sheet upgrade

- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.css
- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.html
> Fallout Equestria character details 

- Exalted2e/exalted2e.html
Corrected error in exalted 2e character sheet causing advantages section of Statistics tab not to show correctly
- The name of this game is: <Exalted>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <White Wolf Publishing> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Exalted 2e> _(i.e. Dungeons & Dragons, FATE)_
Requesting @BronsonHall to complete this task.
> Fixed Error Exalted 2e Character Sheet

- BREAK!!/BREAK.css
- BREAK!!/BREAK.html
- Re merged to apply previously merged but unapplied changes
- Changed darkmode white to a darker shade so that the users' eyes are spared any retina searing
> BREAK!! re merge and color pattern update

- 3D&T_ALPHA/3D&T_ALPHA.html
Ajuste de frase no Chat de resultado de dados
> Ajuste de Frase

- AvatarLegendsMagpie/avatarlegends.html
- AvatarLegendsMagpie/translation.json
Add translations and add conditions in rolls
> update avatar.html and json

- 3D&T_ALPHA/3D&T_ALPHA.html
Reverts Roll20/roll20-character-sheets#12474
> Revert "Ajuste de Frase"

- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.html
Updated skill macro because succusses weren't being tracked correctly
> modified skill roll calculation of fallout equestria pnp sheet

- Prowlers_and_Paragons_Ultimate_Edition/prowlersnparagons.html
- Prowlers_and_Paragons_Ultimate_Edition/sheet.json
Fixed the user ID in the JSON file to to correctly match my own. 
Also found a single checkbox not being recognized in the javascript and fixed the issue.
> [Prowlers and Paragons] Fixed userid and a single check box

- Blue Archive/BlueArchive.html
Adding various new fields; Specialties, DR, Armor, and Initiative (and an Init button)
- The name of this game is:  Blue Archive  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: SPRUG Workshop _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Blue Archive _(i.e. Dungeons & Dragons, FATE)_
> Update Blue Archive - add Specialties, Armor, DR, and Initiative

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
New or expanded features:
Added ability to change order of weapons and armor entries.
Added ability to change order of combat skills and languages.
A weapon's RMod is now applied to an attack's range penalty as selected from the Range Table.
Added movement ability modifiers (to account for movement powers and items) and display of net movement that includes encumbrance.
Fixes:
Fixed range penalty incorrectly showing "-10" for range of 65-125m.
Fixed movement penalty incorrectly showing "-2" for 10-24% carried weight.
Fixed possibility …
> [HeroSystem6eHeroic] Improvements to equipment and skill ordering as well as movement abilities. Bug fixes.

- CoeursVaillants-2/CoeursVaillants-2.html
Reduce text input length to fix display issue in repeating fieldset.
> [CoeursVaillants2] hotfix on field length

- AvatarLegendsMagpie/avatarlegends.html
- AvatarLegendsMagpie/translation.json
Adjust CSS for "Conditions". Add translations for "Basic techniques"
> update avatarlegends.html and json

- velvet_generation/charactersheet.html
Added the ability to drag and drop NPCs, band assets and character roles from the compendium onto the sheet
> [NEW FEATURE] Velvet Generation: increased drag & drop

- NoReturn_2E/README.md
- NoReturn_2E/noreturn.css
- NoReturn_2E/noreturn.html
- NoReturn_2E/noreturn.pug
- NoReturn_2E/src/html/bloecke/charakterdaten.pug
- NoReturn_2E/src/html/bloecke/sonderattribute.pug
- NoReturn_2E/src/js/sheetworker.js
- NoReturn_2E/translation.json
> [NoReturn 2E] Bugfixes

- Mongoose_Traveller2e/MongooseTraveller.html
- Removed errant nbsp on options checkbox
- Added skill speciality into new roll templates
> Mongoose Traveller 2E - Minor typo in non-breaking space

- Golden Sky Stories/goldenskystories.html
Added textarea name for Golden Sky Stories
Text input into Golden Sky Stories sheet's "Human Form" textarea is not saved. I gave it the name `attr_humanformcontent` to fix the issue
> Bugfix: Added textarea name for  Golden Sky Stories

- Prowlers_and_Paragons_Ultimate_Edition/prowlersnparagons.html
Minor alteration to the javascript to make the Nullify Power's PRO Also X calculated as a per rank cost rather than a flat value.
> [Prowlers-and-Paragons] [Bugfix] Correcting Nullify AlsoX Pro cost calculation

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Health Box was updated. LR was removed and the Status Effects were put in to keep track of things easier.
I just noticed that it says Fallout V&V instead of V&D. Not sure how to fix that or if its important.
> Fallout V&D - Health Box Update

- Heavy Gear 4e/HeavyGear4e.html
> Heavy gear 4e ver 0.25 New Feature: Inf Weapons update

- DonjonsEtChatons/donjonsetchatons.html
- DonjonsEtChatons/pug/html/header.html
- DonjonsEtChatons/pug/html/talents.html
- DonjonsEtChatons/pug/js/base.js
- DonjonsEtChatons/translation.json
> [Donjons et Chatons] Update link img / Addition of a missing talent

- BREAK!!/BREAK.css
- BREAK!!/BREAK.html
- Added rolls for Quirk, Bonds, Gear, and shizz
- Added presets for weapon types
- Weapon attack bonus calculates more frequently
- Adding some tooltips
> BREAK!! update, adding utilities and ease of use

- Gaia/gaia.html
- The name of this game is: <Gaia O Preludio>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Auroria Game Studio> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Gaia O Preludio> _(i.e. Dungeons & Dragons, FATE)_
- Bugfix Ability Roll with with blank formula
> Gaia O Preludio - Bugfix

- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.html
Added -10 to battle saddle skill
> updating fallout equestria character sheet, changed a single calculation

- Draci doupe II/DrD2.html
- Fix a typo in the organisations image attribute that prevents images from showing
> Draci doupe II – Fix attribute typo

- ADnD_2E_Revised/2EStyle.css
- ADnD_2E_Revised/css/2EStyle-base.css
- ADnD_2E_Revised/javascript/sheetWorkers.js
Fix to ensure values for henchmen are within limits and do not throw errors
> [ADnD_2E_Revised] Bugfix - Fixed limits of henchmen lookup

- AvatarLegendsMagpie/avatarlegends.css
- AvatarLegendsMagpie/avatarlegends.html
vertically center text in basic and balance moves
> update avatarlegends html & css

- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.html
> Update Fallout Equestria Dead Tree Studio PNP.html (calculation fix)

- Starfinder (simple)/Starfinder (simple).css
Tabs were displaying as radio buttons
> [Starfinder (simple)] Firefox tab fix

- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.css
- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.html
- Official_100DOS_Mythic_by_100DOS/sheet.json
Added:
Inventory tab for NPC sheet
Fixed: 
Json not properly picking up user options
Vehicle Mobility Breakpoints aren’t transferred when drag-and-dropping onto a new sheet
> Fixes and updates to 100DOS mythic sheet by 100DOS

- Fabula Ultima/FabulaUltima.css
- Fabula Ultima/FabulaUltima.html
- The name of this game is: < Fabula Ultima >
- The publisher of this game is: < Need Games!, Rooster Games >
- The name of this game system/family is: < Fabula Ultima >
This commit simply adds a missing upgrade that was planned but also forgotten to the third batch (which consisted of eleven main changes):
12) Added Status Immunities tracker to the character sheet.
> Fabula Ultima: Adding Third Batch missing Upgrade

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Added critical location and severity to vehicle
- Added Notes field to Vehicle
- Added critical severity and location
> Mongoose Traveller 2E - Vehicle Notes & Damage/Severity Changes

- Skyfall/sheet.json
> [Update - Skyfall Character Sheet]Adding Tutorial in sheet.json

- Knight/knight.css
- Knight/knight.html
- Knight/pug/html/popup/popup.html
- Knight/pug/html/tab/IA.html
- Knight/pug/html/tab/IAIncarnee.html
- Knight/pug/html/tab/armure.html
- Knight/pug/html/tab/art.html
- Knight/pug/html/tab/dossier.html
- Knight/pug/html/tab/equipage.html
- Knight/pug/html/tab/heroisme.html
- Knight/pug/html/tab/historique.html
- Knight/pug/html/tab/mechaArmure.html
- Knight/pug/html/tab/modules.html
- Knight/pug/html/tab/subCombat/armure.html
- Knight/pug/html/tab/subCombat/capacites.html
- Knight/pug/html/tab/subCombat/header.html
- Knight/pug/html/tab/subCombat/menu.html
- Knight/pug/html/tab/vehicule.html
- Knight/pug/html/top/right.html
- Knight/pug/js/buttons.js
- Knight/pug/js/knight.js
- Knight/pug/js/library.js
- Knight/pug/knight.pug
- Knight/scss/files/_library.scss
- Knight/scss/files/base.scss
- Knight/scss/files/popup.scss
- Knight/scss/files/tabs/armure.scss
- Knight/scss/files/tabs/dossier.scss
- Knight/translation.json
> [Knight] Improvement of PG/PX - Add Custom Armor

- Storypath/Storypath.css
- Storypath/Storypath.html
- Fixes a bug that prevented knacks from dropping
> Storypath: Fix knack drops

- AvatarLegendsMagpie/avatarlegends.html
- AvatarLegendsMagpie/translation.json
Add translations and adjust "Growth" checkboxes
> Update avatar html and json

- NoReturn_2E/README.md
- NoReturn_2E/noreturn.html
- NoReturn_2E/noreturn.pug
- NoReturn_2E/src/html/bloecke/charakterdaten.pug
**2024-02-17 v1.1 HF5**
* Bugfix 
* Die Spezies-Felder bei Charakterdaten und Fertigkeiten unterscheiden. Das Textfeld bei den Charakterdaten muss dadurch neu befüllt werden.
> [NoReturn 2E] Bugfix

- Vast Grimm/vastgrimmsheet.html
A couple of fields (relating to batteries) were missing input name values and thus resetting every time players closed/reopened their sheets. These edits should correct those problems.
> [Vast Grimm] Bug fix: Correcting battery-related value retention error

- The One Ring 2e/release-notes.md
- The One Ring 2e/sheet.css
- The One Ring 2e/sheet.html
- The One Ring 2e/sheet.json
- The One Ring 2e/translation.json
- added configurable dark theme for pc + adv sheets
- fixed Firefox rolltemplate layout bug
- fixed several CSS bugs
> [TOR 2e]  configurable dark mode + css fixes - 03.09.00 (added feature + bugfixes)

- Knight/knight.css
- Knight/scss/files/_library.scss
> [Knight] FIx CSS

- Draci doupe II/API/DrD2GroupTenacity.js
- Draci doupe II/DrD2.html
- Condensed API script code into one function
- Maybe some performance improvement
> Draci doupe II – API script changes

- alien_rpg/sheet.json
- Updated sheet JSON to possible fix for compendium connection
> Alien RPG: possible fix for sheet not associating with compendium

- dragonbane/dragonbane.html
- Updated compendium drop controller to handle swedish category names.
> Dragonbane 1.93: support for swedish compendium drops

- Fabula Ultima/FabulaUltima.css
- Fabula Ultima/FabulaUltima.html
- The name of this game is: < Fabula Ultima >
- The publisher of this game is: < Need Games!, Rooster Games >
- The name of this game system/family is: < Fabula Ultima >
This smallfix just fixes the styles for the "currency name" input and (CSS) mark global width classes as important.
> Fabula Ultima - Smallfix to CSS and currency name input.

- Paladin/paladin.html
Added correct link to SRC logos as they are currently not displaying on the sheet
> [Paladin] - Update paladin.html - updating broken links to logos

- Paladin/translation.json
Added text from the roll template to translation
> [Paladin] Update translation.json

- Dark Horizons Mechanized Corps/dhmc.html
- Dark Horizons Mechanized Corps/dhmc.html.bak
- Dark Horizons Mechanized Corps/sheet.json
- Dark Horizons Mechanized Corps/sheet.json.bak
JSON updates - Links for support and background info. Also added missing attr_ fields for ATK and Damage counters
Added discord links and main website for support and background, coming soon placeholder for Unit Builder.
> Dark Horizons Mechanized Corps - Bugfix Updated sheet json

- The One Ring 2e/release-notes.md
- The One Ring 2e/sheet.css
- The One Ring 2e/sheet.html
- The One Ring 2e/sheet.json
- minor css fix for wits label wrapping
> [TOR2e] minor css fix 03.10.00 (bugfix)

- Paladin/paladin.html
After initial successful commit, I'm changing all the links to logos that are broken across the sheet, and their placeholder texts, in order to clean the sheet up
> [Paladin] Update paladin.html - Updating all broken links to logos

- Paladin/paladin.html
Adding proper modifiers to character & horse damage - adds or removes d6 to the rolls as per the rules
> [Paladin] Update paladin.html - Adding modifiers to characters/horse damage

- Chasing Adventure/sheet.html
Previous changes from 3 days ago used the wrong file name. I now updated sheet.html
> Chasing Adventure Fixed Filename

- Chasing Adventure/sheet.css
Previous Pull Request had the wrong filenames.
> Chasing Adventure Update CSS

- Paladin/paladin.html
Was missing a part in the code, in order for modifier to be recognized as such
> [Paladin] - Update paladin.html - fixing character damage

- Paladin/paladin.html
Skills was the last section without modifiers to rolls. This will complete the overhaul for this part of the sheet
> [Paladin] Update paladin.html - Adding modifiers to all Skills

- Paladin/paladin.html
The annual glory section was incomplete
- Added missing fields
- Added autocalc to annual glory total
- Updated sum
> [Paladin] - Update paladin.html - Adding missing annual glory values

- Paladin/paladin.html
Next step of overhaul, adding modifiers to all 5 ability rolls
> [Paladin] - Update paladin.html - Adding modifiers to all abilities

- Paladin/translation.json
> [Paladin] - adding missing translation

- Call_of_Cthulhu_DA/sheet.json
> Cthulhu Dark Ages Updating name in sheet sheet.json

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.css
- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
We've add toggles to hide and reveal information in regards to SPECIAL, Combat, Perks, and Inventory.
We added a new section regarding Trackers and we were able to have the inventory automatically keep track of everything.
One odd request that I'm not sure how to do is adding Playtest to the end of the sheet for the name.
> Fallout V&D - Sheet Design Overhaul

- Chasing Adventure/chasing-adventure.css
Fixed layout issue with the 'Hide Unchecked' toggle for Advanced Moves.
- The name of this game is: < Chasing Adventure  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Spencer Moore  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Powered by the Apocalypse  > _(i.e. Dungeons & Dragons, FATE)_
Tweaked Advanced Moves to now be flex-based instead of grid-based, using margins to enforce grid-like appearance layout while properly collapsing when 'Hide Unchecked' is toggled.
> Chasing Adventure Bugfix CSS Update

- inSANe auto cal/inSANe.html
> (InSANe) Remove unnecessary 'disabled' attribute

- Old School Essentials/translation.json
adding missing translation items
> [Old School Essentials] - adding missing translation items

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.css
- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
We added a checkmark to appear within the checkboxes for those who are color blind.
> Fallout V&D - Accessibility Fix

- Vaesen/vaesen_sheet.css
- Vaesen/vaesen_sheet.html
> [Vaesen] Bugfix - attack roll fix

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
Added hiding capability for Equipment section
Fixed the misaligned Speed header
Changed appearance of inputs so they no longer show spin buttons unless hovered over. (Already default behavior in Chrome)
Moved Initiative as Decimal checkbox to the Settings tab
Minor spacing adjustments
> [Star Wars Saga Edition] Appearance changes

- Stewpot/Stewpot.css
- Stewpot/Stewpot.html
- Stewpot/translation.json
Location and look on the Tavern sheet needed to be more complex & larger; added a Notes area to both Tavern and Character modes.
> [Stewpot] Expanded and rearranged some fields

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Sequence Button Fixed
Quick fix on the SQ button.
> Fallout V&D - SQ Button Fix

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Made CT buttons more readable in dark mode.
Changed custom checkboxes to display better when browser zoom is not 100%.
> [Star Wars Saga Edition] Minor CSS changes

- Draci doupe II/DrD2.html
- Change organisation rank range to 0-6
> Draci doupe II – Organisation rank tiny fix

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
An error popped up for END for some reason. It's fixed now.
> Fallout V&D - END Hotfix

- Das_Schwarze_Auge_4-1/dev/css/style.css
- Das_Schwarze_Auge_4-1/dev/html/sheet/footer.html
- Das_Schwarze_Auge_4-1/dev/html/sheet/section_info.html
- Das_Schwarze_Auge_4-1/dev/js/magic.js
- Das_Schwarze_Auge_4-1/dev/js/talents.js
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
- Das_Schwarze_Auge_4-1/sheet.json
My relatively recent changes seem to really have made the sheet more approachable to people other than me and so there is quite the influx of changes to my clone of the character sheets repo :tada:
These are the first small changes, more is on the horizon :)
* Bug Fixes
* Checks of talents with a negative value can now be successful (45be2f6d45)
* Dark Mode: Enhance readability of labels and table headers in the character sheet (312ddcfa8a)
* Preparation of New Version
* Add new author/developer "Pascal Stein" (6bd0d7a377)
* Add info on latest version (68021c4b5a)
* Bump version number (61d731cb1f)
* Regenerate sheet files (c1c3c391d0)
> [Das_Schwarze_Auge_4-1] Contributed Fixes

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Bug fix
RR appeared in DR for some reason.
> Fallout V&D - RR Bugfix

- Paladin/translation.json
> [Paladin] - adding missing translation items

- Old School Essentials - AAC/translation.json
adding missing translation terms
> [Old School Essentials AAC] - adding missing translation terms

- Draci doupe II/API/DrD2GroupTenacity.js
- The API script caused errors to pop up in chat when attempting to change a nonexistent character's attribute
> Draci doupe II – API script fix

- Star Wars Saga Edition/StarWarsSagaEdition.html
Automatically changes the number of dice rolled for a Force Point when the level is increased.
> [Star Wars Saga Edition] Force die sheetworker update

- Private Eye/README.md
- Private Eye/privateeye.css
- Private Eye/privateeye.html
- Private Eye/sheet.json
- Private Eye/translation.json
- CSS changes: the sheet glitched when the avatar was bigger.
- New Feature: when checked at the top, the user is prompted for a modifier before each roll (default to zero)
> [Private Eye] Bugfix, New Feature: fix avatar-height-display and add toggable dynamic modifiers

- Paladin/paladin.html
**ADDING GENTLEWOMAN IDEAL AUTOCALC**
After adding autocalc on ideals for Chivalry, Romantic & Religious, finishing up with the Gentlewoman ideal autocalc, specific to lady characters
**AUTOUPDATE NAME/CHARACTER_NAME**
In order to update name & character_name automatically, without losing the values entered in the @name field in already existing character sheets, I propose this change. This is based on a new hidden attribute called sheet_version. It is functional and changes are done automatically when a player closes & reopens the sheet. Thanks @kfroll20 for the tip!
**FEAST SIZE vs SIZE**
Size is wrongly used in this NPC tab as it is a character attribute, thus updating the value for the character whenever a value is entered in the field, while it's specific to feast size (an event), …
> [Paladin] - Gentlewoman autocalc + autoupdate name/character_name + correcting Size mistake in NPC Feast tab

- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.html
A variety of calculation fixes as well as changing the Logo URL to the one in github
- [] This sheet has been made on behalf of, or by, the game's publisher.
> Update Fallout Equestria Dead Tree Studio PNP.html

- Patient13 v1.5/patient13.css
Changing image urls so that they point to the Roll20 repo
> Patient 13 1.5 - URL change for image

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.css
- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Just an increase to the Fatigue Max due to recent changes.
> Fatigue Increase - Fallout V&D

- BREAK!!/BREAK.html
In most repeating sections, replacing title and textarea default values to placeholders. It’s nicer this way.
> BREAK!! sheet update, replace default values by placeholders

- Mongoose_Traveller/MongooseTraveller.html
As a response to this issue: https://github.com/Roll20/roll20-character-sheets/issues/12309
Both changes have been fixed and tested.
> [Mongoose Traveller] Fixed Computer skill display and Deception skill modifier

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed Menacing Talent, it now adds +2SL per lvl if the roll is a success, and +1SL per lvl if the roll fails. It is now a non-situational bonus adding directly to the SL result to reflect RAW rules more closely.
> [Warhammer 4e Character Sheet ] v1.71 - Menacing Talent fix

- Daemon Exilia/Exilia.css
- Daemon Exilia/Exilia.html
- [ x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repositor …
> Daemon Exilia Imagem change

- H&D/H&D.css
- H&D/H&D.html
> [H&D] Add Bonus Atk to Weapons

- GURPS/gurps.css
- GURPS/gurps.html
- GURPS/translation.json
- ENHANCEMENT: Grimoire tab, spell tables. Added parent/child relationship and sorting, like inventory items. You could create a parent college (remember to set points to zero!) and then set spells to be children of that college. Helps with organizing spell lists.
- ENHANCEMENT: Heat Exposure tool, added formula to determine Intense Heat Threshold.
> [GURPS] 2.14.0

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Allows collapsing class features
- Wraps the repeating class features fieldset in a collapsing feature-style block to hide when not desired - (Comes with a bunch of indentation changes, so sorry for the larger-than-necessary diff)
- Duplicates the flag change scripts to change 'on' and 'off' to '-' and '+'
- Adds CSS rules to support the feature container options flag being on the right and always shown
- Improves visibility of section headers
- Updates the collapsing feature options flag CSS selectors to use child combinators
- Updates README to have collapsible 2023 changes
- Adds space for showing the character avatar
- Adds a div and img to pull in the character sheet avatar and show it in the character sheet tab
- Updates the character stats grid to use a 3-column layout
- Tweaks …
> [PokemonTabletopAdventures_v3] New Features: Collapsing Class Features and Character Avatar

- Cabinet des Murmures/translation.json
Adjusted a tag issue in the translation system
> [TRANSLATION FIX] Cabinet des murmures

- Dragon Ball/dragonball.css
- Dragon Ball/dragonball.html
- Changed the URLS to point Git Hub 
- Added bonus for weapons attacks and Ki atacks.
- Some little bugs
> [DRAGON BALL]  Changed the images URLs to point Git Hub and some other bug fixes

- Notre tombeau/notre_tombeau.css
Just a minor update to fixing picture URL to point to Roll20 Github.
> [FIXING URL] Notre Tombeau

- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
There is an option in the game to have a dice for magic user. I added the option to the file and the possibility to roll that dice.
> ChroniquesOubliees: added missing option for mana dice.

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
> [Star Wars Saga Edition] Repeating Force Powers and minor fixes

- L5R 5th Edition Unofficial/L5R-5thEdition.css
> [L5R 5th Edition Unofficial] Tabs and spin arrow fix

- Star Wars Saga Edition/StarWarsSagaEdition.html
> [Star Wars Saga Edition] Critical bugfix for skills

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
New Burst Buttons have been implemented. Damage has been split between Dice and Flat.
> Fallout V&D - New Burst Buttons

- Masks - A New Generation/masks.css
- Masks - A New Generation/masks.html
Change color of the roll message
directly in the html with a div
> update masks.html & css

- Skyfall/ficha.html
- Skyfall/skyfall.css
Some escaped special characters was not being escaped, swaped by the actual characater.
> [BugFix][Skyfall] Some escaped special characters was not being escaped, swaped by the actual characater.

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
Like seriously, this is RMU attacks.  Including the multiple critical lookup and crit adjustment.  This is a rather complex process.  We roll and lookup criticals, critical scaling (well down anyway), critical type.
Coming soon... hit adjustment.
> [Rolemaster Unified Official]  New Feature Attacks.

- Draci doupe II/DrD2.css
- Apparently I can't write multiline comments and that broke the roll template CSS
> Draci doupe II – Another roll template bugfix

- Kult Divinity Lost/KULT Divinity Lost.css
- Kult Divinity Lost/KULT Divinity Lost.html
Inline styles that worked in sandbox were being stripped from the code when in a live game. Removed all inline styles and replaced with new CSS classes and styles in the stylesheet.
Changed passatt and actatt to passiveatt and activeatt, and made attribute/label order consistent, to make them more readable.
Made the relations textbox into a hidden input since it should never appear but needs to exist for legacy reasons.
> Kult Divinity Lost: Bugfix - Replaced all inline styles with stylesheet classes

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Things like replacing spaces with tab characters, deleting spaces at the ends of lines, replacing labels with h4, properly indenting, etc.
Also fixed a bug where an attribute for Stealth was deleted.
> [Star Wars Saga Edition] Lots of refactoring, Stealth bugfix

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
Created 3 sub-tabs (ability rolls, traits list and buffs list) on the abilities tab to make it less cluttered
> ChroniquesOublieesContemporain Version 3.17.0

- Skyfall/ficha.html
> [BugFix][Skyfall] Fix Reroll

- Dragon Ball/sheet.json
- Medievo Oscuro/sheet.json
- Vikingos/sheet.json
> sheet.json force update

- Dragon Ball/sheet.json
- Medievo Oscuro/sheet.json
- Vikingos/sheet.json
> Refetch preview images

- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.css
- Fallout Equestria Dead Tree Studio PNP/Fallout Equestria Dead Tree Studio PNP.html
> Updating and new features for Fallout Equestria PNP

- Star Wars Saga Edition/StarWarsSagaEdition.html
There are still plenty of unused attributes which were created on sheets which were used during the patches of December 2023, but I think this is the last of the attributes which are in use by the sheet which need to be reset.
> [Star Wars Saga Edition] Fixing attributes which had been set by sheetworkers

- DnD_Moldvay_AmandatheAmazon/D&D_Moldvay_AmandatheAmazon.css
- adjusted field text to be easier to read. (forum request)
> D&D Moldvay - readability bump for input text

- Table Top Defined/Table_Top_Defined.html
Corrected spelling of versatile
corrected critical damage formula
fixed level 5 spell remaining bug
changed links for accessory icons
> Table Top Defined - Typos and Fixes

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Add a targetting button.  When you target someone their db/size/AT etc are populated in the target box.
> [Rolemaster Unified Official] Add a 'target' button

- Official Savage Worlds/SavageWorldsCharSheet.css
- Official Savage Worlds/SavageWorldsCharSheet.html
- Adds the correct class to the compendium drop target so that SWADE Archetypes can be dropped directly to VTT.
> Official Savage Worlds: fixes swade archetypes not dropping on vtt

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.html
Added the possibility to have custom gear slots. Then the sheetworker can enforce some maximum number of items per slot.
> ChroniquesOubliees: added custom slots for gears.

- Official Savage Worlds/SavageWorldsCharSheet.css
- Fixed CSS error that caused roll template styling to be ignored.
> Official SWADE: remove utf-8

- .actions/sheet-http/.gitignore
- .actions/sheet-http/README.md
- .actions/sheet-http/dist/index.js
Look at https://roll20.atlassian.net/browse/CSC-2437 for all the linked PRs.
> requestedsize is now parsed from sheet.json

- Dragon Ball/dragonball.html
- Dragon Ball/sheet.json
More bugs fixed and addapted the character sheet for future translation.
> [DRAGON BALL] Tracker added to the Iniciative roll 

- Vikingos/sheet.json
- Vikingos/vikingos.html
> [VIKINGOS] Tracker added to the Iniciative roll 

- Table Top Defined/Table_Top_Defined.html
Fixed a bug in the spell card macro that prevented the spell school from displaying
a missing " was re-added to the front of attr_spellschool.
> Table Top Defined - Quick Fix

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/translation.json
- RolemasterUnified_Official/updates.md
- Fatigue rolls
- Track HP
- Calculate total maneuver:
- Fatigue
- Injury
- HP Loss
- RR rolls
- (internal) Async calls now timeout and unblock if too long
- Charactermancer:
- Toggle button dissapears more often (when it should)
- Back from languages goes back one, not two.
- Show region selectors in culture ranks
- Fix selection of Region Lore Skills
- Fancy navigation buttons
- Fix most skills (not Material Lore and Languages)
> [Rolemaster Unified Official] Missing features and charactermancer bug fixes

- WAR STORIES WW2 RPG/warstories.css
- WAR STORIES WW2 RPG/warstories.html
> [WAR STORIES - WW2 RPG] Changed the url of the images to point Github folder

- .actions/sheet-http/dist/index.js
- .actions/sheet-http/dist/licenses.txt
Update to github actions code.
> Moving updated github sheet-http code into this repo

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Charactermancer:
- Fix material and creature lore specializations
- Really hit with a hammer the hide chaactermancer button. Hide directly at end of charactermancer.
- Direct critical roll (eg roll an C Electricity)
- Rest to recover Fatigue penalties
- Count the weight of items < 1 lbs
- Update total maneuver penalty when fatigue changes
- Stat info show potential (clearly)
- Fix Talents applying on level up
- Bugs:
- Fix some internal calls using terrible way of saving ranks
- Fix for targets smaller than attacker (no more insane DBs)
- Update Weight Allowance when strength changes.
- Fix alignment of stat info hover
- Fix adding skills failing on error
- Stat gain:
- Show the potential and temporary for stat gains
- Add and remove stat gains tracked correctly
- Extra stat gains are …
> [Rolermaster Unified Official] Talent and many other fixes

- ADnD_1E_Revised/1ESheet.css
- ADnD_1E_Revised/1ESheet.html
- Removed the 18+ Ability score pre-req to show the Exceptional field.
- In-Use adjustment to allow multi-row/attack selections.  Global "Weapon In-Use" attributes (name, speed, misc) will use the "fastest" weapon if multiple rows/attacks are "In-Use".
> AD&D1e Revised

- Masks - A New Generation/masks.css
- Masks - A New Generation/masks.html
Fixed the rolltemplate to match what @akibi90 was trying to do to fix rolls in dark mode. Also adjusted some of the spacing.
Changed the playbook selection so that clicking on the name will also check the checkbox.
> [Masks - A New Generation] Rolltemplate dark mode fix and selecting playbook labels

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- New Crit tables now work as normal with Strike to Injure (UiA version), and some minor corrections.
> [Warhammer 4e Character Sheet] 1.72a Crit table update & corrections

- Warlock Polish Edition/translation.json
- Warlock Polish Edition/warlock.html
> [Warlock-polish-edition] Bugfix

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
This PR is intended to fix a rendering issue that appeared after the last update and which is due to a Roll20 bug
This is Drespar's answer and procedure to fix the problem :
https://app.roll20.net/forum/post/11906410/inline-styles-removed/?pageforid=11912731#post-11912731
No functional or visual changes were made
> Chroniques Galactiques Version 4.5.1 

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
This update is supposed to fix any of the recent Roll20 bugs that have impacted legacy sheets lately (in-line styles, sheet.json settings and preview images)
The suggestion comes from Nicole from Roll20 : https://app.roll20.net/forum/post/11906410/inline-styles-removed/?pageforid=11921782#post-11921782
No functional changes in this update
> ChroniquesOublieesContemporain Version 3.17.1

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Add attacks: Fully(?) customisable:
- Any pubished attack table
- Any listed attack skill
- Modifiers
- Fumble
- etc
- Default skill values for Dynamic Specialisations
- Clear levelup purchases option (button - click it!)
- most buttons are now styled
- Added settings tab to character.
- Move recalc buttons to settings tag
- Added discord link
- Bugs:
- Handle missing regions and lores for culture ranks.
- Fix subskill rolls
- Remove "Immortal" talent from Elves - it's not a thing
- Internal
- Add test framework for level up
- Remove some dead code
- (Need to do rake)
- The name of this game system/family is: < …
> [RolemasterUnified Official] Add custom attacks and bugfixes

- Terre2/Terre2.css
- Terre2/Terre2.html
Correction de la valeur de base pour les langues.  /Fixed base value for languages.
Correction de l'apparence des spécialisations de compétence personnalisées. / Fixed the appearance of custom skill specializations.
Correction sur la valeur 10 sur les jets de caractéristique. / Correction to value 10 on ability rolls.
Correction de bug d'affichage sur les blocs de la bio. / Fixed display bug on bio blocks.
Correction de bug d'affichage sur les bouton "Formé / Non formé". / Fixed display bug on the “Trained/Untrained” button.
Le féminin est appliqué par défaut. / Feminine is applied by default.
> [Terre2] Bugfix

- nechronica/nechronica.html
1. Fix 1 Korean typo (향연 → 향년)
2. Correct the issue where mind1 checkboxes include value="1" but mind2, mind3, and repeating_mind do not.
> [Nechronica] Fixed Madness Points Checkboxes Bug

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - Found an issue with imports where items would be dropped mysteriously.  This affected anything that was in a repeating list and was tied to unique ids within Roll20.  Added another check to prevent duplicate ids.
> Shadowrun Sixth World v.87 - 1 Bugfix (import unique id bug)

- Private Eye/sheet.json
> make change to trigger preview img update

- Star Wars Saga Edition/StarWarsSagaEdition.html
Made sure StealthSize attribute was being included in the Stealth formula.
> [Star Wars Saga Edition] Stealth size bugfix

- Please Rule the North with me, Grand Duke!/northgrandduke.css
In rolltemplates, css url parse error fix (change space to ``%20`` )
> [Please Rule the North with me, Grand Duke!/FIX] rolltemplate url parse error fix

- Skyfall/sheet.json
> [Update] [SkyfallRPG] Update Sheet json

- ADnD_2E_Revised/javascript/sheetWorkers.js
Refactor to remove fetching the character name attribute when it is not needed because it is handled by roll20 at the time of rolling
> [ADnD 2E Revised] Improvement/Removed explicit fetches of character name

- Into the Odd 2nd edition/into_the_odd.css
A minor update to define a variable in the css that was not defined. 
Resolution of the name display of the roll result in the chat window.
> [Bug fix] Into the Odd 2nd edition

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
Vehicle crew skills did not have Initiative properly set.
Removed redundant class
Changed image links to github
> [Star Wars Saga Edition] Vehicle initiative bugfix and refactoring

- Masks - A New Generation/masks.html
Fixed the value of a checkbox so that the Protege's Mentor ability would display
> [Masks - A New Generation] Fixed Protege Mentor showing

- Please Rule the North with me, Grand Duke!/northgrandduke.html
[FIX] add error logic
Add exception handling
- 인연, 계절의 JSON 에러 예외 추가
- 최초 시트 작성시 접기 CSS 미적용 수정
> [Please Rule the North with me, Grand Duke!] fix error

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
- Earthdawn (FASA Official)/sheet.json
- [ X] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
> Earthdawn FASA V331 - New Knack report

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Bugs
- Handle 0 running ranks in DB calculations
- Fix over zealous const in culture ranks
- Fix 4th Crafting skill in Urban Culture
- Fix display of running ranks in DB info
- Charactermancer:
- Make the pbonus & knack totals text, not entries.
- Save languages from charactermancer for all cultures.
- Special button to edit spells (reorder and delete)
- Fix knacks using short name for attributes (without the misc)
- Set critreduction by default
> [RolemasterUnified Official] Bug Fixes Charactermancer culture bugs & Some spell list edit options

- exalted 1/exalted.css
- exalted 1/exalted.html
Changed URL image links to point Github and added wound boxes to Health section
> [EXALTED 1 - FIRST EDITION] Changed URL image links to point Github and added wound boxes 

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Migration of the sheet to CSE
- Replaced CSS trick by details/summary elements in various places
- Minor bugs corrections in the profile and statblock import routine
> ChroniquesOublieesContemporain Version 3.18.0

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Migration of the sheet to CSE
- Changed CSS tricks by details/summary elements in various places
- Minor bugs corrections in the profile et statblock import routines
> ChroniquesGalactiques Version 4.6.0

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Remove HP & PP from side list on main page (tracked in status)
- Show message when weapons are loaded
- Internal
- Ignore (generated) inventory files
- Compendium
- Fix issue with Claw Table missing a row causing wierd misses.
- Improvements for content for the character creation chapter
> [RolemasterUnified Official] Tweak: Remove duplicate PP & HP

- Cloudbreaker_Alliance/cloudbreaker_alliance.css
- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Fixing path to attunement images. Path was pointing to an inexisting branch. Changed to master.
Also fixing inventory weight computation.
Fixing Feature order.
Adding storage system in Notes tab.
Fix movement autocomputing
Fixing Details summary (capitalized all word -> Capitalize start of line)
Fixing missing attribute on Attacks in the magic tab
Summaries of orderable lists now takes the list order into account.
Fine tuning feature visualisation (you can see all features if you have no class, or if feature has no class/discipline. And now features prioritize class when checking if they should be displayed or not, for when you have both class from same discipline)
You can now downgrade your sheet to copper and silver.
> [CLOUDBREAKER ALLIANCE] Multiple New Features and Bugfixes

- ADnD_1E_Revised/1ESheet.html
- Fixed NWP not being hidden by default.
> AD&D1e Revised - nwp fix

- ImperiumMaledictum/sheet.css
- ImperiumMaledictum/sheet_new.html
Fixed the roller color and a few colors on the sheet because color blind people were having issues seeing the green.  Created a sheet_updated variable to ensure that the sheet only imports old sheet values one time and doesn't rely on the old variables being cleaned out.
> Imperium Maledictum hotfix - fix roller sheet colors for colorblindness, sheet update script to run only once

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
- Earthdawn (FASA Official)/sheet.json
- [X ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
> Earthdawn FASA v3.32 Minor fixes

- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Updated attributes and texts from "charm" to "appeal" in skills and sheetworkers
> [CLOUDBREAKER ALLIANCE] update sheet to use "appeal" instead of "charm"

- ImperiumMaledictum/sheet.css
- ImperiumMaledictum/sheet_new.html
My old sheet handled Superiority in the roll as a popup, it disappeared when I uploaded the new sheet.  I added Superiority rolls back in now as dropdown.  Make 3 max fields editable, because talents can add on to calculated totals.
> Bug Fix - Add superiority back to the Imperium Maledictum character sheet

- Please Rule the North with me, Grand Duke!/northgrandduke.css
- Please Rule the North with me, Grand Duke!/northgrandduke.html
- Fixed incorrectly displayed skill roll templates
> [Please Rule the North with me, Grand Duke!/FIX] skill rolltemplate fix

- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Fixing appeal display
Fixing mastery bonus not updating when you stop downgrading
Fixing feature display
> [CLOUDBREAKER ALLIANCE] Fixing Appeal display

- A Song of Ice and Fire/SIFRPNew.html
In this PR, following [this forum post](https://app.roll20.net/forum/post/11950135/song-of-ice-and-fire-sheet-error-and-request#post-11961381) and the original author not responding, we:
- Fix the roll for the "Balance" ability by adding the missing end of the roll formula
- Fix various HTML issues in the sheet detected by Prettier: 2 missing closing tags, and one closing tag of the wrong type (span instead of label)
- Upon user request, we add two custom abilities, at the bottom of the sheet, to support custom/houserules abilities. Those are modelled after the language section except they've been made a bit more compact
> Fix: A Song of Ice and Fire: Fix Balance roll, fix HTML issues, add 2 custom abilities

- Skyfall/ficha.html
- Skyfall/skyfall.css
-> When rolling attribute it was summing the save in it.
> [BugFix][SkyfallRPG] Fixing a Bug when doing attribute roll

- Nephilim-Legende/nephilim-legende.html
- Nephilim-Legende/src/pug/components/incarnation-selector.pug
- Nephilim-Legende/src/pug/tabs/tab4-combat.pug
> [Nephilim-Legende] Fixes in one incarnation period label and on the combat tab (broken roll & magical health management)

- Draci doupe II/DrD2.css
- Draci doupe II/DrD2.html
- Tiny lightmode CSS fix
- Sheet worker optimization attempt
> Draci doupe II – Small changes and sheet worker optimisations

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- First version of individual spell casting
- With compendium; click a spell to cast it
- Spells get own css file now
- Tests for some spell casting function
- New misc Flattern for inline summaries
- Tweaks to edit spell list
> [Rolemaster Unified Official] New Spell casting feature

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Display "No Voice" instead of "none" in spells
- Show all the modifiers in the casting log all the time.
- Can edit spell names
- Spell results show RR targets for F, Fm, I and Im spells.
- No PP spells now longer check or require PP
- Cap passive dodge & passive block at 50
- Fix calculation of partial dodge when encumbered (Thanks @filroden)
- No stats is equal to a 50.  Makes NPCs super easy.
> [Rolemaster Unified Official] Spell casting and defense improvements

- Official Savage Worlds/SavageWorldsCharSheet.html
- Fixed an error that was causing gear information from the upcoming fantasy comapanion to not drop for NPCs
> Official Savage Worlds: Fixes gear not dropping from fantasy companion npcs

- ADnD_1E_Revised/1ESheet.html
- portrait roll (clicking on the on-sheet portrait) no longer includes the whisper option. I have also added a query to prevent accidentally posting the image to chat.
- moved old update announcements to the sheet's wiki page. https://wiki.roll20.net/ADnD_1st_Edition_Character_sheet
> AD&D1e Revised - updated portrait roll

- Chasing Adventure/chasing-adventure.html
Updating the sheet's built-in moves for the new v1.6 game.
Updated the text on several of the moves on the sheet to match the latest update to the game.
> Chasing Adventure HTML Content Update

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- SCR now includes stat modifier.
- Improve layout of hits/injuries/endurance etc
- AP Tracking for spells: So cast a spell with 2AP, -50 mod.  Optional checkbox to enable
- Handle Spell Trickery
> [Rolemaster Unified Official]: Minor Spellcasting features

- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Adding options in the Option tab. 
Option allows players to select if they want to see the advantage and modifier popup
> [CLOUDBREAKER ALLIANCE] New Feature Roll popup suppress option

- StarWars5E/README.md
- StarWars5E/StarWars5E_CSS.css
- StarWars5E/StarWars5E_HTML.html
Reverts Roll20/roll20-character-sheets#13074
> Revert "Star wars 5E : NPC layout improvement"

- Torchbearer 2E/README.md
- Torchbearer 2E/src/pug/pages/relationships.pug
- Torchbearer 2E/src/scss/conditions.scss
- Torchbearer 2E/src/scss/mixins.scss
- Torchbearer 2E/src/scss/relationships.scss
- Torchbearer 2E/torchbearer.css
- Torchbearer 2E/torchbearer.html
You can see it's displaying more conditions than it's supposed to here (the yellow boxes)
> Torchbearer 2e: fix some conditions displaying incorrectly

- Medievo Oscuro/medievooscuro.css
- Medievo Oscuro/medievooscuro.html
> [MEDIEVO OSCURO]Added 3 extra sheets to play with level 0 players

- Fire Emblem/Fire-emblem.html
> [FIRE EMBLEM] 2 input number fields changed to text fields

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Critical Damage Rules Houserule 3#: Changed spells RT crit button, will now Default to Elemental table on the drop down menu.
> [Warhammer 4e Character Sheet] Update 1.72c

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
2024-7-30
- Lots more work on Creatures on the backend.
- Big thanks to Scott C on the roll20 discord for his aid.
- Override 0 ranks when set.  Thanks to Hurin for this bug
- Handle not having compendium when adding attacks.  Thanks to Christoffer Holm for the report
> Rolmaster Unified Official: Bug fixes and enchancements to creatures

- Draci doupe II/DrD2.html
- "current" stat attributes should be allowed to go below zero
> Draci doupe II – Allow negative stat current attributes

- Demon Gate/DemonGate.css
- Demon Gate/DemonGate.html
Recalculate all skills when attributes change or when the sheet is opened. Added basic support for dark mode in roll templates, which are currently illegible in dark mode.
> [Demon Gate] Bugfix - Skill recalc, partial dark mode support

- NoReturn_2E/README.md
- NoReturn_2E/noreturn.css
- NoReturn_2E/noreturn.html
- NoReturn_2E/noreturn.pug
- NoReturn_2E/src/html/bloecke/sonderattribute.pug
- NoReturn_2E/translation.json
Erste Verbesserungen nach der Feedbackrunde
> [NoReturn 2E] Enhancements - Verbesserungen nach Feedbackrunde

- Splittermond/Sheet.html
This fixes #13140 by adding missing try catch block and variable for ranged weapons.
> [Splittermond] [Bugfix]  Adding missing variables  #13140 

- BASH Ultimate Edition/BASH.css
- BASH Ultimate Edition/BASH.html
Page layout is broken from last change, this fixes it.
First time using GitHub. Something went wrong uploading files last time.
> BASH Ultimate Edition - Fixing bug, please apply this ASAP

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Updates 2024-8-6
- Spells:
- Fix bug where OE Low rolls failed with NaN
- Show the correct OE Low roll when rolling OE Low
- Tweak message for PP on failure
- Fonts; add some more fallback fonts.  Impact is terrible
- Create:
- Fix a bug where languages spent in creation were not showing.
- Add validation that events are registered correctly.
- Inventory/Attacks
- Correctly cleanup old attacks.  No longer thousands of attacks
- Refactor code to be cleaner in process
- Use pending infrastructure to remove potential race conditions
- Automatically update the bonuses for attacks.
- Remove encoded attack message on attacks.
> Rolemaster Unified Official: Bugfixes for spell failures and attack generation

- Rogue Trader Improved/RogueTraderImproved.css
- Rogue Trader Improved/RogueTraderImproved.html
- Rogue Trader Improved/sheet.json
See details below
REVISION 5 "Man your battlestations!"
*Ship Tab Update:
-Info titles now placed on the labels
-Fields rearranged in ship statistics
-Extended Shipboard actions added with macros and info.
-Default Manoeuvre action macro next to the Manoeuvre field
-Ship weapons expanded now with a radio selector and unique macros for different types of weapons
-"Ship is Crippled" Button toggle that applies the related penalties
-Homebrew "Emergency Warp Jump" button added
*Roll template update:
-Degrees now specify "of success" or …
> Rogue Trader Improved Rev.5 Update

- 4d6 Morgalad/4D6FantasySheet.html
• Special Abilities now with functioning roll button • Special Ability Text Now Appears in Roll Template. • Fields Available to associate dice rolls and types with special abilities.
- The name of this game system/family is: …
> Update to Special Abilities 4D6FantasySheet.html

- Medievo Oscuro/medievooscuro.html
Changed PNJ sheet number 2 and 3 two lines of code. The name and the bono field.
> [MEDIEVO OSCURO] two bugs fixed in PNJ sheet

- ADnD_1E_Revised/1ESheet.css
- ADnD_1E_Revised/1ESheet.html
- Updated the background-image URL for parchment.
> Ad&d 1e Revised

- Chronicles of Darkness/CofD.html
A very simple change just to enable something that was missing for the Demon the Fallen Supernatural Template
> Chronicles of Darkness: Added a section for Legacy Beats on Demon the Fallen

- Das_Schwarze_Auge_4-1/dev/html/sheet/footer.html
- Das_Schwarze_Auge_4-1/dev/html/sheet/section_info.html
- Das_Schwarze_Auge_4-1/dev/html/sheet/section_talente.html
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* Fix: Rolls on scripts not working (6fbad4d745d08b7f8393b547140628adedd39eec)
* Bump version number (8e4f86d7abd409b7bc2ae09e855e58186a032f26)
* Add info on latest version (47985d05b5f00a012aaa0b5f40dad14e2b2407ff)
* Regenerate sheet files (22e489d5093b3ef46d50f154caeb641151684eea)
> [Das_Schwarze_Auge_4-1] Fix: Rolls on scripts not working

- Rogue Trader Improved/sheet.json
> Rogue trader improved hotfix JSON file

- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Version 3.18
Fixed issue where moving a weapon in the weapon list would not move its "range based on STR" property.
> [HeroSystem6eHeroic] Range based on STR bug fix.

- Rogue Trader Improved/sheet.json
attempting to get the formatting right, since the Sheet Sandbox JSON display does not work
> Rogue Trader Improved JSON hotfix 2

- ADnD_1E_Revised/1ESheet.html
- Updated the Pick Pockets roll to include a query for the hit dice of the target and check for detection if the attempt has failed. The HD query will adjust the target score and check for detection according to the PHB.
> AD&D1e Revised - updated pick pockets roll

- Rogue Trader Improved/RogueTraderImproved.html
- Rogue Trader Improved/sheet.json
bug fixing, as reported by user Jason O.
also another attempt at getting the json formatting to look good
> Rogue Trader Improved rev5 hotfix 3

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Version 3.21
•  Added damage modifier to unarmed standard maneuvers (Combat Skill Levels).
> [HeroSystem6eHeroic] Added CSL damage modifier to unarmed attacks

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
* Fixed dark mode Inline Rolls
* Fixed skills not updating
* Corrected line break in spell descriptions
> Table Top Defined - Bug Fixes

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Support for abilities with usage frequency (once per combat, once per day, once per session, etc...)
- Configuration in the ability tab
- Usage count, alert message in chat when usage exceeded, new button to reset usage count
- Automatically loaded when importing a profile from a JSON blob
- New buttons for hit points loss/gain from the sheet
> ChroniquesOublieesContemporain Version 3.19.0

- ProjectMoonTRPG/ProjectMoonTRPG.html
A quick hotfix for a sizeable bug discovered after the v0.6.3 update
> [ProjectMoonTRPG] Hotfix: Evade rolls being stored as blocks

- sinistros_e_monstros/sinistros_e_monstros.html
ajustments of the fields
- The name of this game is: <   >  _(Sinistros e Monstros)_
- The publisher of this game is: <   > _(Universo  simulado)_
- The name of this game system/family is: <   > _(TTT)_
> ajustments of the fields

- Spire - The City Must Fall/spire.css
Replacing background image with a roll20 hosted version as imgur servers seem to be unstable as of late
> Update Spire the City must fall - minor css change

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
… not to calculate. This also fixed the 2nd profession skill.
* accidental removal of a variable has been corrected. This will restore functionality of skills remaining, and the second profession skill.
*  Some white space changed in the CSS for easier reading in the future.
> Table top Defined - Bug Fix

- Level Up - Advanced 5th Edition/CHANGELOG.md
Bugfix:  Markdown formatting was broken. This commit fixes up the formatting so that the rendered HTML is correct.
> Cleanup formatting in CHANGELOG.md

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Bump sheet to version 3
- Version 3 has only 'Realm Stat' for SCRs, removes 'Realm Stat Bonus'
- Clear high level spell names on updates.
- Move defenses near RRs on the main page.
- Spell display:
- Don't add Realm Stat to casting bonuses twice.
- Always put things [ ] (even hand bonusues) in description
- Display 'no voice' corrently (not undefined)
- Attacks:
- Fix escaping for ')' on targets
- Fix for target size bug (typo I guess)
- Encode location in the damage string.
- Actions
- Persist free action, and clear after 4 phases.
- Show the correct phase (relative, not the total)
- Add 'new combat' button
- Status
- Display staggered/stun status
- Apply stun penalties to spells & attacks
- Injuries
- Display knockback, grapple and other injury types
- Keep record of penalty based …
> RolemasterUnified Official: Injuries and many fixes

- 3DX/3dx.css
Fixed a line which broke text sizes after months.
- The name of this game is: <3DX First Edition>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
Remove one line from the css reset that suddenly broke the entire roll template font-sizes.
> 3DX - Fix broken text sizes on roll templates.

- Roll for Shoes/sheet.html
- Roll for Shoes/styles.css
- Changed: Visual improvements to the individual dice display
- Added: Display of effective (non-zero) modifier number from roll prompt
> [Roll for Shoes] Clean up dice display, add applied modifier number

- alien_rpg/sheet.json
@Kurohyou, I was asked to make this update to the sheet after I gave [this reply](https://app.roll20.net/forum/post/12025794/alien-rpg-character-sheets-inaccurate-number-of-stress-dice-rolled-when-pushing-skills/?pageforid=12026036#post-12026036) in the forums. With so many sheets, it's hard for them to know which sheets are owned by who, so this would help them direct users to the right place for support requests.
> Alien | Documentation | Update Instructions to include support portal directions.

- Draci doupe II/DrD2.html
- Strict equality in conditions, integer conversions and other small changes
> Draci doupe II – Sheet worker tweaks & fixes

- Torchbearer 2E/src/js/init.js
- Torchbearer 2E/src/pug/pages/anatomy/anatomy_mixins.pug
- Torchbearer 2E/src/scss/anatomy/who_you_are.scss
- Torchbearer 2E/src/scss/anatomy/wises.scss
- Torchbearer 2E/torchbearer.css
- Torchbearer 2E/torchbearer.html
This just does a few little fixes and style updates to make things look a bit cleaner across different browsers and some parts I missed in my original testing of the changes I sent up yesterday.
> Torchbearer 2e: cleanup some styles and default values

- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Version 3.23
Fixed roll query related bug where entry of leading plus sign would cause roll math to fail.
> [HeroSystem6eHeroic] Roll query bug fix

- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
- The name of this game is: <   >  _(i. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i. Dungeons & Dragons, FATE)_
Fix a bug which prevented the version attribute to be created.
> Chroniques Oubliées: fix version attribute not set.

- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Just changing two default values from 0 to 1
And rename "Minor" for "minor" in action type for spells
> [CLOUDBREAKER ALLIANCE] Update Equipment default weight

- Brigandyne 2e édition/sheet.json
The following Action failed because of the sheet.json being malformed: https://github.com/Roll20/roll20-character-sheets/actions/runs/10725048060/job/29742158234
> Fixes missing comma

- Delta Green 2/deltagreen.html
- Delta Green 2/src/js/sheetworkers.dev.js
- Delta Green 2/src/js/sheetworkers.js
- Delta Green 2/src/js/sheetworkers_handlersheet.dev.js
- Delta Green 2/src/js/sheetworkers_handlersheet.js
- Delta Green 2/src/js/sheetworkers_onchange.dev.js
- Delta Green 2/src/js/sheetworkers_onchange.js
- Delta Green 2/src/js/sheetworkers_onclicked.dev.js
- Delta Green 2/src/js/sheetworkers_onclicked.js
- Delta Green 2/src/js/sheetworkers_parseinput.dev.js
- Delta Green 2/src/js/sheetworkers_parseinput.js
- Delta Green 2/src/js/sheetworkers_ritual_activation.dev.js
- Delta Green 2/src/js/sheetworkers_ritual_activation.js
- Delta Green 2/src/js/sheetworkers_rolls.dev.js
- Delta Green 2/src/js/sheetworkers_rolls.js
- Delta Green 2/src/js/sheetworkers_versioning.dev.js
- Delta Green 2/src/js/sheetworkers_versioning.js
bug fix in versioning where the version wasn't updated
Bug Fix:
the scope of update in versioning 200_201 and 201_202 was local (let) thus, the versioning function was always updated when the sheet was opened, resulting in overriding names and skills for weapons and special repeating sections
> Bug Fix Delta Green by ArcDream 

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
The first post compendium release... and it's small.  This is a good thing. Sooner I get to Treasure Law I guess.
- Rewrite the way we track spell lists on level up.
- Makes Hybrids happy; stops duplicated lists during level up
- Track lists from from the sheet side.  Should stop the annoying duplicate spell list after level up.
- Fix parsing of Tiers for single Tier talents.
> Rolemaster Unified Official: Update how spells are tracking during level

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
- Star Wars Saga Edition/translation.json
* Added Knowledge (Tactics) to the list of vehicle skills for the Commander position
* Refactoring of attacks-grid CSS
* Added "Turn Order" clarification to Initiative at the top of the page. Added a toggle for Initiative Notes to the turn order button.
* Added highlight for Attack and Damage labels when hovered, to indicate the ability to reveal sections
> [Star Wars Saga Edition] Small CSS changes and refactoring

- Black Troopers/blacktroopers.html
ajustments of the sheet
- The name of this game is: <   >  _(Black Troopers)_
- The publisher of this game is: <   > _(Nozes Game Studio)_
- The name of this game system/family is: <   > _(BXP)_
> Ajustments of the sheet

- Shadow of the Weird Wizard/shadowoftheweirdwizard.html
Fixed broken link, not showing logo in sheet
- The name of this game is: <  Shadow of the Weird Wizard >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Schwalb Entertainment  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Shadow of the Weird Wizard  > _(i.e. Dungeons & Dragons, FATE)_
Link to image broken in sheet was asking for %25 not %20
> BugFix Shadow of The Weird Wizard

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
A number of small updates this week.  Starting some work to fix a mumber
of other wierd bugs; but nothing yet. Thank you to all who have reported
problems.  Please let me know if there are more.
- Dark mode tweaks for side panel, and the crit box.  Dark mode is still a long
way from complete on the main sheet; but the side panel should be usual.
- Spell rank modifier when casting; missed that in the other massive improvements.
- Don't barf AP updates on New Combat.
- Fix for weight allowance (thanks spaturno80).  I totally misread those rules.  Like totally.
- Creature sheet improvements for skills and other items.
- Async: Recover is a few more wierd situations (thanks major__havoc).
- Spells: Show trickery and grace bonuses in spells.  This is the sort of
feature you get when I play …
>     RolemasterUnified Official: Minor fixes and tweaks.

- Demon Gate/DemonGate.html
- Added the Allure attribute (replaces Beauty, and is a full attribute)
- Glory has been renamed to Fame
- Combat skills that used to go up to +3 now go up to +10
- Added the Sorcery skill
> [Demon Gate] New feature - added the Allure attribute, other minor changes

- Table Top Defined/Table_Top_Defined.html
Updated from an in-line macro set up to one constructed with java script to make damage easier to read. This allows the 
damage types to be more easily separated and will make future features easier to implement.
> Table Top Defined -- New Feature -- Updated damage calculation macro

- Brigandyne 2e édition/sheet.json
Fixed preview image name in json
Fixed preview image name in json
> Bug fix Brigandyne 2e édition

- Brigandyne 2e édition/brigandyne_2e_edition.html
Sheet line 6 : changed to a more reliable host for logo image (imgur)
Sheet line 753 : fixed missing semicolon
> Bugfix Brigandyne_2e_edition.html

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Start work on fully supporting encumbrance and maneuver penalties.  So now we calculate load (we did not before), our max pace (been empty forever), change the property name to carried_weight (was set, but never used before).
- Creatures:
- Handle more attack types
- Creature attacks work again with the new maneuver penalties.
- Fix issue with creatures without skills failing
- Update maxpace and load %s on sheet
- Need to update equipment in the compendium to make this effective.
- Add a dot to show skills you have a profession bonus in
- Update DB:
- Add passive block to active dodges and passive dodge to active block
- Cap running ranks, not passive DB at 50.
Note to roll20 reviewer: The attribute changes should not impact any real game.  The properties are currently not used.
- The …
> Rolemaster Unified Official: DB, Creature and skill updates

- Please Rule the North with me, Grand Duke!/northgrandduke.css
- Please Rule the North with me, Grand Duke!/northgrandduke.html
Changed the crisis output logic.
Fixed a 'daegong-dif' roll template output error.
> [Please Rule the North with me, Grand Duke!/FIX] modify crisis print system 

- Brigandyne 2e édition/brigandyne_2e_edition.html
Correction of 2 html typos : missing underscore in lines 633 & 635
> Bugfix  brigandyne_2e_edition.html

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Work continues on improving 'stuff' (aka Inventory or items).  So first up we have casting penalties for armor calculated and working.  This may may the spell casters in your group most unhappy.  I hope they stocked up on Transcendance.   We have also added a 'pack' and 'store'.  A pack is backpack or similar item you can drop if in combat.   Or maybe on
your horse.  There is a toggle button to carry or not carry it. Encumbrance penalties are calculated depending if carried or not. Store is for stuff your character doesn't have with them.  Homewares or buried treasures.  You can move items between the three lists easily.
Then there is a pile of small items; Spells persist previous ranks on lealup is the most notable.  Lots of people have asked for this - Enjoy!
- Stuff (aka Inventory)
- …
> RolemasterUnified Official: Inventory Improvements and other fixes

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Remove a lot of debug in level up and stuff.
- Allow creatures to be called NPCs on drop
- Creatures (NPCS) now display spells
> Rolemaster Unified Official: Some tweaks to creatures.

- Please Rule the North with me, Grand Duke!/northgrandduke.css
- Please Rule the North with me, Grand Duke!/northgrandduke.html
Fixed a 'daegong-crisis' roll template output error.
> [Please Rule the North with me, Grand Duke!/FIX] modify crisis roll template

- Official Savage Worlds/SavageWorldsCharSheet.html
- Fixes drop issues with some complex data items (e.g. cyber Knight)
> Official SWADE: Fix drop issue with some complex items

- Call_of_Cthulhu_7th_Ed_French/coc_7th_ed.html
correct 2 typos in the character sheet
> [Call of Cthulhu 7th edition (French)] correct 2 typos in the character sheet

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
A small list of minor updates.  Big piece was tracking down the annoying errors in some attack rolls which were making me wonder if I could count.  There is a compendium update which was uploaded last night.  Characters may need to regenerate thier attacks (mostly only natural attacks) if they are still seeing the problem.
- (Hopefully) quieten monsters AP messages.
- Handle a numeric AT (some monsters)
- Updated attack testing significantly.
- Remove some not-an-error errors in attacks
- Stop using D for side.  That's death/defeat.  O is now side. (Odd)
- Fix for monsters dropped from compendium
- The name of this …
> RolemasterUnified Offcial: Minor updates

- Broken Compass/brokencompass.css
Better readability :
- Make the text black in Dark mode
- Remove text bolds
> Broken Compass Update CSS

- ProjectMoonTRPG/ProjectMoonTRPG.html
Code Improvements:
- Begins the work of improving a lot of the older code to ease future sheet development
Bugfixes:
- Fixes Targeting not working for players
- Fixes CustomMessages not parsing correctly when containing commas or quotes
> [Project Moon TRPG] Bugfixes & Improvements

- Star Wars Revised RPG/SWRRPG.html
Bug fixes:
Replaced URL for logo from personal GitHub to new roll20 GitHub, as per forum directives. Fixed cut and paste error on Appraise skill. Fixed half rank issue for class skills, as half ranks should not exist for class skills, with sheetworker which rounds down class skills.
Bug Fixes:
1. As per Forum suggestions for future image logo URLs, the last update had the image URL referencing my personal GitHub and this URL points to the image uploaded to Roll20's GitHub.
2. Fixed cut-and-paste error for Appraise skill.
3. Fixed half …
> Star Wars Revised RPG: Bugfix

- ProjectMoonTRPG/ProjectMoonTRPG.html
Bugfixes:
- Fixes conditional AutoEffects from different sources being able to affect one another
- Fixes ChallengeRolls not accepting #Silent
- Fixes CustomMessage and FlatDamage not accepting #Target
- Fixes CustomMessage causing an error when being the first effect in an AutoScript
- Fixes the Give Ailments action button not working
> [Project Moon TRPG] Bugfixes

- Cloudbreaker_Alliance/cloudbreaker_alliance.html
- Setting default defense base value in Options tab to 6 instead of 0
- Setting default fortitude base value in Options tab to 6 instead of 0
- Setting default willpower base value in Options tab to 6 instead of 0
> [CLOUDBREAKER ALLIANCE] Updating default values for defenses

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/sheet.json
- Optimized sheet code and the reduced overall size by ~5%
- Fixed not being able to use certain symbols in the character name without breaking sheet functionality, e.g.: " (). Some still don't work, e.g.: | {}
- PC & NPC RT clicky button code unified, should resolve some odd issues
- Allow Endurance test when Unconscious
- Added Critical Damage Rules House rule 3 to default settings options (outside the game)
- Fixed Enc Penalty not applying to Agility correctly
> [Warhammer 4e Character Sheet] Update 17.3a - Fixes & Optimization

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
We have started power level support - after seeing people use it mixed; I'm doing per characcter, not a game setting.  First up is stat rolls. Fun fact, stat rolls were like the first thing I implemented.  This now uses CRP (custom roll parsing) to generate and display the stats.  And we now support rerolls for each of the standard power levels.
A few more logs when injuries are applied - so you know it worked.
And an easy button to upload NPCs.
- Start of Power Level support
- Sheet version to 4: Set everyones powerlevel to Superior
- Show powerlevel on sheet
- Add create step for power level
- Add support for powerlevel during stat rolling
- Use the roll20 dice roller for dice; not the js one.
- Send stat rolls to the chat.
- More messages when injuries are applied.
- Make checkboxes a …
> RolemasterUnified Official: Power Level start, better stats & others

- Deathwatch/Deathwatch.html
Save the renown attribute that wasn't saved since #9259
(I don't mean to shame the PR author. He was right to change the name, but he made a mistake that wasn't seen in the review)
> [Deathwatch] [Bugfix] Fix renown attribute not saved

- Rogue Trader Improved/RogueTraderImproved.html
- Rogue Trader Improved/sheet.json
***No Attrs were changed or removed, only moved to a different section
*Advancement sections was moved to Journal Tab to reduce clutter on the Talents tab, also added tooltips for the XP labels 
*Force Field and Gears switched places to reduce clutter in Combat Tab 
*Added tooltips on ship tab components, plus script update for ship crippled 
*Final attempt at getting the JSON format to look good in the sheet selection screen
> Rogue Trader Improved hotfix4

- Draci doupe II/DrD2.css
- added a new serif font that looks very pretty
> Draci doupe II – new serif font

- Sword World/sheet.html
Added new races and Battle Dancer class to character sheet, with correct calculations
Added Battle Dancer Warrior-type class, plus new race suggestions in the dropdown (Abyssborn, Dark Dwarf, Fey, Fluorite, Miakis, Newman, Spriggan, and Valkyrie).
> Update sheet.html with Battle Dancer Class

- Rangers of a Broken World/RoaBW.html
- Rangers of a Broken World/translation.json
Just a minor bugfix (scatter and blur tracks were sharing the same attribute set rather than their own distinct separate ones) and an update to the instructional text for the Key section.
> [Rangers of a Broken World] Bugfix and instructional text update

- Medievo Oscuro/medievooscuro.html
> [MEDIEVO OSCURO] Weapon damage changed to a text field instead select class:"dtype"

- Star Wars Revised RPG/SWRRPG.html
Bug Fix: Formula for non-class skill fixed
Fixed error in non-class skill tabulation where the first half rank was not counted (an problem with rules interpretation)
> Bugfix SWRRPG: Fix non-class skill calculation

- Torchbearer 2E/src/js/calculate_dice.js
- Torchbearer 2E/src/pug/pages/kit.pug
- Torchbearer 2E/src/scss/anatomy/abilities_and_skills.scss
- Torchbearer 2E/torchbearer.css
- Torchbearer 2E/torchbearer.html
This adds some polish to a few bugs found during play. Mainly updating some dice calculations.
> Torchbearer 2e: polish some bugs (#7)

- JoJoDnD/jojodnd.css
- JoJoDnD/jojodnd.html
- [ x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repositor …
> New Page for JoJoDnD Sheet

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
A few new skills were added; but the dependancies were not regenerated.  Regenerate so all the events trigger.
> RolemasterUnified Official: Fix dependances for new skills

- Elric/sheet.json
I am not longer supporting this sheet and do not want contacted regarding it.
> [Elric] Update sheet.json I want no contact regarding this sheet.

- Deathwatch/Deathwatch.html
I'm working on adapting the sheet proposed by PR #13308 to the current sheet.
Even though I'm creating a migration process, this may have repercussion on the users. So I want them to know about it (and their feedback may help me streamlining the experience).
> [Deathwatch] Update announcement about the impending sheet migration

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
Ego Save added to the sheet, small increase to note text area size.
> New Feature - Ego Save added

- MorrowProject4e/sheet.json
> [Morrow Project 4e] Update sheet.json No longer supporting sheet

- Serenity/serenity.css
- Serenity/serenity.html
Added Nickname and toggle capability between Character Name and Nickname for display on rolls. Added translation routines for earlier sheet versions. Added second SkillStep drop d own menu. Fixed field spacing.
Added Nickname field and action buttons to select Character Name or Nickname for display in rolls.
Added a second Skill Step drop down menu as two rolls are often required.
Added, belatedly, a translation routine for the earlier version of the attributes (e.g. a '4' became a 'd4').
Fixed some field spacings and textbox margins, …
> Serenity: New Features and Bugfixes

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Finally update skills to show specilisations,
- Fix translation issue identified by Jon_joe.
- Seems French has 2 strings translated.  And one exposed a bug
- Add tests for case
- improve code flow.  My JS has improved.
- Add injury string to direcly rolled cripts
- New combat has moved; now in creatures too
- Improve favourite skills buttons and layout
- Remove some spurious nil class descriptions
- RRs can now click on number or die
> RolemasterUnified Official: Skill and other improvements

- D&D_3-5/charsheet_3-5.html
- D&D_3-5/sheet.json
- D&D_3-5/translation.json
Add new option to damage combo 1/2Str+Int
Update authors list
> [D&D 3.5] Update damage options

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
* Term for non-magical progression changed from "None" to "Null."
* Initiative Rolls have been made into /gr rolls to add suspense during combat
* Fixed the CSS that was messed up on spell descriptions. Tags and boxes are now neatly organized
> Table Top Defined - Minor Fix and Change

- Aria/Aria.css
- Aria/Aria.html
The existing sheet was placing almost everything with an absolute location.
I tried to make it a bit more clean
> [Aria] Update sheet to avoid using absolute placement for each field

- aetherial_expanse/aetherial_expanse.html
- Fixes appearance of nbsp space holder.
> Fix nbsp space usage

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Sheet version to 6.  Funny how lots happen at once.
- Force a skill recalculation after update.
- Fix dependancy issue in edit.js: It depends on the skill list.   Can
now edit dynamic specialisations for the new vocational skills.
- Remove some dead code in skills.
- Update similar skills modifier for fixed specialisations.
- Make roll button for dynamic specialisations actually visible.  0
width buttons are really hard to see and click.
> RolemasterUnified Official: Skill specialization fixes.

- Tales Of Argosa/TOASheet.html
- Fixing the logo link once for all
> Tales of Argosa - fixing the logo link once for all

- Low Fantasy Gaming/sheet.json
- changed the legacy option to false in the json file as it fix the same dark mode issue i had on my sheet who is based on this one
> Low fantasy Gaming - Update sheet.json for fix Dark mode issue

- Dark_Heresy/DarkHeresyStyle.css
> [Dark Heresy]: fix rolls for Dark Mode properly

- Rivers_Of_London/rol.html
> Rivers of London - Bug Fix - expert skill two was using expert skill one's roll

- Knight/pug/js/knight.js
> [Knight] Fix bug with Knight NPC Generator

- Ten candles/ten-candles.css
- Ten candles/ten-candles.html
An update to the proportions of the character sheet and an enlargement of the text boxes to make it easier to take notes.
> [TEN CANDLES] Ergonomic update

- StarWars5E/README.md
- StarWars5E/StarWars5E_CSS.css
- StarWars5E/StarWars5E_HTML.html
- Removing SheetWorker Wrong code
- Correcting minor CSS Issue
- Updating README.md
Test game provided : https://app.roll20.net/join/17737343/0TAFzQ
> Star wars 5E : Bugfixes following PR #13282

- Official Savage Worlds/SavageWorldsCharSheet.html
- Fixed an error with unskilled skills on new sheets
- Fixed an error that caused drag and dropped monsters/archetypes that had a modified pace/parry/toughness to not be calculated correctly
> SWADE Official: Fixes calculation errors when dropping

- Monster of the Week Official/sheet.json
Added missing compendium attribute to the sheet.json
> [Monster of the Week] Add compendium attribute to sheet.json

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Stats are now right aligned.
- Fix update for specialised skills.
- RRs:
- now have a box.  Make them standout more.
- Use the pretty name. not the attribute name.
- Number now rolls with modifier.
- Fix an issue causing some characters to have problems levelling up.
- Fixed specialisations show the skill name when rolling.
- Handle knacks for Alchemists.
> RolemasterUnified Official: RR and misc fixes.

- Knight/knight.html
> [Knight] Fix Knight NPC Generator

- BREAK!!/BREAK.css
- BREAK!!/BREAK.html
Change stat page layout.
Change stat button size to fit.
Fix new_items name, changing defauld value to placeholder.
> [BREAK!!] minor feature updates

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Handle a lot more creature weapons, espcially the fan favourite short sword.
> RolemasterUnified Official:  Fix knockback bug and creature weapons

- D&D_3-5/charsheet_3-5.html
Fix Iaijutsu Focus skill label
> [D&D 3.5] Fix Iaijutsu Focus skill label

- MechWarrior 2e/MW2CharSheet.html
fixed bug with drop down menus
- [x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.
> Update MW2CharSheet.html to fix dropdown menu bug

- Rogue Trader Improved/RogueTraderImproved.html
- Rogue Trader Improved/sheet.json
see details below
critical hotfix for the roll template attack property, was missing a "#" along minor adjustments
another attempt at fixing the JSON display, now using proper backslash n
previous pull request json was invalid, i closed and deleted that branch, sorry for the mess
> Rogue trader Improved critical hotfix1

- Naruto d20 Modern/Naruto d20 Modern.css
- updated image links to the ones hosted on roll20's repo
> d20 modern - updated image links

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
Fix a parse error in creatures that was breaking the whole sheet.
> Rolemaster Unified: Fix creature bug

- Rogue Trader Improved/RogueTraderImproved.html
- Rogue Trader Improved/sheet.json
see details below
*Previous hotfix did not fix the roll template due to a minor oversight, this time it should work
*Movement scores formula updated to account for the Size modifier, as reported by user Somnus
*Complete re-write of the instructions part of the JSON file, hopefully this version will look as intended
> Rogue trader improved critical hotfix2

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
* Profit and Loss Tab
* Expanded functionality in inventory. There are now repeating fields for bags/locations
that will allow users to specify where items they
own are.
* titles are being given to many attributes so the name of said attributes can be known easily to players,
> Table Top Defined - New Features added to sheet

- Naruto d20 Modern/Naruto d20 Modern.css
- Naruto d20 Modern/Naruto d20 Modern.html
- logo selection is now an option. settings added to the bottom of the sheet (sheet was updated by accident thinking it was the only D20 Modern sheet.  My bad.)
> Naruto D20 Modern - optional logo and background

- Deathmatch Island/sheet.json
> Deathmatch Island Bugfix - added compendium to sheet.json

- Thirsty Sword Lesbians/sheet.json
Added missing compendium property to sheet.json
> Thirsty sword lesbians - compendium fix for sheet.json

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
* Zebra Striping added to Skill Table
* Many more titles added to attribute inputs
* Added resource fields for abilities lines like Grace
* CSS added and modified to account for new resource fields
> Table Top Defined -- Sheet Update New Features

- Fate/sheet.json
added compendium property to sheet.json file
> Fate - compendium fix for sheet.json

- Stewpot/sheet.json
compendium property added to sheet.json
> Stewpot - compendium property added to sheet.json

- Band of Blades Official/sheet.json
> "Band of Blades" bugfix - Added compendium to sheet.json

- Wilderfeast/src/pug/wilderfeast.pug
- Wilderfeast/src/scss/wilderfeast.scss
- Wilderfeast/wilderfeast.css
- Wilderfeast/wilderfeast.html
- The name of this game is: Wilderfeast
- The publisher of this game is: Horrible Guild
- The name of this game system/family is: Wilderfeast
Frederico of Horrible Guild asked that the color of the STYLE radio buttons be changed to orange to match the system colors.
I've also updated the images to use this repo instead of a personal repo (oopsie).
> Wilderfeast—STYLE/ASSET update

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Also known as the Author is an Idiot bugfix release for Treasure Law.
- Allow drops from all magic item types
- Save descriptions for all items (even new format)
- Funky line as you lose hits or PP
- Fix a maneuver penalty error which was messing up item drops
> RolemasterUnified Official: Item fixes for Treasure Law

- StargateSG-1/Readme.down
- StargateSG-1/StargateSG-1.html
-Fix Balance, Climb, Open Lock, and Xeno-Languages skills, not rolling because of bad values.
> StargateSG-1 - Bugfix

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
Dec 12th 2024 v1.74a
- Fix for Conditions not working
> [Warhammer 4e Character Sheet] v1.74a - Fix for conditions

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
* Die-type input fields have been changed to selections to simplify use
* Added a Resource field to the abilities so it's easier to mark when an ability uses a resource instead of per-day
* Many CSS changes made to make spell and ability cards pop more
> # Table Top Defined - New Features and adjustments

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Edit talents so you can delete excess talents (@major havok)
- Genericise the code used by edit spells and edit talents
- Fix rendering of side panel after CSS breaks roll20
- Set status penalty to 0 on creature creation.
Orthogonally the first round of superior items is now in the compendium. Additionally a number of improvements to other magical items.
> RolemasterUnified Official: Minor fixes

- Ten candles/ten-candles.html
- Ten candles/translation.json
A minor update to the character sheet to update the RollModifier based on the language the player is using.
> [TEN CANDLES] Rollmodifier Dynamic translation

- Lames du Cardinal v2/lames_cardinal.css
- Lames du Cardinal v2/lames_cardinal.html
- Lames du Cardinal v2/src/abstracts/variables.sass
- Lames du Cardinal v2/src/components/nstatebox/nstatebox.pug
- Lames du Cardinal v2/src/components/nstatebox/nstatebox.sass
- Lames du Cardinal v2/src/components/profile/profile.pug
- Lames du Cardinal v2/src/components/widgets/widgets.pug
- Lames du Cardinal v2/src/components/widgets/widgets.sass
- Lames du Cardinal v2/src/modules/1-personnage/personnage.pug
- Lames du Cardinal v2/src/modules/1-personnage/personnage.sass
- Lames du Cardinal v2/src/modules/2-competences/competences.pug
- Lames du Cardinal v2/src/modules/2-competences/competences.sass
- Fix broken Images due to an error in the base URL
- Add missing "Valet" profile
- Add notes textareas for special Fencing and Occultism skills
- Improve ticks visibility in health swordbar
> [Lames du Cardinal v2] Fix broken images and missing profile and slight improvements

- Knight/knight.css
- Knight/knight.html
- Knight/pug/js/_functionsWeapons.js
- Knight/pug/js/library.js
- Knight/pug/js/rolls/pj/art.js
- Knight/pug/js/rolls/pj/bard.js
- Knight/pug/js/rolls/pj/berserk.js
- Knight/pug/js/rolls/pj/combatAutre.js
- Knight/pug/js/rolls/pj/combatContact.js
- Knight/pug/js/rolls/pj/combatDistance.js
- Knight/pug/js/rolls/pj/combatGrenade.js
- Knight/pug/js/rolls/pj/combatImprovise.js
- Knight/pug/js/rolls/pj/druid.js
- Knight/pug/js/rolls/pj/monk.js
- Knight/pug/js/rolls/pj/priest.js
- Knight/pug/js/rolls/pj/ranger.js
- Knight/pug/js/rolls/pj/recuperation.js
- Knight/pug/js/rolls/pj/simple.js
- Knight/pug/js/rolls/pj/wizard.js
- Knight/scss/files/_library.scss
- Knight/translation.json
> [Knight] Fix visual bug & roll bug

- Scion/Scion.html
The button for the "Command" skill didn't worked, fixed
The button for the "Medicine" skill worked but send a error message each time you used it, fixed.
The "Maximum Legend Points" display, it displayed a squared value the "Current Legend Points", instead of the "Legend" value, fixed, nom show the correct max legend point value
870 : removed the "e" character from the 'attribe' that caused the …
> Bugfixes [Scion 1e]

- Cloudbreaker_Alliance/cloudbreaker_alliance.css
- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Adding a button next to the turn speed field. This button rolls turn speed and adds your initiative to the turn tracker (if a token is selected)
> [Cloudbreaker Alliance] feature adding init tracker button

- Lames du Cardinal v2/lames_cardinal.html
- Lames du Cardinal v2/package.json
- Lames du Cardinal v2/src/components/nstatebox/nstatebox.pug
- Lames du Cardinal v2/src/init.js
- Lames du Cardinal v2/src/lames_cardinal.pug
+ Fixed bad values in swordbar
+ Added version hidden field to manage future update
> [Lames du Cardinal v2] Fixed bad values in swordbar and added version field for future updates

- Shadow of the Weird Wizard/shadowoftheweirdwizard.html
Fixed loss of data in Coin field added value=""
Fixes bug where players data in Coins is lost between sessions
> BUGFIX shadowoftheweirdwizard.html

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
The Maybe a release.. and maybe not a release release.  Not sure if this will got out on Christmas Eve.
- Fix a bug where "Clear Saved" breaks level up
- Remove some dead code in level up - should be a trivial smidge faster.
- Discover the 'actions-test' was not being called - re-enable and fix errors
- Fix bleed so you don't bleed straight after being hit
- Remove 'fantasy' fallback font to see if it is causing rdanhenry's issue
> RolemasterUnified Official: Minor pre-Christmas bug fixes.

- StarWars5E/StarWars5E_CSS.css
- StarWars5E/StarWars5E_HTML.html
- StarWars5E/src/css/legacy.css
- StarWars5E/src/css/main.css
- StarWars5E/src/gulpfile.js
- StarWars5E/src/package.json
Added compatibility to older browser by "unesting" the css in the gulpfile
> [Sw5E] - Add compatibility for older browsers

- ProjectMoonTRPG/ProjectMoonTRPG.html
Bugfixes:
- Fixes AutoEffects for Bleed and On Action ailments not applying correctly when the ailment decays as part of the same action
> [Project Moon TRPG] Bugfix

- Vast Grimm/vastgrimmsheet.html
- Vast Grimm/vastgrimmstyle.css
NPC sheet section was not retaining description details; fixed (added relevant attr_).
Bio & info avatar display was hiding the image, for some reason; fixed (changed div z-index).
> [Vast Grimm] minor bug fixes

- HeroSystem6eHeroic/HeroSystem6eHeroic.html
- HeroSystem6eHeroic/README.md
Version 3.83
Updates
•	Changed the attribute "moveVelocity" to "velocity" to simplify compatibility with the script Hero Roller (heroll.js).
•	Created a default state for "targetSelection" for use with getAttrByName() primarily for use by Hero Roller.
•	Updated README to mention improved support for an upcoming version of Hero Roller.
•	Added a reset of "targetSelection" to its default state when the sheet is opened (quality of life).
Fixes: 
•	Fixed an issue where the preference for weapon damage of d6-1 or d3 in ambiguous cases …
> [HeroSystem6eHeroic] Bug fix and updates for support of the Hero Roller mod

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/translation.json
- RolemasterUnified_Official/updates.md
- Custom profession support.
- Documented: https://github.com/nashidau/RMU-Interchange/blob/main/Profession.md
- Improve the styling of buttons & selected
- Update to creatures.  Not so visible to most users as of yet.
- Can now select 'no swap' for stat swaps at creation (@rdanhenry)
- Sort spell lists in charactermancer (@rdanhenry)
- Add 'C' to Urban survival.  C is City/Civilisations.
- Force reset of any background jobs at the start of the charactermancer finish.
- Save powerlevel (@rdanhenry)
- Fix a bug where "Clear Saved" breaks level up
- Remove some dead code in level up - should be a trivial smidge faster.
- Discover the 'actions-test' was not being called - re-enable and fix errors
- Creatures handle @!# and other codes a little better.
- Fix bleed so you don't bleed straight …
> RolemasterUnified Official: Custom Professions and general improvements

- Fantasy-Gits/fantasygits.css
- Fantasy-Gits/fantasygits.html
I've updated the image paths to directly reference the character sheet folder url in roll20. Sorry for the inconvenience.
> Update: Fantasy Gits

- ADnD_2E_Revised/html/components/rolltemplates.html
Fixed the `title` field not being usable because the `allProps()` were taking its value
> Bugfix: Fixed title for 2e default template

- Infinity-2d20/Infinity 2d20.html
Change the Cashflow match to not use personality as rule book states its just a flat 5 +Lifstyle exp+ mod
> Update Infinity 2d20.html

- Fragged-Empire 2E/FraggedEmpire2E.css
- Fragged-Empire 2E/FraggedEmpire2E.html
FraggedEmpire2E.html
Sheet Modification
Added a Reloads section to facilitate tracking of optional Reloads rules
> FraggedEmpire2E.html modification

- Delta Green 2/deltagreen.css
- Delta Green 2/deltagreen.html
- Delta Green 2/deltagreen.scss
- Delta Green 2/src/js/sheetworkers_onclicked.dev.js
- Delta Green 2/src/js/sheetworkers_onclicked.js
- Delta Green 2/src/js/sheetworkers_rolls.dev.js
- Delta Green 2/src/js/sheetworkers_rolls.js
- Delta Green 2/src/js/sheetworkers_versioning.dev.js
- Delta Green 2/src/js/sheetworkers_versioning.js
- Delta Green 2/src/pug/_navigation.html
- Delta Green 2/src/pug/_navigation.pug
feat: repeating sections updated when leveling up
- Fix the default size of the logo, so if the image server stops working, it does not mess up the sheet (currently, the svg image was not loading correctly)
- Change the link to the logo from my repository to the roll20 one (I forgot to update it when I switched from jpg to svg file)
- Leveling up failed skills automatically updated the repeating sections depending on it (I changed `silent` from `true` to `false` in the leveling up script and checked that it does not interfere with …
> [Bugfix] Delta Green by ArcDream

- Pendragon6thEdition/pendragon.css
Fixed the label in the title changing colors in dark mode Fixed the appearance of the shield characteristics for Firefox
Fixed color of tab labels changed in dark mode
Fixed appearance of shield attribute inputs for Firefox
> [Pendragon6E] Small CSS tweaks

- ADnD_1E_Revised/1ESheet.css
- ADnD_1E_Revised/1ESheet.html
- Fixed a z-index bug where the sheet's portrait could overlap other header areas preventing input/access. This only happens if the use URL option is chosen in the sheet settings but no URL is provided.
> AD&D1e - bugfix

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Creature: Handle Level correctly on dropped creatures.
- Dark Mode updates - closer to useful
- Creature layout updates.
- Handle new Shadowworld Cultures
> RolemasterUnified Official: Dark mode improvements and minor fixes

- Rivers_Of_London/rol.html
Fixed a spelling error, added 2 extra expert skill slots and one extra advantage slot.
> Rivers Of London  - Fix a spelling error and add some additional attributes

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/README.md
- Adds a z-index value to the edit-mode item controls to ensure it is displayed above the repeating sections
> [PokemonTabletopAdventures_v3] Bug Fix: Resolves issue with repeating sections

- BREAK!!/BREAK.html
I removed some useless lines in the rolltemplate and replaced the computed::total by computed::roll1.
That way we can hover on the roll and see the dice rolled.
> [BREAK!!] Feature fixing the attribute rolls hover informations

- Deathwatch/Deathwatch.html
Update the message header to warn about impending migration.
> [Deathwatch] Update the message to warn about the impeding migration

- BREAK!!/BREAK.html
Adding sheetworker to automatically update next level required xp
> [BREAK!!] Update adding next level calculation

- Brigandyne 2e édition/brigandyne_2e_edition.html
- Brigandyne 2e édition/readme.md
Fixed handicaps attributes names, fixed one typo, readme update
> Brigandyne 2e edition bugfix

- Cloudbreaker_Alliance/cloudbreaker_alliance.html
Adding a script to auto select tokens, they work sort of like a gauge now.
> [CLOUDBREAKER ALLIANCE] feature connecting spirit token checkboxes

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
Added support for dark-mode in roll template
> ChroniquesOublieesContemporain Version 3.20.0

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
Added support for dark-mode in roll templates
> ChroniquesGalactiques Version 4.8.0

- Storypath/Storypath.html
> Fixing Boons Drag & Drop and Calling Rolls

- solo10 For_the_quest/ftq.html
> Update ftq.html Bugfix

- Draci doupe II/DrD2.css
- silly me replaced stat colors
- blue is not green
> Draci doupe II – HOTFIX wrong stat colors

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
So this is a change in the way the system parses creatures and attacks.  Now we parse (don't implement all; but parse) all attacks in the system.
- Creatures: Validate attacks for all listed attacks.
- Add attack types for all known attacks
- Correctly adjust attack size
- Change display of attack size for creatures.
- Add meditation to character mancer skills.
> RolemasterUnified Official: Updates for creatures.

- ChroniquesOublieesFantasy2/README.md
- ChroniquesOublieesFantasy2/cof2e.css
- ChroniquesOublieesFantasy2/cof2e.html
- ChroniquesOublieesFantasy2/sheet.json
- Added support for equiped armors, shields and helmets
- Added an option to check used abilities point
- Moved abilities path import to a sub-tab in the abilities tab
- Added an icon for each path name to allow importing of abilities text
- Changed DR computation with a base of 2 excepted for Mysiques profiles (3 DR)
- Changed PC computation with a base of 2 excepted for Aventuriers profiles (3 PC)
- Added options to allow forced max values for PV, DR, PC et PM
- Changed the RD field in the NPC sheet
- Enhanced inline-rolls parsing …
> ChroniquesOublieesFantasy2 Version 1.2.0

- Rogue Trader Improved/RogueTraderImproved.html
Set default Armor Points in Combat tab to 0 (leftover code from the DWI sheet)
Best Craftmanship Ranged Weapon Dice selector had dice formula adjusted
NPC initiative bugged fixed (had incorrect attr call)
NPC Hide Details fancy checkbox now has an attr to save its closed state
> Rogue Trader Improved hotfix 2-10-25

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Fix the stupid problem where buying Specialised skills caused them to be duplicated.  Was only with culture ranks! Big thanks for @rdanhenry for helping me nail it down, along with (in no particular order) @adsmalley, @dudimous, @ixs, @grim, @nefrekin, @bambo and probably some others I've forgottem
- Handle multiple criticals from the same attack.
- F-J crits now handled.
- This is a big set of changes through this parsing code
- Designed to also support "additional crits"
- Injury
- Now has tests.
- Support for multiple H (hits) in the same string.
- Adds a 'Z' on hits only attacks
- Handle duplicate any attribute.
- Make the initiative button big and green (@everyone apparently)
- Added 'Class' to creatures;  can search for Class:III creatures now
- Don't set 'workpending' attribute - …
> RolemasterUnified official: Fix level bug and criticals to degree J

- BREAK!!/BREAK.html
Just adding name of Quirks, Abilities and Bonds in chat when rolling description.
> [BREAK!!] fix chat ability display name

- Aria/Aria.css
- Aria/Aria.html
* Fix incorrect and/or broken skill calculations
* Small html enhancement to avoid code duplication
> [Aria] Fix skills calculations

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
- Earthdawn (FASA Official)/sheet.json
> Earthdawn FASA - V342 Bug fixes

- Lex Arcana/LexArcana.html
fixed missing image links on "img src" tags
The "img src" tags were referring to images that no longer exist. I fixed the links to images that are reachable.
> [Lex Arcana] Update LexArcana.html, fixed missing image links on "img src" tags

- Lex Arcana/LexArcana.css
fixed missing image link
I changed the link to the image (the previous one was missing)
> Updated LexArcana.css, fixed the missing background image link

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/sheet.json
- Translated sheet to Roll20 CSE Sanitization standard. No changes to layout or look.
- Fixed problem with Dual wield Situational Bonuses showing in DW rolls when Custom Roll outcome was active on weapons.
> [Warhammer 4e Character Sheet] v1.75a - CSE & minor fix

- Official Savage Worlds/SavageWorldsCharSheet.html
> Official Savage Worlds | Small typo fix

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Add all the specific static manuever tables from Core Law. Thanks to @grim5352 for the tables.
- Add shield bash to known attacks
- Start of Uses counting: Count use of normal skills.
- Fix specialisation bonus - Use 0 ranks or highest - 25.
- Reneable initiative buttons.  Actions buttons need to have type 'action'.
- Fix specified crits
- Add F->J & X,Y specified crits too
- Add Fate Points - Just a simple text box (@coreylpierce)
- Fix for creating specialised skills during levelup.
- (Creature Law) Update parsing of crit reduction and other resistances.
- The name of this game system/family is: <   > _(i.e. …
> RolemasterUnified Official: Manuever table and little fixes

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn - ED V343

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/sheet.json
- Fixed alignment issue with coin swap buttons
- Fixed Weapon settings Magical Effects textarea sizing
- Fixed Spell Quickbar header spacing
- Fixed problem with Wounds calc not being correct if Larger the Average sized and changes to SB/TB/WPB where made. Only Race change will automatically reset Size and recalculate wounds.
- Updated Sheet.json to add some of the recent custom setting defaults
> [Warhammer 4e Character Sheet] v1.75b fixes

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/modifiers.js
- Palladium Rifts by Grinning Gecko/src/js/utils.js
- Palladium Rifts by Grinning Gecko/src/partials/active.html
- Only copy attributes from Modifiers to the Profile Picker if they have a value.
- Remove Perception from Saving Throws in the Active Profile.
- Fix issue where importing would set the Level Acquired to the current character level.
> Palladium Rifts by Grinning Gecko v1.7.1. Fixes.

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed alignment issue with coin swap buttons, which was not fixed last update.
> [Warhammer 4e Character Sheet] v1.75c fixes

- Cthulhu Dark/CthulhuDark.html
> Cthulhu Dark/CthulhuDark.html // Fixed typo

- Strato Shout/stratoshout.html
The Korean version of the rule book has been officially released and the term has been modified.
Strato Shout/stratoshout.html
> Strato Shout character sheet terms(Korean) update

- TeamSherlock/TeamSherlock.html
Fumction Descript Error Update
teamSherlock Function Descript Error Update
> teamSherlock sheet Update

- Deathwatch/Deathwatch.html
- Deathwatch/sheet.json
Updated .json file for better instructions display
Added terminator armour variable to force field
Minor title change on Auto-Senses (combat tab)
> Deathwatch (improved) bugfix 2-27-25

- inSANe auto cal/inSANe.html
insane : i18n code attribute error update
> insane : i18n code attribute error update

- Storypath/Storypath.html
- Subsections not being added to the correct master section; Movement Dice and Defense set to ready-only
> Fixing Bugs

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Defenses for creatures on Land, Sea and the Air (and climbing)
- More spells formats for creatures
- Creatures talens now line break.
- Show defense bonus for the dfense dropdown
- Creatures can have shields (with passive dodge too)
- Can now 'refresh' data for creatures.
- Tweak layout of the fancybox so it has less margins on the sides.
- Uses now works with specialised skills - not implemented all over yet
- Track Grace & Spell Trcikery
- Start of Level Up review:  Show stat gains for now.
- Fix use of Total/Ranks/Uses in charactermancer.  Cleans up Dark mode a bit
- Add a usecounttotal; so total number of rolls for a character total
- Show usecount for normal skills
- The publisher of …
> RolemasterUnified Official: Defense and minor updates.

- Rogue Trader Improved/RogueTraderImproved.html
fixed bug on lance damage macro
modifiers on weapons now have parenthesis, to prevent errors with negative numbers
Roll template had duplicate body location entry -deleted-
npc fancy checkbox needed value 1 to work properly
> rogue trader improved hotfix 3/2/25

- NWOD-Mage2e/mage2e.css
- NWOD-Mage2e/mage2e.html
- NWOD-Mage2e/sheet.json
Upon forum request, alterations were made to bring the third column into line with the other two columns
.CSS: added line 35 -> width: 860px;
.HTML: Tweaked tolerances 70% becomes 69% and moved Levels and Boxes titles to new line
There was a GitHub warning "This diff contains a change in line endings from 'CRLF' to 'LF'." which I do not know the severity of. whether it needs to be addressed.
> NWOD-Mage2e: Bugfix

- Godbound/Godbound.css
- Godbound/Godbound.html
- Godbound/README.md
- Godbound/sheet.json
Sheet upgrade from legacy to CSE with darkmode compatibility
Multiple changes have been made to the HTML and CSS to fulfill the requirements of the upgrade from Legacy to CSE. There is some inconsistency because of my novice-level coding skills, but it works.
Chekboxes are now wrapped in labels, tab selectors have some new colors, and multiple new lines in the CSS have been added for darkmode compatibility.
> Godbound CSE Update and Darkmode Compatibility

- Apocalypse Keys/ApocalypseKeys.css
- Apocalypse Keys/ApocalypseKeys.html
- Addressed an issue with a translation function (only affected character creation)
- Addressed a bug with the scrollbar preference setting.
Thanks go to Paul Doyle for identifying the issues and fixes.
> [Apocalypse Keys] Small bugfixes

- Strato Shout/stratoshout.html
some sentences was changed
Some error senteces was changed.
Strato Shout/stratoshout.html
> Strato shout terms update

- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn FASA )- EDV344 - Bug Fixes

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Lots of tracker updates.  Still not ready for primetime (but should not break anything)
- Basic layout
- Notes field
- Refresh
- Othermod/parrymod now on the creature sheet
- Sync othermod/parrymod
- New combat clears othermod and parrymod.
> RolemasterUnified Official: Tracker WIP, minor fixes.

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/bonuses.js
- Palladium Rifts by Grinning Gecko/src/js/combat_skills.js
- Palladium Rifts by Grinning Gecko/src/js/utils.js
- Palladium Rifts by Grinning Gecko/src/js/wps.js
- Palladium Rifts by Grinning Gecko/src/partials/options.html
- Fix import race condition that caused WPs and Combat Skills to be duplicated in the Modifier Picker.
> Palladium Rifts by Grinning Gecko v1.7.3. Fix.

- DreamsAndMachines/Dreams and Machines.css
- DreamsAndMachines/Dreams and Machines.html
> [Dreams and Machines] new features and minor fixes

- Fate/FateOmni.css
- Fate/FateOmni.html
Added some responsive layout stuff to the CSS so the sheet displays well at narrower widths (which is mobile friendly), plus some workarounds to deal with the fact that Roll20's mobile/companion app doesn't actually use any of the translation support attributes and functions.
> [Fate] Responsive layout and mobile app workarounds

- Apocalypse Keys/ApocalypseKeys.html
Sheetworker changes to address some bugs in the how the checkbox handler works for the sheet. Also put in some better protections against translation errors.
> [Apocalypse Keys] Bug fixes for checkboxes and translation errors

- DreamsAndMachines/Dreams and Machines.css
- DreamsAndMachines/Dreams and Machines.html
added drop downs on origin archtype and temperament
made archtype goal, exhaustions and attitude text area
fixed some typos
> [Dreams and Machine] New func

- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Features:
•	Added vehicle noncombat move option of 1x (i.e., no noncombat move).
Bug fixes:
•	Fixed typo errors in weapon damage dice calculations.
•	Fixed an issue with optional capped damage and strength damage modifiers.
> [HeroSystem6eHeroic] Bug fixes. Added missing noncombat move of x1.

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Add whisper toggle - GM or Public
- Add whisper toggle to basically every roll in the game
- Tracker:
- Add a return to charactersheet
- Send skill data (not shown yet).
> RolemasterUnified Official: Whispers and Tracker updates

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
- Earthdawn (FASA Official)/sheet.json
> Earthdawn FASA - EDV345 New Charcater Report

- Rogue Trader Improved/RogueTraderImproved.html
*Replaced SB+TB selector and label for automated script
*Minor visual adjustment to reduce clutter
> Rogue trader improved patch 3-15-25

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Tracker now shows skills correctly.
- Creature Law: Template for Encounter Tables
- Creature Law: Finish template for creatures
- Treasure Law: Add will stat bonus
- RRs: Swap the two RR rolls to be consistent with other stuff
- RRs: Fix use of sub attributes
- Skills; Fix uses for skills with specialisations in level up
- Uses:
- Taking injuries tickles a use of 'bodydevelopment'
- Casting a spell tickles a use of 'powerdevelopment'
- Total uses >= Current uses (for new ones)
- Display correct global counter for uses.
> RolemasterUnified Official: Tracker and Uses updates

- Forbidden_Lands/Forbidden_Lands.css
- Forbidden_Lands/Forbidden_Lands.html
- just a small min-width adjustment to the logo
- removed some commented code
> Forbidden Lands

- DreamsAndMachines/Dreams and Machines.css
- DreamsAndMachines/Dreams and Machines.html
I have fixed the weapons rolls and the main and default rolls of NPCs
> [Dreams and Machines] fix on NPC rolls

- HeXXen-1733-2E/hexxen2.html
- HeXXen-1733-2E/sheet.json
Malus dice were added twice, this PR fixes it.
> HeXXen 1733 2E: bugfix for the malus dicepool assignment

- dcc_official/dcc.css
- dcc_official/dcc.html
- Fixes the starting action die
- Fixes display error that caused lucky section to display above rollable tables
> DCC Official: Fix zero level action die

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Fix for the stat abbrievations used in skill summaries
- Add test too
- Spell message nits:
- Remove the trailing . in the PP message
- Fix unbalanced brace in message for grace
- Uses; clear per level count on level up
- Skills:
- forEachSkill has a completion callback
- Remove old (unused) purchase module
- Was used before we had Compendium integration.
- Generate default tokens for creatures
- Incorporate talents in talent file for Creature law.
- Delete all references to Werewolves in the code.
> RolemasterUnified: Where i hunt bugs and wolves

- Storypath/Storypath.css
- Storypath/Storypath.html
- Fixes a crash that occurred while rolling initiative and the `again` value was rolled (default 10)
- Fixes display of multi part template output when the multipart output falls across the avatar display
> Fix initiative crash

- Table Top Defined/Table_Top_Defined.css
- Table Top Defined/Table_Top_Defined.html
- Inventory fields for location and name swapped
- Typo in an attr has been fixed
- Antiquated gold attr was hidden but not removed
- Contains better spacing
- field descriptions added to header
- Antiquated gold field hidden but not removed. ## Advanced Attacks  
Features added to Advanced Tab:
- Twin Talon
- Crack Shot
- Deadly Assault
- Slow Penalty is now correctly being taken out of rolls it applies to
> # Table Top Defined - Update Bug Fixes and new features added

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/migrate.js
- Palladium Rifts by Grinning Gecko/src/partials/options.html
- Fix missing quote on "Output ISP/PPE/Damage usage to chat" attribute.
> Palladium Rifts by Grinning Gecko v1.7.4. Fix.

- Godbound/Godbound.html
- Godbound/README.md
Misc Effort Spent added to Effort Spent in the Resources section for easier auto calculation.
> Godbound adjustment to calculation of Effort Spent

- Storypath/Storypath.css
- Storypath/Storypath.html
> Assorted bug fixes

- Rogue Trader Improved/RogueTraderImproved.css
- Rogue Trader Improved/RogueTraderImproved.html
Optimized scripts with the insight of the Omnisiah (chatGPT)
Updated Insanity Points section, including scripted "degrees of madness"
Updated Corruption Points section, including scripted "degrees of corruption"
Added simple dice roll next to gm rolls
Updated the Armour Points section to include a checkbox for Bionic limbs + visuals
Added new Armour Equipped section with fields for Power Armour augments
Fixed bug on NPC melee macros
Added 1d5 to the scatter diagram
Updated multi-hit macro based on feedback and more logical allocation
Added a toggle section for Notes in the skills tab
Replaced "Fancy" buttons with the Improved Baleine version
Total Wounds are now auto-calculated
Removed Vehicle tab, now vehicle statistics can be found in the Combat tab
*The reason for this is to reduce …
> Rogue Trader Improved Rev7 part 2

- Table Top Defined/Table_Top_Defined.html
> [!WARNING]
> [!NOTE]
- The Profit and Loss sheet makes sense again. Memo and Debit were swapped around 
- Focus advanced attack added to the weapon cards.
> [Table Top Defined] New Feature: Focus button added

- Storypath/Storypath.css
- Storypath/Storypath.html
> Fixing capitalization

- Farsight RPG Community Edition/sheets.css
- Farsight RPG Community Edition/sheets.html
- Farsight RPG Community Edition/translation.json
> [Farsight RPG Community Edition] Fixes to repeating section and condition textarea

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
So this is a lot of little bug fixes from various sources. First is an update to consistant use the same name for the injury and status penalties everywhere.  Now they actually work (and to roll20 staff; they are derived, they will get fixed next time someone ends their turn, so no need to migrate them)
A fix to make crit rolls all work, a stupid typo for Healers casting spells, you can manually remove stun effects.
Background updates include some tweaks to treasure law equipment... and all of Creature Law creatures are now ready to rumble.
- Fix some typos in the skill roll messages.
- Fix crit roll lookups.
- Fix subtle penalty Channeling/Mentalism.
- Status and Injury penalty names were sometimes inconsistent.
- Move to statuspenalty and injurypenalty everywhere.
- Transitory data, so …
> [RolemasterUnified Official] Bugfix: Misc fixes to status, crit rolls, and others.

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
> [!WARNING]
> [!NOTE]
- Adds a table of contents to the HTML file to enable easier browsing
- Adds a range label to move roll templates to enable easier recognition of the range of …
> [PokemonTabletopAdventures_v3] New Feature: Adds range label text to move roll templates

- Farsight RPG Community Edition/sheets.css
Repeating sections overflow now works correctly
> [!WARNING]
> [!NOTE]
If you are submitting a new sheet …
> [Farsight RPG Community Edition]Hotfix to repeating sections overflow

- ProjectMoonTRPG/ProjectMoonTRPG.html
> [ProjectMoonTRPG] Bugfix: Community icons not displaying correctly in ailment update messages

- DreamsAndMachines/Dreams and Machines.css
- DreamsAndMachines/Dreams and Machines.html
Fixed the reroll on the NPC Weapon
Also improved all the Weapon rolls to automatically use Might for melee type weapons and Quickness for Ranged.
> [!WARNING]
> [!NOTE]
Please complete …
> [Dreams and Machines] fixed NPC Weapon reroll

- A Song of Ice and Fire/SIFRPNew.css
- A Song of Ice and Fire/SIFRPNew.html
- A Song of Ice and Fire/sheet.json
Fixes and changes were made to the A Song of Ice and Fire sheet in response to a forum post,  https://app.roll20.net/forum/post/12223469/asoiaf-character-sheet-minor-fixes 2Feb2025. Changes were made to 1) increase description field sizes, 2) swap two variables to match description and 3) fix army buttons and expand to ‘Add’ armies. This last change blew up the code as it’s legacy and the 50 some odd autocalc fields stopped working. So, more extensive changes were made to convert autocalc to sheet workers.
An attempt was made to reach out to Alex-O (3241579), in both English and French, to confirm the validity and integrity of the changes,  25Feb2025. No response has been received.
> [!WARNING]
> Failure to complete this checklist in its entirety will result in your …
> A Song of Ice and Fire: Bug fixes/New Feature

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
This weeks release features
- Typo updates
- Display current status as the current impacting status
- Update stun/stagger/etc status immediately
- Separate updating status end ending turn.
- Update status after injuries are applied immediately
- Fix a bug where you could only bleed once per turn.
- Creature
- Default tokens for all Creature Law 1 Creatures Thanks to Grim!
- Display and Implement Crit Immunities.
- Sorry to players
- Inventory
- Add placeholders for weapon materials
- Work on item edit (not complete - code changes, but no user visible changes)
> [!WARNING]
> [!NOTE]
> Draft Pull …
> RolemasterUnified Official: Instant status updates and various bug fixes

- Fallout PnP 4.0/Fallout PnP 4.css
- Fallout PnP 4.0/Fallout PnP 4.html
> [!WARNING]
> [!NOTE]
- [ X ] The pull request title clearly contains the name of the sheet I am editing.
- [ X ] The pull request title clearly states the type of change I am …
> [Fallout PnP 4.0] Visuals and bug fixes from last patch. No new features are added.

- Demon Hunters Beta/DHRPGtabs.css
- Demon Hunters Beta/DHRPGtabs.html
- fix roll template typo that was breaking the roll template.
- added some higher specificity to the CSS because roll20's base style was causing issues.
- fixed image urls from relative to actual.
> [!WARNING]
> [!NOTE]
Please format your pull request in the following way: `[Sheet Name] Change Type: Description`. For example: `[D&D5e] New …
> Demon Hunters Beta - small fix for roll template

- Fallout PnP 4.0/Fallout PnP 4.css
- Fallout PnP 4.0/Fallout PnP 4.html
> [!WARNING]
> [!NOTE]
- [ X ] The pull request title clearly contains the name of the sheet I am editing.
- [ X ] The pull request title clearly states the type of change I am …
> [Fallout PnP 4.0] Visual fixes, bug fixes

- WTA5e/WTA5e.html
Corrected (hopefully) the URLs for the images to include the WTA5e folder
> [!WARNING]
> [!NOTE]
If you …
> Werewolf the Apocalypse 5e (WTA5e): Bugfix

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
Somehow pasted some spurious sets which are causing a failure.
> [!WARNING]
> [!NOTE]
If you are …
> RolemasterUnified Official: Fix for edit skills/stats not working

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Lots of small fixes to injuries and general improvements to send
inventory materials (crystal, silver, magic) through the to the
defender.
(Note: Not sure why my branch shows Rsoko76 changes).   They are empty however?
- Inventory
- Fix for items not saving strength (thanks @nlbsanarak)
- Persist and restore materials correctly
- Start saving DB bonus for Armor and OB for Weapons
- Style all the drop downs
- Weapons
- Add attack table
- Add attack size
- Add attack skill
- Manually aded weapons now populate attack table
- Materials no longer joined by ','
- Fix for null pointer error during version update.
- Force a version bump to 9 to run it again.
- Attacks
- Make layout a little clearer - bold ftw
- Add materials interface
- Edit materials
- Add additional crit field
- Use fancy …
> RolemasterUnified Official: Updates for Attacks and Inventory

- ChroniquesOublieesFantasy2/README.md
- ChroniquesOublieesFantasy2/cof2e.css
- ChroniquesOublieesFantasy2/cof2e.html
- ChroniquesOublieesFantasy2/sheet.json
> Chroniques Oubliees Fantasy 2e Version 1.5.0

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Midweek release for something different.
- Inventory
- Allow saving of Armor again
- Show notes when editing
- Attacks
- Toggle appearance of additional crits correctly
- Persist extra crit, and allow it to be edited
Note again there seems to some spurious commits.  Not sure what is going on there.
> [!WARNING]
> [!NOTE]
Please format your …
> Rolemaster Unified Official: Bugfix for saving Armor and Items

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Updates the 1/combat move frequency option to 2/combat to match the rulebook
> [PokemonTabletopAdventures_v3] Chore: Updates move frequency to match rule update

- Storypath/Storypath.css
- Storypath/Storypath.html
> Fixing Antagonist Drag & Drop and sheet width.

- Dresden Files Role-Playing Game/DFRPG.css
- Dresden Files Role-Playing Game/DFRPG.html
- Dresden Files Role-Playing Game/src/css/buttons.css
- Dresden Files Role-Playing Game/src/css/components/powers.css
- Dresden Files Role-Playing Game/src/css/roll-templates.css
- Dresden Files Role-Playing Game/src/html/character/powers.html
- Dresden Files Role-Playing Game/src/html/roll-templates.html
- Bugfix : Add "talk" hover button to allow tablet to select the power and open/close the settings
- Improvement : Moved the icons to the right (Follow the sheet flow)
- Improvement : Roll template for power is improved, using the available space better.
> [Dresden Files RPG] - Improved Powers

- d20age/d20age.css
- d20age/d20age.html
> Fix - [d20age RPG] adjusting the seet's header, auxiliaries list, and descending armor class

- d20 Modern/d20 Modern.css
- d20 Modern/d20 Modern.html
- Fixed repeating custom skill button text to a readonly span to make clicking the button easier
- added a tooltip gear icon to help indicate when there is a form-fillable tooltip available. 
- Updated some skill button text to show the custom name in use. Craft, Knowledge, Perform, Read/Write Lang, and Speak lang
- Changed default ability for the Swim Skill to Strength
- added a skill category label and highlight for multi-skills
- updated Profession skill to allow custom entry
> [!WARNING]
> [!NOTE]
> If you are unclear about any of the rules regarding the creation of character …
> D20 Modern - couple fixes by request

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Creatures now go down at 0, not -1
- Save Item strength correctly (I hope)
- Fix encoding of Essence's Perceptions
- Fix some partial block errors.
- Dropping a Creature on a character won't turn you into a character (Major__havoc)
- Fix some attack messages.
> [!WARNING]
> [!NOTE]
Please format your pull request in the following way: …
> RolemasterUnified Official: Creature & Other Bug fixes

- Naruto d20 Modern/Naruto d20 Modern.css
- Naruto d20 Modern/Naruto d20 Modern.html
- since this sheet is based on the D20 Modern sheet's code, I've added a few updates to match what was updated on the D20 Modern sheet this week.
- Fixed repeating custom skill button text to a readonly span to make clicking the button easier
- added a tooltip gear icon to help indicate when there is a form-fillable tooltip available.
- Updated some skill button text to show the custom name in use. Craft, Knowledge, Profession and Misc. Repeating Skills
- added a skill category label and highlight for multi-skills
> [!WARNING]
> [!NOTE]
> If you are unclear about any of the rules …
> Naruto D20 Modern

- Estirpe de Dunwich/Estirpe-de-Dunwich.css
- Estirpe de Dunwich/Estirpe-de-Dunwich.html
> [Estirpe de Dunwich] Correction and New Feature: Corrected CSS, Added automated checking for tracker

- FIST/FIST.css
- FIST/FIST.html
Trying to accommodate perceived differences between Custom Sheet and Production environments
> [!WARNING]
> [!NOTE]
Please complete this section if you are adding a new sheet to the …
> [FIST] Bug fix: Fix for rendering differences

- Doctor Who 2e/DoctorWho2e.css
- Doctor Who 2e/DoctorWho2e.html
Nora had offered feedback that roll results should/could be added, so they have been added.
> [!WARNING]
> [!NOTE]
Please complete this section if you are adding a new sheet to the …
> [Doctor Who 2e] New Feature: Difficulty and Roll Result

- FIST/FIST.html
In trying to accommodate differences between Production and Test environments regarding inheritance, a wrong URL was used.
> [!WARNING]
> [!NOTE]
Please complete this section if you …
> [FIST] Bug Fix: URL change

- Estirpe de Dunwich/sheet.json
> [Estirpe de Dunwich] Uploaded correct JSON (Legacy = false)

- Doctor Who 2e/DoctorWho2e.html
- Doctor Who 2e/translation.json
Missed SuppressDifficulty phrase in last upload. Also, updated roll-template to have translation capability.
> [!WARNING]
> [!NOTE]
Please complete this section if you are adding a new …
> [Doctor Who 2e] Bugfix: Updated translation.json

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.css
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.css
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/bonuses.js
- Palladium Rifts by Grinning Gecko/src/js/definitions.js
- Palladium Rifts by Grinning Gecko/src/js/import_export.js
- Palladium Rifts by Grinning Gecko/src/js/magic_psionics_abilities.js
- Palladium Rifts by Grinning Gecko/src/js/migrate.js
- Palladium Rifts by Grinning Gecko/src/js/profiles.js
- Palladium Rifts by Grinning Gecko/src/partials/active.html
- Palladium Rifts by Grinning Gecko/src/partials/magic-summary.html
- Palladium Rifts by Grinning Gecko/src/partials/magic.html
- Palladium Rifts by Grinning Gecko/src/partials/options.html
- Palladium Rifts by Grinning Gecko/src/partials/psionics-summary.html
- Palladium Rifts by Grinning Gecko/src/partials/psionics.html
- Palladium Rifts by Grinning Gecko/src/partials/repeating_modifiers_readonly.html
- Palladium Rifts by Grinning Gecko/src/partials/roll-templates.html
- Palladium Rifts by Grinning Gecko/src/rifts.html
- Palladium Rifts by Grinning Gecko/src/scss/rifts.scss
- Add "Refresh All Profiles" button.
- Add Range, Duration, Frequency, Damage, DC, and Skill to Modifiers.
- Add Frequency to Magic, Psionics.
- Add rollable attribute checks to Profiles, including D20 + Attribute, D20 + Attribute Bonus, D20 Under Attribute, and D100 Under Attribute.
- Fix issue where spell strength was not being calculated correctly.
> [Palladium Rifts by Grinning Gecko] v1.8.0. Features/fixes: See Changelog.

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.css
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.css
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/migrate.js
- Palladium Rifts by Grinning Gecko/src/partials/options.html
- Palladium Rifts by Grinning Gecko/src/rifts.html
- Palladium Rifts by Grinning Gecko/src/scss/rifts.scss
- Make Active Profile checkboxes look like radio buttons.
> [Palladium Rifts by Grinning Gecko] Style Change: Make Active Profile checkboxes look like radio buttons

- The Aethyrblood Chronicles/aethyrblood.html
Autocalculated value for the Traits:
Bearing = awareness + manipulation.
Glamour = appearance + charisma.
> [THE AETHYRBLOOD CHRONICLES] Update: Autocalculated value for the Traits Bearing and Glamour

- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.css
- Official_100DOS_Mythic_by_100DOS/100DOSMythicUpdated.html
> Official_100DOS_Mythic_by_100DOS Fixed image links

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/import_export.js
- Palladium Rifts by Grinning Gecko/src/js/magic_psionics_abilities.js
- Palladium Rifts by Grinning Gecko/src/js/migrate.js
- Palladium Rifts by Grinning Gecko/src/partials/options.html
- Palladium Rifts by Grinning Gecko/src/rifts.html
- Fix issue where new Modifiers damage field overwrites Ancient: Damage with 0.
> [Palladium Rifts by Grinning Gecko] Urgent Fix: Fix issue where new Modifiers damage field overwrites Ancient: Damage with 0.

- Moonshine/moonshine.css
> [!WARNING]
> [!NOTE]
Change some white things in black things.
> [Sheet Name] Fixing Things : Dark Mode Issue Fixed

- Shadowrun Sixth World/Shadowrun6thEdition.html
> Shadowrun Sixth World - Bugfix: Fix nuyen symbol

- Gundam-Mobile-Suit-RPG/Gundam-Mobile-Suit-RPG.html
> [Gundam-Mobile-Suit-RPG] Major Update, fix RollTemplate

- Earthdawn (FASA Official)/Earthdawn.html
- [ X] The pull request does not, _without express prior permission from affected parties_, include any material that could be considered to infringe on a Publisher's intellectual property rights, such as logos, images, rules text or other rules content.
If you are submitting a new sheet to the repository, please fill in …
> [Earthdawn FASA] - EDV348 - Bug fixes and a few new functionalities for TI

- Rogue Trader Improved/RogueTraderImproved.html
*Fixed Manifest psy powers macro
*Upgraded some ship macros to avoid positive modifier problem
*Updated psy powers template for simplification
> [!WARNING]
> [!NOTE]
Please complete …
> Rogue Trader Imrpoved Patch 6-14-25

- FIST/FIST.html
- FIST/translation.json
The min issue is that none of the four attributes are being added into Die Rolls..
> [!WARNING]
> [!NOTE] …
> [FIST] Bugfix: Attribute not being added to Die Roll

- WTA5e/WTA5e.html
- WTA5e/sheet.json
Added three additional custom rolls based on user request. Fixed bug where Insight was referencing Etiquette, and removed some commented out code
> [!WARNING]
> [!NOTE]
Please complete …
> [WTA5e] New Feature: Three Additional Custom Rolls

- Cyberrats/Cyberrats.css
Added a row of null cell grid spaces to the relationship grid IF briny bastards and space are both enabled.
> [Cyberrats] [Bug fix] Expand relationship grid to not overlap scars in Firefox

- Gestalt/GestaltSheet.css
- Gestalt/GestaltSheet.html
Added Oaths section.
Added Magic Items section.
Added Initiative roller and Turn Tracker integration, with calculations. Fixed minimum width to account for Traits section. Fixed calculation of Unaware AC.
Deleted Shields from armor proficiencies since they aren't a separate category. Added tooltips to some elements.
> [!WARNING]
> [!NOTE] …
> [The Gestalt RPG] New Features and Fixes

- ChroniquesOublieesFantasy2/README.md
- ChroniquesOublieesFantasy2/cof2e.css
- ChroniquesOublieesFantasy2/cof2e.html
- ChroniquesOublieesFantasy2/sheet.json
> [Chroniques Oubliees Fantasy 2E] Version 1.6.0

- D6pp_Wild_West/d6ppww.html
> [!WARNING]
> [!NOTE]
- [ x] The pull request title clearly states the type of change I am …
> D6++ Wild West  - Fixed Revive and some incorrect data

- inSANe auto cal/inSANe.html
Reverts Roll20/roll20-character-sheets#14135
Code error occurred. I'll look into it more...
> Revert "[inSANe] html code changed"

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Pre-Birthday release!
- Fix versioning past version 7
- Fucus -> Focus
- Mental Fatigue/Endurance:
- Calculate the value
- Add a die roll button
- Update feats of strength
- Async (Internal)
- Add a warning if code double calls the async procedures.
- Discover there are literally hundreds of places it's called.. *sigh*
- Inventory:
- More async of methods to make sure we don't double call
- Attacks:
- Make one attacks update async
- Skill updates all linear now (no double calls, should be faster)
- Update DB is now async
- Errors
- Keep an error count, and fix formating of last errors.
- Arcane realm stat
- Basic TP support
- Creatures now set fields bars correctly:
- Green: HP
- Blue: PP
- Red: Status (total penalty)
- Tracker can now target creatures (not super useful yet)
> [!WARNING] …
> RolemasterUnified Official: Bug fix and minor features.

- D6pp_Wild_West/sheet.json
> [!WARNING]
> [!NOTE]
- [ x] The pull request title clearly states the type of change I am …
> D6++ Wild West - updated to new compendium short name

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
It's the rare Thursday RMU update. Enable token actions for attacks and fix a few little bugs.
Thank you all for the bug reports.
- Fix old 'condole.log' problem with ranged weapons (alpinecowboy)
- Fix ranged weapon penalties applying to everything (!)
- Send weapon attacks for creatures in order
- Fix partial block not being set (Major Havoc & others)
- Enable Primary/Secondary attack token actions
- Enable End Turn token action
- Add Initiative token action too.
> [!WARNING]
> [!NOTE]
> If you are unclear about any of the rules regarding the creation of character sheets, or …
> RolemassterUnified Official: DB, Attacks and Token Actions

- PokeVenture/sheet.json
Added "Legacy" line to JSON file for Legacy Sanitization.
> [!WARNING]
> [!NOTE]
If you are submitting a …
> Updated JSON file for Legacy Sanitization for existing PokeVenture sheet.

- A Song of Ice and Fire/SIFRPNew.html
Formula for Sprint calculation has finally been nailed down. And, as a bonus, a bug that had been lying in wait was found and corrected.
> [!WARNING]
> [!NOTE]
Please complete this …
> [A Song of Ice and Fire Roleplay] Bugfix:: Sprint

- Thorgal/Thorgal.html
- Thorgal/translation.json
While the QuickStart has Unarmed Combat, the manual has Intimidate, and the requestor pointed out that Brute Force + Finesse are the two options of Unarmed Combat
> [!WARNING]
> [!NOTE] …
> [Thorgal] Bugfix: Replace Unarmed Combat with Intimidate

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Adds a button to collapse and expand all skills when the skills section is expanded
- Adds action scripts for setting all the flag attributes to on or off
- Updates the dark mode colours for the hovered skill buttons and skill totals to have a better contrast value for accessibility
> [PokemonTabletopAdventures_v3] New Feature: Collapse/Expand All Skills

- Stewpot/Stewpot.css
- Stewpot/Stewpot.html
- Stewpot/translation.json
Previously there was no option to pick "custom" for an adventurer or town job, nor was there a text field so you could *name* your custom job if you decided to craft one. This is now addressed.
> [Stewpot] Custom job support (new feature)

- olddragon2e/olddragon2e.css
- olddragon2e/olddragon2e.html
If you are submitting a new sheet to the repository, please fill in any empty spaces indicated by [  ].
- The name of this game is: [   ]  
> _(e.g. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: [   ]  
> _(e.g. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: [   ]  
> _(e.g. Dungeons & Dragons, FATE)_
- The rules for this game can be found at the following location: [   ]
> _(e.g. a link to purchase, ISBN, Half-Price Books)_
Select EXACTLY One:
Add monster tab functionality and enhance …
> [Old Dragon 2e] New Feature: Add monster tab functionality and enhance character sheet layout

- D6pp_Wild_West/d6ppww.html
> D6++ Wild West - fixed spelling mistake

- When The Wolf Comes/wtwc.css
Fixed Image Path
> [!WARNING]
> [!NOTE]
If you are submitting a new sheet to the repository, please fill …
> [When The Wolf Comes] Bugfix: image path correction

- Imagine/sheet.json
This is the 4th attempt to check in the Imagine Role Playing Official Sheet. It has been minified down to 16.713MB from the original of 20.279MB. I have included the original with this per Roll20 request though obviously you won't be checking it in.
> [!WARNING]
> [!NOTE]
[Imagine Role Playing Official Sheet] (Minified version)
Please format …
> Imagine Role Playing Official Sheet Minified

- MarvelSH/MarvelSH.html
- updated the initiative roll to add a linked token to the tracker as per user request
> [!WARNING]
> [!NOTE]
Please complete this section if you are adding a new sheet to the …
> Marvel Super Heroes (MarvelSH) - updated initiative roll

- Farsight RPG Community Edition/sheets.css
- Farsight RPG Community Edition/sheets.html
> [!WARNING]
> [!NOTE]
NPC Actions now have details to fill and roll button
> [Farsight RPG Community Edition]Added npc actions details and roll button

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/translation.json
- RolemasterUnified_Official/updates.md
- Display bonus when using 2 handed weapons
- Add RRs for Arcane
- Creature Skill roll updates
- Use the specific table when we can
- New UI for critical rolls
> [!WARNING]
> [!NOTE] …
> RolemasterUnfied Offical: Bug fixes and UI improvements.

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
> [Chroniques Oubliées Contemporain] Version 3.21.0

- Moonshine/moonshine.css
- Moonshine/moonshine.html
New functionnality
> [!WARNING]
> [!NOTE]
If you are submitting a new sheet to the repository, please fill …
> [Moonshine] Moonshine Update

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Fix parrymod and other(ob)mod for creatures
- Show aptrack (the AP box) in the 4th box
> [!WARNING]
> [!NOTE]
Please complete this section if you are adding a new sheet to the …
> RolemasterUnified Official: Fix creature parry & content for bubble4

- TheExorcistCodex/translation.json
> [!WARNING]
> [!NOTE]
I've delete some useless options in the translation.js base file and make some correction on it
> [TheExorcistCodex] Update Translation.js

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
> RolemasterUnified Official: BugFix: Fix missing attack mods for PCs

- Blood_and_Doom_by_Dicetale_Games/bloodanddoom.css
> Updating Blood & Doom by DiceTale Games

- Rogue Trader Improved/RogueTraderImproved.css
- Rogue Trader Improved/RogueTraderImproved.html
- Rogue Trader Improved/sheet.json
- Rogue Trader Improved/translation.json
RTI Rev.8 part 1 "Do you speak Eldar?"
This update is to lay the foundation for the insertion of the translation keys, i will split this work in several parts to test as i go, several small modifications will be added to reduce/remove redundant text, so as to reduce the overall translation key list, thus making less time consuming to translate.
* Added Translation.json file with a few keys inserted
* New Tooltip icon (question mark)
* CSS classes updated
* Modified Simple Dice into a simple 1d5
* Placed wiki "link", rev tag and an icon reference in a new footer div
* Fear and Shock buttons were merged
* Trauma Test and Table buttons were merged
* Reorganized Psychic power related buttons and fields
* Added Focus Mod field for fixed Focus Power tests
* Rearranged Vehicle fields to mirror …
> Rogue Trader Improved Rev.8.1 update

- Shinobi_Gami_Chinese_Traditional/ShinobiGami.html
Some Strategy changed into Strategy_field
> [ShinobiGami] Specialty field name error update

- Frontier Scum/frontierscum.html
> [!WARNING]
> [!NOTE]
The wanted status ('dead or alive') was not correctly set with an attr_ prefix to allow it to persist across opening/closing sheets. This update should fix that …
> [Frontier Scum] Minor function fix/update: making wanted status 'dead or alive' attribute persist

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Force statuspercent_max to be 100.
> [!WARNING]
> [!NOTE]
If you are submitting a new sheet to the …
> RolemasterUnified Official: Bugfix: Add statuspercent_max at 100

- MageWillvsParadoxSheet/magewillvsparadox.css
- MageWillvsParadoxSheet/magewillvsparadox.html
- MageWillvsParadoxSheet/sheet.json
> Mage Will vs Paradox: format adjustments, rules changes

- D&Z-Apocalypse/DZ-Apocalypse.css
- D&Z-Apocalypse/DZ-Apocalypse.html
AC calculation fixed
> [!WARNING]
> [!NOTE]
> [DZ Apocalypse] Fix AC Calculation

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/partials/active.html
- Fix issue where Possession roll button was not working.
> [Palladium Rifts by Grinning Gecko] v1.8.5. Fix Possession save bug.

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/translation.json
- RolemasterUnified_Official/updates.md
- First version of token markers (thanks for @shuvuul)
- Sheet options
- Random colours
- Trigger on status change.
- Fix stacking of popups on main page
- Add helper to get total number of bleeds
- Add options for token makers
- Add options for FX (doesn't do much)
- Export to NPC now grabs spell lists.
- Inventory (Stuff)
- Fix Helmet perception penalty trashing other modifiers
- Apply Armor DB
- Removed Armor DB & Perception penalties when you remove items
- Fix for armor losing it's encumberance.
- Add support for "Sets" Armor without a helmet
- Add armor material to edit window
- Correctly support mixed material encumberances (metal != non-metal)
> [!WARNING]
> Failure to complete this checklist in its entirety will result in your Pull Request being dismissed. …
> RolemasterUnified Official: Token makers and Inventory updates

- Hollow_Knight_Unofficial_TTRPG/HKRPG.html
> [!WARNING]
> [!NOTE]
- [ x ] The pull request title clearly states the type of change I am …
> [Hollow Knight Unofficial RPG] New Feature: Tab Cycling

- Draw Steel/draw-steel.css
- Draw Steel/draw-steel.html
> [!WARNING]
> [!NOTE]
Select EXACTLY One:
> Found some Darkmode switching that slipped through the cracks. They should all be fixed now
> [Draw Steel] Darkmode bug fixes

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Validation
- Support Body,Head,Arms,Legs format for AT
- Validate attack sizes for creatures
- Stuff: Fix error in itemmaterial not saving
- Levelup:
- Don't try and levelup current_level/new_level
- Spell lists show the group in summary
- Recreate previous skill ranks correctly
- Misc: Make one of the errors more verbose
- Spells: Fix display of mixed armor penalties
- calculation was correct, display showed culmulative error
- Create: fix highest message for stat creation (@ixs)
> [!WARNING]
> [!NOTE]
> If you are unclear about any of the rules regarding the creation of …
> RolemasterUnified Official: Levelup Bugfixes/Optimisations

- ASHDOM_CharacterSheet/ASHDOM_CharacterSheet.html
> Skills Bug Fix - ASHDOM

- anime5e/anime5e.css
- anime5e/anime5e.html
> [!WARNING]
> [!NOTE]
Changes to the roll20 character sheet of Anime5e (Version 02/10/2025)
- ADDED A ADVANTAGE/DISADVANTAGE BUTTON
This allows to chose between …
> [ANIME 5E] New Features detailed in the description

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
And squash a lot of logging and get rid of the multi pending issue for base lists
> [!WARNING]
> [!NOTE] …
> RolemasterUnified Official: Renenable Base Lists during levelup

- Scion/Scion.html
> [Scion] New Feature: Roll buttons follow now actual game rules

- Strato Shout/stratoshout.html
> [!WARNING]
> [!NOTE]
same as title. it changed as a public name.
> [Strato Shout] table name changed

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Updates skill roll formula when turning skill checks on or off to correctly add the ball modifier
- _Slightly_ optimises the capture modifier calculation by not recursively calling it
- Adds call to the capture modifier calculation to update the displayed values when changin the default custom modifier
- Updates skill and inline-skill roll templates to determine which label to show
- Adds new attribute to track numeric value of the show skill roll flag for captures
> [PokemonTabletopAdventures_v3] Bug Fix: Resolves issue with capture skill check

- PokeVenture/PokeVenture-HTML-Roll20.html
Just updating some default values to 0 instead of 1.
> [!WARNING]
> [!NOTE]
If you are submitting a new …
> [PokeVenture] - Making a Minor HTML Change: Updating some default values to "0" instead of "1".

- Perils and Princesses/Perils.html
In haste to try to fix img elements by transitioning from 'links' to 'locations' (as suggested by support), only part of the change was implemented. This (hopefully) finishes the job.
> [!WARNING]
> [!NOTE]
Please format your pull request in the following way: `[Sheet Name] Change Type: Description`. For example: `[D&D5e] New Feature: Adding …
> [Perils and Princesses] Bugfix: Attempt to fix img elements
