Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Default Advantage for NPCs on Primary attribute 1 & 3 fixed
- Was the same attribute name, fixed so each seperate
=> [Open Legend] NPC default Advantage fix

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
[Fixing my own issue #3797](https://github.com/Roll20/roll20-character-sheets/issues/3797)
=> Changed 5e OGL to process decimals in carrying capacity.

Godbound/README.md
This is a complete redesign and overhawl of the Godbound sheet to resolve several issues. There was sufficient desire from the community for me to publish my work, as shown in this forum post: https://app.roll20.net/forum/post/6269089/new-godbound-sheet/?pageforid=6514817#post-6514817. I also received the original author's blessing to publish this new sheet and replace his work.
=> Complete Redesign

Barbarians Of Lemuria - Mythic/bolm.css
Barbarians of Lemuria - CSS fixes
=> Barbarians of Lemuria - CSS fixes

Free Spacer/FreeSpacer.html
Changed Gender stratagy to Sex Stratagy
Changed Manipulators from # field to text line
Removed unexpress accents from Melee
Added zero line associations
removed home port from associations
Fixed Supply and Complex material from part of a tonne to a tonne per unit
=> Fixed bugs in layout, text, and options

D&D_4E/D&D_4E.css
Making adjustments to the CSS for Template output to Chat for D&D 4e
Character Sheet.  Added values for the template table padding.
=> [D&D_4e Character Sheet] CSS Adjustments for Template Table in Chat

inSANe auto cal/translations/ko.json
=> Error Code Fixed

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html, 5th Edition OGL by Roll20/translation.json
* updates Discard and Exit subtext for better clarity
* adds instructions for Feat Prerequisites
=> Clarifies text to Discard and Exit, Prerequisites

inSANe auto cal/inSANe.html, inSANe auto cal/translations/ko.json
inSANe - Transition Code Modify
=> inSANe - Transition Code Modify

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Quick Fix of layout due to Roll20 Char-o-mancer update changing default padding/spacing for all charactersheets across the site
- Next update should be v2.0 of sheet with improved layout and borders (might be awhile)
=> [Open Legend] Layout fixes from Roll20 update

Cyberpunk 2k20/Cyberpunk 2k20.html, Cyberpunk 2k20/sheet.json
Completed (as far as I can tell) spellchecking and translating fiddly bits from french to english
=> Cyberpunk 2k20 spellcheck/translation

TailsOfEquestria/GruntFile.js, TailsOfEquestria/js/worker.js, TailsOfEquestria/less/colors.less, TailsOfEquestria/less/fields.less, TailsOfEquestria/less/icons.less, TailsOfEquestria/less/main.less, TailsOfEquestria/pug/explodingHooves.pug, TailsOfEquestria/pug/fields.pug, TailsOfEquestria/pug/index.pug, TailsOfEquestria/sheet.css, TailsOfEquestria/sheet.html, TailsOfEquestria/sheet.json
Includes:
* visual/layout improvements
* Reputation section (uses rules from MLP Movie Sourcebook)
* API integration for Exploding Hoof rolls.
=> Tails of Equestria v1.4

The Veil/TheVeil.css, The Veil/TheVeil.html
Added section for Veil 2020 hack
=> Updated The Veil Character Sheet

The Veil/TheVeil.css, The Veil/TheVeil.html
split bipolar emotion spike meter into two separate meters (radio
buttons)
=> The Veil - Fixed emotion Spikes in 2020 version

D6StarWars/D6StarWars.css, D6StarWars/D6StarWars.html, D6StarWars/README.md
**Layout:**
- Made wound tracker wider
- Force section minor adjustments
**New Feature:**
- Under Force skills, space for powers and their roll buttons added
=> [Star Wars D6] V.1.70

RunequestGQS/ReadMe.md, RunequestGQS/RunequestGQS.html, RunequestGQS/sheet.json
=> Runequest Glorantha

Free Spacer/FreeSpacer.html
1. Altered on sheet Damage numbers for greater clairity.
2. Changed the title of a section from Archaic tools to Stuff for greater flexibility/playablity. Did not alter the related attribute.
3. Removed redundant field from letter of Marque. Field doesn't effect play or sheet functionality.
=> Updated information displayed on sheet

Tales from the Loop/TFTL css.css
=> [TFTL] FIX padding in roll template

13th Age Official/13th_Age_Official.css, 13th Age Official/13th_Age_Official.html
CSS fix following Roll20 update.
=> 13th Age Official layout fix

Mutants and Masterminds 3E/mutants-and-masterminds.html
Added support for 2 alternate dice mechanics: The 3d20 take middle version from the Gamemasters Guide and a 3d6 method.
=> Added Alternate Dice

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
adds sheet whisper setting to charactermancer rolls
=> Nw mancerfixes

MarvelSH/MarvelSH.html, MarvelSH/sheet.json
Updated character sheet for additional output to chat on rolls.  This is in preparation for an API script I want to write to use that to get color roll results (based on Ability Name and its Value (Rank Number)).
=> Updated to v1.1.0

Shinobi_Gami_Chinese_Traditional/ShinobiGami.html
=> shinobi Gami

Wrath and Glory API/wrath_and_glory.css
Minor change to header and wrapper.
=> Update Wrath and Glory API

Wrath and Glory API/wrath_and_glory_api.html
Minor cleanup of html with label change.
=> Update Wrath and Glory HTML

TormentaRPG_Tabbed/TormentaRPG_Tabbed.html
Corrected the positioning and spacing of most skills and miscellaneous text in the sheet.
=> Formatting corrections

Weaverdice/README.md, Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html
- fix Health tracker, doesn't reset any more
- added "Stat modifier" lable over stat placement, for clarity
- made "notes" textfields in gear& other repeating sections wider
- made most large textboxes smaller
- some visual corrections
- code cleanup, removed duplicate code& some renaming
=> [Weaverdice] V.1.0

CthulhuTech_1ed/CthulhuTech_1_ed.html
Cthulhu Agility Fix, plus styling update
=> Cthulhutech Agility Fix, plus styling update

CthulhuTech_1ed/CthulhuTech_1_ed.css
=>  Cthulhutech Agility Fix, plus styling update

Deadlands Classic/deadlandsclassic.css, Deadlands Classic/deadlandsclassic.html
Deadlands updates per [Community Request](https://app.roll20.net/forum/post/6670162/deadlands-classic-slash-20th-anniversary-sheets)
* Deleted the old obsolete data. This has been in a tab warning it would be deleted for months. Finally Deleted it.
* Updated the weapons section to optimize repeating fields. Moved the old layout to the Obsolete Data section. The old repeating fields were working anyway so this shouldn't be hurtful. 
* Fixed the CSS.
=> Deadlands: Updates per Community Request

ShadowrunAnarchy/SR Anarchy.html
* Strength was always used as first modifier.
* Added a "None" option in the dropdown to allow for untrained skill use
=> ShadowrunAnarchy - Fixing attribute roll error

The Veil/TheVeil.css, The Veil/TheVeil.html
Added increased and decreased rolls for Veil2020
=> Updated The Veil

CWOD-W20/W20.html
- Athletics added as a combat skill option
- Changed the display name of "Other" in roll dropdowns to "OtherTrait" for clarity's sake
=> [Werewolf 20th] Combat options fix

Ars_Magica_5th/Ars_Magica_5th.css
Attempt at fixing a display issue.
=> Ars Magica 5th: Fix repeating field buttons

Weaverdice/README.md, Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html, Weaverdice/sheet.json
- skill rolls added with minor options
- expanded skill description text field
- set default stat modifier to zero
=> [Weaver Dice] V.1.2

D6StarWars/D6StarWars.css, D6StarWars/README.md
=> [Star Wars  D6] V.1.72

Wrath and Glory API/readme.md, Wrath and Glory API/sheet.json, Wrath and Glory API/wrath_and_glory.css, Wrath and Glory API/wrath_and_glory_api.html
Updates to HTML, CSS, readme, and json files.
Note this is a significant update to all files.  Version 1 of the character sheet was based on 28 pages of rules from a quickstart release.  This release is based on the core rulebook (452 pages).  The changes resulted in significant addition of content (nearly doubled in size) and a reorganization of existing content,   No existing attributes were changed or deleted; this was anticipated when the character sheet was created based on the quickstart rules.
=> Wrath & Glory v2 release

Weaverdice/README.md, Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html
- fix skill rolls added in V.1.2. Added option for using stat bonus and skill bonus to rolls,plus a field to custom the roll. Default "k1" keeps highest dice
- Stat value added above the stat modifier
- adds sheet version in the corner
- hearts and dice changed to red
=> [Weaverdice] V.1.32

Mass Effect/Mass Effect.html
There was a problem with weapon rolling system. I tried something, but we'll see if it fixed the problem.
=> Patch Mass Efect

NWOD-Mage2e/mage2e.css, NWOD-Mage2e/mage2e.html
Mostly stolen from the NWoD official sheet, with some minor styling changes to better match the rest of this sheet. Sheet worker copies damage from the old boxes to the new ones first time the sheet is opened.
=> NWoD Mage2e: Improved health track with single row of cycling boxes.

WOIN/WOIN.html
These are my attempts to improve the WOIN character sheet as I described in issue #4080. The changes are not yet complete. I've mostly made the changes that seemed easiest, from a scripting perspective.
Next up are the status tracks.
I'd also like to go back and add "Roll" buttons for each of the Movement and Defenses fields, so they can be broadcasted to chat. I've held off for now because I fear that will break their formatting (or at least require more changes to the sheet layout).
While I'd like to improve the Attacks section as well, that will be much more complicated than the fixes I've made so far.
I've not tried to tackle the formatting issue in #4079, which I think is being fixed separately by the sheet's original author @CoalPoweredPuppet.
=> Improvements to WOIN character sheet

Urban_Shadows/style.css
For an urban shadows game, we want to modify the default font and background of the inline roll to fit the tone of the game from the comic font and blank background.
=> Formatting text and background inlineroll image

Ars_Magica_5th/Ars_Magica_5th.html
Needed to add in some parenthesis in the combat formulas so that operations weren't solving as strings.
=> Ars_Magica_5th: Fixing combat formulas

Warhammer40KWrathNGlory/Warhammer40KWrathNGlory.css
=> Re-create Warhammer40KWrathNGlory.css file

Urban_Shadows/style.css
Adding drop shadow to the roller text boxes as well as including an animated BG.
=> Re-Beautifying the Urban Shadows In Line Roll Template

Atomic Highway/Atomic Highway.html
Updating health boxes, added sheet workers, minor styling change
=> Atomic Highway

RunequestGQS/ReadMe.md, RunequestGQS/RunequestGQS.html
Fixed Category mods for stats over 20
=> Runequest Glorantha Fixed Category mods for stats over 20

AD&D_1E/1ESheet.css, AD&D_1E/1ESheet.html
- max title text on equipment was wrong. changed to  @{repeating_equipment_$X_quantity|max}
- max attribute on repeating_ability changed from max to current_max in order to work with |max syntax for tokens.  Included sheet version check sheet worker to copy old max attribute data to current_max.
- fixed alignment issue with the repeating equipment fields and the column headers.
=> AD&D1e - fix 

Weaverdice/README.md, Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html
- **fixed skill rolls to display correct skill name when rolled**, previously showed name of the first skill
=> [WeaverDice] V.1.33

Mutants and Masterminds 3E/mutants-and-masterminds.css
Please if you want to make a new color scheme find a way to make this an option rather then making it a default 
as very off shade of orange as it hurts to look at the sheets as they are now
=> Mutants and Masterminds 3E: Unpeached the sheet

GURPS/gurps.html
•	Fixed Encumbrance Table calculations to always allow for a Minimum Move of 1 and a Minimum Dodge of 1.
=> [GURPS] Fixed Encumbrance Bug

Pathfinder Playtest/PFPlaytest.css, Pathfinder Playtest/PFPlaytest.html, Pathfinder Playtest/translation.json
Version 0.011536670800 changelog:
- max dex will now actually affect your ac/tac (syntax for mods field is X max dex to armor, e.g. 3 max dex to armor)
- Signature skills selection has been removed per the [errata 9/10/18|http://paizo.com/community/blog/v5748dyo6sg8r?On-the-Road-to-Sombrefell-Hall]
- Perform is now a discrete skill
- I'm still working on further improvements to the lag situation, if you have further input on causes, or times when you notice it, please let me know
=> Pathfinder Playtest v0.011536670800

Knight/knight.html
I made a mistake on the image of the sheet, it cannot be displayed. I'm correcting that.
=> [Knight Sheet] Various Small Fix

WOIN/WOIN.css
Fixing attribute alignments and button css
=> Woin CSS uPDATE

Weaverdice/CHANGELOG-Weaverdice.md, Weaverdice/README.md, Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html
- Roll Templates added (blue, red, green, black versions of the default template)
=> [Weaverdice] V.1.40

Ars_Magica_5th/Ars_Magica_5th.css
Trying to fix the css for the Add button.
=> Repeating Field Button Fix

Shadowrun2e/ReadMe.md, Shadowrun2e/shadowrun2e.css, Shadowrun2e/shadowrun2e.html, Shadowrun2e/sheet.json
- change roll button icon to d6
=> [Shadowrun 2E] visual fix

vampire-v5/README.md, vampire-v5/vampirev5.css, vampire-v5/vampirev5.html
Coterie/Character tab now fixed from left, to avoid issue where resizing screen would make it unclickable.
Fixed issue with CoterieMeritsAndFlaws not showing.
Renamed Advantages to Merits for consistence.
=> Vampire 5e: Bug fixes

Mongoose_Traveller2e/MongooseTraveller.css, Mongoose_Traveller2e/MongooseTraveller.html
Added repeating sections for Armour and Weapons.
=> Repeating Sections

Tagmar/tagmar.css, Tagmar/tagmar.html
Macro selector added to the charsheet, in the combat tab.
=> Tagmar. Update in combat tab

Pathfinder Playtest/PFPlaytest.css, Pathfinder Playtest/PFPlaytest.html, Pathfinder Playtest/translation.json
- Typed Penalties not being added to rolls
- Perform was not using charisma as it's ability score for rolls
- Perform was not an initiative option
- Untrained proficiency is now -4
=> Pf playtest v0.011537880400

Pathfinder Official/Pathfinder Official.css, Pathfinder Official/Pathfinder Official.html, Pathfinder Official/translation.json, Pathfinder Official/translations/en.json
Pathfinder by Roll20 v1.17 beta 2
=> Pathfinder by Roll20 v1.17 beta 2

Torg Eternity/README.md, Torg Eternity/Torg Eternity.html
Adding uniform changes to sheet that allow mods to attributes and skills.
=> Torg Eternity: Version 3.0

Tagmar/tagmar.css, Tagmar/tagmar.html
Small improvement in the charsheet appearance.
=> Tagmar. Small changes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> D&D 5e by Roll20: Improved Global Fields

D&D_BECM/BDnDSheet.html, D&D_BECM/sheet.json
Fixed Skill rolls, ability rolls, saving throws to show the target for the roll and the actual roll.
Fixed attack rolls where they wouldn't work with negative modifiers
Also made the inventory auto-calculate totals of encumbrance for individual items and individual tabs.
Added rolls for turn undead in addition to the gm whisper
Changed two thief abilities to checkboxes since those are static %
=> [D&D_BECM]

Torg Eternity/Torg Eternity.html
Fixed missing fields for Name, Race, and Home Cosm from last update. Also fixed minor formatting error on Other Skills header.
=> Torg Eternity - Fix Missing Fields

Villains and Vigilantes/VandVMightyProtectors.html
- Corrected spelling
- Changed terminology to be more understandable
- Changed dice roll buttons to be behind the field they are impacting and not in front.
=> Update Villains and Vigilantes/VandVMightyProtectors.html

Knight/knight.html
- Fix for a bug with Armor Druid in Reaction & Defense for Wolf and Lion (value change / autocalc change)
=> [Knight]Bugfix Druid

Hitos/hitos.css
=> (HITOS) Update hitos.css

Hitos/hitos.html
=> (HITOS) Update hitos.html

Metal Adventures/MetalAdventures.css, Metal Adventures/MetalAdventures.html, Metal Adventures/sheet.json
- Add a sheet for ship
- increase some fields (experience, weapon distance)
=> Metal Adventures

Lames du Cardinal/ldc.html
Several items were not at their correct location. Reworked layout.
=> Update Lames du Cardinal/ldc.html

Knight/knight.css, Knight/knight.html, Knight/sheet.json
I have corrected several things:
- The way several effects are managed (Chambre Double, Munitions Non Létales), ensuring that what was to be updated automatically.
- Some texts have been corrected
- Fix template
- Add Tab "Vehicule" and "Equipage"
- Add Sheet "Vehicule"
- Add Template "Vehicule"
- Add my Tipeee in sheet.json
- Bugfix in Ranger's Longbow (bugfix for effect "silencieux")
=> [Knight] Update & Bugfix

Qin Warring States/Qin.html
replace the </option>...</option> by <option>...</option> as it should always have been
=> [Quin] correct a bug in the <select> of weakness

inSANe auto cal/inSANe.css, inSANe auto cal/inSANe.html, inSANe auto cal/translations/ko.json
- Title of Character info area textbox, Position change
- Item box Position change : Plot bottom
- GM Message box Delete : Many bug when use.
- Title style : padding-top:3px; (CSS Line:170)
=> Avocado : inSANe auto cal

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Bio slide updates

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- Set comp_age to be a text input to max the charsheet input
- Remove unnecessary min
- Per QA, remove the warning about race change from the Bio slide. It now only appears on the Review aka summary slide. Going to the Bio slide will update the previous_race aka clear the warning.
=> Update warning per QA. Change Age to text input

inSANe auto cal/translations/ko.json
Translate Error modify
- Translate Error modify
=> Translate Error modify

Metal Adventures/MetalAdventures.css, Metal Adventures/MetalAdventures.html, Metal Adventures/sheet.json
- fix css : (increase some fields, decrease others)
- add missing fields
- fix uniq attr name
=> Metal Adventure 2.5

GURPS/gurps.html
Version 1.4.5 – PULL  11/13/2018 - Successful
•	Fixed version 1.4.1 Pull request Date – Cosmetic Only
•	Fixed version 1.4.2 Pull request date – Cosmetic Only
•	Fixed version 1.4.3 Added back in – Cosmetic Only
•	Fixed version 1.4.4 Renumbered from  1.4.3 – Cosmetic Only
•	Renamed ‘Skils’ tab to ‘Skills’ – Cosmetic Only
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to …
=> [GURPS] Fixed History on Updates page v1.4.5

Shadowrun5thEdition/Shadowrun5thEdition.html
- Corrected the goon script. 
- Fixed commenting
- Changed Accuracy to text
=> Shadowrun5thEdition V1.2 fixes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Updates for the levels slide. Still a work in progress.
=> Levels updates, incomplete

GURPS/gurps.css, GURPS/gurps.html, GURPS/sheet.json
Updated the authors list in the sheet.json file
=> [GURPS] Updated authors list:, Combat page reformatted sheet.json, GURPS.css, GURPS.html

FFD20/README.md, FFD20/ffd20.html
Undead characters now are supported. Created toggle at the top of the page to change Fortitude and hit point calculations from using Con to Cha. added is-undead attribute to accomplish this.
made a few small changes to quotation marks based on errors VSCode was complaining about.
changed ac-armor-maxdex to using parseInt cause maxdex should never be a fraction.
=> FFD20 undead character support

Jojo's Bizarre Tabletop/JJBTT.css, Jojo's Bizarre Tabletop/JJBTT.html
- Adjusted the spacing on the character sheet for the traits/flaws section
- Fixed a bug preventing the stand name from displaying on the sheet
=> [Jojo's Bizarre Tabletop] Quick fixes

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.css, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
*ChroniquesOubliees*
* Tried to change one table into div
* Added tabs to gain some space
* Added the possibility to see 3 more "Voies" in the capacity tab.
=> ChroniqueOubliees: added tabs and removed some tables.

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Average hp update

RunequestGQS/ReadMe.md, RunequestGQS/RunequestGQS.html
Typos and starting skill values fixed.
Add ability to add extra weapons to npc sheet.
=> Runequest Glornatha 

Low Fantasy Gaming/LFGSheet.html
Revved version and maintained unix line feeds.
Updated initiative roller to correctly omit dexterity modifier.
Added spell tracking for each spell level.
None
=> Update Low Fantasy Gaming/LFGSheet.html

Knight/knight.html
- Bugfix for Grenades and Styles
- Typo Fix
*Anything else we should know?.*
=> [Knight] Bugfix

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html, 5th Edition OGL by Roll20/translation.json
Need to add Guildmaster's Guide to the welcome text.
*Anything else we should know?.*
=> D&D 5th Edition - Update charactermancer welcome text

TheWitcher/witchersheet.html
Added additional modifier query on Profession skills, also adjusted spells to not display 0 damage when no damage type is selected, but instead state 'none' in its place.
=> TheWitcher - Additional Features

Scion2e/scion2e.css, Scion2e/scion2e.html
fix Resilience being written Resistance
add Hard Armor option to health levels
=> Scion2e, couple missed bits

Metal Adventures/MetalAdventures.css, Metal Adventures/MetalAdventures.html, Metal Adventures/sheet.json
update version
Merge PJ and PNJ competence for allowing "Initiative macro"
=> Metal Adventure

Rats in the Walls/ratsinthewalls.html
The original fields were defined as att_ instead of attr_. This has been corrected
=> Update ratsinthewalls.html sheet

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> fix spell attack error when moving a character via the vault

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Sets should be working properly on load of the slide now. 
There is an error for a 'includes' when moving to the choices slide. 
Subclasses are still not hiding as they should.
=> fixes for sets in levels

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> inline updates, fixes add/remove buttons

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Fixed the message updates for level changes
The iframe now changes when clicking the 'i' buttons
Changed the headers & moved the hidden attributes
=> update messages, level tots

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
CSS for the Roll & Average buttons
=> CSS updates Average & Roll buttons

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Added flags so the Average & Roll buttons will highlight the one in use. Also set the addhp to Average by default.
=> Average by default, highlight buttons red

Celerity/charsheet_celerity.css, Celerity/charsheet_celerity.html, Celerity/sheet.json
*Skill alignment set to left, instead of center, and I added a floor function to round the 0.5 ranks in the skills to whole numbers.*
*Celerity Character Sheet*
=> Celerity Character Sheet: Fixed skill alignment and calculations, and added roll templates for attack and initiative

Trudvang Chronicles/Trudvang Chronicles.html
Fixed bug with some wilderness value calculating wrong sv
Fixed bug with Vitner description field 3 having wrong attr id
Added two more mother tongue fields and removed readonly from those fields
Only a description field that shared attr name with another description field changed as part of bug correction. As the bug is obvious to users, I will not take any extra measures of communicating this change.
=> [Trudvang Chronicles] Bug fixes

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.css, ChroniquesGalactiques/cog.htm, ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.css, ChroniquesOublieesContemporain/coc.html
Updated Chroniques Oubliées Contemporain (v2.3) and Chroniques Galactiques (v3.2).
This corrects some bugs, and adds vehicle sheets and new resource attributes.
=> Chroniques Oubliées: update of Contemporain and galactique

Knight/knight.css, Knight/knight.html
- Little bugfix for Grenade.
- Visual update for better compatibility with Chrome. (and small visual bug fix)
=> [Knight] Bugfix + Visual Update

Pathfinder Playtest/PFPlaytest.html
- Fix for Saves not showing and attack/damage always showing. The sheet will convert the necessary checkboxes to the new values automatically on load.
=> Pathfinder Playtest V0.011545141600

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Additional fixes for mancerleveler
=> Nwcl mancerleveler fixes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
Fixed collapse & expand css for bylevels
Added comments for Ross
=> updates by level css & add comments

D6StarWars/CHANGELOG.md, D6StarWars/D6StarWars.css, D6StarWars/D6StarWars.html
=> [Star Wars D6] V.1.82

Dark_Heresy/DarkHeresy.html
Added initiative and custom initiative buttons.
=> [Dark Heresy] Initiative buttons

L5R/L5Rsheet.htm
Fixed the typo introduced in last pull. Taking another swipe at the insight bug.
=> L5r 4e sheet

TheWitcher/witchersheet.html
A fix for wound threshold and death state activating incorrectly activating on the number, not below it. Also included are some minor QoL fixes such as font size, query and streamlining changes.
=> TheWitcher - Update- QoL & Bug Fixes

Celerity/charsheet_celerity.html
Changed AC and other title alignment
Changed the alignment of the AC and other titles slightly.
Celerity sheet.
=> Celerity Sheet: Changed AC and other title alignment

New World of Darkness Official/NWoD_Official.css, New World of Darkness Official/NWoD_Official.html, New World of Darkness Official/sheet.json
New World of Darkness Official
Bug fixes:
* Defense now updates when relative stats are changed ("athletics", "brawl", "dexterity", "weaponry", "wits")
* Page 2 repeating section items can be deleted more easily
* Attack roll template not counting results of 8 or 9
* Changing edition now updates attacks to match the edition
=> New World of Darkness Official bug fix

Jojo's Bizarre Tabletop/JJBTT.html
Added what looked like missing brackets to JJBTT.html. Should make it so that setting the character type to just "No Stand" removes the stand rather than any character type
=> Update Jojo's Bizarre Tabletop JJBTT.html

Monsterhearts-2/Monsterhearts-2.css, Monsterhearts-2/Monsterhearts-2.html
Fixed move duplication, added radio button for Ghoul hunger selection
Fixed move duplication, added radio button for Ghoul hunger selection
=> Monsterhearts 2 fixes and addition

Knight/knight.css, Knight/knight.html
=> [Knight] Bugfix Sorcerer

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Misc. Leveler Fixes

WFRP2E-Havoc/wfrp2e-sheet.css, WFRP2E-Havoc/wfrp2e-sheet.html
Tweaks to align the skills list.
=> Warhammer Fantasy 2e (Havoc) Tweaks to skills list

CWOD-V20/V20.css, CWOD-V20/V20.html
- Fixes a number of bugs including those issues found within the Dice section that were simply not functioning at all. The bug was due to the test campaign that was already previously hosting the old sheet did not allow me to spot the issues. Lesson learned and a huge apology again to everyone.
-Moved some tabs and reorganized some sections though it shouldn't have any affect on data as names were not altered in this change, just their location on the sheet.
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us …
=> [CWOD V20] Bug Fixes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Placeholder was spelled wrong
* type="textarea" is not needed
* Spans needed closing
* Added alts to images
=> 5e D&D: fixed html issues

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> fix crash with global save

approved.yaml
Added a few extra tags based on game systems.
=> DEV, 1670 Part of quarterly cleanup

vampire-v5/README.md, vampire-v5/vampirev5.html
Fixed bug in which pushing the Willpower button wouldn't take into account the modifier on Non-API script.
=> Vampire 5th Edition Bug fix

Knight/knight.css, Knight/knight.html
- Bugfix Chrome display
- Bugfix Tenebricide doesn't display
=> [Knight] Bugfix 

Celerity/charsheet_celerity.html
=> Celerity Character Sheet init base value change

vampire-v5/vampirev5.css, vampire-v5/vampirev5.html
Added backgrounds section. Fixed equipement section to function correctly.
=> V5 Character sheet updates

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- Closed Spans in Roll Template
- on change: Saving Throws refactored
- on change: Skills prof, type, bonus refactored
- on change: Global Damage Modifier Flag refactored
- on change: Exhaustion Level refactored
- on change: attribute base, mod, bonus refactored
- on change: repeating_inventory:hasattack & useasresource refactored
=> Cl 5e refactor

Dark_Heresy/DarkHeresy.html
=> Dark Heresy: Added xp Auto cacl

DungeonWorldFrench/ReadMe.md, DungeonWorldFrench/dwfr.css, DungeonWorldFrench/dwfr.htm, DungeonWorldFrench/sheet.json
Dungeon World French v3.5
* Spells repeating section: prepared count bug fix
* Repeating section buttons styling
=> Dungeon World French v3.5

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Cl 5e refactor revert

Knight/knight.html
=> [Knight] Bugfix / Description Update

The-Fade-Tabletop/TFT Sheet.html
Optimization fixes, new sections added, miscellaneous sections added for each skill.
=> Update TFT Sheet.html

The-Fade-Tabletop/TFT Sheet.css
=> Update TFT Sheet.css

Fragged-Empire/Fragged_Empire.css, Fragged-Empire/Fragged_Empire.html
I fixed issue https://github.com/Roll20/roll20-character-sheets/issues/4583, which was due to two field having the same name.
I also fixed some invalid CSS, and applied automatic formatting to the HTML and CSS.
=> Fragged empire vehicle skills bug

Shadowrun5thEdition/Shadowrun5thEdition.html, Shadowrun5thEdition/sheet.json, Warhammer40k-WrathandGlory/WrathnGlory.css, Warhammer40k-WrathandGlory/WrathnGlory.html, Warhammer40k-WrathandGlory/sheet.json
* Bug Fix: modifier, edge, wound buttons
* Included a sheet worker to update them.
=> Shadowrun 5th Edition 1.41, Warhammer 40k Wrath & Glory 1.1

D&D_BECM/BDnDSheet.html
Fix a minor issue due to a typo reported in https://github.com/Roll20/roll20-character-sheets/issues/4682.
=> D&D BECM Fix a typo

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.css, ChroniquesGalactiques/cog.htm
ChroniquesGalactiques:
* Changed the way buffs are treated, we now use natural language instead of a list of buffs
* Automatic translation for buffs from 3.4 to 3.5
* Improved roll templates
* New information capacities
=> ChroniquesGalactique : changed buffs to be parsed in natural language

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Add the new leveler hp changes to staging for testing
=> Cl 1619 hpperlvl

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> 5e HP Per Level

Starfinder Official/Starfinder.html
Rollback of Charactermancer access. Feature is not ready for release at this time.
=> Rollback of WIP Feature

Starcraft RPG/sheet.json, Starcraft RPG/starcraft.html
Fixing bugs with a tab, updating rule changes, and updating the website to the new one
=> Bug Fixes for Starcraft RPG

.gitattributes, .github/pull_request_template.md
- Remove a line in the template
- Enforce LF line endings for specific file types
=> .gitattribute & template update

ChroniquesGalactiques/cog.htm, ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.css, ChroniquesOublieesContemporain/coc.html
Small fixes, mostly aesthetic
Version 2.5, with
* Buffs in natural language
* Some improvements on attacks
* Upgrade of template rolls
* Script refactoring
=> Update ChroniquesOublieesContemporain to 2.5

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Cleaned up the list of listeners for spells
* Simplified the functions for these listeners
* Wrote a helper function to do the same shared task
This is a first step and I believe we can go further in reducing the shared code between these three functions.
=> 5e D&D - DEV 1788 - Spell listener refactor

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- Subclass needs stop adding hp if its set by a "worker"
=> fix for hpperlvl

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> refactored to go faster

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Fixes for Hp Per Lvl

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Fixed for Creature Codex zombies & added !=

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> 5e D&D - DEV 1854 - Cantrip Attack fix

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- Condensed global_${attr}_mod_flag into one function
- Turned remove:resource listener into a ._each to reduce repeating code.
No Attributes were harmed in the making of this.
=> 5e D&D - DEV 1827 - Refactor mod_flag & remove resource

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- npcaction & npcaction-l reduced code for getting repid
- npc_saves & npc_skills lists refactored to use a helper function that utilizes a loop
=> 5e D&D - DEV 1834 - NPC Saves & Skills

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
Adds a Bonus box for the Soak field. The Bear Mentor Spirit gives a Bonus to soak so this is the most appropriate spot.
Also adds the Bonus in the Roll template.
Changed the sheet Shadowrun5th (Advanced). Confirmed working in Roll20
=> Shadowrun5th - Add Bonus Soak box

Naheulbeuk/Naheulbeuk.css, Naheulbeuk/Naheulbeuk.html
- Major source code update : Replace tables and crappy inline css by a light grid system (rows & cols)
- improve spells ui
- minor sheetworker updates
=> Le donjon de Naheulbeuk 2.7

LANCER RPG (1.8)/LANCER.html
Fixed structure and core stress tracks not saving on sheet close.
=> [LANCER RPG 1.8] Fixed structure and core stress tracks not saving on sheet close

PokemonTabletopUnited/ptu.html
Added a field for permanent initiative bonuses.
=> PTU 1.05: Added initiative bonus field

Star Trek Adventures Official/STA_Style.css, Star Trek Adventures Official/Star Trek Adventures Official.html
Star Trek Adventures by Roll20 v1.5
* Bug fix: ship torpedo weapons don't add Ship's Scale to damage
* Feature request: chat roll template now show 0 challlenge dice
* Internal: version upgrade sheet workers
=> Star Trek Adventures by Roll20 v1.5

Call_of_Cthulhu_7th_Ed/translations/ko.json
=> [Call_of_Cthulhu_7th_Ed] Translate Korean

Epyllion/Epyllion.html
Correcting roll buttons : wrong attribute name.
=> [Epyllion] Update Epyllion.html (Correcting rolls)

Knight/knight.html
Fix because of rule's clarifications
=> [Knight] Fix because of rule's clarifications

Call_of_Cthulhu_7th_Ed/coc_7th_ed.html
Just made the Options visible ingame. Fixes everything to the best of my knowlege.
=> CoC_7th_Ed. Quickfix.

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Replaced redundant code with arrays & loops
=> 5e D&D - DEV 1910 - Spells Drag & Drop refactor

Trudvang Chronicles/Trudvang Chronicles.html
Fixed line endings
(( Had some problems with updating the last pull request, so I made a new one. Hope that works for you ))
=> [Trudvang Chronicles] Hot fix for rolling macro

Halo_Mythic/HaloMythic.html
Didnt ACTUALLY fix the bug before
The Recharge bug was made worse re re trying to fix
=> [Halo Mythic] RERE Bug fix

Black_Crusade/BlackCrusade.html
=> Update Black Crusade html

Knight/knight.html
=> [Knight] Fix for Druid's Armor

Call_of_Cthulhu_6th_Ed_French/Call_of_Cthulhu_V6.css, Call_of_Cthulhu_6th_Ed_French/Call_of_Cthulhu_V6.html
* Just adds a simple rolltemplate and update all tests in the character sheet to use it.
=> Call_of_Cthulhu_6th_Ed_French - Add  a rolltemplate

Ryuutama/Ryuutama.css, Ryuutama/Ryuutama.html
Adding a white box around the roll template so you can tell them apart easier. 
=> [Ryuutama] Adding a white box around rolls

.github/pull_request_template.md
* Updating this templated based on user [feedback](https://app.roll20.net/forum/post/7284289/changes-to-the-call-of-cthulhu-character-sheet-what-vetting-process-does-r20-use-to-ensure-radical-updates-are-desired-by-users).
=> GitHub - Updating Pull Template per User Feedback

Low Fantasy Gaming/LFGSheet.html
added default values for Attribute/Max/GS/TF
https://github.com/Roll20/roll20-character-sheets/issues/4835
=> [Low Fantasy Gaming] added default values

Singularity/sheet.json
Added in profile to indicate Singularity's author. Forgot to add to changes on original upload.
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheet …
=> Corrected Sheet Credits

Singularity/Singularity.html
Corrected attribute to attr_drive from attr_culture
If you do not know English. …
=> Corrected attribute to Drive

Godbound/Godbound.html, Godbound/README.md
- Minor changes, spelling corrections and errors resolved.
- Small bug fix of calculation error.
- No attributes changed.
=> Godbound v2.2.0

Ars_Magica_5th/Ars_Magica_5th.css, Ars_Magica_5th/Ars_Magica_5th.html
Correcting bad combat formulas. Putting in default values for Weapon Abilities.
Swapping out imgur links for github images.
=> Ars Magica 5th - Combat Formula fix

Epyllion/Epyllion.html, Mantel dAcier/Mantel dAcier.html
No new features, correcting a roll with wrong attributes.
(Only changes on Mantel dAcier are intentional)
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Chara …
=> [Mantel dAcier] Correcting a roll with wrong attributes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- Update_class removed the hardcoded Switch for Compendium Data
- Updated set_level to use a loop
- Updated console.logs
- If this is a new sheet, did you follow [Building Character Sheets …
=> 5e D&D - UC 310 - Update Class and Set Level

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
- Refactored the update_weight function to be cleaner
- Added in floats per Pull Request #4681 which fixes issue #4562 . THANKS @olivier-grech  :)
- If this is a new sheet, did you follow [Building Character Sheets …
=> D&D 5e - UC 95 - Update_Weight Function

Ryuutama/Ryuutama.css, Ryuutama/Ryuutama.html, Ryuutama/sheet.json
Adding a functional NPC sheet to the basic sheet. This required wrapping things in divs so the changes appear more drastic then they are. Besides minor changes to styling and the roll template, nothing has really changed regarding the player sheet. The bulk of the changes are at the bottom of the html and the css. Highly recommend viewing diff while ignoring whitespace changes.
The NPC sheet itself was made to look like the one in the rulebook. It mostly contains simply number inputs and one larger text area. 
- Does this add functional enhancements (new features or extending existing …
=> [Ryuutama]: Adding NPC character sheet

Starfinder Official/Starfinder.css, Starfinder Official/Starfinder.html
- NPC rolls should all now calculate correctly. Special ability attack rolls were not working correctly. Additionally, critical damage of NPCs for all repeating sections were not calculating correctly.
- CSS fix for misaligned "tot" header in attribute (e.g. strength, dexterity, etc) container.
- Minor CSS change to make sheet header buttons (e.g. equipment or spells) on the pc sheet react to hovering.
=> Starfinder Official v1.011553605200

Shadowrun5th/Shadowrun5th.css
multiple text colors doesn't look nice, also some text colors were barely readable.
though the css needs a serious rework. there's lots of stuff in it where duplicated could be eliminated.
- If this is a new sheet, did you follow [Building …
=> [Shadowrun5th] unified text colors

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Fixed a console log
* Added a console.log to help find NPC spell errors.
If …
=> D&D 5e - UC 353 - Console log NPC Spells

Eirendor/Eirendor.html
Actual and Max PP and PE description was mixed
If you do not know English. …
=> [Eirendor] corrected typo

Shadowrun5th/Shadowrun5th.html
Added Two New Sprite Types
No.
Yes. I added two additional sprite types for use by technomancers.
No.
No.
N/A
N/A
=> [Shadowrun5th] Added Companion and Generalist Sprites

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Update the warning text.
If you do not know English. Please leave a comment …
=> D&D 5e - UC 78 - Deprecated Spells Text

Black_Crusade/BlackCrusade.html
- Revert the changes from #4899 which were untested and broke a number of tabs. …
=> Black Crusade - Fixed BC tabs

Black_Crusade/BlackCrusade.html
-Fixed the intended color code for Degrees of Success and Failure.
-Removed the -1 that was showing the wrong total of Degrees 9/10 times.
=> Black Crusade - minor bugfix

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Folder Rename
- Changing folder name in Roll20 github from "Open Legend Basic by Great Moustache" to "Open Legend"
- When I was a young pup in the game, didn't realize should have named folders better
* Image Updates 2
- Updated all remaining links in preperation for Folder rename
As per conversation on last merge with @clevett : https://github.com/Roll20/roll20-character-sheets/pull/4912#issuecomment-481719057
renamed links to images to be referencing "Open Legend" folder instead of the presently "Open Legend Basic by Great Moustache"
=> Open Legend.html AND Open Legend.css AND Readme.md

approved.yaml
=> Cl uc361 officialsheet

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Fix class saves

Forbidden_Lands/Forbidden_Lands.htm
- Use Wits attribute for Insight
- Use Empathy attribute for Healing
=> Forbidden Lands: Bug fix switched attributes for Insight and Healing

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> Cl uc370 doupdateattack

Rats in the Walls/ratsinthewalls.html
Correction of the roll button Voluntad, because the rolltemplate was showing a different name.
=> Rats in the Walls sheet, roll name corrected

Unisystem-Buffy or Angel/Buffy_or_Angel.html, Unisystem-Buffy or Angel/ReadMe.mdown, vampire-v5/vampirev5.html
Fixes to the Buffy Sheet and updated the user guide for V5.
=> Buffy Sheet Fixes and V5 Update

Sports Brawl by Lost West Media/sheet.json
* Added back some text I removed for troubleshooting.
@LostWestMedia 
Just to keep you update I renamed this folder for easier identification in the repository. I also fixed the issue of the authors not showing up in sheet select. You'll want to update your fork.
Thanks,
Cassie
- If changing or removing attributes, what steps have you taken, …
=> Sports Brawl by Lost West Media - UC-376 - Sheet.json

Cypher Systems by Roll20/cypher_systems_by_roll20.html, Cypher Systems by Roll20/translations/fr.json
Cypher Systems v2.22
translation fixes ( uc-461 )
=> Cypher Systems v2.22

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Fixed an issue with single spell npcs.
If you do not know English. Please …
=> D&D 5E - UC-459 - fix Ravnica's Rakdos

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Refactor the code for update spell from attack
If you do not know English. …
=> D&D 5E - UC-429 - Refactor Update Spell From Attack

Knight/knight.css, Knight/knight.html
=> [Knight] Bugfix for Monk Armor / Silencer

Pavillon Noir 2/Pavillon Noir 2.html
* fix an attribute to have the correct `attr_` prefix in the name
=> Pavillion Noir 2: attribute fix

Ryuutama/Ryuutama.html
Every roll had a roll for bonus that just basically looked like "0+0+0+1+0", which was kind of annoying when you hovered over it because you have no idea where the 1 is coming from. So adding quick little descriptions to the rolls so you can identify what they are.
=> [Ryuutama]: Adding describers to the roll modifiers

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Druid was pulling multiple compendium pages which was causing issues. This will fix it.
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repo …
=> D&D 5e - uc504 - fix the druid select

COPS/COPS.html
=> [COPS] Bugfix

Knight/knight.html
=> [Knight] Fix Druid Armor

Call_of_Cthulhu_7th_Ed/coc_7th_ed.css, Call_of_Cthulhu_7th_Ed/coc_7th_ed.html, Call_of_Cthulhu_7th_Ed/sheet.json, Call_of_Cthulhu_7th_Ed/translation.json
Reverts Roll20/roll20-character-sheets#5086
* Error in the sheet json reverting changes.
=> Revert "[Call of Cthulhu 7th Ed] Adding ''NPC Sheet'' and minor additions."

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Add for QA
If you do not know English. Please leave a comment in your native …
=> D&D 5e - UC-501

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
=> UC-500 for QA

Knight/knight.html
=> [Knight] Fix for Grenade & Guardian & Druid

Gumshoe by Roll20/GUMSHOE.css, Gumshoe by Roll20/GUMSHOE.html
* converted investigative buttons to just text(where considered redundant)
* added input fields to track points for individual covers and networks(doesn't interact with other fields in the backgorund)
* minor code formatting
=> Gumshoe - UC-128 minor fixes

D6StarWars/CHANGELOG.md, D6StarWars/D6StarWars.css, D6StarWars/D6StarWars.html
* remove wound penalties from soak rolls
=> [Star Wars D6] V1.83

LANCER RPG (1.8)/LANCER.css, LANCER RPG (1.8)/LANCER.html
-Re-added accuracy/difficulty toggle, at long last!
-Updated mech autocalc values to match pre-release 2
-Fixed pilot HP input length to account for double-digit HP values
-Fixed rounding errors with HASE autocalc boxes
-Fixed Hull not adding to max repairs at all
-Removed Invocations, re-added Notes box
-Systems modules now have more space for effect description (twice as much!)
-Changed critical and core breach buttons (since those conditions no longer exist)
=> [LANCER RPG] Updates and bugfixes for LANCER Pre-Release 2

Chronicles of Darkness by Roll20/sheet.json
* Clarify in the 'instructions' sections which systems are supported as well as format the text
=> CoD by Roll20:improve sheet.json

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
* Needs a little extra padding for a span used by the API. …
=> D&D 5e - UC-534 - fixed padding for api span

Cypher Systems by Roll20/cypher_systems_by_roll20.css
Adding the font-size fix for the portuguese translation.
=> Portuguese translation CSS fixes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Adding 5e update init refactor
If you do not know English. Please leave a …
=> Fixed uc-501

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> uc-561 add monster drop handling

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Refactor the update initiative function
If you do not know English. Please …
=> D&D 5e - UC-501 - refactor update_initiative

Cypher Systems by Roll20/cypher_systems_by_roll20.html, Cypher Systems by Roll20/translation.json, Cypher Systems by Roll20/translations/en.json, Cypher Systems by Roll20/translations/fr.json
Cypher Systems by Roll20
UC-556: Roll template multilingual fix
If you do not …
=> Cypher Systems by Roll20, uc-556

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Adding some future investigation console logs
* Adding additional Monster handling to allow for more graceful drops
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets# …
=> D&D 5e - uc-561 - add monster drop handling

Free Spacer/FreeSpacer.css, Free Spacer/FreeSpacer.html, Free Spacer/FreeSpacer.json
Updated the sheet to the release version of the game, including:
- Switched the launch craft to a Launch Bay Module.
- Renamed the various damage boost mods to all be called "Damage Boost"
Removed pull down lists from the sheet for potential Compendium compatibility.
=> Free Spacer: Release version

Knight/knight.css, Knight/knight.html
Une mise a jour apportant des fonctions demandées par la communauté.
Il y a aussi quelques bugs résolus.
De plus, elle améliore aussi l'esthétique de la fiche, sans que rien ne soit perdu.
=> [Knight] Various Update

Starfinder by Roll20/Starfinder.css, Starfinder by Roll20/Starfinder.html
- Removing an item that applied a mod to the sheet was not removing the effect of the mod.
=> Starfinder By Roll20 V1.001

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Fixed traits issue with NPCS on drop
=> D&D 5e by Roll20 - uc572 - traits hot fix

GURPS/sheet.json
=> [GURPS] Updated sheet.json

Naheulbeuk/Naheulbeuk.html
- Add COU, INT and CHA throws for Special Shots
- Allows to note "Particular Features" with text rather than the input table
- Add attr_bonus for physical attacks
- Add name to all buttons (for drag & drop )
- Change the Confrontation roll on 1d6 instead of 2d6
- Minor corrections
- Minor graphic update
=> Le donjon de Naheulbeuk 2.9

Tri-Stat/Tri-Stat.html
This change makes the "Initiative" macro on the character sheets add them to the turn order tracker. This is considered a feature enhancement. This does not change any aesthetics, no attributes were changed or removed.
=> Tri-stat: Initiative macro should add tokens to the turn order.

Starfinder by Roll20/Starfinder.html
- Drag and Dropped equipment was not displaying its item level
- Weapons drag and dropped to NPCs were not properly sorting into melee/ranged sections
=> Starfinder by Roll20 v1.002

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
-  Fixed Hit Die button for Spanish sheet version
=> DnD5e - UC-535 - Spanish Hit Die issue fix

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
* Fixed the roll template when stretching the chat
=> D&D 5e by Roll20 - uc584 - roll template fixs

Starfinder by Roll20/Starfinder.html
- Removing an equipment item will now update carrying capacity and
wealth. Resolves issue #5203
=> Starfinder by Roll20 UC-587

Gumshoe by Roll20/GUMSHOE.css, Gumshoe by Roll20/GUMSHOE.html
* Get investigation and general points working again in game settings
=> Gumshoe by Roll20 - UC-532 - fix points

Gumshoe by Roll20/GUMSHOE.css, Gumshoe by Roll20/GUMSHOE.html
Reverts Roll20/roll20-character-sheets#5207
=> Revert "Gumshoe by Roll20 - UC-532 - fix points"

Gumshoe by Roll20/GUMSHOE.html, Gumshoe by Roll20/sheet.json, Starfinder (simple)/Starfinder (simple).html
=> Cl uc532 gumshoepointfix

Gumshoe by Roll20/GUMSHOE.html, Gumshoe by Roll20/sheet.json
* Put Gumshoe fix back on staging
=> uc-532 fix default points

Gumshoe by Roll20/GUMSHOE.html, Gumshoe by Roll20/sheet.json
* Fixed the default point options for Gumshoe
=> Gumshoe by Roll20 - UC-532 - fix the default points

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.html
New try to commit version 2.7 of the character sheet (see Readme for changes).
=> Chroniques Oubliees Contemporain: version 2.7

5th Edition OGL by Roll20/translations/ru.json
=> Skills-list for RU

NoReturn/NoReturn.html
add meditation, edit modifier
fix konstitution macro, fix rangeweapon macro
Merge branch 'master' into master
spelling corrected
fix melee dmg macro
add characteristic points
change characteristic points to text
insert weight calculation
added different fire modes
=> (NoReturn) some improvements

Starfinder by Roll20/Starfinder.html
- Feats were not dropping from the compendium with their benefit entry included in the description field.
=> Starfinder By Roll20 UC-602 Feat benefit wasn't dropping

Band of Blades/bob.html
Update sheet to reflect latest version of game text (1.3):
- Rename tinker to rig (affects attributes `tinker1`, `tinker2`, `tinker3`)
- Update ability text
- Update equipment text
- Add corruptions
- Add version detection and upgrading for attribute changes
> Band of Blades
> Adds "corruption" labelled checkboxes which are functionally equivalent to existing "trauma" checkboxes.
> Attributes `tinker1`, `tinker2`, `tinker3` are automatically copied over to corresponding new attributes `rig1`, `rig2`, `rig3` by version detection if they are set.
=> [Band of Blades] Update to latest game text and add versioning

Knight/knight.css, Knight/knight.html, Prophecy 2/prophecy 2.html
Un petit fix pour les checkbox.
Ce que j'ai changé n'impacte pas les joueurs, dans le sens où il s'agit de cases de blessures qui sont très rapidement retirées et ne donne aucun malus sur les jets ou rien (seul les cases plus élevées en donne).
=> [Prophecy 2]Bugfix

Call_of_Cthulhu_7th_Ed_French/extended_autocalc.js
=> Update extended_autocalc.js Coc7_FR CharacterSheet

Call_of_Cthulhu_7th_Ed_French/sheet.json
=> Update sheet.json Coc7_FR CharacterSheet

Call_of_Cthulhu_7th_Ed_French/coc_7th_ed.html
=> Update coc_7th_ed.html Coc7_FR CharacterSheet

Call_of_Cthulhu_7th_Ed_French/coc_7th_ed.css
=> Update coc_7th_ed.css Coc7_FR CharacterSheet

Call_of_Cthulhu_7th_Ed_French/Readme.md
=> Update Readme.md Coc7_FR CharacterSheet

Call_of_Cthulhu_7th_Ed_French/blind_roll_GM.js
New api for traduction and adaptation of new Call of Cthulhu in EN to FR.
=> Create blind_roll_GM.js Coc7_FR CharacterSheet

Call_of_Cthulhu_7th_Ed_French/sheet.json
Reverts Roll20/roll20-character-sheets#5276
sheet.json is invalid
=> Revert "Update sheet.json Coc7_FR CharacterSheet"

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
=> D&D 5e Italian update - Uc76 v4

Call_of_Cthulhu_7th_Ed_French/coc_7th_ed.html
Reverts Roll20/roll20-character-sheets#5278
=> Revert "Update coc_7th_ed.html Coc7_FR CharacterSheet"

Starfinder by Roll20/Starfinder.css, Starfinder by Roll20/Starfinder.html, Starfinder by Roll20/translation.json
=> Starfinder Mancer - UC-619

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
- fix Italian layout of "DnD5e by Roll20" sheet
=> D&D5E Italian CSS - UC-76

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.css, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
Also changed roll names to start with "roll".
=> Chroniques Oubliees : added roll for magic fatigue.

A Song of Ice and Fire/SIFRPNew.html
Fixes Education rolls trying to roll language.
Made initiative roll print out to chat.
Fixed weapon attack rolls, and removed requirement for a target to be selected.
Partially fixes https://github.com/Roll20/roll20-character-sheets/issues/5302
=> [SFRPG] fixes

Naheulbeuk/Naheulbeuk.css, Naheulbeuk/sheet.json
- Minor css fix for rollTemplate on chrome
- Minor french accent encoding fix for jsonSheet
=> Le donjon de Naheulbeuk 2.9.1

DemonTheDescent/sheet.json
Thought I'd fixed this last month, but apparently it only fixed it on my own branch, so here's a PR to fix it on the master. Woops.
=> Fix sheet.json for DemonTheDescent

approved.yaml
@clevett, could you take a look? This entry is currently referring to the wrong underlying sheet.
=> Fix folder for the new Band of Blades sheet

Mutants and Masterminds 3E/mutants-and-masterminds.css
- Correct Power points input fields being too small when dealing with larger numbers.
=> [Mutants and Masterminds 3E] Correct Power points input fields

Palladium Fantasy 1E/sheet.json
[Palladium Fantasy 1E] Updated instruction line
=> [Palladium Fantasy 1E] Update sheet.json

Naheulbeuk/Naheulbeuk.css, Naheulbeuk/Naheulbeuk.html
- minor css fix
- minor sheetworker fix
- add howto modal popup for "Traits particulier"
- add temporary buff for movement speed
=> Le donjon de naheulbeuk 2.9.2

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css, 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> uc-693 DnD5E: fix spellcasting misalignment

StarWars5E/README.md, StarWars5E/StarWars5E_HTML.html, StarWars5E/sheet.json, StarWars5E/translation.json
* rearranged skills in alphabetic order (PC/NPC)
* made NPC sheet slightly wider
* Added back some  Default Settings
=> [SW5E] Small Fixes

Shadowrun5th/Shadowrun5th.html
I failed my merge roll and duplicated the soak bonus box
=> remove additional soak bonus box

GURPS/gurps.css, GURPS/gurps.html
=> [GURPS] v1.6.4 Minor cosmetic changes for html and gss files

Pathfinder Second Edition by Roll20/pathfinder2.css, Pathfinder Second Edition by Roll20/pathfinder2.html, Pathfinder Second Edition by Roll20/sheet.json, Pathfinder Second Edition by Roll20/translation.json, Pathfinder Second Edition by Roll20/worker.js, approved.yaml
Release notes - User Collaboration - Version Pathfinder 2 v2.01
** Task
* [UC-675] - Pathfinder 2: Refactor Sheetworkers
* [UC-698] - Pathfinder 2: Game Settings set default sheet type
** Bug
* [UC-699] - Pathfinder 2:  Move NPC setting buttons to the left side
* [UC-701] - Pathfinder 2: Saving throws roll template calls wrong notes attribute
* [UC-710] - Pathfinder 2: Display fixes
* [UC-712] - Pathfinder 2: Wrong spell DC calculation when magic tradition is selected
=> Approved list & Pathfinder 2 v2.01

Pathfinder Second Edition by Roll20/pathfinder2.html, Pathfinder Second Edition by Roll20/worker.js
* Fixed level 9 spells
* Fix GM whipser toggle
=> Pathfinder 2: hotfixes Gm Whisper & Lvl 9 spells

Kids-on-Bikes/kob.html
Added Self-Centered & Self-Pitying to Flaws table on KoB Sheet
Bug Fix. No attributes removed, only moved positions
=> Added Self-Centered & Self-Pitying to Flaws table of Kids on Bikes sheet

NoReturn/NoReturn.html
change attribute of experimentaltechnik
rename Range -> Zielbereich
add psi meisterschaft
add psi noob
ad psi aufrechhaltung
=> (NoReturn) some bugfixes

ChroniquesOubliees/co.htm
=> ChroniquesOUbliees: fixed a bug in the import stats for npcs.

Godbound/Godbound.css, Godbound/Godbound.html, Godbound/README.md
- Description fields for words, gifts, miracles, and artifacts changed to auto-expand
- Small adjustment to project layout
- Correction for styling of two fieldset "add" buttons that was missing
=> Godbound v2.3

AllforOne/sheet.json
=> Fixed comma in html file name in JSON

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Fix College of Lore Bard's spells
* Fix ASI not capped at 20
=> D&D 5e, Version 2.713

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> D&D 5e - UC115: Spellcasting save DC

5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
=> D&D 5e - UC800: Global Damage Modifiers CSS is off

Symbaroum/src/pug/_mixins.pug, Symbaroum/symbaroum.css, Symbaroum/symbaroum.html, Symbaroum/symbaroum.pug, Symbaroum/symbaroum.scss
* Fixed Defense by adding a default value
* Added () around the user query so + will work if enter
* Fix Roll template issue in CSS
=> Symbaroum v2.11

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> D&D 5e Mancer: Land Vehicles proficiency does not drop with Marine background (UC748)

D6StarWars/CHANGELOG.md, D6StarWars/D6StarWars.css, D6StarWars/sheet.json
- Adjust rolltemplates so title-text is centered, and bold
=> [Star Wars D6] V.2.14

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
=> D&D 5e Lvl+ Mancer: Spells tab "Level undefined" (UC605)

Mutants and Masterminds 3E/mutants-and-masterminds.css, Mutants and Masterminds 3E/mutants-and-masterminds.html
* visual fixes made so sheet looks good on firefox as well
* sheet tested on both Firefox and Chrome
* some reorganizing of CSS file, added some comments 
=> [Mutants & Masterminds 3E] visual fixes 

approved.yaml
=> uc-822 migration

approved.yaml
* Deprecating old Maid sheet
* Add new Feast of Legends & Cyberpunk sheet.
=> uc-758 new sheets

SavageWorlds-Tabbed/SWTRedesign.css, SavageWorlds-Tabbed/SWTRedesign.html, SavageWorlds-Tabbed/sheet.json, SavageWorlds-Tabbed/translation.json, SavageWorlds-Tabbed/translations/fr.json
Reverts Roll20/roll20-character-sheets#5527
Savage World Tab sheet will not load.
=> Revert "Savage Worlds 3.10"

AllforOne/sheet.json, Heroquest_Glorantha/sheet.json
=> Updated JSON

Symbaroum/src/pug/oldpage4.html, Symbaroum/src/pug/oldsymbaroum.html, Symbaroum/src/pug/oldtabs.html, Symbaroum/symbaroum.html, Symbaroum/symbaroum.pug
HTML/PUG compiled with `pug -P` command, fixes tested on Firefox(Linux).
- fixed faulty data-i18n attributes
- minor html fixes
- updated sheet version to v.2.12, but didn't touch sheetworker that actually does the changes
=> [Symbaroum ] v.2.12

Firefly/firefly.css, Firefly/styles.less
- Fix suggested/requested by #5426 
- Manually made suggested fixes to `.css` and `.less` files without going the mile to recompile the sheet using `Less`.
- Fix tested on Firefox(Linux)
=> [Firefly] Minor visual fix

Delta Green 2/deltagreen.html, Delta Green 2/deltagreen.pug
* Update the images to use master repo
=> Delta Green - images to master

DresdenFilesAccelerated/DFA.css, DresdenFilesAccelerated/DFA.html
- change rolls to use default roll template
- give more space for section containing the roll buttons
=> [Dresden Files Accelerated] minor fix

Torg Eternity/README.md, Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html, Torg Eternity/sheet.json
Tested on Firefoxx & Chrome
- Fixed tab buttons so they also display properly on Firefox (**Archange**, with minor adjustments from **Anduh**)
- Enlarged Logo to be readable
- minor CSS/HTML cleanup
- Changelog update
=> [Torg Eternity] V.3.2

Das_Schwarze_Auge_5_Tsa_Edition/README.md, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.css, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json, Das_Schwarze_Auge_5_Tsa_Edition/translations/en.json
- add different color schemes
- fix bug regarding Fernkampf
=> [Das_Schwarze_Auge_5_Tsa_Edition ] add different color schemes

CWorldofDarkness/CWoD.css
made the number 80 to fix another bug  hopefully this will be the last one needed 
some reason the skill dots were not in the correct location for some users
=> changed the number in input.sheet-attr width

ChroniquesOubliees/co.htm
Improved a bit the stat block import.
=> ChroniquesOubliees: allow import stat block to read wounded characters

The One Ring/sheet.json
* edits only `sheet.json`, doesn't affect sheet itself.
=> [The One Ring] add link to Readme & wiki page in 'instructions'

Ambition_Avarice/Readme.md, Ambition_Avarice/ambition_avarice.css, Ambition_Avarice/ambition_avarice.html, Ambition_Avarice/sheet.json
* add Readme & link to it from `ìnstructions`
* fixed image links to Roll20/master
**First page**
* change "In Sixes" to repeating section
**Equipment page**
* add repeating weapons & armor sections
* add trackers for the four types of AC
**Misc Page**
* add a fourth tab,"Misc, for further development
* add tracker for spell failure
=> [Ambition & Avarice] V.1.2

Taura/TauraSheet.css, Taura/TauraSheet.html
Fixed the sheet for Taura game. It was tested in the roll20 online editor of the pro account.
=> Taura - character sheet fix

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.htm, Forbidden_Lands/translation.json
- fixed missing sheetworker translation code(weapon, spell, push query, etc.)
- optimized sheetworker code(Thank you GiGs).
- small adjustments to the roll template's layout.
=> Forbidden Lands v1.55

GURPS/README.md, GURPS/gurps.css, GURPS/gurps.html, GURPS/sheet.json
This PR is a cleaned up version of #5689. I copied the changes made by @MadCoder253 to the GURPS sheet, and added a Changelog to the Readme for quicker overview of recent changes.
I'll leave this as a draft until Madcoder approves this PR. @KlingonMike might want to comment as well.
* Repeating skills/spells. Removed checkbox to show success/fail notes. Converted text boxes to multi-line text boxes.
* Repeating melee/ranged attacks. Ability to link weapon to skill or spell. The weapon will show the skill or spell level and should update when the skill or spell level is updated.
* Reformat minimum damage notes and include page reference.
**Cosmetic Only:**
* Repeating Spells. Moved checkboxes for ON and MT to avoid collision with delete button.
* Resized some text boxes to allow more space …
=> [GURPS v1.7.0] clean PR

Tesoro-y-Gloria/README.md, Tesoro-y-Gloria/tesoroygloria.html
* fix image path names to point at Roll20/master instead of my branch
=> [Tesoro y Gloria] fix img pathnames to Roll20/master

nephilimV5-vf/nephilim-legende-vf.css
=> fixing image urls in css

Das_Schwarze_Auge_5_Tsa_Edition/README.md, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.css, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json
- redesign status tab
- on talente tab is now a switch to show description or modifier
=> [Das_Schwarze_Auge_5_Tsa_Edition] redesign status tab and talente tab

Knight/knight.html
=> [Knight] Bugfix Warrior

Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html
The sheetworker scripts were in an invalid format because my new code editor has a auto format that doesn't work as expected.
=> [Das_Schwarze_Auge_5_Tsa_Edition] fixed sheetworker scripts

vampire-v5/README.md, vampire-v5/VTM_Dice_Mechanics.js, vampire-v5/vampirev5.css, vampire-v5/vampirev5.html
Added new rituals section, bug fix incoming in API section update.
Yes
The bug is in the API script which needs to be updated seperately.
New rituals section
No
No
N/A
=> Vampire the Masquerade 5th Edition Update

GURPS/README.md, GURPS/gurps.css, GURPS/gurps.html
- Updated, reformatted, and added many ToolTips – Cosmetic Only
- Fixed a very minor error in the CSS file – Cosmetic Only
- Fixed alignment of the Melee Attacks Header – Cosmetic Only
- Changed Options box name of Critical Successes to Successes / Fails – Cosmetic Only
- Cleaned up Change Log and removed all entries prior to 08/06/2019), added some new info on the options page - Cosmetic Only
- Fixed alignment of the Inventory Header – Cosmetic Only
- Fixed basic Swing damage calculator bug – reported and fixed by Vitalii S (User ID: 146689
- Added Grand Total Weight to the Inventory page and reformatted the results – Cosmetic Only
If you do not know English. Please leave …
=> [GURPS] v1.7.2 Mostly Cosmetic changes: GURPS.html, GURPS.css, README.md

Knight/knight.html
=> [Knight] Hotfix

Ironsworn/Ironsworn.html
(Third times a charm, had an issue with rebasing again >.>)
Quick text update for the burdens:
They are now Cursed and Tormented
They were updated in the latest versions of Ironsworn so just keeping this reflecting the new version.
Keeping the variables the same as to preserve player data.
The indenting has also been fixed as there was an issue with excess divs causing an issue with the formatting. And applied auto format for the html.
=> [Ironsworn] Update Burdens to reflect the new sheet and formatting fix

Shadowrun5thEdition/Shadowrun5thEdition.html, Shadowrun5thEdition/Shadowrun5thEdition.pug, Shadowrun5thEdition/src/js/importer.js, Shadowrun5thEdition/src/js/scripts.js
* fixing the importer for real this time
=> Shadowrun5thEdition v3.03 importer

AGE System/AGE System.html, AGE System/translation.json
The current version of the sheet was not usable for AGE The Expanse as important fields were missing. (3 out of 9 relevant abilites were not shown.) 
There are still some items missing, esp. "Toughness" and "Income". I try to 
All changes only apply to the sheet version for "The Expanse"
"AGE System.html"
* "The-Expanse"-Logo is shown on every tab
* renamed Origin i18n "expert" to "earther"
* Header-info-top shown in all tabs 
* Header-info-top now with fields "Level", "Origin", "Social-Class", Background" "Profession", and "Drive"
* Header-info-bottom now works just like Fantasy AGE (Fields are "AGE", "GENDER", "HEIGHT", "WEIGHT")
* Attributes "ACCURACY", "FIGHTING", and "INTELLIGENCE" enabled in CHARACTER tab and FOCUSES tab
* Changed "HEALTH" to "FORTUNE", as it works slightly …
=> [AGE System] hotfixes for sheet version "The Expanse"

Das_Schwarze_Auge_5_Tsa_Edition/README.md, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.css, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json
Neue Features:
- Es wurden jetzt Effekte hinzugefügt, die genauso funktionieren wie Sonderfertigkeiten. Hierüber kann man Auswirkungen von Zaubern, Liturgien oder Artefakten abbilden. Modifikatoren für Effekte werden an vielen Stellen getrennt von SFs angezeigt.
- Sonderfertigkeiten sowie Effekte haben jetzt 4 statt 3 Modifikatoren
- Magie und Götterwirken haben jetzt 5 statt 3 Beschreibungsfelder für Erweiterungen.
- Die Textfelder für Beschreibungen, Anmerkungen oder Referenzen sind jetzt Textareas, die man aufziehen kann und deutlich mehr Text enthalten können.
- Bei Sonderfertigkeiten und Effekten sind die Modifikatoren und Beschreibung jeweils ein- und ausblendbar. Dazu einfach auf das (+) oder (-) klicken.
- Bei Magie und Götterwirken sind die Merkmale, Erweiterungen sowie …
=> [Das_Schwarze_Auge_5_Tsa_Edition] design rework, new features, bugfixes

D6StarWars/CHANGELOG.md, D6StarWars/D6StarWars.css, D6StarWars/D6StarWars.html, D6StarWars/sheet.json
- Fix the Ship's weapons' repeating section
=> [Star Wars D6] v2.15

Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html
Changed all occurrences of "Coup de Gras" to "Coup de Grace"  and of "coupdegras" to "coupdegrace"
=> [Torg Eternity] Corrected Spelling of "Coup de Grace"

Das_Schwarze_Auge_5_Tsa_Edition/README.md, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.css, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json
- fixes a missing row in tab Kampftechniken
- fixes calulcation in Fernkampf Modifier
- rework design for Ausrüstung and Artefakte
=> [Das_Schwarze_Auge_5_Tsa_Edition] fix ktw zweihandhiebwaffen

Knight/knight.html
=> [Knight]Update for new book

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.css, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
adding user options, moving stuff around and improving the code.
=> ChroniquesOubliees: version 3.0

CWOD-V20/V20.html, CWOD-V20/translation.json
* this is meant to replace #5808
=> [CWoD-Vampire 20th] small translation & visual fixes to recent update

D6_Space/D6Space.css, D6_Space/D6Space.html
* add button to weapons
* fixed weaponname for repeating section
* changed main attributes to be customizable
* cleaned up attributes section 
=> [D6 Space] minor fixes

Cyberpunk 2020/Cyberpunk2020.css
The Background images went missing, making rolls impossible to read. This changes them to black
=> Update Cyberpunk2020.css Fixing Missing Backgrounds

Les Chants de Loss/LCDL.html
=> [LCDL] Bugfix

Delta Green 2/sheet.json
=> Delta Green remove patreon & update author

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.css, ChroniquesOublieesContemporain/coc.html, ChroniquesOublieesContemporain/sheet.json
=> ChroniquesOublieesContemporain: version 2.9

Daemon/Correction File Daemon.html, Daemon/Daemon.css, Daemon/Daemon.html
Corrigido redundâncias nos nomes de atributos que estavam gerando bugs
Googlo translate
Fixed redundancies in attribute names that were generating bugs
=> Sistema Daemon (Bug fix)

Les Chants de Loss/LCDL.html
Replace some latin characters by their ISO code as the file seems to be in ISO-8859-1.
@Zakarik  has applied a similar correction this week but it was incomplete
=> [Les chants de Loss] correction of a display bug

nephilimV5-vf/nephilim-legende-vf.html
An attribute name was duplicated and a space was misplaced
=> [Nephilim V5 FR] FIX - copy/paste and typo correction

Connected_stories/Connected_stories.css, Connected_stories/Connected_stories.html
Ui Bug Fix
- [O ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [O ] Is this a bug fix?
- [O ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
=> [Connected stories] Ui Bug Fix

Warhammer-Fantasy-Roleplay-2nd-Edition/translations/pl.json
=> Warhammer Fantasy Roleplay 2e Fix typo

Shadowrun5thEdition/Shadowrun5thEdition.html, Shadowrun5thEdition/Shadowrun5thEdition.pug, Shadowrun5thEdition/src/js/helpers.js, Shadowrun5thEdition/src/js/scripts.js
* Refactor the repeating skills functions to fix bugs
* Fixes issue #5905 
=> Shadowrun 5th Edition skill bugs

AD&D_1E/1ESheet.css, AD&D_1E/1ESheet.html
updated the logo and background image to github images subfolder
=> AD&D1e - image links updated

Technoir/Technoir.css
Bug fix for broken image urls in the stylesheet. The new images are cosmetically different but functionally the same.
=> [Technoir] updating image urls

Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html
In preparation for a major sheet update, this commit adds an announcement at the top of character sheets letting players know about it, and how to preview the changes.
No functional changes to the sheet are made in this commit.
=> Torg Eternity Sheet Update Announcement

ChrisPerrinsMecha/ChrisPerrinsMecha.css
* display fix for middle section, should now show it instead of having it be under the background image
=> [Chris Perrin's Mecha] display fix for middle section

TIH/sheet.json, TIH/translations/it.json
I fixed a typo and changed an email address.
Thank you.
=> The Indie Hack Some fixes

Eclipse Phase V2/Eclipse Phase V2.html
Fixed 'Free Fall' showing as a REF based skill when it is a SOM based skill.
=> Updated Eclipse Phase V2.html

Deadlands Classic Anniversary/deadlandsclassic_anniversary.html
One skill was using the attribute of another one. This bug was fixed
=> Deadlands Anniversary: Fix bug Mad Science reffering to attr_disguise

DnD_Moldvay_AmandatheAmazon/D&D_Moldvay_AmandatheAmazon.css, DnD_Moldvay_AmandatheAmazon/DnD_Moldvay_AmandatheAmazon.html
Changes:
CSS
1. -odnd changed to -moldvay
2. Patrick Hand commented out and Suez One added
3. .charsheet div, charsheet span:  font-size: 21px changed to 16px;
HTML
1. fixed quote marks in: “TO HIT” ROLL NEEDED using &ldquo; and &rdquo;
2. fixed apostrophes in Player's Name, Character's Name using &rsquo;
NOTE: If accepted, the change log in ReadMe.md needs to be updated.
=>  DnD_Moldvay_AmandatheAmazon template name and font suggested changes

Scion2e/scion2e.css, Scion2e/scion2e.html
=> [Scion 2e] Add Roll

Shadowrun5thEdition/Shadowrun5thEdition.html, Shadowrun5thEdition/Shadowrun5thEdition.pug, Shadowrun5thEdition/src/js/newScripts.js, Shadowrun5thEdition/src/js/processingFunctions.js, Shadowrun5thEdition/src/js/versioning.js
- Fix common rolls being x3
- Fix type causing melee primary not to work
- Fix translation key
=> Shadowrun 5th Edition v4.13

Cyberpunk 2k20/Cyberpunk 2k20.html
=> Cyberpunk 2k20 : add new option tag

City Of Mist Offical/city-of-mist.html
=> City of Mist update text

Scion2e/scion2e.css, Scion2e/scion2e.html
=> [Scion 2e] Bugfix

Prophecy 2/prophecy 2.html
=> [Prophecy 2] Bugfix

Das_Schwarze_Auge_5_Tsa_Edition/README.md, Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json
- Bugfix: Typo in Button halbe Parade
=> [Das Schwarze Auge -  Tsa-Edition] - bugfixes

LANCER RPG (1.8)/LANCER.css, LANCER RPG (1.8)/LANCER.html
The print-release version of the sheet was pushed with some significant UI bugs for Firefox users. These changes address those bugs, in addition to some minor display fixes.
=> [LANCER RPG] Critical UI /stat display bugfixes

Cyberpunk2k20_v2/Cyberpunk2k20.css, Cyberpunk2k20_v2/Cyberpunk2k20.html
change checkbox to radio
Upgrade worksheet
fix css
=> cyberpunk 2k20 v2 upgrade

Kids on Bikes Official/kob.html, Kids on Bikes Official/kob.pug
- Fix broken images on the official KOB sheet.
=> Kids on Bikes Official v1.03 image fix

Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html
Minor layout tweaks and significant addition to tab2
=> Torg Eternity v4.01

ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
Added a sheet option to whisper all rolls to GM for a character
Added json option so that NPC sheets whisper to GM by default
=> Chroniques Oubliees: sheet option to whisper npc rolls to GM.

Knight/knight.css, Knight/knight.html
=> [Knight] Bugfix Psion

D&D_3-5/charsheet_3-5.html
update side of power points field to accommodate translations.
=> D&D3.5 Update size of Power Points field

WOIN/WOIN.css, WOIN/sheet.json
Removed background colour from OLD version for clearer reading
OLD version of sheet difficult to read (feedback from players), removed tan background.
- [Y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Rol …
=> [WOIN] Removed background

SavageWorlds-Tabbed/SWTRedesign.html
Adding missing data-i18n to Savage Worlds Tabbed sheet
=> [SavageWorlds-Tabbed] Adding data-i18n

Dark Heresy Advanced 2nd Edition/darkheresy2ndedition.html
Fixed a bug in the psy power page where the buttons did not point to correct parameters
=> Updated darkheresy2ndedition.html

Godlike/Godlike.html
Added "sheet-" in the html to make the templates work.
- [y] Does the pull request title have the sheet name(s)? Include each sheet name.
- [y] Is this a bug fix?
=> Godlike: fix templates

ChroniquesOubliees/co.htm
=> Fix miscelaneous HTML problems on ChroniquesOubliees character sheet

Blades in the Dark/blades.css, Blades in the Dark/blades.html
No functionality change (I hope!), this just makes the code human-readable, more or less.
=> [Blades in the Dark] Pretty-print the source code

GURPS/gurps.css, GURPS/gurps.html
GURPS\gurps.html
GURPS\gurps.css
- General Tab. Fix rounding error for jumping distance.
- General Tab. Allow negative values for Air Move modifier and Water Move modifiers. Reported by James W.
- Combat Tab. Active Defenses. Hide checkbox when the Modify button is clicked. Reported by Charles.
- Combat Tab. Active Defenses. Fix alignment issues. Verified on Chrome, Firefox, MS Edge (chromium)
- General Tab. Current HP and Current FP tooltip. Thresholds were not updating when max HP or FP were updated. This should be fixed.
- Traits Tab. Add some gutter space to perks and quirks tables.
=> [Gurps 2.3.2]

Knight/knight.css, Knight/knight.html
=> [Knight] Fix Monk + Psion + Other

Forbidden_Lands/Forbidden_Lands.html, Forbidden_Lands/translations/sv.json
- Updated the Consumables resource dice reminder used for the Swedish translation.
=> Forbidden Lands v1.67 updates

WFRP4CharSheet/translations/pl.json
Update "pl.json" for WFRP4CharSheet
roll20-character-sheets/Warhammer 4e Character Sheet/translations/pl.json
=> Update translate for WFRP4CharSheet

SavageWorlds-Tabbed/SWTRedesign.html
=> [Savage Worlds - Tabbed] fix data-i18n for input

Elric/translations/es_v0.1.json
=> Update traslate file spanish to es_v0.1.json

DungeonWorldFrench/dwfr.htm
Fix for sheet workers and notably prepared spell count.
=> Dungeon World French : fix prepared spells count

Earthdawn (FASA Official)/Earthdawn.css, Earthdawn (FASA Official)/Earthdawn.html, Earthdawn (FASA Official)/sheet.json
New Version with several new features and some bug fixes. 
It does change some attribute names, but if it goes live at about the same time as the (optional) API of the similar name, an update routine in the API changes the attribute names from old to new. 
=> Earthdawn by FASA V01.001

Krystal (FR)/Krystal character sheet v1.html
Fix incorrect refresh trigger for (INT, SAG)-based skill on the Krystal (FR) sheet 
=> Krystal (FR) fix

Knight/knight.css, Knight/knight.html
Pour les attributs changeant, je scan les anciennes sections repeating (avec le Sheetworker) et j'y copie dans la nouvelle section.
For changing attributes, I scan the old repeating sections (with the Sheetworker) and copy them into the new section.
=> [Knight] Update Modules / Bugfix

Vermine 2047/vermine2047.css, Vermine 2047/vermine2047.html
=> [Vermine 2047]bugfix

Shadowrun5thEdition/README.md
=> [Shadowrun5thEdition] tweaking README.md

DungeonWorldFrench/dwfr.css, DungeonWorldFrench/dwfr.html, DungeonWorldFrench/sheet.json
Layout refresh and new rolls options.
=> Dungeon World French - Layout refresh and roll options

Metal Adventures/MetalAdventures.html
Add a new archetype (extending a list)
=> add missing archetype

Knight/knight.css, Knight/knight.html
=> [Knight] Bugfix / Update Bestiaire / Update Art

Eclipse Phase V2/Eclipse Phase V2.html, Eclipse Phase V2/translation.json, Eclipse Phase V2/translations/en.json, Eclipse Phase V2/translations/es.json
=> [Eclipse Phase V2] Update

Nuestro-ultimo-verano/nuestroultimoverano.html, Nuestro-ultimo-verano/sheet.json
Ahora si se añade el valor de Instinto de la ficha a la tirada.
=> [Nuestro Último Verano] Instinto corregido

Hermanos-de-sangre/hermanosdesangre.html
Ahora se suman dados en vez de un valor fijo al daño
=> [Hermanos de Sangre] Daño adicional

Legacy - Life Among the Ruins/LegacyRoll20CSS.css, Legacy - Life Among the Ruins/LegacyRoll20sheets.html
This is a near complete rebuild of the Family section of the character sheet and fixes for character stat setup in the Character section of the sheet.
Massive structural changes, with associated styles. (Should all work, thoroughly tested in the sandbox.)
Numerous fixes for bad roll buttons and HTML structure. Adds more useful roll button setups, notes fields, and other data fields that either weren't in place before or weren't usefully/properly functioning.
All old data structures preserved and accessible to sheet users. No old attribute fields removed.
=> Legacy: Life Among the Ruins Family Sheet Rebuild

Earthdawn (FASA Official)/Earthdawn.html
A few minor bug fixes,  nothing major. Version was changed to keep it the same as Earthdawn by Fasa character sheet companion (API script), which has some slightly bigger changes. 
=> Earthdawn by FASA V1.002

A Fistful of Darkness/README.md, A Fistful of Darkness/aFoD.css, A Fistful of Darkness/aFoD.html, A Fistful of Darkness/sheet.json, A Fistful of Darkness/translation.json
V1.1
* Improved colors for Location Cards (black / red)
* Improved colors for Achievements (better contrast)
* Bugfix to Outlaw Achievements (wrong category)
* Typos fixed
* Add credits for Jacob and Tim
* Improved colors for Location Cards (black / red)
* Improved colors for Achievements (better contrast)
* Bugfix to Outlaw Achievements (wrong category)
* Typos fixed
* Add credits for Jacob and Tim
=> [A Fistful of Darkness] V1.1 Minor changes, fixed typos, added credits

GURPS/gurps.css, GURPS/gurps.html, GURPS/sheet.json
**Files updated**
- /GURPS/gurps.html
- /GURPS/gurps.css
- /GURPS?sheet.json - tweak to sheet option
**Changes**
- Creates a new field for show Rules as Written active defense notes and mark it as checked.
- Highlight Row Option. Update style so input boxes use the same background color. Reported by GroundWalker.
- Fixed and revised alignment of custom success/fail notes. Updated by TamedFlame.
- Several new style themes added by TamedFlame.
- Critical failure by 10 or more points no longer applies to ranged attacks.
- Roll template, removed debugging code for sub-heading. Spotted by Karu.
- Added character name just above the navigation tab. This will allow you to see the name when the sheet has been popped out into its own window.
- Combat Tab. Added Close Range Shotgun Damage Tool.
- …
=> [Gurps 2.3.4]

Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html
Minor update - Some style tweaks, and a change to the way ammo counts work under the hood.
=> Torg Eternity 4.02

AD&D 2E Revised/2ESheet.html
- Actual changes will come in following pull request
Added a message to inform players of upcoming changes.
=> [AD&D 2E Revised] Update message

CWOD-C20/C20.css, CWOD-C20/C20.html, CWOD-C20/README.md, CWOD-C20/sheet.json
=> [CWoD Changeling 20th] v0.7

Agone-(french)/agone-sheet.html
- Quick fix for missing index and replacing vars by lets
=> Agone-(french) new version 0.39

Marvel Heroic Roleplaying/mhrpg.html
Adding Dice Pool, buttons, styling, NPC sheet tab, Doom Pool sheet tab
Yes
No
This adds functional enhancements, both new features and extending existing features
This adds functional aesthetics both layout and color scheme
I have retained all existing attribute names, only adding attributes
I have followed the standards
=> Overhaul MHRPG Character sheet mhrpg.html

Marvel Heroic Roleplaying/mhrpg.css
Styling for the Overhaul
Yes
No
Yes, this adds functional enhancements, both new features and extending existing features
Yes, this adds functional aesthetics, both layout and color scheme
All original attributes have been preserved, only new attributes have been added
I followed the standards
=> Overhaul MHRPG Character sheet mhrpg.css

Marvel Heroic Roleplaying/sheet.json
Add Overhaul author and instructions
=> Overhaul MHRPG Character sheet mhrpg.json

Ghost-Ops-RPG/ghostopsrpg.html
=> Remove wound mod from weapon damage rolls

Magica_Logia/MagicaLogia.css, Magica_Logia/MagicaLogia.html
[MagicaLogia] Character Name Text Modify
Character Name Text Modify
- [O] Does the pull request title have the sheet name(s)? Include each sheet name.
- [O] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [O] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
=> [MagicaLogia] Character Name Text Modify

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.html
- Added again the change on revamped skill system that was refused last week
- Tried to program around Roll20 recent [bug on linked token attributes](https://app.roll20.net/forum/post/8427520/token-bars-not-syncing-up-with-values), since we've had no news of a fix.
=> Chroniques Oubliees Contemporain: fix to avoid recent Roll20 bug

Magic_World/magicworld.html
Corrected a spelling error and made some cosmetic changes to provide a more consistent look throught the whole of the character sheet.
=> [Magic_World] Cosmetic

Nuestro-ultimo-verano/nuestroultimoverano.css, Nuestro-ultimo-verano/nuestroultimoverano.html
Salía colapsado y no podía leerse el título.
=> [Nuestro Último Verano] Título Ataques corregido

Degenesis/Degenesis.css, Degenesis/Degenesis.html
=> Change picture links

ChroniquesOublieesContemporain/coc.css
Added a missing CSS class required for Version 3.2
@Ulty forgot to include a change I made in the CSS
From now on, I will do the PRs for this character sheet (I am now more experienced with the Git versionning system and do not need Ulty's help anymore)
If this PR can be integrated sooner than later as a hotfix, that would be great. 
TIA
=> ChroniquesOublieesContemporain Version 3.2 hotfix

Mongoose_Traveller2e/MongooseTraveller.html
Streamlined the sheet workers. Lots of people have used the traveller sheets as templates for thier own games, so it would be nice if they had a better example of sheet workers to follow.
Also changed the order of stats in the skill selection dropdowns, to match the official order.
=> Mongoose Traveller 2e

Mongoose_Traveller/MongooseTraveller.html
Streamlined the sheet workers. Lots of people have used the traveller sheets as templates for thier own games, so it would be nice if they had a better example of sheet workers to follow.
Also changed the order of stats in the skill selection dropdowns, to match the official order.
=> Mongoose Traveller 1e

Earthdawn (FASA Official)/Earthdawn.css, Earthdawn (FASA Official)/Earthdawn.html
Earthdawn by FASA
Minor updates.  A new gm option.  Should pose no data incompatibilities. 
=> Earthdawn by FASA   v1.0021 minor bugfixes

Forbidden_Lands/Forbidden_Lands.html
- expanded weights beyond Heavy
=> Forbidden Lands v1.70

ADnD_1E/1ESheet.css, ADnD_1E/1ESheet.html
- added cantrips
- added #mem to each repeating spell
- added spell tabs to sort by level
=> ADnD1e v1.51 update

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.html, ChroniquesOubliees/sheet.json
- armor and shield on NPC sheet
- helmet on PC sheet
- automatic labelling of attacks
- follow PC hit points even in NPC mode.
=> Chroniques Oubliees: version 3.2

Mutant Year Zero/mutantyearzero.html, Mutant Year Zero/sheet.json
* Fix the file names
* Update image urls
=> Mutant Year Zero v1.11

Warhammer40k-WrathandGlory/WrathnGlory.css, Warhammer40k-WrathandGlory/WrathnGlory.html
=> Warhammer v1.11

RunequestGQS/RunequestGQS.html
- Agility Skill Mod/Size -5% bonus upper limit stat corrected to Size
- Agility Skill Mod/Size bonus extension stat corrected to Size
- Agility Skill Mod/Strength bonus calculation made possition independent
- Perception Skill Mod/Pow +5% bonus upper limit corrected to 20
- Manipulation Skill Mod/Strength bonus calculation made possition independent
- Corrected some currently harmless (+ -) operators to (-).
=> [RunequestGQS] Fixes in Skill Modifiers Calculations

Shadowrun5thEdition/Shadowrun5thEdition.css, Shadowrun5thEdition/Shadowrun5thEdition.html, Shadowrun5thEdition/Shadowrun5thEdition.scss, Shadowrun5thEdition/src/html/skillselect.html, Shadowrun5thEdition/translation.json
=> Shadowrun 5th Edition v4.17 Add artificing

CyberpunkRED_Gerdofal/CyberpunkRED.html
=> Fixing int/will error for tracking and perception

Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json
update import function using getTranslationsByKey
=> [Das_Schwarze_Auge_5_Tsa_Edition] update import function using getTranslationsByKey

Pendragon5thEdition/pendragon.html, Pendragon5thEdition/pendragon.pug, Pendragon5thEdition/src/pug/character.pug, Pendragon5thEdition/src/pug/feast.pug, Pendragon5thEdition/src/pug/holdings.pug
=> Pendragon v1.02

Vermine 2047/vermine2047.css, Vermine 2047/vermine2047.html
=> [Vermine 2047] Update

Hermanos-de-sangre/Readme.md, Hermanos-de-sangre/sheet.json
=> [Hermanos de Sangre] Info actualizada

Zweihänder Grim & Perilous/sheet.json
=> DEV-3985 Zweihander Compendium Default

Shadow of the Demon Lord/translations/pt.json
Fix wrong translation for FATE field.
Tradução errada para o campo DESTINO.
=> Shadow of the Demon Lord - update pt.json

DungeonWorldFrench/dwfr.css
Dungeon World French: dynamic action roll display fix
=> Dungeon World French: dynamic action roll display fix

Earthdawn (FASA Official)/Earthdawn.html
Minor bugfixes, correct some math.
There is an update routine to update change an attribute. 
=> Earthdawn by FASA update 1.0022a

Agon Official/agon.html
- Update underlying worker library
- Increase number of starting islands to 6
=> [Agon] Worker tweaks

Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html
fixed the URLs for images to roll20 github
=> Torg Eternity Update

A Song of Ice and Fire/SIFRPNew.css, A Song of Ice and Fire/SIFRPNew.html
- Css update for army layer
- Update script TheAaronSheet.js 0.2.3 to 0.2.5
- Add army layer in Character sheet
=> [A Song of Ice and Fire] Add Army Layer

Splittermond/Sheet.html
- I fixed some minor bugs
- I added some new modifier for attributes
=> [Splittermond] Small bugfixes, new modifiers

HARP/harp.html
Corrected issue with the rolltemplate that allowed an exploding roll to show as a fumble.
=> [HARP] Roll Template Corrections

Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html, Das_Schwarze_Auge_5_Tsa_Edition/translation.json
add translations and bugfix for rs calculation
=> [Das_Schwarze_Auge_5_Tsa_Edition] add translations and bugfix for rs calculation

Tales from the Loop/TFTL css.css
=> Tales from the Loop - Updating Product Identity

ChroniquesOubliees/co.html
=> Chroniques Oubliees: correct some display size

approved.yaml
Hello,
Butterfly Aspect does not belong to Fate but is an independent set of rules.
=> [Butterfly Aspect] approved.yaml

Midgard German RPG/Midgard.css, Midgard German RPG/Midgard.html
Configtab added for configurable dice rolls.
=> [Midgard German RPG] Midgard german rpg v3

approved.yaml
- the sheet was initially categorized as a GURPS sheet, even though it's a standalone system and have nothing to do with GURPS.
- Requests to have the category changed mentioned in past PRs have fallen through the cracks, so editing the approved.yaml file directly even though we aren't supposed to, should get the point across more clearly.
=> [Supers RED] Change Game category

approved.yaml
- Sheet was never added to approved.yaml, fixes #6528
- As mentioned in the original PR #6351, this sheet is for a re-imagined version of the game, but shouldn't replace the old sheet.
- Based on that, and info on [the publishers page(google translated)](https://translate.googleusercontent.com/translate_c?depth=1&pto=aue&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://www.burobrasil.com/sobre-a-edicao-aprimorada-do-old-dragon/&usg=ALkJrhjWezT-v5snIXqEhXlBTA9LcFWSQA), I suggest the Sheet should be named "Old Dragon Enhanced Edition" to distinguish it from the old sheet.
- Yes, I know we aren't supposed to edit the yaml file, but making a PR with the correct or close to correct changes gets the point across much more easily.
- On a related note, a previous commit have fixed #6387 …
=> [OLD DRAGON] add already merged sheet to approved.yaml

approved.yaml
- the sheet doesn't appear in the sheet template menu, likely due to the error in the approved.yaml
- fixes #6476
=> [Hermanos de Sangre] fix error in approved list

Legacy - Life Among the Ruins/LegacyRoll20sheets.html
* fixed two enclave deep knowledge attributes that where tied together, fixes #6406 
=> [Legacy - Life Among Ruins 2e] v0.21 bugfix

HARP/harp.html, HARP/readme.md
=> [HARP]Harp read me

Path of Paper/path_of_paper.html
=> [Path of Paper] fix 4 attributes not saving stats

Drakar_och_Demoner-91/README.md, Drakar_och_Demoner-91/dod_91.html, Drakar_och_Demoner-91/sheet.json
- Fix 9 attributes not saving stats
- removed id tags as they produce problems with Roll20 sheets
- @andreasdrougge liten fix
=> [Drakar och Demoner 91] v.1.01

Daemon/Daemon.html, Daemon/Readme.md, Daemon/sheet.json
- minor code cleanup, linked to readme file in instructions
=> [Daemon] minor code cleanup

Hero Kids/Hero-Kids.html
=> [Hero Kids] Fix 1 attribute not saving stats

Babylon 5/Babylon 5.html, Babylon 5/readme.md, Babylon 5/todo.txt
- Fix 3 attribute not saving stats
=> [Babylon 5] v. 1.41

Through The Breach/ThroughTheBreach.html
=> [Through the Breach] Fix 9 attributes not saving stats

mutants-and-masterminds-2e-master/mutants-and-masterminds-2e.html
=> [Mutants & Masterminds 2E] Fix couple of attributes not saving stats

Hc Svnt Dracones/Hc Svnt Dracones.html
=> [Hc Svnt Dracones] Fix 1 attribute not saving stats

Conan-2nd-Ed/conan.html
=> [Conan 2E] Fix attribute not saving stat

Villains and Vigilantes/VandVMightyProtectors.html
=> [Villains and Vigilantes] Fix attribute not saving stat

Trail of Cthulhu/sheet.html
=> [Trail of Cthulhu] Fix attribute not saving stat

The Cthulhu Hack/ch.html
=> [The Cthulhu Hack] Fix attribute not saving stat

Battle Century G/Battle-Century-G.html
=> [Battle Century G] Fix couple of attributes not saving stats

Império De Jade/ImperioDeJade.html
=> [Imperio De Jade] Fix attribute not saving stat

Karyu Densetsu/karyu.html
=> [Karyu Densetsu] Fix 2 attributes not saving stats

ButterflyAspect/sheet.json
- add dexcription to sheet.json
- change authors name
=> [Butterfly aspect] add dexcription to sheet.json

NoReturn/sheet.json
- add dexcription to sheet.json
- change authors name
=> [NoReturn] add dexcription to sheet.json

Mutant Year Zero/mutantyearzero.html
=> Mutant Year Zero v1.12 fix images

Les Chants de Loss/LCDL.html
There was a bug for the roll of the Psychology skill. 
This little modification will correct it.
=> [Les chants de Loss] bug correction for skill Psychologie

AllforOne/AllforOne.html
- @zelgar00 this should fix it
=> [All for One] fix image links

MorrowProject4e/sheet.json
=> [The Morrow Project 4th edition ]Update sheet.json

Earthdawn (FASA Official)/Earthdawn.html
One minor new feature, one bugfix, several spelling corrections.  Nothing major. 
=> Earthdawn by FASA Update v1.0023

approved.yaml
=> [Dragon Warriors] add already merged sheet to approved.yaml

Mork Borg/morkborgsheet.html, Mork Borg/morkborgstyle.css
After a major git fiasco on my end, I deleted my earlier PR and am submitting this instead. Hopefully it's fixed the conflict issues of its predecessor.
PR is for aesthetic updates to improve readability with wider displays.
=> Mork Borg aesthetic update

approved.yaml
Needs to be merged with #6621 
=> DEV-4075 add tales from the loop as a publisher sheet

ChroniquesOubliees/co.html
improved parsing of statblocks to accept latest official material.
=> ChroniquesOubliees: improved parsing of statblocks

Heroclix/README.md, Heroclix/sheet.json
Updated the documentation to match that the sheet is released and you no longer need to use custom sheet css and html to use it in a game
=> [Heroclix] Updating documentation to match release state

Oreste/oreste.html
=> [Oreste] Add Sil'warym + Bugfix

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
This should fix the problem behind issue #6152
=> Warhammer 4e Character sheet bugfix

HackMaster_5E/HackMaster_5E.css, HackMaster_5E/HackMaster_5E.html
I have added additional features to improve the usability of this character sheet. These include
-Opposed Skill Checks
-Poison Saves/Ability Score Checks and Saves
-Feat of Agility and Feat of Strength roll buttons
-Fatigue
-More detailed combat profiles
- [x ] Does this add functional enhancements (new features or extending existing features) ?
=> Updating the Hackmaster 5th Edition Character sheet

Marvel_Saga/Marvel_Saga.html
Marvel SAGA sheet.
Fixes typo in power template for Intellect powers (missing 'l' when power template is echoed to GM).  No functional changes.
=> Marvel SAGA - UI fix

Magica_Logia/MagicaLogia.html
- minor bug fixed: change duplicated HTML object name&value (attr_relation_****_10)
=> [Magica_Logia] Update MagicaLogia.html

Marvel Heroic Roleplaying/mhrpg.html
Fix a bug that caused repeating sections on the NPC tab not to work
Fix the same name for some repeating sections and attributes within those sections
- [ x ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ x ] Is this a bug fix?
Yes, this fixes a bug
=> Marvel Heroic Roleplaying - Update mhrpg.html

Torchbearer/sheet.json, Torchbearer/torchbearer.css, Torchbearer/torchbearer.html, Torchbearer/translation.json, Torchbearer/translations/ru.json
- Realigned some fields
- Removed external links to images
- Added default values for the fields
- Added The Grind section (duplicates Conditions, but has different order, as for the rules)
- Changed Conditions table from two columns to one for the order of recovery
- Added rollable buttons for Abilities and Skills
- Added Beginner's Luck buttons, also with rollable macros
- Realigned Skills to two columns for better user expirience
- Changed Level Requirements by rules errata
No fields have been deleted.
=> [Torchbearer] improvements

approved.yaml
=> DEV-4101 fix hot fix tales from the loop

Old Dragon - Aprimorado/od_enhanced.html
Fix to the ranged weapon damage calculation, for normal, critical and sneak attacks.
- [] Does this add functional enhancements (new features or extending existing features) ?
- [] Does this add or change functional aesthetics (such as layout or color scheme) ? 
=> [Old Dragon Enhanced Edition] Ranged weapon damage

MorrowProject4e/MorrowProject4th.html
Changed Firearms to use AWA and Climb to STR
=> [The Morrow Project 4e] Fixed and Climb and Firearms defaults

RWBY_RoC-Unofficial_Tabletop_RPG/RWBY-UnofficialTabletopRPG.html
Hello.
This is a really minor fix:
closing a <td> tag in the Dust Phial section.
Thank you.
=> [RWBY Unofficial Tabletop System] bug fix: minor html yntax correction.

A Song of Ice and Fire/SIFRPNew.css, A Song of Ice and Fire/SIFRPNew.html, A Song of Ice and Fire/translation.json, A Song of Ice and Fire/translations/fr.json
- Minor translation fix
- Add new field translation
- Update French translation
- Invert field value between Army penalty and Army Bulk
- Modify Army Table Design
- Update css design
- Add Hero Bonus in the Army
- Add Disorganization Malus
- Remove button value from attribut
=> [A Song of Ice and Fire] Minor Update

L5R/L5Rsheet.htm
Radio imput span not have "-title" ended in:
skills-u
weapons-u
spells-u
Resolve error visualization
=> [L5R]L5Rsheet.htm - visual bug fix

1800 El ocaso de la humanidad/1800 el ocaso de la humanidad.css, 1800 El ocaso de la humanidad/1800 el ocaso de la humanidad.html, 1800 El ocaso de la humanidad/sheet.json
- bugfixes by @Hornwar, originally rejected in #5751 due to GitHub difficulties
=> [1800 El Ocaso de la Humanidad] bugfix by @Hornwar

Meute/meute.css, Meute/meute.html
=> [Meute] Bugfix img

3D&T_ALPHA/3D&T_ALPHA.css, 3D&T_ALPHA/3D&T_ALPHA.html, 3D&T_ALPHA/sheet.json
Super atualização de ficha de personagens;
Adiconado regras de combate;
Melhoria nos testes de atributos;
Melhoria na disposição dos itesn na ficha;
Adicionao Tab pra veiculos e robos;
Melhoria no teste de magia;
Criação de bonus em atributos;
=> SUper Update 3D&T Alpha

Agone-(french)/agone-sheet.css, Agone-(french)/agone-sheet.html
* rolltemplate stylishing (dices for fumble and critical rolls)
* help text fixed
=> Agone-(french) version 0.4

UltimaTorcia/CS_LUltimaTorcia.html
=> Update "Bandoliera" field

Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.css, Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.html
=> Update All Flesh Must Be Eaten.html

Das_Schwarze_Auge_Ilaris/ilaris_roll20.html, Das_Schwarze_Auge_Ilaris/readme.txt, Das_Schwarze_Auge_Ilaris/sheet.json
sheet.json updated with improved instructions.
Fixed a bug in ranged combat roll templates.
=> [Das Schwarze Auge: Ilaris] update 1.4.1

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.css, ChroniquesOubliees/co.html, ChroniquesOubliees/sheet.json
Added optional fields to the attacks
=> Chronique Oubliees Fantasy: version 3.3

WerewolfTheForsaken2e/WerewolfTheForsaken2e.css
Fixing bugs left behind by my less-experienced css writing when I originally submitted the sheet, and hiding the radio buttons a bit better.
=> Update WerewolfTheForsaken2e Healthbox css

Deadlands Classic Anniversary/deadlandsclassic_anniversary.html
Changed some code on the Arcane Abilities page. Hexslingn' and Rituals should now work as seperate rolls.  Changed name of role from Magie/Wunder??? to Hexslingin'/Ritual
=> Changes to Arcane Abilities

Ryuutama/Ryuutama.css, Ryuutama/Ryuutama.html
Fixed a translation tag error and a spacing issue. Also added a border on your dice size to indicate if it has been increased or decreased.
=> [Ryuutama]: fixes and color on dice size change

FFD20/README.md, FFD20/ffd20.css, FFD20/ffd20.html
Added a few extra options to allow users to customize any sheet and roll's background, as to personalize and differentiate them.
Yes, FFD20
Yes, added attributes to set the background color for the sheet and rolls of any character. The default matches the current style, though, so there should not be any notable changes for the users who chose to ignore it.
=> FFd20 Custom Background Gradient implementation

Reve de Dragon - french/RDD.html
The added fields allow to:
* write down some advantage/hindrances - "Têtes/Queues/Souffles de Dragon"
* store the related "refoulement"
=> [Reve de dragon] tetes/queues/souffles/refoulement

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/sheet.json
- Buttons & Banners further improved look
- Condition Tracking integration into roll template, first pass. see readme.
- NPC tab reworked, look improved, includes full Condition tracking and 2 custom skill rolls fields.
- Various other small fixes
=> [Warhammer 4e Character Sheet] Condition tracking update & NPC tab enhanced

Buried Treasures/buried-treasures.html
Buried Treasures ruleset: minor changes to formulas
- Does the pull request title have the sheet name(s)? Include each sheet name.
yes
yes
no
no
attributes were not changed
this is not a new sheet …
=> Buried Treasures ruleset: minor changes to formulas

3D&T_ALPHA/3D&T_ALPHA.html
Adicionao o valor 0 em tudo atributo numerico, corrgindo um bug de teste,
Mudança no moficado de teste que ante era no dado agora e no atributo.
Pequenos acertos gerais
=> Correção de bugs

Old School Essentials - AAC/CHANGELOG.md, Old School Essentials - AAC/OSE-AAC.html, Old School Essentials - AAC/translation.json
- Add optgroups to class dropdown to categorize classes
- Add automatic XP calculation for monsters based on hit dice. Closes wesbaker#17
- Fix a missing translation for "Find secret door"
- Fix automatic hit dice for character classes
=> [Old School Essentials by Necrotic Gnome] - 1.4.0

WerewolfTheForsaken2e/WerewolfTheForsaken2e.css
Tried to do something fancy with them when fixing a bug last week, turns out I just introduced a different bug. Removing the line that causes said bug, and the other now-redundant line that was added for the fancy styling.
=> Fix bug on WerewolfTheForsaken2e healthboxes

Nephilim-Legende/nephilim-legende.css, Nephilim-Legende/nephilim-legende.html
Fix a typo in the word Kabbale
Duplicate image of alambic instead of athanor
=> [Nephilim-Legende] - fix typo in name and dedup image link

Cronicas-RPG/Cronicas-RPG.html, Cronicas-RPG/sheet.json
[Crônicas RPG]
-Fix roll macro
=> [Crônicas RPG] Roll Fix

INS-MV_3E/insmv3e.css, INS-MV_3E/insmv3e.html
Bugs squashed:
- [powers]: checkboxes values are now properly stored in attributes
- [name]: character name is now synced with its value in the sheet
- [attributes]: hit points are now synced with the Strength attribute
- [powers/weapons]: extra damage and accuracy bonus are now set to 0 by default
- [misc]: a few wordings now use the official terms (e.g. "Vrai nom")
- [misc]: some display tweaks
=> [INS-MV_3E] Fix some bugs in the INS/MV 3rd edition sheet (in French)

ChroniquesOubliees/co.html
Fix position in the script where version attribute is set.
=> Chroniques Oubliees: fix version attribute

thordezilhas/thordezilhas.css, thordezilhas/thordezilhas.html
Thordezilhas Character Sheet
Including spells tab
=> [Thordezilhas] Including spells tab

Supers-Revised-Edition/supers-revised.css
The images were using the wrong address.
=> SUPERS Revised: fix images

ChroniquesOubliees/co.html
Fixed issue introduced in previous commit.
=> Chroniques Oubliées: fix wrong commit missing 'on' keyword.

DutyandHonourBeattoQuarters/DutyandHonourBeattoQuarters.html, DutyandHonourBeattoQuarters/readme.md
- there was a good +100 appributes taht din't save anything, as they where missing "attr_" from their name
- figure @MattBx8 the author want a chance to look at it before approval, I'll leave it as a draft a couple of weeks before turning it in if you haven't checked this out.
=> [Duty & Honor] Fix couple of attribute not saving stats, code cleanup

approved.yaml
=> Add Magical Land of Yield

Fading Suns 2nd Edition Revised/Fading_Suns_2nd_Edition_Revised.html, Fading Suns 2nd Edition Revised/README.md
- Fixed roll buttons not triggering for newly created combat actions, psi powers and theurgy rites.
=> Fading Suns 2nd Edition Revised - v1.2.1 (bugfix)

Tormenta20/tormenta20.html
Resolve critical calculation and add an event to recalculate it when the sheet are opened.
=> [Tormenta20] Resolve critical calculation

3D&T_ALPHA/3D&T_ALPHA.html
=> [3D&T Alpha] Corrects typo in the "Informações Adicionais" field

Star Frontiers 2/Star Frontiers HTML.html
=> Update Star Frontiers HTML.html

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
HP was incorrect so some people may be getting a small buff.
=> Fallout VNDPNP - HP Fix

Splittermond/Sheet.css, Splittermond/Sheet.html
- I added tooltips for derived values
- I added some attributes to be modified by the players
- Just a little increase of the tool tip box' width
=> [Splittermond] Tooltips for derived values

NOC/NOC.css, NOC/NOC.html
=> [NOC] Update combat helper

D6_Adventure/D6AdventureSheet.html
Added the ability to roll weapon damage from the character sheet
- [ X] Does this add functional enhancements (new features or extending existing features) ?
=> [D6 Adventure] Added roll-able weapon damage

FreeSpacer/FreeSpacer.css
The image urls in the sheet point to the wrong address. This fixes that.
=> [FreeSpacer] Bugfix

Only-War-Enhanced/OnlyWarEnhanced.css, Only-War-Enhanced/OnlyWarEnhanced.html, Only-War-Enhanced/sheet.json
changed "Page #" in the Advancements tab to input type "text" for users who want to include abbreviated rulebook names,
refactored range check for Insanity/Corruption,
renamed Unnatural Characteristics grid squares from "mythicgs" to "unnatgs",
fixed incorrect comment in carryweight sheetworker,
improved css grid for armor display overall (so that the "figure" stands up straight),
removed css grid in armor display cells because it looked ugly,
Added disclaimer next to Efffective Psy Rating that it isn't counted in Focus Power Tests yet,
Added WIP framework for sheetworker psykana calculations in case an associate can help with debugging it
Not quite
The Effective Psy …
=> Only War (Enhanced) code improvements

Simulacres v8 base/simulacres.css, Simulacres v8 base/simulacres_v8_base.html
Bonjour
Correction d'un bug dans le lancé de dés des talents pour la matrice 4x4.
Remise en forme de la feuille détaillée sur la partie des Talents avec possibilité de mise à jour.
=> [Simulacres] Mise à jour et correction de bug

thordezilhas/thordezilhas.html
Fixed the second attack button.
=> [Thordezilhas] Fixed attack button

approved.yaml
Adding missing sheets to the approve.
=> Update approve with missing sheets

Old Dragon - Aprimorado/od_enhanced.html
#6839  Changes / Comments
- Initiative adjustment, now using Dexterity instead of the modifier.
- Critical damage of ranged weapons can now be flexible (x1, x2, x3).
- Inclusion of moral, surprise, initiative and protection rolls in the monster sheet.
- Layout adjustments, field types and spelling.
=> [Old Dragon Enhanced Edition] General adjustments and monster sheet improvements

Monsterhearts-2/Monsterhearts-2.html, Monsterhearts-2/translation.json
* Fixed wrong names in data-i18n tags (e.g. 'text-Choseninfo' to 'text-choseninfo')
* Changed 'Heart Move' to 'Sex Move' (who did that???)
=> [Monsterhearts 2] Fix typos in translation file

Shadowrun6th-German/sheet.html
@clevett as mentioned by mail, I've begin adding the missing i18n ids so that we can fully translate the (german) SR6 CS. It's a work in progress, but I'll would rather do it step-by-step.
=> [Shadowrun6] Externalising strings

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/translation.json
- Endurance test in Combat Action no longer rolls a Heal test
- Impale mechanics tidied up for Attack/Opposed/Shoot rolls and made more obvious when it occurs.
- NPC pages 2/3/4 fixes which were only applied on page 1 before
=> [Warhammer 4e Character Sheet] Fixes

3D&T_ALPHA/3D&T_ALPHA.html
Correção de erro de repertir objetos em
kits e itens
=> Bug Fix 3D&T-ALPHA

CWOD-Vampire/Vampire.css, CWOD-Vampire/Vampire.html
=> [Vampire] Bugfix

Palladium Fantasy 1E/palladium_fantasy_1e.css, Palladium Fantasy 1E/palladium_fantasy_1e.html, Palladium Fantasy 1E/sheet.json
Added a new roll template (spells).
Added tabs for spells, psionics, healer abilities, wards, and circles (all are magic related tabs).
Added a configuration tab which provides the ability to show/hide the new tabs and options for roll template colors displayed by the rolls from the new tabs.
=> Palladium fantasy 1 e

H&D/H&D.css, H&D/H&D.html
=> [H&D] Bugfix + Update

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
For some reason, it calculated AG instead of a second IN.
=> Fallout VNDPNP - Doctor Skill Fix

Chronicles of Darkness/CofD.css, Chronicles of Darkness/CofD.html, Chronicles of Darkness/README.md, Chronicles of Darkness/_translation.json, Chronicles of Darkness/translations/en.json
Add Homebrew 1st Edition and Homebrew 2nd Edition sheet types. These give input boxes for the user to enter custom labels of various sections:
* Virtue
* Vice
* Age
* Faction
* Group Name
* Abilities
* Rank
* Resource
Completed various styling cleanup. Notably, the CSS used to display / hide based on sheet type has been simplified to a subtractive approach, demonstrated below:
Apply `display: none !important;` to all game-line elements and override it with `display: <value> !important;` if it has a class corresponding to the current sheet type
```css
.sheet-mortal,
.sheet-vampire {
display: none !important;
}
input.sheet-game-line[value="mortal"] ~ * .sheet-mortal,
input.sheet-game-line[value="vampire"] ~ * .sheet-vampire {
display: inline-block !important;
} …
```
=> [Chronicles of Darkness] Homebrew

Cuentos de Ánimas/cuentosdeanimas.html
=> [Cuentos de ánimas] Bug fixed

Cthulhu D100/cthulhud100.html
=> [Cthulhu D100] Fixed bug

Old School Essentials - AAC/CHANGELOG.md, Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where the roll templates were showing nothing
=> [Old-School Essentials by Necrotic Gnome] - 1.6.1

urbanheroes/urbanheroes.css, urbanheroes/urbanheroes.html
=> [urbanheroes sheet] 4 more fields

Dark_Heresy/DarkHeresy.html, Dark_Heresy/DarkHeresyStyle.css
=> [Dark_Heresy] fix gihub links

Heroclix/clixSheet.css, Heroclix/clixSheet.html
Fixed Defense power issue pointed out by @mam882002 
Added Support for WWE Heroclix standard powers
Fixed UI issue where the populate button moved when the user clicked out of the Dial input box
=> [Heroclix] Fixed Defense powers, added WWE powers and fixed button movement

Harry Potter JDR/harryPotterJDR.css, Harry Potter JDR/harryPotterJDR.html
=> [Harry Potter] Bugfix

Les-Oublies/LesOublies.css, Les-Oublies/LesOublies.html
I have:
- fixed the images url (to the images of the Roll20 repo);
- fixed the attribute for the "notes" textarea;
- added an initiative roll;
- added the armor penality;
- added a line for the spells description.
- [ x] Is this a bug fix?
- [x ] Does this add functional enhancements (new features or extending existing features) ?
=> [Les Oublies] various fixes and adds

Stargate-RPG/Readme.md, Stargate-RPG/stargate.css, Stargate-RPG/stargate.html
Official sheet by Wyvern Gaming
Please ignore this PR (v1.1) , if #7079 was submitted in time to be accepted. #7079 was submitted few hours late to the weekly(but before you got to the end of the list). It Contains QoL improvements that would be **very nice** if they mad it to GenCon.
* prof checkboxes updates skills/saves when toggled
=> [Stargate RPG] v1.1 (this PR is redundant if #7079 was submitted in time)

Stargate-RPG/Readme.md, Stargate-RPG/stargate.css, Stargate-RPG/stargate.html
Official Sheet (Wyvern Gaming)
I know this PR was a few hours late to the deadline, but if possible, would be great if this could still get accepted this week so it make it to GenCon next weekend.
**v.1.2 (2020-07-27)**
* skills, saves, init, ac, ac_extra & moxie now update when their attribute changes. init is keyed to dex, moxie to cha.
* skills & saves that have been marked as proficient will now update when the prof bonus changes.
**v.1.1 (2020-07-27)**
* checking/unchecking proficency checkbox for skills/saves automatically adds/subtracts the proficiency bonus to the affected skill.
=> [Stargate RPG by Wyvern Gaming] v.1.2 (GenCon update)

whitehack/whitehack.css, whitehack/whitehack.html
=> Community guided updates.

Mork Borg/sheet.json
per https://github.com/Roll20/roll20-character-sheets/pull/7035#issuecomment-663337195
- [ x] Does the pull request title have the sheet name(s)? Include each sheet name.
=> Add myself to the Mork Borg authors

RWBY_RoC-Unofficial_Tabletop_RPG/RWBY-UnofficialTabletopRPG.html
Hello,
This is a minor update to keep the sheet up to date with the newest edition of the rules.
The only change to the sheet is a modification of the value of a damage roll.
Changed :
-Martial Arts damage 
-ver. number
-changelog
Thank you.
=> [RWBY_RoC-Unofficial_Tabletop_RPG] V.2.5.2 - minor stat change to match v.20.7.25

Ars_Magica_5th/Ars_Magica_5th.html
=> [Ars Magica 5th] weapon init rolls sent to turn tracker

Blades in the Dark/blades.html
=> [Blades in the Dark] Add Veteran to Whisper abilities

Hitos/hitos.html, Hitos/translations/fr.json
Replace `round` by `floor` for combat and health characteristics calculation according to Hitos core book.
=> [Hitos] Fix calculation of combat and health characteristics

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.html
- Added sheetworker code to auto generate entries in the resources repeating section on the equipment tab based on the context/universe selected on the configuration tab
- Added a list of superhumans types on the configuration tab and added sheetworker code to auto generate the corresponding entries in the resources repeating section and/or auto set hit dice type, magic ability, etc...
=> ChroniquesOublieesContemporain Version 3.3

approved.yaml
Adds Alice Is Missing to the approved.yml
=> Includes the Alice Is Missing game

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.html
- No functional or aesthetics enhancements
- Modified the sheetworker migration/update logic to revert back to semantic versionning
=> ChroniquesGalactiques Version 3.10

Beacon/beacon.html, Beacon/readme.md
Added Encumbrance rules, update inventory page.  Adjust beastman starting text.  Fix some layout issues.
Changes text, descriptions, changes coin weights, adds fields.  No changes to player data.
- [y] Does the pull request title have the sheet name(s)? Include each sheet name.
- [n] Is this a bug fix?
- [y] Does this add functional enhancements (new features or extending existing features) ?
- [y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
=> Beacon Update add Encumbrance rules

Fallout 3.5/Fallout 3.5.css
Background image link has been change due to old website terminated.
=> Update Fallout 3.5.css

Fallout (classic_pnp 2)/Fallout 2.0.css
Background link has been changed due to old website terminated.
=> Update Fallout 2.0.css

Fallout PnP 4.0/Fallout PnP 4.css
The background image has been changed because the old website terminated.
=> Update Fallout PnP 4.css

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.html, ChroniquesOubliees/sheet.json
* Global attack options
* parsing and use of modifier field in attacks
=> Chroniques Oubliees: version 3.4

urbanheroes/urbanheroes.css
[urbanheroes sheet] aesthetical improvement
=> [urbanheroes sheet] aesthetical improvement

Dark_Heresy/DarkHeresy.html, Dark_Heresy/DarkHeresyStyle.css, Dark_Heresy/translation.json
damage type in separate line
add gm roll
=> [Dark_Heresy] improvements

Torchbearer 2E/torchbearer.css, Torchbearer 2E/torchbearer.html
Fixing the following issues:
1. The Fresh status wasn't working correctly in rolls if it had never been checked/unchecked before on brand new characters.
2. The Fresh status wasn't working correctly when it was unchecked by no other statuses had been checked.
3. Trying to roll Nature was rolling Will.
4. Resources at rank 0 wasn't rolling.
=> torchbearer 2e bugfixes

D6_Adventure/D6AdventureSheet.html
Added Dice Mod and Pip Mod boxes/functionality
Improved wild die highlighting functionality
- [ X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [X ] Does this add functional enhancements (new features or extending existing features) ?
=> [D6 Adventure] Added a dice and pip mod box, improved wild die highlighting (#3)

Basic_Roleplaying/Basic_Roleplaying.html
A user of the sheet notified me that some of the images on the sheet had a "Broken Link" notification. I fixed it by finding or uploading new images to use on the sheet instead.
=> Fixing Broken Images

whitehack/whitehack.css, whitehack/whitehack.html
=> Feature Update

Basic_Roleplaying/Basic_Roleplaying.html
A user of the sheet notified me that some of the images on the sheet had a "Broken Link_ notification. I fixed it by finding or uploading new images to use on the sheet instead.
=> Fixing Broken Images for the Basic Roleplaying System

Godbound/Godbound.css, Godbound/Godbound.html, Godbound/README.md
Update to Godbound sheet to include space for Martial Strifes, Low Magic, and Theurgy.
=> Godbound v2.4.0

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- channelling list fixed, added metal lore, removed duplicate death lore. 
=> [Warhammer 4e Character Sheet] channelling list fix

Fallout PnP 4.0/Fallout PnP 4.html
=> Update Fallout PnP 4.html

Old School Essentials - AAC/CHANGELOG.md, Old School Essentials - AAC/OSE-AAC.css, Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where the strength bonus was not added to new melee weapons. Fixes wesbaker#49
- Fix a bug where strength and dexterity weapon modifiers didn't change when the attributes changed. Fixes wesbaker#49
- Fix colored borders shown for skill rolls. Fixes wesbaker#46
=> [Old-School Essentials by Necrotic Gnome] - 1.6.2

Dark_Heresy/DarkHeresy.html
=> [Dark Heresy] remove rounding

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.css, ChroniquesGalactiques/cog.html
- The statblock import logic has been partly rewritten and enhanced to be more water-proof
- The statblock import process is now run when clicking on a new action button
=> ChroniquesGalactiques v3.11

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.css, ChroniquesOublieesContemporain/coc.html
- The statblock import logic has been partly rewritten and enhanced to be more water-proof
- The statblock import process is now run when clicking on a new action button
=> ChroniquesOublieesContemporain v3.4

SotS/Swords of the Serpentine.css, SotS/Swords of the Serpentine.html
Fix Health and Morale tracks
Add True Name checkbox
Add Sorcerous Spheres box
Add Talent names
=> {SotS] Some Fixes and additions

Palladium Fantasy 1E/palladium_fantasy_1e.css, Palladium Fantasy 1E/palladium_fantasy_1e.html
I added a new tab called Structures.  It has a place to store info on a ship and track damage to various parts of the vessel.  It also has another section for detailing a structure or besieging force, and places to track damage to wall sections.  Both the ship and structure sections have a repeating attack section to set up siege weapon or arrow/javelin volley fire attacks.
=> Palladium Fantasy 1E

Dark_Heresy_2ed/DarkHeresy2ed.html
The sheet used floor to calculate str-bonus but did not calculated the value. This made the character sheet ignore the bonus and print out the calculation.
With the fix, the str-bonus is calculated and added to the reminder of the formula-
=> [Dark Heresy 2ed] fix not calculated str bonus for melee dmg

Magical-Kitties/sheet.json
=> [Magical Kitties Save the Day] description correction

Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css, Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html, Das_Schwarze_Auge_4-1/sheet.json
* **New features**
* Equipment tab features repeating section on shields and parry weapons (aad3536, 299ef40, c0f1523, 2e3ac6b)
* AT/PA values take shields and parry weapons into consideration (aad3536)
* AT/PA: Replace autocalculating fields with sheet worker scripts (1fcb528)
* Combat techniques take encumbrance into consideration (1f79a82, 70619d0, 609a5bc, 54387ae)
* Add special skills for Armour Adaptation I to III (1f79a82)
* Honour special skills for lefthand weapons, parry weapons and shield combat (aad3536, 23e110c)
* **Interface/Style**
* Melee values summary (a93399b, 1230c48, 9e24fae, 40ea6e6, 0ba0da0)
* Textarea for armour names for Armour Adaptation I (24705ca, 3b3f8c0)
* **Fixes**
* No more than one melee weapon active at the same time (aad3536, 99a5e59)
* (More) …
=> [Das_Schwarze_Auge_4-1] Shields, Parry Weapons, Encumbrance

TerraDevastada/terradevastada.css, TerraDevastada/test/test.css, TerraDevastada/test/test.html
fixing size of name input text for my Terra Devastada sheet.
=> [Terra-Devastada]fixing layout issues

Ultima Torcia - Pagina Singola/lutps.css, Ultima Torcia - Pagina Singola/lutps.html
=> [Ultima Torcia - Pagina Singola] Fixed firstWeapon dice error, added new diceRoll to Abilità and change textarea text-size to 18px

Godbound/Godbound.css, Godbound/Godbound.html, Godbound/README.md
* Small layout fixes and adjustments
* Fix missing style to "add" button for Weapon and Damage feildsets
* Faction Interests and Trouble changed to auto-expanding feilds
* Project descriptions changed to auto-expanding  and can be toggled to show or hide
* Readme updated with cleaner version progression.
=> Godbound v3.1

CWOD-M20/M20.html
**Sheet name: CWOD-M20/M20**
- Lots of whitespace autoformat changes by IDE - addition/removing spaces, indentations, etc to make code consistently formatted
- **Actual Change**: Line 1581:
Updated
` <fieldset class="repeating_Backs">`
to
` <fieldset class="repeating_Rotes">`
The repeating fieldset shared a name with one on the previous tab (line 1562) and led to odd behaviour when adding new data rows.
=> Bugfix for [CWOD-M20] sheet

Fallout/Fallout 3.0.css
Due to website's termination, the background image has been deleted. I have linked a new website to see the same background.
=> Update Fallout 3.0.css

Marvel Heroic Roleplaying/mhrpg.css
Add a new size of dropdown/select and adjust the layout slightly
=> Update Marvel Heroic Roleplaying mhrpg.css

Marvel Heroic Roleplaying/mhrpg.html
Correct some terminology and add two dropdowns/selects for marking when power traits are stepped back, stepped up, or shut down
=> Update Marvel Heroic Roleplaying mhrpg.html

Harry Potter JDR/harryPotterJDR.css, Harry Potter JDR/harryPotterJDR.html
=> [Harry Potter JDR] Bugfix + update avantages

Alien Roleplaying Game/Alien-Roleplaying-Game.css
Updated the font to Roboto, no functionality changes at all.
=> Alien character+visuals

nechronica/nechronica.html
* Act Dice Result Modify : Critical and Fail
- [ O ] Is this a bug fix?
=> Nechronica Dice Result Modify

Strato Shout/stratoshout.css, Strato Shout/stratoshout.html
* Error Test Modify
* Add - Over Damage Check Box
- [ O ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ O ] Is this a bug fix?
=> Strato Shout : Bug Fix

Dark_Heresy_2ed/DarkHeresy2ed.html
=> [Dark Heresy 2e] fix minor location error

Ultima Torcia - Pagina Singola/lutps.html
=> [Ultima Torcia - Pagina Singola] Fixed varables in Ability with "cx" at the end and ability_name in Abilities

CriancasEnxeridas/criancasenxeridas.css
Some minor layout fixes for Criancas Enxeridas sheet.
=> [criancas enxeridas]Minor layout fixes

Godbound/Godbound.html, Godbound/README.md
- Missing entry for spending effort on invocations added
- New misc effort entry added to track healing and other effects
=> Godbound v3.2
