Roll20/roll20-character-sheets

- SavageWorlds-Tabbed/SW_CharSheet-tabbed.css
- SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Added support for cyberpunk settings by adding Strain and Augmentations as well as Street Cred (for Interface Zero 2.0). 
Added the IZ2.0 Logo as an option. 
Included a couple new Backgrounds. 
Reorganized the CSS so that it’s more logical its groupings. 
Added a Skills Modifier to the Wild Card skill area and a new heading for Skill Rank.
Added an Unshaken Modifier and roll button to the Basic Info Tab.
> Additional Setting Support and CSS Cleanup

- Anima-Beyond-Fantasy/A-BF.html
Corrected Weapon Attack damage calculation.
Corrected Weapon Fortitude calculation.
Corrected Ki Detection formula not properly using order of operations.
Corrected Weapon Breakage to allow negative values. Useful for some weapons such as the whip or net, which have negative breakage.
Corrected resistances to account for Body of Emptiness automatically.
> Updated inaccurate fomulae

- Anima-Beyond-Fantasy/A-BF.html
-Corrected Martial Arts damage calculation for characters with ki abilities
-Added Ki abilities for elemental attacks based on Light and Darkness
-Added modifiers prompt for basic attack/block/dodge rolls to better work with martial arts
-Added modifier prompt for projection rolls for consistency w/ attack/block/dodge
-Corrected weapons to prompt for fatigue before other modifiers to reduce possible user confusion.
-Corrected ranged weapon fortitude being based on melee weapon quality (and the wrong multiplier besides).
> Martial arts and consistency corrections

- Anima-Beyond-Fantasy/A-BF.html
Added attributes for tracking daily Zeon Regeneration when active creatures/ spells are used. Declaring these attributes somehow missed the initial quality check.
> Added Creature/Spell regen attributes

- Microlite20/microlite20-test.html
- Microlite20/microlite20.html
- Microlite20/readme.md
- Microlite20/sheet.json
The changelog says it all.  I added more roll buttons, and also put restrictions in to add extra bonuses if you chose human as your race and/or chose fighter as your class.  I removed the spell section, since the rules of microlite state that you have access to ALL spells at your given level.  The only way to make use of that section would be to painstakingly add every single spell to the section, effectively making a really really long character sheet.  Not really all that useful.  There's a table in the rulebook that shows you how much each spell level costs, but I wasn't sure if I'd be allowed to include such a table in the character sheet.
Also added Saving Throw rolls, and added in the strength bonus to melee damage rolls.  Modified the attack rolls to include light weapon melee …
> Added even more functionality - Microlite20

- Witch_Hunter_2e/WH_2e.css
- Witch_Hunter_2e/WH_2e.html
> Fixed the Skill row alignment; made tables out of everything so now
it should be bullet-proof.
> Added an Advancement tracker inside the Survivor Point section.
Decided against creating a whole new tab since that feature is giving
me headaches on Firefox. Test it out. Because its a repeating field, I
can't make it calculate the whole SP cost total, but it should tell you
the SP cost based on the type of improvement.
> Added "vs Target Discipline" to Charm, Command, Empathy and Perform
rolls. I thought this would be a good reminder (for me as much as
anyone) but it wouldn't require you to target a token on the screen.
It's just a prompt to remind us what Defense affects those skill rolls.
> In the Skills/Talents section, I've added an expanding field called
GM Rolls. This is identical to …
> Witch Hunter Character Sheet Updates

- Microlite20/microlite20.html
- Microlite20/readme.md
M20's rulebook stated that on every level advancement, you had to add +1 to your skills and attack rolls, and +1d6 to your hp.  Unfortunately, this was written for people doing it on pen and paper.  For attack rolls in roll20, those are already calculated.  The +1 will happen naturally with the advancement of a level due to how the attack rolls are calculated.  So, me adding an additional +1 per level was actually incorrect.  Had to remove that.
> Microlite20 - Bugfixes, Additions, and Visual Rearranging

- Cyberpunk 2020/Cyberpunk2020.html
Added a second attack button that doesn't require a roll-able table
Also added tool tips to explain it.
> Added non-roll table button

- Cyberpunk 2020/Cyberpunk2020.html
Kept the old, old before-I-got-here damage table!  This is important because my previous changes were not good.
* Minor change to the damage table: Light Wound checkbox has a value of 1, because a value of "0" would result in a random checking.  LightlyWounded attribute was removed from all equations; it was adding "0" or "0", so there should be no effect.
Cleaned up the roll template a little.
All stats now have an button.  
Added "Mortal 0" damage track.  It was missing from the beginning.
Added a 'Simple' save button.  All it does is roll a d10 plus a modifier and shows the body stat.
Cleaned up the second weapon button; now rolls a d10 for hit location.
> Better Update

- Pathfinder-Neceros/pathfinder-neceros.html
added attacks to pf_spell roll template that matches the pf_attack roll
template format. attack and attack2 can be used within a macro using
pf_spell for spell-based attacks. (attack. damage, crit_confirm, crit_damage)
> Pathfinder-Neceros: Updated pf_spell to include attacks

- pathfinder_simple/pathfinder.html
repeating_lvl-5-spells fieldset class was incorrectly set to repeating_lvl-0-spells which caused repeating_lvl-5-spells descriptions to be overwritten by repeating_lvl-0-spells description.
> pathfinder-simple small patch

- Anneau Unique/sheet.html
"Combat values" was lost in translation.
> Anneau Unique / The One Ring (french) v1.1

- Pathfinder-Neceros/pathfinder-neceros.css
- Pathfinder-Neceros/pathfinder-neceros.html
- added toggles for Saving Throws to include DR, Resistances, Immunities, Weaknesses, SR,
Armor notes, Save Notes, CMD Notes, Defense Notes.
-   added toggles for all Spell attributes (repeating items only for now) will add global toggles for Spell button bar
-   placed all toggles in an Options[hide/show] directly under their applicable section.
-   added iterative attacks to the NPC section.  NPC attacks are linked to the Attacks tab, so if you want NPC attacks whispered, you need to add "/w gm" at the beginning of the macro text.
Might add a toggle to whisper all attacks which would be good for NPC's.
-  added CMB as an attack-type option. 
-  added spellclass selector (attr_spellclass) to spells to show the proper spellclass of the spell in output. This was previously showing …
> Pathfinder-Neceros updates

- Deathwatch/Deathwatch.html
40k rpgs have two systems for using characteristics; one uses the raw with misc modifiers. The other uses the characteristic bonuses (First Number). The problem is how this sheet is done does not take into consideration what those bonuses do. EX: Strength bonus for a Space Marine is Strength x2 +20. But it reads off the raw characteristic not allowing for modifiers of those bonuses. The changes here allow the player to input those bonuses and make the system that use them read off of that.
> Changed Unnatural Attributes to Bonus.

- Kobolds Ate My Baby/Kobolds Ate My Baby.html
- Kobolds Ate My Baby/sheet.json
Added Link to Roll20 Wiki Kobolds Ate My Baby Character Sheet wiki page and changed Version Number in HTML.
Updated sheet.json to Include Link to Kobolds Ate My Baby Character Sheet Wiki page on Roll20 wiki and show sheet version number in the Character Sheet Description.
> Updating Kobolds Ate My Baby HTML and sheet.json

- D&D_4E/D&D_4E.css
- D&D_4E/D&D_4E.html
- D&D_4E/sheet.json
* Changed Gender Field from a Select Field to a Text Field.
* Added a “None” to the AC Select List in the Settings Tab. The value is set to Zero “0” and is set to selected.
* Added a “Tie Breaker Select in the Settings Tab.
* The Initiative roll was changed to add the bonus value of @{initiative}*@{init-tie}. Multipling the initiative bonus by either 0 or 0.01 depending on the selected value and adding it to the initiative roll.
* Added a Magical Per Plus Die Size to the Weapons in the Inventory Section. Users will be able to call this value into macros for critical damage calculations.
* Added Roll Template information under the Powers in the Powers Tab.
* Changed Emote text in the Settings tab to work with Roll Templates.
* Added Roll Templates to the character sheet.
* Changed the …
> Updated HTML and CSS

- Dark_Heresy/DarkHeresy.html
- Rogue_Trader/RogueTrader.html
The numbers in the paper doll are not correct. I suspect this is true of (at least) Deathwatch and the other 40K systems, but I don't have the sourcebooks for them.
> fix hit location values in Dark Heresy 1e and Rogue Trader

- Stars_Without_Number/ReadMe.md
- Stars_Without_Number/Stars_Without_Number.css
- Stars_Without_Number/Stars_Without_Number.html
- Stars_Without_Number/sheet.json
I won't claim it's the best in the world, but it'll do.
In this PR:
* a multi-tab implementation
* a tab with a basic implementation of ship character sheets. Including:
- All basic data (Name, Hull Type, AC, Armor, Crew Min/Max, HP, etc)
- A section for additional notes
- Repeating fields for Weapons, Defenses, and Fittings.
- A second section for more notes (you can never have enough space for arbitrary notes)
* an updated changelog + sheet.json (I forgot to update it last time)
What it doesn't contain:
* Roll macros for any of the ship stuff (that would require some way of syncing the ship between character's, so you could use the right gunnery stat, etc). Fortunately, there isn't a great deal needed there besides damage; so it could be done.
* Great CSS. The repeating fields don't …
> Stars Without Number -- Ship Sheet Implementation

- D&D_3-5/charsheet_3-5.css
- D&D_3-5/charsheet_3-5.html
Added notes areas for saves and skills to use in the roll template notes
property.  Added support for epic levels by adding Epic Save Bonus and
Epic Attack Bonus.  Switched some value= to placeholder= to make text
fields a bit more friendly to edit.  Adjusted the size of several fields
and removed some redundant styles.
Also added additional checkbox to CSS to support the save notes.
> D&D3.5 update, cosmetic +

- DungeonWorld/DungeonWorld.css
Added a single line to force disabled input fields to use textbox appearance to avoid input spinners in those fields when using Firefox
> Fix for Disabled Fields in Mozilla

- D&D_3-5/charsheet_3-5.css
- D&D_3-5/charsheet_3-5.html
Reverted old pull due to an issue/mistake I made with the repository. 
This commit has fixes to solve the spacing/alignment issue previously 
seen in Chrome, reverts the colorizing of the skill rank box at zero 
ranks for trained only skills (and thus solves the error it produced), 
fixes the appraise macro issue, etc.  Also standardizes spacing in 
CSS file.
> D&D3.5 Spacing fixes, color/error fixes etc

- Exalted2e/exalted2e.css
- Exalted2e/exalted2e.html
In FFX, repeating items with flexboxes below floating content weren't
beginning below the floated content. Additionally, "header" widths for
several repeating sections had incorrect widths, and intimacy repitems
weren't flowing correctly..
> Correct repeating item flexboxes & widths for FFX

- Numenera_NathasNumenera_English/NathasNumenera_tabs.css
- Numenera_NathasNumenera_English/NathasNumenera_tabs.htm
- Numenera_NathasNumenera_English/ReadMe.md
- Numenera_NathasNumenera_English/sheet.json
- Numenera_NathasNumenera_French/NathasNumenera_tabs.css
- Numenera_NathasNumenera_French/NathasNumenera_tabs.htm
- Numenera_NathasNumenera_French/ReadMe.md
- Numenera_NathasNumenera_French/sheet.json
By popular demand, the basic (non API) stat/skill roll template has been
unified and only rolls one d20 dice (for the 3D dice users out there),
whatever is the "Difficulty" roll parameter from the "Action" section.
If the difficulty parameter has been set to 0, the beaten difficulty is
no longer calculated (due to Roll20 limitations), but the raw d20 dice
is shown, as the special natural rolls (1 or 17+), and the steps
modifiying the difficulty are displayed (and summed).
New (small) API button to reset Action parameters.
> Numenera tabbed v4.8: unified basic roll template

- Stars_Without_Number/Stars_Without_Number.html
In response to #1032. 
Quick patch to stop a few repeating fields from having the same name.
Weapons, Defenses, and Fittings were all labeled as "repeating_weapons". Defenses and Fittings were given their own repeating values. After some testing in roll20, the issue seems to be fixed.
> #1032 Patch

- Swords_&_Wizardry/SWSheet.html
I fixed the spelling of "Deity" but only in the label (did not change the form field's attribute, in other words).  Apparently there was some spurious whitespace in there, too.
> Fix spelling of Deity (label only)

- Stars_Without_Number/Stars_Without_Number.html
Fixed checkboxes in the gear section with value set to 0 causing roll20 to always set them as checked after they were checked once.
> SWN: Fixed "Always readied" gear

- AD&D_1E/1ESheet.css
- AD&D_1E/1ESheet.html
- fixed repeating sections to comply with new roll20 update
- removed preset attacks.  No longer necessary with update.
- added a background option
- added a few new sections (wealth, equipment,special abilities, spells,
notes )
- movement and encumbrance(plan to add auto-calc weights from euipment)
- special abilities, and spells are only textarea now, but will updated
with more fields soon.
> AD&D1e updates

- pathfinder_simple/pathfinder.html
- rolled back my changes to repeating attribute names (this was not
necessary)
- only titles of the repeating attributes have been changed to include
"$"
- kept previous change to damage mod selection and attention text
> Pathfinder - Simple

- fate_core_with_rolls/fate_core_with_rolls.html
- fate_core_with_rolls_VF/fate_core_vf.html
fix for unicode symbol ± not being display correctly on Fate Core Character sheet with roll in english and in French
>  fix for unicode symbol ± not being display correctly

- Pathfinder-Neceros/pathfinder-neceros.html
- minor formatting updates
- added "none" option to Init ability selector
- changed "Non-lethal DMG" to "Nonlethal DMG" to help a little with the
forced line break
- changed the size and default value of the class selector for repeating
class abilities and adjusted some column sizes to compensate
- changed default of Attack type to melee and Damage ability to STR
(these were set to none previously to force users to change them due to
repeating section limitations) None is still an option.
- added additional labels to NPC skills and enlarged some of the
"field-only" skills like craft, perform, profession, misc...
> Pathfinder v19

- CWOD-W20/W20.html
This fixes the dice rules used in the buttons on the Character sheet.
Werewolf 20 does not use exploding dice (either for normal rolls or
specialties)
The buttons also neglected to use the 1s subtract from successes rule
standard to classic world of darkness (with the exception of damage
rolls). Buttons have been modified to correct this.
An extra Bruised health box has been added to accommodate users with the
Huge Size merit.
> Dice Rule Fix + Extra Bruised Health Level

- DungeonWorld/DungeonWorld.html
Modified the Dungeon World sheet automatic modifiers to better match the table in the book. This fixes discrepancies for stats lower than 5, correctly setting the modifier to -2/-3.
For full calculations/demonstrations, see this gdoc:
https://docs.google.com/spreadsheets/d/1EnI0PmM7sgqAPYxGdS94O2jvUQhYQrTruRB1iXh0Cxo/edit#gid=0
> DungeonWorld character sheet modifier calculation tweak

- pathfinder_simple/pathfinder.html
- Total HP, @{HP|max} has been changed to @{HPCurrent_max} so that HP
can be properly linked with token bars. This conversion is handled
automatically using sheet workers to verify the version of the sheet and
updating @{HPCurrent_max} with the value of @{HP|max}. Once the sheet
has been updated, any changes made to @{HPCurrent_max} will also be
reflected on @{HP|max} for backward compatibility.
- Added a Carried coins area and they will be included in Total Weight and encumbrance.
- The Critical damage roll has been changed from simply multiplying
damage based off of the crit multiplier to rolling damage once(w/mods),
and prompting for additional damage(w/mods), x2, x3, or x4 damage.
> PF_simple - HP|max fix, carried coin weight, crit damage roll query

- Iron Kingdoms RPG/IKPRG.html
Adds: 
Sheet workers!  Some, not all.
Button to set health to what is listed in base physique, agility, and health.  And a button to reset all health boxes to empty
Power field easier to see.  
Moved the feat tracker to the top bar.
Put arrows in the top bar to control the the feat tracker.
All skills are no roll templates, plus the ability to edit the text of the roll template.
Whisper to GM rolls for all skills, attack rolls and spells.
Added Efraarit, Blighted Orgrun, Satyxis,and Striders to racial selection.  
All racial and Archetype abilities can now be displayed in chat.
Spells & Fell calls will only display what you want to when rolled
F/X on spells!  You will need a pro subscription to use them, and they are 'off' by default.  
Cleaned up the weapons a bit
Multiple armor …
> Massive IKRPG update

- OVA/OVA.html
Due to a problem with Sheet Workers not updating the character sheet
via a token bubble, removed the token action roll button until that’s
fixed.
> Removed Token Action

- Der Eine Ring/sheet.html
Repeating sections didn't work with macros as macros needed numbered
attributes. So I replaced the repeating sections with a fixed weapon
list for NPCs. So they are identical to the PC sheets now. There is
place for 4 weapons which should be more than enough.
Furthermore I added call for target numbers to all sheet rolls and fixed
a small copy-paste error.
> Replaced repeating sections with fixed weapon slots for NPCs

- Dark_Heresy_2ed/DarkHeresy2ed.html
Currently the base characteristics rolls were adding the value of the advance in that characteristic, but it wasn't reflected when using the skill rolls. This made this change necessary in order to align the sheet so both rolls have the correct target value.
Removed the advance from the Influence characteristic since it can't be upgraded this way like all other characteristics and this drop down menu is pointless.
> Adjustment of the base Characteristics rolls

- Mutant Year Zero Alternative/MutantYearZeroAlternative.css
- Mutant Year Zero Alternative/MutantYearZeroAlternative.html
Arrows on input boxes for core attributes and skills were set to 100% opacity and were hiding values once entered on some browsers.
Also, added sheet workers to auto-fill max trauma with changes to core attributes and test for incongruent max trauma values on sheet load. 
Made text areas vertically resizable.
> Removed forced 100% opacity on input arrows - Mutant Year Zero

- WFRP-2nd-Ed/WFRP-2nd-Ed.html
Two bugs quietly lurked in the WFRP 2e character sheet. One incorrectly referenced a calculated value that populated an underlying attribute used in macros.
The second reversed the values of the number of wounds that could impact health bar display.
> Fixed two bugs in WFRP 2e character sheet

- 13th Age Official/13th_Age_Official.html
For use when people are adding spells, this change adds additional options to the Attack selector, letting people select which statistic to use.
Since this selector doesn't actually lookup which option people use for Melee attacks, I also changed the text to specify that Melee means STR and Ranged means DEX.  I feel it really should go look that up since players will have selected this earlier, but I can't currently work out how to do that.
(Apologies for the github fail in calling this branch the superdescriptive "patch-1", it's my first pull request.  You can see I got better on the second!)
> add attack options for all stats not just STR/DEX

- 13th Age Official/13th_Age_Official.css
The sheet power labels are set to 100px, but there's space in the form for about 160px according to the other CSS.
Since 100px cuts off lots of power/spell names, let's use that extra space please.
> Widen .sheet-powerlabel .sheet-label

- DragonQuest/DQSheet.css
- DragonQuest/DQSheet.html
- DragonQuest/readme.txt
v1.1 - 2016-04-07
Simplified attributes - removed unnecessary prefixes for attributes in repeating sections
Fixed display issues in Firefox
Changed summaries to update when options tab is closed, as new items didn't run an 'on change' command when defaults were used
Changed order of fields in roll templates to have fixed data at the top and rolls at the bottom
Tidied up the css to remove some of the repeated information
Re-ordered the script workers to follow the order of the html elements
> DragonQuest v1.1

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.css
- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Verbesserungen in Umsetzung bestehender Regeln:
- Entfernungssinn in Fernkampf-Tab berücksichtigt
- Herausragender Sinn explizit auf Einzelsinne gesplittet
- Mag. Einstimmung und Mag. Einschränkung als spezielle Modifikatoren in Zauber- und Rituale-Tab berücksichtigt
- Zauberzeichen (Schutz- und Bannkreise) hinzugefügt
Neue Regelelemente aus Abenteuern hinzugefügt:
- Tradition Goblinzauberinnen inkl. neuer Rituale
- Tradition Zibilja inkl. neuem Ritual
- 4 Liturgien des Namenlosen
- Zauberzeichen Verschluss
- Sonderfertigkeiten Leg-ga-leg und Bine Maschores
> Minor improvements and new rule elements from recent adventure books

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.css
- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
- Anzeigeoption "Gegner-Sheet": Versteckt die Tabs Inventar, Notizen. Zeigt vereinfachte Ansicht der Grundwerte und Kampfausrüstung.
- Anzeigeoption "Reduzierte Talentansicht": Zeigt im Talente-Tab ausschließlich die für nicht-humanoide Gegner gängigen Talente.
- Flag "Nicht-Humanoider": Option nur verfügbar in Gegner-Sheets, ersetzt Ausweichen, Waffen- und Schildparade durch Verteidigung.
- Kampf-Sonderfertigkeiten aus Bestiarium ergänzt
- Zauber Dunkelheit und Große Verwirrung ergänzt
> Added Options for NPC management and a couple of missing skills and spells

- Der Eine Ring/sheet.html
Now you can enter 2 mounts according to the Rohan supplement and roll
for a charge as an attack. The riding modifier is automatically
substracted from the TN. The reduced encumbrance is not calculated
automatically as it applies only on armour and only when mounted - so
you have to do that manually via the inventory.
> Added mounts to the german char-sheet

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.css
- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
- Das_Schwarze_Auge_5/sheet.json
**Allgemein**
- Einführung von Sheet Worker, d.h. viele Werte werden nunmehr per Sheet Worker statt "autocalculated field" berechnet. Dies erlaubt insbesondere auch mehr Flexibilität beim händischen Ändern von berechneten Werten. Es kann sein, dass durch die Umstellung einige Werte noch nicht neu berechnet wurden, hier kann aber durch kurzes hin- und herändern von abhängigen Werten eine Neuberechnung erzwungen werden. Die neue Version beinhaltet aber auch erstmalig ein Update-Skript, das dazu gedacht ist Änderungen von der alten auf die neue Version automatisiert zu übernehmen.
**Anzeige / UI**
- Konfigurationen Verstecke Magie und Verstecke Götterwirken: AE/KE werden jetzt im Tab Grundwerte ebenfalls ausgeblendet
- Konfigurationen zur Anzeige von Schilden, Parierwaffen und Fernkampf …
> [DSA5] Integrated sheet workers, UI improvements, minor feature additions and bugfixes

- Blades-in-the-Dark/README.md
- Blades-in-the-Dark/blades.html
- Blades-in-the-Dark/sheet.json
This update improves the robustness of the Blades in the Dark macros by handling additional roll cases for actions.  The macros will now auto-detect if an action has zero (0) or few dice and revert to the 2d6 keep lowest rule.  Additionally, macros for resistance rolls have been added.
> Blades in the Dark Macro Updates

- D&D_3-5/charsheet_3-5.css
- D&D_3-5/charsheet_3-5.html
Add Notes section for Ability Stats and moved them and the macro to a toggle-hidden area, adjusted/fixed calculation for dex penalties for flatfooted and immobile AC.
> D&D3.5: Flatfooted/Immobile AC calc fix + Ability Notes

- Pathfinder (Old)/pathfinder-old.html
- init total and init-misc were being added to initiative rolls.
- removed the **target** requirement for PC initiative rolls.  Using target seemed unnecessary...
- fixed init value to use init-DEX instead of DEX-mod.
- matched NPC initiative macro to PC
- added DEX field near NPC init for clarity
> PF legacy Init fix

- Pathfinder-Neceros/pathfinder-neceros.html
One line is causing red attack rows to be created. This fixes the one line, so people wont' see tons of red attacks at the con, if you push this out.
> Pathfinder 1 line emergency fix

- D&D_4E/D&D_4E.html
Updated the following fields to be player input:
Bloodied, Surge Value, Fort/Ref/Will Ability value
Updated the following names:
"Attack Weapon" -> "Weapon Attack Bonus"
"Damage Weapon" -> "Weapon Damage Bonus"
"Weapon # of Dice" -> "# of Dice"
"Weapon Dice Size" -> "Damage Dice Size"
Added the following options to power dropdown options:
None option for "Weapon Attack Bonus"
None option for "Weapon Damage Bonus"
1-10, and 1-5*WeaponX for "# of Dice"
d4, d6, d8, d10, d12, and d20 for "Damage Dice Size"
Removed Extra line in powers (d6+power damage)
> Update Labels, power drop down options, and allow some fields to be player input

- Deadlands Classic/deadlandsclassic.css
- Deadlands Classic/deadlandsclassic.html
- Deadlands Classic/sheet.json
This just removes the redundant repeating fieldset buttons, adds the default values for some aptitudes in parenthesis next to the  aptitude name, and some other minor cosmetic fixes, on the Deadlands Classic sheet.
> Minor fixes

- AD&D_2E/2ESheet.html
In Firefox the HP was not visible for henchmen, changing this to use the same class as other number fields such as current weight fixed this
issue.
> Fix hench HP

- MAGUS_UTK/MAGUS_UTK.html
1. Modify the defense system, which earlier used a d100 instead of a constant value of 60.
2. Fix the skill system, where throws added a [Skill level]-2 modifier to every skill throw. However, as it turns out, there are a few skills, for which this is not applicable, so the skills will require the players to input their modifiers via a prompt.
3. Change the title of the last column of the weapon tables from "Lefegy." to "Átütés". It was a duplicate.
> Urgent fixes in defense and skill systems.

- Stars_Without_Number/Stars_Without_Number.html
Fixes the weapon fields to properly calculate attacks using attribute modifiers and skill levels. Also added drop down menus for these fields so they can be changed on the fly in certain circumstances. Minor Fix: the "Strength Modifier" will now default to 0 instead of being blank. Updated the sheet version to 0.1.1 as the original author informed me the version was wrong.
> MG: Fix and Update Weapon Fieldset

- Nightshade Academy/nightshade.html
Remove a skills section of the char sheet that has been replaced by a more usable UI and has been marked as deprecated with a warning not to use it since March.
> Nightshade Academy - Remove deprecated skills section

- White Star/White_Star.html
Player notes weren’t saving, because I forgot to make them an attribute. This has now been corrected.
> Made notes an attribute

- Pathfinder-Neceros/pathfinder-neceros.css
- Pathfinder-Neceros/pathfinder-neceros.html
1. fix "spells known" on spellclass tab 1 for spell levels 0 and 1 (row 0 was displaying row 1)
2. fix tab 1 was defaultinstead of tab 0 for class features and spellcasting classes
3. change cr import so it won't overwrite user changes, made CR and Metadata ranks text fields
4. removed nonbreaking space codes from in front of armor and shield placeholders
5. fixed width of "is npc" checkbox label
6. fixed "iterative attacks" arrow which was not changing
> Pathfinder v.63

- 13th Age Official/13th_Age_Official.html
I don't have the ability to directly test these changes and how they interact with other operations, but the calculations themselves work and have a rather dramatic performance gain. I encountered issues as a GM using the AC/MD/PD and serious delays in UI responsiveness after attempting to execute macros using those values.
Using the history, first use of ABS in 13th age sheets comes from ea32475ee90052d49bc375a8f7bef643675cfcff.
Commit message explanation copied here:
> This commit removes calls to ABS in internal attributes in favor
of other built-in functionality: dice calculations.
> Calls to ABS suffer from performance issues, with AC/MD/PD calls
taking upwards of 10 seconds. When changing these to use the
built-in dice calculations, there are no noticable performance
issues.
> The …
> Remove ABS calls in 13th Age Official

- ChroniquesGalactiques/cog.htm
Le menu déroulant pour les jets de capacité liste SAG au lieu de PER.
@NathaTerrien
> Fix SAG used instead of PER

- Rogue_Trader/RogueTrader.html
There was an issue with some duplicated stuff and incorrect tabbing that was causing issues with the Psychic Powers part of the sheet, making it so that you could never use it correct due to there being two instances of Psychic Disciplines and Psychic Techniques at all times.
> Fixes an issue with the Rogue Trader character sheet

- Open Legend Basic by Great Moustache/Open Legend.css
- Open Legend Basic by Great Moustache/Open Legend.html
- Open Legend Basic by Great Moustache/ReadMe.md
* Modified power level to have a min and max value to input
- Success message in chat output based on min value, but tells you for
both.
* Added another actions section
- Renamed Actions to "Favored Actions"
- Created "Other Actions"
- Allows players to better organize their actions, and with 1.6.8, hide
so less cluttered
* Added checkbox within actions if you need to specify a power level to
roll at (for boons)
- Roll templete now will tell if you were Successful, or Failed to reach
the power level
* Added a graphical change (blue highlight) to show which Physical
Attribute is using substitution
* Added "check boxes" to show/hide different areas of the sheet
- Allows players to only see the information they want at a given time
> Open Legend: Display Options & Actions update

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
- fix for attr_NKW_AT_typ1 and attr_NKW_PA_typ1 not giving the
appropriate value for "Zweihandhiebwaffen";   renamed option values to
match the existing attribute names.  @{AT_zweihand-hiebwaffen} and
@{PA_zweihand-hiebwaffen}
> DAS 4_1 bug fix

- Only War/Only War.html
Rolls to hit now provide dropdowns for difficulty modifiers, prompting for bonuses from aim or attack range as well as final modifier dependant on other conditions, simplifies the process.
The base of the sheet now includes common weapon damage formulas for special effects such as tearing, proven, primitive and 1d5 weapons. These can be placed in the current "Damage" fields without requiring additional code. 
Position of Size dropdown now more aesthetically pleasing.
> Update Only War C

- Fallout/Fallout 3.0.html
I was playing with this sheet and came across with some bugs related to skill roll section. I saw Unarmed skill using different skill's value changed that to original as well as throwing skill. So they are now using their own values for rolling. Athleticism and barter skills have bugs too. When rolling for them in the chat we saw them as wrong name. Like Barter skill was the name of smallguns how evet their values are correct, so I only changed names.
> skills dice roll fix

- Dark_Heresy_2ed/DarkHeresy2ed.html
Large number of corrections in line with work carried out on Only War sheets including:
Characteristic advances no longer pick up on the chosen advances. This would previously happen in some but not all cases.
Replaced characteristic tickboxes with Unnatural Attributes numeric input
weapon skill damage picks up on unnatural strength
move speed picks up on unnatural agility
total armour soak picks up on unnatural toughness
fatigue threshhold picks up on unnatural toughness
Replace characteristic rolls with dialogue including additional degrees of success
Character size dropdown included, will directly influence stealth rolls and move speeds.
Updated to reflect degrees of success accurately (0 additional is a successful roll, 1 additional is an additional degree of success.
Rolls to hit …
> Update DH2E 2017

- Fallout (classic_pnp 2)/Fallout 2.0.html
1- Roll button for statics was 12. Due to Fallout PnP I changed it back to 10, as it should be.
2- When you roll for skills, the dice was always rolling 1. Not more not less. Now I change it to 1d100 and modifiers so it will roll as it should be.
3- Same as 2, but this time it was for weapons both left hand and right hand. I changed them to 1d100, so now they will work just fine.
> Bug fixes for Fallout 2.0 rolling system

- Shadowrun-Anarchy/Shadowrun-Anarchy.html
The auto-roller behaves strangely with nested formulas and was rolling 2 dice for this instead of the displayed number. As with the other rolls, I've expanded the formula into the roll itself and verified that the new behavior is correct.
> fixed Initiative roll

- GURPS/gurps.html
The Grimoire page introduced a bug where all skills were effected by the Grimoire page settings.
ACTION NEEDED: If you opened a character sheet with the new Grimoire tab, then two Attributes were created "base" and "bonus" you will need to delete these from your attributes tab before your character sheet will begin to function properly.
> [BUG FIX][GURPS] Fixed issue where Spell setup effected all skills.

- CWOD-W20/W20.html
Fixed the player/name issue
Added roll templates to pretty much everything.
Roll button for Gnosis, Rage, and all that are more visilbe
One click transformation is the name (Homid, Lupus, etc).
Replaced health boxes, added wound penalties
Wound calculations all dice pools, weapon attack and damage, and claw weapon and damage. Willpower, Gnosis, Rage and all soak roll are unaffected.
Put the Brawling combat stuff under a claw marker.
Rebuilt the common dice pools. Should not damage the dice pools. You can pick and choose if you want the query or not.
Re-colored and renamed the attack and damage rolls, so its easier to find them.
...and I am sure I missed something.
> W20 fix & upgrade (no attribute name changes)

- GURPS/gurps.css
- GURPS/gurps.html
Resized several fields on the "General" tab to make major Attributes Stand out, give room for new fields
Added 2 "blank" stats for user pools like Energy Reserve or Blood Points
Added Lifting ST and Striking ST
Added step values for attribute costs, so users can just press up or down and get the right cost per level.
Updated the "Current" line in the Encumbrance box to show the current encumbrance level, load, move, and dodge.
Changed many of the auto-caculated fields to be updated by helper scripts.
Added first time script to run when sheets are opened and populate values for formerly caculated fields. This will also initalize any "blank" values from reapeating sections that are missing the default values now.
> [GURPS] Major Update

- Open Legend Basic by Great Moustache/Open Legend.html
- Open Legend Basic by Great Moustache/ReadMe.md
Took out Sanity Points as this was not Core Rules.
Also took out Attribute dice calculations for 11, only meant to go up to 10.
> Open Legend: Sanity Out

- Dark_Heresy_2ed/DarkHeresy2ed.html
Currently, the Dark Heresy second edition sheet does not add any modifier value given, nor does it properly calculate the effects of manifesting a psychic power at a rating that is different to the character's base Psy rating. This change aims to fix that.
> Fixing math on Focus Power test targets.

- Iron Kingdoms RPG/IKPRG.html
- Remove SPD, DEF, ARM modifiers from the Shield section since they
don't apply to shields (shields are weapons, not armor).
- Remove shield DEF and ARM modifiers from the derived stats
calculations.
@CoalPoweredPuppet FYI
> Iron Kingdoms RPG - shield modifiers and derived stats

- Marvel Heroic Roleplaying/mhrpg.html
Changed distinctions to a Form, so now it is possible to use NPC distinctions (d4) and mob/large scale thread distinctions (multiple dice).
Fixed the dice range for both trauma and stress (it should go from d4 to d12 for each option, plus 0 and Dead/Out).
Changed Specialties to Repeating fields, as Marvel Heroic characters have very few of those. Also, fixed the range from d4 to d12, to include the Grandmaster level introduced in the Annihilation core book.
> Fixed rules errors in to make the sheet playable

- Exalted 3/Ex3-Sheet.css
- Exalted 3/Ex3-Sheet.html
Prevent overflow for crafting/MA
With teh Cimiez font, the "Show Crafts"/"Show Stlyes" text are wholly
contained within their buttons. If Cimiez is not loaded, the text
overflows onto the next ability.
Prevent horizontal scrolling without Cimiez
xp/sxp line was causing horizontalscrolling with the default character
sheet window size when Cimiez wasn't available.
Fixed issues with resizing charsheet dialog
Fixed horizontal scroll issue w/o Cimiez font
Removed spinners from FFX number inputs
> Exalted 3e sheet v2.1 updates

- DresdenFilesAccelerated/DFA.html
The change broke the roll buttons, but fixed the Fate Point calculations.
Rolling back the changes to the approaches.
Changed Mantle approach to fixed text because it never saved what was inside the text box. Also changed it to roll specifically for the mantle instead of Intellect as a fix from the first version.
I'm have no idea how to create flexible, saving text boxes for the approaches and still have them work, so this might be the next best option. Hopefully you (Ikidaore) or someone else can figure out a fix.
> Partial DFA.html revert

- DnD_5e/DnD_5e.html
This adds partial spell compendium support to the community 5e sheet; I did not add the full range of fields, as some of them do not directly map between the compendium and the sheet.
Current known issues:
- Concentration / Ritual dropdowns can be set to 'Yes' from the compendium, but do not get unset if dropping a second spell onto the slot.
- Material components don't have a spot to live on the sheet
- Spell attack type (None/Melee/Range) does not have a spot on the sheet
> [DnD_5e] Adding partial spell compendium support to D&D 5e Community sheet.

- Urban_Shadows/sheet.html
- Urban_Shadows/sheet.json
- Urban_Shadows/style.css
A new supplement was released that introduced four new playbooks, that data has been added into the sheets.
I've swapped Corruption to load with the rest of the specific playbook information, as the new playbooks change around that mechanic so there are some specific versions now.
Moved notes section to stretch whole sheet instead of residing in the third column.
> Urban Shadows - Updated for Dark Streets supplement playbooks

- Rogue_Trader/RogueTrader.html
- Rogue_Trader/RogueTraderStyle.css
The old ship sheets in Rogue Trader were almost unusable. You could add names and components, but the weapon fields were just tiny and impossible to put info into/read. I moved the fields around a bit and added some CSS to make the fields for the weapons wide enough to read. Particularly, the ship sheet is now one column to make enough room for the tables. The code isn't pretty, but it works.
Since I do not have a Pro subscription I have not been able to test this as a custom sheet, but I have replaced the current sheet HTML and CSS with this using Inspect Element to design it. None of the changes should affect any functionality, but I can't test all of it without the editor.
> Fixing the styling of Rogue Trader ship sheet

- Burning Wheel/Burning Wheel.html
Adding script workers for Reflexes and Mortalwound attributes. Shade math is taken from the Monster Burner pg 367, the chapter on Gray and White Math. Also added a checkbox for the Tough trait, which affect Mortalwound calculations.
These changes disable the dropdown for shade for Reflexes and Mortalwound, since they are automatically calculated from the base stats.
> [Burning Wheel] Reflexes and Mortalwound

- CWOD-W20/W20.css
- CWOD-W20/W20.html
- Moved Dicepool header so it's centered.
- Standard difficulty is 6, so attack difficulty has been defaulted to 6. 
- When rolling damage, wound penalties should not be applied. These have been removed from damage calculations in combat.
- Only extra successes above those required to hit should be applied as extra dice of damage. Changed wording of query to reflect this. Change default extra die to 0, since this is the minimum extra dice that can be rolled as extra damage. 
- Updated broken image for check boxes. Now slash image will display for both conditions, but will distinguish between checked and unchecked with red behind image. 
- Background was using a Chronicles of Darkness image. Updated to use W20 specific background.
> Werewolf 20 Updates

- MouseGuard/readme.md
I was just trying out Roll20 and importing the Mouse Guard character sheet, and noticed this link in the description was returning a 404.
I guessed maybe the repo moved at some point, but the link hadn't been updated, so did a GitHub search to find this repo which had the same content.
> Fix link to issues on Mouse Guard character sheet

- Shadow of the Demon Lord/style.scss
Currently, when the Talent and Spell pages contain a large number of entries (Most Level 3+ Characters will have enough Talents/Spells to cause this issue), the background doesn't repeat and it simply goes to plain white. Which not only looks bad, but also makes entries that are on the edge of the background hard to read.
My proposed change is to simply have the backgrounds on those two pages repeat when they end, making the sheets look nicer and more uniform, and removing any legibility issues the current sheet may cause.
> Repeating Background Image for Talent and Spell Pages

- Open Legend Basic by Great Moustache/Open Legend Homebrew.html
- Open Legend Basic by Great Moustache/Open Legend.css
- Open Legend Basic by Great Moustache/Open Legend.html
- Open Legend Basic by Great Moustache/ReadMe.md
* Fixed a typo in the Initiative output to chat (when clicking on Speed)
* Made any Description output to the chat window from Actions be limited to 5 lines
- If over 5 lines, adds a scroll bar, so now it won't take up so much space when someone has lots of description/info
* Added in text below "Guard", "Toughness", and "Resolve" that indicates you can click them to do resist rolls
* Also renamed "power level" variable that was causing error if you dragged an action to the quick bar that wouldn't display the "Max" power level info.
> Open Legend: Long Descriptions now have Scroll bar

- Planet_Mercenary/Planet_Mercenary.html
Updated Planet Mercenary sheet Fireteam Combat fields to be of the text type instead of number
based on Errata.
> Updating Planet Mercenary Sheet fields to support fireteam damage

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* Minor bug fixes: Swap "current break factor" and "minimum break factor" to match attributes and UI (f56d28d); remove superfluous attributes introduced in my last PR (#2704) and use the pre-existing ones instead (2e50073)
The first commit will require people to manually swap the values in the UI (up to 4 x 2 fields).
The attributes in the second commit were added a month ago, but were merely duplicating already existing data. Know idea what I was thinking ;) The problem is (or: was) that both attributes were user-editable and not synchronized. Therefore, there might be inconsistencies in the sheets. The attributes in question do not change frequently. In my group with six players, the values remain constant for tens of sessions. Since there is no sensible way to decide which of the two …
> [DSA4.1] Fix Minor Break Factor Issues

- Deathwatch/Deathwatch.html
In skill rolls the bought attribute advancements weren't used.
> [Deathwatch] Fixed Attribute Advancement for Skills

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* Ranged Combat Tab Overhaul (66fced0, 772d015, c831b71, 93ac832, 0ee790f, 72eba46, 58d7480, 5981c98, 48a7bef, 41884b2, 93c4f95, b5f8b45, b337f25, 1340a12, 4e208c0, 15a4fa6, fb852d7, aa4775e, 119922c, a41e0a3, f8435b3, d73443f, 5d334c6, c92d146, 845f7b4, 317a34c, 48af3cc, 8784dc1, 51d213d)
* New Attributes: FKW1_RW1, FKW1_RW2, FKW1_RW3, FKW1_RW4, FKW1_RW5, FKW2_RW1, FKW2_RW2, FKW2_RW3, FKW2_RW4, FKW2_RW5, FKW3_RW1, FKW3_RW2, FKW3_RW3, FKW3_RW4, FKW3_RW5, FKW4_RW1, FKW4_RW2, FKW4_RW3, FKW4_RW4, FKW4_RW5, FKW1_TPRW1, FKW1_TPRW2, FKW1_TPRW3, FKW1_TPRW4, FKW1_TPRW5, FKW2_TPRW1, FKW2_TPRW2, FKW2_TPRW3, FKW2_TPRW4, FKW2_TPRW5, FKW3_TPRW1, FKW3_TPRW2, FKW3_TPRW3, FKW3_TPRW4, FKW3_TPRW5, FKW4_TPRW1, FKW4_TPRW2, FKW4_TPRW3, FKW4_TPRW4, FKW4_TPRW5 (c831b71)
* Removed Attributes: FKW_AT1, FKW_AT2, …
> [DSA4.1] Ranged Combat Tab Overhaul (Among Others)

- Basic_Roleplaying/Basic_Roleplaying.html
Minor Edits and Fixes on Existing Basic_Roleplaying Character Sheet
•	You now input your damage bonus instead of choosing one from a drop-down list.
•	Changed Modifier to Multiplier in the Attribute rolls
•	Changed Magic Pts to Power Pts in Characteristic Box
•	Flipped Max HP, Max MP, Max Fati. Max San with Cur HP, Cur MP, Cur Fati, Cur San respectively.
•	Fliped Max MP and Cur MP in the powers section.
•	Fixed the extra Ranged Weapons section so that it uses the roll template
•	Changed Ranged Weapon Type to Damage Bonus? (Y/N)
•	Fixed Ranged Damage Bonus so that the modified Bonus is rounded up. Instead of the allowing fractions.
•	Fixed the Persuade skill, the special success section was using the Etiquette skill instead of the persuade skill.
•	Added Artillery (Various), Fast Talk …
> Minor Edits and Fixes

- Dark_Heresy_2ed/DarkHeresy2ed.html
At large window sizes, ranged weapon reload field causes Hit button to become displaced. Aims to fix this issue.
> Update to ranged reload box size

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* **Bug Fixes**: Roll buttons now work without active calculator (3d5e0ce), distance-dependent modifier now shown to the user (7fecfbe), ranged attack roll button roll no longer leads to false-positive fails with negative modifiers (c40ae4c), activation weirdness of the ranged combat calculator on new characters fixed (05274c6)
* **New Features**: Adapt roll template to take shots into the fray into account (d0bd416), add option to use a different brightness system (02a0f57
* **Convenience Issues**: Add default and minimum values to ranged combat equipment/calculator (fa27013)
* **Style Issues**: Limit label width to child width (d3a17d7)
* **New Attributes**: fkr_helligkeitssystem (02a0f57)
* **Removed Attributes**: PA_armbrust, PA_belagerungswaffen, PA_blasrohr, PA_bogen, PA_diskus, …
> [DSA4.1] Ranged Combat Fixes

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
This PR fixes several minor issues I wanted to get done prior to the conversion to sheet worker scripts.
* New features: Add a place for exhaustion and overstrain (ca2da3b)
* Interface: Show all relevant information for evasion checks in the roll template and adapt roll buttons (ddf9561)
* Style: Use colours for combat 1/20 for stat checks as well (3d1efe8), use different background and text colour for highlighting default stats of talent checks instead of just using bold face (3501303)
* New attributes: erschoepfung, erschoepfung_max, erschoepfung_basis, ueberanstrengung, ueberanstrengung_max, ueberanstrengung_basis (ca2da3b)
> [DSA4.1] Default Stat Visibility, Evasion Checks, Exhaustion & Overstrain, Stat Check Roll Templates

- AW/style.css
- AW2E/style.css
- Urban_Shadows/style.css
This is a simple fix for the CSS of the AW, AW2E, and Urban Shadows
sheets to display repeating sections better. Also added some margins
to the harm radios for AW 1+2.
> Fix some repeating section display bugs

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
most of the attack and defense templates had one } too many, was always shown in the roll as text
> dsa5 sheet: roll template fix

- Stars_Without_Number_Revised/ReadMe.md
- Stars_Without_Number_Revised/Stars_Without_Number_Revised.css
- Stars_Without_Number_Revised/Stars_Without_Number_Revised.html
A whole bunch of upgrades to the sheet, including an all-new NPC sheet with only the stats needed for NPCs.
All of the indentation is changed/cleaned up to be consistent. This does fill up the git "lines changed" thing, but it was all done alone in their commits to minimise that.
A text field was changes to a repeating section, but all the data is migrated as best I could. It was a place to list languages, so I split it by newlines (and ofc removed empty lines).
The autofilling in the NPC sheet does kind of go against the "don't make automatic character creatin" thing, but the creator of SWN has said [here](https://www.reddit.com/r/SWN/comments/6dp5er/ok_to_write_software_for_swn_revised/) among other places that this is completely fine as long as the content used is in the free version …
> SWN Revised v1.4.0

- Mythras/Changelog.md
- Mythras/Mythras.html
Bug results in some data not migrating from the old hit locations to the new customizable ones.  These two version updates correct that as much as possible.
> Mythras v1.3.2, fixing bug in versioning from v1.2.X to v1.3.X

- Open Legend Basic by Great Moustache/Open Legend.css
- Open Legend Basic by Great Moustache/Open Legend.html
- Open Legend Basic by Great Moustache/ReadMe.md
* Fixed Default (Dis)Advantage not always popping up correctly
* Updated Attribute description text
* GUI update to chat window rolls
- Rolled Value much larger
- Power Level display changed
- No shows you the Achieved Power Level based on your roll
- Shows the Min Needed to Succeed as well as the Max Allowed (based on what is entered in Actions)
- Increased the Description areas to display a max of 7 lines (mouse scroll wheels jump 6-7 lines at a time)
> [Open Legend] GUI Rolls Improved & Minor

- D6StarWars/D6StarWars.css
- D6StarWars/D6StarWars.html
**Changes:**
- made physical description section a row shorter
- made inert a dysfunctional tracker in force section
- enlargen star wars logo & change dice pic to one with transparent background
- init bonus line fix
- Force powers textarea expanded
- Armor section minor text changes
- unify weapon stat blocks
- made pip input boxes smaller(need only a single digit as opposed to any other input box)
- fixed duplicating textfield
> [D6 Star Wars WEG] minor layout fixes

- Shadowrun-Anarchy/Shadowrun-Anarchy.html
This should explain where these otherwise opaque values come from.
> added mouseover tooltips for perception, memory, initiative, defense

- Mongoose_Traveller2e/MongooseTraveller.html
Just a leftover, the skill was still called "Computer" in there from 1E
> Mongoose Traveller 2E: fix Deception skill roller not working.

- Fallout 3.5/Fallout 3.5.html
Changing order of damage type to be same as in the book. Due to not same order as in the book, it was hard to write down damage numbers correctly.
> Fallout Patch

- Basic_Roleplaying/Basic_Roleplaying.html
•	Added a drop down menu for attribute rolls
•	Swapped the HP Counter on the bottom of the sheet. It was putting the Max HP value on the top instead of the bottom.
•	Added a “Roll Under Half” Section for Skill Roll Template. Due to there being some rules for them.
•	Increased the size of the number box in order to handle triple digit skills in alphabetical skills.
•	Created a drop down menu for the multiplier input when rolling in alphabetical and categorical skills.
•	Added a default value for skills in alphabetical and categorical skills
•	Made the number box bigger to take 3-digit numbers
•	Added drop down menu for the multiplier input in hand-to-hand weapons and ranged weapons
•	Added Default skill values, weapon length and attack type for Brawl and Grapple Attacks
> A Series of Minor Changes to the BRP Sheet

- Star Trek Adventures Official/STA_Style.css
- Star Trek Adventures Official/Star Trek Adventures Official.html
Weapons needed to be fixed to account for torpedoes not using scale. Scale was removed from the damage calculations. Stress 18 was also missing. Added that attribute in.
> Star Trek: Weapons & Stress fixed

- Star Trek Adventures Official/STA_Style.css
- Star Trek Adventures Official/Star Trek Adventures Official.html
- Star Trek Adventures Official/translation.json
Minor formatting change for min=0 adding "". Gave stess_max & shield_max a starting value to eliminate an issue where all the bubbles disappeared if the user never changed the default attributes. Added an attribute for Version to help with future updates.
> Added default attributes

- Basic_Roleplaying/Basic_Roleplaying.html
•	Removed the “Rolled Under 1/2” Sections of the Roll Template.
•	Change Attribute Rolls to Easy (x10), Normal (x5) and Hard (x5/2)
o	Normal-x5,Easy-x10,Difficult-x5/2,x4, x3, x2, x1
•	Remove number from First Aid, Knowledge, Literacy, Pilot, Psychotherapy, Ride, and Technical Skill on Alphabetical Skills as they have variable base numbers.
•	Add Default Number to Repair (15%) on Alphabetical Skills
•	Remove number from Knowledge and Technical Skill on Categorical Skills as they have variable base numbers.
•	Removed Repeating Shields due to problems when Repeating Armor is deleted. Will be re-added in another update.
•	Accidentally left Alphabetical Skills checked when it should have been unchecked, this caused the Alphabetical Skills to only appear when unchecked. My Apologizes for that …
> Housecleaning and Additions

- Impulse_Drive/Impulse Drive.html
Fixed roll button errors for primary stats: Volatile, Calculating, Stalwart. Output now references the stats correctly.
> Fixed roll buttons on statistics

- Elite Dangerous Role Playing Game/EDRPG.html
Fixed the value for checkboxes was previously 0, is now 1 which allows the boxes to be unchecked.
I added a sheet worker which unchecks all the checkboxes so that it does not have to be done manually at the end of a session if desired.
Corrected the name of the Initiative (tactics) to be like the other fields on the sheet. It was backwards and listed as Tactics (initiative)
Rolls buttons were added at the top of the sheet for defence (dodge), initiative (tactics) and defence (parry). This was an ease of use feature request that I received.
> Elite Dangerous RPG; Added 2 Features and Fixed 1 bug

- Elite Dangerous Role Playing Game/EDRPG.html
Fixed a bug where in repeating sections two different values were saving to the same atribute.
- This occured 3 times
Fixed 1 misnamed attribute which was pulling an incorrect value from somewhere else on the sheet.
Fixed 5 attributes which were not properly tagged as attributes and not saving their values.
This affected ranged weapons to hit values, a fighting weapon to hit value, a field for where clothing is being worn,  strength and power values in  ship weapons, utilities, fixed components and internal components and vehicle weapon accuracy and to hit.
> Elite Dangerous RPG - Bug Fixes for attributes linked and not saving

- Dungeon_World_Official/Dungeon World.html
- Dungeon_World_Official/translation.json
Adds a rolltype option that queries to pick the name of a bond (from the list on the sheet) or "other." Adds the the number of bonds with that name to the roll. Other, and default when no bonds listed, adds 0.
> Add BOND option to move roll type dropdown.

- GURPS/gurps.css
- GURPS/gurps.html
- GURPS/sheet.json
* Restyled tabs to work with Firefox and MS Edge
* Traits tab -> disadvantages section: slight changes to column spacing
* Combat tab -> Ranged attacks section: slight changes to column spacing and abbreviate titles
* Skills Tab -> Techniques section: slight changes to column spacing
* Added URL to GURPS roll20 wiki
* Tested on Chrome (PC), Firefox (PC), and MS Edge
> [GURPS] Style change to tabs and columns

- DnD_5e/DnD_5e.html
- DnD_5e/ReadMe.md
- DnD_5e/sheet.json
Adds partial support for drag-and-dropping monsters from the compendium onto the NPC sheet. Automatically populates most values, but doesn't set actions.
> DnD_5e Monster Compendium Support

- Open Legend Basic by Great Moustache/Open Legend.html
- Open Legend Basic by Great Moustache/ReadMe.md
* Fixed Speed Calculations if Mighty is 0
- Was halving speed even if no heavy items
> [Open Legend] Quick Fix to Might 0 Speed Calc

- Mutant Year Zero Alternative/MutantYearZeroAlternative.css
- Mutant Year Zero Alternative/MutantYearZeroAlternative.html
Added a roll template and uses default stats. This cleans up a lot of the hassle of playing MYZ online, since tracking which dice get which results is important in the system.
Added missing fields and added new logic to shift the titles out to match other expansions of MYZ.
> Update to Mutant Year Zero Alternative

- Mutant Year Zero Alternative/MutantYearZeroAlternative.css
- Mutant Year Zero Alternative/MutantYearZeroAlternative.html
- Mutant Year Zero Alternative/sheet.json
This adds a number of small and less small enhancements including 
-new rolling functionality
-character races and appropriate labeling of sheet features relative to race. 
-a new advanced roll template
-hover over text on values
No sheet values were removed or renamed. I've only added new functionality that enhances what was already there. I've play tested this with my group and contacted the rpg community in question to get feedback. I think this is ready for a wider audience.
> [Mutant Year Zero] Sheet Rolls, character race added

- City-of-Mist/city-of-mist.css
- City-of-Mist/city-of-mist.html
Added repeating sections for each theme card to add power tags and weakness tags.
Added a sheet worker script to calculate the power of a roll based on the checked tags and the modifier fields, replacing the previous version's auto calculating value attribute.
Note: I originally wrote the calls to getSectionIDs() using Promises but that did not seem to work with the way the getAttrs() function works.  
If support for Promises was included with the API used by the sheet worker scripts, this type of thing would be much cleaner.
> City of Mist character sheet repeating Power and Weakness tags.

- Star Wars 30th Anniversary Edition/StarWars30thAnniversaryEdition.html
Could this game be grouped under "D6", like Star Wars D6 is? This sheet is for essentially the same system.
https://en.wikipedia.org/wiki/Star_Wars:_The_Roleplaying_Game
https://en.wikipedia.org/wiki/Star_Wars:_The_Roleplaying_Game#Fantasy_Flight_Games_Reprint
The author will update the sheetworkers, so the sheet rolls will function, when he has time.
> [Star Wars 30th Anniversary Edition] Move to D6 system

- New World of Darkness Official/NWoD_Official.html
Add functionality for including potency stats (Blood Potency, Gnosis, Wyrd, etc) in sheet rolls.
Duplicate of PR #3617 pulled from it's own branch rather than my master.
> Add potency option to sheet rolls in CofD Official

- Deadlands Classic/deadlandsclassic.css
- Deadlands Classic/deadlandsclassic.html
Fixed the broken repeating field buttons. 
Improved the Roll Macros to include "k" to keep the highest for skills.
Updated the weapon roll buttons to include the GM & Location toggles mentioned below
Updated Hand to Hand weapons to now also roll Str & damage in the roll template
Added placeholders & update incorrect ones
Added a whisper to GM roll toggle
Added a Location Weapon shot toggle
Changed all the inputs to opacity 0 and put numbers on top of them with hover & checked feedback
Gave the page a width to fix minimization/maximization issues
Added to the roll template & changed the colors
Fixed the CSS for weapons damage repeating fields section
Added "Selected" to Options so they have a default value now
Added a Money text field in Misc
General CSS improvements
**No attributes were …
> Deadlands Classic: Fixes & Updates

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
A new item modifier has been added to update all of the skills on the character sheet as well as the initiative for the character. Use the modifier, Ability Checks, to trigger this effect. This change allows for the utilization of items that modify all ability checks such as the Stone of Good Luck. However, this change does not impact the base ability checks, such as Strength checks.
> Added item modifier for ability checks to 5e OGL

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Half casters (Paladins and Rangers) and third casters (Arcane Tricksters and Eldritch Knights) will now calculate the correct number of spellslots. Previously the spell slots were rounding up to the next level of spellcasting when it should instead be rounded down.
> 5e OGL fixed spellcasting lvls of non-full casters

- WOIN/WOIN.html
This change would be to Fix the typo that when you roll Logic, it states you roll Agility. It will now say you roll Logic.
Reputation was written repuation everywhere. Made it Reputation again.
The sheet needed a field to add additional damage to a weapon roll, for example, when you want to roll 2d6+2. There was no way to add the +2. I added a field called Damage Add. for that.
The sheet needed a field to record current health and max health. Left the Health field as is and added a max Health field.
> Update WOIN.HTML to fix two typos, add new fields

- Exalted 3/Ex3-Sheet.css
On the current sheet, it is impossible to click the radio buttons for Craft:Geomancy, since they are layered below the checkbox for Martial Arts "Show Styles", even though they appear visually to be layered in the opposite order.
> Ex3: Fix contention between 'Show MA Styles' and 'Craft: Geomancy'.

- Exalted 3/Ex3-Sheet.css
- Exalted 3/Ex3-Sheet.html
- Exalted 3/sheet.json
- Exalted 3/translation.json
Updates Exalted 3 character sheet to add support for battle groups.
Adds a toggle to the settings page to flag a character as a "battle group". This toggle hides the health track on the main page and adds a section for battle-group-specific traits (as described on page 206-210 of the core rulebook).
> Ex3: Add support for battle groups.

- PokemonTabletopAdventures - Sun & Moon/PTA.html
The update to the Sun & Moon version contained a few mistakes I corrected:
- Added "Sooth", a forgotten trainer skill
- Added the stat in the skill name so player can quickly see what stat is linked to what skill
- Changed the "radio" input to "checkbox", so it can be un-checked
- Changer the formula for the trainer skill roll to correct a bug occuring when leaving the "Misc. Skill Modifier" blank
- Corrected the roll formula for 4 skills, as the wrong stat was used
> [Pokemon Tabletop Adventure - Sun & Moon] Corrections

- Open Legend Basic by Great Moustache/Open Legend.css
- Open Legend Basic by Great Moustache/Open Legend.html
- Open Legend Basic by Great Moustache/ReadMe.md
* Sheet Type Selection added (and lots of backend coding)
- Pick between: Primary Character, NPC/Summons, Alternate Form Tier 1 or 2, Companion Tier 1, 2, or 3
- Changes the calculations for Attribute Points & Feat points based on what is selected
- Adds some entry fields were applicable (Companion Tier 3 Feat Points Granted)
- For NPC, shows a completely different sheet for "Quick" build (useful for summons as well)
* Fix for "Other Actions" section & Effects
- On Load function for Other Actions wasn't doing the Power Levels Correctly
- Forgot to make Effects dice explode (all dice in OL explode!!)
> [Open Legend] NPC Section & More

- Exalted 3/Ex3-Sheet.css
- Exalted 3/Ex3-Sheet.html
- Exalted 3/translation.json
Adds checkbox on settings page to toggle quick-character mode. This option hides sections of the sheet that aren't used by quick characters (or are calculated differently for them), and adds new sections for quick-character dice pools.
> [Exalted3] Add support for quick characters.

- Burning Wheel/Burning Wheel.html
These improvements were little bugbears we encountered during play. I am aware the Grayscales are quite large, I find them fairly useful when burning supernatural characters. The beginners luck issue still needs a bit more work with calculating obstacle penalties on the difficulty check, but it is much more solid. (if needed you can add those penalties as complications in the updated prompts)
> [Burning Wheel] Fixed beginners luck difficulty calculations + Added Grey and White Grayscales to the Combat Page

- Burning Wheel/Burning Wheel.html
The expanded PTGS that was recently added is appreciated, but it's not ready yet. The added rows are edge cases used in only a fraction of games, but they dominate the sheet now and take up way too much space. Until they can be hidden in some way (drop downs perhaps?), I think we should stick to the original PTGS.
> Undoing the PTGS additions just added

- Weaverdice/README.md
- Weaverdice/Weaverdice.css
- Weaverdice/Weaverdice.html
The original html/css was originally autocreated, and as such hard to read, removed lots of unnecessary classes and replaced the css heart symbol that seem to break the layout on Roll20. Now the preview is actually accurate.
> [Weaver Dice] fix broken layout, code trimming

- Burning Wheel/Burning Wheel.html
It was raised in the Burning Wheel discord, that people were having issue, only been allowed to have 3 of each. Updated this to now expand like sustained spells.
> [Burning Wheel] Make Reputations and Affiliations an expandable list

- D6StarWars/D6StarWars.css
- D6StarWars/D6StarWars.html
- D6StarWars/README.md
**Added:**
- option menu to customize sheet with following options:
- pc/npc sheet switch
- hide/show gmroll buttons
- show/hide option for Force, Background & Equipment sections
- fixed Force Emptiness, can now adjust Emptiness bonus according to your DSP
- minor formatting changes
- updated readme
- code cleanup, some comments added
ATM showing the gmroll button doesn't align that well with the existing content but I have the intention to adjust them further.
**Comments:**
- The NPC sheet is partially duplicated from the original sheet, will trim code later 
- I haven't manage to remove all unnecessary scripts nor css as I don't fully understand how much of the scripts are relevant to the new features, but will over time trim it away. 
- seem to have gained some extra mini-buttons that …
> [Star Wars D6] Customization menu and NPC sheet added

- Unknown Armies 3e/UnknownArmies3e.html
Turns out "#00000000" doesn't work for setting transparency in roll20. Switching it out for "rgb(0, 0, 0, 0)", which worked at the top of the sheet.
> Fix textfield background-color

- OpenLegend_Minimalist/open_legend_minimalist.css
A simple one line fix to fix the positioning of the attribute dice size box due to the changes that Roll20 made. I had been working with the other collaborator before he too vanished. It's a small fix though and hopefully can be passed easily.
> Fixes the Dice box position

- GURPS/gurps.css
- GURPS/gurps.html
Changed the word Fear to Fright on the general page - cosmetic change only.
Changed the macro results from 'vs Will' to 'vs Fright' - cosmetic change only.
Changed the Hit Location DR to accept text input and have a wider field visibility - cosmetic change only.
Fixed bug in Hit Location Penalty not saving for custom added locations. The attribute was incorrectly named in a repeating table and thus was not saving.
Added Tool Tip for Pen header in Hit Location - cosmetic only.
No attributes were modified except for the bug fix.
ver 1.3.5
> [GURPS] Changed Fear with Fright - Changed Macro from 'vs Will' to 'vs Fright'. Changed Hit Location DR: Cosmetic only.

- ShadowrunAnarchy/SR Anarchy.css
- ShadowrunAnarchy/SR Anarchy.html
- ShadowrunAnarchy/sheet.json
Fix: Removed all REMs which broke after last update
Refactor:
- Removed & renamed excess classes. Replaced with selectors.
- Added Alts for images
- Fixed spelling error for skill specializations
- Added a Version for the sheet in the footer
- Added sheet worker  & display for Skills & Skill Specs so they will be shortened when excessively long
> Shadowrun Anarchy: Fixes & Refactor

- Free Spacer/FreeSpacer.html
Fixed bug in Ship and Launch Shields: Removed ":" from attribute name that kept stat from displaying.
Removed pull down for prefix and replaced it with a text field for flexibility.
Changed Gender Identity to Pronouns for clarity
Changed Open Source to Liberation in Drive pulldown. Will not effect Drive until it changes. Attribute changes every session- will have no effect on play.
Shortened and fixed spelling in descriptions for consistancy.
Added spacing to tools for layout.
> Free Spacer: Bug and clarity fixes

- GURPS/gurps.css
- GURPS/gurps.html
•	Updated the Language Box format – Cosmetic Only.
•	Added additional options for Native Language in regards to Spoken and Written levels as a Disadvantage.
•	Updated the Inventory Box format – Cosmetic Only.
•	Added fields for ‘TL’ (Tech Level) and ‘Ref’ (Reference) to the Inventory repeating section.
•	Fixed bug for Single Modifier Prompt and Extended Modifier Prompts if a ‘+’ is used for a positive modifier entry.
> [GURPS] Inventory and Language Box reformatted

- Wrath and Glory API/readme.md
corrected number list and rewrote known issue (referenced a roll of a 2 when it should have been a 6).
> Update readme.md for Wrath & Glory v2

- Free Spacer/FreeSpacer.html
- Replaced a pulldown for Trivial traits with a seperate flexable text field.
- Replaced a dice pulldown that is no longer required with text.
- Fixed a tense issue in consumption.
> Free Spacer  - Removed Pulldown for Trivial traits to increase flexibility

- GURPS/gurps.css
- GURPS/gurps.html
•	Fixed bug with calculating Current Move for Heavy and Extra Heavy Encumbrances and not using a Minimum of 1. Reported by Ray G (@raymond-g)  (UserID: 1600355).
•	 Fixed bug with calculating Total Weight from Inventory which at times created a weigh of more than 3 decimal places.
•	Added a ‘FOA’ (Frequency of Appearance) field under Advantages (& Quirks)
•	Modified the Tool Tip for SCN under Disadvantages (& Quirks) and Racial Traits to include the wording ‘OR Frequency of Appearance’– Cosmetic Only
•	Added Max Load to the Encumbrance table.
> [GURPS] Bug Fixes and added FoA

- Eirendor/Eirendor.css
- Eirendor/Eirendor.html
- Eirendor/sheet.json
The following corrections have been implemented, after the new layout included last week:
- Bonus per level formula changed from "ceiling" to "floor", as apparently was showing decimal numbers in rolls for levels higher than 2.
-Fields "rasgo1" was duplicated, changed to "rasgo1" and "conjuro1
-Rolltemplate had a word misspelled, removed.
Thanks
> Eirendor character sheet corrections

- CWOD-DAV20/DAV20.css
- CWOD-DAV20/DAV20.html
- CWOD-DAV20/sheet.json
- Added dots to Perception, Intelligence and Wits trackers, so they can go you to 8, as with the other main attributes.
- fixed sheet.json typo
> [Vampire Dark Ages 20th] attribute fix

- DungeonWorldSpanish/DungeonWorldSpanish.html
1 - correjido un fallo que no se podia desplegal el textarea de los hechizos
2 - quitado las etiquetas de los objetos para que se vea mas limpio y añadido "usos" para los objetos
> (DungeonWorldSpanish) cambios y arreglos html

- DungeonWorldSpanish/DungeonWorldSpanish.css
1 - correjido un fallo que no se podia desplegal el textarea de los hechizos
2 - quitado las etiquetas de los objetos para que se vea mas limpio y añadido "usos" para los objetos
> (DungeonWorldSpanish) cambios y arreglos CSS

- New World of Darkness Official/sheet.json
The sheet.json's "instructions"-section had an non-functioning html tag to a link, replaced with the functioning format.
> [New World Of Darkness Official] minor fix

- Weaverdice/CHANGELOG-Weaverdice.md
- Weaverdice/README.md
- Weaverdice/Weaverdice.css
- Weaverdice/Weaverdice.html
- Weaverdice/sheet.json
- crit fails/successes add back to skill rolls(roll of highest/lowest shows red/green)
- skill rolls use blue roll templates, attribute rolls use red
- readme fix
> [Weaverdice] V.1.41

- D6StarWars/CHANGELOG.md
- D6StarWars/D6StarWars.css
- D6StarWars/D6StarWars.html
- D6StarWars/README.md
- readme link fix
- attribute/skill rolls use blue template, weapons/armor use red, initiative/custom rolls use black
> [Star Wars D6] V.1.81

- Naheulbeuk/Naheulbeuk.html
Really sorry guys i made a little mistake in my previous PR Y_Y
updateWeapon and updateWeapons exist both so I had no visible error but right now, the wrong function is called during sheet:opened event and the weapons aren't updated and players see bad values.
> Le Donjon de naheulbeuk 2.4.1

- README.md
This prevents an issue where the `<head>` and `<body>` tags were not displaying on GitHub, causing the readme to read:
> Your HTML file must **not** have a or tag, or your character sheet may not load in the virtual tabletop.
This PR also adds a newline after the "**Don't Use Reserved HTML**" line, so that the pseudo-heading and the comment do not run together.
> Escape reserved HTML tags using backticks

- Wrath and Glory API/wrath_and_glory.css
I did not close off a comment and it broke the rendering of the sheet.  The only change is to close off the comment.
Close off a comment in the first line.
Can this be expedited as the sheet is broken in the Roll20 community.
> Wrath & Glory v2.2 css Fix: wrath_and_glory.css

- ChroniquesOubliees/co.htm
*ChroniquesOubliees*
Added the option to use a d3 in for weapon dmg (needed for fairies and pixies)
Natha, the original author of the sheet asked me to maintain his sheets for Chroniques Oubliees.
> ChroniquesOubliees: added the possibility to use d3 for weapon dmg.

- GURPS/gurps.css
- GURPS/gurps.html
•	Fixed version 1.4.1 Pull request date – Cosmetic Only.
•	Fixed version 1.4.2 Pull request date – Cosmetic Only.
•	Added information pertaining to who made changes in version 1.4.2 – Cosmetic Only.
•	Widened Shots field in the Range Attacks section – Cosmetic Only.
•	Fixed widths (margins) of the Active Defenses, Melee Attacks, and the Ranged Attacks sections – Cosmetic Only.
•	Fixed widths of the Damage Macro for the Melee Attacks and the Ranged Attacks sections – Cosmetic Only.
•	Change the background color of the Skill field and Macro field to a Light Blue for Melee Attacks and Ranged Attacks – Cosmetic Only.
•	 Added some ‘Hover’ information for the Trait and Skills Tabs – Cosmetic Only.
•	Restore some deleted Revision History – Cosmetic Only.
*Include the name of the sheet you made …
> [GURPS] - Mostly Cosmetic changes v1.4.3

- Mutants and Masterminds 3E/mutants-and-masterminds.css
- Mutants and Masterminds 3E/mutants-and-masterminds.html
- Mutants and Masterminds 3E/sheet.json
Script
======
This script accurately calculates the cost for:
- Powers
- Alternate effects
- Dynamic alternate effects
- Advantages
- Equipment
- Wealth
Once it's done calculating, it either enters the results in the correct boxes or displays a message informing the player about what mistakes they've made.
HTML
====
- New powers and advantages now cost 1 by default.
- New menu to choose between normal powers and alternate effects.
- Secret wealth stat (see below).
- Equipment now has a cost field (which also defaults to 1).
Wealth
=======
I wanted to include the GM guide's optional rules for wealth, without drawing attention to them. I figure that anything not found in the Hero's Handbook should be well-hidden.
I considered commenting out the relevant HTML, and then paying users could …
> Mutants and Masterminds 3E: Add worker script to count power points and catch errors.

- README.md
Now it should link directly to the relevent section, instead of the wiki page in general.
> Update Guideline link in Readme

- Dungeon_World_Official/Dungeon World.css
- Dungeon_World_Official/Dungeon World.html
- Dungeon_World_Official/translation.json
- Dungeon_World_Official/translations/en.json
- Quickstart playbook selection - If you haven't got a class filled out, you'll be presented with the option to automate a playbook drop from compendium at the click of a button.
- Catch-all compendium drops -- the entire PC sheet is now a single drop zone, and will properly add the dropped item into the correct section on the sheet.
- Miscellaneous sheet worker changes to accommodate a plethora of changes to the Dungeon World compendium data.
- Styling updates to improve the user experience.
- Misc. bug fixes and tweaks
> [Dungeon World by Roll20] - Version 2.0

- Urban_Shadows/sheet.html
Added a button for Session Intro, another move that uses the faction ratings.
Very small change, adding this because my group has been rolling manually or selecting other faction moves, so this is a little more convenient.
> [Urban Shadows] Adding Session Intro button

- Knight/knight.css
- Knight/knight.html
- Bugfix for new "Vehicule" sheet & visual update (text center)
- Rework for "Style de combat" system & ensure compatibility.
- For the checkbox value changes, I used a sheetworker to make it transparent for users
- For hidden fields, users will not be aware of the change, everything being automatic
- Add "ameliorations d'armes" for Ranger Armor
- Add "Flux" for Psion Armor
- Add a CSS Wizardry for min to 0 for Réaction & Défense
- Add Défense & Réaction on Barbarian Armor Tab
> [Knight] Various Bugfix / Update

- L5R Fantasy Flight Games/L5RFFGSheet.html
[Found by Grant L. (Roll20 thread)
](https://app.roll20.net/forum/post/6969899/l5r-ffg-endurance-and-composure-equations-are-swapped)
Endurance and Composure where calculating eachothers values. 
- Now Endurance is (Earth + Fire) x2
- Now Composure is (Earth+Water)x2
[source](https://imgur.com/a/2fVe5PB) p36, CRB
> [L5R FFG] fix Endurance & Composure calculation

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
This fixes a bug in the charactermancer that would not allow you to select a tool as an expertise choice (example: rogue thieves' tools)
> 5eOGL: Fix bug not allowing choosing a tool as expertise.

- FFD20/ffd20.html
I made a mistake with the ternaries for undead characters. that should be fixed now. also added in a new attribute for displaying the ability mod for undead characters in fort calculations
This is super vital to be added quickly as it breaks current sheets. I'm so sorry. will do a better job debugging in the future
> ffd20 fix undead compatibility. hotfix needed

- Urban_Shadows/sheet.html
I fixed the Custom Weapons fields, which had the same names, and as a result duplicated content. Now, the two fields are distinct, as they should be.
> (Urban Shadows) Fix the Hunter's Custom Weapon fields

- GURPS/gurps.css
- GURPS/gurps.html
•	Added Latest Update with date to the top of the Updates page - Cosmetic Only
•	Changed the Input color from pink to a light gray (Because of so many complaints about the pink)- Cosmetic Only
•	Fixed the Current HP, Thrust, and Swing fields on the General page to display the Input Color – Cosmetic Only
•	Fixed bug for the Total Points and the calculated Unspent Points were not totaling correctly on the General page – The actual fix was spotted and provided by Filipe (UserID: 1089514)
•	Fix alignment of columns for Attributes on the General page - Cosmetic Only
•	Fix base tooltip font size from 10 to 11 to make it more readable - Cosmetic Only
•	Added tooltips for POINT SUM on the General page  for Total, Spent, and Unspent - Cosmetic Only
•	Under POINT SUM in the General page, changed …
> [GURPS] Cosmetic changes and a few bug fixes in gurps.html and gurps.css

- GURPS/gurps.css
- GURPS/gurps.html
Changed the PULL date for version 1.4.7 to 12/04/2018 – Cosmetic Only
Changed the width of the REF field in Advantages, Disadvantages, Skills, Techniques, and Possessions – Cosmetic Only
Removed the visual cue for editable fields on the General Tab – Requested by MANY – Cosmetic Only
Added highlighted light gray color for calculated fields on all pages – Cosmetics Only
Removed the blue highlight from Melee and Ranged attacks as it is no longer needed – Cosmetic Only
Fixed alert indicating to use whole number on attributes that can be up to 2 or 3 decimal places in value in the Inventory section - Cosmetic Only
Resized the Life and Moving box and the Encumbrance box for FUTURE upgrades - Cosmetic Only
*Include the name of the sheet you …
> [GURPS] Bug fix, Cosmetic Changes v1.4.8

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Rolling top Roll button will fill in all of the by level inputs with its unique roll.
* Average button fills in the Average
* New roll template to allow for rolling of hp by up to 20 levels.
Still needs doing:
* Data needs to be cleared if a multiclass need is removed
* CSS needs beautification 
> updates hp bylevel

- Kult Divinity Lost/KULT Divinity Lost.html
In the first version of the sheet, I seem to have inappropriately referenced the src for an img tag,, and my attempt to use padding to set a table's width didn't work out.
This commit appends the appropriate src, and adds an empty column in the table to (hopefully) fix the width.
> Kult Divinity Lost - Fixing some minor visual issues

- d20 Modern/d20 Modern.html
Modifies attr_fx-Known and attr_fx-PP to have a 'max' value instead of 'max' and 'current', thereby allowing for a PP bar on token.
* Renamed `attr_fx-Max_Known` to `attr_fx-Known_max`
* Renamed `attr_fx-PP_Max` to `attr_fx-PP_max`
* Renamed `attr_fx-PP-Current` to `attr_fx-PP`
> Correct d20 modern to allow bars

- GURPS/README.md
- GURPS/gurps.css
- GURPS/gurps.html
- GURPS/sheet.json
•	Fixed the placement and alignment of the SCN, Macro, PTS, and REF fields in Racial Traits – Cosmetic Only
•	Added a Background color for all Calculated fields – Cosmetic Only
•	Remove odd and even row background color – Cosmetic Only
•	Added bottom border to all Input fields – Cosmetic Only
•	Fixed alert indicating to use whole numbers for Speed which can have can have up to 2 decimal places - Cosmetic Only
•	Added a ‘Note to Authors’ section in the Updates page
•	Updated the Readme.md file
•	Fixed Skills Column alignment order – Code Fix only
•	Set the Default selection for the Modifier Prompt to Single Modifier Prompt
•	Fixed ToolTip placement for Thrust and Swing attributes – Cosmetic only
•	Increased width of character sheet to the maximum possible – Cosmetic Only
•	Adjusted the …
> [GURPS] Mostly Cosmetic changes: GURPS.html, GURPS.css, Readme.rd v1.4.9

- Mutant Year Zero Alternative/MutantYearZeroAlternative.html
* added missing attr-name to textarea, so it saves info now.
* bug noticed by [Sherm](https://app.roll20.net/users/3561), [forum post](https://app.roll20.net/forum/post/7095956/mutant-year-zero-ark-sheet)
> [Mutant Year Zero] added missing attr-name

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Global damage modifiers is being converted from text area to inputs.
Rollstring attribute is being eliminated. Versioning was written to convert current modifiers.
Dropping Global Damage modifier blog also applies correctly now. 
> Updates to global damage modifiers

- CWOD-V20/V20.html
-Fixed a repeating bug in the dice rolling tab between main dice pool and combat dice pool.
> [CWOD V20] Bug Fixes

- CthulhuTech_1ed/CthulhuTech_1_ed.html
Dice were counted by raw Agi instead of `floor(Agi / 2)` like all other attribute feat rolls.
AGI Feat was changed to calculate number of dice equal to raw AGI. This is incorrect and does not match how the other attribute feats are calculated. Dice count should equal `floor(AGI / 2)`
@CoalPoweredPuppet was your previous AGI calculation in https://github.com/Roll20/roll20-character-sheets/pull/4042 a mistake?
- When updating existing …
> [CthulhuTech_1ed] Fix Agility math to correctly roll AGI Feat

- GURPS/gurps.css
- GURPS/gurps.html
Changes, Fixes, and Adds made by Mike W (UserID: 1414610)
Fixed alert indicating to use a valid 3 decimal Weight value for the Inventory weight attribute, which in fact can up to 4 decimal places. Reported by Ray G (@raymond-g)  (UserID: 1600355
Fixed Inventory header alignment – Cosmetic Only
Fixed Inventory calculations color bacground – Cosetic Only
- When updating existing sheets if you are changing attribute names please note …
> [GURPS] Mostly Cosmetic changes: GURPS.html, GURPS.css, v1.5.0

- LANCER RPG (1.8)/LANCER.html
There was a somewhat significant visual bug in the first sheet release—one of the fields extended outside of its frame and was mostly hidden from view. This has been fixed.
> [LANCER RPG 1.8] fixed 'tech attack' field extending outside of the sheet frame

- The Strange/The Strange.html
* change the _might_ attribute from a `<span>` into an `<input>` so it should now work like normally like all the other stats
* [Bug report thread](https://app.roll20.net/forum/post/7217594/the-stranges-sheet-bug#post-7217913) 
* Not tested in Roll20, but this is a simple/obvious fix so...
> [The Strange] Fix 'might' attribute

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.css
- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Refactored Average buttons to be Roll buttons for user output
* Refactored HP by level sections so they now run more on demand
* Created some helper functions so they can be accessed more dynamically
* Hill Dwarf now adds HP per level
* Draconic Sorcerer now get HP per level of that class
* Switching between Sorcerer subclasses with dynamically change input results
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to …
> 5e D&D - DEV 1619 - Leveler HP fix

- Dungeons the Dragoning 40000 7th Edition/DtD.html
Added default value to level field in Dungeons the Dragoning character sheet to allow certain macros to function even when character sheet is incorrectly or incompletely filled out
Dungeons the dragoning 40k 7th Edition
> Dungeons the dragoning 40k 7th Edition: Default value for Level

- 5e Darker Dungeons/5e Darker Dungeons.css
Attribute background css was misplaced.
Now fixed and displays correctly.
> Fix misplaced line in Darker Dungeons css

- Exo 2933/Exo2933.html
The following has been changed:
- Added {ca=[[4]]} to all skills in order for the rolltemplate to calculate success in a savage-worlds like way.
- Added automated Fighting skill and roll against token (in red in the character sheet)
- Tag for Ataccks changes "Armas y Daños". Columns have had their width changed.
- Injuries field "Heridas" attr_heridas has been changed from negative scale to positive scale.
- Some labels changed, no attribute name changed.
- In the attacks rows, we include manual damage button (Roll_Dmg) and damage against token (Roll_DmgAuto). We have removed the attack rolls from them (Roll_Attack2).
- Added variable to check extra damage in buttons Roll_Dmg and Roll_DmgAuto, it is called ?{Aumento}
- Corrected the -2 modifier to non skilled roll button, and tag also …
> Changes to Exo 2933 Character Sheet

- StarWars5E/StarWars5E_CSS.css
- StarWars5E/StarWars5E_HTML.html
- StarWars5E/sheet.json
- StarWars5E/translation.json
* Added a sheet with type "Ship"
* Specific new fields added for ships:
* Modifications (similar to Features)
* Pilot proficiency
* Pilot skill: INT(Piloting) with it's own specific field
* Ship tier
* Shield points
* Abbreviated saving throws (STR, DEX, CON)
* Abbreviated attributes (STR, DEX, CON)
* Separate inventory for hidden cargo, with it's own total weight counter
* Turning speed
* Flying speed
* All new fields and any calculation changes do not affect NPC or PC type sheets.
- …
> StarWars5e: Added a Ship sheet type with all necessary fields

- RunequestGQS/ReadMe.md
- RunequestGQS/RunequestGQS.css
- RunequestGQS/RunequestGQS.html
Tweaked CSS so skill names can be read when modifying repeating sections
Added fields for coinage on the 2nd tab.  Currently this does not effect encumbrance.
I added a bunch of new hit locations including all the location tables  at the start of the bestiary. 
Added fields for individual weapons skill modifiers or occasion such as Bladesharp cast as per request  
[https://app.roll20.net/forum/post/7170823/runequest-roleplaying-in-glorantha-feature-request-weapons-skill-mod/?pageforid=7170823#post-7170823](url)
I also added checkboxes with the heading Spells Cast for Vigor, Strength  and Glamour they handle all the fudges listed under the spells,such as skill category  increases, damage die steps and max enc.So don't add the stat bonuses in the mod fields of the characteristics.The …
> RuneQuest:Rolepaying in Glorantha  version 04.03.2019

- CWOD-Wr20/translation.json
- WerewolfTheForsaken2e/WerewolfTheForsaken2e.css
- WerewolfTheForsaken2e/WerewolfTheForsaken2e.html
- Fixed the repeating rites section on the Werewolf sheet(accidentally wrote "repeating-" instead of "repeating_")
- Moved Rites type selector into the collapsing section of the repeating rite fieldset, to preserve space
- Fixed the number inputs in Firefox on the Werewolf sheet
- Fixed the Manipulation labels on 2 forms for the Werewolf sheet(put +1 instead of -1)
- Adding Persuasion to the translation files for the Wraith sheet
> Minor fixes to Wraith20 and new Werewolf 2e

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Spell Attacks are not getting set. This will fix that.
> D&D 5e - DEV 1977 - Spell Attack hot fix

- Low Fantasy Gaming/ReadMe.md
- Low Fantasy Gaming/sheet.json
* Added link to sheet Readme and game's homepage on the `Sheet instruction`-section.
* Readme mention of two uncommon abbrevations
@dedurrett If more info is added to the Readme later, it will be easier to find for the average user.
Is it fine if I include in the Readme  what the **TF** and **GS** stats means?
> [LowFantasyGaming] sheet.json & Readme edit

- Call_of_Cthulhu_7th_Ed/coc_7th_ed.css
A couple of users have mentioned that the sheet appears tiny to them. I have not made out yet if its from personal settings or something done wrong by me, but removing the Sheet's set-width seems to fix that. As it was added by me recently, I do not see its removal creating any problems.
> Call of Cthulhu 7th Ed. - Size fix

- CWOD-W20/W20.html
Changed the text area's name so it won't conflict with the radio buttons that had the same name.
Issue brought to me via private message on Roll20, from some one called "Ana.  (https://app.roll20.net/users/2338421/ana)
No data loss because the textarea wasn't holding any data anyhow.
- If changing or removing attributes, what steps have you …
> Werewolf W20 Appearance fix.

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Update the old NPC Spells text to inform users of its intended removal.
If …
> D&D 5e - UC 78 - Deprecated NPC Spell Text

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Fix the issue where Paladins could not level from 1 -> 2 due to a single spell select.
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repos …
> D&D 5e - UC 13 - Mancer Level up Fix single spell selection

- AEON-Aberrant/aberrant.css
- AEON-Aberrant/aberrant.html
This is a bug/layout fix
Some new buttons, better roll templates, some hide/show areas
Massive aesthetic change (its now readable)
Only this sheet (HTML and CSS)
The only attribute name change is from"Mega-foo" to "Mega_foo" because the roll template didn't like the dash.
- If changing or removing attributes, what steps have you taken, if any, …
> AEON-Aberrant Overhaul

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Encode Thoughts was not being displayed on Level Up. 
* Also added comments to the Mancer code.
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_She …
> 5e D&D - UC 26 - Fixed Encode Thoughts in Level+

- 5e Darker Dungeons/5e Darker Dungeons.css
- 5e Darker Dungeons/5e Darker Dungeons.html
- 5e Darker Dungeons/sheet.json
Fixed monster import: can now drop monsters onto the battlemap correctly.
Fixed global modifiers to match OGL sheet.
Added global AC modifiers.
Added toggle for intelligence as initiative.
Added repeating field for extra resources.
Fixed rounding error on inventory sizes.
Fixed rolltemplate character name rendering.
Added new notes page.
Show correct ability scores when modified (per the OGL sheet).
Added advantage/whisper toggle buttons to PC/NPC.
Fixed missing modifier in attack rolltemplate.
Increased size of personality/bond boxes.
Added useroptions to sheet.json.
Corrected persuasion modifier text from WIS to CHA.
Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in …
> Update Darker Dungeons sheet to v2.1

- Cyberpunk 2020/Cyberpunk2020.html
Not attribute changes.  Adding missing "}" in the steal skill
If you do not …
> Cyberpunk Steal fix

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Bugfix for Das_Schwarze_Auge_5 character sheet:
- Each parrying weapon now has its own attribute for range, instead of using the fourth weapons range
- Before it was not possible to correctly enter the range attribute for each parrying weapon as all had the same backing attribute (attr_ReichweiteNKWaffe4) instead of their own field.
- Now all parrying weapons use their own attribute created in the same naming scheme as the other attributes
- No other changes are necessary, as the fields are not used for auto calculation of values
> Das_Schwarze_Auge_5 Fixed: Each Parrying Weapons can now have its own range

- Forbidden_Lands/Forbidden_Lands.css
- Forbidden_Lands/Forbidden_Lands.htm
- removed "selected|..." from sheet rolls.  Rolls can now be made from the sheet regardless if a token is linked and/or selected.
- added a version attribute to the sheet.  Currently only used as a visual indicator, but could be used from version checking later if needed.
> Forbidden Lands v1.1 small update

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Refactored & optimize how resources & repeating inventory work together
* Remove the code that was force deleting the field if a name wasn't present
* Remove update_item_from_resource function. Nothing else uses this function so the code was integrated in the change events
* Fixed a bug that were not apparent with the changes above.
* Removing Item or a Resource will update the opposite.
- Are you intentionally …
> D&D 5e - UC 330 & 371 - Fix #4890

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Added update_save(ability); to allow for saves to be updated.
* fixed jack_bonsu to jack_bonus
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Shee …
> D&D 5e - UC 382 & 386 - Fix class saving throws

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* SRD was not loading hit die and saves on class select change
If you do not …
> D&D 5e - UC 405 - Fix Saves & Hit die for SRD

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
- Das_Schwarze_Auge_4-1/formulas.md
- Das_Schwarze_Auge_4-1/sheet.json
This PR marks the beginning of the conversion to sheet worker scripts. Basic stats and derived stats are now calculated via sheet worker scripts. Also, meta-talents received an overhaul. For other minor things, see below.
* **New features**
* Fill in meta-talent and gift stats automatically (034c130)
* Meta-talents, gifts, stats and derived stats use sheet worker scripts now (034c130, 68cd766, 64c1892, 046c050, b999a5c, 41cadf5, 26f8cc8, 0e50f75, f547692, 6f7f087, a4f8423)
* Support for custom gifts (d91ff2d)
* Version number for sheet data to be able to distinguish between the current character sheet version and the data version (969f110)
* Migration of old gifts data (557a5e1, 8928533, de389c0) and old meta-talents data (97ab820, de389c0)
* Tab for accessing old data manually (034c130, …
> [DSA4.1] Sheet Worker Scripts for Stats & Derived Stats, Gifts and Meta-Talents

- Valor/Valor Character Sheet.html
- Valor/translations/en.json
- Added missing skill "Safe Stride" to list.
- Fixed a bug where Mind-based Ultimate Attacks weren't generating text.
- Fixed a bug where Transformations showed the wrong amount of restored Health.
All changes compatible with previous version.
- If this is a new sheet, did you follow [Building Character Sheets …
> Valor: Sheet bugfixes

- Exalted 3/Ex3-Sheet.html
Field would calculate the would penalty wrong (Would add the wound penalty instead of subtract it)
Bug caused by incorrect function call in math ('abc' instead of 'abs')
- Is this a bug fix? [Yes]
- Does this add functional enhancements (new features or extending existing features) ? [No]
- Does this add or change functional aesthetics (such as layout or color scheme) ? [No]
- Are you intentionally changing more that one sheet? If so, which ones ? [No]
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ? [No attributes changed or removed]
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ? [ Sheet is existing]
*Include the name of …
> Exalted 3rd edition Bug Fix for Evasion Specialization Field

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* .replace wasn't replacing all of the spaces. Using a split & join instead.
If …
> D&D5e- UC-471 - fix sleight of hand bug

- Warhammer-Fantasy-Roleplay-2nd-Edition/README.md
- Warhammer-Fantasy-Roleplay-2nd-Edition/WHFRP2.html
Small update to fix career advancements to only update for career profiles marked as "entered".
- This is a fix to implement an intended feature.
- No player data should be affected.
- Value for attributes @{attr_CareerEntry#} changed from "100" to "1".
- Hidden attributes for calculating highest career profile changed to include @{attr_CareerEntry#} toggle.
> Warhammer Fantasy Roleplay 2nd Edition

- Star Wars Saga Edition/StarWarsSagaEdition.html
Correcting an error which duplicates certain rolls. All of the rolls removed already displayed outside of the more "#more" sections, this just removes duplicates.
> Fix Star Wars Saga Error that Duplicates Rolls

- Call_of_Cthulhu_7th_Ed/coc_7th_ed.css
- Call_of_Cthulhu_7th_Ed/coc_7th_ed.html
- Call_of_Cthulhu_7th_Ed/sheet.json
- Call_of_Cthulhu_7th_Ed/translation.json
• Changed Companions and Mounts to NPCs.
• Added Option to Hide all Major Sheet Sections, apart from Companions, Common Dice Rolls and Talents. (This comes in handy when running a game and want an ''NPC'' sheet.).
• Changed Add/Edit/Del Buttons appearance.
• Set Sheet Width to 840px.
• Changed sheet.json format to display Default Sheet options in Select style, and added minor info about the sheet.
- Are you …
> [Call of Cthulhu 7th Ed] Adding ''NPC Sheet'' and minor additions.

- Gumshoe by Roll20/GUMSHOE.html
* when fleeing have more than double the ranks athletics have, fleeing cost half the points to increase.
> Gumshoe - UC-309 - Fix fleeing buy calculation

- 5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
* Cantrips had the wrong display
If you do not know English. Please leave a …
> D&D 5e - uc-533 - fix cantrip display

- D&D_3-5/charsheet_3-5.css
Re-add closing comment tags to fix the CSS files so the StdRoll and Initiative roll templates work again.
(was broken with the encoding/line ending fix.)
Note: Was edited within the GitHub web file edit utility to try and prevent changing any of the encoding fixes.  It looks like that added a newline to the end of the file; don't know if that is a bad thing or not and I have no idea how to fix it if it is.
- Are you …
> D&D3.5 Roll Template Bug Fix

- A Song of Ice and Fire/SIFRPNew.html
Change to Alex Ott's sheet for A Song of Ice and Fire RPG to fix https://github.com/Roll20/roll20-character-sheets/issues/5183
Changed the roll for all roll buttons on the core section of the sheet.
By the rules all forms of -D turn Test dice into Bonus dice, and this change causes the roll buttons to respect this, rather than removing bonus dice, which is the current behavour.
##Changes / Comments
Restructured the rolls to look like this:
`[[ ( [[ ?{Dice|1} + ?{Bonus Dice|0} ]] )d6dl( [[ ?{Bonus Dice|0} + ?{Penalty Dice|0} ]] ) + ?{Modifier|0} ]]`
Should now be rolling `([Test dice] + [Bonus dice]d6dl([Bonus dice] + [Penalty dice]) - [Modifier]` …
>  [SIFRP] Fixed rolls from new sheet.

- Shadowrun5thEdition/Shadowrun5thEdition.html
Use 'repeating_spell' to attach listener, since repeating section is named 'repeating_spell' in the character sheet. This fixes the trigger and changes to dicepool modifier will now be included into rolls correctly (cc @clevett).
> Shadowrun5thEdition: Use 'repeating_spell' to attach sheet worker listener

- A Song of Ice and Fire/SIFRPNew.html
Fixes regression of rolls not working after https://github.com/Roll20/roll20-character-sheets/commit/e7928985df2b5b635cee57780246bf265892ed03.
The issue comes from so wierd Roll20 behavour. E.g:
The roll `7d6dl2` works fine.
The roll `( 7 )d6dl2` works fine.
The roll `( 7 )d6dl( 2 )` does not work (always gives 7).
The roll `7d6dl( 2 )` does not work (always gives 7).
This should fix https://github.com/Roll20/roll20-character-sheets/issues/5243
Removed parentheses `( )` around the drop lowest part of the rolls, as this stops them from working.
> [SFRPG (Alex Ott)] Fix to sheet rolls not working

- Palladium Fantasy 1E/ReadMe.md
- Palladium Fantasy 1E/sheet.json
The "scc" typo in the sheet.json has been corrected.  Made a couple additions and wording changes to Readme.md.
> [Palladium Fantasy 1E] fixed sheet.json typo

- Tri-Stat/Tri-Stat.html
Fixed the Tri-Stat sheet to actually display the weapon name correctly for attacks. This is a bug fix. No new functionality, the only aesthetic change is to display the name as was originally intended. No changed or removed attributes.
> Tri-Stat: Fixed tristat roll for attack to actually display the weapon name.

- GURPS/gurps.css
- GURPS/gurps.html
Fixed wording from roll table to roll template. (Cosmetic Only)
Fixed Spell Macro roll to include Modifier, if any.
Fixed the Spell Effective Skill level to include the Spell MOD, if any
Fixed columns for MOD, Pts, Duration, and Maintains. (Cosmetic Only)
Reordered column layout to match GURPS Magic format. (Cosmetic Only)
Added attributes Class and Resisted By under Spells.
Fixed Spells ‘Based On’ header to show the attribute chosen. (Cosmetic Only)
Reduced the attribute size for Diff, MOD and Pts and increased size for Cost and Time. (Cosmetic Only)
Added attributes for Latest Changes date. (Cosmetic Only)
Added attributes College and Modifier Notes for Spells.
Updated Spell roll template with the new Class ad Resisted By attributes.
Added Attributes Misc and Modifier Notes for Skills. …
> [GURPS] v1.6.1 Cosmetic and Fixes for gurps.html, gurps.css

- Cypher Systems by Roll20/sheet.json
* The accented e is throwing off the name in the sheet select settings. Replacing the accented e.
> Cypher Systems - DEV 2585 - replace the e in Numenera

- WOIN/WOIN.html
Points field for Psi and Magic points (will need additional work for Chi version of sheet)
Carried field and js to auto-sum Armor and Equipment weights to Carried field.
- [NA] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [NA] If this is a new sheet, did you follow [Building Character Sheets …
> [WOIN] Added Points and Carried fields

- WOIN/WOIN.html
Removed Luck Pool rebuild on sheet:open, to preserve Luck Pool use between sessions. Rebuild of Luck Pool happens only under specific circumstances and should be managed by player, not auto-calculated.
- [N/A ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [N/A] If this is a new sheet, did you follow [Building Character Sheets …
> [Woin] Luck Pool, Attack fields and Dmg Mod auto-calc

- D6StarWars/CHANGELOG.md
- D6StarWars/D6StarWars.css
- D6StarWars/D6StarWars.html
- D6StarWars/sheet.json
**Fixes:**
- Added back strength pip to Soak rolls in the armor section
- remove duplicate DM roll button from Tech skills
**Features:**
- **New sheet section:** Character Point summary; meant for tracking how points are used. Includes option to hide section
- **New sheet section:** Credit Spenditure summary; meant for tracking how credits are spent. Includes option to hide section
- **New sheet modes**: **Ship** and **Shop/Container** as new options alongside existing **PC** and **NPC** sheet modes
- **Default Settings:** All Settings defaults can now be adjusted by GMs in the [Game Settings Menu](https://wiki.roll20.net/Game_Settings_Page#Character_Sheet_Default_Settings) outside the game. Additional settings that can be changed are `Character Points`, `Credits`, `Force Points` …
> [StarWarsD6] V2.13

- Song of Ice and Fire Roleplaying/SIFRP.html
- Fix button roll for Agility Specialty for the repeating section. Was a typo in the attribute name called, leading to roll failing thanks to non-existing attribute
- tested on firefox
> [SOIAF] - Agility speciality fix

- Mekton Z/Mekton Zeta.css
- Mekton Z/Mekton Zeta.html
Adds new Roll Templates for Mecha Weapons
* Allows creating macros for mecha weapon attacks identifying properties in a simple layout
Minor issue resolution
* Some skill rolls displayed the incorrect text
* Some attributes were mislabelled and the calculation was broken as a result
* Syntax warnings concerning empty rulesets that are superseded by other rules
- This has been added as requested.
- Cleans up a few aesthetic issues with some rolls from the sheet.
- Adds new roll templates to allow for better macros.
> [Mekton Zeta] Additional roll templates

- Delta Green/delta_green.html
Final fix for issue #5150 
This issue veered off from its original topic.  The last update requested was for table headers to match position and widths for the data rows.  This change has been implemented.
This change is visual only.  No logic or character attributes were modified.
> Delta Green: Fixed table headers for weapons

- WOIN/WOIN.css
- WOIN/WOIN.html
WOIN-NEW uses a Condition Tracking system different to WOIN-OLD Status Tracking. Changes are on the Combat/Equipment tab under Conditions & Status Track
- added Condition Tracking
- linked Condition Tracking to sheet type toggle (NEW)
- linked Status Tracking to sheet type toggle (OLD)
- updated CSS to support Condition Tracking pull down menus field
- [N/A] If changing or removing …
> [Woin] html & css - Added Condition Tracking for NEW version of sheet

- Scum - Villainy/scum.css
- Scum - Villainy/scum.html
- Updates the faction sheet to add a feature; system names can now be edited for games in custom settings.  System names default to the four provided in the default setting (Rin, Holt, Iota & Brekk) so existing players will see no change.
- Provides a small edit to CSS that adds padding between system names and the carat that expands the system's notes.  This helps to prevent the user from accidentally expanding the system notes when they wish to change the system name and vice-versa.
> [Scum & Villainy] Allow system names to be editable

- Eclipse Phase V2/Eclipse Phase V2.html
- Eclipse Phase V2/translation.json
* Hardware & Meshware added to all four morph sections
* The 4 morph sections now are named Morph 1,2,3,4 by default instead of Morph 1,1,1,1
* Mental disorder roll buttons fixed
* Willpower check button fixed to use bcheckWIL instead of bcheckSom
* Free Fall changed to use somatics instead of previous reflexes
* Initiative rolls now add things to the turn tracker, and both uses 1d10 for rolls
* Psi table with "Break point" & "physical damage" mentioned now mentions only "physical damage" in the first slot, and the second slot is made editable plus missing description section of the second slot is added.
If you do not know English. Please leave a comment in your native …
> [Eclipse Phase V2] General bug fixes

- GURPS/gurps.css
- GURPS/gurps.html
Updated ToolTips for Fright Check, Knockdown and Stunning, Death, Unc. Check (Unconsciousness), ER, and Unstun - Cosmetic Only
Updated Knockdown and Stunning Roll Template - Cosmetic Only
Updated Unstun (Recovering from Physical Stun) Roll Template - Cosmetic Only
Updated Death Check Roll Template - Cosmetic Only
Updated Unc. Check (Unconsciousness) Roll Template - Cosmetic Only
Change the basic format of all ToolTips - Cosmetic Only
Corrected Wound Modifier Notes for imp, pi+, and pi++  - Cosmetic Only
> [GURPS] v1.6.5 Cosmetic Changes gurps.html and gurps.css

- mutants-and-masterminds-2e-master/mutants-and-masterminds-2e.html
Fixed a typo in the computers skill for Mutants and Masterminds 2e sheet (mutants-and-masterminds-2e.html).
> Fixed typo in computers M&M 2nd Ed skill name

- Log Horizon TRPG/LHsheet.html
Fix accuracy check for general skills: accuracy mod was applied 2 times.
accuracyTotal already include highMod.
> Log Horizon TRPG: Fix accuracy check for general skills

- CWorldofDarkness/CWoD.css
for some reason -91 makes one line of text go massively to the left but -78 and -79 fix it 
so thank you when you push this live 
and if anyone knows why this happens i would find it interesting to know
> CWorldofDarkness - changed the number in margin-left on line 528

- Low Fantasy Gaming/LFGSheet.html
- Low Fantasy Gaming/ReadMe.md
Fixed skills rolls to apply modifier to target number rather than roll result, to a maximum of 18.
Added sheetworker to update skill roll target numbers immediately when an Ability Score is updated.
> [Low Fantasy Gaming] Repeating Skills Update

- CyberpunkRED_Gerdofal/CyberpunkRED.css
- CyberpunkRED_Gerdofal/CyberpunkRED.html
Adjustments to html and css so clicking the skill names on tab 1 becomes an alternate way to roll an action. Also has some new functionality for netrunner actions and some other minor bug fixes. No changes to attribute names. Full list of commits: https://github.com/Gerdofal/roll20-CyberpunkRED_Gerdofal_BETA/commits/master
> CyberpunkRED_Gerdofal 2019 10 10

- Low Fantasy Gaming/LFGSheet.html
Several changes have been made:
- **Bugfix:**  The initiative roll now adds Dex and Bonus modifiers to the DC target rather than modifying the roll.  This is a roll under system.
- **Bugfix:**  Luck rolls now add bonus modifiers to the DC target rather than modifying the roll.  This is a roll under system.
- **Bugfix:**  Luck rolls will now use at least the minimum target value, (lvl/2 round up), as the DC to compare the roll to.
- **Bugfix:**  Luck rolls required the "Level" field to have a value or it would error out.  Set the default value of "Level" to 1.
- **Bugfix:**  "Terrible Failure" values were not capped at 20, and they should be.
- **Enhancement:**  Every ability check has a target DC for "great success" and "terrible failure".  Previously we had to put these values in every …
> Low fantasy gaming updates

- Fate Core v2/fate.html
`isNullOrWhitespace()` expects a string but sometimes receives a number, so I added a check for that. Also, `tim()` is clearly a typo.
> [Fate Core v2] Fix runtime errors

- Hc Svnt Dracones Second Edition/Readme.md
- Hc Svnt Dracones Second Edition/hsd2.css
- Hc Svnt Dracones Second Edition/hsd2.html
Update made on cooperation with publisher.
* "XP purchase"-section(Page 3) now automatically adjusts "XP Spent" and "Remaining Exp" when checking/unchecking new entires in the section(it does not prevent from selecting both options in places where ther are choices, nor does it prevent selecting things out of order).
* Editing "Total Exp" also updates "Remaining Exp" accordingly
* "Xp purchase"-section updates the numbers in the "Progression Purchase Tracking"-section, as well as increase credits amounts accordingly if credits have been gained through it. Adds a hidden "attr_progression_credits_track" attribute for tracking how many times credits have been gained through XP purchase
* "XP Purchase"-section choices now updates the Six Main Stats, Focus_max, Readiness_max, Base_move, …
> [Hc Svnt Dracones 2E] V.1.60 

- Exalted2e/README.md
- Exalted2e/exalted2e.css
- Exalted2e/exalted2e.html
- When selecting one of the Dragon-Blooded Castes, the sheet will show Dragon-Blooded statblocks, otherwise it still defaults to Solar
- Added some comments/space to code
- Minor formatting
- expanded Readme comments
> [Exalted 2E] Add Dragon-Blooded stat-blocks

- Palladium Fantasy 1E/palladium_fantasy_1e.css
- Palladium Fantasy 1E/palladium_fantasy_1e.html
I added toggle buttons in the melee attack section of the main tab that will enable/disable bonuses for mounted combat (pulling from existing attributes in another section of the sheet).  The mounted parry/dodge toggle required changes in the dodge roll button macro and the parry roll button macro in the repeating melee section.  The mounted damage toggles required changes to the strike and damage roll button macros in the repeating melee section of the sheet.  
CSS was added for the new toggles.  I also reduced the size of the whisper toggle buttons at the top of the sheet.
I put a mention of the addition in the release notes section of the sheet. …
> Update [Palladium Fantasy 1E] sheet

- Exalted2e/README.md
- Exalted2e/exalted2e.html
*  split Dragonblooded to use separate attributes from Solars, to track abilities. 
Due to this WoD sheet being older & more outdated than the others, making sensible additions harder to implement.
My addition of  statblocks for Dragon-blooded caused problems to existing sheets last week(specifically, the radio buttons did not display the  right number of dots for attributes shared with DragonBlooded, leading to the user to only see the stats valuee from the A&A tab).
This quick fix makes the Dragonblooded use separate set of attributes to track the same thing as the original Solars. It should be possible to implement the DragonBlooded  and other Castes without needing to give their "Abilities"-section separate attributes. If more Castes would be added by my current method, the sheet …
> [Exalted2E] Fix Solar abilities bug from last week

- Pavillon Noir 2/Pavillon Noir 2.css
- Pavillon Noir 2/Pavillon Noir 2.html
Those changes simply add a nice "jolly roger" flag behind the roll result. It's mostly esthetic, but it does also outline when the roll contains a critical success (1 on 1d10 in Pavillon Noir) or a potential critical fail (10 on 1d10).
I've split the change in two commit for clarity purpose, so that one can look at the commit adding the custom roll without the "change everywhere" of the second commit...
> Pavillon Noir 2 - Custom roll (enhancement)

- Knight/knight.html
Pour le changement fait à l'attribut :
Première ouverture de la fiche, je vérifie une checkbox qui, si elle est à 0 (valeur par défaut), déclenche la suite : 
- On vérifie les valeurs dans le repeating concerné (repeating_armeDruidLion) du bouton concerné (attr_leste). Si la valeur est celle cherchée (l'ancienne), je met la nouvelle. Sinon je ne fais rien.
- Je met ensuite à 1 la checkbox de vérification, histoire que la fiche ne revérifie pas.
> [Knight] Bugfix Druid

- AGE System/AGE System.html
- AGE System/sheet.json
- AGE System/translation.json
* added missing i18n-tags for the recently added "The Expanse" sheet section
* minor cleanup of `instructions`
* updated sheet version, to v.1.20.1
Last week's addition of "The Expanse" would have resonably bumped sheet from v.1.17.2 to v.1.20.0, and this bugfix being minor sets it at v.1.20.1. With the sheet having had no major update by the author @GhostMatter it seemed proper to follow the established 
> [AGE System] v.1.20.1 bugfix

- Ironsworn/sheet.json
Added link to sheet wiki page in `sheet.json` 'instructions' section so info on how to use the sheet and recent updates are easier to find to the average user. 
@LeeRhodes your PR descriptions are the best I've seen on this repo, ever, but they aren't easily accessible to the average user, or even someone who might make their way here to Github look at the sheet code, but this link & created wiki page should bridge that gap somewhat.
On the wiki page I linked & copied the info on your latest updates so people have easier to find them in the future, but future updates to the sheet would need to be manually added to the page for them to be found. Added a link to the sheet folder's github history so new updates will be easier to found by others.
Comments are very helpful for reviewing the …
> [Ironsworn] add link to sheet wiki page

- Palladium Fantasy 1E/palladium_fantasy_1e.css
- Palladium Fantasy 1E/palladium_fantasy_1e.html
I created a notes field to input situational saving throw bonuses to be displayed when saves are rolled, added a new field for character occupation specific notes, and posted a warning at the bottom of the first tab of the character sheet.  
There will be upcoming changes to the repeating attacks section that will remove a couple entry fields to make them "global" to that repeating section, so that this serves as prior warning of that change to the temporary bonus fields.
> Update [Palladium Fantasy 1E]

- Pathfinder_Cazra/sheet.html
There was a bug in the HTML of the sheet "Pathfinder_Cazra" (also known as "Pathfinder (Simple)" in the sheet picker during game creation) that showed the alignment value of "Chaotic Neutral as "CG" - resulting in everyone who chose "Chaotic Good" as an alignment in the character sheet to be displayed as "Chaotic Neutral" once the sheet was closed and re-opened.
I tested this with a custom sheet in an own game of mine and there were no issues. No player data needs to be changed or is affected otherwise, the alignment will simply be displayed correctly in the sheet from now on.
> [Pathfinder_Cazra] fix Chaotic Neutral alignment value

- nephilimV5-vf/nephilim-legende-vf.html
The repeating_vecus_passe line 214 is forbidden as state here https://wiki.roll20.net/Building_Character_Sheets#Repeating_Sections and should be modified into repeating_vecus-passe
> [Nephilim V5 FR] FIX - incorrect repeating ID

- AS&SH/assh.html
* "Astonishing Swordsmen & Sorcerers of Hyperborea" had a incorrectly named repeating section that resulted in stats in the section to not save
* [reported in this thread](https://app.roll20.net/forum/post/8069819/new-field-disappears-after-added)
> [AS&SH] Fix repeating section

- AD&D 2E Revised/2ESheet.html
Fixed currency calculations for all settings, this includes
- Standard
- Dragonlance
- Dark Sun
- Ravenloft
- Maztica
- BirthRight
My tests and results can be seen here:
https://app.roll20.net/forum/post/8070888/ad-and-d-2e-currency-calculation-is-wrong-for-ep-gp-and-pp/?pageforid=8072523#post-8072523
I have not changed any whitespacing or HTML element closures, even though the document seems to have multiple unclosed elements. I stricktly only fixed the calculations for curencies.
> [AD&D 2e Character Sheet] Fixed currency calculations for all settings and all currencies

- GURPS/README.md
- GURPS/gurps.css
- GURPS/gurps.html
Added and/pr modified several ToolTips – Cosmetic Only
Updated alerts due to HP and/or FP loss in Red – Cosmetic Only
Added ToolTips to ‘Reason for MOD’ with some examples – Cosmetic Only
Added a title to the Speed button to remind you that you must select a Token first – Cosmetic Only
Added missing macro name title for Current HP – Cosmetic Only
Add to Turn Order macro for Initiative has been revised to help eliminate ties – Suggested by Jared (UserID: 1026445)
When adding a new spell, it will now input 1 point automatically to avoid 0 point spells.
All are self-explanatory.
- [ X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ X] Is this …
> [GURPS] v2.1.1 Mostly Cosmetic changes: GURPS.html, GURPS.css, README.md

- Palladium Fantasy 1E/palladium_fantasy_1e.css
- Palladium Fantasy 1E/palladium_fantasy_1e.html
I have restructured the melee and ranged repeating attacks sections on the main tab of the sheet.  First I pulled the temporary bonus fields out of the repeating sections and gave them a place at the top of each section to make it easier to add and remove temporary bonuses.  I enlarged the bonus and notes fields and put them on a second line which can be hidden or revealed with a checkbox for each repeating entry.  I changed the "notes" entry from text to a textarea to enable line breaks, since the roll template can handle that formatting.
The temporary bonus fields within the repeating section are gone, and the button macros no longer check for those attributes, so any values left there will be gone.  I put a warning at the bottom of those sections 3 weeks ago and posted in the forum …
> Update Palladium_Fantasy_1E sheet

- GURPS/gurps.css
- GURPS/gurps.html
•	Adjusted the field widths for Techniques (Revised) and Parent Attributes – Cosmetic only.
•	Added new function of ‘Dodge and Drop’ to default Active Defenses.
•	Techniques Table Revised. Points spent on techniques are now totaled correctly. NOTE: When transferring techniques to the revised table, be sure to delete the old techniques, otherwise the total will be wrong.
•	Techniques Table Revised. Fix bug where Modifier was not added to the final Technique Skill Level.
•	Quirks/Perks Bugfix. Adding a row did not total the quirks/perks correctly.
•	Repeating Spells, quickly clicking checkboxes prevented correct totals. Using new code provided by GiGs to improve speed.
•	Many ToolTips updated or added.
•	Some slight format changes – Cosmetic Only.
•	Added a Defense Bonus (DB) Notes box to …
> [GURPS] v2.2.1 Bug fixes, Cosmetic changes, New features: GURPS.html, GURPS.css

- GURPS/gurps.css
- GURPS/gurps.html
Added some new ToolTips – Cosmetic Only.
Changed width of Weapon and Damage Notes fields, under Melee and Raged Attacks, to be more readable – Cosmetic Only
> [GURPS] v2.2.3 Bug fuxes, Cosmetic changes: GURPS.html, GURPS.css

- Les Chants de Loss/LCDL.html
bug correction for the following problems : 
- duplicate skill orientation
- duplicate attribute names for "experience total" and "experience reserve"
- duplicate attribute names for the diverse inspirations (Courage, Sagesse, Foi and Honneur used attr_hon)
- duplicate attribute names for the diverse affinités (Courage, Sagesse, Foi used the Attr_Corps)
- correct affinity score use in the skill rolls (all were using the attr_Honneur instead of the correct Courage, Sagesse and Foi affinity attributes)
@Zakarik if you can check the changes...
> [Les Chants de Loss] bug correction

- 5e Darker Dungeons/5e Darker Dungeons.css
- 5e Darker Dungeons/5e Darker Dungeons.html
Bug fixes and new features for the Darker Dungeons sheet.
- Fixed missing HTML span elements and indentation.
- Applied basic beautifying to HTML/CSS sheet.
- Fixed NPC reactions bug: Reactions now display correctly.
- Can now edit equipment quantity/slots/notches directly on the equipment panel.
- Containers can now add extra inventory slots.
- Items can now be marked as carried-but-not-equipped.
- Feature details can now be hidden/condensed.
- Currency names can now be changed.
- Added open skills to PC sheet.
> Update 5e Darker Dungeons to 2.2

- Monster of the Week/MotWHTML.html
The MotW playbooks specify that the spell-slinger's fire magic gives +2 damage, not +1. This corrects that.
From the revised playbooks and the revised rulebook:
> Correct fire damage for Monster of the Week Spell-Slinger

- Legacy - Life Among the Ruins/LegacyRoll20CSS.css
- Legacy - Life Among the Ruins/LegacyRoll20sheets.html
Minor cleanup of Legacy - Life Among the Ruins (2nd edition) character sheet.
Checkboxes should now work correctly in all places. (There were numerous places where the input items had the same names, leading to multiple selections.)
Also cleaned up some minor typos.
- [Kind of. Instead of reporting the bug, I just fixed it.] Is this a bug fix?
- [It fixes features that were broken.] Does this add functional enhancements (new features or extending existing features) ?
- [No.] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [All attributes that were …
> Legacy - Life Among the Ruins 

- RunequestGQS/RunequestGQS.html
The Magic modifier was calculated wrong. curPow was used in a place where curChr was the characteristic to check.
> [RunequestGQS] Magic modifier calculated wrong

- Pendragon5thEdition/pendragon.html
- Pendragon5thEdition/src/js/scripts.js
The derived attribute in question was mistakenly left out of the ternary determining what divisor to use - "damage" is supposed to use a divisor of 6 while "healing" and "movement" use 10.
Due to this and the boolean status of strings, the ternary condition was always true. All three derived attributes used a divisor of 6.
> [Pendragon5thEdition] Update ternary in attributeSumDivide to determine the correct divisor

- DeltaGreenRPG/delta_green.css
- DeltaGreenRPG/delta_green.html
substitute the relative path to the absolute relative to github for showing the art
I used relative path for all the images, resulting in art not showing up on roll20. I've updated all the relative path to an absolute one with respect to the absolute path on github (i.e. https://github.com/Roll20/roll20-character-sheets/DeltaGreenRPG/img/<nameimage>?raw=true) 
> [Delta Green] Bug fix Change relative path of images to absolute

- GURPS/gurps.css
- GURPS/gurps.html
Sheets:
GURPS/gurps.css
- Combat tab. fixed alignment issues with active defense arrow and chekbox when the sheet is popped out into a window.
- Combat tab - Active Defense Success/Fail Notes. Had time to restructure the Rules As Written (RAW) notes so they are  no longer part of the custom notes. They are now just stored on the options and automatically appended to the roll template.
- IMPORTANT: If you see double notes for active defense success, critical success, fail, or critical fail, you will need to manually delete the custom success/fail notes for each active defense. This is a one time edit and you will not need to do that again.
If you do not …
> [GURPS 2.3.1]

- Star Wars Revised RPG/SWRRPG.html
Duplicate classname caused to add a craft and knowledge skill when adding either skill.
> Duplicate classname fix.

- TheWitcher/witchersheet.html
Similar to file change #6075, the REC stat is recorded as REF, however here it is in the NPC side of the sheet.
> [TheWitcher] Typo with npc attributes

- NWOD-Hunter The Vigil/NWOD-Hunter.html
Feel free to tell me if this is breaking, i took a look at the page and couldn't find issues related to said change.
Yes
Yes
Nope
Nope
N/A
N/A
> Fix roll again behavior by removing trailling 8, NWOD-Hunter The Vigil

- Agone-(french)/agone-sheet.css
- Agone-(french)/agone-sheet.html
- A few typos were fixed
- Missing titles were added
- For Demons and NPCs, the SeriousWound and the Worker auto-calc for the associated Penalty were added
- A word was added about the Armor Penalty for PCs
> Agone-(french) new version (0.21)

- DCC_Tabbed_Sheet/DCC_Tabbed_Sheet.html
Remove critical hits from Dwarven shield bash.
The current code is broken. `critThreat` does not exist as an attribute.
Per the rulebook, a d14 scoring a critical hit is never mentioned, so I don't see that this is needed.
No
No
Not necessary
Not necessary
> [DCC_Tabbed_Sheet] Remove critical hits from Dwarven shield bash

- Shadowrun5thEdition/README.md
Macros were using modifier_toggle and wound_toggle instead of modifiers_toggle and wounds_toggle, causing them to cause an error on roll
> [Shadowrun 5th] Fixed the sample macros

- MERP/merp_2nd_ed_sheet.css
- MERP/merp_2nd_ed_sheet.html
- MERP/readme.md
- MERP/sheet.json
* [MERP] New feature: NPC/Creature sheet.
- Add new NPC tab for non-player characters. 
- Add new dedicated set of attributes for NPCs (this does not affect existing player data).
* [MERP] New feature: Whisper settings
- Add new settings tab with a drop-down menu for whisper settings.
- Integrate the whisper settings with all the roll buttons.
* [MERP] Re-label (fix) some roll button titles
> [MERP] Add NPC/Creature tab and whisper settings to MERP. 

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Small Bugfix. Would Treshold on Fighting-Site was wrong. Corrected it to show the same values as on the main stats page.
> [Das_schwarze_Auge_5] - Wound treshold corrected

- Ironsworn/Ironsworn.html
The endure stress oracle roll template had been missed when implementing the oracles. This now works as expected.
- Fixed the Site Name oracle header to no longer be camel-case.
> [Ironsworn] [Fix] Added Missing Endure Stress Oracle

- Old School Essentials - AAC/OSE-AAC.css
- Old School Essentials - AAC/OSE-AAC.html
- Old School Essentials - AAC/translation.json
- Encounter movement rate should be exploration * 1/3, not 1/4
- Missing `weaponDescription` caused error in Character tab
- Add "Type of Attack" to weapon table to only add DEX bonus to attack and not damage
- Change hit point and HD fields for characters to be more flexible and roll using a button
- ~~Does this add or change functional aesthetics (such as layout or color scheme) ?~~
- ~~If changing or removing attributes, what steps have you taken, if any, to preserve player data?~~
- ~~If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?~~ …
> [Old-School Essentials - AAC] Fix encounter movement rate and missing weaponDescription

- D&D_3-5/charsheet_3-5.html
from:
```
... data-i18n=" data-i18n="load" ...
```
to:
```
... data-i18n="load" ...
```
I agreed to an incorrect html attribute, and wanted to try my first PULL request :) .
it is a very small error, I don't think it gives real problems, as far as newer browsers are concerned, they are able to automatically correct this syntax error.
I wanted to give my support, as a thank you for the work done by Diana
> Html syntax error, attribute not closed

- ADnD_1E/1ESheet.css
- ADnD_1E/1ESheet.html
- added languages field.
- fixed typo in non weapon prof ability selector (Charisma was listed as Strength).
- updated macro used for non weapon prof check.  Existing macro did not utilize @{rmodifier}. New macro will roll 1d20 vs proficiency check threshold (@{rAttribute}+@{rmodifier}+modifier query).
- removed coin conversion to lbs.  All weight is tracked in gp's.
- changed sheet background checkbox to a radio selector.
- small updates to title text.
- added Strength Encumbrance bonus under Carrying Capacity as a reminder it should be included when determining thresholds.
- versioning routine included to check if existing nwp macro-text has been edited so that only unedited(default) macro-text will be replaced with the new macro-text.
Comments are very helpful for reviewing the code …
> ADnD1e update

- Aquelarre/aquelarre.html
FIX: Roll for custom language not working (wrong attribute name)
Updated attr name
> [Aquelarre] Update aquelarre.html

- Supers-Revised-Edition/supers-revised.css
- Supers-Revised-Edition/supers-revised.html
- change img urls to point to Roll20's repo 
- The sheet is incorrectly categorized under "GURPS". The game is standalone and have no conection to GURPS, and should be in a category by itself under the games own name.
> [Supers RED] v1.2 url fix + Request to correct Sheet Category in dropdown

- Ironsworn/Ironsworn.html
There was a drop-down option for Shadow-Kin included in the Swear an Iron Vow Move roll query. This was accidently added and should be removed.
> [Ironsworn] Removed Shadow-kin Option from Swear an Iron Vow

- Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Advantage for ranged bonus was calculated wrong (same for all distances). 
Corrected it, so it only affects distance "far".
> [Das schwarze Auge 5] Bugfix ranged attack

- Naheulbeuk/Naheulbeuk.html
- Naheulbeuk/readme.md
Correct some typographic errors from Naheulbeuk sheets.
* `Resits` by `Resist`
* `armre` by `arme`
* `basculter` by `basculer`
> [Naheulbeuk] Fix minor typos

- AllforOne/AllforOne.html
- BakerStreet/BakerStreet.html
- Call_of_Cthulhu_DA/Call_of_Cthulhu_Dark_Ages.html
- Elric/Elric.css
- Heroquest_Glorantha/Heroquest_Glorantha.html
- Our Last Best Hope/ourlastbesthope.html
- Sengoku/Sengoku.css
- Stargate-RPG/Readme.md
- Stargate-RPG/stargate.css
- Terre 2/Terre 2.css
- vampire-v5/VTM_Dice_Mechanics.js
* change several sheets that had image link pointing to the creator's repo so they now point at the images' location in the Roll20 repo. Tested the unsure cases
> [10 Different Sheets] change image link to point at Roll20 repo

- Starfinder (simple)/Starfinder (simple).html
The 'Perception' button for NPCs was misspelled.
> Starfinder (simple): Correct 'Perception' spelling in NPC sheet

- WFRP4CharSheet/WFRP4Charsheet.html
WFRP4 sheet does not use character attribute for `Ranged(Entangling)` skill due to typo, this fixes that
> [WFRP4CharSheet] Fix Ranged(Engtangling) typo

- Band of Blades Official/blades.css
Temporarily replace the critical background by the normal background until the image proxy is no longer broken.
Fixes #6541.
> [Band of Blades] Critical roll template hotfix

- PokemonTabletopUnited/ptu.html
Added value=1 to attr_st_froz so when the Frozen checkbox is ticked, attr_st_froz returns 1 instead of  on. This brings it in line with other statuses which already have value=1 in them.
> [PokemonTabletopUnited] Fix frozen status not saving correctly

- Starfinder (simple)/Starfinder (simple).html
This is a minor spelling fix on the Starships tab of the character sheet from 'senors' to 'sensors'.
> Starfinder (Simple): minor spelling correction on starship tab

- Starfinder (simple)/Starfinder (simple).html
Fixed several attr's that were not saving data on Drone Sheet
Fixes for the NPC portion of the sheet:
- Move  fields for race and class to correspond with sheet titles
- Modified Class level to distinguish it from PC Class level of the same name
- Add Source field to Fly movment
- Add None option and set it to selected for Misc Skills to aid in parsing NPCs in the future
> Starfinder (simple) update 05272020

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.css
- Old School Essentials - AAC/OSE-AAC.html
- Old School Essentials - AAC/sheet.json
- Old School Essentials - AAC/translation.json
- Add an option to disable threshold modifier. Closes wesbaker#9
- Add monster, normal human, and custom classes as class options. Closes wesbaker#10
- Add auto-calculating saves and BAB/THAC0 for monsters either as monster HD or as class and level. Closes wesbaker#10
- Add monsters in wilderness number appearing values. Closes wesbaker#11
- Change class input to a dropdown. Closes wesbaker#10
- Change monster attacks so there is no minimum damage. Closes wesbaker#8
- Fix movementEncounter and movementOverland not being available to tokens (needed to be readonly versus disabled, which means it needed to be calculated via sheet workers and not in the value itself). Refs wesbaker#8
- Fix a bug where monster attack descriptions were not shown
Comments are very helpful for reviewing the code …
> [Old-School Essentials by Necrotic Gnome] - 1.2.0

- Mongoose_Traveller/MongooseTraveller.html
The specialty skills have an upper case letter in their fieldset name, causing button rolls to fail when called in macros. Fixed.
> Mongoose Traveller 1e - fixed repeating section rolls

- Mongoose_Traveller2e/MongooseTraveller.html
The specialty skills have an upper case letter in their fieldset name, causing button rolls to fail when called in macros. Fixed.
> Mongoose Traveller 2e - fixed repeating section rolls

- Scion2e/scion2e.html
Modified the attributes used to build the roll for the roll template to use exploding dice (d10!) instead of normal d10's. Also added the curly brackets needed for the roll engine to understand that we want to explode normally, not based on the target number. This changes the behavior of the embedded roll template to match the Storypath system rules, excerpt: "If a player rolls a 10, that die gives one success and is rolled again. This is called 10-again, and it continues until no dice show a 10. "
Whether this means that the change is a bug fix or not depends on philosophical questions I shan't ponder here.
- [YES] Does the pull request title have the sheet name(s)? …
> [Scion2e] Rolls fixed to use exploding dice

- LANCER RPG (1.8)/LANCER.html
When base damage and bonus damage were the same type, only the bonus
damage would display. This adds additional template variables to let
the bonus damage always display separately.
- [n/a] If this is a new sheet, did you follow [Building Character Sheets …
> LANCER RPG (1.8): Fix bonus damage display

- Cyberpunk 2020/Cyberpunk2020.html
Change 1d10! to 1d10!!
If you roll in 1d10 10 and critic as 1, mark with pifia
----------
Cambiado el commando de 1d10! por 1d10!!
Si lanzas 1d10 y el critico es 1, lo marca como pifia. (en las tiradas de armas)
> [Cyberpunk2020] html corrections

- Torchbearer/torchbearer.css
- Torchbearer/torchbearer.html
- Torchbearer/translation.json
- Fixed rounding in Beginner's Luck macros from floor() to ceil()
- Added title to Beginner's Luck button since it's noted only as abbreviation and it was hard to recognize for some players
- Added Spellbook checkbox into magic section for better user expirience of magic-users. This checkbox required because of the wizard's known spells (written in the sheet) is not the same as the spells in the traveling spellbook (it has limited space).
> [Torchbearer] Magic and Beginner's Luck improvements

- LANCER RPG (1.8)/LANCER.css
- LANCER RPG (1.8)/LANCER.html
This adds a fouth button to the character sheet to roll the 6d6
dice block instead of rolling it every time. If the previous
ACC/DIFF buttons are used, an annotation is displayed next to the
calculated roll instead.
- [Y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a] If this is a new sheet, did you follow [Building Character …
> LANCER RPG (1.8): Make always rolling 6d6 optional

- Champions Now/Champions Now.css
- Champions Now/Champions Now.html
Bug fix:
- REC is no longer a primary stat, but correctly derived from BODY
New features:
- Automatic expenditure and recovery of Endurance is now possible
- The sheet will calculate (but not auto-calculate) point totals, and track XP
> Champions Now: assorted quality of life improvements

- Champions Now/Champions Now.css
- Champions Now/Champions Now.html
Bug fixes:
- Cost calculation now works correctly for situations
- Recovery now includes KO as well as END
New features:
- Added a button to announce initiative (DEX, EGO, SPD, and Phases)
> Champions Now: fix recovery and point costs

- Heart-the-City-Beneath-mk2/Heart.html
- Heart-the-City-Beneath-mk2/translation.json
Correcting the button roll mechanic for Fallout tests, which should take into account all stress tracks rather than individual stress tracks.
Also added internationalization support for two button labels.
(As an aside, please forgive me for the earlier PR-related hiccups that I couldn't quite seem to smoothe out without just starting a new PR altogether.)
> correcting Fallout mechanic button

- Monsterhearts-2/Monsterhearts-2.html
Four Skins (read: character classes) that were released after the game's original launch were missing from the selection. They're now included for players to choose from.
[Chosen](http://buriedwithoutceremony.com/wp-content/uploads/2017/05/the-chosen.pdf) • [Serpentine](http://buriedwithoutceremony.com/wp-content/uploads/2017/05/the-serpentine1.pdf) • [Cerberus](https://buriedwithoutceremony.com/wp-content/uploads/2019/03/The-Cerberus.pdf) • [Disciple](https://buriedwithoutceremony.com/wp-content/uploads/2020/01/The-Disciple.pdf)
Absolutely nothing was changed from the original code besides the added Skins and a credit for my work alongside the existing names.
If you do …
> [Monsterhearts 2] Additional Skins added (Chosen, Serpentine, Cerberus, Disciple)

- Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.css
- Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.html
- Add back 'Posession'-tab that was removed without migrating measures in #6778 by @ChristianMCGarcia. 
- Was brought up by user in this [forum post](https://app.roll20.net/forum/post/8873104/character-sheet-changed-during-use) as it removed a used feature/stat of the sheet for them. As the change was removing a feature of the sheet without migrating the stat anywhere, it should have never been approved, considering it wasn't an upgrade to the sheet. If an *option* to hide the tab had been made, or moved the stat to the last tab, it would have been better. 
> [All Flesh Must Be Eaten] Revert recently removed stat

- Halo_Mythic_3dot5/HaloMythic3dot5.css
- Halo_Mythic_3dot5/HaloMythic3dot5.html
:green_square: 1 Fix text expand in the Weapons section overlapping with buggy to chat button
:green_square: 2 Skills do not work on firefox(added firefox compatibility mode)
:green_square: 3 The hit table is mislabeled  (46-60)
> various fixes for mythic 3.5

- A Fistful of Darkness/README.md
- A Fistful of Darkness/aFoD.html
- A Fistful of Darkness/translation.json
V1.2 Fine Hellstone fixed (was 2 not connected boxes, now 3 connected boxes)
Minor change to Hellstone boxes, see above
> [A Fistful of Darkness]V1.2 Minor Fix

- UltimaTorcia/CS_LUltimaTorcia.html
Adding new roll buttons in Character(Personaggio) and Weapons(Armi) sheets:
- Health and Mana recovery after a refreshing rest
- Charge weapon roll and Weapon Breakage roll
> Adding new roll buttons

- Ironsworn/Ironsworn.css
- Ironsworn/Ironsworn.html
- Ironsworn/src/Ironsworn.styl
- Ironsworn/src/components/moves/mixins/container.pug
- Ironsworn/src/components/moves/mixins/move-builder.pug
- Ironsworn/src/components/moves/moves.pug
- Ironsworn/src/components/moves/moves.styl
- Ironsworn/src/components/oracles/oracles.styl
- Ironsworn/src/data/move-list.pug
- Ironsworn/src/data/scroll-list.pug
- Ironsworn/src/package-lock.json
- Ironsworn/src/roll-templates/moves/moves.pug
- Ironsworn/src/roll-templates/oracles/oracles.styl
- Ironsworn/src/workers/scripts/stats.js
The Discover a Site move had not been re-implemented when migrating to pugjs. There were also some other issues that cropped up as part of this release, outlined below.
Resolves #6884 
- It was only using the iron stat for endure harm. Resolves #6897 
- Reordering Scrolling move list, as the most used moves where in the centre of the list.
- Unprepared Debility was not being set when supply reached zero. This was because of the wrong attribute been looked for.
- Removed some dead Ironcrunch code.
> [Ironsworn] Discover A Site and minor fixes

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where the strength bonus was not added to attack rolls. Closes wesbaker#26
- Fix a bug where new characters would have AC of 0
- Fix armor calculation code to account for worn armor
> [Old-School Essentials by Necrotic Gnome] - 1.5.1

- D&D_3-5/charsheet_3-5.html
The Repeating section for divine level 1 spells is a bit flakey. This is a bugfix for that. It adds a version function to migrate attributes from the old section to the new.
> [D&D 3.5] Bugfix

- Chronicles of Darkness/CofD.css
- Chronicles of Darkness/CofD.html
These changes are mostly related to styling and simplifying the logic for sheet rolls.
* Display 'Player' label for Geist: The Sin-Eaters Second Edition sheets.
* Update Willpower max amount whenever Resolve or Composure attributes change.
* Replace remaining `.sheet-attr` checkbox-span styling with buttons updating hidden flag attributes.
* Replace more instances of radio-span styled "dots" with buttons updating hidden attributes.
* Replace an HTML `table` with CSS Grid styling.
* Use new `wod` roll template for sheet rolls rather than `3part` roll template.
* Use hidden attributes for dice pool value and display, allowing a simple roll template and auto-calculated roll button value.
* Set the roll image on the button, rather than a transparent (and small) button overlaid on a background …
> [Chronicles of Darkness] Styling and Sheet Roll refinements

- Shadowrun6th-German/sheet.html
toggle-hide in front of the drain dropdown deactivated
no other changes ... just a bugfix according to https://app.roll20.net/forum/post/8786790/shadowrun-6-sheet-german-work-in-progress-translation-en-later/?pageforid=8939316#post-8939316
> changing visibility of drain attribute

- Tormenta20/tormenta20.html
Vida and Mana max attributes didnt work with token bars, due to being based on autocalc sheets. Added a sheet worker to calculate them instead.
Also combined the stat mod workers into a single one, and removed sheet:opened from a repeating section without a row id to avoid the startup error.
> [Tormenta 20] Max vida and mana fix

- Legend-of-the-Elements/LOTE.css
A line break in the Legend-of-the-Elements/LOTE.css was preventing the Watershaper sheet from being correctly loaded. This fixes it.
> [Legend of the Elements] Fix bug when selecting the Watershaper

- Fate/FateOmni.css
- Fate/FateOmni.html
- Fate/sheet.json
- Fate/translation.json
Character sheet now has a space for pronouns.
Support for swappable skillsets (useful for various shapeshifting implementations).
Support for Ngen Mapu gameset.
Extras Icon bug fixed (minus/blank swapped), added option to display a 2nd and 3rd icon. Closed a missing span tag.
Skills are "externalized" from their fieldsets as named attributes in the format Skill-[Name], e.g., Skill-Athletics attribute stores the numeric value of the Athletics skill and can be addressed in macros via @{selected|Skill-Athletics}.
Aspects are externalized as Aspect-[Label] attributes with the name of the aspect as the value. If multiple aspects with the same-named label are encountered, subsequent instances are given a number, so you might have Aspect-OtherAspect and Aspect-OtherAspect2 if you had two aspects …
> [Fate] Sheet Updates week of July 14th 2020

- Only-War-Enhanced/OnlyWarEnhanced.css
- Only-War-Enhanced/OnlyWarEnhanced.html
Changes / Comments
CSS: added semicolons to all padding statements for consistency
HTML: changed "1 2 3" choices to "0 1 2"
fixed a bug in the sheetworker that had broken calculations in the Psykana tabadded (EPR * 5) to Focus Power Tests
yes: the previous release's autocalc field for "attr_effective_psy_rating" read from incorrect values, creating a misleading result.
yes: the EPR is now handled by a sheetworker, making it easier to reference in other macros, and the Psychic Phenomena modifier is now calculated and displayed automatically, courtesy of the same sheetworker.
Removed the disclaimer from the Psykana tab because it's no longer needed, replacing it with a new …
> [Only War (Enhanced)] psyker sheetworker fixed

- approved.yaml
I understand we're generally not meant to update the `approved.yaml` file. This is just putting the Chronicles of Darkness sheet into the correct category - "Storytelling System", *not* "Storyteller System".
> [Chronicles of Darkness] Fix category

- AW2E-Burned-Over/apocalypse-world-burned-over.html
#6922 It was pointed out that the dice roll button for Harm used the stat incorrectly, so I changed the equation.
> [AW2E Burned Over] Fixed harm roll

- Mork Borg/morkborgsheet.html
A couple fields on the Mork Borg character sheet were missing an attribute name, so they weren't getting persisted.  This change just adds the attribute names so that the values aren't lost whenever the sheet refreshes.
- [ x ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ x ] Does this add functional enhancements (new features or extending existing features) ?
> Mork Borg - Add missing attributes for items carried and current omens.

- Chronicles of Darkness/CofD.html
Move border divs to be underneath clickable divs in the CSS Grid for Attributes.
This issue occurs in Firefox, but not in Chromium (Chrome, Edge, Brave).
This is an alternative fix to #7039
> [Chronicles of Darkness] FIX Attribute Grid Order

- Tormenta20/tormenta20.html
A subtitle property was appearing twice on a specific template roll.
> [Tormenta20] little fix on custom template roll

- d20 Modern/d20 Modern.html
The D20 Modern SRD lists several skills as having armor penalties.  These penalties appeared to be missing from a few skills.
> [D20 Modern] Adding missing armor penalties

- Palladium Fantasy 1E/palladium_fantasy_1e.html
Changed the output of the perception roll button.  Perception doesn't actually exist in this old ruleset, and so I had inserted my homebrew version of it.  It has been changed to use the version of perception from the Rifts game system (also produced by Palladium Books).  I only learned of that rule while writing the Heroes Unlimited 2E sheet, so thought I should probably bring that rule here also.  
This changes no attributes, just the output of one roll button to a more "official" version.
> Update Palladium Fantasy 1E

- Coriolis Alternative/CoriolisAlternative.html
- The repeating field for **talents** was using the same attribute as **critical damage**. Changed the talent attribute to the correct attribute.
- This will unfortunately result in some data loss for players
> (Coriolis Alternative) Fixed wrong attribute on talents

- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
Can parse more statblocks that led to errors.
The text area for statblocks is now in a dedicated tab, so that the user is forced to click outside to see the result.
> Chroniques Oubliees: improvements for the import of statblocks

- Palladium Fantasy 2E Sheet/palladium_fantasy_2E.css
- Palladium Fantasy 2E Sheet/palladium_fantasy_2E.html
Added a new tab called structures.  This tab has a place to describe and track damage to a ship or a structure of some sort.  Attacks can also be set up for arrow volleys, siege weapons, etc.  I also adjusted how the wrapping works on the tab bar to take up a wider space before creating another row of tabs.
> Palladium Fantasy 2E

- Only-War-Enhanced/OnlyWarEnhanced.css
- Only-War-Enhanced/OnlyWarEnhanced.html
- Only-War-Enhanced/sheet.json
Added Righteous Fury roller, tables.
added an option to toggle a crunch summary for Righteous Fury rolls
Edited Crit and Fumble thresholds to show when Psychic Power rolls fail or cause Psychic Phenomena
Re-ordered the Psychic Abilities block to look better
Re-ordered the Melee Weapon block to look better
Re-ordered the Ranged Weapons block to streamline function, make room for new Mishap Chance
Added dropdown for Mishap Chance for ranged weapons. Added "spray?" checkbox to add a Fumble on a "9" when rolling damage.
No, this is a feature update.
Added Righteous Fury roller, added Mishap Chance dropdown menu for ranged weapons. 
Updates to the statisic blocks for Ranged …
> [Only War (Enhanced)] update 08/16/20

- D6_Adventure/D6AdventureSheet.html
Updated the labels on the radio button toggles for ease of reading.
Modified the dice mod toggle to have a better off usage.
- [ X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [X ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
> [D6 Adventure] Updated Toggle Labels, tweaked dice mod toggle option

- Iron Kingdoms RPG/IKPRG.html
The Investigation Skill is supposed to be an Intellect skill instead of a Perception one (as stated in Iron Kingdoms Unleased Core Rules, pg.184), updating the field that references which attribute to use to properly reflect that.
Fixes #7302
> [Iron Kingdoms] Correcting Investigation attribute to Intellect

- Twilight-2000-v2.2/Twilight2000.css
- Twilight-2000-v2.2/Twilight2000.html
Minor css change to remove the radii  from text inputs
adjusted Mag header on missile weapons
Automatic hit location roll with damage
Added rolled number to hit location to use with 4 legged hit location
Clarified hit location hit capacities
Added missing logo
The initiative button will now add a token to the turn order if a token is selected when it is clicked.
- [x ] Does this add functional enhancements (new features or extending existing features) ?
> [Twilight 2000 2.2] css tweak and sheet improvments

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- New checkbox on the ability tab of the PC character sheet that toggles between :
- Display mode, with the name and full textual description of the ability
- Edit mode, where the user can enter the abilities in text areas (the first line of the text area is always assumed to be the name of the ability).
- The list of paths and abilities for the character profile can now be imported using JSON data copied from a public API and pasted into the sheet.
- It is now possible to link an ability roll with one of the abilities in the grid, by specifying the corresponding path and rank numbers. This information is mainly used by the API script COlib. This companion script also allows JSON data import, not only in the character sheet but also in the Roll20 journal.
Comments are very helpful for …
> ChroniquesOublieesContemporain Version 3.6

- Spell_the_RPG/spell.html
Changed how spells are rolled, as they weren't following game rules previously. It does delete one attribute option from the spell list, but that's due to that attribute not being needed per rules of the game. None of the base attributes have been changed.
- [ x] Does the pull request title have the sheet name(s)? Include each sheet name.
> Update spell.html for SPELL the RPG

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
- Changed encoding and display of recovery points (value instead of check boxes)
- new values are computed by sheetworker from old representation.
- Display attack options in tab
> Chroniques Oubliees: version 3.6

- Age-of-Sigmar-Soulbound/README.MD
- Age-of-Sigmar-Soulbound/soulbound.css
- Age-of-Sigmar-Soulbound/soulbound.html
added new options menu (Accessible by the cog symbol) 
added npc sheet (toggle between player and npc switch in options menu)
fixed issue with wounds, sheetworker will update existing sheets
Fixes an issue with wounds not being able to be used in token bars
Adds options section
Adds cut down NPC version of the sheet
Minor changes to PC sheet to allow some text boxes to expand
Added on sheet:opened to the calculation for wounds, this coincidentally also fixes existing sheets
> [Soulbound] NPC sheet

- HARP/harp.html
Bug caused by residual code accidentally pasted into sheet from prior version caused the level to calculate based on incorrect input causing an erroneous value in the characters level. The level is not supposed to in this version of the sheet.
> [HARP] Character Level Bug Fix

- Dark_Heresy_2ed/DarkHeresy2ed.html
Before the fix putting a plus sign in the modifier query (e.g +10) caused a modification of the roll of 0. Now it makes no difference if you put a plus in front or not (10 === +10)
> [Dark Heresy 2e] allow plus sign in modifier query

- Age of Ambition/aoa.html
Fixed typo in the Age of Ambition character sheet. The character creation stat array was missing a value.
> Fixing typo in Age of Ambition character sheet

- Chronicles of Darkness/CofD.html
The Geist character sheet had a value called "crisis point" that had the same value for the three boxes, which means that whenever the player wrote something on any of those places, the three of them repeated. This was making it impossible to have different values on those text-boxes. I've made a simple change to fix it.
The Geist character sheet had a value called "crisis point" that had the same value for the three boxes, which …
> [Chronicles of Darkness] Fixed Geist repeating crisis points

- CWOD-Technocracy/Technocracy.html
- formatting changes - top section now enforces line breaks
- bugfix: Added missing Abilities for die pool lists
- updated Die Pool and sheet workers - die pool now prints out the attributes rolled (eg Dexterity+Dodge) instead of "Die Pool X". This will clear the settings for the Die Pools however will not lose or remove any attributes.
Workaround implemented: since the sheet is unable to query the state of a dropdown box for the displayed text, the original text is used as the value, and the on change event updates a hidden element with the actual value to be used.
> [CWOD-Technocracy] - Die pool update, minor formatting changes

- Age-of-Sigmar-Soulbound/README.MD
- Age-of-Sigmar-Soulbound/sheet.json
- Age-of-Sigmar-Soulbound/soulbound.css
- Age-of-Sigmar-Soulbound/soulbound.html
added party sheet
added npc initiative to tracker
added initiative rolls, can choose between none, d6 and 2d6
made defaults for sheet type (only player/npc) and initiative dice
all stat rolls were named the same, this PR fixes that so they have the correct names
adds a party sheet and improves initiative to allow for the optional rule of adding d6/2d6
party sheet has its own aesthetics but is consistent with the rest of the sheet
> [Soulbound] Party sheet and initiative improvements

- ChroniquesOubliees/co.html
- Improved display for equipment
- when importing statblock, compute the type of atack.
> Chroniques Oubliees: small improvements.

- Reve de Dragon - french/RDD.html
Fix following attribute name for the "Reve de Dragon - french" sheet
- change attr_blessure0_1_desc to attr_blessure1_1_desc
- change attr_blessure0_2_desc to attr_blessure1_2_desc
- change attr_blessure0_1_desc to attr_blessure3_1_desc
Currently, the attr names are mispelled and stored to the wrong "blessure" (wound) :
Grave (Serious) and  critique (critical) wound descriptions are stored using légère (light) wound descriptions.
> Fix blessure desc bug for Reve de Dragon - french

- Reve de Dragon - french/RDD.html
Adding 
Adding rolling buttons for those "caractéristiques": 
- APPARENCE
- INTELLECT
- CONSTITUTION
- EMPATHIE
- FORCE
- AGILITÉ
- CHANCE
- DEXTERITÉ
- Mêlée
- VUE
- Tir
- OUÏE
- Lancer
- ODORAT-GOÛT
- Dérobée
> Update Reve de Dragon - french adding characteristic button rolls

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- Removes undesired margins causing _"vs Special Defense"_ to require a second line in the move roll template
- Also reduces the font size for this label
- ~~Corrects the attribute name used in the sheet worker reacting to move field changes to update the total damage~~
- This change was folded into a separate piece of refactoring work
- Marks the Normal move-type hidden checkbox as checked by default. This ensures new moves are styled correctly for the information indicated by the fields within the section
> [PokemonTabletopAdventures_v3] PTA3 Sheet bug fixes

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Adds support for displaying whether conditional effects are applied when making an attack using the move roll template
- Adds support in the character sheet for providing detail about conditional effects that can apply as riders to attacks
- Adds a static field that provides the total accuracy bonus, and displays the total accuracy roll, for each move
- Refactors the previous total damage roll to provide the same benefit and functionality
- Allows the move roll template to recognise when a move requires a customised critical hit calculation and performs that to ensure critical hits are reported as accurately as possible
- Prevents the damage field from displaying if the damage would be 0 to preserve valuable chat log real estate
- Greatly extends the move roll template's ability to …
> [PokemonTabletopAdventures_v3] Improves the Move roll template

- Fate/FateOmni.css
- Fate/FateOmni.html
- Fate/sheet.json
- Fate/translation.json
- Pronoun box given more width
- Aspects can now have an optional category header to divide sections up if desired
- Sheet preferences now include the ability to toggle on or off a Fate logo (defaults to off)
- Stress and Condition tracks can now go up to 10 in length
- Situation aspects with zero free invokes were getting turned into one free invoke situation aspects; this was a bug. Fixed now, zero free invoke situation aspects should work correctly now.
None of these should affect existing stored data for characters already in use.
> [Fate] Updates for 2020-10-29

- Lex Arcana/LexArcana.html
This is a minor bug fix to remove a defect where the checkbox for the encumbrance 19 and 14 had a clashing name.
> [Lex Arcana] fix encumbrance box 19

- Empire_des_cerisiers/EdC.css
- Empire_des_cerisiers/EdC.html
- Empire_des_cerisiers/ReadMe.md
- Empire_des_cerisiers/sheet.json
- Added : players can now check for gm roll on top of the character sheet
- Added : bonus on armor 
- Updated : change on some labels
- Updated : players can now equip multiple pieces of armor
- Updated : when using arrows for selecting associated field,  players can now select "blank" to remove association
- Updated : split skill and ritual calculator in two separated forms
> [L'Empire des Cerisiers V1.2] New features and updates

- Império De Jade/ImperioDeJade.html
Fix in Weapon attacks for Império de Jade sheet
Fix no calculo rolagens de ataques com armas corpo-a-corpo e armas à distância.
- [Y ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [Y ] Is this a bug fix?
- [N ] Does this add functional enhancements (new features or extending existing features) ?
- [N ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [N ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_ …
> Fix to Character sheet ImperioDeJade.html

- Official Savage Worlds/SavageWorldsCharSheet.css
- Official Savage Worlds/SavageWorldsCharSheet.html
- Official Savage Worlds/translation.json
Bug Fix and minor enhancement.
Bug Fixes:
Vigor re-roll now re-rolls Vigor (instead of Agility)
Unskilled, Athletics, and Shooting buttons are now styled properly in statblock view
Patch for Weapons affected by the Trademark Weapon update.
Enhancement:
Conviction rolls when Conviction is checked.
> Official Savage Worlds v1.00.06 Update

- Império De Jade/ImperioDeJade.html
Reverts Roll20/roll20-character-sheets#7613
The previous modifications totally broke the character sheet.
About the Critical:
"1d20cs>(@{critrangearma} - 1)" will aways return 1, without rolling dice. Besides, the old macro was totally right. Even if this modification was not breaking the rolls, it would be breaking the game rules, basically increasing the critical range of the weapon by 1.
About the attributes that were removed from the attack rolls, they were there for a reason. The logic is messy, but they allow you to change the main attribute from your attack.
(I appologise by my grammar, i had a busy day and I'm quite tired. Thanks for you attention).
> Revert "Fix to Character sheet ImperioDeJade.html"

- Ironsworn/Ironsworn.html
- Ironsworn/src/data/move-list.pug
- Ironsworn/src/roll-templates/oracles/raw-oracles.pug
- A couple page references were missing for moves. These have now been added
- The Ask the Oracle logic had been implemented incorrectly for matching rolls, it was meant to match based on the dice rolled (technically it rolls 2d10 and matches the 2 numbers displayed). Now it will show the match for 11, 22, 33, 44, 55, 66, 77, 88, 99, and 100.
> [Ironsworn][Fix] Added missing page numbers and corrected Ask the Oracle logic.

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Fixes a bug in Bluff and Deception where the correct modifier is not pulled.
> PokemonTabletopAdventures_v3 - Bluff and Deception use SPDMODEF

- Vulcania/vulcsheet.css
Fixed height bug on Firefox. I think browsers have a different way to count pixels (like Firefox and Chrome), so i use 100% instead of pixels and now all works fine.
> [Vulcania] fixed height bug using Firefox

- Basic_Roleplaying/Basic_Roleplaying.css
- Basic_Roleplaying/Basic_Roleplaying.html
Added a width to the CCS to prevent the sheets from stretching or deforming when resizing the window.
Replaced the Attks entry on the Hand-to-Hand weapons with a Damage Bonus drop down menu (since melee weapons universally have 1 attack)
Increased the width on the repeating Hit Locations entry to match the rest of the sheet.
- [ X ] Does this add functional enhancements (new features or extending existing features) ?
- [ X ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
> Small changes and fixes for Basic_Roleplaying

- Warhammer_v2_french/Warhammer_v2_french.html
Removed missing pictures in templates which were replaced by a huge and ugly placeholder.
Deleted it alltogether in the 2 templates (test & combat)
The pictures displayed in the roll template used throughout the sheet is no longer accessible, I juste removed the <tr></tr> containing them in the 2 templates.
Here is the former picture link wich is no longer valide :
https://lh3.googleusercontent.com/-ptR_NzBo340/VYslrf-t9NI/AAAAAAAAV4Q/rV7U24IJdAc/w745-h10-no/co_hr.png
> Warhammer_v2_french : Removed missing pictures in templates

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Changes the header of the talent checkboxes to Talent to make it easier for users to identify their purpose
- Sets the value of each checkbox to 2 to eliminate the need to select talent in a particular order
- Updates the skill total sheet workers to add the extra +1 if both checkboxes are on
- Updates the skill total sheet workers to encapsulate some repeated code into a function to make the scripts section neater
- Updates sheet workers to react to attribute mods, which ensures attribute changes have time to propagate to the mod before being used
- Updates the README
> [Pokemon Tabletop Adventures v3] Refactors skill talents

- Basic_Roleplaying/Basic_Roleplaying.css
- Basic_Roleplaying/Basic_Roleplaying.html
Adjusted the width of the sheet since it was a little too small for a few of the buttons.
Changed the modifier and multiplier pop-up windows to global inputs on the sheet.
-Alphabetic Skills
-Category Skills
-Hand-to-Hand Weapons
-Ranged Weapons
-Shield
-Powers
Fixed an issue with the layout of the Repair Skill on the Alphabetic skills section
Fixed an issue in the Categorical Skills where they aren’t rounding up from a decimal point.
Fixed Issue with Powers Section that registers Fumbles inappropriately
Turned Martial Arts into repeating skill to allow for more than one specialization.
- …
> Big Update to Basic Roleplaying

- TheWitcher/witchersheet.html
Fixing an input bug for the 'Weapon Type' area found within each weapon. It lacked a 'type' which means any value isn't being saved as an attribute and had an unneeded closing tag.
> TheWitcher - Weapon Type Bug Fix!

- Anima-Beyond-Fantasy/A-BF.html
Add turn tracker to init roll.
The open rolls are not handled. If anyone has an idea how to do that, I'm interested.
- Does the pull request title have the sheet name(s)? Yes
- Is this a bug fix? No
- Does this add functional enhancements (new features or extending existing features) ? Yes
- Does this add or change functional aesthetics (such as layout or color scheme) ? No
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ? No change is made to player data.
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ? This is not a new sheet.
Comments are very helpful for reviewing the code changes. Please answer the relevant questions …
> [Anima-Beyond-Fantasy] Sheet A-BF : add turn tracker to init roll

- GURPS/gurps.html
Remove Target Token macro from melee attack rolls. This was supposed to be for a future feature to add optional targeting.
> [Gurps 2.5.3.1] important

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- feature: Added a pokemon capture skill
- Adds a new skill to the end of the skill list - placement intentionally breaking alphabetical order for fast location, and because the format doesn't match the rest of the table
- feature: Added generic stat checks
- Changes the readonly input field for stat modifiers to be buttons with attribute-backed span titles to allow for making them rollable
- Added dice rolls for generic stat checks to the new dice modifier buttons
- This means Pokémon character sheets don't have checks for DEF and SPDEF, as those mods aren't used for Pokémon; this may change in the future
- chore: Ran code through linter
- Installed the Prettifier linter to ensure the code is presented in a "standard" format
- Helps to catch any errors missed _(such as missing …
> [Pokemon Tabletop Adventures V3] More Trainer Rolls

- Basic_Roleplaying/Basic_Roleplaying.html
•	Fixed the spacing on the Repeating Hand Weapons section
•	Added a roll template for Characteristic Rolls
•	Added a roll template for Sanity Checks
•	Added Resistance Table Function with a roll template
•	Decreased the Font Size of the Charisma Check so that it fits into the button
- [ X ] Does this add functional enhancements (new features or extending existing features) ?
> Small Update to Basic Roleplaying

- Shadowrun5th/Shadowrun5th.html
Adding will to the possible Drain Attributes
Adding Will power to the drain attributes for mages
This is a change to Shadowrun5th. Adding Will as one of the possible drain attributes. This fix patches https://github.com/Roll20/roll20-character-sheets/issues/7954
There are no appearance changes as part of this pull request.
> Shadowrun5th Will as Drain Attribute

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Added a new optional counter on the Caracteristics tab under the conditions
- has a label and a value (no max value)
- activation of the counter and its label are determined upon the setting chosen on the Configuration tab
- enables counting Madness (Cthulhu), Tension (Menace-X), Pulsion (Monstres), Soul/Rage/Blood (Demons/Werewolfs/Vampires superhumans), etc...
- Added a new Origine field under the Profil and Famille in the sheet header. The 'Profil', 'Famille' and 'Origine' labels are determined upon the chosen setting
- For the Monstres setting, Weakened is replaced by Badluck (worse of two d20) for all conditions using a d12 instead of d20.
- On a vehicle sheet, the physical traits section (sex, age, height, weight) is not displayed
Comments are very helpful for reviewing the code …
> ChroniquesOublieesContemporain v3.7

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Added a checkbox on the Abilities tab of the PC sheet to toggle between:
- Display mode, where the name and full description of the abilities is displayed as wrapped text
- Edit mode, where the player can enter the ability name and description (first line of text is assumed to be the ability name).
- Added fields to bind an ability roll with an ability in grid, by specifying the ability path number and rank in the path. This information is primarily used by the [COlib](https://github.com/stephaned68/COlib) API script.
- On the starship sheet :
- added support for energy points allocation, including a check with the maximum energy potential
- added checkboxes for crew stations occupation, in order to include or not the crew bonuses on the starship action rolls (including Init(iative) et …
> ChroniquesGalactiques v3.110

- PokemonTabletopAdventures_v3/PTA3.html
- Consolidates all attribute changes into a single getAttrs and setAttrs pair
- Adds a new migration for the Character Type selection that was previously missed
_Yes._
_Yes and also no._
_Yes._
_Not this time._ 
_New migration to use the `character-type` attribute rather than `tab`; change already made, this carries data over._
_Not a new sheet._
> [PokemonTabletopAdventures_v3] More performant version migration code

- Only-War-Enhanced/OnlyWarEnhanced.css
Firefox users were having issues rolling Skills because the buttons were behind disabled inputs (used to display custom text) which ultimately consumed the mouse click.
To fix this, use CSS to prevent the click from being consumed by the disabled input and instead have it fall through to the parent button.
Fix taken from here: https://stackoverflow.com/a/32925830
Disclaimer: I am not a Pro user so haven't properly tested it outside of the Firefox debugger. I'm also not the best person to judge whether this provides the opportunity to clean up some of the Firefox compatibility code from the Only War (Enhanced) sheet.
If you do not know English. Please leave a comment in …
> [Only War (Enhanced)] Fix Firefox Skill rolls without compatibility mode

- Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.html
i added this  `<option value="skill(@{rankDiscipline}|@{willpower})" data-i18n="discipline">Discipline</option>`
to line 1732
so that Discipline can be used for the Unleash power on attacks
- [yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [no just something that was missing] Is this a bug fix?
- [yes] Does this add functional enhancements (new features or extending existing features) ?
- [no] Does this add or change functional aesthetics (such as layout or color scheme) ?
> Added Discipline to weapon skill options dropdown for Star Wars FFG API-Compatible

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- feature: Streamlines combat moves
- Makes the pokemon-move repeating section fields collapsible to hide the clutter of the roll customisation options
- Adds an inline roll command for the move to make using it easier
- feature: Adds quick roll options to moves
- Adds an extra inline move roller to the top segment of both move display types to allow for quickly rolling a move without configuring it with effectiveness and temporary modifiers
- feature: Added support for scatter-type moves
- Adds a move configuration option for Scatter typing
- Adds new roll templates that support the additional attacks that scatter moves come with
- feature: Adds tooltip information to the inline roller buttons
- Updates README with relevant changes from this branch
<details>
<summary>Screenshot of final …
> [Pokemon Tabletop Adventures_v3] Upgrades the Move Repeating Section

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Adds a new option to the configuration page which allows swapping the associated ability for each skill - _and the capture pokémon meta-skill_
- Updates CSS to allow for attribute-based colouring of each skill field
- Updates sheet workers to allow for double-dipping into getting attributes, and slightly refactors them to be more generic! Woo!
> [Pokemon Tabletop Adventures_v3] Changing Skill Ability Modifiers

- OperaRPG/operarpg.css
- OperaRPG/operarpg.html
- OperaRPG/translation.json
- Splitting weapons in two types;
- moving fields around;
- Changing the roll template layout
> [Opera RPG] Changes on layout of some fields and of the Roll Template

- Heroes-Unlimited-2E/hu2.css
- Heroes-Unlimited-2E/hu2.html
Added entry fields for tracking chi on the main character tab.
Moved the skill level entry field from the toggled hidden row of each skill to the visible row to make it easier to advance skill levels at character level up.
Fixed a missing class designation on a hand to hand combat skill input field that caused it to have a different background color than other inputs on the sheet.
Updated the documentation and release notes tab.
> Heroes unlimited 2 e

- Palladium Fantasy 2E Sheet/palladium_fantasy_2E.css
- Palladium Fantasy 2E Sheet/palladium_fantasy_2E.html
Moved the skill level entry field from the hidden toggle row to the visible row in each of the 3 repeating skill sections on the skill tab to make it easier to access during character level up.
Updated the documentation and release notes tab.
> Palladium fantasy 2 e

- Wildsea/wildsea.html
- Changed the salvage name input type from "test" to "text" to fix the data disappearing on unfocus
> [Wildsea] Fix a typo that broke the salvage section of inventory

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Armor Tab rework: Separated AP from Armor Damage points and added field to add Durable value to increase Damage Points only without increasing AP. Also added a Robust talent lvl selector which modifies the right hand body location total AP displays.
> [Warhammer 4e Character Sheet] Armor update

- CyberpunkRED_raycw/cyberpunkred-raycw.html
The weapon mods used to autocalculate hits were missing the Assault Rifle value. I fixed this by adding it.
To my knowledge, this shouldn't influence existing player data.
> CyberpunkRED_raycw: Added Assault Rifle weapon mod that was missing.

- Warhammer Fantasy Roleplay 4e Official/src/js/sheetworkers.js
Fix for issue with encumbrance. According to rules if item is worn it's encumbrance should be reduced by 1, however it cannot be less than 0 (this doesn't make any sense).
Link to bug report at forum https://app.roll20.net/forum/permalink/9663326/
> [Warhammer Fantasy Roleplay 4e Official] Prevent negative encumbrance

- Warhammer Fantasy Roleplay 4e Official/src/pug/components/repeating/spell-row.pug
Do not use localized strings for spell type value since it breaks visibility of some related fields.
Closes: #7747
> [Warhammer Fantasy Roleplay 4e Official] Do not use localized strings as value for spell type

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- ensures single-hit roll template doesn't show the damage row when total damage is less than or equal to 0
- ensures dual- and multi-hit roll templates - used for scatter moves - always show damage to ensure the roll template table isn't left incomplete
- adds fix to readme, and corrects dates therein
> [PokemonTabletopAdventures_v3] Resolves issues with Roll Templates

- Only-War-Enhanced/OnlyWarEnhanced.html
reverting an earlier change that disallowed "text" in the Weight section. turns out decimal points are "text"
> revert weight from number to text

- Chronicles of Darkness/CofD.css
- Chronicles of Darkness/CofD.html
- Chronicles of Darkness/README.md
- Chronicles of Darkness/translation.json
Add a new section for the alternate beats/experiences used in some 2nd Edition game lines:
* Mage: Arcane
* Promethean: Vitriol
* Hunter: Practical
* Geist: Synergy
* Demon: Cover
(Also rearrange the display of Beats and Experience)
Minor: Remove Vampire 2nd Edition health modifier from Resilience; deprecated when Disciplines were moved to repeating section.
> [Chronicles of Darkness] Alternate Beats/Experiences

- Log Horizon TRPG/LHsheet.html
Small fix for the position of the fatigue text on the character sheet. It was incorrectly placed outside its box. This puts it in the correct position.
> [Log Horizon TRPG] Minor fix for text position

- Cyberpunk Red Tabbed/cyberpunk-red-tabbed.html
Updates to the Cyberpunk Red Tabbed character sheet: 
* Add Precision Attack from the Solo Role to attack rolls automatically.
* Fix the Evasion button in the Combat section to be based on DEX not REF.
There are no changes to page aesthetics, styles, or data storage. These changes only affect triggers for dice rolls in a few places to include adjusted modifiers.
> Cyberpunk Red Tabbed: Updates and fixes

- PARANOIA 25th Anniversary Edition/README.md
- PARANOIA 25th Anniversary Edition/translation.json
I just noticed that due to a bug, the i18nOutput console command didn't extract the "fallback_for" translation entry, messing up my previous release of the PARANOIA 25th Anniversary Edition character sheet. This has been fixed and documented. Note that I'm reporting the i18nOutput bug separately through normal support channels.
On an unrelated note, my Roll20 profile has yet to be credited as a sheet author despite identifying my user ID in `sheet.json`. Please verify.
- Does the pull request title have the sheet name(s)? Yes.
- Is this a bug fix? Yes.
- Does this add functional enhancements (new features or extending existing features) ? No.
- Does this add or change functional aesthetics (such as layout or color scheme) ? No.
- If changing or removing attributes, what steps have you …
> [PARANOIA 25th Anniversary Edition] Added missing "fallback_for" translation entry

- Serenity/serenity.css
- Serenity/serenity.html
- Serenity/sheet.json
* Rearranges asset & complication descriptions to put text after title
* Adds divider between assets and between complications
* Make sheet start full width
* Opt-out of legacy sanitization to allow details/summary elements to work (when deployed)
* This sheet doesn't depend on automatic changes like "sheet-" prepending 
> Serenity: Rearrange asset/comp description, put divider between, opt-out of legacy sanitization

- PokemonTabletopAdventures_v3/PTA3.html
- Ensures `sheet-` is prepended to every class name in the HTML file, in preparation for the sanitisation changes currently on the dev server.
- Ensures that when the Roll20 changes go live, the CSS continues to style the sheet properly
- Makes some of the elements that were previously split into many lines less cumbersome to read
> [PokemonTabletopAdventures_v3] HTML Class Name Sanitisation

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- Adds an option for character/pokémon type that is intended to represent the many type-less artefacts in-game
- Updates the default type selection for new characters to be typeless
> [PokemonTabletopAdventures_v3] A new Type Option

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Updates Changelog with the previous addition
- Corrects the move field open/close button display value based on the field state
> [PokemonTabletopAdventures_v3] Minor Sheet Worker Bugfix

- MERP/merp_2nd_ed_sheet.css
- MERP/merp_2nd_ed_sheet.html
**New Features**
- Added all playable races
- Added stat autocalcs for races
- Added defense autocalcs for races
- Added development point fields for leveling
- Autoselect realm based on profession
- Body Development now is calculatable!
- Added a section for background options
- Added a language dropdown
- Added adolescent ranks to all appropriate sections
**Enhancements/Bug Fixes**
- Fixed Language Headers
- Fixed Spell School Capitalization
- Fixed Appearance (AP) Calculation
- Added some tooltips
- Improved some field alignments
- Condensed stat section
- Fixed NPC strength bug
- Fixed power point calculation bug
**Breaking Changes**
- No variable names were changed so existing sheets should still work.  
- Race stat bonuses were overridden to be auto-calculated and protected, so any …
> MERP: Add Races and Autocalcs

- Mongoose_Traveller2e/MongooseTraveller.html
Rather than have each skill default to Strength when it is added, it will default to a more likely characteristic
(such as DEX or INT).  Characteristics can still be changed, it only changes what they initially default to.
Added selected option to tags in drop down menus.
- [ N ] Is this a bug fix?
- [ N ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ N ] …
> Mongoose_Traveller2e sheet update, to add default skill characteristics

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- refactors the capture pokemon skill section to allow for more information and more extensive modifiers
- adds two new options to the configuration page to further modify the capture pokemon skill
> [PokemonTabletopAdventures_v3] Adds capture roll modifiers

- Call_of_Cthulhu_7th_Ed/coc_7th_ed.html
The Drive Auto skill would produce the `name` text "Drive Auto Roll Roll" in the chat window output templates.  This was caused by the explicit inclusion of the text "Roll" in the HTML in addition to the translation data.  This change removes the extra "Roll" from the HTML and the output.
roll20userid: 16813
> [Call_of_Cthulhu_7th_Ed] De-dupe "Roll" text in Drive Auto skill use output

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Changed spellbook Channel button label from "Cast" to "Channel". 
- Language Magick is now always shown
> [Warhammer 4e Character Sheet] Channel label change

- ShadowrunAnarchy/ShadowrunAnarchy.css
- Sheet: ShadowrunAnarchy
- It is a bug fix
- It doe not add functional enhancements or anything, only fix a margin issue in the french version of the sheet
I removed the margin-top: -2em that was hiding the Karma boxes labels, like this:
With this fix, the boxes look like this:
> ShadowrunAnarchy: Fix French Karma boxes

- Awakening_RPG/awakening.html
There was a duplicate in character list - two different attributes have same name in input field. This updated aimed to remove this duplication in order to have two separate fields: attr_ac and attr_tal.
You can find rule book on the DriveThru: https://www.drivethrurpg.com/product/318336/
> [Awakening_RPG]fixed attribute name to exclude duplicates

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- fix: Small CSS fix for the ball modifier section
- improves appearance at the standard width of character sheets
- ensures transparency is correctly set for text background colours
- feature: Collapsing origin feature
- Added the capability to collapse the Origin Feature to save scroll time
- Added the capability to send the Origin Feature to the chat log in a neat and colour-coded format
- feature: Makes class features collapsible
- Updates text area and number input backgrounds to use the type-variable text background colour
- Updates number inputs to use bold font-weight for consistency across the character sheet
- Adds collapsing to class features
- Corrects the assignment of relative position for the origin feature div
- chore: Adding more to-do entries
- Adds missing sheet-worker …
> [PokemonTabletopAdventures_v3] Allows Collapsing of Origin and Class Features

- AD&D 2E Revised/2ESheet.html
- AD&D 2E Revised/2EStyle.css
- AD&D 2E Revised/javascript/version.js
- AD&D 2E Revised/javascript/wizardSpells.js
- AD&D 2E Revised/raw/2ESheet-raw.html
- Added toggle for Public / GM only thac0 and attack
- Fixed newline in Choke wizard spell
- Fixed backslashes in level three wizard spells
- Updated changelog
- Bumped version
Changes can be seen here: https://app.roll20.net/forum/permalink/9844117/
> [AD&D 2E] - GM_Monster-sheet_update

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
_PC Sheet_
- Added magic attack as a choice to the repeating list of weapons/attack
- Corrected layout of hit points and recovery points : remaining / maximum (were erronneously inverted)
- Removed the logic that was reworking the abilities texts and suppression extras carriage returns
_Starship Sheet_
- Corrected the calculation of the starship DEFences 
- Added a sheetworker for the calculation of the DEFence attributes so they can be bound to a starship token
> ChroniquesGalactiques Version 3.112

- Deadlands Classic/deadlandsclassic.html
Added two common rolls (initiative and perception) to the Core tab.
Updated a few of the skills with concentrations to have their concentrations be separate classes rather than all linked with the same name (language) so they can be added/deleted separately.
Fixed roll name for survival (was performin).
Changed placeholder in Fightin to use (') rather than (`) like the rest of the sheet.
Replaced second instance of TN in arcane abilities with Hand.
> Update Deadlands Classic (html)

- StarWars5E/StarWars5E_HTML.html
Removed the attempt to calculate the weight for the ships cargo inventory, it does solve the error and allow the encumbered message to display, but now a ship will not be warned when it is over capacity
Though, the calculation for a ship being overcapacity is wrong, as it before used the same method as the pc sheet when it should rely on fixed values dependant on it's size
https://sw5e.com/rules/sotg/equipment#cargo-capacity
The ship sheet also doesn't have the text display fields for the encumbered message, so it shouldn't matter anyway
Fixes #8413
> [StarWars5e] Fix to encumbered not displaying on StarWars5e

- Serenity/serenity.css
- Serenity/serenity.html
* Prevent printing from putting page breaks inside float groups
* Maintain needed backgrounds while printing
* Add advancement point attribute
* Fix line-spacing bug in some browsers
- New Attribute, player data not impacted
> Serenity: Page breaks, print backgrounds, advancement points

- T2K 4e/twilight-2k-4e.css
- T2K 4e/twilight-2k-4e.html
- Added 3rd weapons slot for Vehicles
- Added attributes and skills listed above dice roller for quick reference
- Yes: Twilight 2000 4th Edition
- This is not a bug fix
- Yes, adds additional weapons slot to vehicle and displays some quick reference information about dice rolls in the Combat Section
- Yes, adds additional weapons slot to vehicle and displays some quick reference information about dice rolls in the Combat Section
- Not Applicable
- Not Applicable
> Twilight 2000 4th Edition | Additional vehicle weapons

- Serenity/serenity.css
- Serenity/serenity.html
* Fix gradients
* Tooltips for plot/adv points point left
* Right align adv points
* Remove media query for print
* Make float groups have white background
> Serenity: Fix gradients, move new tooltips to left, move adv points right

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/translation.json
Fixed ship name/class/TL saving on ship sheet
Modified Inventory to have a carried checkbox to only count weight of carried items.
Modified weights in inventory and combat sheet to be sub-kilo.
> [Mongoose_Traveller2e] Add fractional weights, fix ship name

- T2K 4e/sheet.json
- T2K 4e/twilight-2k-4e.html
Necessary fix to Medical Aid resolving a typo on the attribute.
- This fixes an issue with a typo in the Medical Aid attribute so that the roller works as expected
- This does not add new or enhanced features
- This change does not
- Will not preserve data as the previous medical aid attribute had a typo in it
- This is not a new sheet
> Twilight 2000 4th Edition | Fix medical aid roll bug

- Call_of_Cthulhu_Spanish/Call_of_Cthulhu.html
- Call_of_Cthulhu_Spanish/translation.json
- Call_of_Cthulhu_Spanish/translations/en.json
- Call_of_Cthulhu_Spanish/translations/es.json
I changed the Call_of_Cthulhu_Spanish sheet. Added i18n to the firearms area, the grapple attack and the Medicine roll.
The 5th edition sheet in my campaign seems to use the internationalised Spanish version (English being the language we use). However, some of the text wasn't translated into English (see image below).
I put existing i18n attributes into the firearms roll template. I added some JavaScript attributes to insert i18n text into the grapple attack and the Medicine roll template.
> [Call of Cthulhu 5e/Spanish] corrected some i18n

- Ironsworn/Ironsworn.html
- Ironsworn/src/components/assets/asset-custom.pug
- Ironsworn/src/components/resources/resources.pug
Fixes https://github.com/Roll20/roll20-character-sheets/issues/8452
Missed setting one of the input fields to Dynamic for the custom assets:
```
input(class=`builder-ability-${value}-text-input hide` type='checkbox' name='attr_builder-ability-1-text-input')
```
The resources translation was replacing the contained button. Added a separate div within the label to fix this.
> [Ironsworn] Resource and Custom Asset Fix

- Mythras/src/scripts/import.js
Simple bug fix.
Survival skill should be calculated based on Pow and Con, not Pow and Cha.
Fixes #8473.
> [Mythras] Bux-fixed import.js Survival skill.

- Ironsworn/src/components/assets/assets.styl
CSS fix for alignment of checkboxes beside custom asset abilities, and add a grey highlight behind the builder/view radio buttons to distinguish them from the asset title.
> [Ironsworn] Modify Custom Asset CSS

- GURPS/gurps.html
Fix GCA import issue for multiple attack modes
- GCA Import Bug Fix. With the help of Gata, The Fabulous Iron Chef, and a discord user I was able to find a bug related to multiple attack modes.
> [GURPS] 2.6.6

- Pathfinder_Cazra/sheet.html
the "&{tracker}" code was missing on the "Initiative" button ; this code will add the selected token to the "Turn Order" table.
> [Pathfinder_Cazra] add tracker for Turn Order on "initiative" button

- The Expanse RPG (AGE System)/sheet.json
- The Expanse RPG (AGE System)/the-expanse-rpg-age-system.css
- The Expanse RPG (AGE System)/the-expanse-rpg-age-system.html
- The Expanse RPG (AGE System)/translation.json
Update for The Expanse RPG sheet
Bug Fixes:
• DEX/Toughness increase now possible with ever 4 character levels, using new widgets.
• Fixed Level for specialisation  2, was a duplicate of specialisation 1 level parameter attribute
• Added Dex penalty dropdown option for armour (backported from AGE System All in One Sheet)
Extra Functionality:
◇ Custom dice roller backported from AGE sheet so that TotalrollAGE API no longer required to show stunts points
Attributes added but not removed.
Layout changed slightly on main screen for the extra two widgets labelled 'Tough Lvl bonus' and 'Defence Lvl Bonus'
Layout changed slightly on 'Cog' screen for 'Apply Armor Penalty to Dexterity rolls' dropdown
Comments are very helpful for reviewing the code changes. Please answer the relevant questions …
> The Expanse RPG (AGE System) - Dex/Tough and Other Bug fixes Feb/Mar 2021

- Monsterhearts-2/Monsterhearts-2.html
It's doing that thing again where it's showing all the sheets at once no matter which one is selected.
I can't remember how I fixed it before so fingers crossed I figured it out -- _but also_ if this is correct I'mma pissed because it's so stupid and arbitrary.
Like just... I'm too tired for this.
> [Monsterhearts 2] fixed display problem

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- You can now set Afflictions in the character sheet, and they modify stats accordingly!
- Not everyone will use these, so they can be mostly hidden with just a click
- Automatic initiative macro - if you have a token associated with a character sheet, you get a free token action
- Add bonus movement field
- Rename Attack Damage Bonus and Special Attack Damage Bonus for clarity
- Fix typo in config page
- Remove leftover debug logging
> PokemonTabletopAdventures_v3 - Autoinitiative, status boxes, and more

- Ironsworn/Ironsworn.css
- Ironsworn/Ironsworn.html
- Ironsworn/src/components/bonds/track.pug
- Ironsworn/src/components/misses/track.pug
- Ironsworn/src/components/progress/mixins/box.pug
- Ironsworn/src/components/progress/progress.pug
- Ironsworn/src/components/progress/progress.styl
- Ironsworn/src/components/sites/sites.pug
- Ironsworn/src/components/vows/vow-container.pug
- Ironsworn/translation.json
Changes the progress track boxes to use gradient based backgrounds to display 'tick' marks instead of just the characters - + * #
Changes progress bars in: Failure track, Legacy Vows, Repeating Vows, Progress Tracks, Bonds Track, Sites Track
Does not add any new attributes or remove any attributes.
> Ironsworn: Show images for progress boxes

- Basic_Roleplaying/Basic_Roleplaying.html
•	Fixed Right Leg on Hit Locations, it was not supposed to be a blank entry
•	Fixed Repeating Hit Location Section Box by shrinking it down a little.
•	Reversed the position of the Current and Max HP on Hit Locations section.
•	Added a “/” between the Cur. HP and Max HP on Hit Location sections
•	Added a Sheet Worker to automate Skill Category Bonuses
•	Added default values of “10” to all of the characteristics
•	Fix the Problem where an attack lands on the skill rating, it counts it as a success but does not display the weapon damage.
- [ X ] Does this add …
> Automation and Minor Changes to Basic Roleplaying System

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Added a title field for each ability (attributes @{voieN-tR} where N = skill path number and R = rank)
- Sheet worker to migrate from older versions : first row in the ability textual description is assumed to be the title
- Support for the new attribute in all related functions (binding an ability roll to a skill+rank, JSON profile data import)
- Corrected a bug occuring after removing the one and only attack or damage modifier from the repeating section (the removed modifier is not taken into account anymore in the attack rolls). Issue #7836 resolved
> ChroniquesOublieesContemporain Version 3.9.0

- Shadowrun Sixth World/Shadowrun6thEdition.html
In a patch on Tuesday unannounced to the community the code that automatically prefixed classes in roll templates with sheet- was removed.   This has caused several character sheets to stop working for roll buttons that use roll-templates.  This fixes the issue for the Shadowrun Sixth World sheet.
To be clear this makes the sheet un-useable for any rolls until this fix is in or roll20 reverts to adding sheet- to roll-template classes automatically.
This fixes this issue: https://github.com/Roll20/roll20-character-sheets/issues/8616#issue-847049214
- [ N ] Does …
> Shadowrun Sixth World EMERGENCY FIX for roll20 roll template change

- Agone-(french)/agone-sheet.css
- Agone-(french)/agone-sheet.html
- Agone-(french)/sheet.json
- Add animation on textarea focus
- Several issues fixed (missing stuff, wrong css, old stuff...)
- Godfather becomes Seasonling Sponsor (attribute converted automatically)
- Aiglet becomes Eaglet (attribute converted automatically)
- Animations on dices
- Useless but pretty animated fireflies on the logo
- Translation capability added
> Agone-(french) - New version v0.7

- Metal Adventures/MetalAdventures.html
In character sheet, there are 6 checkboxes, that can be checked and unchecked.
However, once the checkbox is checked, the data is memorized and will always be checked when the character sheet is reopened. 
If check by mistake, the only way to fix is to DELETE the character sheet an recreate a new one
I guess, the default value (uncheck) should be null
When we check, the value become "0" (from the code) 
And when we uncheck, it's still a falsy value like the check value... so nothing to save about that sheet.
* Go to "Attributes Abilities" tab
1)
* Remove the value "${carac}_predilection"
* Close and open again the character sheet
2) OR
* Update value "${carac}_predilection" for anything else "0"
All previous character sheets for Metal Adventure, will have these checkboxes uncheck
They are …
> [Metal Adventure] Fix checkboxes (with valid merge)

- Metal Adventures/MetalAdventures.html
In character sheet, there are automatic input updated by Carac+Skill, however the strategy skill was forgotten. The calculation between Caract+Skill still always blank.
Do the calculation yourself, and update it from the "Attributes Abilities" tabs each time
Add a max value for the attribute that was missing
This PR is **RETROCOMPATIBLE**
> [Metal Adventure] Fix update max strategy

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.css
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
This is basically a retrofit of the changes/enhancements made to ChroniquesOublieesContemporain Version 3.9, namely : 
- Added a title field for each ability (attributes @{voieN-tR} where N = skill path number and R = rank)
- Sheet worker to migrate from older versions : first row in the ability textual description is assumed to be the title
- Support for the new attribute in all related functions (binding an ability roll to a skill+rank)
- Corrected a bug occuring after removing the one and only attack or damage modifier from the repeating section (the removed modifier is not taken into account anymore in the attack rolls).
If you do not know English. Please leave a …
> ChroniquesGalactiques Version 3.114

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
This contains a fix for an annoying issue commit d895e6b3cbab509114418df2ee7503d5da6becee caused. Two attributes were still stored in auto-calculating fields, but I thought they had long phased out of use. I was wrong and I did not test this. Shame on me, but at least here's the fix. Please apply and push to production asap.
* **Fixes**
* Restore auto-calculating fields for attributes 'TP_W_Aktiv' and 'TP_Bonus_Aktiv'
> [Das_Schwarze_Auge_4-1] Hotfix: Auto-calculating fields restored

- Ironsworn/Ironsworn.html
- Ironsworn/src/app/workers/scripts/progress.js
Added a fix for repeating vow mark progress. This was broken when using the `progressStrings` const.
Also added a small fix for grave accents in the base template.
> [Ironsworn] [Fix] Vow Mark Progress

- Shadows of Esteren/ShadowsOfEsteren.html
The base speed is calculated incorrectly on the Shadows of Esteren Character sheet.
Rule book page 215 states: 
```
To know the initial Speed rating of a Character,
make the following addition: Way of
Combativeness + Way of Empathy
```
This looks like it might be a simple copy/paste issue where line 411 was copied here and Combativeness was changed, but the +5 was left in. There should be no +5 to Speed base. 
- [N] Does this add or change functional aesthetics (such as layout …
> [Shadows of Esteren] Fix Base Speed Calculation

- SLA Industries 2ed/sla.html
Fixes on unarmed weapon damages, so they do not get the strength damage bonus, but are correctly calculated from the correct base - STR+2, STR-1 etc...
- fixed default skill for Chuckleduster to be Unarmed
- fixed polearm skill so it appears when a polearm weapon is selected
- altered damage bonuses so unarmed weapons do not get strength damage bonus to weapon damage and min damage
- Altered the calculation of natural weapons so they are correctly calculated from Strength - Str-1, Str+2 etc... 
- [No] Does this add functional enhancements (new features or …
> [SLA Industries 2ed] Fixes Unarmed Weapons

- Hack The Planet/Hack the Planet.css
- Hack The Planet/Hack the Planet.html
Make selected checkboxes more legible.
The very light pink that was used for selected checkboxes before was
very difficult to discern from the white used for empty boxes.
Instead employ either a darker red, or black with a white border,
depending on what looks best in a given use case.
> [Hack The Planet] Improve legibility of checkboxes and the like

- Shadows of Esteren/ShadowsOfEsteren.html
The disciplines under Prayer were using Empathy when they should be using Conviction.
Rule book page 198 lists Prayer as using Conviction.
- [N/A] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Characte …
> [Shadow of Esteren] Fix Prayer Disciplines

- Only-War-Enhanced/OnlyWarEnhanced.html
- Only-War-Enhanced/sheet.json
Added a space to {{loc=}}, to create {{loc= }}, which I have no idea if it'll work but it won't break anything to try
separated {{@{settings_hitroll}} to have a space before and after, for readability
adjusted whitespacing for hitroller
Renamed "Initative Overrides" to "Initiative Tiebreakers"
> [Only War Enhanced] hitroller bug fix

- Monster of the Week Official/MotWHTML.html
A couple small quality of life improvements.
The History & Notes field is now triple in height, so folks will both notice and use it, and also be able to see more of what they put in.
A few of the advances now display a text field when you pick those advances so you can write down what specific choice you made after taking that advance.
No impacts on player data expected.
**PLEASE ALSO NOTE:** On live production Roll20, the Monster of the Week By Evil Hat sheet does not (at the time of this writing) correctly display some of the moves, despite the code and translation.json source file being correct for months now. As you might expect, I can't do anything about problems that don't actually exist in the code, so those problems are Roll20's to fix. Some sort of total refresh of the …
> [Monster of the Week Official] Updates for week of May 10 2021

- PokemonTabletopAdventures_v3/PTA3.html
The Pokelicious sheets have the word Special, not Special Attack. Allow this.
> PokemonTabletopAdventure_v3 - Allow using the word 'Special' in JSON import instead

- .gitignore
When using Github Desktop to manage the git repo on macOS, a .DS_Store file gets created in the root directory.
Adds `.DS_Store` to the .gitignore file to fix the issue.
> Update .gitignore to remove .DS_Store files from root

- Splittermond/Sheet.css
- Splittermond/Sheet.html
- Adding input fields for spell damage
- Adding sheetworker for filling spell damage fields
- Changing rolltemplate to allow players to enable and disable damage rolls
> [Splittermond] Spell damage and tooltips

- Fate/FateOmni.html
- Fate/sheet.json
- Fate/translation.json
- Made changes/additions to the sheet to support JSON object export of sheet data and import of same, with an eye on supporting compendium features down the line. Should not cause a change to any existing character data.
- Optional labels for combinable skills columns added.
- Altered rollable aspect formatting so the rating value of each aspect is constantly visible rather than conditionally.
- Settings support for preconfiguring column groupings for combinable skills
- Bugfix: Removed duplicate Stunts preference setting in sheet.json
> [Fate] Developer mode & compendium support

- Genefunk 2090/genefunk2090.css
- Genefunk 2090/genefunk2090.html
- Genefunk 2090/genefunk2090.js
- Genefunk 2090/genefunk2090.pug
- NPC damage rolls should no longer cause an `attribute not found` chat error.
- NPC hit dice averaging should now work again
- Statblock Importer for Genefunk2090 statblocks
> Genefunk 2090: Statblock Importer and Fix for NPC damage rolls and hit dice calc

- GURPS/gurps.html
Changes
- Bug fix in container "turning and velocity modifiers".
Values are incorrect when the current move has the step in parentheses.
When get the current move value, it generate a NaN in the conversion.
- Added the event On:change:turning_move_type to update the calculations of "turning and velocity modifiers".
- Updated function getBaseMove to ignore values in parentheses.
> [GURPS] Update

- Only-War-Enhanced/OnlyWarEnhanced.html
The accurate d10s were being tracked, but not where you could see
> [Only War Enhanced] Add accurate d10s to dmg roll

- RatasEnLasParedes/RatasEnLasParedes.html
With this changes I want to fix visual bug associated with the `<input type=number>` in PV, PC and PE atributs. The aforesaid bug consist of a too small width that hide the second number. This problem is caused to the `style="width: 10%;"`.
**Before commit:**
When we remove this HTML Style Attribute, the `<input type=number>` recover its default width (3.5em) from `charsheet.css` and we can see two-digit numbers.
**After commit:**
> [sheet: RatasEnLasParedes] Restore default width on inputs to PV, PC and PE atributes

- World Wide Wrestling 2nd Ed/wwwrpg.css
- World Wide Wrestling 2nd Ed/wwwrpg.html
This minor change styles the three page navigation buttons as tabs. These tabs adopt whatever color is set on the Settings tab.
> World Wide Wrestling RPG 2nd Ed - Nav buttons styled as tabs with player chosen color

- Basic_Roleplaying/Basic_Roleplaying.html
Added a "None" option for the Damage Bonus in Hand-to-Hand Weapons.
- [ X ] Does this add functional enhancements (new features or extending existing features) ?
> [Basic_Roleplaying]Added a "None" option for the Damage Bonus

- Crossed-Fates/CrossedFates.css
- Crossed-Fates/CrossedFates.html
- Crossed-Fates/source/app/components/acts/acts.pug
- Crossed-Fates/source/app/components/header/header.scss
- Crossed-Fates/source/app/pages/acts/acts.pug
- Crossed-Fates/source/app/pages/index.pug
- used `main` instead of `master` branch for asset URLs
- acts.pug files had backslash include statements that compiled on Windows, but not macOS
> [CROSSED / FATES] Change asset URLs from main to master

- CWOD-Vampire/Vampire.css
This is a very small fix for Chrome browsers.
`select` and `option` elements width was calculated differently in Firefox and Chrome due to an `auto` setting. Now it calculates correctly in both browsers.
> [CWOD-Vampire] FIX dice pools width

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Corrects the initiative tie-breaker config description, as the attribute is now used by the sheet
- Provides cleaner wording, and an example, for the skill modifier selection
- Allows hiding the accuracy field when building a customised move roll template
> [PokemonTabletopAdventures_v3] Updates config option descriptions

- Genefunk 2090/genefunk2090.html
- Genefunk 2090/genefunk2090.js
- Genefunk 2090/genefunk2090.pug
- Fix for imported statblocks not having their damage macros correct.
> Genefunk 2090: Fix for statblock importer not parsing damage correctly

- Only-War-Enhanced/OnlyWarEnhanced.html
Adds JS that checks for the Accurate prerequisites in Ranged Weapons and Vehicle Ranged Weapons, and appropriately adds +10 to hit.
Moved the Accurate damage DoS dialog to only appear when it's needed
Adds default values to attr_ammo (used for the ammo counter API), and vehicle weapons. [Thanks to ChtiKenny, now I know why default values are a thing.]
> [Only War Enhanced] Accurate +10 to hit as appropriate

- Only-War-Enhanced/OnlyWarEnhanced.html
Fixed bug: Normal Ranged Weapons not correcting for the Accurate +10
Fixed bug: Accurate checkboxes automatically turn on all other Accurate checkboxes in the list of weapons
Fixed bug: DMG button never asks for DoS even if everything checks out
> [Only war enhanced] Bugfix

- HarnMaster3/harnsheet.html
- HarnMaster3/harnstyle.css
A small bugfix where using two classes in the repeating weapons section prevented the roll buttons being drag&dropped to the macro bar properly.
> [HarnMaster3] Bugfix - Fix drag-and-drop to macro bar for repeating weapons roll

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.css
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - NPC->Grunt fixed a bug or oversight on grunt repeating skills.   They were all showing Agility on the roll template as their ability.  Upon first opening a grunt sheet all repeating skills for the grunt will be re-set to use their default associated attribute and the display attribute will also be fixed.
Bugfix - NPC->Host IC dice roll buttons weren't working.
Bugfix - PC->Rolls->Misc fixed width on conversions
- [ N ] Does this add functional enhancements (new features or extending existing features) ?
- [ N ] Does this add or change functional …
> Shadowrun sixth world v.38

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- PC crit roll now shows modifier in the roll template. NPC crit roll removed first modifier box pop up which did nothing.
> [Warhammer 4e Character Sheet] 1.51 fixes

- Valor/Valor Character Sheet.html
Sheet: **Valor**
- Bugfix: Added SP values for skills "Polearm Wielder" and "Ranged Weapon Wielder".
- Bugfix: Vitality Limit could be leveled up.
- Bugfix: Guts-based techs (e.g. healing core) wouldn't update when changing Guts value.
> Valor sheet accuracy fixes

- Forbidden_Lands/Forbidden_Lands.html
- Fixed the dice pool's roll button indicator when selecting Strength-based skill selections.
> Forbidden Lands v1.76

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Added a level field to the `hybrid` _(or Pokémon (Character Class))_ character type.
- Altered some CSS ever so slightly to ensure the new _"Level / Honors"_ label is displayed on one line for the default font size.
- Updates the README accordingly.
> [PokémonTabletopAdventures_v3]: Adds level tracker to hybrid characters

- Deathwatch/Deathwatch.html
Fame is not used in Deathwatch, instead it uses "Renown" that is synonymous but has clearly defined mechanics in the game.
Changed the name as well as the margin so it all still looks fit.
> Deathwatch.html - Fame field change

- Deathwatch/translation.json
Fame is not used for Deathwatch.
Renown is the corrent naming for the influence mechanic present in the books.
This change goes with the other one on the HTML to make the change complete.
No data is removed only renamed. With no need to roll on the attribute there should be no data loss.
> Deathwatch/translation.json - Fame Field Change

- Genesys-RPG/Genesys-CharacterSheet.css
Fixed typo in the URL for images. Should now display images from ship section for speed, hulltruma, and sysstrain correctly for issue #6187
> [Genesys-RPG] Update Genesys-CharacterSheet.css

- DnD_5e/DnD_5e.html
This Pull Request adds a new row, "Prepared", to the spell table on the Spellbook tab of the DnD_5e character sheet. Included are the HTML changes to add the row to the table, and javascript changes to calculate and set the attribute whenever a spells preparation status is changed.
The code only listens to changes on spell levels 1-9, since changes to cantrips do not impact the number of spells prepared.
The javascript code starts by checking which field on the spell was changed, and only continues if it was the "prepared" field.
The javascript code also runs when the sheet is first loaded, to ensure the spells_prepared_count attribute exists for all users and does not generate an error.
The fields in the Prepared row of the spell table are auto-calced.
This is informational only, and …
> [DnD_5e] Add Spells Prepared count to spell table in spellbook

- Weaverdice/CHANGELOG-Weaverdice.md
- Weaverdice/Weaverdice.css
- Weaverdice/Weaverdice.html
- updated wounds counter from text to drop down to reflect weaver dice types of damage and effects
- used emojis for interchangeable hearts for health, damaged health, armor, and damaged armor on wounds
- changed sheet version to SV for cleaner look
> [Weaverdice] Made changes to the wounds counter

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
To minimize dice roll errors, Roll buttons now call hidden variables that are equal to user-defined dice strings, but cleaned of all characters save for 0-9, d, D, +, and -.
The basic strength attack damage dice roll is now understandable as Xd6+Yd3+Z when hovered over.
Limited normal damage dice to type d3 and d6 for BODY calculations.
Added max length limits to all textarea and text fields to prevent excessive input problems.
Small cosmetic fix to talent section styling.
> [Hero System 6e Heroic] Changes to damage roll handling

- Basic_Roleplaying/Basic_Roleplaying.html
Fixed the Dodge Button in the bar underneath the Ranged Weapon section to include category bonuses in skills when skills by category is chosen.
- [ X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ X] Does this add functional enhancements (new features or extending existing features) ?
> [Basic Roleplaying] Fixed the Dodge Button

- Shadowrun3e/README.MD
- Shadowrun3e/shadowrun3e.css
- Shadowrun3e/shadowrun3e.html
- Shadowrun3e/sheet.json
- Fixed bug with Matrix rolls
- Fixed bug with Ranged and Explosive rolls for vehicles
- Added armor calculation with different slots for head, body, shield, gyro harness and cyber/bioware. 
- Armor calculation includes penalties for combat pool and quickness related tasks
- Added Dice Pool and Target number modifiers to Melee, Explosives and Ranged Weapons to allow for easier tracking of defaulting and specializing and edge modifiers.
- Changed logic for offhand weapons.  Removed "secondary" equip as the logic is now handled by the above change.
- Added "pool" selector to repeating skills.
- Added recoil penalty tracker
- Added pool tracker for Task Pool
- Added Karma Tab for keeping track of abilities/skills/spells purchased
- Added credsticks with rolls
- Added contacts
- Added …
> [Shadowrun3e] Srun3ematrix2

- Legacy - Life Among the Ruins/LegacyRoll20sheets.html
- Adding a tracker for the Historian character specific resource called Wisdom. 
- Also a minor spelling error is fixed on line 10167(pre-wisdom)/10169(post-wisdom).
It should but if it doesn't it is "Legacy - Life Among the Ruins/LegacyRoll20sheets.html"
Historian character specific resource tracking added
> [Legacy - Life Among the Ruins] Add Wisdom Tracker to Historian Sheet

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.css
- Shadowrun Sixth World/Shadowrun6thEdition.html
- Shadowrun Sixth World/translation.json
Added Social Rating to derived tests (even though it's not a test) just to the right of the Edge Attribute.  This is a total of Charisma + any cumulative + primary armor social adjustments.
Added mouseovers for Composure, Judge Intentions, Memory and Lift & Carry buttons detailing where the values come from for those of us that forget.
Added the ability to add Spells, NPC Spells, Qualities and Augmentations by pasting raw data into the Notes textarea for a new repeating row.
- [ N ] Is this a bug fix?
- [ NA ] If changing or …
> Shadowrun Sixth World v.40

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added a skill roll field to each power description, which shows in the power activation roll's text in chat.
Changed minimum END value to 0, which is needed for some automaton type characters.
Increased skill name character limit slightly.
Added "show" buttons to Talents and Complications that display description text in chat.
A little more improvement to organization and styling of powers.
Changed readonly input fields from type number to text, allowing more consistent styling between Chrome and Firefox.
> [Hero System 6e Heroic] Added 'show' buttons and improved powers.

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - Drone/Vehicle Initiative should have been normal Initiative but Pilot * 2 + 3d6.
Bugfix - Grunt template was applying wounds to Soak rolls.
Added IC to the list of pastable raw data
Host->IC now display notes in the roll template
- [ NA ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ NA ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets …
> Shadowrun Sixth World v.41

- HarnMaster3/harnsheet.html
- HarnMaster3/harnstyle.css
- Small changes and some fixes:
- Allow decimal value input for armour
- Fix bug in horse penalty calculation (encumbrance was ignored)
- Fixed horse dodge roll button not working
- Add SB field to spells to allow for optional rule Individual Spell skills (Shek-Pvar 24)
- Added more fields to spells to quickly see time, duration etc. Added auto-calculation for Skill Index (SI)
- layout changes to spells section to track additional info and create more space for spell description
- background script to copy back character name to old "name" field for backward compatibility
> [HarnMaster3] 202109 bugfixes

- Starfinder (simple)/Starfinder (simple).html
Updated Trick attack to include sniper alternate class ability.
Added in Sniper level damages to the list of drop downs for trick attack level.
> [Starfinder (Simple)] Added Operative Sniper to Trick attack

- Alien Roleplaying Game/Alien-Roleplaying-Game.html
Fixed the rolltemplate so that it again includes allprops section. 
Fixed Success counter to also include the stress dice hits. 
> [Alien Roleplaying Game] Fixed roll template: allprops and stress hits

- Runequest_6/Runequest_6.css
- Runequest_6/Runequest_6.html
Runequest_6.html
Bugfix
Removed extra closing brace on the first button to roll weapon damage, adding an "}" character on the Effects cell when the input is empty.
> Runequest 6 | Remove extra closing brace on the first combat weapon row

- Mutants and Masterminds 3E Official/mutants-and-masterminds3e.html
The attribute descriptor wasn't being passed on to attack macros in repeating sections outside of basic Powers.
> MnM 3E Official macro fixes

- Myriad Song/Myriad Song.html
Myriad Song.html
bug fix
Lines 460+461: legacy_roll and career_roll buttons were using <td> tags instead of <th>, breaking the formatting. Changed tags to <th> so proper CSS is used.
No added enhancements or features. Just fixes a minor layout bug on the sheet.
> Myriad Song | Fix table tags

- Shadowrun3e/README.MD
- Shadowrun3e/shadowrun3e.html
1. movment pentaly is now shown in RangedTN modifiers
2. fixed calculation of ammo weight
3. fixed end turn - no longer refreshes pools unless there are no more combat phases for the icon.
4. fixed matrix target number, legit vs. intruder were reversed.
5. killjoy resistance is now willpower - not body.
6. vehicle gunnery updated to account for movement penalty re-write for showing it in the rangedTN
> [Shadowrun3e] sprint11

- D&D_BECM/BDnDSheet.html
changes to BDnDsheet
Changed the names of the basic armors from the rules cyclopedia to match those in the book and made them clearly stand out as the basic options by adding the AC value in the name
> [D&D_BECM] Clarified and changed names of the basic armors for in BDnDsheet

- MERP/merp_2nd_ed_sheet.css
- MERP/merp_2nd_ed_sheet.html
- MERP/readme.md
- MERP/sheet.json
Changes in functionality
* Change languages from dropdown back to text field.
* Change auto-calc mechanisms to JavaScript functions where applicable.
* Add optional professions from 1993 edition.
* Add martial arts skill category from 1993 edition.
* Add placeholder list for injuries.
* Refactor weapon sheet and weapon attack template.
* Add weapon weight calculations.
* Remove the half-baked background options.
Bug fixes
* Fix ad hoc modifier for secondary skill (MM) rolls.
* Fix tracking skill stat from IT to IG.
* Fix culture/race bonuses.
* Adjust the development point display on skills sheet.
Aesthetic changes: 
* Fix invalid HTML elements.
* Align section elements.
* Add table header to secondary skills table.
* Update readme.
Changes in attributes:
* No previously existing …
> [MERP] Fix and refactor MERP character sheet

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.html
- Shadowrun Sixth World/translation.json
Bugfix - Removing Technomancer echos with modifications didn't update things correctly.
Bugfix - Replaced translation "Rotarcraft" with correct "Rotorcraft"
Added Modifications functionality to Magic->Adept->Powers
Added Modifications functionality to Magic->Meta->Metamagics
Added Modifications functionality to Technomancer->Complex Forms
- [ NA ] If changing or removing attributes, …
> ShadowrunSixthWorld-v.48

- Palladium Fantasy 1E/palladium_fantasy_1e.css
- Palladium Fantasy 1E/palladium_fantasy_1e.html
Added ammo count, range, and rate of fire to the roll template for the ranged attack section.  Removed the spinner arrows from the number inputs.
> Palladium fantasy 1 e

- GURPS/gurps.html
- Legacy Bugfix, the improved type checking made it so you had to delete skills, spells, and techniques twice. This helped me find a syncing bug and streamline the code and hopefully resolve a nagging legacy issue where a random blank row showed up or row gets highlighted with a red border. Reported by Mike.
- `GURPS\gurps.html`
> [GURPS] version 2.6.8.3

- T2K 4e/twilight-2k-4e.html
Another change from Alpha to full release.
Replaces the Alpha letter system for vehicle reliability with the official release version of using a number.
- Yes. A correction between the alpha ruleset and the official release
- It does not.
- It does not.
- Unfortunately because of the change, there isn't a way to preserve existing data, however the change is mostly minor and doesn't impact any sheet-based roles.
- Not applicable.
> Twilight 2000 4th Edition | Update Vehicle Reliability from Letter to Number

- Shadowrun3e/shadowrun3e.css
- Shadowrun3e/shadowrun3e.html
IC now correctly identified as "legitimate" in cyber combat.   Removed iconstatus selected from repeating IC, this is now calculated based on the iconstatus switch on the Character/NPC sheet ( decking tab ).
All reactive IC rolls now whisper to the GM. 
Token Name is used for all cyber combat instead of character name.
> [Shadowrun3e] sprint12

- Alternity-RPG/Alternity_RPG.html
Added a checkbox to toggle wearing equipment and added a calculated total worn mass to the bottom of the equipment list.
> Alternity-RPG: Add toogle worn and calculated total mass to the equipment list.

- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Functionality: (DEV Mode) Dual Wield Talent ability now uses the reverses crit roll if one occurs right before the 2nd DW hit is rolled using the icon in the roll output of the first hit. If no crit is roll before it will reverse the previous roll as normal. This is a slight deviation from the core book rules, because they dont really make sense to make the 2nd hit harder if you crit roll is higher (i.e. penalised for a crit), like this is more random due to the roll reversal just like the none crited 2nd hit..
- Cosmetic: Arcane Spells roll output now correctly state Arcane Spell, rather then Petty Spell.
If you do not know English. Please leave a comment in your native …
> [Warhammer 4e Character Sheet] DW changes

- Robotech The Macross Saga (SMG)/robotech.html
Drama was only defined as a field, and didn't have a variable assigned to each field. As a result, every time the sheet was closed and then opened, the changes vanished.
> Robotech: The Macross Saga | Fix for Drama not being saved on sheet.

- CyberpunkRED_raycw/cyberpunkred-raycw.html
Removing slash from div tag
**All changes have been tested and validated in Sheet Sandbox # 12114933 "CPREDSANDBOX"**
Changes include:
- **Resolution of format-breaking / character in DIV tag**
- Completion of DEF, REX, MOVE adjustment based on absolute value of higher armor penalty fields
- Completion of addition of Brawling an Martial Arts to Weapon type drop down list
Thanks!
- [ Yes ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ Yes, it resolves a display error ] Is this a bug fix?
- [ Yes ] Does this add functional enhancements (new features or extending existing features) ?
- [ Yes, it resolves an error ] Does this add or change …
> [CyberpunkRED_raycw] Syntax error fix

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fix for Characteristics modifier which was adding twice on the skill target display in rolls.
- Resolved issue with Custom Spell Advantage rule (which basic removed advantage modifier from casting), this will now also disable Advantage for Langange Magick skill roll aswell as spellbook rolls. And removes the gold star indicator when disabled too.
> [Warhammer 4e Character Sheet] fixes

- BESM4eExtras/BESM4eExtras.css
- BESM4eExtras/BESM4eExtras.html
BESM4eExtras.css
v1.4.6
Group Types (Standard, Power Flux, and Power Variation) now display in title case.
v1.4.5
Ranged Defense attribute (Personal or Movement) now apply to DCV Roll when the respective button is depressed.
v1.4.4
Shield Parry Enhancement now applies to defense rolls.
v1.4.3
Added active Protection values to DCV Roll roll template.
Shock Value now correctly displays in relevant roll templates.
Minor bug fixes.
v1.4.2
Corrected roll template for Penetrating/Piercing. Key=value descriptors were reversed.
v1.4.1
Corrected initial Capacity value for Ammo. Should have been 0 instead of full Capacity value.
v1.4.0
Added support for range penalties on weapons when Range Enhancement is applied (Extras rulebook).
Added support for weapons with Ammo Limiter. …
> [BESM4eExtras] v1.4.6

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed issue where Twohanded weapons when selected would show offhand penality added to the target value of the specific weapon. This did not effect the Roll itself.
> [Warhammer 4e Character Sheet] 2H fix

- Sentinel Comics RPG/SCRPG-Sheet.css
- Sentinel Comics RPG/SCRPG-Sheet.html
- Sentinel Comics RPG/sheet.json
Added 2 Roll Templates, and stylized the Default Template. Also added a background texture to the tab buttons, so players can see which is selected.
This update is almost entirely aesthetics. Which are bringing this Sheet and it's Roll Templates more in line with the art of SCRPG.
One new button was added (it required a roll template w/ 3 Columns), and 3 checkboxes to determine Environment Status.
No attributes were removed, so no player data will be lost.
> Sentinel Comics RPG - Roll Templates

- BESM4eExtras/BESM4eExtras.html
Fixed bug where in some cases, such as taking an attribute over level 6, will cause the attribute's cost to be double counted when applied to the group cost.
> [BESM4eExtras] v1.4.13

- The Fantasy Trip/TFT.css
- The Fantasy Trip/TFT.html
I didn't like the dark purple font color of the weapon adjust component of the to hit number in the roll template.  I tried coloring the background a light purple, which was legible, but added too many different colors to the already colorful roll template.  So I stuck with the yellow background but added a lightning superscript.  Being a superscript it invites mouseover which will show you the weapon_adj or spell_adj inline roll tooltip.
> [The Fantasy Trip] Changed roll template weapon adjust color into a lightning superscript

- Exalted 3/Exalted3-Sheet.css
- Exalted 3/Exalted3-Sheet.html
Adjusted the dot-based layout of the sheet to have 5 dots per ability/attribute rather than 10, as those stats have a normal maximum of 5. 
Added an enemy soak prompt to the quick pools damage roll so the damage pools don't have to be adjusted each time.
Made a couple of touch-ups to the dot layout to make better use of the space and align the sections better.
> [Exalted 3] dots layout adjustment

- D&D_4E/D&D_4E.css
* Corrected CSS so that linear-gradient is a background property instead of background-color. Before this change, monster stat block headers had a default background. Now they will be green/chartreuse (as intended).
> [Dnd4e] Bugfix for Header Color of Monster Powers

- Runequest3/Runequest3.html
発射武器欄にある余剰な中括弧を削除。
- [yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [yes] Is this a bug fix?
- [no] Does this add functional enhancements (new features or extending existing features) ?
- [no] Does this add or change functional aesthetics (such as layout or color scheme) ? 
> Update Runequest3.html/ Remove extra curly braces

- World-of-the-Storytellers-WoS/wos.css
I'm trying to fix the error **again** that rolltemplate styling isn't work... 
Change font to google font.
I hope to solve the problem this time. please...
> [World-of-the-Storytellers-WoS] fix: try to fix rolltemplate css error (2)

- Alien Roleplaying Game/Alien-Roleplaying-Game.html
Fixed the Ships armament rolls to support the next version of the API Dice Roller. 
Fixed the Armor rolls to not use the API Dice Roller (armor rolls cannot be pushed).
> [Alien RPG] Fixed ship armament rolls

- World-of-the-Storytellers-WoS/wos.css
Remove duplicate images (remove background-image)
> [World-of-the-Storytellers-WoS] Remove duplicate images

- Monster of the Week Official/MotWHTML.html
Incorrect text key was fed to the move displayer for the Searcher's Prepared to Defend move. Fixed.
Fixed a small bug with the move-sharer button for one of the Searcher's moves. Single line. No impact beyond making the displayed text more correct expected.
> [Monster of the Week Official] Bug fix

- Symbaroum/symbaroum.html
Add an hidden input in corruption section to compute attr_corruption_total as (corruption+corruption_premanent).
This is to be able to use [corruption_total / resolute] as a token bar.
> [Symbaroum] Add total corruption hidden input for use in token bar

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Added Ogre to the race list race with x2 human HP and Enc as from Archives of the Empire vol 2
- Fix for melee weapons list target display for any weapon except 2H
> [Warhammer 4e Character Sheet] Ogres & Fixes

- Masks - A New Generation/masks.css
Because it's unreadable in roll20 Dark Mode
> [Masks] Darkmode

- D&D_4E/D&D_4E.css
When using a power template, the "emote" part of the power looks like it was intended to be on a light background and was hard-coded to black. This made it nearly impossible to read on the dark theme. Changing this `.sheet-emote` rule to set color to inherit causes it to inherit the color that normal chat text gets, which is correctly adjusted for the dark theme.
Before (dark theme, unreadable):
Before (light theme, readable):
After (dark theme, readable):
After (light theme, readable, looks almost the same):
In light theme, the inherited color is `#404040`, very dark grey, which is slightly different from the current sheet's hard-coded black. I don't see any reason it needs to be different from the inherited color but maybe someone disagrees. 
The reason for `inherit` instead of removing …
> [D&D_4E] Fix emote text color on dark theme in powers

- Red Giant/RedGiant.css
Updated image links to github from the temporary image hosting.
The logo isn't showing up right in chrome for some reason, but I've submitted a bug report for that.
(Does not image usability of the sheet).
It works in Firefox though.
> [Red Giant] - update image links to github

- CWOD-V20/V20.html
- CWOD-V20/translation.json
Fixed the spelling of the word "Conviction" in `translation.json` and in the name of the i18n key as well.
> [CWOD-V20] Fix typo in translation and i18n key for "Conviction"

- Classified/Classified.css
- Classified/Classified.html
Fixed pc wounds resetting when sheet closed and reopened.
Missing quotes from attributes drawTurn and selectTarget
Added a modifier for pain multiplier.
Fixed attribute name for pain DF for first squad member.
Added Draw button to Major NPCs a popup will ask for the draw modifier for the weapon.  The squad member that the draw roll member does not have to be the selected member.
> [Classified] Bug fixes and Draw buttons for npcs and squads

- Fate/FateOmni.css
- Fate/FateOmni.html
- Fate/sheet.json
- CSS changed to support moving to the new model (legacy: false now in sheet.json)
- Added darkmode support for all sheet themes
> [Fate] Darkmode Support + Moved CSS off Legacy

- Blades in the Dark/blades.css
Added a different value for the --dark-secondarytext in the label styling; the background of some labels on this sheet is the same color as the initial value of --dark-secondarytext so it's making the text invisible. It'll be a much more significant undertaking to modify the sheet to fully take advantage of dark mode, but this should at least allow things to function as they should without full toggle support.
> [Blades in the Dark] Minor tweak to blades.css to prevent invisible text during dark mode

- StarWars5E/README.md
- StarWars5E/StarWars5E_CSS.css
- StarWars5E/StarWars5E_HTML.html
- StarWars5E/translation.json
* CSS fix for issue where new ship sheet tab selectors were covered when Advantage Toggle was on
> [StarWars5e] Bug Fix - Advantage Toggle covering page button tabs

- StarWars5E/README.md
- StarWars5E/StarWars5E_HTML.html
* Put in a check against a new behavior that began today 3-17 where sheet attributes are not being set on sheet open even when defined with a value in hidden attributes.  This caused HP and Shield calcs to fail until the related modifiers were changed at least once.  I have added a NaN check against this at least for the ship portion of the sheet.
> [StarWars5e] Workaround for attribs not being set on sheet open

- StarWars5E/README.md
- StarWars5E/StarWars5E_HTML.html
* Bug Fix - It was identified that because the default to-hit modifier had been changed from DEX to WIS on the Ship Sheet, sheets upgrading from 2.4 were over-riding any PC weapons to WIS that had not been EXPLICITLY set to DEX, because the weapon attacks on PC and Ship share the same repeating fieldset.  This is a documented Roll20 *feature*.  We have set the default back to DEX on the Ship Weapons for now as a fix for anyone else that still needs to upgrade.  In addition, the defaults between the SHIP and PC defaults have been aligned.  In version 2.4 the PC sheet set the defaults to STR, the SHIP to DEX and we have confirmed that once a name was placed in the 2.4 attack section the defaults would change to DEX.  This should now keep both attack sections in line and avoid a potential …
> [StarWars5e] Bug Fix - repeating section defaults New Feature - add ship save mods

- ADnD 2E Revised/2ESheet.html
- ADnD 2E Revised/javascript/sheetWorkers.js
- ADnD 2E Revised/javascript/version.js
Improved the handling of quotes from the Default Sheet Settings. The previous solution worked for new sheets, but not for old sheets when the GM uses the "Apply Default Settings" button from the menu.
> [ADnD 2E Revised] Bugfix useroptions

- Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
- Paradigm's RWBY TTRPG V1.0/readme.md
- Paradigm's RWBY TTRPG V1.0/sheet.json
Removed Yellow Dust effect being added to attacks due to double counting.
Migrated Defenses to their own section under Resources
Alphabetized Defense Checks
Alphabetized Skill Checks
Alphabetized Combat Actions
Changed .json from legacy = true to legacy = false
Updated Brown Dust's effect description in accordance to V1.01
Added auto calc for Max Armor and Movement
V1.01 Update
Removed Yellow Dust effect being added to attacks due to double counting.
Migrated Defenses to their own section under Resources
Alphabetized Defense Checks …
> Paradigm's RWBY TTRPG - New Feature/Bugfix 4/11/2022

- CoeursVaillants/CoeursVaillants.html
Following updates have been done:
- use default template on all rolls.
- add prompt to choose the 'métier' or the 'sauvegarde' to use.
- remove unecessary buttons thanks to that prompt.
- add a button to roll 2 series of characteristics.
- weapon roll now automatically adds the 'BC'.
- add a number input for maximum 'matrice' for each level.
- on 'fiche PNJ', automaticaly take the 'DV' amount to add to combat rolls (with +12 cap).
- add a button to roll a new hit points total (PJ and PNJ).
- correct the mistake on 'répit' roll. Was …
> [Coeurs Vaillants] New Features and Bugfixes - use template for rolls and other updates

- PokemonTabletopUnited_v2/PTUv2.html
Currently when using the import button, all attributes set to 0 will be skipped, because the [`==`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality) operator is silly and auto-converts strings into numbers. This PR fixes that.
This is technically a backwards-incompatible change, since this could in theory be used to set some attributes to "please don't override this" by setting them to 0. I don't think that's useful, however, since simply omitting those attributes achieves the same effect, and if this was intentional I doubt it would be checked this way - anyone who bothered to figure out how this all works would set their values to `""` if `null` is not an option in this case anyway (well, the correct option is `null`, but let me change as little as …
> PTUv2: Use strict equality checking for strings on attribute import (Bugfix)

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Updates the default page for PTA3 character sheets to the configuration page
- Updates the default character type to pokemon rather than trainer as the more commonly used type
- Updates the default tie breaker initiative to allow a full range of decimal values
- Updates the default type selection for new moves to typeless
- Resolves an issue where pokemon- and hybrid-type characters were showing "Normal" for their primary type instead of "Typeless" if it was not updated
> [PokemonTabletopAdventures_v3] Update: Changes default values to allow easier use

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* **Fixes**
* Fix: Function of roll buttons of spells 'Kraft des Erzes', 'Kraft des Humus' and 'Krähenruf' are no longer swapped (2b290269e2d2ecd54abba596b830745b07c2b3cb)
* **Miscellaneous**
* Bump version number (7cc62be78781b3ebb62ce614f6a889c93bc80fe2)
* Info on the latest version/changes (7cc62be78781b3ebb62ce614f6a889c93bc80fe2)
> [Das_Schwarze_Auge_4-1] Fix Mixed Up Spells

- PokemonTabletopAdventures_v3/PTA3.html
- Adds a button with an attribute-backed-span along with some inputs to hold the attribute
- Adds a sheet worker to toggle the publicity values when the button is pressed
- Updates all roll buttons to utilise the `publicity_roll` attribute when sending rolls to chat
> [PokemonTabletopAdventures_v3] New Feature: Adds a toggle button for rolling publicly or to the gm

- The One Ring 2e/release-notes.md
- The One Ring 2e/sheet.css
- The One Ring 2e/sheet.html
- enhanced contrast of roll buttons
> [The One Ring 2e] - 2.13 - increased contrast of roll buttons

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added 8-pt combat skill levels.
Changed total point formula so that EXP is subtracted.
Added space to point total inputs in CSS to better see 1000+ pts.
> [HeroSystem6eHeroic] Fixes for point totals. Added 8-pt Combat Levels.

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* ''Fixes''
* Fix external and internal spelling of the spell 'Visibili Vanitar' (5634696ced8f4a442a1cb15df8c41fda6f198160)
* Old attributes and roll buttons are kept, new attributes are migrated on sheet-open
* Miscellaneous
* Add comments on previous two sheet versions with migrations (0d91259d4eefc38bdb80d8dff12f9bd5f57f00da)
* Bump version number (24937e5625698df7c66d560f2a34380e5cda246e)
* Old attributes (unused after migration)
* `zauber_visibli`, `z_visibli_action`, `Spez_visibli`, `ZfW_visibli`
* Old roll buttons (same naming issue) will continue to exist for macro compatibility, but will use the new attributes and are hidden from the user to prevent future use
* New attributes
* `zauber_visibili`, `z_visibili_action`, `Spez_visibili`, `ZfW_visibili`
> [Das_Schwarze_Auge_4-1] Fix Spell Spelling (Internal and External)

- BESM4eExtras/BESM4eExtras.html
v1.8.4
* Reduced attribute cache ~35%-40% by removing all falsey assigned attributes and hardcoding default falsey values.  Such as when an attribute (Roll20) returns undefined then a default value of 0 will be assigned for an integer-based attribute.  Only attributes with non-falsey values will be written to cache.  The smaller cache size increased sheet performance.
> [BESM4eExtras] v1.8.4 - Bugfix/Sheet Performance Enhancement

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added 'Takes No STUN' power effects to the list of options. This feature would be typically used for undead, robots, golems, and other types of automaton NPCs. With the option set, STUN no longer counts towards character costs and cannot be recovered through healing or aid.
> [HeroSystem6eHeroic] Added option for 'Takes No STUN' power effects

- CWOD-V20/V20.html
Minor adjustment to styling of Path Sins, making it a bit more readable. Before, the number beside the textbox was below the textbox, making it a little unclear which one it was associated to.
This is a minor HTML styling change to the Path Sins block. The number denoting what text block was associated to which sin tier was a little unclear, because the number was BELOW the text block. I changed this to align to the top of the box instead. Also, since 10 is one pixel wider than the other numbers, I reduced the initial width of the first text block by one pixel so it lined up better on the right-hand side.
> Update V20.html - Minor Style Fix to Path Sins

- Warpland/Warpland.css
Number input box size is wrong size. It wasn’t an issue in sandbox.
> [Warpland] small fix on attribute number input size

- Torchbearer 2E/torchbearer.css
The new dark mode feature was overriding the css on the roll card causing a purple background and border. Added the important tag to prevent this override.
The new dark mode feature causes an override to the inline roll result background color. I have added the important tag to prevent this override.
Screen cap of bug with dark mode enabled.
Screen cap of fix with dark mode enabled.
Screen cap of fix with dark mode disabled.
> [Torchbearer-2E] [Bug Fix] Inline roll background color overridden in dark mode

- The Fantasy Trip/TFT.css
- The Fantasy Trip/TFT.html
- Round the 4d and 5d Attack radio buttons, to make the fact that they are radio buttons more clear.
- Remove the bottom clunky "Saves" row and replace with radio buttons for how many dice to roll
- Replace 3 and 4 dice stat saves with just one button which references the radio buttons
> The Fantasy Trip: styling, round the 4d and 5d combat radio buttons, add stat check radio buttons for dice count.

- BESM4eExtras/BESM4eExtras.html
v1.8.7
* Fixed bug where non-weapon attributes would fail to activate.
* Attributes with specialized configurations will now update when specialization is set.  Previously only would set when level was adjusted.
* Ranged Attack will now reflect which weapon it is specialized for.  Would still apply to weapon it was configured for correctly, the weapon configuration just didn't display.
* When Targeted limiter is added to Massive Damage, now shows <not configured> if an enemy has not been defined.
* The function setCombatRoll() no longer crashes if a maneuver is not selected. Previously this would cause some attributes not to activate until a maneuver was selected.
> [BESM4eExtras] v1.8.7 - Bug Fixes

- HeroSystem6e/HeroSystem6e.html
- Made generic attack button on OCV provide hit location and body count as powers do
- Added a button to do the same thing at the end of the OCV line of the combat preview table
The generic attack button provided very barebones attack roll info.  With this update it adds hit location and body calculation so that it is as complete as attack rolls for powers.  Additionally, I've added an intuitive attack roll button in the combat preview table at the end of the OCV row.
> Update HeroSystem6e,html to improve generic attack button

- HeroSystem6e/HeroSystem6e.html
The "hth" field was using traditional human notation for half dice, which was not properly parsed when passed to a dice roll.  By switching it to "dice" format instead of "text" format, we get dice annotation that roll20 can parse.
The character sheet previously displayed human-friendly damage dice in the "hth" attribute (e.g., 5½d6).  This occasionally made this attribute unusable for Roll20 dice rolls.  By changing the function call that populates the attribute to use "dice" format instead of "text" format, this issue is resolved.
> Update HeroSystem6e.html to store proper dice in hth

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed Enchanted Staff CN mod when casting. Should now add -1 appropriately for all Lore's.
- Fixed used with Characteristics Mod add resetting under certain circumstances.
- Channelling rolls from the Skill tab will now add Accu Ext SL to spells and rituals of the same Lore.
> [Warhammer 4e Character Sheet] Cast Lore/Staff fixes

- The Fantasy Trip/TFT.html
- When a weapon or spell is selected, attributes beginning with the word "ready" are set to mirror the current selection.  So we have `ready_name`, `ready_damage`, `ready_tohit`, `ready_attackflavor`, `ready_successflavor`, and `ready_failureflavor`  This to make it easier/possible for macro writers to get at the currently selected or "ready" spell or weapon.
> The Fantasy Trip:  feature add ready_XXX attributes mirroring the currently selected weapon or spell attributes.

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Adds conditional check when performing follow up Dual Wield attack, if the Player has just rolled a crit, they now will chose if they want to use main hand or crit result for the DW attack. Crit result DW hits will now remove any modifier on crit roll before reversal, so result stays within 1d100 range.
> [Warhammer 4e Character Sheet] Dual Wield - Crit update

- HeroSystem6e/HeroSystem6e.html
- Allow set and brace to be used along with another maneuver (e.g., strike or haymaker) as per rules
- Separate the various kinds of combat maneuvers for cleaner look
- Bring Skill Levels to the top so that they are not overlooked
- Separate the range modifiers and called shots from the refined hit location areas
- Move "focus" to called shots
> Update HeroSystem6e.html to improve the Combat tab

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed recent issue with Dark Mode on Chrome based browsers, illegible white text was showing in much of the chat log RT output.
- Custom WFRP4e token marker set 4.0 released includes UiA edition with no Advantage markers. Splits Fear into 1/2/3 markers. And a number of usefull custom markers.
https://github.com/Djjus/Vault/raw/master/Warhammer%204e%20Character%20Sheet/markers/WFRP4eset4.0.zip
UiA Edition: https://github.com/Djjus/Vault/raw/master/Warhammer%204e%20Character%20Sheet/markers/WFRP4eset4.0%20(UiA).zip
> [Warhammer 4e Character Sheet] Chrome Dark Mode fix

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.css
- Shadowrun Sixth World/Shadowrun6thEdition.html
- Bugfix - Non-PC sheets were broken anywhere that a textarea (notes style) entry existed you couldn't display it to add or edit the values.
- New Feature - character_name sanitization.  Sometimes we want to use names with characters that will break roll buttons and other parts of the sheet.  This replaces the bad characters with an asterisk *
> Shadowrun Sixth World v.59 - sheet breaking bugfix, minor new feature

- Ironsworn/Ironsworn.css
- Ironsworn/src/app/Ironsworn.styl
- Ironsworn/src/app/components/moves/moves.styl
- Ironsworn/src/app/roll-templates/mixins/body.styl
- Ironsworn/src/app/roll-templates/mixins/outcomes.styl
This is a possible fix for the CSS not loading into the chat frame, which completely screws the roll templates.
See also https://app.roll20.net/forum/post/11059481/roll-template-styles-no-more-applied-on-ironsworn-sheet
> [Ironsworn] Fixed roll template selectors not prefixed with template class, and forbidden escape sequence in CSS

- Fate/FateOmni.css
Unwelcome change in base.css definition of .label style's white-space property caused issues for labels that absolutely needed to wrap in the sheet. Have established a kinder override value for white-space in the relevant situation.
> [Fate] Bugfix for CSS styling of aspect labels

- Thirsty Sword Lesbians/TSL.css
Fixed a bug with displaying shared moves in chat that made them unreadable in both dark and light mode.
> [Thirsty Sword Lesbians] CSS bug fix

- GURPS/gurps.html
minor revision to resync button and add additional code to update skills linked to an attribute
- Options tab. Sheet Options sub-tab. Updated <b>Resync</b> button to change colors when clicked. Thanks to Onyxring's Roll20Async functions!
- Repeating Skills, attribute drop-down. The character sheet uses an old method to link skills to an attribute. The old method might not trigger correctly when an attribute like Dexterity is changed. Solved the issue by tricking the system into resyncing skills when an attribute is changed.
> GURPS 2.8.4

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - PC->Rolls->Matrix actions including cracking were not using the Cracking skill rating but whatever the rating of the last updated skill was. Fixed the bug causing this and loading the sheet the first time should update the attr_cracking value to be correct again.
> Shadowrun Sixth World v.60 - 1 Bugfix

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Updated Armor Tab - There is now 3 (Light/Medium/Heavy) Equip/unequip buttons at the top of the tab. This allows quicker equipping and unequipping of Armor for players. Also all Equip/Unequip and Worn/Unworn actions in this tab now automatically activate or disable the corresponding Armor penalties.
> [Warhammer 4e Character Sheet] v1.61 - Armor Tab update

- Level Up - Advanced 5th Edition/CHANGELOG.md
- Level Up - Advanced 5th Edition/levelup.css
- Level Up - Advanced 5th Edition/levelup.html
- [Yes] The pull request title clearly contains the name of the sheet I am editing.
- [Yes] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [Yes] The pull request makes changes to files in only one sub-folder.
- [Yes] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)
Added D10 and D12 in to the Expertise dice list for high level Rogues - but this is a static Expertise dice uneffected by Specialty (as …
> [Level Up - Advanced 5th Edition]expertise dice improvements

- Chronicles of Darkness/CofD.css
Fixes #10707 
The inputs are correctly populated, but the value is not seen because it is covered by the Firefox number input spinners (the up and down arrows for number inputs).
Hide the Firefox number input spinners for these "derived" inputs.
(Chromium spinners are already hidden with different css rules.)
> [Chronicles of Darkness] Hide firefox spinner for derived inputs

- Star Wars Saga Edition/StarWarsSagaEdition.html
Tiebreakers for skills in SWSE (including initiative rolls) are determined by the skill modifier, not the score of the ability that it's based on. That has never, ever been a thing.
Tiebreakers for skills in SWSE (including initiative rolls) are determined by the skill modifier, not the score of the ability that it's based on. That has never, ever been a thing.
> [Star Wars Saga Edition] Update: Changed Initiative tiebreaker to initiative mod

- Star Wars Saga Edition/StarWarsSagaEdition.html
Vehicle rolls would display as 
Strength}
(or Dex or Int), with an extra bracket in the name.
Vehicle attribute rolls currently have a bracket in their name when they are rolled.
> [Star Wars Saga Edition] Fix: Removed extraneous bracket from roll

- Star Wars Saga Edition/StarWarsSagaEdition.html
@{level|max} is a calculation which finds half of the heroic plus nonheroic levels. This is fine for things like skills, but it should not be used for damage. Only heroic levels.
Damage rolls currently use @{level|max}. That attribute is half (rounded down) of the combined heroic and nonheroic levels. Damage should not take nonheroic levels into account. There are some other rolls and values which …
> [Star Wars Saga Edition] Fix: Removed nonheroic level from damage calculations

- Snice/snice.css
Adjusted the roll result text color in the Roll20 dark theme. Apparently there was an update not so long ago that made the roll result's text white by default when dark theme is enabled, which then makes it almost invisible on the semi-white backgrounds of the Snice template. Updated the style to set a default text color so it's safe for future updates. (Totally my fault for forgetting this in the initial version as I left the color to the Roll20 defaults)
> [Snice] Adjusted result text color in dark theme

- T2K 4e/twilight-2k-4e.css
- T2K 4e/twilight-2k-4e.html
Since the release of this sheet the skill Persuasion have erroneously been named Manipulation (as it is called in many other YZE games). This changes that to the correct name, and adds versioning to handle the change not only in frontend but also in the data model (attribute is renamed to persuation as well).
> [Twilight 2000 4e] Renamed manipulation to persuasion, added versioning

- Level Up - Advanced 5th Edition/CHANGELOG.md
- Level Up - Advanced 5th Edition/levelup.css
- Level Up - Advanced 5th Edition/levelup.html
Added new Dice rolling logic, that gathers the components of the dice roll when the button is press this means that the every roll on the sheet doesn't need to be updated everytime standard/Advantage/Disdadvantage is pressed
Fixed Wisdom (perception) initiative to use Wisdom
Fixed all the Passive Checks to be 10+modifiers
- [Yes] The pull request title clearly contains the name of the sheet I am editing.
- [Yes] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [Yes] The pull request makes changes to files in only one sub-folder.
- [Yes] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)
- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, …
> [Level Up: Advanced 5TH Edition] dice rolling improvements

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - PC Weapon skills weren't applying the -1 unskilled penalty to some skills, this has been updated however users will need to update the skill to something else and back to trigger the data change.
Bugfix - PC Sheet imported from Genesis in a non-English language had many problems mostly related to skills.  I believe I've fixed these issues please report any new ones
Bugfix - NPC Spell roll template issue where if drain was under 2 it added "Drain: 2" at the bottom of the description.
> Shadowrun Sixth World v.65 - 3 Bugfixes

- ADnD_2E_Revised/javascript/sheetWorkers.js
Fixed magic weapons when placed somewhere without a whitespace, ie
- "Long Sword" becoming "Long +2 Sword" is okay
- "Short bow, Arrow" becoming "Short bow +2, Arrow" was broken
> [ADnD_2E_Revised] Bugfix/Fixed magic weapons not updating if the bonus is in the middle of the name

- Warhammer-Fantasy-Roleplay-2nd-Edition/WHFRP2.html
Updated Warhammer-Fantasy-Roleplay-2nd-Edition fixing the following.
SB & TB (Secondary profile) now actually use their respective BonusMod value for the Current calculation. 
Melee weapon 6 & 7 when rolling damage now use the correct name instead of using meleeweaponname1.
> Updated WHFRP2.html - Bugfixes SB & TB modifier actually used & Melee Weapon 6 & 7 damage rolls use correct name

- Castles&Crusades/C&C.html
Fixed some weapon roll buttons.
The WeaponOne_action buttons were misnamed in the button roll value.
> [Castles & Crusades] Weapon Buttons Fixes

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Resolves issue where every attack type throws out five sets of attack and damgae dice instead of only the number required
- Adds `attack_rolls` and `quick_attack_rolls` attributes to the repeating moves fieldset to house the accuracy and damage checks for normal rolls - asking for modifiers - and quick rolls - asking for no modifiers
- Updates the scatter type selection field values
- Adds support for updating sheets to use this new value
- Adds support for Population Bomb by adding an "Up to 10 Hits" option for the scatter type
> [PokemonTabletopAdventures_v3] Fix: Updates 3D Die Rolling

- PokemonTabletopUnited/ptu.css
- Removed spin buttons (up-down arrows) from numerical fields as they would overlap text in several fields.
- Removed page-wrap width as it was breaking the layout on tabbed view
- Added workaround for ::before elements in Firefox
- Added high-specificity height and border setting for tab radio buttons to maintain Firefox layout consistent with Chrome
> PokemonTabletopUnited - Bugfixes

- Magical-Kitties/Magical-Kitties-Save-the-Day.html
Once the big changes from the last pull request went live, I naturally discovered a bug in an edge case--if you create a fresh character sheet without a token assigned, attr_character_token doesn't get the default token image, but instead gets no image at all, which makes the top of the character sheet go wonky.
All the solutions I could find for switching to displaying nothing when the image is missing end up being stripped out by Roll20 (e.g. onerror, using wrapping <object> tags).
I don't know whether this is a bug with attr_character_token, but it's easier to take the img tag out than it is to troubleshoot a possible bug there.
Summary of behaviors with `attr_character_token` and `attr_character_avatar`:
1) Works great: Character has token assigned
2) Works great: Character HAD token …
> [Magical Kitties Save the Day!] bugfix: remove attr_character_token img

- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css
To the attention of @Plushtoast.
This small CSS change fixes some weird behavior in checkbox sizing that appears on the character sheet when using longer strings (from the Italian translation, for instance).
For reference, this is the sheet previously:
And this is the same sheet with the fix:
>  Das Schwarze Auge (TDE) 5 OFFICIAL: Fix checkbox sizing

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed Talent Nobleblood test +SL text during leadership rolls, now correctly dislays as situational bonus SL.
> [Warhammer 4e Character Sheet] v1.65b Talent dissplay fix

- Tesoro-y-Gloria-1E/tesoroygloria.css
- Tesoro-y-Gloria-1E/tesoroygloria.html
Hey, I'm the developer hired by the creators of the game Tesoro y Gloria (Telmo Arnedo). I realized that Roll20 applies the sheet- prefix to all CSS classes, and this is the reason of https://github.com/Roll20/roll20-character-sheets/issues/11489. This should fix the issue for this sheet. There is a [separate PR](https://github.com/Roll20/roll20-character-sheets/pull/11599) to fix the sheet "Tesoro-y-Gloria-2E", which has the same problem. Thanks in advance!
> Fix Tesoro-y-Gloria-1E sheet

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.css
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - Final(?) fix to Spirit and Vehicle dicepool bug.  Spirit ranged/melee dicepools are set when the spirit is created (when force/type are changed and reset toggle is on).  Vehicle pools are set when the sheet owner sets them.  They will only change now if/when they are in grunt groups and the number of grunts change or the sheet owner changes the dicepool directly.
> Shadowrun Sixth World v.78 - 1 bug fix

- Coriolis Alternative/CoriolisAlternative.css
Changed typeface to sans-serif in some classes that missing it so there's no mismatch in fonts throughout the sheet. While the original version of the sheet is displayed correctly, the mismatch can be clearly seen when adding translation. Probably because the font doesn't have cyrillic alphabet, so instead a default font is used that has different typefaces, unlike the Exo font that is sans serif in itself.
An example:
Font on the left:
Font on the right:
> Coriolis Alternative - Bugfix - Fix fonts in CSS

- Fate/FateOmni.css
- Fate/FateOmni.html
- Fate/translation.json
This is a small update for the official Fate sheet created & supported by Evil Hat Productions.
The Extras section of the sheet can get unruly if you have many Extras defined. This update adds a filtering feature; type in a search string, and any element that does NOT follow a title that matches your search will be hidden. Works in both editing and displaying modes.
> [Fate] New feature - Added filtering support for the Extras section

- Ordem Paranormal/ordemparanormal.css
- Ordem Paranormal/ordemparanormal.html
- Ordem Paranormal/sheet.json
- The name of this game is: Ordem Paranormal  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Jambo _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Ordem Paranormal _(i.e. Dungeons & Dragons, FATE)_
Adding the `sheet-` prefixs to CSS classes. Couldn't visualize this problem during tests on the custom sheet sandbox, so it passed without us realizing it was happening.
> Fixing Ordem Paranormal Sheet - Missing `sheet-` prefix in CSS file

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - More weapon dicepool tweaks
New Feature - NPC->Spirits made spirits awakened and now display the spells section for them.  Dicepool does not auto-update when spirit force changes, that is an exercise for the user.
New Feature - Added Critter Powers drag and drop from the compendium for spirits and grunts.
> Shadowrun Sixth World v.81 - 1 bugfix, 2 new features

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
- Now shows Degree of Success instead of separate chance/roll lines
- This can be disabled through Options menu
- Currently Applies to:
- Characteristics Rolls
- Perception Rolls
- Skill Rolls
- Armor Activation
- Power Activation
- Weapon/Shield/Basic Attacks
- Armor Activation of N/A will now show Locations if they contain information
- Option to Whisper Rolls to GM
- Tooltips added to Talents & Complications Page
> HeroSystem6eHeroic: New Feature - Rolls Output Display

- Kult Divinity Lost/KULT Divinity Lost.css
- Kult Divinity Lost/KULT Divinity Lost.html
Made Relations styled in line with the traits textboxes. Added extra fields for traits so that results show up in the roll template.
Changed style of relations text inputs so they match the ones in the traits section.
Added css to make the textareas in traits and relations auto-resize to their content.
Added roll result textareas and options textareas to traits.
Added the roll results to the roll buttons on the traits.
Added a checkbox + css to traits to hide the rollable parts for non-rollable traits.
Added placeholder text to textareas to clarify usage.
> Kult Divinity Lost: New feature - Updated relations style and traits layout with roll results

- Mythras/CHANGELOG.md
- Mythras/sheet.json
- Mythras/templates/sheet.js
- Issue causing default setting of Mythic Britain to actually be Mythic Babylon and visa-versa.
- Fixed issue with default "whisper rolls to GM" being set incorrectly.
> Upgrade Mythras to v3.2, two fixes to default settings

- Ars_Magica_5th/Ars_Magica_5th.css
- Ars_Magica_5th/Ars_Magica_5th.html
- Ars_Magica_5th/__tests__/testFramework.js
- Ars_Magica_5th/source/Ars_Magica_5th.scss
- Ars_Magica_5th/source/helpers/_helpers.scss
- Ars_Magica_5th/source/helpers/helpers.sheet.js
- Ars_Magica_5th/source/updates/updates.sheet.js
- Split out the Material Symbol import into a different `@import` statement, so that it doesn't interfere with other fonts
- Removed the variable font axes selection from the import. Those use nonstandard character for an import URL that the sanitizer likely trips on, and aren't apparently necessary
> [Ars Magica 5th] fix Roll20/roll20-character-sheets#11951: fix font imports

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
June 30nd 2023 v1.66
- Added Practical Quality option tick box to all Mail/Plate Armor, this will reduce all penalties by -10 on the given armor piece and update the penalties boxes accordingly.
- Corrected issue on Armor Tab where Shield Durability was adding to AP on the hit locatiojns display to the right.
> [Warhammer 4e Character Sheet] v1.66 Add Practical Armor Quality

- Star Wars Saga Edition/StarWarsSagaEdition.css
- Star Wars Saga Edition/StarWarsSagaEdition.html
- Star Wars Saga Edition/sheet.json
"Is Droid?" checkbox sets @{FortMod} to STR instead of CON.
Minor formatting changes.
Set correct default skill mods for NPC Acrobatics and Deception.
Fixed corners for dark mode rolltemplates.
Centered text for disabled and readonly inputs in Chrome.
> [Star Wars Saga Edition] Minor bugfixes, formatting changes

- Sword World/sheet.css
- Sword World/sheet.html
- Bug: monster unique skill fix (the window should now stay open until you click to close it on the same icon)
- Target numbers removed
- Bug: damage rollers should now work on first create (weapons and power table)
- Trade common is now optional, but selected by default
- Bug: Fairy Tamer spelling
- Bug: Marksman removed from evasion calculation and display
> [Sword World 2.5] Bug fixes

- D&D_4E/D&D_4E.css
- D&D_4E/D&D_4E.html
Several changes made to repair the D&D 4e roll template layout, which has drifted out of date in recent years.
- Emote text (above the table) now uses the text color. Roll20 doesn't appear to specify a single css variable like `--chat-text-color` that specifies the chat text color regardless of mode, so I had to set per-theme the way Roll20 sets it.
- Table header has slight padding on the right now.
- All rows have slight padding and line height increase. Somewhere along the way the table became incredibly cramped, or maybe it was that way since the beginning.
- Rolls are now colored correctly and no longer spill outside the cell they're in.
- Added a ✦ to the center of the keyword line, which is a staple separator on this line of D&D 4e power templates.
Additionally did some cleanup:
- …
> D&D 4E: Roll template updates to fix layout and text issues

- MERP/merp_2nd_ed_sheet.html
* Typo: Slash in equipment critical dropdowns had Crush headers
* Fix:  Exploding dice should be >96 (means >=96 in roll20)
* Fix:  Effective MM Bonus on NPC/Equipment only showed penalty, not bonus+penalty.  Display issue only.
* Fix:  Orientation on NPC/Creature tab always rolling 0
* Enhancement: Enable _max for hit points and power points so token bars will work when the related attribute is linked.
> [MERP] Typo/bugfix/enhancement

- Mongoose_Traveller2e/MongooseTraveller.css
- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/translation.json
- NPC Armour wrapping
- Vehicle now has Mounts and Weapons with same logic as Ship
- Animal has initiative
- Ship hard point title Hardpoints/Firmpoints has properly defaulted [0] for number of hard points based on tonnage (and is flipped to Hardpoint/Firmpoint
- Ship Power title now has [0/0] properly defaulted showing Used/Total
- Vehicle and Ship now have repeating Sensor rows with Player and Sensor Mod and roll button
- Psionics now represented like skills with the five Talents and then repeating Powers
- Fixed bug in Passengers where wrong dice result being used for quantity
- Fixed input focus colour in Firefox to be red as per Chrome
- Minor styling based on CSS refactoring
- Minor descriptive text changes/additions e.g. recommending using Source and Destination UWPs on Trade tab …
> Mongoose Traveller 2E - Ship, Vehicle and Psionic Enhancements

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Corrected a bug in the ability rolls buttons on new sheets
- Added support for a configurable list of skills
> ChroniquesGalactiques Version 4.4.0

- Godbound/Godbound.html
- Godbound/README.md
Changes to attack roll buttons and template to use new calculation that speeds up combat slightly. 
Attacks now do not require inputting target's AC. Instead, the rolltemplate displays the AC the attack would hit. New calculation is "20 - roll - modifiers" instead of "roll + modifiers + target's AC vs 20." This makes combat faster by removing one step in the sheet's rolling process.
This change means that AC is no longer required to be revealed before rolling, but rolling for attacks is still compliant with the game's RAW.
> Godbound Minor Feature Update

- HarnMaster3/harnsheet.html
- HarnMaster3/harnstyle.css
Minor layout change for missile weapon grid to prevent 1 weapon displaying on 2 rows
n/a
Minor layout change for missile weapon grid to prevent 1 weaping displaying on 2 rows
> HarnMaster3 - Minor css update

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Change log:
Features:
Expanded functionality of martial maneuvers: Roll Buttons for normal and killing attacks and blocks, END costs with buttons for non-martial or advanced maneuvers, and STUNx.
Removed the "Basic Attack" maneuver and added a ninth martial maneuver with the name "Basic HTH Strike." 
To keep the default strike functionality, "Damage by STR" is a keyword phrase for maneuver effects. Any maneuver effect that includes this keyword will use and update normal damage and END values according to STR.
Maneuver rolls display …
> [HeroSystem6eHeroic] Maneuver and color accessibility improvements. Bug fixes

- Shadowdark-Unofficial/Shadowdark-Unofficial.css
- Shadowdark-Unofficial/Shadowdark-Unofficial.html
- Shadowdark-Unofficial/sheet.json
- Fixed HP parsing (precedence issue, affected by previous Hydra fix attempt)
- Fixed Level parsing (precedence issue, affected by previous Hydra fix attempt)
- Fixed exception thrown by `titleCase()` when input is null / empty
- Improved regex for level, hp, and attack damage to account for weird slash `/` issue with elementals (picks the left hand side as default - for best results people shouldn't paste slash, or can edit after import)
- Fixed issue with splitting ATK with commas in the effect section, i.e.: the "Azer" stat block "2d8, ignites flammables" to properly parse the effect
- Effect output now shows "Effect: <effect>" in the description
- Fixed issue where range wasn't being imported due to using `.rng` instead of `.range`
- Fixed issue with parsing non-die damage (like …
> Update Shadowdark-Unofficial.html: Fix monster parser, options, and initiative

- Shadowdark-Unofficial/Shadowdark-Unofficial.html
- Version 2024.1.29.0
- Attacks and Spells: Damage 1 flag is once again a checkbox that user can control.
-- The Damage 1 flag is checked by default.
-- Spells or attack-like actions that don't deal damage can uncheck the box to avoid showing a "0" in the attack effect template (AKA damage template)
> Shadowdark-Unofficial: Restore damage flag checkbox to fix non-damage spells

- Fabula Ultima/FabulaUltima.css
- Fabula Ultima/FabulaUltima.html
- The name of this game is: < Fabula Ultima >
- The publisher of this game is: < Need Games!, Rooster Games >
- The name of this game system/family is: < Fabula Ultima >
This offers several corrections and upgrades to the sheet:
1) The sheet now uses images hosted on Roll20 repository instead of outside sources. This also fixed Tonic image on Inventory, which was broken.
2) Changed Inventory tab name to Backpack, and "Inventory" is now a section of Backpack for items that use Inventory Points.
3) Created slots on the Backpack tab for spare armor/shields, spare accessories, and other items.
4) Created a mechanism for fast swaping current equipment with those from the backpack spare, and also the possibility of swaping weapons with those of the Other Weapons section.
5) Refactored the …
> Fabula Ultima: Third batch of upgrades to the sheet.

- Shadowdark-Unofficial/Shadowdark-Unofficial.html
**Shadowdark-Unofficial sheet - Version 2029.2.29.0**
Fixed 2 typos: Attack modifiers applied correct stat bonus but showed DEX instead of CON and CHA
BUG FIXED: In Attacks & Spells, the labels for the drop down options CON and CHA were showing "DEX" instead.
> Update Shadowdark-Unofficial.html: fix DEX typo for attack modifiers

- Paladin/paladin.html
Change list 03/12/24 - following pull request blocked due to attribute conflict: 
Corrected Age button
Fixing repeating container bug
Ideals - adding missing romance ideal field
Ideals - changed descriptions to reflect current rules
Squire section was wrongly pointing to the checkbox rather than the actual text field
Annual glory - added missing total, fixed sum calculator
"Knights" attribute (_attributes.knights.forEach(attr => {_)was doubled, changed for "annualglory" attribute that was missing
Fixed sum calculator syntax
Dropped change from attribute "name" to "character_name" - will use sheetworker at a later stage (thanks for the tip)
Modified calculator for derived attribute damage (rounding down as per rules, instead of rounding up)
Added my name as contributor, updated sheet …
> [Paladin] Overhaul continuation

- Paladin/paladin.html
The checkboxes & text in the health section are all unaligned, causing unaesthetic alignment in the sheet. By changing the div class, the three lines & corresponding checkboxes realign properly.
The "member of the round table" attribute & box is useless - it is a holdover from the old King Arthur Pendragon character sheet on which the Paladin sheet is based. There are no round table knights in the Paladin universe :) However "Paladins" are indeed a thing (given the name of the game, what a surprise :) ), and this space is to keep track of the year in which the characters potentially receive this super rare honor. It makes sense to drop the old attribute and put the paladin one instead. Impact is extremely minor for users - its just there to track a year, and as I said, it is super rare …
> [Paladin] next small ovehauls

- Paladin/paladin.html
All three ideals for knights (Romance, chivalry, religion) consist in adding up the values of six relevant personality traits.
Rather than doing it manually, I propose this change to automate the calculations and thus making it easier/faster for players.
**Current version (in French)**
**Proposed change**
Also, adding 0 as default value to all 4 squire basic skills
> [Paladin] Automating ideals calculation + squire skills default value

- olddragon2e/olddragon2e.html
From now on, all attributes (Strength, Dexterity, Constitution, Intelligence, Wisdom and Charisma) will start with a value of "10". Consequently, all respective modifiers will have their initial value as "+0".
In addition, the JPD, JPC, JPS, BA and CA fields will also have their initial values ​​as "0".
This way, we prevent the rolls of these values ​​from presenting errors.
A partir de agora todos os atributos (Força, Destreza, Constituição, Inteligência, Sabedoria e Carisma) iniciarão com valor "10". Por consequência, os todos os …
> [Old Dragon 2e] New Feature: Add attribute and modifier initialization on sheet open

- Paladin/paladin.html
The Entourage tab in the character sheet allows players to track members of their entourage (squires, spouse, soldiers, professionals working for them, etc)
That tab as it is now is pretty much useless. No buttons for the skills of the entourage, code is a mess, etc...
Using the Pendragon 5.2 character sheet as a basis, I made some much needed changes to the tab, to make it much more usable & enjoyable for players, without touching the attributes:
-adding buttons for actions, with rolls with modifiers as per the rest of the sheet
-re-arranged columns to make them more easily readable 
-cleaned up the code
All the changes are functional & greatly enhance the use of that tab
**Note :** wanted to create a different pull request from the other one I have waiting, as it is quite a substantial …
> [Paladin] - Update of the Entourage tab

- Paladin/paladin.css
Darkmode is not set for this sheet (as it is an old character sheet), and I got requests from some players who would like to be able to use the sheet with darkmode. As it is now, the roll template is unreadable while in darkmode.
This makes the roll template usable & readable:
**Changes to the roll template in darkmode**
> [Paladin] - adding darkmode support

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Shows the stats without the avatar when collapsed and the avatar and stats when expanded
- Refactors non-repeating section attribute changes to use a single function
- Resolves small issue with mobile companion overflow
> [PokemonTabletopAdventures_v3] New Feature: Converts stat and avatar to collapsible area

- Metal Adventures/MetalAdventures.html
In the MetalAdventures books, there are many skills that can be learned during the adventures.
However, the current sheet does not allow these skills to be added.
The paper sheets provide empty slots specifically for these cases.
Thus this pull request suggests adding 2 blank skills for each characteristic.
For years, we've been using extra lines for equipment, transfers and even specialities, but every time we have to think that we have a skill.
We often forget that we have an additional skill.
> [MetalAdventure][New Feature] Additional skills to add them when asked from books

- Star Wars Saga Edition/StarWarsSagaEdition.html
I hate this update. It's so stupid that a bug which has been on the sheet since the beginning can be fixed with something as stupid as changing an attribute and then changing it right back.
Anyway, the skill values on the sheet update properly when attributes or level changes now. 
Also added the repeatable Force Powers section to the NPC sheet.
Also added a fix for a bug introduced in December 2023 where the attributes were manually calculated with sheetworkers, causing them to be forever stuck that way.
> [Star Wars Saga Edition] Skill display fix

- Aventures/Aventures.html
Update Aventures.html
Correct the dice of 20 for puissance / finesse / aura / relation / instinct / savoir 
There was a small error at the d20 of the puissance / finesse / aura / relation / instinct / savoir.
The show dice was a 1d20 dice, but it was launching a 1d4 dice.
The formula was wrong before at the line 102 : 
d20, 1d4cs1cf4 -> d20, 1d20cs1cf20
> [Aventures] Fix of sub-stat dice roll

- Das_Schwarze_Auge_4-1/dev/html/sheet/footer.html
- Das_Schwarze_Auge_4-1/dev/html/sheet/section_info.html
- Das_Schwarze_Auge_4-1/dev/html/sheet/section_magie.html
- Das_Schwarze_Auge_4-1/dev/js/migration.js
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* Fix bug (kreuvf/roll20-character-sheets#145) preventing certain spells from receiving the automatic stat replacement based on representation (5baf0f5156, 313e313029)
* Indicate updates with accompanying videos, add direct text links to the videos (2932c1735b)
* Fixed typo (ff5529cbf0)
* Bump version number (f77ce9744c)
* Add info on latest version (ce9a4adf18)
* Regenerate sheet files (4abeaa0bb5)
> [Das_Schwarze_Auge_4-1] Fixes to Spell Representations

- Blades in the Dark/blades.css
Missing line from CSS to fix current production-impacting bug
I was asked not to submit this fix for a known issue with last week's pull request update due to Roll20 dev needing to fix a separate code issue on their side that the prior deployment revealed. Folks are still complaining loudly about this CSS-based issue, though, so we need to get this out to production ASAP. (It's thankfully a small and simple thing)
> [Blades in the Dark] Fix for missing line from CSS to fix current production-impacting bug

- Blades in the Dark/blades.css
Fixing error induced by non-legacy-mode Roll20 code not conveying defined color variables to the roll template's subsection of CSS — marked clock segments were not displaying properly when the a clock's status was broadcast to chat. They display correctly with this adjustment.
> [Blades in the Dark] Bugfix: Clock segments not displaying when broadcast to chat

- GURPS/gurps.html
Fixed bug where all rolls was showing the note "If parrying weapon is or less, check for breakage. B376." Reported by Niccy_Everson and Cal Godot.
- BUGFIX: Fixed bug where all rolls were showing the note "If parrying weapon is or less, check for breakage. B376." Reported by Niccy_Everson and Cal Godot.
> [GURPS] 2.20.0

- Heavy Gear 4e/HeavyGear4e.html
Fixed Add New Gear Weapon not displaying traits and update valueless inputs
**Reissued Pull request after auto-update bug**
Values added to inputs that lacked initial values
Bug fix: Gear Weapon Traits now update when weapons are created with Add New Weapon button
> Heavy gear 4e: Bug Fix Add Gear Weapon now shows traits properly, cleaned up

- LANCER RPG (1.8)/LANCER.html
Fixed White Witch missing semicolon.
Made IPS-N Caliban selectable in Frame list.
Added data for other official mech frames from expansions:
GMS Chomolungma
GMS Sagarmatha
IPS-N Empakaai
IPS-N Kidd
IPS-N Störtebeker
SSC Emperor
SSC Orchis
SSC Swallowtail (Ranger Variant)
SSC Viceroy
Horus Calendula
HA Enkidu
HA 'Worldkiller' Genghis MK I
> [Lancer RPG (1.8)] Bugfix and Additional Mech Data for Frame Selection

- BASH Ultimate Edition/BASH.css
- BASH Ultimate Edition/BASH.html
- New custom roll parsing, to
-  - calculate the result
-  - show the dice rolled
- Made the roll table collapsible. Collapsed by default.
- Replaced the Patrick Hand sections with a font I think fits the theme better
- Boxes are now aligned to each other and no longer overlap
- Added custom roll-able attacks to the repeating section
-  - Separate for hit and damage, with custom messages optional messages for each
- Lots more space for the skills, notes, and equipment textareas
- Secondary stats now have 3 sections for dice mod, roll …
> BASH Ultimate Edition - sheet & rolls update

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Characters now save their skill costs on creation
- Enables use of custom professions
- Helps with Roll20 Characters (create characters outside of game)
- Support: Add "charactermancer" button to the settings page.
- Will break your harcater.  You hae been warned
- Allows migration to new skill costs
- Bugfix: Highest stat gets confused if the first is highest, and the second is not the secondhighest.  Add tests for these cases.
> RolemasterUnified Official: Save Skill costs and bugfixes

- RolemasterUnified_Official/rolemasterunified.css
- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Update 2024-8-27
- Add movement for creatures
- Set default values for hp, pp and injuries and the like.
- Sort skill and table names in attack add
- Add option for no attack skill
- Spells show +/- in summary
- Initiative is an action; not a roll.  Remove superfluous d20
- Attacks
- include manuever penalty
- add AP tracking (melee only)
- Expand modifiers clearly
- Spells now include manuever penalty
- Bugs
- Fix missing attack modifiers
- Handle applying damage to creatures with ')' in their name
- Add internal sheet versions.  Unfortuantely
- Display sheet version on last page
- Automatically upgrade sheet 1 -> 2
- Sheet 2 is skill costs on sheet (Character support)
> Rolemaster Unified Official: Attack and other updates

- BattleTech-A-Time-of-War/BattleTech-A-Time-of-War.html
- BattleTech-A-Time-of-War/development/src/domain/skills/skills-list.js
- BattleTech-A-Time-of-War/development/src/sheet-worker.js
- BattleTech-A-Time-of-War/development/src/skills.js
- BattleTech-A-Time-of-War/development/test/skills.test.js
The 3rd printing of A Time of War removes tiered skills, making them work just like regular skills, with the "advanced" level being treated as the standard. I'm fairly certain that this change doesn't actually necessitate updating the sheet version or changing the migration script for older versions, as it doesn't actually change the data format of the sheet, just the behavior for what were previously tiered skills.
> BattleTech A Time of War 3rd Printing Update - Removal of tiered skills

- HarnMaster3/harnsheet.html
Due to type in attribute Horse willpower wasn't taken into account for Horse endurance. Fix now and added small data migration to move over data from old attribute.
n/a
Due to type in an attribute, Horse willpower wasn't taken into account for Horse endurance. Fixed now and added small data migration to move over data from old attribute.
> [Harnmaster3] Bugfix horse endurance

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
Urgent fix for a roll20 API change.  Some of the values in fields from the charactermancer started getting expansion ids shoved on the return values. (if they contain a ~).
So before we look parse the string, remove any expansion ids on the end.
> RolemasterUnified Official: Urgent fix for ~ behaviour change

- Open Legend/Open Legend.css
Fixes a giant purple block from appearing on dark mode Roll20.
This adds !important to the ends of some of the CSS to force the night mode not to alter the inline roll template within the sheet rolls. Otherwise the night mode adds a large purple box blocking view of parts of the roll template. This is a fix intended to be replaced later  on with a proper one once I understand more fully how the night mode replacement works. A very minor update.
> BugFix for Dark Mode for Open Legend Sheet

- HarnMaster3/harnsheet.html
Missing ";"in html resulted in "nbsp" tag showing on horse combat stats
n/a
Missing ";"in html resulted in "nbsp" tag showing on horse combat stats, fixed now.
> [Harnmaster3] Bugfix - Minor html typo correction

- Prowlers_and_Paragons_Ultimate_Edition/prowlersnparagons.html
Fixed the PRO/CONs for the animal form showing up regardless of which transformation type is selected. 
Fixed Doppelganger spelling: Doppleganger -> Doppelganger 
Edge sheet button now invokes &tracker
Summoning power now shows PRO costs in text.
> [Prowlers-and-Paragons-UE] UI fix for Transformation Power and Summoning Power

- Serenity/serenity.css
- Serenity/serenity.html
Sharpened contrast for some tooltips.
Added number of die for explosives
Padding on left margin for some textboxes
HTML changes:
Corrected (likely) cut-and-paste errors in Assets and Complications
Added a ‘Number of Die’ field to Explosives
Extended left padding in textboxes to Notes, Description, and History
CSS changes: 
Tweaked field length to allow a ‘Number of Die’ field to Explosives
Changed tooltip colors for better contrast
Removed superfluous roll templates
Added a small checkbox: smallCheck
> Serenity: New Features and Bugfixes

- Dark_Heresy/DarkHeresyStyle.css
Rolls in Dark Mode are unreadable due to the custom background image and font color.
This fix simply disables the problematic styles if Dark Mode is enabled.
> fix Dark Heresy rolls for Dark Mode

- Dragon Warriors/Dragon Warriors Revised.css
- Dragon Warriors/Dragon Warriors Revised.html
- Dragon Warriors/sheet.json
Demonologist Spells have been implemented.
Fixed errors in the layout for Custom Classes - skills and abilities sections. Removed "readonly" …
> Dragon Warriors: Bugfix and feature additions, updates sheet to version 2.01

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Adds a new roll template used by skills that has a more streamlined appearance
- Adds a new toggle button at the top of the sheet to toggle between skill roll templates, that defaults to the existing style
- Adds transitions for all collapsible sections of the sheet to make it more pleasing to use
- Adds collapsing sections for all areas of the sheet's character page
> [PokemonTabletopAdventures_v3] New Feature: Roll Template & More Collapsing Sections

- Brigandyne 2e édition/brigandyne_2e_edition.html
Correcting a typo to enhance the display of the spells repeating list
> Bugfix brigandyne_2e_edition.html 

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/README.md
- Adds `scrollbar-width: none;` to the visible component of the collapsible sections
- Also set webkit scrollbar height and width properties to zero
- Updates readme
> [PokemonTabletopAdventures_v3] Bugfix: Removes scrollbars from sections

- Forbidden_Lands/Forbidden_Lands.css
- Forbidden_Lands/Forbidden_Lands.html
- small header adjustment to help with translations
> Forbidden Lands

- Dragon Warriors/Dragon Warriors Revised.css
- Dragon Warriors/Dragon Warriors Revised.html
Bugfixes and Layout/styling updates
Ver 2.02
Fixed more incorrectly placed readonly tags across the sheet
Fixed high Psychic Talent score bonus …
> Dragon Warriors Update to 2.02 (bugfixes and layout/style updates)

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Initiative modified by maneuver penalty
- Update rolltemplate for initiative to show penalty if present.
- Add tests and validations for creatures.
- All creature weapons now have a size (usually 0)
- Display a message when an injury takes a character to negative hits.
> RolemasterUnified Official: Initiative improvements and creature fixes.

- ADnD_1E_Revised/1ESheet.css
- ADnD_1E_Revised/1ESheet.html
- basically just a rollback of last weeks single column not spanning full width 'fix' and a proper redo that doesn't cause collateral issues with the spell header layout.
> AD&D1e Revised

- RolemasterUnified_Official/rolemasterunified.html
- RolemasterUnified_Official/sheet.json
- RolemasterUnified_Official/updates.md
- Finalise handling of Professions with selectable Base lists
- Alchemists are the first users
- Half shield bonus skill for partial block - not the full one (all my players)
- Change 'maneuver_penalty' -> status_penalty
- Update everywhere except inventory; it was a collision of names before.
- Try and squash the super long list of errors when you first update stateud
- Compendium data: Move a long bow to Bow, Long for the table. (@nef)
- Equipment:
- Perception Penalties are now applied
- Ranged Penalties are now applied.
- Take a terrible guess if it's a ranged or melee weapon when adding attacks
- Creatures: Creatures can now roll skills.
- Creatures: Add hx for Hand Crossbows, and a few other attacks (@nef)
- Creatures now have framework for type of attack (melee, ranged, directed)
- …
> RolemasterUnified Official: Pre-Treasure Law Fixes

- The One Ring 2e/release-notes.md
- The One Ring 2e/sheet.css
- The One Ring 2e/sheet.html
- The One Ring 2e/sheet.json
- added "Favoured" modifier for pc combat proficiencies to allow handling of specific cultural virtues (e.g. Hobbit Cultural Virtue Sure At The Mark)
> [TOR 2e] added favoured rolls for combat proficiencies (new feature)

- D&D_3-5_Epic_6/README.md
- D&D_3-5_Epic_6/dnd_3-5_epic_6.css
- D&D_3-5_Epic_6/sheet.json
- D&D_3-5_Epic_6/src/css/header.css
- D&D_3-5_Epic_6/src/js/skills.js
- Adding user guide link
- Updating the logo to point to the roll20 github
- Add the attribute in the correct language for the skill label.
> [D&D 3.5 E6] - Small changes

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Add Cantor Talent from Heart of Glass/Ubersreik Adventures 1, situational test bonus for entertain singing.
- Add Chanty Talent from Sea of Claws, situational test bonus for entertain singing.
- Fix Master of Disguise Talent, now shows situational test bonus for entertain acting.
> [Warhammer 4e Character Sheet] v1.75 Add Talents

- ADnD_2E_Revised/javascript/sheetWorkers.js
Fix monster weapons to correctly apply bonuses when the modifier is a +1.
> AD&D 2E - Bugfix: Fixed monster weapon autofill for +1 magic weapons

- MythicD6/src/core.html
Per discussion at https://app.roll20.net/forum/post/12154470/mythic-d6-success-threshold/?pageforid=12154577#post-12154577, the current math for Mythic D6 Successes treats any roll of 3, 4, 5, or 6 as a success. Per the rules this is not the intent, as success should occur on rolls of 4, 5, or 6.
This seems to be happening as the dice math in the current html code states `>3` which seems like it should work, but per discussions above, this is actually treated as Greater Than or Equal to Three. 
To test this I made a custom sheet in my personal roll20 account with this math. As it lacks many of the files found in the official Mythic D6 Sheet there's no pretty formatting, but since this is a calculation-only change, this was adequate for my purposes. I verified these changes worked for both …
> Bugfix: Correct math on Mythic D6 Success Rolls

- Dresden Files Role-Playing Game/DFRPG.css
- Dresden Files Role-Playing Game/DFRPG.html
- Dresden Files Role-Playing Game/sheet.json
- Dresden Files Role-Playing Game/src/css/buttons.css
- Dresden Files Role-Playing Game/src/css/components/theme-threat.css
- Dresden Files Role-Playing Game/src/css/flex.css
- Dresden Files Role-Playing Game/src/css/general.css
- Dresden Files Role-Playing Game/src/css/legacy.css
- Dresden Files Role-Playing Game/src/css/main.css
- Dresden Files Role-Playing Game/src/css/roll-templates.css
- Dresden Files Role-Playing Game/src/gulpfile.js
- Dresden Files Role-Playing Game/src/html/character/charsheet.html
- Dresden Files Role-Playing Game/src/html/character/spells.html
- Dresden Files Role-Playing Game/src/html/character/worksheet.html
- Dresden Files Role-Playing Game/src/html/city/faces.html
- Dresden Files Role-Playing Game/src/html/city/high-level.html
- Dresden Files Role-Playing Game/src/html/city/locations.html
- Dresden Files Role-Playing Game/src/html/configuration.html
- Dresden Files Role-Playing Game/src/html/header.html
- Dresden Files Role-Playing Game/src/html/main.html
- Dresden Files Role-Playing Game/src/html/roll-templates.html
- Dresden Files Role-Playing Game/src/js/legacy.js
- Dresden Files Role-Playing Game/src/js/main.js
- Dresden Files Role-Playing Game/src/package.json
- Refactor with gulp to add modularity (smaller source files)
- Migration to CSE
- Added "Send to chat" feature for some fields that can be usefull to be send to chat.
> [Dreden files RPG] - Migration to CSE + Small features

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
Adds a level field for the advanced class level for hybrid-style character sheets, intended for use with Pokémon-class characters
- Ensures mobile shows the level field beneath the advanced class field
- Ensures desktop shows the field in-line with advanced class
> [PokemonTabletopAdventures_v3] New Feature: Adds Hybrid Advanced Class Level Field

- Chronicles of Darkness/CofD.html
From what I can tell, every single time the character sheet is opened it will revert a character's defense setting to the template's default rather than any value they had previously selected.  I know this is a little duplicative in terms of code but I figured it would avoid a major refactor.
I believe this bug is also present in CofD by Roll20 as well:
https://github.com/Roll20/roll20-character-sheets/blob/master/Chronicles%20of%20Darkness%20by%20Roll20/CofD%20by%20Roll20.html#L2371
I don't have a pro account so I wasn't able to test …
> Chronicles of Darkness:  Don't overwrite defense setting each time the sheet is opened

- Palladium Rifts by Grinning Gecko/CHANGELOG.md
- Palladium Rifts by Grinning Gecko/dist/rifts.css
- Palladium Rifts by Grinning Gecko/dist/rifts.html
- Palladium Rifts by Grinning Gecko/rifts.css
- Palladium Rifts by Grinning Gecko/rifts.html
- Palladium Rifts by Grinning Gecko/src/js/ammo.js
- Palladium Rifts by Grinning Gecko/src/js/armor.js
- Palladium Rifts by Grinning Gecko/src/js/attributes.js
- Palladium Rifts by Grinning Gecko/src/js/migrate.js
- Palladium Rifts by Grinning Gecko/src/partials/active.html
- Palladium Rifts by Grinning Gecko/src/partials/ammo.html
- Palladium Rifts by Grinning Gecko/src/partials/magic-summary.html
- Palladium Rifts by Grinning Gecko/src/partials/powersabilities-summary.html
- Palladium Rifts by Grinning Gecko/src/partials/psionics-summary.html
- Palladium Rifts by Grinning Gecko/src/partials/repeating_modifiers.html
- Palladium Rifts by Grinning Gecko/src/partials/repeating_modifiers_readonly.html
- Palladium Rifts by Grinning Gecko/src/partials/roll-templates.html
- Palladium Rifts by Grinning Gecko/src/partials/skills.html
- Palladium Rifts by Grinning Gecko/src/rifts.html
- Palladium Rifts by Grinning Gecko/src/scss/rifts.scss
- Add roll buttons to punch and kick damage.
- Add kick damage to Supernatural Strength.
- Add Ammo tracker to Profile tab.
- Move Perception from Saving Throws to beside Initiative.
- Active Profile columns now fill the width.
- Fix issue where damage that rolls into the next layer now outputs the correct layer name.
- Alternating colors on repeating rows, except in the Modifier Picker.
- Fix issue where using a `+` in a skill modifier dialog would cause the roll to be 0.
> Palladium Rifts by Grinning Gecko v1.6.1. Features/fixes.

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
> Earthdawn V341 - Big fixes

- Chronicles of Darkness/CofD.html
Small addendum to #13729 - it looks like a new sheet only counts as `sheet:opened` so the default is never set.  This change should verify if the defense_select property exists.  If it does, set the defense from the existing selection.  If it doesn't, initiate it for the current setup.
Test steps:
1.  Create a new CofD sheet
2. Expected:  The defense should be the default (lowest if 1.0, lowest + athletics if 2.0).  It should not be undefined (Defense?).  There should be no console errors.
3. Change the Defense Setting and close the …
> Chronicles of Darkness: Defense will be undefined on a new sheet

- Earthdawn (FASA Official)/Earthdawn.css
- Earthdawn (FASA Official)/Earthdawn.html
- Earthdawn (FASA Official)/sheet.json
> [!WARNING]
> [!NOTE]
- [ X] The pull request title clearly states the type of change I am …
> Earthdawn FASA - EDV346 Bug Fixes

- Dolmenwood/dolmenwood.css
- Dolmenwood/dolmenwood.html
- Dolmenwood/sheet.json
The formatting was incorrect due to my following some legacy code. This removes that error. It also makes the moonsign field more flexible for creative GMs.
> [Dolmenwood] Bugfix: Repair CSS and formatting caused by legacy setting.

- Dolmenwood/dolmenwood.css
- Dolmenwood/dolmenwood.html
Some fields on the monster tab did not have the attr_ prefix on the name. Also some style fixes.
> [Dolmenwood] Bugfix: Repairing the monster text fields to persist data.

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Adds collapsible section for skills
- Adds collapsible skills
- Adds collapsing functionality to skills section as a whole
- Adds new design for the skills in the trainer sheet
- Adds collapsing functionality to individual skills
- Consolidates individual skill configuration into the character page
- Fixes bug with skills not updating the roll template colour based on the attribute selected to roll for that skill
- Updates capture pokemon to new skill visuals
- Updates visuals of the capture pokemon field to match the new skill visuals
- Updates configuration of the capture pokemon field to surface the selected pokeball name
- …
> [PokemonTabletopAdventures_v3] Refactor: Skills Visual Update

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Ensures the ball capture modifier is added to the d100 roll every time
> [PokemonTabletopAdventures_v3] Bugfix: Correctly adds all ball modifiers

- Shadowdark-Unofficial/Shadowdark-Unofficial.css
- Shadowdark-Unofficial/Shadowdark-Unofficial.html
- Shadowdark-Unofficial/sheet.json
- Add Auto Roll Damage option
- Update UI for Repeater item forms to use a dialog instead of pushing content around when it opens
- Fix typos in legal text
- Add sword emoji to left side of damage rolling hyperlink because some users were confused about how to roll damage
- Updated mobile property to try to mitigate the roll20 app warning about sheet not working well with mobile (it seems to work) and tested on my pixel phone: Some font issue still, but roll20 wiki has details and I might or might not try to fix later - for now it shows letter "t" but the rolling works. Also, if you enable the new Auto Roll Damage option, the rolls actually work on phone - output rolls and damage properly. (Without this option, the damage link does not work on mobile). Mobile still has known issues, but …
> Update Shadowdark-Unofficial sheet to add option for Auto Roll Damage and make repeater forms into dialogs and fix typos

- Shadowdark-Unofficial/Shadowdark-Unofficial.css
- Shadowdark-Unofficial/Shadowdark-Unofficial.html
The phone app experience is now pretty decent - as long as "Auto Roll Damage" is checked!
- Version 2025.9.3.0
- Fixed mobile d20 dice font: the dice icons now show for rolling initiative and stats
- Fixed fonts and style for repeaters for Features/Traits and Spells/Attacks for better readability and to reduce overlap
- Fixed some wide elements which were causing mobile to overflow (the import options)
- Luck tokens now 50% bigger!
- **Includes previous patch fix for the "Modify" mode in Spells/Attacks/Features** - no conflicts expected
- The Gear/Treasure text area is now much taller, but can no longer be resized
> Shadowdark-Unofficial 3 Sep 2025 Fix mobile style and repeaters

- Outgunned/Outgunned.css
- Outgunned/Outgunned.html
- Outgunned/sheet.json
Code changed to try to work around differences between PROD and TEST enviroments
> [!WARNING]
> [!NOTE]
If …
> [Outgunned} Bugfix: Accommodate PROD Environment
