Roll20/roll20-character-sheets

PokemonTabletopUnited/ptu.html, PokemonTabletopUnited/sheet.json
Shifted some of the commonly used sections to the top of the sheet and vice-versa, eliminated HP combat stages (aren't supposed to exist), and added default values to trainer attributes.
=> PTU User Friendliness increase

13th_Age-neovatar/13th_Age-neovatar.html, 13th_Age-neovatar/src/sheet.html
**Fixed Bugs:**
* icon relationship type is now saved correctly as attribute
Sorry for the number of fixes, but the sheet is new and user are reporting bugs, so I fix them one by one. Thanks for the merge @SteveKoontz !
=> Fixes for 13th_Age-neovatar character sheet

Fate_Freeport/fate.css, Fate_Freeport/fate.html, Fate_Freeport/sheet.json
Simple formatting fixes for the new fate sheets.
=> Fate CSS and layout fixes

Dark_Heresy_2ed/DarkHeresy2ed.html
This pull request improves the following issues:
* Some of the percentages caused the buttons to render on the wrong line, making interacting with them difficult.
* Roll to hit buttons weren't working due to a missing paren. 
* Typo in advance select field
=> A few formatting tweaks and bugfix for Dark Heresy 2nd Edition

Palladium Megaverse/palladium_megaverse.css
=> Mild changes to css.

Eclipse Phase/Eclipse Phase.html
=> Fix for Int skills

Cyberpunk 2020/Cyberpunk2020.css
Making the boxes lining up and smoothing out my OCD
=> Lining up the text areas and select boxes

Exalted2e/exalted2e.css, Exalted2e/exalted2e.html
Add favored attribute checkboxes for lunar characters, add additional castes to the drop down box for non-solar characters.
=> Exalted2e expand caste list

Iron Kingdoms RPG/IKPRG.css
Includes Combat Caster, cleaned up css.
=> Cleaned up css

Iron Kingdoms RPG/IKPRG.html
Power-fields, fixed unarmed combat, other small changes
=> Newest Update

Pathfinder-FR/pathfinder-fr.html
Just a tiny fix about distances conversion (meters vs feet)
=> metric system patch

Stars_Without_Number/Stars_Without_Number.html
Added "_xp" to the name entry, on line 382
=> Fix to Misc Goal

Eclipse Phase/Eclipse Phase.html
Fix to Armor and arrow check boxes...all the check boxes, this time
=> Fix to Armor and arrow checkboxes

Eclipse Phase/Eclipse Phase.html
Skill totals in both active and knowledge skills include other bonus
=> Fixed Skill totals

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Added support for the Hellfrost settings (by Triple Ace Games), and a
some additional modifier fields in preparation for roll templates.
=> Minor Updates

Cyberpunk 2020/Cyberpunk2020.css
=> Matches new-er html

Vampire the Requiem/Vampire the Requiem.html
Exploding dice pools, repeating dice pools, wider blood potency box
=> Requested update

NWOD-Werewolf/NWOD-Werewolf.css
Just some pretty-ing up of stuff.  Added image.
=> Matching new html

NWOD-Werewolf/NWOD-Werewolf.html
Changed:
gifts into dotted boxes, with repeating
dice now explode on roll 10, and now repeating 
primal urge dots now red
change gnosis to essence
rage to primal urge
Added:
renown
picture to forms
rite/ritual box
...and some other stuff.  Minor overhaul, but an overhaul.
=> Minor overhaul

Microlite20/microlite20.html
The calculation for armor class was incorrect, so I fixed it.  I also
added roll buttons for all the different skill checks you could have.
=> Fixed calculation and added more roll buttons

NWOD-Werewolf/NWOD-Werewolf.css
Primal Urge now has 20 blocks
Essence is now all boxes, with 20 showing. 80 more (book says is max'es out at 100) are hidden behind boxes.
Added tool tips to forms.
Automated the forms input.
=> To match upgrade .html

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Pokemon Tabletop United recently updated from v. 1.04 to v. 1.05. I have changed the character sheet to account for these changes. This mostly involved changing some numbers in the calculations and trimming cut features.
=> PTU 1.05 Update

Fantasy_Craft/README.md, Fantasy_Craft/fantasycraft.css, Fantasy_Craft/fantasycraft.html
Added checkbox for including str-mod to damage rolls, several look & feel changes detailed in README
=> checkbox for adding str-mod to damage, look & feel changes

Maid/maid.css, Maid/maid.html, Maid/sheet.json
I am so new to github, I'm really not sure if I did this all right. I sure hope so!
Anyway, this is a slightly updated version of the Maid RPG character sheet. Updates include adding some fields for optional rules, as well as the ability to change the sheet if you wish to play one of the optional character types. I've tested it, and it seems to work well.
=> Maid RPG character sheet

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Added Roll Template Support for custom Macros and Abilities.
=> Roll Templates

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html, PokemonTabletopUnited/sheet.json
Added roll templates and features to support them, and a little bit of cleanup.
=> Update of Holding Support for PTU

Anima-Beyond-Fantasy-Spanish/A-BF.html, Anima-Beyond-Fantasy-Spanish/sheet.json
The last translation was completely messed, fixed it so it can be used.
=> Fixed Anima: BF spanish sheet

UnknownArmies/unknown-armies.css
See 13bd2503cb7acab418456b49e6a48aa790575d07 for details.
=> Attempt #2 to fix div.sheet-madness bug

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Added a Status Button, for moves which do not need to roll for damage.
=> Added Status Button

Microlite20/microlite20.css, Microlite20/microlite20.html, Microlite20/readme.md
I somehow missed adding a note to the initiative roll template explaining how it was calculated.
=> Microlite20 - Reordered positioning, and Cure for Walls of Text

Cyberpunk 2020/Cyberpunk2020.css
Added a button to roll attacks without using a roll-able table.
Also added some tool tips
=> Added non-roll table button

7th Sea/7th Sea.css
Cleaned up css, fixed some html, added static modifiers & tooltips
=> Adding modifiers

7th Sea/7th Sea.html
Added modifiers, cleaned up css, html, added tool tips, etc
=> Cleaned and fixes

Deathwatch/Deathwatch.html
Updating html & css to include unnatural characteristics
=> Added Unnatural Characteristics

Stars_Without_Number/ReadMe.md, Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html
Also, removed some redundant CSS.
=> Stars Without Number - Corrected weapon widths

D&D_5e_Shaped/D&D_5e.css, D&D_5e_Shaped/D&D_5e.html, D&D_5e_Shaped/ReadMe.md, D&D_5e_Shaped/sheet.json
Css fix to prevent wrapping of the death save boxes.
Also added Actoba as an author.
=> 5e Shaped updated

Mongoose_Traveller/MongooseTraveller.html
Fixed weapon table and character history tab (shouldn't open all with one click now)
=> Fixed Weapon Table

Mongoose_Traveller/MongooseTraveller.css
The first tab was over-sized; its not any more.
=> First Tab fix

Cyberpunk 2020/Cyberpunk2020.html
=> Fixing heavy weapons skill

Vampire the Requiem/Vampire the Requiem.html
Show all tab, some cleaning up of css
=> Update Vampire the Requiem.html

Vampire the Requiem/Vampire the Requiem.css
Show all tab, some cleaning up of css
=> Update Vampire the Requiem.css

Vampire the Requiem/Vampire the Requiem.css
Replace aggravated damage; should not conflict with other pull requests
=> Fix Aggravated damage

AD&D_1E/1ESheet.css, AD&D_1E/1ESheet.html
- added attrib_HitDice attribute.
- changed column layout to allow better placement of HitDice field.
- changed Multi-Class 2 and 3 to just Class 2, and Class 3 to help text
overlap of input fields when the sheet is decreased in size.
=> Added attrib_HitDice

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Added capability to use Roll Templates with the sheet buttons, or to
use the original emote style buttons. Also added Advancements tracker
to Journal
=> Roll Templates Integration

PokemonTabletopUnited/ptu.html
Fixed a bit of random info from a copy-paste error.
=> Fixed Copy-Paste Error

AD&D_1E/1ESheet.css
accidentally pasted the PF css to the 1e css.  This is the proper css for the 1e sheet.
=> Updated css for AD&D 1e

Ironclaw/Ironclaw.html
Initiative fixed, added roll templates, added show all tab
=> Fixed Initiative

Ironclaw/Ironclaw.css
Initiative fixed, added roll templates, added show all tab
=> Matching Html request

Cyberpunk 2020/Cyberpunk2020.css
=> Css Update to match 'Better Update' html

AD&D_1E/1ESheet.html
removed indent style on the roll template's <td> tags that would cause formatting issues on some inline rolls.
=> Removed old css style on roll templates

13th_Age-neovatar/13th_Age-neovatar.css, 13th_Age-neovatar/13th_Age-neovatar.html, 13th_Age-neovatar/README.md, 13th_Age-neovatar/package.json, 13th_Age-neovatar/sheet.json, 13th_Age-neovatar/src/sheet.html
* character default macro references description
* npc power default macro uses roll template
=> Update to 13th_Age-neovatar character sheet

Silent Legions/sheet.json, Silent Legions/silentlegions_sheet.css, Silent Legions/silentlegions_sheet.html
Sheet for Silent Legions added.
=> Adding a Silent Legions sheet for submission

D6StarWars/D6StarWars.html
Added name="attr_Physical_Description" to Physical Description textarea.
=> Physical Description Saves

Stars_Without_Number/Stars_Without_Number.html, Stars_Without_Number/sheet.json
min attribute was set to 0 when it should be -1.
=> SWN: Fixed min skill value bug

D6StarWars/D6StarWars.html
Added name="attr_credits" to credits textbox
=> Fixin's credits

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Added additional fields to the roll templates.  Also added Roll Buttons
to the Equipment and Acrana tabs.
=> Roll Template Enhancements

Icons Assembled/IconsAssembled.html, Icons Assembled/sheet.json
removed superfluous blank in Origin dropdown; fixed sheet.json to have
proper name for Preview image.
=> minor fixes

D6_Space/D6Space.html
=> Fix to Agility

GURPS_Mutonized/GURPS.html, GURPS_Mutonized/ReadMe.md
Finally came around to fixing some issues. Read me updated to reflect that as well.
=> Update to GURPS_Mutonized sheet

L5R/L5Rsheet.htm, L5R/L5RsheetCSS.css, Silent Legions/silentlegions_sheet.css, Silent Legions/silentlegions_sheet.html
NOW everything should be in order and functional.  L5R and Silent
Legions sheets both updated.
=> L5R and Silent Legions updated

Cyberpunk 2020/Cyberpunk2020.html
Minor fixes, including nested inline rolls
=> Nested Inline Rolls

Naheulbeuk/Naheulbeuk.css, Naheulbeuk/Naheulbeuk.html
Few improvement for my Naheulbeuk character sheet
=> Update Naheulbeuk Sheet (Invoker part and Main Carac. Modifier)

Mekton Z/Mekton Zeta.html
Armor Type
Servo Type
MS, HS, & others
Range
Ammo
Cockpit
Systems
=> Fix to Several Areas

Numenera_NathasNumenera_English/NathasNumenera_tabs.htm, Numenera_NathasNumenera_English/ReadMe.md, Numenera_NathasNumenera_English/sheet.json, Numenera_NathasNumenera_French/NathasNumenera_tabs.htm, Numenera_NathasNumenera_French/ReadMe.md, Numenera_NathasNumenera_French/sheet.json
Skill level added to the roll parameters. API script updated
accordingly.
"Tiers" corrected to "Tier".
=> v4.3 : skill level as roll parameter

Pathfinder-Neceros/pathfinder-neceros.html
STR was not being calculated correctly.
=> Pathfinder STR math fix

Star Frontiers/StarFrontiers.html
=> Added KH and Containers V2

D&D_BECM/sheet.json
Hopefully this is in better shape.  Not sure how I managed to get my fork so out of sync last time.
=> Update small error in the json file.

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html
changed the inventory description to be hidden by default
=> Pathfinder-Neceros: inventory description hidden by default

PortesMonstresTresors/ReadMe.md, PortesMonstresTresors/pmt.htm, PortesMonstresTresors/sheet.json
The PMT logo was too big on Firefox.
=> PMT v2.1 : layout bug on Firefox

NarrativesUnlimitedD10/NUD10.html, NarrativesUnlimitedD10/NUD10Style.css, NarrativesUnlimitedD10/README.md
Added a few things (see readme) patched a few undesirable anomalies.
=> NUD10 June update

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html
Mainly formatting update to facilitate the inclusion of more show/hide options and all relevant fields.
Big change that will affect users is the conversion of the Defense Level/Armor fields into an autocalc with a show-able field to manually put in the math, (Level put in by default, which is good for most characters)
=> Massive Update

Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css, Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
fixed a major bug about the talent rolls
added most of the currency´s of aventuria to the sheet,
also added auto calculation of the weight of the money
=> fixed major bug + multiple currency´s added

Cyberpunk 2020/Cyberpunk2020.html
Roll templates on skills, adjusted skills and weapon attacks able to (but not required to) reference rollable tables, etc. 
Fixed a few broken rolls,
=> General Update

Pathfinder-Neceros/pathfinder-neceros.html
Fixed consolidated skill Religion
=> Pathfinder - Neveros update

Iron Kingdoms RPG/IKPRG.html
Rune shots now available under the magic section.  Increased number of health boxes, etc.
=> Added rune shots

D&D_3-5/charsheet_3-5.css, D&D_3-5/charsheet_3-5.html
add color coding to skill ranks for untrained skills + CSS support for
the color coding.
=> Add Total AC calc to AC tab; +

Cyberpunk 2020/Cyberpunk2020.html
Fixed weapon button, adjusted default on hit location, changes font color.
=> Fixing weapon buttons

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
Chroniques Oubliees v1.1 : DEX roll and tooltips fixes.
=> Chroniques Oubliees v1.1 : bug fixes

Iron Kingdoms RPG/IKPRG.html
=> Change to Config menu

Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
Basic skills (Basistalente) that are shared among all characters added
=> Added basic skills

Pathfinder (Old)/pathfinder-old.html
=> Pathfinder(old legacy) Init fix

Atomic Highway/Atomic Highway.css
Because FontsAddict.com is a big 'o tease
=> Updating fonts links

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Added Vehicle support, Languages and minor fixes
=> Vehicles, Languages, & Fixes

Microlite20/microlite20.html, Microlite20/readme.md
Bugfix: Armor Class now accounts for the miscellaneous modifiers.
=> Microlite20 - AC Mod Bugfix

Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html
@kevinsearle Hi! I believe you're the author of the SWN sheet. I don't know if you have the commit bit or not, but I figured I'd ping you regardless.
I've gone and added a bunch of things that are useful to me for macro-ing / ease of play in SWN. In particular, this PR adds:
* Roll buttons for all the listed skills
* Roll buttons for all saves
* Auto-sets the Max Strain to Unaltered CON
* Boxes to store each Attribute's bonus value[1]
* A Box to store your current AC (to allow target-macros + for easy reference)
* A button for rolling initiative. If you have your token selected, it will automatically add it to the turn tracker. 
* A section just below the Core Stats sheet for the above initiative macro/roll button (and any future buttons that might be useful)
* Buttons for rolling attacks …
=> Stars Without Number Improvements

Shadowrun5e-Gerdofal/Shadowrun5e-Gerdofal.html
Changes in this version:
- Re-designed wound section to make it easier to understand
- Added boxes to increase or decrease physical and stun track due to modifications
- Enabled options section (in testing) at bottom of sheet (first option is to show or hide notes in rolls)
=> re-design of wound section and enabling of certain options

Feng Shui/Feng Shui.html
=> Adding shot tracker, cleaning up for Firefox

13th_Age-neovatar/README.md, Dragon Age RPG/Dragon Age RPG.css, Dragon Age RPG/Dragon Age RPG.html
I'm interested in forking this character sheet for the new Fantasy Age RPG. 
I felt I should correct a few typos first.
=> Typos Corrected

Pathfinder-Neceros/pathfinder-neceros.html
CL check formula fix
{{Check=[[ 1d20 + [[ @{spellclass-1-level} ]] ]]}} 
should be
{{Check=[[ 1d20 + [[ @{spellclass-1-level-total} ]] ]]}}
=> Pathfinder (tabbed)

Pathfinder-Neceros/pathfinder-neceros.html
Rolling back to no header images
- I need to offer options to toggle the images on/off and allow custom
image url.
=> Pathfinder - Neceros (tabbed)

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
improved rolls tooltips with nested rolls.
=> Chroniques Oubliees v1.2 : improved rolls tooltips

AW/apocalypse-world.html, AW/style.css
Corrected bugs where information wasn’t displaying properly and
modified the layout slightly.
=> Bug Fixes and Formatting

AW/apocalypse-world.html, SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Corrected the problem with Harm, Experience, and Improvements not
staying unchecked.
=> Harm, XP, and Improvements Fixes

D&D_3-5/charsheet_3-5.html, Rolemaster-Standard-System/charsheet_RMSS_fullcalcs_RollTemplates.html, Rolemaster-Standard-System/charsheet_RMSS_nocalcs_RollTemplates.html
Also updated the titles of several repeating section inputs.
=> Update buttons to have correct html close tag.

Deathwatch/Deathwatch.html
Two new tabs, adjusted rolls to show degrees of success, fixed some skills, etc.
=> Update to Deathwatch

Stars_Without_Number/ReadMe.md, Stars_Without_Number/sheet.json
With recent bugs and coming changes all from the current maintainer and I not having time to work on this sheet anyway, removing myself from the contacts. Also emphasizing the current maintainer's credit over mine.
=> Updated maintainer and contact info

GURPS/gurps.html
Fixed attributes not updating properly due to unintended use of max field;
Minor correction in swing damage progression;
Fixed lifting & encumbrance box not calculating properly;
=> Fixes to attributes, lifting and encumbrance boxes

Stars_Without_Number/ReadMe.md, Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html
What it says on the tin, the templates aren't the prettiest, IMO, but I used some NASA starfield image in the background, and it looks a hell of a lot nicer than the bare `/me`
Also adds defaults for attribute bonuses.
Also fixes a bug in the initiative button. The wrong die was being used (1d10 instead of 1d8). Fixes #979 
Bumps the version to 0.0.8
=> Implement roll-template for all roll buttons.

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
added magic.
more auto calculation
fixed several bugs
=> added magic. more auto calculation

Fate_Accelerated/fate.css, approved.yaml
added a custom roll template (FAE), based on one on the wiki, added the roll template to the default rolls on the character sheet, and added a button "Approaches" which is uses a roll query to allow the user to use one button for all their approach rolls.
the roll template is  FAE
its fields are name, approach, roll, and effect. approach, roll, and effect do not show if left blank.
=> slight modifications

PokemonTabletopUnited/sheet.json
=> Added my User ID

Diaspora/diaspora.css, Diaspora/diaspora.html, Diaspora/sheet.json
Looks like my use of fieldsets and how I was naming the attributes were causing most of the fields on this form to not save. This should fix that. bump to V0.2
=> rename attributes and remove fieldsets - using divs instead to group

MouseGuard/readme.md
Finally adding the readme text
=> Adding MouseGuard character sheet readme

13th_Age-neovatar/13th_Age-neovatar.css, 13th_Age-neovatar/13th_Age-neovatar.html, 13th_Age-neovatar/README.md, 13th_Age-neovatar/package.json, 13th_Age-neovatar/sheet.json, 13th_Age-neovatar/src/13th_Age-neovatar.html
=> Update of sheet 13th_Age-neovatar

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
added select inputs for species, culture and experience
improved rolls for attack and defense to show more detailed information
=> added select boxes and improved attack rolls

D&D_Moldvay_Natha/dndmold.htm, Numenera_NathasNumenera_English/NathasNumenera_tabs.htm, Numenera_NathasNumenera_English/ReadMe.md, Numenera_NathasNumenera_English/sheet.json, Numenera_NathasNumenera_French/NathasNumenera_tabs.htm, Numenera_NathasNumenera_French/ReadMe.md, Numenera_NathasNumenera_French/sheet.json, PortesMonstresTresors/ReadMe.md, PortesMonstresTresors/pmt.htm, PortesMonstresTresors/sheet.json
Roll template improvements, showing success or failure.
=> Roll template improvements

PokemonTabletopUnited/ptu.html
Added Display Roll Buttons for Features and Abilities.
=> Added Display Buttons

Stars_Without_Number/Stars_Without_Number.html, Stars_Without_Number/sheet.json
Version numbers the same.
Added info back to sheet.json I had removed previously.
=> Minor version/author changes

Exalted2e/exalted2e.html
See https://app.roll20.net/forum/post/2401442/exalted-sheet-bug/?pageforid=2401442
=> Fix autocalc fields error

Rogue_Trader/RogueTrader.html
- Fix some CSS classes assignation to resolve the overlapping issues when adding ranged weapons.
=> [RT] Fix right column overlapping

L5R/L5Rsheet.htm, L5R/L5RsheetCSS.css
=> rolltemplates

Exalted 3/Ex3-Sheet.css, Exalted 3/Ex3-Sheet.html, Exalted 3/sheet.json
Made large changes to the Exalted Third Edition character sheet, including fixing the CSS in one spot and many alterations to the HTML. Added Survival to Abilities, fixed check boxes, made most features repeatable, fixed a number of minor errors in the HTML, Etc.
=> Exalted 3e Sheet changes

Stars_Without_Number/ReadMe.md, Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html, Stars_Without_Number/sheet.json
* Fix weapon repeatable field widths
* Fix attack roll failure due to null attack bonus
* Added Languages text area
=> SWN: Weapon and Attack fixes

Star Wars EotEmpire_Dice - FR/sheet.json
I add the original authors of the sheet that I used.
=> Add other authors

Exalted 3/Ex3-Sheet.html
added the performance ability, made a martial arts style section that functions like crafts
and resized the divs to fit this change
=> Exalted 3e ability revision

Torchbearer/torchbearer.html
Two typos fixed: "Dugneoneering" obstacles for backpack, and "opponenet's versus tests".
=> Updated torchbearer.html by fixing typos

Cyberpunk 2020/Cyberpunk2020.css
Fixing background and non-working skills
=> Fixing background and skills

Icons Assembled/IconsAssembled.html
Took me 6 months to realize I had the abilities in non-standard order.
=> Put abilities in proper order

Exalted 3/Ex3-Sheet.html
relaid out several sections,
changed essence to 1-5 scale,
changed limit to checkboxes instead of radio buttons
ran html through a beautifier for consistent spacing and indentation
=> [Exalted 3e] Layout update

Shadowrun5e-Gerdofal/Shadowrun5e-Gerdofal.html
- Bug fix in spellcasting specialty button.
- Added v10 to output.
=> Minor bugfix

Shadowrun5e-Gerdofal/Shadowrun5e-Gerdofal.css
Changes in this version:
- Added light colored template (Thanks Neovatar for the idea)
=> Added second template

Basic Fantasy RPG/BFRPGsheet.html
Updated BFRPGsheet.html to add Experience block; also updated version number text.
=> Revisions to Basic Fantasy RPG sheet to add XP fields.

wfrp3e-French/wjdr3.html
Wrong related characteristic on skill ( Premiers Soins = First Aid ),
it's " Int " for "Intelligence", not " F " for "Force" (=strength)
=> Corrected related caracteristic

Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
added Lanzenreiten as Kampftechnik/talent and Raufen and Ringen as a Nahkampftalent, you can use these with a weapon like a Schlagring
=> Added some talents and combat techniques in DSA4.1

Fallout/Fallout 3.0.html
Added options of rolling D16 and D20 for Left and Right Hand Damage Dice
=> Update Fallout 3.0.html

Basic Fantasy RPG/BFRPGsheet.html
I've learned I did the HP fields wrong with respect to using them with tokens, and that this is the correct way.
=> Basic Fantasy RPG: Fixed hp and hp_max so token mapping will work.

Pathfinder-Neceros/pathfinder-neceros.html
Expression module update - Chris
=> Pathfinder - Neceros

Pathfinder-Neceros/pathfinder-neceros.html
- npc-hp max formula fix to match stat block computations
=> Pathfinder - npc-hp max fix

D&D_3-5-fr/feuilledeperso.html
Test to try fixing Sag and For
=> Fix for D&D 3.5 fr

Pathfinder-Neceros/pathfinder-neceros.html
=> Pathfinder fix fly and acrobatics

Pathfinder-Neceros/pathfinder-neceros.html
- changed value="" to value="0" for attributes outside of <select>
- small formatting change
- hide wound threshold(unchained ruleset)by default
=> Pathfinder

Pathfinder-Neceros/pathfinder-neceros.html
updated vince's code tonight with:
1. fix to macro evaulation code
2. set some default values from 0 to ""
3. updated max skill calculation if person is using consolidated skills.
=> Pathfinder fixes

Shadow of the Demon Lord/shadow-of-the-demon-lord.html
1) Added the new ancestries and magic traditions from the new source
book.
2) Fixed the built-in rolls to correctly calculate boons and banes. Had
to use inline rolls to include negative values (banes) and applied the
keep method (k1).
=> Add Demon Lord Companion content and fix boons and banes

AEON-Aberrant/aberrant.html
=> Aberrant - wrapper fix

Song of Ice and Fire Roleplaying/SIFRP.html
Adding button, auto-calc fields
=> Adding Stuff

PokemonTabletopUnited/ptu.html
=> Le Bug-fix *sigh*

pathfinder_simple/pathfinder.html
corrected the names of repeating attributes.  I mistakenly renamed them
when doing the update for repeating sections.
=> Pathfinder - Simple

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html
fixes to total buff for new columns on row uncheck, speed up ability editing, fixed check on sheet open, added invis attack note
=> Pathfinder 0.17

Dark_Heresy_2ed/DarkHeresy2ed.html
Updated all rolls to include degrees of success.
=> Degrees of Success

CWOD-W20/W20.html
Including options for other breeds
=> Updating forms tab

Pathfinder-Neceros/pathfinder-neceros.html
=> Pathfinder .18 skill bugfix

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Added an option to use a new version of the sheet, which uses tabs to minimize scrolling, while still keeping the original sheet available.
=> Added Tabbed Sheet!

Dark_Heresy_2ed/DarkHeresy2ed.html
Made a mistake, and this is the fix for it
=> Reverting the Degrees of success modification

Adventure!/Adventure!.html
Fixed weapon buttons, added modifier to damage
=> Fixing Attack buttons

Pathfinder (Old)/pathfinder-old.html
- Corrected HP formula value to be included within "( )"
"((@{CON-mod} * @{level}) + @{total-hp})"
=> Pathfinder (old/legacy)  Corrected HP formula value to be included within "( )"

PortesMonstresTresors/ReadMe.md, PortesMonstresTresors/pmt.htm, PortesMonstresTresors/pmt.js, PortesMonstresTresors/sheet.json
=> Portes Monstres Trésors v3.1

Call_of_Cthulhu_7th_Ed_Chinese_Traditional/coc_7th_ed.html
The text is garbled,so i try to fix this problem.(Call of Cthulhu 7th Ed Chinese Traditional)
and thank you again.
=> The text is garbled,so i try to fix this.(COC7thCT

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Added a sheet helper that allows the use of a properly constructed JSON to update the sheet, thus allowing users to sync up the R20 sheet to external sheets.
=> Import Update

Ryuutama/Ryuutama.html
Adding new mechanics for the Navigator class and the Koneko Goblin sp…ecies from the holiday 2015 package. Also added weapon and armor capacity mechanics.
=> New Mechanics

Symbaroum/symbaroum.css, Symbaroum/symbaroum.html
=> Symbaroum major update

NWOD-Demon/NWOD-Demon.css
Added a bunch os tiny improvements, cleaned up health boxes, etc
=> Clean up and matching html

NWOD-Demon/NWOD-Demon.html
Added extra options for dice pools, combat automation, expanded exploits and embeds, added and extra tab, few other minor upgrades
=> Expanding dice pools, combat automation, etc.

AD&D_1E/1ESheet.html
- made text clickable for section/sub-section collapsible titles
- fixed spells/day for spell levels 1-9 not being unique attribute names
=> AD&D1e - minor update

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Made Features and Abilities hidable, so that they don't take up necessary space.
=> Hidable Features and Abilities

CWOD-W20/W20.html
Roll templates, attack and damage buttons, few minor updates
=> Roll templates, etc

Iron Kingdoms RPG/IKPRG.html
General update, including roll templates for NPC attacks, Virtuoso checkboxs, collapsing weapons, and the derived attributes on every page
=> Iron Kingdoms Update

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Added a radio input to toggle targeting functionality in sheet rolls
=> Added Targeted Mode

Call_of_Cthulhu_7th_Ed_French/Readme.md, Call_of_Cthulhu_7th_Ed_French/coc_7th_ed.css, Call_of_Cthulhu_7th_Ed_French/coc_7th_ed.html
I'm adding this with the approval of the [sheet author](https://app.roll20.net/users/1190203/pierre-d).
=> Small additions to the french sheet for Cthulhu (7e)

Iron Kingdoms RPG/IKPRG.css
General cleaning; sheet is a direct copy of what I use in my games, and it works.  If something is broken in this one, I will do an line by line search for the issue.
=> IKRPG Update

Iron Kingdoms RPG/IKPRG.html
General Cleaning, moving derived attributes
=> Update to IKRPG

Runequest_6_FR/Runequest_6_FR.html
The finalisation of the French Character Sheet for RuneQuest6.
=> RuneQuest6 : Fix Finale French Character Sheet

fate_core_with_rolls/fate_core_with_rolls.css, fate_core_with_rolls/fate_core_with_rolls.html, fate_core_with_rolls/sheet.json
Add of feature : line by line array of skills or keep the previous fixed array
of skills
=> Update for Fate core with roll

Fantasy_Craft/README.md, Fantasy_Craft/fantasycraft.html
Fixed some attribute names (added or made unique)
changed ranged attack bonus from STR to DEX
=> Attribute name corrections

Song of Ice and Fire Roleplaying/SIFRP.html
Added misc mod fields to Composure, Health, and Intrigue Defense
=> Update to Song of Fire and Ice

Dungeon-slayers-4/DS4EN.html
Signed-off-by: GuiGnomeDev <guigui.cabuz@gmail.com>
=> Various fixes (added names to attributes)

CthulhuTech_1ed/CthulhuTech_1_ed.html
changing the Reflex calc from "/2" to "/3"
=> Fixing Reflex

WFRP-2nd-Ed/WFRP-2nd-Ed.html
Fixed concealment rolling as Charm
=> WFRP Sheet

HollowEarthExpedition/Hollow-Earth-Expedition.html
=> Added missing name attribute for stun 

Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.css, Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.html, Star Wars FFG API-Compatible/FFG-SWRPG-Dice-Roller.js, Star Wars FFG API-Compatible/README.md, Star Wars FFG API-Compatible/sheet.json
Added Roll Templates to Dice Rolls
Also changed display of species/career/specializations.
=> Updated to FFG Star Wars RPG API-Compatible to 4.0.3.12

DnD_5e/DnD_5e.html
Fixing 2 minor issues - 
typo in charisma save roll name
error in show math roll option output for weapon attacks
=> Bugfix 5e community sheet v1.1.2

AD&D_1E/1ESheet.css, AD&D_1E/1ESheet.html
I asked Vince if he minded the addition and he said it was great. =D
=> AD&D 1E: Added optional colors to the header of the General Template

Der Eine Ring/sheet.html
logo links now to the file on raw.githubusercontent.com
=> Updated image-link

Star Marx/star marx.html
fix images path for STAR Marx sheet
=> fix images path for STAR Marx sheet

Star Wars Edge of the Empire/EotE.css, Star Wars Edge of the Empire/EotE.html, Star Wars Edge of the Empire/sheet.json
Updated charsheet with:
- Names changed to reflect the rulebook (attributes -> characteristics, coerce -> coercion etc.)
- Improved skill listing, ability to add custom skills.
- More space for notes in talent/weapon/armor sections.
- Extra note area at the bottom for misc. character notes.
=> Updating Edge of the Empire (Simple) character sheet.

Atomic Highway/Atomic Highway.html
General clean up and fixing the background
=> Clean up and matching css

Iron Kingdoms RPG/IKPRG.css
=> Massive IKRPG update

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.css, Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Neue Features
- Kulturen aus dem Aventurischen Boten 172 hinzugefügt
- Zustände aus dem Aventurischen Bestiarium hinzugefügt (ohne Berechnung)
- Aufrechterhaltende Liturgien Erschwernis ist nun eintragbar
- Zeremonien aus dem Grundregelwerk wurden hinzugefügt
Behobene Fehler
- Fehler bei der  Berechnung der Initiative im Kampfbogen behoben
- Doppelte Führung der Traditionen für Götterwirken behoben
- "Gebete und Gesten weglassen" bei Götterwirken aufgeteilt
- "Ort der Ruhe" war das FW etwas breiter wie die anderen Felder
- Schutz der Wehrlosen" wurde nicht angezeigt wenn angeklickt
- Berechnung des Gewichts im Inventartab wurde behoben (bisher ohne BE Anstieg bei Überlastung, folgt später aus auswählbare Optionalregel)
=> additions + bugfixes

Hero Games 6e/Hero Games 6e.html
Changed a strange dot into " &#8224; "
=> Hopefully fixing the dagger things

HollowEarthExpedition/Hollow-Earth-Expedition.html, HollowEarthExpedition/hex.css, HollowEarthExpedition/hex.scss
Minor optimization of CSS by extending a common input-cell class.
=> Try to get rid of leading garbage character in hex.css. 

Iron Kingdoms RPG/IKPRG.html
Fixed the issue with the spell attack  roll
=> IKRPG: Fixing spells

Iron Kingdoms RPG/IKPRG.css
Damage boxes for the IKRPG sheet disappeared; I have found new ones.
=> Fixing damage tracker IKRPG

Spycraft_2.0/spycraft2.html
Talent and Specialty are different, don't auto populate one with the other.
=> [Spycraft2.0] Unlink Specialty and Talent

Shadow of the Demon Lord/shadow-of-the-demon-lord.html, Shadow of the Demon Lord/sheet.json
Added DK Heinrich and myself as sheet authors in the sheet.json file.
Changed the Ancestry and Spell Tradition fields to be text fields instead of selects to allow for custom and future game changes. Previous values are preserved (although will look a little funny).
=> Add Authors, Change Select to Input for Future-Proofing

7th Sea/7th Sea.css
=> 7th Sea background fix

Pathfinder-Neceros/pathfinder-neceros.css
small Css fix can we get this in ASAP
=> Pathfinder .40 css file fix to spells so they don't overwrite

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html
fixed buffs missing, fixed shields applying to armor
=> Pathfinder .41 fix buffs and shields

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html
fixed armor (again)
update weight to allow floats and only round at end
fix all spells tab
=> Pathfinder .42 more tiny fixes to recent release

D6StarWars/D6StarWars.html
Added weapons section with Name, Damage Dice, Ranges, Rate of Fire,
Ammo, and Roll Damage button.
=> Star Wars d6 added Weapons

Vampire the Requiem/Vampire the Requiem.css
Updated link to background image
=> VtR: replacing backgrounds

Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.css, Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.html, Star Wars FFG API-Compatible/sheet.json
=New Features:=
- 4.0.4.6 - Added Version info and Recent Changes list.<br />
=Bug Fixes:=
- 4.0.4.5 - Fixed an auto-calculation error that effected skill down-down lists.
- 4.0.4.6 - Fixed species display for Dressellian. & - Fixed an auto-calculation error that effected skill down-down lists (again).
=> Updated to Version 4.0.4.6

CWOD-M20/M20.css, CWOD-M20/M20.html
Corrected attr "bi4" to "Abi4" with sheetworker
Added damage and soak buttons.  Put a copy of all buttons at the top of the sheet and a pulldown to select if rolls will be public or whispered.
=> attr correction, added roll template and more buttons

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html
REALLY the final, everything working with correct versions merged.
Fixes to skills, bonus spells
=> Pathfinder v0.43 

CWOD-W20/W20.css
=> W20 background fix

Dark_Heresy_2ed/DarkHeresy2ed.html
Removed a layout mistake that resulted from previous update.
=> Dark Heresy 2ed layout mistake

CWOD-Changeling/CWOD-Changeling.css
=> Changeling: Fixing Background and Rolltemplates

Adventure!/Adventure!.css
=> Adventure! Background Update

Scion/Scion.css
Updating image links for background fix
=> Scion: Background Fix

NWOD-Werewolf/NWOD-Werewolf.css
=> WtF Background FIx

CWOD-M20/M20.html
Attr 'corresondence' to 'correspondence' with sheetworker
lower DP1 roll missing closing bracket
science and politics swapped
=> more fixes

Nightshade Academy/nightshade.css, Nightshade Academy/nightshade.html
Fix issue where new skills UI is unusable. Adds a Stress track section similar to the Fate sheet's, and changes the Backlash section to be a Consequences section similar to the Fate sheet's.
=> Nightshade Academy - Fix new skills UI, add stress, change Backlash to Consequences

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.css, Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
- Reworked section "Sonderfertigkeiten" to give better overview of what
is currently active
- Added Berufsgeheimnisse (Regelwerk, Bestiarium, Meisterschirm)
- Added support in combat section for "Hass auf..." and Drachentöter
- cosmetic changes in magic section
=> Sonderfertigkeiten (Cosmetic changes, added Geländekunde, Berufsgeheimnisse) and misc.

DnD_5e/DnD_5e.html, DnD_5e/ReadMe.md
Permits the default roll style to be set sheet-wide, while allowing individual rolls to be configured.
=> Add default roll options panel

DnD_5e/DnD_5e.html
Removing whitespace that caused the roll options feature to not work as expected
=> Fixing bug with recently introduced default roll option

d20 Modern/d20 Modern.html
Correcting reflex emote, added grapple check
=> d20 Modern Minor Fix

Tri-Stat/Tri-Stat.html
fixing DSV, ACV, and a few minor updates
=> Tri-Stat repair

Der Eine Ring/sheet.html
fixed alignment and header-style
=> minor layout changes for adversary and LM-character sheets

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Corrected typo in the backgrounds. Added improved setting support for
Interface Zero 2.0 (Money can be Credits, and Max Fatigue can be
increased to 3)
=> Corrections and New Setting Support

Fate_Core/fate.css, Fate_Core/fate.html
Make sure skill boxes are wide enough for all core skills. If not, widen
them.
Add skills from -2 to +8.
Add roll buttons for skills.
Add roll modifiers for skill rolls.
=> Small additions to skill boxes

Der Eine Ring/sheet.html
now also opponents and lm-characters can have a mount and roll for a
charge in combat
=> added mounts also for adversaries and lm-characters

Fate_Accelerated_No_Approaches/FAE_No_Approaches.json
Fate Accelerated Character Sheet with Aspects replacing Approaches in addition to standard Approach usage. Adding missing json file.
=> FAE_No_Approaches.json

Vampire the Requiem/Vampire the Requiem.html
This appears to fix the saving issue...
=> VtR: slight clean up?

Warhammer_v2_french/Warhammer_v2_french.css, Warhammer_v2_french/Warhammer_v2_french.html, Warhammer_v2_french/sheet.json
Added repeating sections for weapons and advanced skills. Near all the
sheet now have automated rolls with a custom roll template, except
initiative. Just add the total DMG bonus for weapons, the macro already
consider the 1D10 in the attack roll.
=> Warhammer v2 french

Fate_Accelerated_No_Approaches/FAE_No_Approaches.html
=> FAE_No_Approaches.html

Dark_Heresy_2ed/DarkHeresy2ed.html
Removed duplicate conditions entries.
=> DH2ed Conditions duplicity 2

CWOD-M20/M20.html
Dice button didn't prompt for difficulty
=> Fix Dice button

Warhammer_v2_french/Warhammer_v2_french.html
Added coin purse and corrected roll template so that a roll equal to a skill will correctly trigger a succes.
=> Added coin purse and corrected roll template

Runequest_6_ES/Runequest_6_ES.html
Unarmed style on "combat" is now editable.
Added minor aestetical fixes.
=> Spanish RuneQuest6 translation - minor fixes

Song of Ice and Fire Roleplaying/SIFRP.html
Added specialization fields and added keep/drop to rolls
=> Song of Fire and Ice Update

Song of Ice and Fire Roleplaying/SIFRP.css
=> Song of Fire and Ice Update css

Rogue_Trader_fr/RogueTrader-fr.html
=> Rogue trader fr starship sheet

Lames du Cardinal/ldc.html, Reve de Dragon - french/RDD.html, Warhammer_v2_french/Warhammer_v2_french.html
Made corrections like missing default value, attribute name duplication and so.
=> Minor corrections

13th_Age-neovatar/13th_Age-neovatar.css, 13th_Age-neovatar/13th_Age-neovatar.html, 13th_Age-neovatar/README.md, 13th_Age-neovatar/package.json, 13th_Age-neovatar/sheet.json, 13th_Age-neovatar/src/13th_Age-neovatar.html
* Repeating section items now can be dragged to macro quick bar
* Removed HP-lvlmod from sheet and autocalc hp_max with worker (fixes issues with HP recalc and tokens)
* Additional to STR and DEX also INT, WIS and CHA may be used as ability mods for basic attacks
=> Updates "13th Age Legacy" sheet

d20 Modern/d20 Modern.html
=> d20 Modern

D&D_3-5-CN/charsheet_3-5.html
=> DND3.5 Chinese

Song of Ice and Fire Roleplaying/SIFRP.html
=> Song of Ice and Fire update

Mongoose_Traveller/MongooseTraveller.css
=> Traveler Robotics & Psi

AW/style.css
Updated CSS to encompass new classes.
=> Update CSS to support new classes.

AW/apocalypse-world.html
Updated HTML to include optional 1E classes.
=> Update to include new optional classes.

SavageWorlds/SavageWorlds.html
Corrected the extra d6 damage roll for Raises to explode.
=> Raise Damage Fixed

Castles&Crusades/C&C.html
This adds a repeating inventory input section on the character sheet.
=> Add Inventory Section

Dark_Heresy_2ed/DarkHeresy2ed.html
Added repeating field to lore area
=> Update Dark Heresy 2ed

d20 Modern/d20 Modern.css
Changed the number box to only act like number boxes when you hover the mouse over them.
=> d20 Modern Critical Clean Up

Mongoose_Traveller/MongooseTraveller.html
Cleaned up/improve robotic area
=> Mongoose Traveller Robot Update

Mongoose_Traveller/MongooseTraveller.css
=> Mongoose Traveller Robot Update Css

d20 Modern/d20 Modern.html
Added an asterisk for skills that require training to be used.
=> Added Indication for untrained skills

Dungeons the Dragoning 40000 7th Edition/DtD.html
this has been bugging me since roughly the moment I actually read the word on the sheet, and Pyro hasn't bothered to fix it yet.
=> fix spelling of a word

CWOD-M20/M20.html
They had the same reference and the input-text was the same
=> Fixed Strength & Streetwise values

Fragged-Empire/Fragged_Empire.html
There was a problem with the checkboxes not working properly and they were remade according to roll20's specs.
=> Corrected checkcboxes' declarations

D&D_3-5/charsheet_3-5.html
To allow easy conversion from lbs to kgs or stone or any other desired weight unit on calculated load weights.
=> D&D3.5:  Add scaling factor and setup for custom weight units

Tri-Stat/Tri-Stat.html
=> Tri- Stat Mild Fixes

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html, Pathfinder-Neceros/translation.json
fixes description updates to spells
may fix tabs
=> Pathfinder .55 description and tab fix

Digital Shades/sheet.css, Digital Shades/sheet.html
*fixed all the rolls formulas with appropriate skill names (had forgotten the _  )
=> digital shades: html: fixed roll formula

Low Fantasy Gaming/BDnDSheet.html
Making LFG icon small and inserting date of sheet 12 July 2016
=> LFG sheet update

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.htm, ChroniquesGalactiques/sheet.json, ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
New repeating section for custom rolls.
=> Chroniques Oubliées Fantasy v1.5 / Chroniques Galactiques v1.1

Lotfp/Lotfp.html
Small fix; rolls were leaving stray } after results.
=> Remove unmatched braces from LotFP sheet rolls

d20 Modern/d20 Modern.html
renamed current hit points to "attr_HitPoints_max"
=> d20 Modern: Renaming current Hit Points

Shadowrun5e-Gerdofal/Shadowrun5e-Gerdofal.html
Added &{tracker} to initiative rolls so that the rolls will automatically add the selected token to the turn order when rolling initiative.
=> Added &{tracker} to the initiative rolls

Iron Kingdoms RPG/IKPRG.html
- fix attribute name for Cygnaran language checkbox
- fix attribute name for third advancement point text box
- escape ampersands
- fix textarea elements that were written with self-closing tags
=> Iron Kingdoms RPG - bug fixes

Exalted 3/Ex3-Sheet.html
Added -3 wound penalty option, as the Pain Tolerance merit changes -4 wound penalties to -3.
=> Small addition to Exalted 3rd Edition

New World of Darkness Official/NWoD_Official.html
* Changed chance dice roll to highlight 10s as successes.
* Added missing semi-colons causing JS errors.
* Explicitly declared JS variables in sheet workers.
* Changed some hard-to-read variable names to camel case.
=> Changes to official New World of Darkness Official sheets

Stars_Without_Number/Stars_Without_Number.css
Changes the scale of items in the Weapon fieldset to reflect new drop down boxes etc.
=> MG: Update for Version 0.1.1

SavageWorldsFrench/ReadMe.md, SavageWorldsFrench/sawofr.html, SavageWorldsFrench/sheet.json
New misc notes field + new untrained skill roll + better power chat
description.
=> Savage Worlds French v1.6

Blades-in-the-Dark/README.md, Blades-in-the-Dark/blades.css, Blades-in-the-Dark/blades.html
Added Cohort Name and Type drop down
Wrapped 8 clocks on 4 ticks
Moved claims checkbox to left side of the text area to mirror what's provided by the book
Bugfixes
- Fixed Claims map wrapping issue
- Fixed blank vice roll if Vice text box is blank
=> [Blades in the Dark] Bugfixes and some small features

Haunted-House_Spanish/HH_spanish.css, Haunted-House_Spanish/HH_spanish.html, Haunted-House_Spanish/readme.md, Haunted-House_Spanish/sheet.json
Added a new game: Haunted House by Proyecto Arcadia.
=> Haunted House (Spanish)

Pathfinder-Neceros/pathfinder-neceros.html
quick fix skill and defense lines, submitted a slightly out of date file a few lines different than latest
=> Pathfinder .61

SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Updated the Sheet Worker to calculates encumbrance penalty.
=> Encumbrance issue fix

Dark_Heresy_French/DarkHeresyFrench.html
=> Add "Bonus" Col for skills, allow to set a semi-perma roll modifier

Mekton Z/Mekton Zeta.html
=> Mecha Z fix

PokemonTabletopUnited/ptu.css, PokemonTabletopUnited/ptu.html
Added field for Status Conditions, as well as new roll template functionality, for use in macros/API scripts.
=> Added Statuses

d20 Modern/d20 Modern.html
Swapped Hit Point names
Added tracker to initiative 
Added titles to several combat attributes
=> d20 Modern Update

Fate_Accelerated/fate.css, Fate_Accelerated/fate.html, Fate_Accelerated/sheet.jon
*html + css: I added a button to theme transform the sheet to fallout edition. 
Check the box and the original sheet is hidden while the fallout edition sheet is unhidden.
*json: updated the info to mention the change
=> fate accelerated: html css json updates

Rogue_Trader/RogueTrader.html, Rogue_Trader/RogueTraderStyle.css
Code is directly copied (with translation) from Rogue_Trader_fr. HTML has been beautified and unclosed tags corrected
=> Added ship sheet from french edition

DungeonWorldFrench/ReadMe.md, DungeonWorldFrench/dwfr.css, DungeonWorldFrench/dwfr.htm, DungeonWorldFrench/sheet.json
Update for the 2nd french edition of Dungeon World. Totally compatible
with 1st edition.
=> DW french v3.0 for 2nd edition

Deathwatch/Deathwatch.html
evaluate skill is set to int
Strength upgrade applies to melee damage.
=> Deathwatch minor fix

AD&D_1E/1ESheet.html
- fixed bend bars/lift gates to fail if rolled above the given value
- updated TAS to latest version
=> AD&D  1e minor update

PokemonTabletopUnited/ptu.html
Added More Edge and Ability Support, Improved DB Calc
=> Large-ish update

Unknown Armies 3e/UnknownArmies3e.css, Unknown Armies 3e/UnknownArmies3e.html, Unknown Armies 3e/sheet.json
Everything should be fixed now.
=> Fixing the layout and some other, minor things

AD&D 2E Revised/2ESheet.html, AD&D 2E Revised/2EStyle.css
Updated certain repeating fields and formatting sheet wide.
=> Project462-Patch-1-edit

Hc Svnt Dracones/Hc Svnt Dracones.css
=> Hc Svnt Dracones, Host of fixes

Tri-Stat/Tri-Stat.css
=> Tri-Stat Update

Ars_Magica_5th/Ars_Magica_5th.html
Adding roll buttons for spells
=> Spell buttons

Ars_Magica_5th/Ars_Magica_5th.css
=> Adding Spell buttons

Unknown Armies 3e/UnknownArmies3e.css, Unknown Armies 3e/UnknownArmies3e.html
Re-submitting, hopefully without merge conflicts this time.
=> Fixing the layout

PokemonTabletopUnited/ptu.css
Forgot to update the CSS with the last HTML update.
=> CSS Update

LeaguesOfAdventures-fr/LoA-fr.html
Minor string translation fixes :)
=> LoA-fr : Translation fixes

DnD_5e_Chinese_Traditional/DnD_5ecn.html, DungeonWorldChinese/DungeonWorld.html
Fixed a bug that produces lots of error messages when rolling a dice. Probably from a deprecated version of character sheet. Now it should work just fine.
Fixed some skill names.
Fixed some translations to be more accurate.
=> D&D 5e Chinese bug fixes & Dungeon World Chinese name fixes

Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.html
Damage is now number rolled times multiplier (and strength, if checked), instead multiplier worth of dice rolled
=> All Flesh Must Be Eaten- Damage Fix

Stars_Without_Number/Stars_Without_Number.html
To permit the use of macros where a roll LESS than the target is a
success. Based off save template.
=> Added Morale RollTemplate

Warhammer_v2_french/Warhammer_v2_french.css, Warhammer_v2_french/Warhammer_v2_french.html
1) corrected distance damage roll bug.
2) modified critical rolls so that confirmation rolls are displayed. No
more confusion !
3) corrected critical damages that were using wrong values.
3) Unlocked Movement data for careers that upgrade movement.
4) added a magic tab.
=> Warhammer v2 french update

StraightToVHS/straighttovhs.css, StraightToVHS/straighttovhs.html
Added character names to Roll Templates, also added "Generic Roll" button to
sheet.
=> Added Names to Roll Templates

Stars_Without_Number/Stars_Without_Number.css
CSS elements for the Morale Template
=> Morale CSS

DFRPG/DFRPG.css, DFRPG/DFRPG.html
* Fixed error with Trajan Pro font not being used in some places
* Reduced font size across the board to account for Trajan Pro font
being used
* Adjusted tab locations to account for Trajan Pro font
* Added finer adjustments to the "Phase N" text on the character
worksheet
* Added lang-es styles for Fate Points overlay, tab positions, "Phase N"
text positions, and consequence types
=> Update to accomodate ES translation by Zexar z

Pathfinder_Cazra/pug/core/baseAttack.pug, Pathfinder_Cazra/pug/fields.pug, Pathfinder_Cazra/pug/magic/index.pug, Pathfinder_Cazra/pug/specialFeats/index.pug, Pathfinder_Cazra/sheet.html
Also added Favored class options area.
=> Pathfinder (Cazra) Fixed attack roll button

StraightToVHS/straighttovhs.css, StraightToVHS/straighttovhs.html
Will make old version of this sheet's roll templates unviewable. I don't think the sheet is widely used at the moment though.
If that is an issue I can go back and add some backwards compatability.
=> Fix for dice sometimes not showing up if the result is 0 or less.

Reve de Dragon - french/RDD.html, Warhammer_v2_french/Warhammer_v2_french.html
Warhammer 2
#1 modified html code to correct a bug in the tabs.
#2 modified spells tab to optimize column sizes.
RDD
#1 added Medecine in the archetype tab
#2 added missing attribute names in some case
#3 added missing data in the 2nd tab
#4 switched encumbrace data from numbers to text to allow decimal
numbers.
#5 switched armor data from number to text to allow armor description.
=> Warhammer 2 french and RDD french updates

Vampire the Requiem/Vampire the Requiem.css
replaced images used in open and lethal damage areas.
=> Vampire the Requiem: health boxes

Terra-X/ReadMe.md, Terra-X/sheet.json, Terra-X/terrax.htm
=> Terra-X v1.1 : attack bug correction

Impulse_Drive/Impulse Drive.html
October Update
Updated character sheet and ship sheet to reflect rules changes in Impulse Drive version 3.0
=> Update to 3.0 101816

Iron Kingdoms RPG/IKPRG.css
=> IK RPG Update

Iron Kingdoms RPG/IKPRG.html
Update to IKRPG
Condensed Character, Warbeast, and 'jack to a single page
Added transformation area for tharn and warp born, etc.
Added boosted rolls
Upgraded roll templates 
Other minor changes
=> IK RPG Massive Update

Reve de Dragon - french/RDD.css, Warhammer_v2_french/Warhammer_v2_french.html
switches to Spells).
intended.
=> RDD and Warhammer 2 - french  - update

Knight/knight.css, Knight/knight.html
- Various Small Bugfix
- Improve use effect of weapon
=> Modification of Knight

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Added a small warning and a link to the header of the charsheet warning the user about future updates and that the next version will change a lot of things. Doing this to give the users a heads up what to expect and what internal things will change in the next update which is scheduled for release within the next 2 weeks since I've implemented tons of new features, fixed dozens of bugs and changed some internal problems resulting in the user losing a few saved valuables. To minimize the damage - even if it only concerns some rarely used variables - this warning also reminds users to keep their chars saved offline.
=> DSA 5 - German Charsheet

Shadows of Esteren/ShadowsOfEsteren.html
Major: 'Easy' difficulty step was set to low!
Minor: Logo image was missing
=> Fix issues in Shadows of Esteren character sheet

Pathfinder-Neceros/pathfinder-neceros.html, Pathfinder-Neceros/translation.json
Fix for setting ability mod to -5 when ability score is 1. Was setting to -4.
This should go in even though i have the bug report open since the bug is already in prod anyway, this only changes one small thing that doesn't relate.
=> Pathfinder v.70 1 line update

Impulse_Drive/Impulse Drive.html, Impulse_Drive/Impulse_Drive.css
Especially targeting the Gear section.
=> Reduce some of the vertical whitespace on the Impulse Drive sheet.

DungeonWorldFrench/ReadMe.md, DungeonWorldFrench/dwfr.css, DungeonWorldFrench/dwfr.htm, DungeonWorldFrench/sheet.json
=> Dungeon World French v3.1b

Naruto d20 Modern/Naruto d20 Modern.html
- Fixed issue with repeating fields in Techniques sections
=> Update 11/22/2016 #2

AD&D 2E Revised/2ESheet.html
Platinum values and Currency weights now read correctly
=> Fixed Currency Discrepancy

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
Fixed an error where if fortitude hadn't been adjusted yet, presence
would add 20 at a time instead of 2 to HP.
=> Open Legend: Presence rare error with HP calc

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html
Fix to skill total when negative int modifier and multiclassed
Remove survey from footer
Add 'do not show again' so people see they can collapse announcements
=> Pathfinder v.73

Das_Schwarze_Auge_4-1/sheet.json
Removed an errant roll20userid
=> JSON Update

Barbarians Of Lemuria - Mythic/ReadMe.md, Barbarians Of Lemuria - Mythic/bolm.htm, Barbarians Of Lemuria - Mythic/sheet.json
* Bug fix: Agility penalty due to Armour and/or Shield was not applied
to attack rolls using Agility (Melee or Ranged)
* Bug fix: Damage rolls using Half Strength were not properly calculated
with negative Strength
=> Barbarians of Lemuria v1.1

Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
=> Open Legend: Supernatural to Extraordinary

Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
Fixed Workerscript to take into account a null value.
Only  happened on pre-existing actions, not newly creatred ones.
Also added min/max power level to other actions.
=> Open Legend: Error in Workerscript if Null value

Only War/Only War.html, Only War/sheet.json
I'm requesting approval to update the Only War character sheet html with a number of improvements, corrections and new functionalities.
=> Requested updates to Only War character sheets.

Pendragon/Pendragon.html
@{squire_name} added to the squire skills.
Lines: 566-590
Added a roll button for end of round concern rolls
Lines: 803-804
Concern and Hate of landlord reworked. Love added to counter hate when below 0.
Lines: 802-808
Knight entry added for easier access to Stewardship skill
Lines: 811-820
Steward entry added.
Line: 824-848
Land Record Sheet updated to look close to the real one.
Line: 854
Manor Income Worksheet updated to look close to the real one.
Line: 900
Added Misfortune opposed roll to Manor Income Worksheet
Line: 949-950
=> [Pendragon] Squire Tracking and Manor Tab Overhaul

Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Updated for new calculation of evasion, and evasion's name changed to
Resilience
- Resilience = 10 + Agility + Might + Armor + Other
=> Open Legend: New Evasion => Resilience & Calculation

Ars_Magica_5th/Ars_Magica_5th.html
=> Ars Magicka Update

Tephra/Tephra.css
=> Tephra update

Warhammer-Fantasy-Roleplay-2nd-Edition/WHFRP2.html
Ulric's Fury achieved with Ability Command Buttons.
=> Update January 2017

Mongoose_Traveller/MongooseTraveller.css, Mongoose_Traveller/MongooseTraveller.html, Mongoose_Traveller/sheet.json
Mostly affects Skills and Weapons
Added Boon and Bane Die to rolls potentially affected by it.
=> Mongoose Traveller 2nd Edition Update

Stars_Without_Number/Stars_Without_Number.html
As per Discussion in https://app.roll20.net/forum/post/4462699/stars-without-number-very-odd-roll-details/?pageforid=4462699
=> Stars Without Number: Hide Attribute Formula

AD&D_1E/1ESheet.html
- fix to allow fractional data for total weight and costs.
=> AD&D1e patch

Ars_Magica_5th/Ars_Magica_5th.html
Added Puissant to all attributes
=> Ars Magicka, ability fix

Only War/Only War.html
Numerous formatting corrections.
Focus power test now can roll using psyniscience, willpower or pereception based on dropdown.
=> Only War Update E

Stars_Without_Number/Stars_Without_Number.html
=> Stars Without Number: Attack Labels

Impulse_Drive/Impulse Drive.html, Impulse_Drive/Impulse_Drive.css
Just a little cleanup and updating to make the Impulse Drive sheet work a bit better for the latest version of the rules.
=> Impulse drive shipdamage

GURPS/gurps.css, GURPS/gurps.html
Several improvements and additions to the existing GURPS Sheet.
=> GURPS (Style 1) - Added helper script for inventory totals and Grimoire page

L5R/L5Rsheet.htm
Iaijutsu added in weapons and notes fixed to not be the same.
=> Iaijutsu and Note fix

Vampire the Requiem/Vampire the Requiem.css
Removed the need to link images for the health boxes.
=> VtR: removing need to healthbox images

AD&D 2E Revised/2ESheet.html
Fixed naming error in monster damage section.
=> Fixed Damage reference error

Symbaroum/symbaroum.html
- bug fix: updated burden attribute names
=> Symbaroum - fix for burdens

L5R/L5Rsheet.htm
Added fields for Macro-Skills
Double Affinities added
Insight bonuses added for Courtier and Etiquette under its box.
=> [L5R] Fixes and Improvements

Dark_Heresy_2ed/DarkHeresy2edStyle.css
Fixed button size for new changes.
=> Small fix.

CWOD-W20/W20.css
To match host of upgrades in html
=> W20 Update

Stars_Without_Number/ReadMe.md, Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html
=> SWN: Added power to ship weapons

Titansgrave/README.md.txt, Titansgrave/Titansgrave.html
This update makes it possible it grabs spell TN numbers from an inlineroll so that the TotalRoll API can tell the user if the spell TN has been reached. If the API isn't used the character doesn't appear to change for the end user.
=> Titansgrave Character Update

Dark_Heresy_2ed/DarkHeresy2ed.html
Added Pages.
Added Vehicle section.
Added Minion Section.
Separated Gear to its own page.
Separated Advancements and exp to there own page.
Separated Psyker powers to its own page.
Added Journal Section.
Moved Unnatural Characteristics to the inside of characteristic box.
Changed special abilities to text box.
Added initiative macros.
Added Other skills below skills.
Lots of other small fixes.
Fixed macros to use dh2 core rules instead of OW core rules.
Modified by Craftomega and Messiahcide.
=> Added Pages

Agone-(french)/sheet.json
=> Logo's author

CthulhuTech_1ed/CthulhuTech_1_ed.css
Sheet workers and pick and choose skills
=> C-tech update: to match HTML

AD&D_2E/2ESheet.html, AD&D_2E/2EStyle.css, AD&D_2E/sheet.json
This adds several cleanly styled templates to augment game mechanic resolution with minimal fuss as well as provide additional functionality for players and gm's alike to take advantage of.
=> Add 2E Sheet rolltemplates

CWOD-W20/W20.html
=> w20 Update, with Initiative buttons

CWOD-W20/W20.css
=> w20 css update

Mongoose_Traveller/MongooseTraveller.html
Host of improvements, including a lot of sheet workers, pick and choose skills, etc.
=> Mongoose Traveller 1E Update

Mongoose_Traveller/MongooseTraveller.css
=> Mongoose Traveller Css update

L5R/L5Rsheet_en.htm
Last L5Rsheet.htm with data-i18n for translation
=> Rename L5Rsheet.htm to L5Rsheet_en.htm

Impulse_Drive/Impulse Drive.html
For tracking hold on moves that grant it.
=> add Hold box to moves fieldsets

Pendragon/Pendragon.html
Both needed chirurgery and the skill gets checked. Now they get checked seperatly.
Improvement to the automated manor tab. Now zeroes are added to value so it updated correctly.
=> [Pendragon] Chirurgery fix and manor improvement

Pathfinder-Neceros/pathfinder-neceros.html, Pathfinder-Neceros/sheet.json, Pathfinder-Neceros/translation.json
updated sheet.json with some default values, additional translation values
=> Pathfinder .74 default values

BESM-3e/.gitignore, BESM-3e/besm3e.css, BESM-3e/besm3e.html, BESM-3e/besm3e.json
Created character sheet for Big Eyes Small Mouth (BESM) 3rd Edition
=> Created character sheet for Big Eyes Small Mouth (BESM) 3rd Edition

Pendragon/Pendragon.html
Added a selection box if the weapon gets an extra 1d6, or if its a Dagger/Javelin and use 1 or 2 dice less respectively.
Updated Chivalry if a female  is used and other minor improvements.
=> [Pendragon] Dice Modifier Weapons - Chivalry Update

PokemonTabletopUnited/ptu.html
Added a hidden attribute that lists the row ids of repeating moves in a JSON string, mostly for access by the API.
=> Added Repeating Moves List

Sagas_Of_The_Icelanders/soti.html
Relationship and Moves repeating skill no longer linked.
=> [Saga of the Icelanders] Linked repeating skill fixed

GURPS/README.md, GURPS/gurps.html
Fixed various issues with calculations and updated the initilization script to set up values when a sheet is first opened. This uses a new attribute added to characters "sheet_version" which is currently checked for and set to "1.3".
=> [GURPS] Fixes for issues #2323, #2324, #2335

Pathfinder-Neceros/pathfinder-neceros.html
announcing sheet updates next week
=> Pathfinder announcement for sheet updates

Stars_Without_Number/ReadMe.md, Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html
=> SWN: Attribute mods auto-calculated by sheet workers

Dark_Heresy_2ed/DarkHeresy2ed.html
Sheet is not properly taking modifiers into account when rolling for Willpower and Perception-based Focus Power tests. Attempted fix.
=> Attempt number 2 at fixing Focus Power Tests.

Shadow of the Demon Lord/shadow-of-the-demon-lord.html, Shadow of the Demon Lord/sheet.json, Shadow of the Demon Lord/style.css, Shadow of the Demon Lord/style.scss
Improved ease of use by merging Boons and Banes queries in a single one.
Improved weapons section by replacing unnecessary (complicated) fields to set damage for a single text field and by adding Boons/Banes field to weapons (some weapons/relics have fixed boons or banes).
Improved all rolls, replaced simple '/rolls' for 'default' template rolls.
Added Fortune Points tracker.
=> [Shadow of the Demon Lord] Improved overall ease of use and added Fortune Points tracker.

Basic Fantasy RPG - Expanded/Readme.md, Basic Fantasy RPG - Expanded/bfrpgsheet-expanded.html
Removed unneeded sheetworkers that was broken. Fixed some html codes also.
=> Fixed coding

Tales from the Loop/TFTL html.html
Added character_sheet attribute
=> Update TFTL html.html

PokemonTabletopUnited/ptu.html
Added character_sheet attr as per the request made by TheAaron
=> Added character_sheet attr

Shadowrun-Anarchy/Shadowrun-Anarchy.html
- Now persisting note fields for attributes.
- Increased text input size for qualities and plot directives.
=> Shadowrun-Anarchy

GURPS/README.md, GURPS/gurps.html, GURPS/sheet.json
This update should finally set all caculated stats to the default values. This fixes issues where new charactes look broken before changing values.
=> [GURPS] Updates to initialize new sheets.

Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css, Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
Mostly fixes for stuff I recently touched. The first commit fixes something I broke terribly. I already adapted my test environment to prevent such things in the future. No attribute name changes. Includes one very minor style change.
=> [DSA4.1] Fixes as of 2017-03-05

Shadow of the Demon Lord/shadow-of-the-demon-lord.html, Shadow of the Demon Lord/style.css, Shadow of the Demon Lord/style.scss
[Shadow of the Demon Lord] Fixed bug causing issues with the weapon and attributes section in the previous build.
=> [Shadow of the Demon Lord] *NEW* Talents page; *NEW* Languages field; *REVAMPED* Spells page; Bugfixes; Improved overall readability.

Urban_Shadows/sheet.html, Urban_Shadows/style.css
Two fields had an error where they would not save. They were missing the correct input type, adding that allowed them to save.
=> Urban_Shadows - Fixed error with Look and Demeanor not saving

Pathfinder-Neceros/pathfinder-neceros.html
fix for missing import statement
=> [Pathfinder] 1.18 tiny herolab fix

L5R/L5Rsheet.htm
Added a box for seperate points for Insight and fixed Acting rolls
=> [L5R] Input for Insight and fixed Acting roll

Fragged-Empire/Fragged_Empire.html
=> Updated Fragged Empire logo link

Dark_Heresy_2ed/DarkHeresy2ed.html
Fixed pykana casting on second repeating field.
=> [Dark Heresy 2]

AD&D 2E Revised/2ESheet.html
Fixed an error in the sheet worker script so that it works correctly now.
=> Auto-calc bug fix

Pendragon/Pendragon.html
Added Maintenance to Manor worksheet.
Fixed Automated Calculation.
=> [Pendragon] Minor manor improvement

Call_of_Cthulhu_DA/Call_of_Cthulhu_Dark_Ages.css, Call_of_Cthulhu_DA/Call_of_Cthulhu_Dark_Ages.html, Runequest3/Runequest3.css, Runequest3/Runequest3.html
Runequest 3 changed button display, fixed track check box, added parry checkbox, added newtling hit location
CoC DA fixed characteristic rolls
=> Runequest 3 and CoC Dark Ages updates

Anneau Unique/README.md, Anneau Unique/sheet.html, Anneau Unique/sheet.json
L'Anneau Unique (The One Ring French) version 1.3 : bug fix
=> L'Anneau Unique (The One Ring French) v1.3

Mutants and Masterminds 3E/mutants-and-masterminds.html
on line 244 
changed <span class="sheet-table-data"><input type="number" name="attr_toughness-points" title="toughness-points" disabled"/></span>
to <span class="sheet-table-data"><input type="number" name="attr_toughness-points" title="toughness-points" value="0"/></span>
this will allow the toughness to be edited in the defenses and allow it to roll
=> Fixed the toughness-points

Dark_Heresy_2ed/DarkHeresy2ed.html
Added ship section by request.
=> Dark Heresy 2nd

Dark_Heresy_2ed/DarkHeresy2edStyle.css
Needed changes for new section.
=> Dark Heresy 2 CSS

Pendragon/Pendragon.html
Added the Leader and Player's battle record.
Did minor changes to text boxes and fixed the background picture.
=> [Pendragon] Added battle record sheet and minor improvements.

Pendragon/Pendragon.css
Added buttons for tabs 7 and 8.
Fixed background picture.
=> [Pendragon] Tabs added and background readded.

AD&D 2E Revised/2ESheet.html, AD&D 2E Revised/sheet.json
Added autocalc script for gem values, added comeliness, added bardic identify, removed rogue and psion follower class boxes, and fixed hundred of title errors and references
=> Numerous fixes and changes

CWOD-Demon/Demon the Fallen.html
Changed images source link to the raw version of each image in the Roll20 repo.
=> Changed image path

Dark_Heresy_2ed/DarkHeresy2ed.html
Changed how psyker powers are cast to allow for each power to be customized.
=> [Dark Heresy 2nd]

L5R/L5Rsheet.htm
Removed / on bow 1 and 2 that broke rolls.
=> [L5R] Roll fix bow 1 and 2.

The Veil/TheVeil.css, The Veil/TheVeil.html, The Veil/dev/TheVeil.html
=> The Veil bugfix

Pendragon/Pendragon.css, Pendragon/Pendragon.html
The leader and player sheet made repeatable for looking back at older battles.
Made sheets use less space.
Added filled in sheets for NPCs.
Added the ability to hide the sheets.
Fixed background and title link.
=> [Pendragon] Leader / Player sheet repeatable and NPCs

Mekton Z/Mekton Zeta.html
Fixed the personal weapons rolls, added a roll template for them
=> Mekton Z personal weapon fix & Roll templates

Mekton Z/Mekton Zeta.css
=> Mekton Z rolltemplates

Anime Campaign/Anime_Campaign.html
Changed the sheet to replace drop boxes that wouldn't save with text
input.
=> Basic Edits

d20 Modern/d20 Modern.html
Navigate skill roll description was wrong. It was showing Listen skill, but it should be Navigate.
=> Update d20 Modern.html

MouseGuard/mouseguard.html
Just a small addition to give a space for keeping track of Wises
=> Added Wises

Infected!/infected.html
=> Infected! Formula correction

Monster of the Week/MotWHTML.html
3 gear options were numbered the same so they all selected together.
That has been corrected
=> Fixed Expert gear

Monster of the Week/MotWHTML.html
Had set min stat to -1 but Monsterous playbook can take a -2 stat. That
has now been corrected
=> Fixed min and max stats

Warhammer-Fantasy-Roleplay-2nd-Edition/WHFRP2.html
Faster application of Ulric's Fury
Addition of Critical Hit button
Addition of Blood Loss button
Addition of Channeling button on Spell Tab
=> Update April 2017

microluxe20/microluxe20.html
making the 'built for' version more broad (don't include patches), since there are no character sheet changes between patch versions.
=> [Microluxe20] version bumping

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Added in Extraordinary/Legendary Item section
* Fixed an issue where Advantage/Disadvantage to the d20 wasn't working
=> Open Legend: Added Legendary Item Section

AD&D 2E Revised/2ESheet.html, AD&D 2E Revised/2EStyle.css
Added optional Barbarian Movement block and Enabled default Skirmish combat compatible with AD&D 2E Birthright Rules.
=> Barbarian Movement and Skirmish Fighting

Stars_Without_Number/ReadMe.md, Stars_Without_Number/Stars_Without_Number.css, Stars_Without_Number/Stars_Without_Number.html, Stars_Without_Number/sheet.json
- Fix issue #2564 [SWN] Saving Throw Template UI Alignment Error
- Revamped and made consistent all roll templates for Saves, Weapon Attacks, Basic Attacks, Skills
- Initiative now using roll templates
- Removed unused Morale roll template
=> [SWN] 0.1.7 Roll template updates

Monster of the Week/MotWHTML.html
Found some attributes (gear etc) with the same values. This has been
fixed. Also tidied up some bits of code from where I previously moved
sections. Also added another custom advance improvement box for the
custom sheet.
Officially version 1 completed. (May add besic moves in version 2)
=> Code clean up and fixed some attribute numbers

Pendragon/Pendragon.css, Pendragon/Pendragon.html
Added missing code that broke new background image.
As well as new features.
=> [Pendragon]Fix missing code

L5R/L5Rsheet.htm
Reverted skill calculation as it broke initiative roll.
Made ranks show when opening the character sheet instead of being in modification mode.
=> [L5R] Skill calculation and Rank changes

Naruto d20 Modern/Naruto d20 Modern.html
-TX Roll button for Technqiues is now listed as Perform to help make
clear that its a button to be pressed.
-Chakra Resistances has been fixed, the mysterious 5 that kept appearing
has been vanquished.
-Training Technique section has been added below Taijutsu in the
Techniques section.
=> Naruto D20 Modern Update 5/1/2017

Mass Effect/sheet.json, WFRP2E-Havoc/README.md, WFRP2E-Havoc/sheet.json, WFRP2E-Havoc/splitArgs.js, WFRP2E-Havoc/wfrp2e-api.js, WFRP2E-Havoc/wfrp2e-sheet.css, WFRP2E-Havoc/wfrp2e-sheet.html, approved.yaml
Maintainers, I took a stab at the `approved.yaml`
This is an alternate API driven WFRP2e character sheet by Paul "Havoc" Stein (55273). Several forum members looked for this sheet to be added, and working with Paul, I obliged.
=> Paul 'Havoc' Stein alternate WFRP2E character sheet

Pendragon/Pendragon.html
=> [Pendragon] Damage fix

Fallout/Fallout 3.0.html
=> Fallout Fix

Naruto d20 Modern/Naruto d20 Modern.html
-Fixed an incorrect notice on Climb roll stating it was Bluff being rolled.
-Fixed Tumble skill from default selecting Str, changed to Dex.
=> Naruto Update 5/6/2017

Anima-Beyond-Fantasy/A-BF.css, Anima-Beyond-Fantasy/A-BF.html, Anima-Beyond-Fantasy/sheet.json
Changed Fumble Range default to 3 (Corrected value).
Fixed Roll buttons without icons not showing properly in Chrome.
Note: Do I need to update the files under /translations with the changes from the translation.json made with the last merge? They are missing for the current sheet on roll20.
=> A-BF: Corrected Fumble Range, Chrome Fix

Pathfinder_Cazra/js/worker.js, Pathfinder_Cazra/pug/index.pug, Pathfinder_Cazra/sheet.html, Pathfinder_Cazra/sheet.json
Widened XP field.
Compendium integration.
Added character_sheet attribute for Aaron's character sheet API integration script.
=> Pathfinder simple

Open Legend Basic by Great Moustache/Open Legend Homebrew.html, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Fixed an error that caused actions to not roll because of 'undefined'
- Caused by previous fix to Advantage/Disadvantage to the d20 in 1.8.0
* Added support for modifying the "Level" to calculate XP, Feat Points, and Attribute Points
- Previously it was only if you modified XP, now works for both
* If value higher than 9 or lower than 0 is entered for Attribute, changes it to 0 or 9 as needed
- Shouldn't be able to have values higher or lower than these
- If value of 10 needed for dice size, can be done via input field within attribute settings "Attribute Dice Bonus/Penalty
=> Open Legend: Fixed Actions Not rolling & More

Multiverse/Multiverse Sheet.html
Major changes to the Defenses, Weapon tab, Artisan and Knowledge skills, and Spells tab.
=> Multiverse Sheet.html

Brigandyne/ReadMe.md, Brigandyne/brigandyne.htm, Brigandyne/sheet.json
=> Brigandyne v1.2

AD&D 2E Revised/2ESheet.html
Fixed a known issue with Priest Spell Points automation.
=> Priest Spell Points tracker fixed

Open Legend Basic by Great Moustache/Open Legend Homebrew.html, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
Variable name needed updating for functions to act properly.
=> Open Legend: Minor Fix to Other Actions

Ironclaw/Ironclaw.html
=> Ironcalw, Fixing Image

WFRP2E-Havoc/wfrp2e-sheet.html
=> Corrected spelling

Tales from the Loop/TFTL html.html
Changed Build (tech) to Program (tech) to reflect the changes made in the official release.
=> Update TFTL Sheet

Pathfinder-Neceros/pathfinder-neceros.html
rolled back a few lines, i thought i rolled back before but i pasted wrong. just realized
=> [Pathfinder] emergency fix

TailsOfEquestria/js/worker.js, TailsOfEquestria/pug/index.pug, TailsOfEquestria/sheet.html
Tweaked exploding hoof roll expressions to be slightly faster.
=> Tails of Equestria v1.1.1

Shadowrun-Anarchy/Shadowrun-Anarchy.css, Shadowrun-Anarchy/Shadowrun-Anarchy.html
* Added (essence cost) heal penalty field.
* Changed various fields from number to text.
=> Minor changes based on feedback

5th Edition OGL by Roll20/translations/pt.json
It's just a small fix that makes the text have a little more sense for some people
=> Minor correction in translation

7th Sea/7th Sea.html
=> 7th Sea, Fixing Skills

Pathfinder-Neceros/pathfinder-neceros.html
Fix to melee damage buff not applying without hitting recalc
Fix to nonlethal hp resetting on level drain
Fix to @{size_display} stuck on medium
Fix to spell class calculations when spell class not set
Fixes to buffs writing NaN and undefined
=> [Pathfinder] v1.54

Black Hack/BlackHack.css, Black Hack/BlackHack.html, The Veil/TheVeil.html
Should be a clean repository this time. Freshly forked.
=> Minor changes to The Veil and the Black Hack

Pathfinder-Neceros/pathfinder-neceros.css, Pathfinder-Neceros/pathfinder-neceros.html, Pathfinder-Neceros/sheet.json
FIX SKILLS (again)
Fix ability damage multiplier on attack rows
Fix spells linked to attacks
Fix monster "plus x" damage parsing
Update NPC page ability list
Announcements hidden by default on new sheets
=> [Pathfinder] v.1.55

Monster of the Week/MotWHTML.html
Gear was pairing up when checked, now fixed
=> Fixed Professional Gear

Burning Wheel/Burning Wheel.html
Reverts Roll20/roll20-character-sheets#2656
=> Revert "[Burning Wheel] Reflexes and Mortalwound"

Path of Paper/path_of_paper.html
=> Minor bugfixes

Monster of the Week/MotWHTML.html
armour choice was missing, now added in
=> Added Professional armour choice

Monsterhearts-2/Monsterhearts-2.html
The expanding field within an expanding field was buggy. Remedied this by changing it to a single expanding field with fields for Strength, and up to 6 members.
=> Monsterhearts-2 : Changed Queen's Cliques.

Pendragon/Pendragon.html
Battle size modifier change to the correct ones.
=> [Pendragon] Battle size modifier fix

Symbaroum/sheet.json
=> Added proper author credit for Julian Draven

Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.html
Installing user adjusted background, fixing weapon #2
=> AFMBE Update

Unisystem-All Flesh Must Be Eaten/All Flesh Must Be Eaten.css
Added user selected background adjustment
=> AFMBE; Background update

Little-Fears-Nightmare-Edition/LittleFearsNightmareEdition.html
=> Little Fears

ICRPG (Warp Shell)/changelog.md, ICRPG (Warp Shell)/icrpg-warpshell.html, ICRPG (Warp Shell)/rcrpg-warpshell.css, ICRPG (Warp Shell)/sheet.json
This adds a fully functional ICRPG character sheet for the Warp Shell setting.
=> Add ICRPG - Warp Shell character sheet

tigres_volants/tivi.html
Somebody on the forums noticed that the sheet for Tigres Volants was displaying incorrectly. I believe this happened because the file was encoded with Windows Latin 1 instead of utf-8, this is an attempt to fix that.
=> Change tigres volants html to utf-8

CWOD-V20/V20.html
Fixed version of the V20.html supporting i18n.
After a first pull request i got noticed about two potential issues that i fixed.
This should be fine now.
I also created a new .json file to permit translations.
=> V20.html file formatted for i18n (fixed)

Zweihänder Grim & Perilous/Zweihander.html
Added a host of sheet workers and buttons
=> Zweihänder adding sheet workers and buttons

Zweihänder Grim & Perilous/Zweihander.css
=> Zweihänder update

Scion/Scion.html
Lots of improvements, sheet workers, roll templates, skills that roll
=> Scion, General Upgrdade

Scion/Scion.css
=> Scion, general update

Sword & Scoundrel/sheet.json
=> Sheet.json was added

Mass Effect/Mass Effect.html
=> Update Mass Effect.html

Shadowrun-Anarchy/Shadowrun-Anarchy.html
Added a basic roll template to the buttons to make the rolls look cleaner.
=> Updated to clean up chat window

Multiverse/Multiverse Sheet.html
Added "Maximum Skill Ranks" tab, along with changing the placement of the "Skill Focus" checkmarks and making it so they don't destroy the screen. The code around the Defenses has also been changed for stylistic purposes and ease of reading.
=> Update Multiverse Sheet.html

Scion/Scion.html
Added Join Battle, fixing armor and Defense values, added parry button to weapons
=> Scion, Fixes

Monster of the Week/MotWHTML.html
Icon header wasn't being hosted properly so removed it
=> Removed header

Adventures in Middle Earth/Adventures in Middle Earth.html
Really fix the script that manages "use as resource" inventory items given that I removed the default "other_resource" item from the sheet.
=> Really fix the resource/inventory issue this time

Cyberpunk 2020/Cyberpunk2020.html
Updated with sheet workers, some design stuff, etc.
=> Cyberpunk 2020 sheet workers

Cyberpunk 2020/Cyberpunk2020.css
=> Cyberpunk 2020 update

Iron Kingdoms RPG/IKPRG.css
=> IKRPG, Fix to health box images

Call_of_Cthulhu_Spanish/Call_of_Cthulhu.html
1. The sheet has broken image links, hopefully solved with the spanish version of it.
2. Also had problems with the dice buttons, retranslated the english version with those problems solved.
3. With the book in hand, added skills and changed others
4. Arranged the skills alphabetically while waiting for list ordering and adding i18n to the original one
=> Update Call_of_Cthulhu.html spanish

Pathfinder-Neceros/pathfinder-neceros.html
announce next release changes at top of sheet
=> [Pathfinder] Announcement

Deathwatch/Deathwatch.html, Deathwatch/sheet.json
due to missing parentheses only the skill bonus was halfed.
=> [Deathwatch] Fixed "half" skills

Delta Green/delta_green.css, Delta Green/delta_green.html
Simple but it works.  Anyone can feel free to make it look nicer.  For some reason the roll20 site doesn't respect the css I used to make the section headers with vertical transformations but otherwise it's serviceable.
=> Delta Green Character sheet.  CSS based on Call of Cthulhu 7ed CSS.

Scum - Villainy/scum.css, Scum - Villainy/scum.html
Added note to settings menu to make auto generation more intuitive.
Added default Factions to faction generation.
Styled factions page, (functioning, still in progress).
=> Updated Scum & Villainy sheets with faction status stylings

AD&D 2E Revised/2ESheet.html, AD&D 2E Revised/2EStyle.css
Added numerous sections, fixed several typos and bugs and did general maintenance.
=> AD&D 2E v2.7.63 Fixes, Additions, and Maintenance

Zweihänder Grim & Perilous/Zweihander.html
Activated 10 Basic Tier skill buttons missed the first time around.
=> Update3 Zweihander.html

Zweihänder Grim & Perilous/Zweihander.html
Fixed some buttons, added some modifier boxes, fixed some input fields.  Too numerous to list here.
=> Zweihandler, multiple fixes

Vampire the Requiem/Vampire the Requiem.css
removed the images in the amount of blood the creature is carrying, and replaced them with css boxes and circles.
=> Vampire the Requiem, Removing the need for images for vitae

Star Wars Revised RPG/SWRRPG-updated.html
Added additional force powers and feats from "Power of the Jedi" Sourcebook. 
Added input values, repeating sections, and text areas for starships and vehicles
=> Updates to SWRRPG character sheet

ArcaneCodex/ArcaneCodex2e.css, ArcaneCodex/ArcaneCodex2e.html
-fixed some text areas sharing the same attr_id
-made some text areas bigger
-changed the size of  the money input fields
=> fixes and minor layout changes

AEON-Aberrant/aberrant.css, AEON-Aberrant/aberrant.html, AEON-Aberrant/sheet.json
okay hopefully these changes will work, fixed the logo not working (was removed from the original linked site) undid an attempt to make a repeating entry within a repeating entry (that didn't work out so well but was nice attempt (it kept putting them in all the other repeated entries so that was no good.
=> Cowtankerous patch 3

ArcaneCodex/ArcaneCodex2e.css, ArcaneCodex/ArcaneCodex2e.html
more specific input for damage values on weapons
=> improved weapon input

d20 Modern/d20 Modern.html
Added sheet worker to try and fix hit point issue.
=> d20 Modern, Sheet Workers

Call_of_Cthulhu_Spanish/Call_of_Cthulhu.css, Call_of_Cthulhu_Spanish/Call_of_Cthulhu.html
Solving a css problem and changing some things
Added more roll buttons, to repeating lists and trying to solve the bug on the roll bug
Trying to make the sheet worker go
tl;dr: Some problems solved.
=> [CoC 5e] css, roll buttons and sheet worker

ICRPG/ICRPG.html
=> updated ICRPG typos

Stars_Without_Number_Revised/ReadMe.md, Stars_Without_Number_Revised/Stars_Without_Number_Revised.css, Stars_Without_Number_Revised/Stars_Without_Number_Revised.html
A few extra little things to make things actually work properly. The skill list was only half-functional and confusing, it has now been made fully functional and clear. Hit rolls were weird because of the change from descending to ascending AC, I fixed that by removing hit detection. This also allows the GM to not reveal an NPCs AC.
=> Some improvements and fixes to the SWN Revised sheets

Mongoose_Traveller/MongooseTraveller.html
Increased maximum attribute, added skill modifiers to specialties, made pilot specialties visible, allowed multiple armors
=> MongooseTraveller Update

AGE System/AGE System.css, AGE System/AGE System.html
- Spell button is now the spell name in the Character tab Spell section.
=> AGE System 1.14

Fallout 3.5/Fallout 3.5.html
Added roll option for SPECIAL.
=> Update Fallout 3.5.html

AGE System/sheet.json
- I'm hoping this fixes the Default Sheet Settings once and for all.
(it would be helpful to be able to test it with a custom sheet instead of waiting for the merge each week)
=> AGE System 1.16

Call_of_Cthulhu_Spanish/Call_of_Cthulhu.html, Call_of_Cthulhu_Spanish/sheet.json, Call_of_Cthulhu_Spanish/translation.json, Call_of_Cthulhu_Spanish/translations/en.json, Call_of_Cthulhu_Spanish/translations/es.json, Fate_Core/fate.html
Sheet worker modified, added roll template to aditional skills, trying to solve the medicine roll bug
=> Call of Cthulhu 5e updates

AGE System/AGE System.css, AGE System/sheet.json, AGE System/translation.json
- Minor fix for a forgotten option in Default Sheet Settings
=> AGE System 1.16.1

The Black Company/Previous Versions/bcsheet v1.0.html, The Black Company/bcsheet.html
Updated the skill calculations and added a 'total'.
Previous versions also added for rollback needs.
=> The Black Company: Skill updates

Babylon 5/Babylon 5.css, Babylon 5/Babylon 5.html
Made fonts in CSS web safe.
Added missing Starship Defense section.
=> Font Fixes, Added Missing Section

Stars_Without_Number_Revised/ReadMe.md, Stars_Without_Number_Revised/Stars_Without_Number_Revised.css, Stars_Without_Number_Revised/Stars_Without_Number_Revised.html, Stars_Without_Number_Revised/sheet.json
Further development on the SWN Revised sheet.
I do at one point remove completely a field, but as this is a field tracking committed effort that shouldn't really be a problem. Trying to migrate that data may very well cause more confusion as the previously united day/scene effort is all dumped into one of them. These are also numbers that reset every game day or scene (encounter or similar), so any lack of data or confusion would disappear very quickly.
=> SWN Revised v1.3.0

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Made Destructive Trance Checkbox for Actions, Other Actiosn, and Legendary Items
- Allows explosions on 1 less than max die size
=> Open Legend: Destructive Trance Support

OldDragon/olddragon.html
Fix: 
- double attr_repeal1
- added more weapons
Add:
- New fields Aprender magicas, Línguas conhecidas and Habilidade de raça e especialização
- New field in spells 'duração'
Rework:
- Rolling dices in weapons and spells
=> Fix and adding system community hints

TailsOfEquestria/js/worker.js, TailsOfEquestria/less/fields.less, TailsOfEquestria/less/main.less, TailsOfEquestria/less/rolltemplate.less, TailsOfEquestria/pug/fields.pug, TailsOfEquestria/pug/index.pug, TailsOfEquestria/pug/rolltemplate.pug, TailsOfEquestria/sheet.css, TailsOfEquestria/sheet.html
Dice rolls can now go above D20.
Added Upgrade/Downgrade steps fields to talents.
Allow talents with no traits.
=> Tails of Equestria v1.2

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.htm, ChroniquesGalactiques/sheet.json, ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.htm, ChroniquesOubliees/sheet.json
Attributes above 30 don't provoke an error message anymore.
=> Chroniques Oubliées & Galactique bug fix

AGE System/sheet.json
- Possible fix for Default Sheet Settings
=> AGE System 1.16.2

Star Trek Adventures 2d20/Star Trek Adventures 2d20.css, Star Trek Adventures 2d20/Star Trek Adventures 2d20.html, Star Trek Adventures 2d20/changelog.md
Improved performance, moved number fields to text fields due to unreliable behavior
=> [STA 2d20] Version 1.2

Starfinder (simple)/Starfinder (simple).css, Starfinder (simple)/Starfinder (simple).html
Drone sheet completed
Skill bug fixes
Character sheet appearance fix
NPC sheet restored
=> Update Starfinder (simple)

AGE System/AGE System.css, AGE System/AGE System.html, AGE System/sheet.json
- Fixed Intelligence focus rolls.
- Added focus value in the Character tab.
- Reduced size of Focuses description fields.
- Changed placeholder for Focuses and Aim values.
- Added version numbering in Options tab.
=> AGE System 1.17

Burning Wheel/Burning Wheel.html
- Refined the text and formatting and fixed some typos
- Added a Property line
=> Update Burning Wheel

AGE System/AGE System.html, AGE System/sheet.json
- Update to sheet.json (return to line)
=> AGE System 1.17.1

Dungeonslayers-4/DS4.css, Dungeonslayers-4/DS4.html
fixed:
- mana calculation after level up
- unarmed attack output
usability:
- numbered each section for easier reference
- rearranged bonus attributes to reflect main section
=> Dungeonslayers-4: bug fixes and usability improvements

Knight/knight.css, Knight/knight.html
Update for Codex 5
Little bugfix
Simplifying the code
=> Major Update : Knight Sheet

Pendragon/Pendragon.html
Steward name gets put in the roll instead of 'Steward/ess'.
Layout outside of sheet fixed and typos.
=> [Pendragon] Minor UI and typo fix

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
- There was an issue with the value from the advantage/disadvantage prompt, if you would enter "+1" instead of "1" the roll would evaluate to something like 1d20++1 which doesn't work. I've placed brackets around all prompts which results in 1d20+(+1) instead of ++. 
- As far as i've read there is no more work being done on the "big update" (correct me if i'm wrong!) and the warning should probably be removed. I've removed the link to arcfox's website as it's down anyways.
=> Fixed an roll issue and removed link to website

fate_core_with_rolls/fate_core_with_rolls.html
Fixing Modifier question for Fate Character Sheet
=> Fix Modifier question for Fate Character sheet

Basic Fantasy RPG - Expanded/Readme.md, Basic Fantasy RPG - Expanded/bfrpgsheet-expanded.html
Fixed mistyped entries and removed input fields that was not needed.
=> Fixed errors

Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
- Outputs to chat show Attribute Score next to the Attribute now
- Attributes can have a max value of 10
- Before only 9 has that is the highest a PC can have (changable through "dice modifer")
- Changed it to 10 so NPC charactersheets can have this value and to make it possibly easier for players
=> [Open Legend] Max Attribute Value and Chat Output

Cerbere/ReadMe.md, Cerbere/cerbere.htm, Cerbere/sheet.json
Bug fix for "Le Métal Froid des Anneaux de Cerbère".
=> Bug fix (Le Métal Froid des Anneaux de Cerbère)

Babylon 5/Babylon 5.html
Added more missing sections, corrected some small errors, reorganized weapons code.
=> Missing Sections, Error Corrections

Cepheus Engine/CepheusEngine.html
Updated the section headers for Characteristics, Skills and Equipment. Also, updated "Traits" text area, removing "blah, blah" spacer text.
=> Update section headers in CepheusEngine.html

Cepheus Engine/CepheusEngine.html
Updated characteristics mod fields, to populate the formula properly.
=> Update to Characteristic Mod fields

Cepheus Engine/CepheusEngine.html
Updated characteristics modifiers, and added skill roll buttons to all skills.
=> Cepheus Engine Update to stat mods

OVA/OVA.css, OVA/OVA.html, OVA/README.md
Created roll buttons for the Attack section of the character sheet.
Any existing characters will need to be updated manually for the roll
buttons to work.
=> Attack Roll Buttons

Babylon 5/Babylon 5.html
Fixed broken defense calculations, as equipment bonuses do not exist in B52E causing the macro to fail.
=> Fixed Defense Calculation

WODVtM5eAlpha/README.md, WODVtM5eAlpha/VtM5eAlpha.html, WODVtM5eAlpha/sheet.json
It's useless as created, preview gravely incorrect.
-Hopefully skills, grouped under respective attribute(mental, pysique, social)
-Backgrounds, Dicipline, other traits should be aligned next to each other.
-Everything else still a hot mess.
-Translation are in no way corrected yet but will be left alone for now. 
P.S Please rename the sheet 5E Alpha(from current 5E), as this sheet is based on the alpha release of the 5E sheet. Someone more competent will take on the 5E sheet when it comes, so best to leave the name free too.
=> Big fixes(WODVtM5EAlpha)

Tavern-Tales/TavernTalesSheet.css, Tavern-Tales/TavernTalesSheet.html
added roll buttons to main page
=> Updated Tavern Tales

The One Ring/sheet.css, The One Ring/sheet.html
Some problems with translations in the rolls have been fixed, and a minor style fix.
=> Fixed some translation problems with the rolls

Cyberpunk 2020/Cyberpunk2020.html
Fixing background, color, and misspellings
=> Update Cyberpunk 2020

Cyberpunk 2k20/Cyberpunk 2k20.html
They won’t save entered values otherwise.
=> Cyberpunk 2k20: Add types to untyped inputs

SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Had an input field in twice and one was overwriting the correct value.
Submitting this to correct that error.  This is necessary as
preparation for a sheet upgrade that’s in the works.
=> Field Conflict Correction

The Mutant Epoch/The Mutant Epoch.html
Fixed text area forgetting input
=> Updated sheet

Stars_Without_Number_Revised/ReadMe.md, Stars_Without_Number_Revised/Stars_Without_Number_Revised.css, Stars_Without_Number_Revised/Stars_Without_Number_Revised.html
A fix, some data I forgot to add the last time, and a system for making sheet section show/hideable.
=> SWN Revised v1.5.0

AD&D_1E/1ESheet.html
Reverts Roll20/roll20-character-sheets#3182
=> Revert "Update 1ESheet.html"

D6StarWars/D6StarWars.css, D6StarWars/D6StarWars.html
- long range and ammo number fields made wider
- moved Force Powers textarea to better position and gave it proper height
- made two description textareas bigger
- formatting for initiative field and dice
- added 5th option to "nr of force powers active#
=> [D6 Star Wars] sheet formatting

AD&D_1E/1ESheet.css, AD&D_1E/1ESheet.html
- added input type="text" to text input fields.
=> Ad&d1e text attribute fix

SavageWorlds-Tabbed/SW_CharSheet-tabbed.css, SavageWorlds-Tabbed/SW_CharSheet-tabbed.html
Set up an important notice to make users of the SWT sheet aware of a
potentially game-breaking update coming and inviting them to
participate in the QA game so we can catch as many bugs as possible.
=> Important Notice

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Inventory, Notes, Goals, Beliefs, & Instincts can now be sent to chat
* Inventory Area Re-worked
=> [Open Legend] Inventory area Improvement

WODVtM5eAlpha/VtM5eAlpha.html, WODVtM5eAlpha/translation.json, WODVtM5eAlpha/translations/en.json
- text fixes
- formatting attempts
- Removed unnecessary rolls
- added single roll button for making skill/attribute rolls, takes into account your hunger
=> [VtM5E Alpha] (formatting & small fixes)

Basic_Roleplaying/Basic_Roleplaying.html, Basic_Roleplaying/sheet.json
Fixed Art skill roll template bug and set default category modifier to zero. See full description of issues here: https://app.roll20.net/forum/post/5789874/brp-basic-roleplaying-sheet-skill-rolls-always-failures
Corrected some minor typos.
=> Art roll template and category modifiers fix

Star Trek Adventures 2d20/Star Trek Adventures 2d20.html, Star Trek Adventures 2d20/changelog.md
* Default sheet is missing milestone tracking, added this to the settings screen (attr_norm-mile, attr_spot-mile, attr_arc-mile, attr_rep).
* Default sheet is missing resistance tracking, added this to the settings screen (auto calculates for ships based on scale, players 0, bonus allows wearing armor or altering for NPCs - attr_resist, attr_resist_bonus)
=> [Star Trek Adventures 2d20] v1.2.4

Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html
- repeating sections fixed
- Health symbol corrected to a heart
- unnecessary skill rolls removed
- skills textarea enlarged
- header image added
=> [Weaverdice] repeating section fix

Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
3 roll commands wrongly named for "item_1" on sending inventory to chat window.
=> [Open Legend] Small Mis-named Inventory

Weaverdice/Weaverdice.css, Weaverdice/Weaverdice.html
Should fix layout that got broken last update.
=> [Weaverdice] Missing "sheet-" added to CSS class names

Mythras/Changelog.md, Mythras/Mythras.html, Mythras/translation.json, Mythras/translations/en.json
=> Mythras v1.4.1

D6StarWars/D6StarWars.html
- all new skills should have a default value of 3D+ 0 pip when created, was missing from a few
- few text areas resized
=> [D6 Star Wars] minor fixes

Black Hack/BlackHack.css, Black Hack/BlackHack.html
Added user preferences for color and font-size.
=> Updated Black Hack Sheet

Mutants and Masterminds 3E/mutants-and-masterminds.html
toughness-points were not being added to the attr_total-defense-points so they were not being added to how many power points you have spent
=> Fixed toughness calculation problem

TormentaRPG-PDF_Based/fichaTormenta.css, TormentaRPG-PDF_Based/fichaTormentaHtml.html
everything was messed up when pulled, had to fix it
=> layout fixes

Dungeon_World_Official/Dungeon World.css, Dungeon_World_Official/Dungeon World.html
- Added Herculean Appetites button under Global Modifiers
- Added "notes" section under Sub page (I've used two text areas to simulate two columns; the shorter line-lengths are easier to read than one wide box).
- I added a text area for Race to make it consistent with Bonds and Alignment. In my playtesting, some of the racial features are quite long and it's fiddly trying to read them in a one-line text input.
=> Dungeon World Official - Herculean appetites and minor tweaks

CWOD-Hunter/Hunter.css
this may not be the best way to fix it but it fixed the buttons
=> fixed the radio buttons

Cyberpunk 2020/Cyberpunk2020.html
Major update, including humanity/empathy interaction
=> Cyberpunk 2020 major update

Weaverdice/Weaverdice.css
added readded "sheet-" to places that should have them, sheet should hopefully return to look okay.
=> [Weaverdice] umptheenth attempt at css fix

The Strange/The Strange.css, The Strange/The Strange.html
Reverts Roll20/roll20-character-sheets#3304
=> Revert "Repeating Section for Skills in The Strange"

Kuro/Kuro.css, Kuro/Kuro.html
Change characteristics
Add skills tab and repeat_field
Add skills roll
Thk,
Sylvain
=> [Kuro] roll and css upgrade

Basic_Roleplaying/Basic_Roleplaying.html
•	Make the damage bonus be automatically calculated
•	Re-added Fast Talk to Categorical Skills, deleted it by mistake.
=> Re-added missing skill and Damage Bonus change

Infinity-2d20/Infinity 2d20.css, Infinity-2d20/Infinity 2d20.html
These commits fully change the checkbox-styled stress tracks into radio buttons, allowing the stress tracks to be tied to token bars.
=> [Infinity 2d20] Changed stress tracks to radio boxes

CWOD-Hunter/Hunter.html
they were editing the backgrounds before but now i have made them there own attributes
=> Fixed the Virtues Text fields

Hero Games 6e/Hero Games 6e.html
On teh current sheet, the boxes holding the current values for three stats (STUN, END, BODY) are disabled autocalc fields, but they need to be editable by users. I've replaced them with a sheet worker.
See this thread for details: https://app.roll20.net/forum/post/5977686/pulling-numbers-from-character-sheets-for-macro/?pageforid=5983586
=> Hero Games 6e sheet: Fixed END STUN BODY calculations

Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md
* Removed the temporary warning that old inventory not moved over would be lost
* Completely removed the old inventory section
=> [Open Legend] XP 0 calcs & Default Adv for Attr

OpenLegend_Minimalist/README.md, OpenLegend_Minimalist/open_legend_minimalist.css, OpenLegend_Minimalist/open_legend_minimalist.html
Changed the style of the Advantage menu to allow up to 12 Advantage and
Disadvantage. Also fixed a small bug where the Power Level for Boons in
the Actions section did not update correctly.
=> [Open Legend Minimalist] Advantage limit increase + slight bug fix

Star Trek Adventures Official/STA_Style.css, Star Trek Adventures Official/Star Trek Adventures Official.html
Fixed margin, moved an * in the style template to a different location, and fixed the footer to display a different width based on sheet type.
=> Small fixes to Star Trek

Lyceennes/lyceennes.css, Lyceennes/lyceennes.html, Stargate Coalition/sgco.html
=> Update Stargate Coalition  and Lycéennes

OpenLegend_Minimalist/README.md, OpenLegend_Minimalist/open_legend_minimalist.css, OpenLegend_Minimalist/open_legend_minimalist.html
The notes in the Actions section are now added to the roll and text
areas are now resizable.
=> [Open Legend Minimalist] Update to the notes sections

Rogue_Trader/RogueTrader.html
Fixed issue with adding ship weapons table
=> [Rogue-Trader] Ship weapons fix

Open Legend Basic by Great Moustache/Open Legend.css, Open Legend Basic by Great Moustache/Open Legend.html, Open Legend Basic by Great Moustache/ReadMe.md, ReadMe.md
* GUI improvements on layout
- Inventory made into nicer section that can be expanded
- Legendary Items through Inventory will expand across
- Different symbol for Feats/Perks/Flaws/Inventory to expand
- Output to Chat made to take up slightly less space w/ different background
* Other Inventory/Notes section not finished
- Will be made to be like the inventory section
- Might be updated before merge, maybe not
=> [Open Legend] GUI Improvements

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Fixed bug where 2 status used the same attribute. (Vergiftet/Versteinert)
=> Fixed bug where 2 status used the same attribute.

Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.css, Das_Schwarze_Auge_5/dsa5_character_sheet_roll20.html
Added the ability to freely add custom (or not yet added) spells to the spell list.
Also Fixed Display bug in the "Gaben"
=> Das_Schwarze_Auge_5 - Custom Spells

Mongoose_Traveller/MongooseTraveller.html
Replaced/repaired Gun Combat
Change the name of the repeating field under melee weapons, removing conflict with ranged weapons.
Added value "0" to weapon damage
=> Mongoose Traveller 1e, GunCombat Fix

CWOD-Hunter/Hunter.html
Notes and Equipament are no longer the same fields
=> Added attr_equipament

CWorldofDarkness/CWoD.html
Resolve to Perception
Presence to Charisma
Composure to Appearance
=> Corrected some Attributes

revolutiond100/RD100sheet.html
Changed attribute names for ride and pilot.
=> Trait fix for Revolution D100

Starfinder (simple)/Starfinder (simple).html
When these titles are inaccurate users can't call the attributes directly without digging into the source code.
=> Starfinder Sheet: Setting repeating field titles to match names

revolutiond100/RD100sheet.html
Fixed a few issues when the sheet was resized
=> Resizing fix

RWBY_RoC-Unofficial_Tabletop_RPG/RWBY-UnofficialTabletopRPG.html
Updates things to current version:
+Fixed how HP is calculated
+Fixed how Aura is calculated
+Changed initiative attribute to willpower.
+Updated accurate ranged weapons to use discipline
Fixed some typos.
=> Update Rwby-UnofficialRPG to Current Version

D6StarWars/D6StarWars.html
- removed remaining force_pain attributes from rolls
- fix attempt on force layout
=> [D6 Star Wars] fixing weapons roll and some layout

conan-2d20/conan 2d20.html
Bug , found 2 attributes of the same name , 1 changed
=> Update conan 2d20.html

Burning Wheel/Burning Wheel.html
*Added Test Difficulty and Practice Times tables (available in the free version of the rules)
*Added alternating row highlights to improve readability
*Minor corrections
=> Update Burning Wheel html

L5R Fantasy Flight Games/L5RFFGSheet.html, L5R Fantasy Flight Games/translation.json
Taking another run at the Fitness (Defense) label. Also fixing a variable call I discovered this weekend.
=> L5r ffg sheet

Multiverse/Multiverse Sheet.css
Fixed the picture in the background.
=> Multiverse Sheet.css

The-Fade-Tabletop/TFT Sheet.css
=> TFT Sheet.css

QUARTS/QUARTSSHEET.css
=> QUARTSSHEET.css

Star Trek Adventures Official/Star Trek Adventures Official.html
Changed the default attributes to 7 rather than 8. All characters begin with a score of 7 at creation.
=> Fixed default attributes

Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.css, Star Wars FFG API-Compatible/FFG-SWRPG-CharacterSheet.html, Star Wars FFG API-Compatible/README.md
6.4.3 Updates
Fixed Warfare to no longer roll from Xenology dice
Redirected some sheet icons to imgur
=> Star Wars FFG API-Compatible, Warfare skill and image fixes

5th Edition OGL by Roll20/5th Edition OGL by Roll20.html
Hey Steve, your previous fix will work for the Animal Handling scenario, but it will not work for Sleight of Hand. Using a string for the replace method will only replace the first instance of the string that is found, not all of them. Changing the search string to a regex with the global tag will replace all instances of the string though.
=> Update 5th Edition OGL by Roll20.html

Demon Gate/Demon Gate.css, Demon Gate/Demon Gate.html
Updated Demon Gate sheet to include condition tracker and background
=> [Demon Gate] Sheet Update

Starcraft RPG/starcraft.css, Starcraft RPG/starcraft.html
minor bug fixes, adding auto-calculating values, and major reorganization through tabs
=> Starcraft Changes

Burning Wheel/Burning Wheel.html
=> Added missing attribute

Torg Eternity/Torg Eternity.css, Torg Eternity/Torg Eternity.html
Optional ability command buttons for possibilities and bonus dice.
=> Torg Eternity optional ability command buttons for expanding rolls

Over the Edge 2e/Over_The_Edge.html, Shadows Over Sol/README.md, Shadows Over Sol/sheet.json, Shadows Over Sol/sos.css, Shadows Over Sol/sos.html
Fixed typo in the Important Person attribute of the Over the Edge 2e sheet. Also updated the Shadows Over Sol character sheet for compatibility with the Siren's Call supplement.
=> Over the Edge sheet typo fix and Shadows Over Sol sheet update

L5R Advanced/L5Rsheet.htm, L5R Fantasy Flight Games/L5RFFGSheet.html, L5R/L5Rsheet.htm
All 3 L5R sheets had faulty sheet workers. Eacch script was in its own
script block, instead of having a single script block for all sheet
workers.
=> L5R Sheets Script fix

Stars_Without_Number_Revised/Stars_Without_Number_Revised.html
Roll was broken due to a typo, it is fixed now.
=> Precognition Fix

Starcraft RPG/starcraft.css, Starcraft RPG/starcraft.html
Changes include: a lot of reorganizing, addition of hidden variables, and various fixes for functionality
=> Update to Starcraft RPG

AD&D_1E/1ESheet.css, AD&D_1E/1ESheet.html
- fixes DmgBonus attribute conflict.  new attribute within repeating_weapon is AttackDmgBonus. 
- added sheetworker to handle the migration
=> AD&D 1e v1.1

7th Sea 2e/7th Sea 2e.html
Removed the number bit, made it a number box
=> 7th Sea, Fixing Hero Points

NWOD-Mage2e/mage2e.css, NWOD-Mage2e/mage2e.html
As the title says. Motivated by one of my players running out of merit spaces, figured I'd add repeating sections to all the lists that aren't limited to a certain count by the system.
=> add several relevant repeating sections

Multiverse/Multiverse Sheet.css
Fixed the background to be less painful on the eyes.
=> Update Multiverse Sheet.css

Metallic Guardian/Metallic Guardian.html, Metallic Guardian/sheet.json
Added roll20 internal id. Status roll buttons was changed to show status dice rolling clearly.
=> Modify Metallic Guardian RPG Custom Sheet.

Star Trek Adventures Official/STA_Style.css, Star Trek Adventures Official/Star Trek Adventures Official.html, Star Trek Adventures Official/sheet.json, Star Trek Adventures Official/translation.json
- Added additional translation for select menus. 
- Created an NPC ship sheet which includes a generic dice roller for GMs to make easier dice rolls. 
- Ship & character sheets now have a resistance input for tracking. Offers no functionality.
- Updated the sheet Json to try to add an option for GMs to set a default color scheme. _This is my first time trying to do this._
=> Star Trek v1.3

Deadlands Classic/deadlandsclassic.css, Deadlands Classic/deadlandsclassic.html
Missed the Gizzards hit location in the combat tab. Also forgot to added the Bounty (XP) tracking  fields to the sheet orginally.
The repeating field for gun damage was not working. Fixed that.
=> Added XP Spot, Fix Dmg Repeat, and added missing Hit Location

Cyberpunk 2020/Cyberpunk2020.html
Adjusted tabs for use with Firefox
=> Cyberpunk 2020 to mesh with Firefox

Cyberpunk 2020/Cyberpunk2020.css
=> Cyberpunk 2020 to mesh with Firefox (css)

Star Trek Adventures Official/STA_Style.css
NPC sheet had a few wrong colors when toggled to white.
=> Star Trek: Fixed background on NPC sheet

README.md
Adds Wiki links to contribution section, as well as better structuring of the information
=> Updates contribution section
