- Fate/sheet.json
Updated sheet.json instructions field with a link to our ongoing series of posts about using the sheet.
Updated the sheet.json instructions field to point to https://www.evilhat.com/home/fate-on-roll20-part-1-character-sheet-setup/ where we are doing a series of posts guiding people through using the sheet.
> [Fate] Update to sheet.json instructions field

- ADnD_1E/1ESheet.html
- increased armor and shield input field size.
> ADnD1e small update

- Strato Shout/stratoshout.css
- Strato Shout/stratoshout.html
Skill UI Change
HTML & CSS Chage
- [ O ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ O ] Is this a bug fix?
> Strato Shout : Skill Ui Change

- whitehack/whitehack.css
- whitehack/whitehack.html
> fix and commit

- Shadowrun6th-German/sheet.html
Externalising some strings, plus adding a <br> to enhance text alignment. It's mostly small stuff.
> Sr6 last externalisation

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Name changes to UArmor and Armor.
> Fallout VNDPNP - Armor Name Change

- Naruto d20 Modern/Naruto d20 Modern.html
Updates
- Fixed a bug with Range calculation for Techniques
Notes
- It does reset the range for each technique but it doesn't remove the technique entirely so players need only to put the range to where it needs to be.
> [ND20] Range Calculation bug fix

- Ultima Bomba - Pagina Singola/lubps.css
- Ultima Bomba - Pagina Singola/lubps.html
Fix margins in vehicle and ability buttons and min-width set to 900px
> [Ultima Bomba - Pagina Singola] Fix css in vehicle and buttons

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
Share the same attribute for hit points between npc and pc variants
> Chroniques Oubliées: version 3.7

- Das_Schwarze_Auge_Ilaris/ilaris_roll20.html
- Das_Schwarze_Auge_Ilaris/readme.txt
Bugfix for stealth talent roll.
> [Das Schwarze Auge: Ilaris] 1.7.1

- Basic Fantasy RPG/BFRPGsheet.html
Two small changes to correct an issue with ability bonuses.  May be a temporary fix, but stable and good enough to deploy.
> Fixed issue with Basic Fantasy RPG sheet reported by email regarding ability bonuses.

- Harry Potter JDR/harryPotterJDR.css
> [Harry Potter JDR] Bugfix

- Empire-of-the_Petal_Throne/EPT.css
- Empire-of-the_Petal_Throne/EPT.html
- Empire-of-the_Petal_Throne/ReadMe.md
- Empire-of-the_Petal_Throne/sheet.json
* Fixed double-quote issue in Rope making skill
* Fixed error in Intelligence stats
- [ X] Is this a bug fix?
> Empire-of-the_Petal_Throne v1.3

- AGE System/AGE System.css
- AGE System/AGE System.html
Fixes bugs in previous version of AGE System sheet:
- Added race field on Fantasy AGE
- Fixed roll button for Fantasy AGE 
- [yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [yes] Is this a bug fix?
- [no] Does this add functional enhancements (new features or extending existing features) ?
- [no] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_R …
> AGE System - 20200920

- Delta Green 2/translation.json
added Update to the translation
Added "Update" to the translation file to remove the red around the Update button.
- [ x] Is this a bug fix?
> [Delta Green by ArcDream] Update translation.json

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Fixed some grammar, errors in terminology, and a common bug. Also did some reformating!
Also, we were placed under "custom" games in sorting. We'd like to be placed under powered by the apocalypse.
>Reformated Items (will end up removing the right column, however, a public announcement was made on Tumblr and discord.
>Changed order of personality and persona stats 
>Renamed personality and persona stats (did not rename attributes)
>Changed some labeling 
>Fixed a common bug, by having some spaces default to 0.
>Less fixing a bug, more making sure it doesn't happen to people new to the sheet.
>Some minor changes in spacing but no changes to CSS.
>We made an announcement …
> Update crimsonparcelsupttrpg.html (CP Unofficial Persona TTRPG / Unofficial Persona TTRPG)

- CWOD-Hunter/Hunter.css
Hunter.css is not being merged into the character sheets, discussed and identified the most likely cause. Used the value from CWOD-Vampire
https://app.roll20.net/forum/post/9217849/cwod-hunter-css-not-rendered/?pageforid=9219098#post-9219098
> [CWOD-Hunter] Bring Hunter.css inline with Vampire.css

- Strato Shout/stratoshout.html
Strato Shout Bug Fix
- [O] Is this a bug fix?
> Strato Shout Bug Fix

- 3D&T_ALPHA/3D&T_ALPHA.css
- 3D&T_ALPHA/3D&T_ALPHA.html
> Fix Url Image

- Empire_des_cerisiers/EdC.css
- Empire_des_cerisiers/EdC.html
- Empire_des_cerisiers/ReadMe.md
- Empire_des_cerisiers/sheet.json
- Added : magic tab
- Added : simple roll at the top of the sheet
- Updated : changing an injury level now update the others accordingly
- Fixed : skill aspect name not updating when source aspect is changed
> [L'Empire des Cerisiers V1.1] Add Magic tab and minor updates

- Barbarians Of Lemuria - Mythic/bolm.htm
- Correct spelling of Strength (from Strengh)
- Default to Strength attribute when rolling a Melee attack
- Format HTML
> [Barbarians of Lemuria - Mythic] - Bug fixes

- Into the Odd/into-the-odd-sheet.html
- Into the Odd/into-the-odd-style.css
- Into the Odd/translation.json
- Into the Odd/translations/af.json
- Into the Odd/translations/cs.json
- Into the Odd/translations/da.json
- Into the Odd/translations/de.json
- Into the Odd/translations/el.json
- Into the Odd/translations/en.json
- Into the Odd/translations/es.json
- Into the Odd/translations/fr.json
- Into the Odd/translations/he.json
- Into the Odd/translations/it.json
- Into the Odd/translations/ja.json
- Into the Odd/translations/ko.json
- Into the Odd/translations/nl.json
- Into the Odd/translations/pl.json
- Into the Odd/translations/pt.json
- Into the Odd/translations/ru.json
- Into the Odd/translations/sv.json
- Into the Odd/translations/tr.json
- Into the Odd/translations/zh.json
- Into the Odd/translations/zu.json
Various fixes and improvements for the Into the Odd character sheet:
- Slightly reduce the width of the stat block to gain some space.
- Remove the useless `follower-u` translation key.
- Improve the French translation (French is my native language).
- Actually add the i18n data in the HTML... yeah I forgot to do that when submitting the sheet.
- Add some responsiveness to the sheet. See the images for an example.
**Does the pull request title have the sheet name(s)? Include each sheet name.** 
Yes.
**Is this a bug fix?**
There's a bug fix, among other changes.
**Does this add functional enhancements (new features or extending existing features) ?**
No.
**Does this add or change functional aesthetics (such as layout or color scheme) ?** 
Yes.
**If changing or removing attributes, what …
> Various fixes and improvements for Into the Odd

- Offworlders/offworlders.html
- Offworlders/sheet.json
* Fixes  #6596 
* Ship checkbox fixed
* Default Settings added for PC/ship toggle, credits and starting xp
> [Offworlders]  Small Fix + Default settings

- Mutants and Masterminds 3E/mutants-and-masterminds.html
* Fixes #7464
* Minor bug fix to html img src references
* No functional enhancements, changes to functional aesthetics (beyond correcting broken image elements) and no effect on player data
> Bug Fix: Mutants and Masterminds 3E

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Just fixed a term error. Also corrected spelling
> Update crimsonparcelsupttrpg.html (CP Persona TTRPG / Unofficial Persona TTRPG)

- CWOD-Hunter/Hunter.css
- CWOD-Hunter/Hunter.html
- Converted the layout to grid for a responsive layout
- Add experience_spent attribute
> [CWOD-Hunter/Hunter.html] Hunter html cleanup

- Mutant Year Zero/mutantyearzero.css
- fixed checkbox images for critical injuries (url's updated in css)
- adjusted expand/hide button position on the appearance grid (face, body, clothing)
> MYZ - small fixes

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Further modification of how Armor tab works. Worn? check will now add/remove ENC and AP appropriately. Some descriptive text has been added to these sections too.
- Continued adding IL8N tags that were missing from a lot of the new content. This work is now mostly complete.
- Workable Italian translation is now implemented (Translation credit to Andrezzo/Roll20). (change language to Italian on Roll20 website/account config, then start server to see it). I am more then willing to work with others to implement more languages, but can not do this by myself.
> [Warhammer 4e Character Sheet] v1.23 Armor tab & translation updates

- Knight/knight.html
- Knight/translation.json
> [Knight] Bugfix translation

- Stargate-RPG/Readme.md
- Stargate-RPG/sheet.json
- Stargate-RPG/stargate.css
- Stargate-RPG/stargate.html
- **Could Roll20 opt-in the character sheet repo to this years [Hacktoberfest](https://hacktoberfest.digitalocean.com)? It should be as easy as just [adding "hacktoberfest" as a topic for the repo](https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean).**
- Official character sheet update backed  Publisher.
- changes to `sheet.json` have been checked with a `.json`-validator, and tested in the Sheet Sandbox.
- See Readme for full list of changes
- Sheet Changelog also added to the "Settings"-page
- Changes tested, big thanks to **dmitriwillguard** for testing and feedback.
> [Stargate RPG] v.1.4 

- Coriolis/Coriolis.html
- Coriolis/translation.json
These are changes for issue #5756 
Corrected 2 of the 4 points the original poster mentioned.
- Modifier query button for all rolls
- Xd6>6 armor buttons
The other points I can't fix due to lack of familiarity with the game rules.
Sheet appearance was unaffected, though new items were added to the translation file.
New sheet attribute default to a value that will cause no effect to existing characters, the modifier query will be turned off.
> [Coriolis] Issue fixes

- Pugmire/pugmire.html
> Use input size xlarge for Defense and Initiative elements for Pugmire character sheet

- Lex Arcana/LexArcana.html
- Lex Arcana/translation.json
- Lex Arcana/translations/af.json
- Lex Arcana/translations/cs.json
- Lex Arcana/translations/da.json
- Lex Arcana/translations/de.json
- Lex Arcana/translations/el.json
- Lex Arcana/translations/en.json
- Lex Arcana/translations/es.json
- Lex Arcana/translations/fr.json
- Lex Arcana/translations/he.json
- Lex Arcana/translations/it.json
- Lex Arcana/translations/ja.json
- Lex Arcana/translations/ko.json
- Lex Arcana/translations/nl.json
- Lex Arcana/translations/pl.json
- Lex Arcana/translations/pt.json
- Lex Arcana/translations/ru.json
- Lex Arcana/translations/sv.json
- Lex Arcana/translations/tr.json
- Lex Arcana/translations/uk.json
- Lex Arcana/translations/zh.json
- Lex Arcana/translations/zu.json
Adds a checkbox for the Heal state.
I have added the heal key to all the translations, I have requested access to the translations panel to Cassie, so next time I will be able to do these changes via the Crowdin platform, would it be possible to have this PR accepted in the mean time please?
> add heal checkbox

- Dark_Heresy_2ed/DarkHeresy2ed.html
> [Dark Heresy 2e] fix modifier query

- Qin Warring States/Qin.html
Tao are duplicated five times over.
Also, quick fix to input height for equipment and deeds
> [Qin] Remove duplicate tao and fix height of equipment / deeds

- Dark_Heresy/DarkHeresy.html
> [Dark Heresy] fix range placeholder (#7503)

- Dark_Heresy_2ed/DarkHeresy2ed.html
- Dark_Heresy_2ed/DarkHeresy2edStyle.css
- Dark_Heresy_2ed/sheet.json
> [Dark Heresy 2e] tweaked rolltemplate

- Trinites/Trinites.css
- Trinites/Trinites.html
> [Trinités] Bugfix / Improve

- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/sheet.json
Fix #6789 the issue of modifier being wrong when attribute falls to 0 due to injury.
Also fix modifer going >3 if attribute somehow exceeds 17!
> [Mongoose Traveller 2e] Fix issue #6789

- CWOD-Hunter/Hunter.css
- CWOD-Hunter/Hunter.html
'grid-' related CSS properties are being stripped out of HTML, breaking layout.
Moving more styling out of HTML and into CSS to preserve layout.
> [CWOD-Hunter] Grid cleanup

- MAGUS_ETK/magus_etk.html
Enhance layout.
Optimise health section's position in layout for better user experience.
Adds worker for setting default values.
Fixes ambiguity of attributes (asztral).
> M.A.G.U.S. ETK - v1.2

- Doctor Who Adventures in Time and Space/DoctorWho.css
- Doctor Who Adventures in Time and Space/DoctorWho.html
- Doctor Who Adventures in Time and Space/sheet.json
- [x ] Does this add functional enhancements (new features or extending existing features) ?
- [x ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
Used the same attribute names for existing ones. 
> New Version

- Dark_Heresy_2ed/DarkHeresy2ed.html
> [Dark Heresy 2ed] fix damage in roll template

- Aria/Aria.html
> Update Aria.html encoding

- Savage Worlds - Graph Paper/SavageWorldsGraphPaper.css
- Savage Worlds - Graph Paper/SavageWorldsGraphPaper.html
- Savage Worlds - Graph Paper/browser_preview.html
- Savage Worlds - Graph Paper/source/scripts/workers.js
- Savage Worlds - Graph Paper/source/styles/_armor.scss
- Savage Worlds - Graph Paper/source/styles/_engrams.scss
- Savage Worlds - Graph Paper/source/styles/_general.scss
- Savage Worlds - Graph Paper/source/styles/_health.scss
- Savage Worlds - Graph Paper/source/styles/_power.scss
- Savage Worlds - Graph Paper/source/styles/_settings.scss
- Savage Worlds - Graph Paper/source/templates/_settings.pug
- Savage Worlds - Graph Paper/translation.json
~~One part of the update routine did not work and was removed; it's not critical and can be done manually if even necessary. There is a note in the support game.~~ Repaired update routine to actually do something! Also, some CSS was not working as intended.
> [SWADE] Savage Worlds - Graph Paper Sheet Hotfix

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Added Readme with Changelog and other details
- Added 1/combat as an option for move frequencies
- Added Pokemon moves section to the Trainer sheet, since Trainers often use moves. Now this section is on all sheets.
- Revamped how move usage is tracked, to use buttons instead of checkboxes. Added this same tracker to Features.
- Changed Nature selection to a dropdown
PokemonTabletopAdventures_v3
Will notify existing playerbase of the change. Previous values for Nature will be replaced, but this is trivial to select again.
> PokemonTabletopAdventures_v3 - Community suggested features and improvements

- Dark_Heresy_2ed/DarkHeresy2ed.html
- Dark_Heresy_2ed/DarkHeresy2edStyle.css
> [Dark Heresy 2ed] add a damage roll template

- Empire_des_cerisiers/EdC.html
- Empire_des_cerisiers/ReadMe.md
- Added : missing options in skill / magic calculator
- Fixed : wrong formula on Mental resistance roll
> [L'Empire des Cerisiers V1.1-1] Minor bug fixes

- Arcanas&Ancestrais/arcanas.html
Realizadas melhorias visuais na exibição de PV e DV
Melhoria nas rolagens de dados de uso e dano das armas
Correção nas rolagens de dados de uso dos itens
> Melhorias visuais e nas rolagens de dado da ficha do Arcanas & Ancestrais

- Kamigakari/kamigakari.css
- Kamigakari/kamigakari.html
- Kamigakari/sheet.json
Fixed instructions and made them more clear
Fixed the white pixels under the tab names
Fixed a translation error with Spirit Burn
No Variables were changed
- [Y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [N] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Ro …
> [Kamigakari God Hunters] Minor Fixes

- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
- Change some attribute names (to lower cases, or change '-' into '_')
- Guess actions for scrolls and potions.
- new version to update the attributes.
> Chroniques Oubliees: version 4.01

- Dragon Warriors/Dragon Warriors Revised.css
- Dragon Warriors/Dragon Warriors Revised.html
Bug fixes, layout changes, updated sheet rolls.
Improved display of all areas of the sheet utilising CSS Grid more substantially.
Removed redundant information from across the entire sheet: 
- "Combat" tab has been revised and is now "Miscellaneous Modifiers". It is now possible to enter misc modifiers for almost every numerical entry on the sheet. 
- All guard functions are now controlled on the front page. 
- The majority of roll templates are now handled primarily on the front page.
- Final tally modified scores now appear alongside their base stats, or in the Combat Summary box
Encumbrance was not calculating properly due to an old Sheet Worker which was not updated properly, fixed.
Sheet rolls were clumsy and unprofessional looking, they have been updated to use roll templates. …
> Dragon Warriors Revised Update 1.2.1

- Dark_Heresy_2ed/DarkHeresy2ed.html
> [Dark Heresy 2ed] use rolltemplate for characteristics

- Doctor Who Adventures in Time and Space/DoctorWho.html
- Doctor Who Adventures in Time and Space/sheet.json
> attr name fixes

- Anima-Beyond-Fantasy/A-BF.css
> [Anima Beyond Fantasy] Bugfix

- Serenity/serenity.css
- Serenity/serenity.html
A user contacted me that two of the "repeating_" attributes weren't properly saving data. Checked the "Common mistakes" page on roll20 and it looks like repeating_ sections with other underscores aren't allowed. This change renames the offending attributes. This only affects the name of the 2 equipped weapons attributes. The rest of the attributes are unchanged.
I only saw this issue occurring on those two attributes, the other repeating_ attributes are still functioning correctly.
Another roll20 user has requested the ability to save custom Assets/Complications that are not part of the original Serenity sets.
* Renames the two equipped weapon attributes to camelCase instead of snake_case
* Formats the html with prettier and the css with js-beautify
* Adds custom asset/complication …
> Serenity: remove underscores from repeating_ attribute names & enable custom assets/complications

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.css
- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Fixed a bug and added a slot for Wild Cards~
Fixed two different text boxes having the same attribute. Also added a slot to help record a mechanic in the game. Also added a different background to increase visibility! 
> Update crimsonparcelsupttrpg.html (CP-Unofficial-Persona-TTRPG)

- Star Trek Last Unicorn/Star Trek.html
Renamed wrong attribute from attr_logic to attr_intellect
- [Yes ] Is this a bug fix?
- [No ] Does this add functional enhancements (new features or extending existing features) ?
- [No ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ None; name was duplicated] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [N/A ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ? …
> Star Trek Last Unicorn: Intellect fix

- Arcanas&Ancestrais/arcanas.css
- Arcanas&Ancestrais/arcanas.html
- Inclusão de rolagem automática do dado de uso no ataque;
- Inclusão de valor de destreza nas rolagens de ataque e dano;
- Separação do css do html.
- [ x] Does this add functional enhancements (new features or extending existing features) ?
> Arcanas & Ancestrais: melhorias nas rolagens

- Kids on Brooms Official/kobrooms.css
- Kids on Brooms Official/kobrooms.html
- Kids on Brooms Official/src/pug/mixins.pug
- Kids on Brooms Official/src/scss/kobrooms.scss
> Kids on Brooms Official - Fixing Display Bug

- Serenity/serenity.css
- Serenity/serenity.html
* Fix formatting of custom asset/complications
* Fix display of asset/complication descriptions
* Fix bad css class name
> Serenity - Fix custom asset/complication formatting, asset/complication descriptions

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
* Add more fine-grained attributes for purse
* Add equipment tab for NPCs.
> Chroniques Oubliees: version 4.02

- Rogue_Trader/RogueTrader.html
> [Rogue Trader] correct melee damage calculation

- Rogue_Trader/RogueTrader.html
- Rogue_Trader/RogueTraderStyle.css
> [Rogue Trader] add journal and xp tab

- D6StarWars/CHANGELOG.md
- D6StarWars/D6StarWars.css
- D6StarWars/D6StarWars.html
- D6StarWars/sheet.json
- removed broken logo at top
- revamp of starship section
- add new roll templates, used in ship weapon damage rolls
> [Star Wars D6] v.2.31 ship update

- Feast_of_Legends/feast_of_legends.css
- Feast_of_Legends/feast_of_legends.html
- Feast_of_Legends/sheet.json
> [Feast of Legends] Second Attack added

- Stargate-RPG/Readme.md
- Stargate-RPG/sheet.json
- Stargate-RPG/stargate.css
- Stargate-RPG/stargate.html
> [Stargate RPG] v.1.55

- Drakar_och_Demoner-91/dod_91.html
Noted spelling mistakes and naming mistake of a skill. These are fixed in PR.
> Fix naming and spelling in Drakar_och_Demoner-91

- ChroniquesOubliees/co.html
> Chroniques Oubliees: change logo display.

- AD&D 2E Revised/2ESheet.html
- AD&D 2E Revised/extra/sheetWorkers.js
- Fixed rogue detect noise update sheetworker
- bumped version
> [AD&D 2E Revised] Fixed detect noise not updating

- Dark_Heresy/DarkHeresy.html
- Dark_Heresy/DarkHeresyStyle.css
- Dark_Heresy/translation.json
fix the logic roll
revert the placeholder from #7506
add hover descritption for range
> [Dark Heresy] logic and range

- Kamigakari/kamigakari.html
Fixed Resistance button so it properly adds dice
Fixed Talent Buttons so they properly send the talent to chat
> Kamigakari God Hunters

- Dark_Heresy_2ed/DarkHeresy2ed.html
> [Dark Heresy 2ed] next batch of roll template usage

- Meute/meute.html
> [Meute]Bugfix

- Esper_Genesis_5E/EG_Sheet.css
- Esper_Genesis_5E/EG_Sheet.html
- Esper_Genesis_5E/sheet.json
> Drag and Drop Should Allow Powers/Spells onto NPC Sheet (UC1341)

- Esper_Genesis_5E/EG_Sheet.css
- Esper_Genesis_5E/EG_Sheet.html
- Esper_Genesis_5E/sheet.json
> Talent Points/Slots auto-fill by class level (UC1343)

- Aborea_new/aborea.html
> [Aborea] fix job toggle

- Rogue_Trader/RogueTrader.html
- Rogue_Trader/RogueTraderStyle.css
> [Rogue Trader] fix new tabs not handled like existing tabs

- Forbidden_Lands/Forbidden_Lands.html
- Forbidden_Lands/translation.json
- Fixed a translation error that caused the dice pool to show "false" when the Melee skill was selected.
> Forbidden Lands v1.75 translation bug fix

- H&D/H&D.html
> [H&D] Bugfix

- HeXXen1733/hexxen1733_community.html
- HeXXen1733/sheet.json
Source project now uses PUG to create the HTML skeleton.
See https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733/issues/3
Added Features:
- Bonus Health Points and Healing Tokens added 
https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733/issues/4
Fixed Bugs:
- Powers are not mirrored anymore 
https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733/issues/2
- Coups are now correctly calculated
https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733/issues/1
Externalized Instructions on github wiki.
> [HeXXen 1733] Update to v1 of character sheet fix

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Just added a weapon notes section
> Update crimsonparcelsupttrpg.html (CP-Unofficial-Persona TTRPG)

- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
A bit more space to display what's in the purse.
> Chroniques OUbliees: a bit more space to display what's in the purse.

- MascarasDelImperio/MascarasDelImperioSheet.css
I have updated the url of the sheet background
> MascarasDelImperio: fixed image url

- Esper_Genesis_5E/EG_Sheet.html
> Esper Mastery should auto-fill by class level (UC1344)

- Empire_des_cerisiers/EdC.css
- Empire_des_cerisiers/EdC.html
- Empire_des_cerisiers/ReadMe.md
- Empire_des_cerisiers/sheet.json
- Fix : non working selector on ritual tab.
- Updated : re styling of gmroll button.
- Added : currencies.
> [L'Empire des Cerisiers V1.2-1] Fix, new feature and update

- Warhammer Fantasy Roleplay 4e Official/src/js/dragndrop.js
- Warhammer Fantasy Roleplay 4e Official/src/js/sheetworkers.js
- Warhammer Fantasy Roleplay 4e Official/wfrp4.html
> WFRP4e Official - Minor bugfix

- Agone-(french)/agone-sheet.css
- Agone-(french)/agone-sheet.html
Minor text fixing
Help section updated
New Notes section at the end with autogrowing when unfocused
All penalties from rolls removed
Armor revamped
New Summary section to see PC state and major rolls quickly
> Agone-(french) New version 0.5

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
The language text box was linked to the perks text box.
> Fallout VNDPNP - Language Text Box Hotfix

- Dark_Heresy_2ed/DarkHeresy2ed.html
> [Dark Heresy 2ed] roll templates for all lore skills

- Drakar_och_Demoner-91/README.md
- Drakar_och_Demoner-91/dod_91.css
- Drakar_och_Demoner-91/dod_91.html
Fixed several fields not saving.
Minor css tweak
Applied code formatting
> [Drakar_och_Demoner-91] Fix fields not saving

- Tesoro-y-Gloria/tesoroygloria.html
Arreglado el bug que clonaba el valor de Dureza Actual 3 en la 4.
> 3 ranuras más de armas debajo de talentos.

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Added a section for Trackers
Just adding something to the character sheet I should have added ages ago~ 
>  Update crimsonparcelsupttrpg.html (CP-Unofficial-Persona-TTRPG)

- ICRPG extended/ICRPGextended.html
…The COIN field resets every time game is closed causing players to lose track of money. This will hopefully make the values permanent in the sheet from game to game.
> [ICRPGextended] Fixes bug with storing coin value permanently.

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
This adds four missing special abilities to the DSA 4.1 sheet. According to the rules (Wege der Helden, Page 281) it is also possible to acquire the "Scharfschütze" and "Meisterschütze" abilites for blowpipes and slingshots.
> [Das_Schwarze_Auge_4-1] add missing special abilites for blowpipe and slingshot

- Weaverdice/sheet.json
> [Weaverdice] add patreon link

- D6StarWars/sheet.json
> [Star Wars D6] add patreon link

- Feast_of_Legends/sheet.json
> [Feast of Legends] add patreon link

- Ambition_Avarice/sheet.json
> [Ambition & Avarice] add patreon link

- Hc Svnt Dracones Second Edition/sheet.json
> [Hc Svnt Dracones 2E] add patreon link

- Genefunk 2090/genefunk2090.html
- Genefunk 2090/genefunk2090.pug
- Fixed a bug where the initiative roll wasn't being added to the tracker when a token was selected.
> Genefunk 2090fix for initiative not being added to tracker

- Agone-(french)/agone-sheet.css
- Agone-(french)/agone-sheet.html
- Fixed some titles
- New armor penalties management
- New checkbox to choose if armor is worn or not
> New version 0.6

- Star Wars EotEmpire_Dice - FR/EotE-Dice-Fr.css
Update Dice png from brokenlink
http://galacticcampaigns.com doesn't exist anymore, so i change for png from Imgur
> Update Sheet Icon of Star Wars EotEmpire_Dice - FR/EotE-Dice-Fr.css

- Star Wars EotEmpire_Dice - FR/EotE-Dice-Fr.html
http://galacticcampaigns.com/images/EotE/ is no more avialable
http://galacticcampaigns.com doesn't exist anymore, so i change for png from Imgur
> update dice img from brokenlink of Star Wars EotEmpire_Dice - FR/EotE-Dice-Fr.html 

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
Added a game option to dissociate base attack bonus from level.
new version updates the attributes
> Chroniques Oubliees: version 4.03

- MonarchiesOfMau/monarchies-of-mau.css
- MonarchiesOfMau/monarchies-of-mau.html
* Include constitution modifier for maximum number of spell slots
#####
* Fix CSS linting errors
> Update Monarchies of Mau character sheet

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.css
- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
There are some small typo corrections and attribute additions but the biggest change is a format change of the "Wildcard Section."
We are changing wildcards to be represented by check boxes instead of a number text box. That being the textbox (and it's value) are being removed. Precautions were taken by making a post on the game's Discord Wednesday to try to give a early warning!
> Updating CP-Unofficial-Persona-TTRPG character sheet

- Chroniques_De_L_Etrange/CdE.css
- Chroniques_De_L_Etrange/CdE.html
> [CdE] Improvement

- H&D/H&D.html
> [H&D]Bugfix

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Shields was removed from Helmets.
> Fallout VNDPNP - Removed Shields

- Empire-of-the_Petal_Throne/EPT.css
- Empire-of-the_Petal_Throne/EPT.html
- Empire-of-the_Petal_Throne/ReadMe.md
- Empire-of-the_Petal_Throne/sheet.json
* Fixed Magic User ad Priest XP Bonus calculations
> Empire-of-the_Petal_Throne v1.5.1

- Pugmire/pugmire.css
- Pugmire/pugmire.html
This is the same change done for [Monarchies of Mau](https://github.com/Roll20/roll20-character-sheets/pull/7795)
Include constitution modifier for maximum number of spell slots
Fix CSS linting errors
> Update Pugmire character sheet

- Empire_des_cerisiers/EdC.html
- Empire_des_cerisiers/ReadMe.md
- Empire_des_cerisiers/sheet.json
Fix : bug on rolltemplate when ritual bonus is not set.
> [L'Empire des Cerisiers V1.2-2] Fix minor bug

- Beacon/beacon.css
- Beacon/beacon.html
Update for 7.4 Beacon rules
*Druid skills
*Enchanter Skills
*Remove archane penalty from armour
*Add Hunter
*Weapon base damage
*Weapon damage calculation
*armor durability - N/A
*update fighter damage calc
*fix stat modifier and damage descriptions
*general text and form improvements
- [ y ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ y] Is this a bug fix?
- [ y] Does this add functional enhancements (new features or extending existing features) ?
- [ y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a] If changing or removing attributes, what steps have you taken, if any, to preserve player data …
> Update Beacon Sheet for new 7.4 rules

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
-Added a basic guide for more complex attributes.
-Added a checkbox to make a new concept in the next update of the game easier to use.
-Added a dropdown to censor the name of your character.
> CP-Unofficial-Persona-TTRPG (Updating HTML)

- Worlds in Peril/Worlds in Peril.html
- Worlds in Peril/sheet.json
- Worlds in Peril/translation.json
Enabled labels for translation
> [Worlds in Peril] Enabled labels for translation

- Alas For The Awful Sea/AlasForTheAwfulSea.html
- Alas For The Awful Sea/sheet.json
- Alas For The Awful Sea/translation.json
> [Alas for the Awful Sea] Enabled for translation

- Worlds in Peril/Worlds in Peril.html
> [Worlds in Peril] Fixed glitch in comments

- Alas For The Awful Sea/AlasForTheAwfulSea.html
- Alas For The Awful Sea/translation.json
> [Alas for the Awful Sea] Fixed name label for translation

- Agone-(french)/agone-sheet.html
- Fixed wrong penalty on summary page
- Fixed some texts
> Agone-(french) Quick Fixes

- Ryuutama/Ryuutama.html
> [Ryuutama]: add d20

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where newly created monsters did not have a die button. Closes wesbaker#55
> [Old-School Essentials by Necrotic Gnome] - 1.7.1

- Aria/Aria.css
Résolution d'un soucis de lisibilité dans les notes.
> Aria : Update Aria.css

- Mongoose_Traveller2e/MongooseTraveller.html
Combine multiple sheetworker sections
Fixes issue of sheet not working on dev server
Merged the two sheetworker sections in the character sheet.
> [Mongoose_Traveller2e] Combine multiple sheetworker sections

- Esper_Genesis_5E/EG_Sheet.html
- Esper_Genesis_5E/EG_Sheet.pug
- Esper_Genesis_5E/sheetworkers.js
> Esper Genesis | Drag and Drop Should Correctly Assign Ships as NPCs (UC1340)

- Trinites/Trinites.css
- Trinites/Trinites.html
> [Trinités] Bugfix + little add

- CWOD-M20/M20.css
- CWOD-M20/M20.html
> [Mage V20] Bugfix

- Dark_Heresy_2ed/DarkHeresy2ed.html
Most of the recent changes are in violation of the game rules, restoring to an older version.
> Dark Heresy 2nd Restoring to older version.

- Esoterroristas/Esoterroristas.css
- Esoterroristas/Esoterroristas.html
I have added one more skill checkbox per skill row. Minor change.
> [Esoterrorists] Add one more skillbox per row

- Marvel Heroic Roleplaying/mhrpg.html
change a number of i18n translation keys from "power point" to "plot point" to match game book language
> Marvel Heroic Roleplaying minor update mhrpg.html

- Marvel Heroic Roleplaying/mhrpg.css
increase size of input boxes for numbers
> Marvel Heroic Roleplaying minor update mhrpg.css

- TheElephantAndMacawBanner/the_elephant_and_macaw_banner.css
- TheElephantAndMacawBanner/the_elephant_and_macaw_banner.html
- TheElephantAndMacawBanner/translation.json
Fixing: 
- a css issue on the settings tab grid 
- adding new text to the translation file 
- fixing other texts there;
- changing the initiative roll to add the token to the initiative tracker.
> [The elephant and macaw banner] minor fixes

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Reaper Check boxes and Max HP can not be editted.
> Fallout V&DPNP - Condition Box Rework

- Sagas_Of_The_Icelanders/translation.json
> [Sagas of the Icelanders] Update translation.json

- Serenity/serenity.css
- Serenity/serenity.html
* Fixes typo in complications to correctly show complication description
* Adds tooltips to attributes and skills to describe what they do and what they are used for
> Serenity: Add tooltips to attributes & skills; fix complication typo

- Nephilim-Legende/nephilim-legende.css
> [Nephilim Legend] Improvement

- spacedragon/spacedragon.css
- spacedragon/spacedragon.html
Fixed macrobar bug.
Also, now the sheet display the weight carried.
> SpaceDragon : fixes

- Nanochrome/NanoChrome.css
- Nanochrome/NanoChrome.html
> [Nanochrome] Update

- Basic_Roleplaying/Basic_Roleplaying.css
Added roll template for Resistance, Characteristic and Sanity Checks.
- [ X ] Does this add functional enhancements (new features or extending existing features) ?
> Small Update for Basic Roleplaying

- Vulcania/vulcsheet.html
Fixed an error that pick the wrong value to make a roll. Now works fine
> [Vulcania] fixed ranged roll value

- Nephilim-Legende/nephilim-legende.css
- Nephilim-Legende/nephilim-legende.html
> [Nephilim Legende] Bugfix / Improvement

- Trinites/Trinites.css
- Trinites/Trinites.html
> [Trinités] Update

- John Carter of Mars/JCoM.html
Was incorrectly calculating stress.  Adding the two attributes, should have been using the better of the two.
> Update to John Carter of Mars Character Sheet

- Dark_Heresy_2ed/DarkHeresy2ed.html
removed strength bonus on ranged weapon damage
> Darh Heresy 2ed Bug fix

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.html
- Change damage die to a text field to provide more flexibility. Closes wesbaker#56
> [Old-School Essentials by Necrotic Gnome] - 1.8.0

- Cybersalles/cybersalles.css
- Cybersalles/cybersalles.html
- Cybersalles/sheet.json
> [Cybersalles] Botón iniciativa

- Vaesen/vaesen_sheet.css
- Vaesen/vaesen_sheet.html
Updated the main PC sheet with new styling and fonts.
Moved the die modifier to a more central location
> Vasesen RPG

- Nephilim-Legende/nephilim-legende.css
- Nephilim-Legende/nephilim-legende.html
> [Nephilim Legende] Correct Link

- CWOD-M20/M20.css
> [Mage V20] Chrome fix

- Star Wars FFG Alternate/README.md
- Star Wars FFG Alternate/Roll20_FFG_StarWars_CharacterSheet.css
- Star Wars FFG Alternate/Roll20_FFG_StarWars_CharacterSheet.html
- Added the "Stun" quality and changed the current quality to "Stun Damage"
- Updated the README to reflect that the sheet can be used as a standalone record but requires the included diceroller.js to activate roll buttons
- Messed up my former branch so resubmitting with from a fresh branch
> [ Star Wars FFG Alternate ] Added "Stun" weapon quality; Updated README

- ADnD_1E/1ESheet.css
- ADnD_1E/1ESheet.html
- added an announcements section to show important information on upcoming sheet changes
- fix for Spells Known roll
- small adjustments to the sub-section hide/expand carrot/nav button
- changed non-repeating attribute names to lowercase as well as title text.  Purely aesthetic and for attribute naming consistency.
> AD&D 1e update

- Only-War-Enhanced/OnlyWarEnhanced.css
- Only-War-Enhanced/OnlyWarEnhanced.html
Added a handful of HTML tooltips to help out players who may not understand some abbreviations, buttons, or jargon used in the sheet.
Changed some placeholders and flavor text to more accurately reflect the OW corebook.
Moved "Vehicle Page" button back to the bottom of its menu because it looks better that way.
> Only war (enhanced) update

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Fixed a bug
Minor Formatting changes
Corrected Term
> Update crimsonparcelsupttrpg.html (Unofficial Persona TTRPG)

- Nephilim-Legende/nephilim-legende.css
- Nephilim-Legende/nephilim-legende.html
This reverts commit dfd66fff890126062bc8fa8f17f58b2be99f3daa.
> [Nephilim Legende] Hotfix

- Cle en main/CleEnMain.css
- Cle en main/CleEnMain.html
> [Cle en main] Fix img

- Lowlife 2090/LLSheet.html
I've just changed a few of the attribute descriptions, by request of the author of the system.  No functional changes, merely cosmetic/informative.
> Lowlife 2090:  Changed attribute descriptions to be more in line with Cyberpunk trappings

- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
Added repeating section for skills
> Chroniques Oubliees: added repeating section for skills

- Basic_Roleplaying/Basic_Roleplaying.html
Weapon Lengths were resetting back to short once a player closed the sheet, so I fixed it.
> Minor Update for Basic Roleplaying System

- ShadowbaneInquisition/Shadowbane.css
- ShadowbaneInquisition/Shadowbane.html
Changed weapon damage type to a list
Roll to hit now show number of hits
Added Agility limiter on Armor
Graphical change
> [Shadowbane Inquisition] update

- GURPS/gurps.html
- GURPS/translation.json
- Fix spelling error for drowsy. Reported by Charles
- Fix bug with checkbox **Show casting details on roll template:**. The bug was if checked no roll is made, if unchecked the roll is made. Reported by Charles
- Fix bug for mini-roll modifier tool. If Encumbrance level changed, the total may not calculate correctly. Reported by PL M.
- Fix but with range calculator. Math error calculating total distance when firing up. Reported by Idle
GURPS/translation.json
> [GURPS] 2.6.1

- Aborea_new/aborea.html
- fixed typo for one attribute
- standard variable added to attribute modifiers
> [Aborea] bugfix

- The One Ring/Changelog.md
- The One Ring/README.md
- The One Ring/sheet.css
- The One Ring/sheet.html
added experience_total something that has been heavily asked for and added Jakob's Better Default Rolltemplate to the character sheet & added all 66 Character/ping color options for the header.
> updated The One Ring to 2.0.3

- Das_Schwarze_Auge_5_Tsa_Edition/dsa5.css
- Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html
> [DSA 5 Tsa] make talent categories collapsible

- ShadowbaneInquisition/Shadowbane.html
attr_psykana_class bug fix
a space in name attribute caused the roll to not register
> [Shadowbane Inquisition] Bug fix

- StarWars5E/StarWars5E_HTML.html
- correct Scholar saves
- class dropdown reordered
> [Star Wars 5E] minor fix

- Basic_Roleplaying/Basic_Roleplaying.html
•	Removed a piece of coding that added a minor graphical glitch to the sheet.
•	Added Knockback attack types for melee weapons
•	Fixed the Alphabetic Perform Skill since it was still using the old pop-up windows
> Minor update for Basic Role Playing

- Best Left Buried/bestleftburied.html
- Best Left Buried/sheet.json
- Best Left Buried/translation.json
Two small fixes. 
One Typo and changed IMG Url to git hub main roll20
> Best left buried

- OperaRPG/operarpg.html
Changes on the roll template formulas
> [OPERA RPG]-Opera rolltemplate change

- Empire_des_cerisiers/EdC.html
- Empire_des_cerisiers/ReadMe.md
- Empire_des_cerisiers/sheet.json
Fix : incorrect helper stating 1 Gin equals 1000 mon instead of 100
Fix : Init bonus from field not updating on field level changed
Fix : Init mod from armor incorrect calculation
Updated : renamed number of attack / turn to number of action / turn
> [L'Empire des Cerisiers V1.2-3] Fix minor bug

- Empire-of-the_Petal_Throne/EPT.html
> Empire-of-the_Petal_Throne - Fix MU XP Bonus

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Adjusted Sequence equation.
Adjusted Unarmed, Intimidation, and Survival skill equation.
> Sequence Hotfix

- The One Ring/sheet.css
- The One Ring/sheet.html
- The One Ring/translation.json
- The One Ring/translations/en.json
> fix: cleaned up code

- Official Savage Worlds/SavageWorldsCharSheet.css
- Official Savage Worlds/SavageWorldsCharSheet.html
Simply adding a few more fonts.
> Official Savage Worlds v1.00.09 CSS Update

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
For some reason, combat rolls didn't work. They're fixed now.
> Fallout V&DPNP - Fixed Combat Rolls

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
The first combat box had an error.
Rewrote Sequence display.
> Combat - Hotfix 2

- The One Ring/sheet.html
- The One Ring/translation.json
> fix: calculating fields and a minor typo

- Burning Wheel/Burning Wheel.html
- Fixed Readme macro version number display error
> [Burning Wheel] Readme macro typo fix

- Best Left Buried/translation.json
> Update Best Left Buried translation.json

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th] fix broken import for edge and magic

- MechaAndMonsters/MechaAndMonsters.css
- MechaAndMonsters/MechaAndMonsters.html
- fixed alignment issues with sheet/background image and input fields.
> MechaAndMonsters alignment fix

- Starfinder (simple)/Starfinder (simple).html
corrected issue where NPC Sense Motive skill check did not roll.
> Starfinder (simple) bug fix 012721

- GoddessSaveTheQueen/goddesssavethequeen.html
- GoddessSaveTheQueen/translation.json
Just a minor fix on string on the sheet's html and in the base translation.json file.
I've already done the change on crowdin, but I think it will be better to fix on the base code as well.
> [goddess-save-the-queen]fixing string 'abilidade'

- Cyberpunk Vieja Escuela ES/Cyberpunk Vieja Escuela ES.css
- Cyberpunk Vieja Escuela ES/Cyberpunk Vieja Escuela ES.html
Now rolls are available (stats, skills and attack)
> [Cyberpunk Vieja Escuela ES] Rolls added

- CWOD-M20/M20.html
> [M20] Bugfix

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.css
- Old School Essentials - AAC/OSE-AAC.html
- Old School Essentials - AAC/sheet.json
- Old School Essentials - AAC/translation.json
- Add modifiers to attribute scores. Closes wesbaker#57
- Add roll button for NPC Reaction. Closes wesbaker#64
- Add spells tab. Closes wesbaker#63
- Add default sheet setting for default character type. Closes wesbaker#61
- Change rolltemplates to show character name. Closes wesbaker#58
- Change button hover color to orange for better contrast. Closes wesbaker#62
> [Old-School Essentials by Necrotic Gnome] - 1.9.0

- xenoscape/xenoscape.css
- xenoscape/xenoscape.html
Just aesthetic improvements
- [ x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
> [Xenoscape] aesthetic improvements

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
Split capacities into title + body, body can be unfolded
Update is performed through sheetworker.
> Chroniques Oubliees: version 4.04

- 3D&T_ALPHA/3D&T_ALPHA.css
- 3D&T_ALPHA/3D&T_ALPHA.html
> Novas Funcionalidades

- Pavillon Noir 2/Pavillon Noir 2.html
Oublie d'une { pour le jet de charisme
Forget a { for the charisma throw
> Update Pavillon Noir 2.html

- HeXXen1733/hexxen1733_community.html
Changelog at https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733/wiki/Changelog
Changed roll queries in hidden inputs are not stored in the sheet, so no migration was necessary
> [HeXXen 1733] Releasing v1.0.1

- DC_Heroes_MEGS/DC_Heroes_MEGS.html
Added initiative roll button
Fixed bug where text entered into journal field was not saved
- [ x] Is this a bug fix?
- [ x] Does this add functional enhancements (new features or extending existing features) ?
> DC_Heroes_Megs bugfix and initiative button

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
- Adds Triple Hit to the scatter type options
- Adds a roll template for Triple Hit moves
- Adds CSS to the new roll template
> [PokemonTabletopAdventures_v3] Adds support for triple hit scatter moves

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where the Death/Poison save incorrectly added the modifier. Fixes wesbaker#66
> [Old-School Essentials by Necrotic Gnome] - 1.9.1

- HeXXen1733/hexxen1733_community.html
- Skill "Hexenkunst" was not properly calculated
- Sheet-Worker was updated accordingly
> [HeXXen 1733] Hotfix: Fix calculation of Skill "Hexenkunst"

- Shadowrun2e/shadowrun2e.html
(Shadowrun 2e) Fixing minor Errors Added some attributes to avoid mirroring issue on one tab.
> Minor Updates to code, Fixing issues

- PokemonTabletopAdventures_v3/PTA3.css
- PokemonTabletopAdventures_v3/README.md
- Restores the correct CSS rules for the multi-hit roll template
> [PokemonTabletopAdventures_v3] Restores css rules for the multi hit roll template

- Shadowrun5thEdition/Shadowrun5thEdition.css
- Shadowrun5thEdition/Shadowrun5thEdition.html
> Shadowrun 5th Edition fix importer

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where the modifier inputs would throw validation errors when less than 0. Fixes wesbaker#67
- Fix a bug where the modifiers could be changed
> [Old-School Essentials by Necrotic Gnome] - 1.9.2

- 3D&T_ALPHA/3D&T_ALPHA.css
- 3D&T_ALPHA/3D&T_ALPHA.html
Adicionado novos templates pra melhorias no testes e mensagens do chat
> novos Templates

- xenoscape/xenoscape.css
- xenoscape/xenoscape.html
> [Xenoscape]  aesthetic improvements

- Dragon-Age-RPG-PT-BR/Dragon AGE RPG (PT-BR).css
- Dragon-Age-RPG-PT-BR/Dragon AGE RPG (PT-BR).html
> Fixing issues and change fonts

- D6StarWars/CHANGELOG.md
- D6StarWars/D6StarWars.css
- D6StarWars/D6StarWars.html
- D6StarWars/sheet.json
*  add missing lightsaber dmg roll
> [Star Wars D6] v2.32

- Shadowrun2e/shadowrun2e.html
> Shadowrun 2E update-Format issue please push ASAP

- Tierras Quebradas/tierrasquebradas.css
- Tierras Quebradas/tierrasquebradas.html
> [Tierras Quebradas] Bugs fixed

- 3D&T_ALPHA/3D&T_ALPHA.css
- 3D&T_ALPHA/3D&T_ALPHA.html
- correção do CSS
- correção dos testes dos templates
> Correção gerais

- Shadowrun2e/shadowrun2e.css
- Shadowrun2e/shadowrun2e.html
Elements no longer collapse when windows resized.
Roll Templates changed/added to match sheet colours.
Extra Dice pools added for more flexibility/other use.
> Shadowrun 2E update css/html added features

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th] experimental language independent import

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th] add custom drain roll to drain-attribute

- LANCER RPG (1.8)/LANCER.html
Adds functionality for npcs and gives players more options that were lacking in current version
Note this shouldn't affect any player sheets as doesn't change the core values past ones you would changing a lot in play. 
The exact changes are one, added more sizes for players to use as previously it didn't go up to the maximum npcs can get to. 
Added more accuracy/difficulty to the choice select so players with specific builds can utilize there accuracy properly 
> Lancer sheet update 

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.css
- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Added some more helpful tools for players!
Removed some needless CSS chains.
> CP-Unofficial-Persona-TTRPG

- Das_Schwarze_Auge_5_Tsa_Edition/README.md
- Das_Schwarze_Auge_5_Tsa_Edition/dsa5.css
- Das_Schwarze_Auge_5_Tsa_Edition/dsa5.html
- add a css fix
- add a new option for ae/le base values
> [Das_Schwarze_Auge_5_Tsa_edition] small fixes

- Don't Rest Your Head/dontrestyourhead.html
- Don't Rest Your Head/sheet.json
Add space for 4 scars.
Add temp madness modifier to dice roll (sheet only keeps track of permanent madness and then asks for extras which are then removed)
- [N/A] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
> Don't rest Your Head edits

- Pathfinder Community/pathfinder_community.css
> PF Community: fix for hovering over the attack roll details.

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] improvements to import

- Shadowrun2e/shadowrun2e.html
Vehicle/Drone seperated into seperate tabs.  Layout Cleaned up.
Decks Layout Cleaned up.
> Shadowrun 2e Update, Decks/Drones/Vehicle Layout

- 3D&T_ALPHA/3D&T_ALPHA.html
Correções de bug , melhora de textos e acrescimos de novos testes para templates das mensagens do Chat
> Update 3D&T Alpha - Templates

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Moved around initiative and attacks on main tab
- Enhanced the equipment properties parsing 
- Added a button on the vehicle sheet to generate default rolls
> ChroniquesOublieesContemporain v3.8

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Moved around initiative and attacks on PC sheet
- Moved around Hit Points, Damage Resistance on PC sheet
- Added Recuperation Points with max and current values
- Added "Space Fantasy" checkbox on Configuration tab
- Added Magic Attack bonus and Mana Points if 'Space Fantasy' box is checked on PC sheet 
- Enhanced the equipment properties parsing
> ChroniquesGalactiques v3.111

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
Reverts Roll20/roll20-character-sheets#8327
Sorry can you please revert this change ASAP.
typo is breaking the JS code
> Revert "[Warhammer 4e Character Sheet] Channel button label fix"

- Shadowrun2e/shadowrun2e.css
Update to CSS for most recent HTML change.
Forgot to chgange CSS to match recent HTML changes.  This fixes issues.
> Shadowrun2e CSS update

- AGE System/AGE System.html
With my last commit for fixing translations on roll queries, unfortunately, had broken the whisper roll feature. This update was made to fix that.
It's a really minor and simple fix.
> [AGE System]fixing whisper roll feature that was broken with last commit.

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix safeguard

- Call_of_Katzulhu_7th_Ed - German/cok_7th_ed.html
> [Call of Katzulhu] fix wrong values and minor improvements

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
> Minor bug fix with crimsonparcelsupttrpg.html (CP-Unofficial-Persona-TTRPG)

- Serenity/serenity.css
- Serenity/serenity.html
* Add skills tooltip with competency levels and roll difficulties
- [] Is this a bug fix?
- [] Does this add functional enhancements (new features or extending existing features) ?
> Serenity: Add skills tooltip with competency levels and roll difficulties

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.css
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
Removed sheetworker logic to reformat abilities descriptions
> ChroniquesOublieesContemporain Version 3.8.1

- Serenity/serenity.css
- Serenity/serenity.html
- Serenity/sheet.json
* Didn't realize data attributes are stripped, replaced with extra HTML
* Fixed oversized font in Skills tooltip
* Centered some skills tooltip table data
- [] Does this add functional enhancements (new features or extending existing features) ?
> Serenity: Remove data attributes, fix font css

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Vehicle Resistance boxes were condensed to one.
Vehicle Condition Marks were removed.
> Vehicle Resistance - Fallout V&DPNP

- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
Small cosmetic changes + one bug fix.
> Chroniques Oubliees: small adjustments and fixes

- Deadlands Classic/deadlandsclassic.html
Updated names of Common Rolls.
Added description of General Perception roll including order of modifiers.
Added a Location roller separate from any particular attack/damage roll.
> Update Deadlands Classic (again, sorry)

- Serenity/serenity.css
- Serenity/serenity.html
* Fix font sizing for skills tooltip
- [] Does this add functional enhancements (new features or extending existing features) ?
> Serenity: Fix font sizing for skills tooltip

- SvardOchSvartkonst/svardsvartkonst.css
Updated link to background image. Now it points to Roll20 repository, not the authors repository.
The character sheet/css is now not dependent on my fork on Github anymore.
> Svärd & Svartkonst image link update

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
_Starship sheet_
- Corrected a bug on attack rolls (when a new weapon line is added and no gunner is set up)
- Corrected Initiative calculation to handle an un-manned starship
- Added an attribute field for the lost energy points (@{PEV_DMG}) and modified the max energy points calculation
> ChroniquesGalactiques Version 3.113

- 3D&T_ALPHA/3D&T_ALPHA.html
Melhorias no código dos templates;
novo templete pra teste de defesa;
> 3D&T-Alpha update

- AD&D 2E Revised/2ESheet.html
- AD&D 2E Revised/raw/2ESheet-raw.html
Changed number field back to text
> Changed @{hitdice} field back to text from integer

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] add some more helpful texts to import

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix some typos in text

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] add error message to invalid structure

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] add import for contacts

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] make rituals language independent

- ChroniquesOublieesContemporain/sheet.json
Since I am the only author working on this character sheet, I updated the sheet.json in the hope of getting the "Sheet Author" badge on the Roll20 forums ;-)
> ChroniquesOublieesContemporain

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Added an option to switch between having a +4 max and a +8 max to rolls.
Discarded some old terms.
Switched the order of some things
> Updated HTML (CP-Unofficial-Persona-TTRPG)

- Quest-boardgame/Quest.css
- Quest-boardgame/Quest.html
Larger type
Drop down for monsters
Skip turn tracker
- [ X] Does this add or change functional aesthetics (such as layout or color scheme) ? 
> Adjustments

- Cultos-innombrables-hitos/HITOS.html
corrected typo, just a letter converted "points" to a mean word in Spanish.
> Cultos-innombrables-hitos: corrected typo.

- ChroniquesOubliees/co.html
> Chroniques Oubliees: bug fix on skill.

- 3D&T_ALPHA/3D&T_ALPHA.css
- 3D&T_ALPHA/3D&T_ALPHA.html
> 3D&T ALPHA - Templates novos

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
> CP Unofficial Persona TTRPG (Small fix)

- Deadlands Classic/deadlandsclassic.html
> Deadlands Classic: roll name fix.

- 3D&T_ALPHA/3D&T_ALPHA.html
novo teste e melhoria de templates
> Template 3D&T Alpha

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import notes and ratings for qualities

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] make sensible logs to narrow done errors

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] add subheader to rolltemplate

- 3D&T_ALPHA/3D&T_ALPHA.html
Update pra a versão final:
aplicação de testes de atributos, defesas e ataques para a nova versão dos templates, correção de textos e nova funcionalidade de menu de defesa.
> Updade 3D&T Alpha final

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] increase imported weapons to 8

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] make experimental features public available

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import notes of spells

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix read of experimental

- ButterflyAspect/ButterflyAspect.html
Typos and spelling errors fixed
> [ButteflyAspect] Typos and spelling errors fixed

- .gitignore
- 13th Age Glorantha/13th_Age_Glorantha.html
- 13th Age Glorantha/src/13th_Age_Glorantha.html
Pull Request on behalf of user @speque who made all of the edits
- Fixed disabled number input field controls on Chrome
- Centered dropdown text on Chrome
- Replaced triangle glyph with a triangle Unicode character 
> [13th Age Glorantha] Bug fixes & improved browser / OS compatibility

- Warhammer Fantasy Roleplay 4e Official/src/js/sheetworkers.js
- Warhammer Fantasy Roleplay 4e Official/src/pug/wfrp4.pug
- Warhammer Fantasy Roleplay 4e Official/wfrp4.html
If you do not know English. Please leave a comment in your native language
> [Warhammer Fantasy Roleplay 4e Official] Fixing Typo in Initiative Roll

- Daemon Exilia/Bug.txt
- Daemon Exilia/sheet.json
> Daemon Exilia, Atualização json

- 3D&T_ALPHA/3D&T_ALPHA.html
Correção de texto duplicado na guia de magias.
Criado nota de roda-pé da editora e desenvolvedor
> FIx 3D&T Alpha

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] add experimental import of ai programs

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix delete and import of contacts

- Kalymba/Kalymba.css
Alteração da imagem de Background da ficha
> Upgrade Kalymba

- Shadowrun6th-German/sheet.html
Initiative (Physical) now roles with correct ini-dices
- [ X] Is this a bug fix?
> Shadowrun6th-German Initative Hotfix

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] simplify naming scheme in delete logic

- Quest-boardgame/sheet.json
> Use legacy sanitization for the Quest boardgame

- Torchbearer 2E/torchbearer.html
Give players the ability to roll their Beliefs, Goals, Creeds and Instincts into the chat
Allows you to post BIGs into the chat
> Torchbearer 2E Add BIGs to chat

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix "for" init

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] allows armor rating with +

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
> Update crimsonparcelsupttrpg.html (CP's Unofficial Persona TTRPG)

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
CM wasn't saving for some reason.
> Fallout V&DPNP - Condition Marks Hotfix

- Invisible Sun/invisiblesun.html
> Invisible Sun: Turning the Certes and Qualia labels into reset buttons

- Call_of_Katzulhu_7th_Ed - German/cok_7th_ed.html
> [Call of Katzuhlu] fix dmg die of natural weapons

- Kult/sheet.json
> [KULT] Update sheet.json

- Prowlers-n-Paragons/prowlersnparagons.html
Added Agility, Covert, Intellect, and Investigation to the character sheet.
> Prowlers and Paragons Fix

- Buried Secrets/buried.css
- Buried Secrets/buried.html
- Buried Secrets/sheet.json
This is a short fix to switch from the legacy character sheet layouts to the new system. Mostly CSS changes (removing 'sheet-' prefix)
> Upgrade [Buried Secrets] to work with new layout guidelines

- Mork Borg/morkborgsheet.html
- Adds an enemy armor function to weapon rolls
Needs to be verified, I am not a PLUS subscriber
> [Mörk Borg] add enemy armor to weapon rolls

- ShadowbaneInquisition/Shadowbane.css
- ShadowbaneInquisition/Shadowbane.html
fixed missing attribute for damage roll
> [shadowbane inquisition] bug fixes

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Added Max corruption modifier to allow for Pure Soul and other effects to be integrated in the sheet.
> [Warhammer 4e Character Sheet] v1.35 max corruption update

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix import of ammunition

- T2K 4e/twilight-2k-4e.css
Current
Fix
This issue made the sheet effectively unreadable. It's not universal, other players were not affected. I suspect either browser or monitor resolution. This change has minimal effect on the rest of the sheet layout.
> [T2K 4e] Fix for dropdown spacing

- HackMaster_4E/hm4e.css
- HackMaster_4E/hm4e.html
Sheet: HackMaster_4E
Changed method of doing the Tabs
Added Combat Roll Template
> SHEET: Hackmaster_4E, Removed use of Google fonts due to Roll20 bug (broke tabs)

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] add a flag for nightly functionality

- Mothership Official/sheet.json
> [Mothership Official] Fixing Legacy Support

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] allow output of multiple errors

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import alias as name

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix import of weapon ap

- Ryuutama/Ryuutama.css
> [Ryuutama]: Fix font

- D6StarWars/CHANGELOG.md
- D6StarWars/D6StarWars.html
- remove duplicated control force power name field
- fix force power section width
> [D6StarWars] v2.33

- Mork Borg/morkborgsheet.html
- update to weapon roll prompt to be more clear
> mork-borg: update enemy defense prompt

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/sheet.json
> [Shadowrun 5th Advanced] move to non-legacy

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import rating and extras of gear

- Monsterhearts-2/Monsterhearts-2.html
> [Monsterhearts 2e] Resolving issue with Playbooks

- Fading Suns 4th Edition - Pax Alexius/Fading_Suns_4th_Edition_Pax_Alexius.css
- Fading Suns 4th Edition - Pax Alexius/Fading_Suns_4th_Edition_Pax_Alexius.html
- Fading Suns 4th Edition - Pax Alexius/README.md
- Fading Suns 4th Edition - Pax Alexius/prepros.config
- Fading Suns 4th Edition - Pax Alexius/src/Fading_Suns_4th_Edition_Pax_Alexius.pug
- Fading Suns 4th Edition - Pax Alexius/src/Fading_Suns_4th_Edition_Pax_Alexius.scss
- Fading Suns 4th Edition - Pax Alexius/src/prepros.config
- Fixed auto-height of description boxes of perks/capabilities/items/etc, which were sometimes not high enough thus requiring a vertical scroll.
> Fading Suns 4th Edition - Pax Alexius - v1.2.1

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] delete ammunition when it is imported

- Shinobi_Gami_Chinese_Traditional/sheet.json
>  Shinobi_Gami_Chinese_Traditional/sheet.json  fix error

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
Quick fix for latest changes, found during video preparation.
* **Fixes**
* Shield attack AT value now affected by wounds (76335493a28b1cb764071da55b4aed296a2dd612)
> [Das_Schwarze_Auge_4-1] Fix: Shield Attack AT value unaffected by wounds

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import of contacts leaves experimental phase

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import of cyberdeck - experimental

- Die_Schwarze_Katze/Die_Schwarze_Katze.css
- Die_Schwarze_Katze/Die_Schwarze_Katze.html
- Die_Schwarze_Katze/sheet.json
Adds support for non player characters (NPCs). This update will add the possibility to use the character sheet for NPCs. It also provides some minor updates.
> Die_Schwarze_Katze - Add support for NPCs

- SLA Industries 2ed/sheet.json
- SLA Industries 2ed/sla.css
- SLA Industries 2ed/sla.html
Added in the actual link to the logo, now that it is on the roll20 repository I can link to the logo on the character sheet
Fixed link to Nightfall games website
- [No ] Does this add functional enhancements (new features or extending existing features) ?
- [No] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [None] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [Not a new sheet] If this is a new sheet, did you follow [Building Character Sheets …
> SLA Industries - 2ed - Minor fixes

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced]fix minor errors

- PokemonTabletopAdventures_v3/PTA3.html
- PokemonTabletopAdventures_v3/README.md
Import/Export support for character sheets in roll20. Primary use case is to allow Pokemon created with the "Pokelicious" Google Sheets to be imported into roll20 games.
> PokemonTabletopAdventures_v3 Import/Export Support

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Combat Page only applies +/- for Support Skills instead of the Total so we removed them from the Combat page.
> [Fallout Vaults and Deathclaws] Support Skill Error

- Knight/knight.html
> [Knight] Bugfix import

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] fix rolltemplate wounds

- Farsight RPG Community Edition/sheet.json
- Changed legacy field to false for future updates and to make work actual styling.
- Corrected some errors in instructions field.
> [Farsight RPG Community Edition]Updated and corrected sheet.json

- Heroes-Unlimited-2E/hu2.html
I'm working on getting the stats to be able to roll for your stat.
> Working on getting the dice roller for each stat

- Knight/knight.html
> [Knight] Bugfix import #2

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] make ammo import compatible with latest stable

- thordezilhas/thordezilhas.html
Foram realizadas as alterações:
nome Raça para Povo;
nome Classe para Arquétipo;
remoção do atributo Interações Sociais, pois ele não existe mais no sistema
> [Thordezilhas] Atualização de nomenclatura de povo e arquetipo

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] show negative modifier in rolltemplate

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] import notes of metamagics

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
Corrected a bug on the title of rank 3 ability in skill branch 3 duplicated in skill branch 8
> ChroniquesOublieesContemporain Version 3.9.1

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
* **Fixes**
* Parry value of active weapon always 0 (8ef92ddf209566383d85f19e447348c4c8cedf4c)
* Shield parry not available due to typo (a946cdac95e6e9c3645ca578fe3ec1e951edfbba)
* Shield attack/parry not available when wound modifiers not existant (3d4e22f1a6968e17f88a84ec644eb54affbbe7d1)
* Hardening of attribute checks/comparisons (61ac5c90d2d42ab7681d8b083536bf60bd422eee, e81174ba2c04e618f454ae4a36c82c0db9702ec8)
* **Miscellaneous**
* Bump version number (3d4e22f1a6968e17f88a84ec644eb54affbbe7d1)
* Add description for latest changes (badf5509a978c4a3bf727a1bbca5eeca2ff7083d)
> [Das_Schwarze_Auge_4-1] Bug Fixes

- HackMaster_4E/hm4e.html
New Feature: Pixie Fairy Variants from Pixie Fairy Splat book
Functional Enhancement: To Hit and Damage Roll Templates
Functional Enhancement: Better Roll templates for most other rolls.
> Sheet: Hackmaster_4E, Add Pixie Variants, Add To Hit / Damage Templates

- Anime Campaign/Anime_Campaign.html
The logo url has changed. I just want to update it to the new one.
> Logo Update

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun 5th Advanced] armor as repeating row

- Starfinder (simple)/Starfinder (simple).html
Added two rows to augmentations section (per user request)
Cleaned up code spacing for the Augmentations section (no changes made to attribute names)
> Starfinder (simple) update 04262021

- Only-War-Enhanced/OnlyWarEnhanced.html
I broke the js and it needs fixed
fixed a fatally bad error
> [Only War Enhanced] Bug Fix

- Crescent/crescent.html
-Fixed the formula for calculating additional Technique Points.
-Added misc Action Points and Combat Stamina modifiers
-Added "Other" recharge option
-Fixed Mook TP wording
> Crescent: Bugfixing TP and adding more misc modifiers

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] migrate with flag instead of deleting values

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Corrected a bug on the skill branch 2, rank 4 ability title
- Corrected a bug in the computing of a rank in a skill branch : the box must be checked and either the title or the text of the ability must be specified
> ChroniquesOublieesContemporain Version 3.9.2

- barbaric-error
* maybe something went wrong with the `approved.yaml`, or it's because #8795 haven't been merged, and the sheet doesn't have all it's translation fies
* Jackals, the other sheet merged today, shows up properly
> Barbaric! sheet doesn't show up properly in the dropdown

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Corrected a bug on the skill branch 3, rank 3 ability title duplicated in skill branch 8
- Corrected a bug on the skill branch 2, rank 4 ability title
- Corrected a bug in the computing of a rank in a skill branch : the box must be checked and either the title or the text of the ability must be specified
> ChroniquesGalactiques Version 3.114.1

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] catch weird behaviour with missing armor attributes HOTFIX

- Mongoose_Traveller2e/MongooseTraveller.html
Modified the roll queries so that translated items are used.
> [Mongoose_Traveller2e] Add translations to roll queries

- Heroes-Unlimited-2E/hu2.css
- Heroes-Unlimited-2E/hu2.html
I reworked the IQ stat roll button submitted by elirjo so that it won't displace stat input fields.
I created stat check roll buttons for all the other stats, and included the css to style the roll buttons. 
> Heroes Unlimited 2E

- AD&D 2E Revised/2EStyle.css
CSS fix to overwrite base Roll20 styling. Forum postes here:
https://app.roll20.net/forum/permalink/10027218/
https://app.roll20.net/forum/permalink/10029180/
> [AD&D 2E Revised] Fixed styling for summary

- SLA Industries 2ed/sheet.json
- SLA Industries 2ed/sla.css
- SLA Industries 2ed/sla.html
I have fixed the number layout issue, so all the numbers fix in the layout of the character sheets
Improvements to the number formats - I have removed the spin buttons - the number fields still increase and decrease using the up and down buttons- but the format is tidier and fits in the character sheet layout
- [No layout improvements] Is this a bug fix?
- [No] Does this add functional enhancements (new features or extending existing features) ?
- [Yes  -monir layout improvement] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [No changes] If changing or …
> [SLA Industries 2ed] - Layout Improvement

- Chroniques_De_L_Etrange/CdE.html
> [CdE] Bugfix

- 3D&T_ALPHA/3D&T_ALPHA.html
Correção de teste de perícias.
> 3D&T-ALPHA Fix test

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix regression with armor migration

- Basic_Roleplaying/Basic_Roleplaying.html
Fixing the check box so that it saved even after you close the sheet.
- [ x ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ x ] Is this a bug fix?
> [Basic Roleplaying System] Minor Bug Fix for the POW check box

- Star Wars Revised RPG/SWRRPG.html
The initiative roll was being sent to the turn tracker
Yes
Yes
No
no
N/A
N/a
> Star Wars Revised RPG: Send initiative roll to the tracker

- thordezilhas/thordezilhas.css
- thordezilhas/thordezilhas.html
Foram realizadas melhorias visuais na ficha de Thordezilhas
> [Thordezilhas] Melhorias visuais

- approved.yaml
* Attempted fix, as described in [Issue #8860](https://github.com/Roll20/roll20-character-sheets/issues/8860) / (roll20 support ticket `#56192` created earlier today)
* edited sheet doesn't currently work in the dropdown selection, so this has a chance of fixing things, but can't make it worse
* not likely to actually fix anything
> possible fix, revert manual edit

- Barbaric/Readme.md
- Barbaric/barbaric.css
- Barbaric/barbaric.html
- Barbaric/sheet.json
- Barbaric/src/barbaric.scss
* visual fix for spanish version
* update sheet.json desc
> [Barbaric!] visual fix for spanish version

- Anima-Beyond-Fantasy/A-BF.html
> [Anima] Bugfix

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] prepare import of attributes to changed export

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] add a note where to report bugs

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] import max of rc and ac when importing weapons

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] importing ai programs is no longer experimental

- Awfully Cheerful Engine!/ace.html
minor fix to buttons.. ensuring for spaceships the correct statistics are rolled
- [No just change to button labels] Does this add functional enhancements (new features or extending existing features) ?
- [No] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [No changes] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [Not a new sheet] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sh …
> [Awfully Cheerful Engine] fixed spaceship rolls

- Ashen_Stars/Ashen_Stars.css
- Ashen_Stars/Ashen_Stars.html
- Fix the broken header image URL
- Make ability tables show up beside each other (in two columns) again
- Add missing "Flirting" ability (see [character sheet](http://site.pelgranepress.com/wp-content/uploads/2011/10/character%20sheet.pdf))
- Make general abilities boostable (see [Species Cheatsheet boosts](http://site.pelgranepress.com/files/Ashen_Stars/Species_Cheat_Sheet.pdf) for the Durugh, Humans, etc.)
- Made popper checkboxes load properly (would always start unchecked when opening sheet)
- Fix typo ("Vioware" -> "Viroware", see [character sheet](http://site.pelgranepress.com/wp-content/uploads/2011/10/character%20sheet.pdf))
If you do not know English. Please …
> [Ashen Stars] Visual and functional bugfixes

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] handle empty role of contact

- Only-War-Enhanced/OnlyWarEnhanced.css
- Only-War-Enhanced/OnlyWarEnhanced.html
Adds a "demeanor" blank to Comrades, near "Status"
> (Only War Enhanced) Add "demeanor" to Comrades

- Dragon Ball Universe/DragonBallV2.html
Fixed a small bug in the code. The hidden power attribute is now encased in [[]] so, when it crits it doesn't light up the roll.
Also added a new race called Shinjin.
- [YEs] Does the pull request title have the sheet name(s)? Include each sheet name.
- [Yes] Does this add functional enhancements (new features or extending existing features) ?
- [No] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N/A] If this is a new sheet, did you follow [Building Character Sheets …
> Added Shinjin race and fixed small bug error - Dragon Ball Universe

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] enable import of contacts again after fixing the bug

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] show limit mod only when not zero

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Fixed an issue with Condition Marks being copied on three parts of the sheet.
> Armor Condition Hotfix - Fallout VNDPNP

- YnnPryddein/sheet.json
Correction in sheet.json, from legacy=true, to legacy=false
> Ynn Pryddein: correction to sheet.json

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] micro flares are not tagged as ammunition

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] handle contacts without names

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] handle import of weapon without dv

- World Wide Wrestling 2nd Ed/wwwrpg.css
- World Wide Wrestling 2nd Ed/wwwrpg.html
Added a missing radio button style (alignment related.) Switched to using version 1 of the Google Fonts API and remove some unused weights from the import. Perhaps only coincidentally, this change seems to have allow the Sheet Validator check to pass in the Pull Request.
Renamed an option in the Move roll type dropdown. Variable value is still the same so it won't affect any existing sheets. The wording is no longer cut off when selecting it improving the appearance.
Consolidate sheetworker scripts as suggested by Nic B.
> World Wide Wrestling 2nd Ed - FIX for sheet validator - Change Google Fonts to API version 1 + Minor adjustments

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] when importing stats import all digits

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] repair import of martial arts

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
> Unofficial Persona TTRPG (Update crimsonparcelsupttrpg.html)

- Knight/knight.css
- Knight/knight.html
> [Knight]Bugfix Import + VIsual Bugfix

- GURPS/gurps.css
GURPS/gurps.css
- Minor change to Tabs. The Width will adjust according to the title length.
In other languages the length may be longer.
See: https://app.roll20.net/forum/permalink/10094355/
> [GURPS] Update

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Added Personality and Vault Limit.
> New Secondary Stats - Fallout V&DPNP

- DungeonWorldSpanish/sheet.json
Small fix to sheet.json description that shows on the initial game creation page.
> fix minor typo on sheet.json text

- Tephra/Tephra.css
[fixes requested here](https://github.com/Roll20/roll20-character-sheets/issues/8905)
The header image was broken, but now it is fixed. I did have to resize so that it looked right.
Also, the chosen font was not the best (for multiple reasons, detailed in the referenced issue).
Tephra
> Updated Tephra Character sheet

- Horror Movie World/hmwSheet.html
> fix layout for Horror Movie World character sheet

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] remove disfunctional reload button

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] add after 3 to rolltemplate

- Knight/knight.css
- Knight/knight.html
- Knight/translation.json
> [Knight]Bugfix i18n + Bugfix Geste

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] make single clip import backwards compatible

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] add repeating weapons after fixed eight

- The Villainy/villainy.css
- The Villainy/villainy.html
Renamed css styles to fix layout problems in the charsheet.
- [+] Does the pull request title have the sheet name(s)? Include each sheet name.
- [+] Is this a bug fix?
- [-] Does this add functional enhancements (new features or extending existing features) ?
- [+] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [-] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
If you do not know English. Please leave a comment in …
> [The Villainy]fixed popup styles names;

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] restyle weapon area

- The Villainy/sheet.json
Changed legacy mode to use new features.
> [The Villainy]fixed legacy mode

- CortexPrime-Tales-of-Xadia-Playtest/ToX-CortexPrime.html
Fixes to a few errors
Portraits/distinctions/assets associating with wrong character name
Missing specialty Cooking
> [Tales of Xadia] Fix

- ShadowbaneInquisition/README.md
- ShadowbaneInquisition/Shadowbane.css
- ShadowbaneInquisition/Shadowbane.html
+ fixed bug in soak calculation
+ started refactoring
> [Shadowbane Inquisition] Update V0.1.4

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] import critter powers as spells

- Mongoose_Traveller2e/MongooseTraveller.html
- Mongoose_Traveller2e/translation.json
Use translations for the roll template labels (attributes and skills)
> [Mongoose_Traveller2e] Translate roll template labels

- Ludosystem/ls-style.css
- Ludosystem/ludos-sheet.html
- Ludosystem/sheet.json
> [Ludosystem] need to fix some roll issues on the sheet

- CortexPrime-Exiles/Exiles-CortexPrime.css
- CortexPrime-Exiles/Exiles-CortexPrime.html
- CortexPrime-Exiles/readme.md
Fixed the dice icons in the Distinctions and Hinder SFX
Made the Dice roller visible, was only showing in the edit feature.
> [Exiles - Cortex Prime]

- Monster of the Week Official/MotWHTML.html
A small fix to eliminate an accidental duplicated variable name in the Hex playbook
> [Monster of the Week Official] Hex fix

- Knight/knight.html
> [Knight] Add Update Import

- RatasEnLasParedes/RatasEnLasParedes.css
- RatasEnLasParedes/RatasEnLasParedes.html
* closes #9038
* fix input width, as requested in above issue
> [Ratas en las Paredes] fix input width

- T2K 4e/twilight-2k-4e.css
- T2K 4e/twilight-2k-4e.html
* stamina roll now shows correct name
* update url to point to main repo
> [twilight 2000 4E] stamina roll fix

- Nephilim-Legende/nephilim-legende.html
> [Nephilim Legend]Bugfix

- World Wide Wrestling 2nd Ed/wwwrpg.css
- World Wide Wrestling 2nd Ed/wwwrpg.html
Added functionality to event/match log for tag team matches.
> World Wide Wrestling RPG 2nd Ed - Enhancement to Event/Match Log

- T2K 4e/twilight-2k-4e.html
* update weapon Reliability select from alpha rules "A-D" to newer rules  "0-5"
> [Twilight 2000 4E] update weapon Reliability

- Ysystem/ysystem.css
- Ysystem/ysystem.html
- Fix range attack bug, added experience points tracker
> Ysystem - Minor fixes

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
ST -> STR
PE -> PER
EN -> END
CH -> CHA
IN -> INT
AG -> AGI
LK -> LCK
> Fallout PNPV&D - SPECIAL Rename

- ShadowbaneInquisition/README.md
- ShadowbaneInquisition/Shadowbane.css
- ShadowbaneInquisition/Shadowbane.html
- ShadowbaneInquisition/SheetWorker.js
- ShadowbaneInquisition/sheet.json
+ Switching to CSE
+ Started adding Datalist
+ Fixed unpleasant CSS
+ Fixed bug in weapon weight calculation
> [Shadowbane Inquisition] switching to CSE

- CWOD-Vampire/Vampire.css
- CWOD-Vampire/Vampire.html
This is a visual update for a VtM Revised sheet.
CSS Grids were placed for many grid-like elements that previously were structured with simple columns and the like (this lead to character sheet reacting very unpleasantly to width change). Now it is structured better.
Visual style of some elements (mainly inputs and textfields) was changed into a more clean and readable state.
Also, all styles were moved from HTML file into CSS one.
> [CWOD-Vampire] Visual Upgrade (Migration to CSS Grid)

- Knight/knight.css
- Knight/knight.html
> [Knight] Bugfix Vehicule

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Vastly improved performance of Target value re-calculations due to condition changes, by moving them to the sheet worker. This was particularly bad on Firefox, while MS Edge(Chromium) and Chrome were less impacted but also benefit from the changes. No actual changes in functionality just faster!
> [Warhammer 4e Character Sheet] v1.41 Performance

- cepheus-atom/sheet.css
- cepheus-atom/src/scss/_core.scss
> [Cepheus Atom] fix weapon section width

- CWOD-Vampire/Vampire.css
- CWOD-Vampire/Vampire.html
This pull request corrects column gap, reducing minimal gap to a more sensible value.
Also, this PR includes small visual changes, that make Willpower dots look better.
> [CWOD-Vampire ] Make character sheet narrower

- The Troubleshooters/TheTroubleshooters.html
- The Troubleshooters/sheet.json
Discrepancy between formatting in Sandbox and live - changed logo image URL and updated legacy setting in .json to resolve
> Update to fix formatting issue

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Initiative penalty display not functioning correctly fixed.
> [Warhammer 4e Character Sheet] 1.41 Initiative penalty fix

- Knight/knight.html
> [Knight]Bugfix

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/aaronscript.js
- Shadowrun5th/js/import.js
- Shadowrun5th/js/initAndMigrateSheet.js
- Shadowrun5th/js/script.js
> [Shadowrun5thA] gear extras and cyberdeck no longer experimental

- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix for combat paralysis breaking initiatives
- [ YES ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ YES ] Is this a bug fix?
- [ NO ] Does this add functional enhancements (new features or extending existing features) ?
- [ NO ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ NA ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ NA ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
If you do not know English. Please leave a comment …
> Shadowrun Sixth World

- ButterflyAspect/ButterflyAspect.html
- typo
- add title to checkbox
> [Butterfly Aspect] small fixes

- Brindlewood Bay/BrindlewoodBay.css
> [Brindlewood Bay] Fixed image links

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Created an option for a d20 variant. Also raised a cap to allow for higher modifiers.
> Unofficial-Persona-TTRPG (crimsonparcelsupttrpg.html)

- TheWitcher/witchersheet.html
> [TheWitcher] give crit/fumble button a name

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix fallback for older chummer version

- Mothership Official/sheet.json
> Mothership Official | Update Sheet.json

- TheWitcher/translation.json
- TheWitcher/translations/af.json
- TheWitcher/translations/ca.json
- TheWitcher/translations/cs.json
- TheWitcher/translations/da.json
- TheWitcher/translations/de.json
- TheWitcher/translations/el.json
- TheWitcher/translations/en.json
- TheWitcher/translations/es.json
- TheWitcher/translations/fr.json
- TheWitcher/translations/he.json
- TheWitcher/translations/hu.json
- TheWitcher/translations/it.json
- TheWitcher/translations/ja.json
- TheWitcher/translations/ko.json
- TheWitcher/translations/nl.json
- TheWitcher/translations/pl.json
- TheWitcher/translations/pt.json
- TheWitcher/translations/ru.json
- TheWitcher/translations/sl.json
- TheWitcher/translations/sv.json
- TheWitcher/translations/tr.json
- TheWitcher/translations/uk.json
- TheWitcher/translations/zh.json
- TheWitcher/translations/zu.json
- TheWitcher/witchersheet.css
- TheWitcher/witchersheet.html
> [TheWitcher] incorporate crit into roll

- ShadowrunAnarchy/ShadowrunAnarchy.html
Gave each button a proper name, starting with roll_, so they can be used properly in roll20.
Named each rollbutton properly (adding roll_) and gave each button a unique name (adding NPC to npc buttons) so that they work properly in roll20.
> ShadowrunAnarchy

- Doctor Who Adventures in Time and Space/DoctorWho.css
display in fire fox of radio buttons bleed onto next line.
- [y ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ y] Is this a bug fix?
- [ n] Does this add functional enhancements (new features or extending existing features) ?
- [ n] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [n/a ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
If you do not know English. Please leave a comment …
> who-bug/player-container-202106

- TheWitcher/translation.json
- TheWitcher/translations/af.json
- TheWitcher/translations/ca.json
- TheWitcher/translations/cs.json
- TheWitcher/translations/da.json
- TheWitcher/translations/de.json
- TheWitcher/translations/el.json
- TheWitcher/translations/en.json
- TheWitcher/translations/es.json
- TheWitcher/translations/fr.json
- TheWitcher/translations/he.json
- TheWitcher/translations/hu.json
- TheWitcher/translations/it.json
- TheWitcher/translations/ja.json
- TheWitcher/translations/ko.json
- TheWitcher/translations/nl.json
- TheWitcher/translations/pl.json
- TheWitcher/translations/pt.json
- TheWitcher/translations/ru.json
- TheWitcher/translations/sl.json
- TheWitcher/translations/sv.json
- TheWitcher/translations/tr.json
- TheWitcher/translations/uk.json
- TheWitcher/translations/zh.json
- TheWitcher/translations/zu.json
- TheWitcher/witchersheet.css
- TheWitcher/witchersheet.html
Reverts Roll20/roll20-character-sheets#9130
> Revert "[TheWitcher] incorporate crit into roll"

- Malefices/malefices.html
Correction orthographique (gave -> Grave) dans les résultats de test.
> [Maléfices] update

- TheWitcher/translation.json
- TheWitcher/witchersheet.css
- TheWitcher/witchersheet.html
> [TheWitcher] incorporate crit into roll and add fumble to rolltemplate

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] prepare drainattribute import for nightly

- TheWitcher/witchersheet.html
> [TheWitcher] add more rollnames to quick buttons

- mutant_cronicles_3/CHANGELOG.md
- mutant_cronicles_3/mc3.css
- mutant_cronicles_3/mc3.html
Image hosting changed to roll20 github repo.
> [Mutant Chronicles 3] Image host changed

- TheWitcher/witchersheet.html
> [TheWitcher] reorder fast strikes template

- HarnMaster3/harnsheet.html
- HarnMaster3/harnstyle.css
Fixed a bug in calculating effect of being mounted. Incorporated suggestions from the community (mainly some wording changes). Also made sure to bump version number and include changes for this and previous minor tweaks in the changelog.
> [HarnMaster3] Minor tweaks2

- TheWitcher/witchersheet.html
> [TheWitcher] remove random input field

- TheWitcher/witchersheet.html
> [TheWitcher] death save without penalties

- FFD20/ffd20.html
This is a hotfix to repair a sheet-breaking bug. Please merge this as soon as possible.
> FFD20 (Final Fantasy d20) v1.61 hotfixes

- ButterflyAspect/ButterflyAspect.html
- bugfix for magic heading
- bugfix for css class
> [ButterflyAspect] fix Headline & css class

- D&D_OED/README.MD
- D&D_OED/sheet.json
> D&D_OED Minor Updates

- Chronicles of Darkness/CofD.html
Added blood beats to vampire character sheets. This is just enabling something that was hidden for vampire characters.
> [Chronicles of Darkness] Added Blood Beats field

- FFD20/ffd20.css
- FFD20/ffd20.html
This is just some hotfixes for the latest v1.6 update.
> FFD20 v1.6.2 hotfixes

- AD&D 2E Revised/2ESheet.html
- AD&D 2E Revised/javascript/version.js
Fixed the version checker. Now handles null values... ups
https://app.roll20.net/forum/permalink/10242329/
> [AD&D 2E Eevised] Version check fix v2.0

- ChroniquesOubliees/ReadMe.md
- ChroniquesOubliees/co.css
- ChroniquesOubliees/co.html
- ChroniquesOubliees/sheet.json
Version 5.00, with non-legacy code.
Also added support for drain damage type and a tab for script setup, and some minor css corrections.
> Chroniques Oubliees: update to non-legacy

- Shadowrun2e/shadowrun2e.html
- [Y ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [  Does this add or change functional aesthetics (such as layout or color scheme) ? 
> (shadowrun2e.html) Tab added to inform players of coming Updates

- Shadowrun2e/shadowrun2e.css
> (shadowrun2e.css) CSS Updates

- TheWitcher/translation.json
- TheWitcher/witchersheet.css
- TheWitcher/witchersheet.html
> [TheWitcher] add checkbox for used skill

- Warhammer 4e Character Sheet/README.md
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Miracle Damage also adapted to match new Spell layout, but without the WPB modifier.
> [Warhammer 4e Character Sheet] v1.51 Miracle dmg update

- Eclipse Phase FATE - Transhumanity's FATE/eclipse-phase_fate.css
- Eclipse Phase FATE - Transhumanity's FATE/eclipse-phase_fate.html
- Eclipse Phase FATE - Transhumanity's FATE/sheet.json
Various fixes and tweaks, gear section improvements, added additional
bonus consequence box, added muse repeating skills, changed stress
boxes layout.
- Yes
- Yes
- Yes
- Yes
- No features were removed
- All player data is retained by keeping same values as previous
> Eclipse Phase FATE (Transhumanity's FATE) - Sheet v1.1.

- HackMaster_5E/HackMaster_5E.html
Fixed fatigue no armor giving no bonus to fatigue
Added HOB2
Minor armor field changes
> HackMaster 5E | Updates

- TheWitcher/witchersheet.html
> [TheWitcher] re-add checkbox for used skill crossbow

- psirun/psirun.html
- psirun/translation.json
> [Psi*Run] Enable translations with data-i18n attributes

- TheWitcher/witchersheet.html
> [TheWitcher] fix green skill roll template

- Eclipse Phase FATE - Transhumanity's FATE/eclipse-phase_fate.css
- Eclipse Phase FATE - Transhumanity's FATE/eclipse-phase_fate.html
- Eclipse Phase FATE - Transhumanity's FATE/sheet.json
Added additional stress boxes for muses and advanced equipment.
Minor cleanup of whitespace, etc.
- No
- No
- N/A
- N/A
> Eclipse Phase FATE (Transhumanity's FATE) sheet v1.1.1

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] import notes for qualities

- Shadowrun2e/ReadMe.md
- Shadowrun2e/shadowrun2e.html
Adds mods to allow all damage modifiers to be added to appropiate skill rolls.
> shadowrun 2e.html Updates to all damage monitors.

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.css
- Shadowrun Sixth World/Shadowrun6thEdition.html
- Shadowrun Sixth World/translation.json
**2021-07-19 ** v.39 Chuz (James Culp)
Added Grunt Groups and Autocalculations based on the # of grunts
Bugfix - PC->Rolls tab was showing conversions on the Matrix Actions Tab
- [ NA ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ NA ] If this is a new sheet, did you follow [Building Character Sheets …
> Shadowrun Sixth World v.39

- Shadowrun2e/shadowrun2e.html
> shadowrun2e.html Update Tab Removal

- Die_Schwarze_Katze/Die_Schwarze_Katze.css
- Die_Schwarze_Katze/Die_Schwarze_Katze.html
- Die_Schwarze_Katze/sheet.json
Some fixes for Die_Schwarze_Katze character sheet
- Fixes the calculation of some values
- Minor style fixes and improvements
> Die_Schwarze_Katze bugfix update

- DnD_5e/DnD_5e.css
- DnD_5e/DnD_5e.html
This Pull Request adds a new column, "Attuned?", to the inventory page of the DnD_5e character sheet. Some incidental whitespace fixes were also added by my IDE.
- **Sheet name:** DnD 5e
- **Is this a bug fix?** No
- **Does this add functional enhancements (new features or extending existing features)?** Yes, adds a checkbox to first page of inventory to indicate if the character is attuned to the item. I have only added this change to the first page, so the user can group their attuned items together, but I can add the checkbox to the other pages if requested.
- **Does this add or change functional aesthetics (such as layout or color scheme)?** The only layout change is to shrink the Description box slightly to make room for the Attuned column
- **If changing or removing attributes, what …
> [DnD_5e Charcter Sheet] Add attunement to first page of Inventory

- AD&D 2E Revised/2ESheet.html
- AD&D 2E Revised/2EStyle.css
- AD&D 2E Revised/html/2ESheet-base.html
- AD&D 2E Revised/javascript/version.js
Added announcement of upcoming removal of variants section
> [AD&D 2E Revised] Announcement of upcoming section removal

- FHTAGN/index.html
- FHTAGN/src/pug/sheet-worker-scripts.js
changed calculation of hitpoints to round them up instead of down
changed some code formatting without functional relevance
> FHTAGN: round TP calculation up instead of down

- TheWitcher/witchersheet.html
> [TheWitcher] fix description of npc stun save

- Escape from Dino Island/DinoIsland.css
> [Dino Island] Move Google Fonts to First Line

- Dragon-Prince-fanmade/sheet.json
> fix json error

- T2K 4e/twilight-2k-4e.css
Fixed URL errors in CSS. There is a previous pull about fixing the same errors. But noticed they were not pointing to the correct URL. There was also another URL that needed to be changed in line 3. All this This should fix issue #9291
> [T2K 4E] Updated twilight-2k-4e.css

- Brindlewood Bay/BrindlewoodBay.html
> [Brindlewood Bay] - Fixed error with button

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleArmor.js
> [Shadowrun5thA] relax needing of fields for import

- Changed Stars/changed-stars.css
- Fixes a bug where the images URLs were no longer valid
- No
- No
- No
- N/A
> Changed Stars Character Sheet | Fix image URLs

- Shadowrun2e/shadowrun2e.html
> Shadowrun 2e Added Movement in Combat Tab

- ButterflyAspect/ButterflyAspect.html
> [ButterlfyAspect]remove modifier

- TheWitcher/js/actionButton.js
- TheWitcher/sheet.json
- TheWitcher/witchersheet.css
- TheWitcher/witchersheet.html
> [TheWitcher] computed auto fumble

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleSpell.js
> [Shadowrun5thA] split spells in categories

- Call_of_Cthulhu_2th_Ed_French/Call_of_cthulhu_french.html
Bugfix for Impalement.
I have versioned the sheet, check when opening the sheetthe version.  If it is the old version, I automatically update the attributes that have changed.
----
Bugfix pour l'Empalement.
J'ai versionné la fiche, vérifié à l'ouverture de la fiche la version. Si c'est l'ancienne version, je met à jour automatiquement les attributs qui ont changés.
> [Call-of-Cthulhu V2 French] Bugfix 

- D&D_3-5/charsheet_3-5.html
> [D&D 3.5] Fix Issue #9380

- Blades in the Dark/sheet.json
> [Blades in the Dark] add compendium to sheet.json

- Shadowrun3e/shadowrun3e.css
- Shadowrun3e/shadowrun3e.html
shadowrun3e sheet changes
Added tracking for utility degradation ( example. IC )
Added dice pool tracking for Spell, Astral, Hacking, Control and Combat.
Added "end turn" roll button to update initiative and refresh dice pools
Fixed some formatting in the vehicles/drones tab.
- [yes ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ no ] Is this a bug fix?
- [ yes ] Does this add functional enhancements (new features or extending existing features) ?
- [ yes ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ n/a ] If changing or removing attributes, what steps have you taken, if any, to preserve player …
> [Shadowrun3e ]  matrix enhancements

- D&D_3-5/charsheet_3-5.html
Bugfix:
- Create separate attributes numspell and spelldc for arcane and divine spells
> [D&D 3.5] Buffix (attributes numspell and spelldc)

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] clarify new magic heading

- Escape from Dino Island/DinoIsland.css
> [Escape from Dino Island] - Fixed background image link

- ShadowbaneInquisition/Shadowbane.css
> [Shadowbane Inquisition] major CSS fix

- Neuroshima/Neuroshima.html
Updated formula for Initiative - now it rolls correctly, as it should be.
- [x ] Is this a bug fix?
> [Neuroshima] - Initiative roll formula update

- HeroSystem6eHeroic/HeroSystem6eHeroic.css
- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Minor changes to styling.
Added max length values to a few missed text fields.
Increased max input lengths to others that were too limiting.
> [Hero System 6e Heroic] Minor edits

- Red Markets/redMarkets.html
- Red Markets/sheet.json
Minor changes to the sheet in order to make some readonly fields editable in case the automatic functions do not work and making some changes to the Sheet.json to fully attribute the game to Hebanon Games
> Red Markets Update

- ChroniquesOubliees/co.html
> Chroniques Oubliees: do not spellcheck predicates.

- NOC/NOC.html
> [NOC] fix on HTML

- AD&D 2E Revised/2ESheet.html
- AD&D 2E Revised/html/2ESheet-base.html
- AD&D 2E Revised/javascript/version.js
- Updated changelog and version
Removed the variants section to make room for new features.
A month long warning have been given to players prior to this update. Another month long wait is scheduled before the change is made permanent
> [AD&D 2E Revised] Removed variants section

- Stargate-RPG/Readme.md
- Stargate-RPG/src/pug/core.pug
- Stargate-RPG/src/scss/_core.scss
- Stargate-RPG/stargate.css
- Stargate-RPG/stargate.html
- options to set adv./disadvantage to init/moxie rolls
- 2 more attack slots
> [Stargate RPG]  v.1.74

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
> Fallout VNDPNP - Hotfix

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleVehicle.js
> [Shadowrun5thA] fix import when vehicle has weapon upgrade

- Shadowrun3e/README.MD
- Shadowrun3e/shadowrun3e.css
- Shadowrun3e/shadowrun3e.html
enhanced resist and dodge roll buttons for rangedweapons
resist button added for matrix sheet-rolls
fixed calculation of deck attributes for host/grid/ic
fixed rolls for IC combat
added support for calculating damage for different ammo type
additional notes in README.md
- [yes ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [yes] Is this a bug fix?
- [yes ] Does this add functional enhancements (new features or extending existing features) ?
- [yes ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- …
> [Shadowrun3e ] sprint4

- ChroniquesOubliees/co.html
> Chroniques Oubliees: added ammo tracking for thrown weapons

- Shadowrun3e/README.MD
- Shadowrun3e/shadowrun3e.css
- Shadowrun3e/shadowrun3e.html
Fixed issue with Tar Baby and Tar Pit IC
updated README.MD with details of changes
- [yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [yes] Is this a bug fix?
- [yes ] Does this add functional enhancements (new features or extending existing features) ?
- [no] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [n/a ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ? …
> [Shadowrun3e] sprint5

- Stargate-RPG/Readme.md
- Stargate-RPG/src/js/sheetworker.js
- Stargate-RPG/src/pug/core.pug
- Stargate-RPG/src/pug/data.pug
- Stargate-RPG/src/scss/_core.scss
- Stargate-RPG/stargate.css
- Stargate-RPG/stargate.html
* Moved Eureka Points to main page. Shown to Scientists by default, setting option to always show it
* Added HD & TD buttons to main page, changed HD to dropdown
* rearrange WIS & INT to correct order
* minor visual fixes
> [Stargate RPG] v.1.75

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleArmor.js
> [Shadowrun5thA] auto equip armor on import

- Basic_Roleplaying/Basic_Roleplaying.html
Found that the Perform Skill still had a pop-up that it was not supposed to have so I fixed it.
> [Basic Roleplaying System]

- ChroniquesOubliees/co.html
set the throwing weapon flag correctly when guessing weapon type.
> Chroniques Oubliees: set the throwing weapon flag correctly

- Forbidden_Lands/Forbidden_Lands.css
- Forbidden_Lands/Forbidden_Lands.html
- Forbidden_Lands/sheet.json
- sheet is now compatible with the CSE update. Legacy mode is no longer needed.
> Forbidden Lands v1.78

- CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
Fixing an aesthetic bug I've been too lazy to fix.
> CP-Unofficial-Persona-TTRPG (Update crimsonparcelsupttrpg.html)

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
- **New Features**
- Debug Mode (2fa6645baa3438115764b5467a3b7ee04d3e3a89, 39c5105a97ad74ae7f39accebccb19829c6638a5, d8c0054c072fcbbd0e7c2c6a6e682bb7be6de6ba, 332172dc537217830804b272463d1cfcb5312b25)
- Currently limited to toggling debug output.
- Add and use safe versions of `getAttrs()` and `setAttrs()`, contains base for default value mechanism (5fad4ad7abe9c668d620c788640ba76c44ec0c93, 99b1266acbb3c95b701c1d92ef7b27bf1d768c5b, a8adeeca304f872ab3ce478bfe0b98e892ca60e0, 4ea81abd51b97c5fee85fdc5cb8857ef81c6685c, 829b5512ad75edf4af7b717593bed6abf9a46216)
- Add default values (d764e5a145215ae62caf6992e4f926016defeac2)
- **Style**
- Info tab easier to skim (dc01d2a6104945545d66b9b090760ce485f4e0fd)
- **Miscellaneous**
- Remove superfluous debug text …
> [Das_Schwarze_Auge_4-1] Harden Code, Add Debug Mode

- TheWitcher/witchersheet.html
> [TheWitcher] fix displayed value of fumble die

- Basic_Roleplaying/Basic_Roleplaying.html
Fixed an issue found in the Perform skill
Negative Damage Bonus was not appropriately included into the final output.
> [Basic Roleplaying]Fixes to the Perform Skill and Damage

- Supers-Revised-Edition/supers-revised.css
- Supers-Revised-Edition/supers-revised.html
- Added a mook sheet
- Added query for # of bonus d6's on a roll
- Added roll parsing to automatically determine number of successes
- Roll parsing is togglable for those that do not want the automation
- Fixed a name duplication
- Sheetworkers will handle the conversion of the duplicate names
- Added versioning functionality; sheet version updated to 1.3
- Layout of sheet has been adjusted to fit inside the default character sheet window size
> Supers! Revised Edition v1.3

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix rawap weapon import, fix more ammo attributes

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix drain resist button

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix skillattr sheetworker

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] use correct naming for skillusage

- Ragnarok 3e/ragnarok.html
> [Ragnarok 3ed] Hot fix

- Fragmentos/fragmentos.css
La imágenes de fondo y los iconos no se muestran correctamente. Pueden no estar puestas correctamente las rutas de las imágenes.
> Edit fragmentos.css

- Ragnarok 3e/ragnarok.html
> [Ragnarok 3ed] Fix PV

- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css
- Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Warhammer 4e Character Sheet/translation.json
- Various minor style fixes
- Adds ranged mod calc in devmode
> [Warhammer 4e Character Sheet] 1.53 Extra

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Missing Mod_CHA in Personality question.
> Personality Bug Fix - Fallout VNDPNP

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleRepeatingWeapon.js
- Shadowrun5th/js/importSingleWeapon.js
> Shadowrun5th a react dodge

- Fragmentos/fragmentos.html
> FIX previous commit

- Fragmentos/fragmentos.css
> FIX background url

- Mutants and Masterminds 3E Official/mutants-and-masterminds3e.css
- Mutants and Masterminds 3E Official/mutants-and-masterminds3e.html
- Mutants and Masterminds 3E Official/sheet.json
Updates to making the importer more robust and capable of bringing in the default NPC sheets.
Updates to fix a majority of text overflow problems, particularly in the power window.
Minor adjustment to the hero points so it doesn't cover the Power Points section
> Mutants & Masterminds 3E Official

- GODSEND-Agenda/sheet.css
- GODSEND-Agenda/sheet.html
- GODSEND-Agenda/sheet.pug
- GODSEND-Agenda/src/pug/core.pug
- GODSEND-Agenda/src/scss/_core.scss
- page navigation now buttons
- made Attribute and Skill levels wide enough for 2 digits
> [GODSEND Agenda] - minor fix

- Stargate-RPG/Readme.md
- Stargate-RPG/src/js/sheetworker.js
- Stargate-RPG/src/pug/core.pug
- Stargate-RPG/src/pug/variables.pug
- Stargate-RPG/src/scss/_core.scss
- Stargate-RPG/stargate.css
- Stargate-RPG/stargate.html
- Stargate-RPG/stargate.pug
* add passive perception(next to bulk)
> [Stargate RPG] v1.76 

- Old School Essentials - AAC/CHANGELOG.md
- Old School Essentials - AAC/OSE-AAC.html
- Fix a bug where "AttackMatrix6:#" appears when rolling dice with DAC. Closes wesbaker#75
> [Old-School Essentials by Necrotic Gnome] - 1.9.3

- Harry Potter JDR/harryPotterJDR.html
> [Harry Potter JDR]Bugfix

- README.md
- Updating the repository readme, feel free to contribute thoughts on the changes.
> Updated Repository Readme

- README.md
> File clean up

- City Of Mist Official/city-of-mist.css
- Increased height of cards because anything more than 2 Weaknesses were being hidden by the Flip Card  button.
> City of Mist Official - fix for Weaknesses being hidden

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] add react soak

- Robotech The Macross Saga (SMG)/robotech.css
- Robotech The Macross Saga (SMG)/robotech.html
Added several new skills from the upcoming Robotech Homefront book to the skill list option list/auto-fill.
Fixed spelling on a couple of items. Changed the skill roll button process to a single roll button. Updated Roll Template
REQUEST: Please, please, please, change the name of this template on the template list from "The Macross Saga" to "Robotech The Macross Saga" - or at least "Robotech". The game is based on the Robotech IP and this is what players will be looking for. Thank you!
- [YES] Does the pull request title have the sheet name(s)? Include each sheet name.
- [NO] Is this a bug fix?
- [NO ] Does this add functional enhancements (new features or extending …
> [Robotech The Macross Saga (SMG)] New skills from Homefront book/fixed spelling

- HeroSystem6eHeroic/HeroSystem6eHeroic.html
Wrong variable in shield damage type corrected.
Fixed math error in carried weight formula.
Removed some unnecessary breaks.
> [Hero System 6e Heroic]: Bug fixes.

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Removed Addiction Chance.
Added Resolve.
> New Secondary Stat Added - Fallout VNDPNP

- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.css
- Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
- **New Features**
- Add spell 'Metamorpho Felsenform' (ed41107a3bdaa97005fb5dc9f5afc1d3ddf941d1)
- **Miscellaneous**
- Document latest changes on info tab (b799b75f8bb3ebff253d8ec8904e4fc3540fe1bd)
- Bump version number (70c66761222ae1d1d4ffec51a9ffaefe34514af5)
> [Das_Schwarze_Auge_4-1] Add missing spell

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/customRollParsing.js
> [Shadowrun5thA] calculate drain/nethits for rituals and spirits

- Heartbeats/heartbeats.html
Fixing bug with sheetworker bounding the heartrate (comparing as a string instead of Int)
> [Hearbeats] fixing sheetworker bug

- Basic_Roleplaying/Basic_Roleplaying.html
Forgot to remove the energy counter on repeating armors
> [Basic Roleplaying System]Forgot to remove the energy counter

- GammaWorld1e/GammaWorld1e.css
- GammaWorld1e/GammaWorld1e.html
- GammaWorld1e/Readme.md
- GammaWorld1e/sheet.json
* update requested by [Lowe505](https://app.roll20.net/forum/permalink/10458753/)
* Roll updates
* Update initiative roll to be `1d6+@{dex}`, (from previous `@{selected|dex}`). Init rolls now work without selecting token.
* Init rolls can be called with `%{selected|INIT}`/`%{selected|INIT-mutant}`
* artifact rolls can be called with `%{selected|ARTIFACT}`/`%{selected|ARTIFACT-mutant}`
* Armor Class input looks better
> [Gamma World 1e] v.1.02

- Mantel dAcier/sheet.json
* french characters now displays correctly
> [Mantel dAcier] sheet.json fix

- Zweihänder Grim & Perilous/sheet.json
> {Zweihander] update  sheet.json

- Barbaric/sheet.json
> [barbaric] sheet.json

- ChroniquesOublieesContemporain/sheet.json
* now french characters are displayed correctly
> [Chroniques Oubliées Contemporain] fix sheet.json formatting

- Official Savage Worlds/sheet.json
- removed the legacy flag from sheet.json
- This will fix the styling errors in the recent update
> Official Savage Worlds - Switching to non legacy styling fix

- Level Up - Advanced 5th Edition/levelup.css
- Level Up - Advanced 5th Edition/levelup.html
- Level Up - Advanced 5th Edition/translation.json
-ensured the PC tab is first
-put Heritage and Culture into strict alphabetic order
Corrected spelling
Fixed some lists formatting
- [No] Does this add functional enhancements (new features or extending existing features) ?
- [Some minor] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N/A ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_C …
> [Level Up - Advanced 5th Edition] - minor fixes

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Electricity Resistance (ER) has been removed.
> ER Removal - Fallout VNDPNP

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] unexperimental critterpowers + ammo import

- Mutants and Masterminds 3E/mutants-and-masterminds.css
- Mutants and Masterminds 3E/scss/files/page1.scss
- Mutants and Masterminds 3E/scss/files/page23.scss
> [Mutants & Masterminds 3E] Fix CSS

- Knight/knight.html
- Knight/pug/html/tab/combat.html
- Knight/pug/js/buttons.js
- Knight/pug/js/rolls/pj/combatContact.js
- Knight/pug/js/rolls/pj/combatDistance.js
- Knight/pug/js/rolls/pj/combatGrenade.js
- Knight/pug/js/rolls/pj/combatImprovise.js
- Knight/pug/js/rolls/pj/mechaArmure.js
- Knight/pug/js/rolls/pj/monk.js
- Knight/pug/js/rolls/pnj/combatDistance.js
- Knight/pug/js/rolls/pnj/combatImprovise.js
> [Knight] Bugfix Monk + Bonus carac

- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD
- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css
- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/sheet.json
- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
…ge additional modifiers of armor, show weapon range in combat tab
* Fixed a upper-/lowercase issue with compendium drops
* Added data-i18n-list ordering for combat techniques
* Fixed an issue with armor encumbrance modifiers
* Rangeweapon range now visible in the combat tab
> Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses - Minor fixes

- SkyfallRPG/skyfall.css
- SkyfallRPG/skyfall.html
> [Skyfall RPG] Ajustes de perícias

- Knight/knight.css
- Knight/knight.html
- Knight/pug/html/templates/combat.html
- Knight/pug/html/top/right.html
- Knight/pug/js/_functionsWeapons.js
- Knight/pug/js/knight.js
- Knight/pug/js/library.js
- Knight/pug/js/rolls/pj/combatContact.js
- Knight/pug/js/rolls/pj/combatDistance.js
- Knight/pug/js/rolls/pj/combatGrenade.js
- Knight/pug/js/rolls/pj/combatImprovise.js
- Knight/pug/js/rolls/pj/monk.js
- Knight/pug/js/rolls/pj/ranger.js
- Knight/pug/js/rolls/pj/simple.js
- Knight/pug/js/rolls/pj/wizard.js
- Knight/scss/files/base.scss
- Knight/scss/files/tabs/dossier.scss
- Knight/scss/files/templates.scss
- Knight/scss/knight.scss
> [Knight] Bugfix Warrior / Protections / Sur Mesure

- Shadowrun Sixth World/CHANGELOG.md
- Shadowrun Sixth World/Shadowrun6thEdition.css
- Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - Technomancer Complex Forms with no roll were displaying oddly.  This has been fixed, now the roll button that shows up will show the fade and notes section.
- [ N ] Does this add functional enhancements (new features or extending existing features) ?
- [ NA ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ NA ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
> Shadowrun Sixth World v.47

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] import notes for adept powers

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleRepeatingWeapon.js
- Shadowrun5th/js/importSingleWeapon.js
> [Shadowrun5thA] import weapons which are gear

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] add extended rolls

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] chummer has introduced adept, so we use it

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] uncheck autochecked checkbox for repeating perception

- ChroniquesGalactiques/ReadMe.md
- ChroniquesGalactiques/cog.html
- ChroniquesGalactiques/sheet.json
- Added the new attr_character_token attribute in an <img> element on the sheet
> Chroniques Galactiques v3.115.0

- ChroniquesOublieesContemporain/README.md
- ChroniquesOublieesContemporain/coc.html
- ChroniquesOublieesContemporain/sheet.json
- Added the new attr_character_token on the sheet
> Chroniques Oubliees Contemporain v3.10.0

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix autocalc P -> S

- GURPS/gurps.html
- fix syntax error with method toLowerString()
GURPS\gurps.html
> [GURPS] 2.6.8.2

- ARC/arc.css
- ARC/arc.html
- ARC/src/package.json
- ARC/src/pug/layouts/roll-template.pug
- ARC/src/pug/meta/data.pug
- ARC/src/scss/meta/_variables.scss
Change assets to use `master` branch instead of this branch. _sigh_.
> [ARC] Change assets URL

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] improve import of cyberdecks, rccs and commlinks

- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] fix vehicle weapon roll, soak with AP > Armor

- IAS-Freude-schoener-Goetterfunken/README.md
- IAS-Freude-schoener-Goetterfunken/fsg.css
- IAS-Freude-schoener-Goetterfunken/fsg.html
Name: Freude schöner Götterfunken
System: Icarus Adventure System
Minor Bugfix for Rerolls with 5 dices
- [ yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ yes] Is this a bug fix?
- [ no] Does this add functional enhancements (new features or extending existing features) ?
- [ no] Does this add or change functional aesthetics (such as layout or color scheme) ?
> Icarus Adventure System - Freude schöner Götterfunken

- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css
- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* Fixing a major bug with wrongly calculated skill value modifiers
> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] DSA5 v1.0.3 FW Modifier Fix

- ICRPG-MasterEdition/ICRPG_ME.css
- ICRPG-MasterEdition/ICRPG_ME.html
Fixed some issues with Defense stats not calculating properly
Add Heart control buttons for quick adjustments
Added rolling buttons to extend Firefox compatibility
Fixed NPC heart input and added heart buttons
Fixed some incorrectly coded effort buttons
> Index Card Master Edition

- Talessya/Talessya.css
- Talessya/Talessya.html
Fixing small bugs with advantage and whisper queries. In order to do that, we defaulted some players config attributes, but this won´t be a problem for the user experience and it would be transparent for them.
> Talessya: Fix minor bugs

- T2K 4e/twilight-2k-4e.html
Increase Encumbrance value from 2 to 4 when Load Carrier is active.
- Fixes change to Load Carrier Encumbrance bonus
- It does not
- It does not
- Not applicable
- Not applicable
> Twilight 2000 4th Edition | Fix to updated rules for Load Carrier

- Knight/knight.css
- Knight/knight.html
- Knight/pug/html/tab/armure.html
- Knight/pug/html/tab/combat.html
- Knight/pug/html/tab/vehicule.html
- Knight/pug/html/templates/combat.html
- Knight/pug/html/templates/mechaArmure.html
- Knight/pug/html/top/right.html
- Knight/pug/js/_functionsWeapons.js
- Knight/pug/js/dist/knight.dev.js
- Knight/pug/js/knight.js
- Knight/pug/js/library.js
- Knight/pug/js/rolls/pj/bard.js
- Knight/pug/js/rolls/pj/berserk.js
- Knight/pug/js/rolls/pj/combatContact.js
- Knight/pug/js/rolls/pj/combatDistance.js
- Knight/pug/js/rolls/pj/combatGrenade.js
- Knight/pug/js/rolls/pj/combatImprovise.js
- Knight/pug/js/rolls/pj/druid.js
- Knight/pug/js/rolls/pj/mechaArmure.js
- Knight/pug/js/rolls/pj/monk.js
- Knight/pug/js/rolls/pj/ranger.js
- Knight/pug/js/rolls/pj/wizard.js
- Knight/pug/knight.pug
- Knight/scss/files/base.scss
- Knight/scss/files/tabs/armure.scss
- Knight/scss/files/tabs/combat.scss
- Knight/scss/files/tabs/vehicule.scss
- Knight/scss/files/templates.scss
- Knight/translation.json
> [Knight] Bugfix + add features

- Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Fixing attribute modifier through status/abilities
> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] DSA5 v1.0.4 Bugfix

- Knight/knight.html
- Knight/pug/html/tab/combat.html
- Knight/pug/js/buttons.js
- Knight/pug/js/rolls/pj/combatAutre.js
- Knight/pug/js/rolls/pnj/combatDistance.js
> [Knight] Bugfix Berserk

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/import.js
- Shadowrun5th/js/importSingleDrone.js
- Shadowrun5th/js/importSingleVehicle.js
> [Shadowrun5thA] split vehicles and drones

- GURPS/gurps.html
- GURPS/readme/sheet-open-sync-skills-spells.md
- GURPS/readme/updating-skill-level-hooks.md
- Streamline how skill and spell levels are updated when a new GURPS version is loaded.
- Resolved issue where linked melee items were not updating. Reported Tsuka and troubleshooted by Mike W.
- Added a readme folder with markdown files that explain hook interactions and to find conflicts
- GURPS\gurps.html
- GURPS\readme\sheet-open-sync-skills-spells.md (new)
- GURPS\readme\updating-skill-level-hooks.md
> [GURPS] 2.7.0.1

- Aquelarre/translation.json
> [Aquelarre] Update translation.json

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleDrone.js
> [Shadowrun5thA] import general autosofts when added to drone in chummer

- GURPS/gurps.html
Repeating Spells Table. Bugfix Mod column stopped working. Reported TechnoMaestro.
- GURPS\gurps.html
> [GURPS] 2.7.0.2

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Fixed typo in Deception. It said PET instead or PER.
> Hotfix - Fallout VNDPNP

- CoeursVaillants/sheet.json
> correction bugs

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importSingleRepeatingWeapon.js
- Shadowrun5th/js/importSingleWeapon.js
> [Shadowrun5thA] fix import of dmg type

- LANCER RPG (1.8)/LANCER.html
> Lancer RPG | Fixing Pilot HP Positioning

- BESM4eExtras/BESM4eExtras.html
v1.3.0
Added support for the Swarm attribute.
Fixed Weapon Selection logic.
Temporarily removed Telekinesis attribute as a weapon. Upon reading the Core rulebook on how this attribute can be used offensively, it was not implemented correctly. Will address in a future update.
> [BESM4eExtras] v1.3.0

- CoeursVaillants/CoeursVaillants.html
> CoeursVaillants - Correction lien image

- Forbidden_Lands/Forbidden_Lands.html
- fixed title text for repeating_mount attributes.
> Forbidden Lands - small title text fix

- Knight/knight.html
- Knight/pug/js/_functionsWeapons.js
> [Knight]Bugfix Rogue

- Ragnarok 3e/Readme.md
- Ragnarok 3e/ragnarok.html
- Ragnarok 3e/sheet.json
> [Ragnarok 3ed] Added new field "Frialdad"

- Level Up - Advanced 5th Edition/CHANGELOG.md
- Level Up - Advanced 5th Edition/levelup.html
Fixed NPC CR current using the incorrect attribute --Reset to using attr_CR
Fixed NPC CR current using the incorrect attribute --Reset to using attr_CR
- [No] Does this add functional enhancements (new features or extending existing features) ?
- [No] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N/A] If this is a new sheet, did you follow [Building Character Sheets …
> [Level Up - Advanced 5th Edition] NPC Sheet Fix

- CyberpunkRED_raycw/cyberpunkred-raycw.html
Updates DEX, REF, MOVE based on armor penalty; converts to X of X format; adds Brawling and Martial Arts to Weapons; update Event Trigger for Weapontype
I've updated the Dexterity, Reflex and Movement stats to have a _max value as Empathy and Luck have.
I've updated the existing code that counts stat points spent to look for the _max values.
I've updated the HTML code to use the `outof` CSS class.
I've added Brawling and Martial Arts as options in the Weaponstype drop-down list.
I've updated the Event Trigger for Weapontype to update when Reflex or Dexterity change or when the sheet is opened (this accounts for any impairment to those abilities mid-session without having to change the Weapontype to update the value).
I've added functionality to update the current Dexterity, Reflex and …
> cybperunkred-raycw: Update fields automatically for cyberpunkred-raycaw

- Knight/knight.html
- Knight/pug/js/knight.js
> [Knight] Bugfix Wizard

- Level Up - Advanced 5th Edition/CHANGELOG.md
- Level Up - Advanced 5th Edition/levelup.css
Increased size of HitDice and Speed on the NPC Sheet
Increased size ofthe Challenge rating section
Fixed the formatting of the Damage Vulnerabilities/Resistances/Immunities/Conditional sections so they are left formatted and fit on the same line
- [No] Is this a bug fix?
- [No] Does this add functional enhancements (new features or extending existing features) ?
- [Yes] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N/A] If this is a new sheet, did …
> [Level Up - Advanced 5th Edition] Formatting fixes

- Shadowrun5th/Shadowrun5th.html
- Shadowrun5th/js/importArmor.js
> [Shadowrun5thA] import cyberware armor to armor

- Shadowrun5th/Shadowrun5th.css
- Shadowrun5th/Shadowrun5th.html
> [Shadowrun5thA] hide fixed weapons with click on heading

- Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
> Base AC is now Edittable - Fallout VNDPNP
