Roll20/roll20-character-sheets

Knight/knight.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/library.js, Knight/pug/js/rolls/pj/combatContact.js
=> [Knight] Bugfix Style Puissant

BESM4eExtras/BESM4eExtras.css, BESM4eExtras/BESM4eExtras.html
BESM4eExtras.css
v1.3.2
Added "Documentation" button to Sheet options menu. Pressing this button will send a link to the documentation in chat.
v1.3.1
Defect, Impaired Sense, now has field to select sense.
Impaired Sense now affects Perception Roll.
Cleaned up extraneous debug messages and commented code.
=> [BESM4eExtras] v1.3.2

CyberpunkRED_raycw/cyberpunkred-raycw.css, CyberpunkRED_raycw/cyberpunkred-raycw.html
All changes developed and tested in Sheet Sandbox # 12114933 "CPREDSANDBOX"
This PR includes the following changes:
- CSS syntax fixes (removing unnecessary comments that IDE was complaining about)
- Changed line-height of the attack template so weapons with long names don't show up with overlapping lines
- Added lines to CSS sheet to allow the inventory area to stay in its own div when more than 20 items are added and user can scroll through contents.
- Added attack bonus field to weapon section and incorporated value into roll template for attacks.  Tested with zero, negative and positive values successfully.
- Added Journal section to allow players to keep notes.
- Tied new Journal section to existing Notes section in Character tab so I can preserve player data and later replace Notes …
=> [CyberpunkRED-raycw] Attack bonus, weapon line height, journal, inventory overflow, mook sheet and role ability updates

Halo_Mythic_3dot5/HaloMythic4dot0.css, Halo_Mythic_3dot5/HaloMythic4dot0.html
Added a Repeating shields and armour display to allow for multiple handheld shields 
- [Y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [None changed] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
=>  Halo_Mythic_3dot5 V2.1 patch

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.html, ChroniquesOublieesContemporain/sheet.json
Minor fixes
- Fixed logic for conditions action buttons
- Fixed an issue with an attack modifier persisting after having been canceled
- Fixed logic for better support of damage modifiers as dice rolls
- Fixed an incorrect display when selecting the 'Surhumains' setting
- Added sheet version number on the Configuration tab
=> ChroniquesOublieesContemporain v3.10.1

Knight/knight.html, Knight/pug/js/rolls/pj/combatImprovise.js
=> [Knight] Small Bugfix

Aventures/sheet.json
Legacy to false because it create a bug on sheet
=> Correct bug - Update sheet.json

ADnD 2E Revised/2ESheet.html, ADnD 2E Revised/2EStyle.css, ADnD 2E Revised/html/2ESheet-base.html, ADnD 2E Revised/javascript/sheetWorkers.js, ADnD 2E Revised/javascript/version.js
Added validation and error messages for fields that try to use CRP to calculate the results.
All changes described on the forum: https://app.roll20.net/forum/permalink/10568391/
=> [ADnD 2E Revised] CRP Validation

AGE System/AGE System.css, AGE System/AGE System.html
Original Sheet Author could not fix error with Focus Bonuses, and asked for help.
I have fixed the bug, and want to merge it to the master
This update does not remove any attributes or functionality.
The only Attributes changed were the ones causing the bug.
The bug was based on default values, so players who never input a value, might experience a loss of data, but they should be able to input a value, and continue normally.
=> AGE System - Apply Focus bonuses to Character page

Aventures/sheet.json
Reverts Roll20/roll20-character-sheets#9946
=> Revert "Correct bug - Update sheet.json"

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] split of contacts and SINs, add fellow runners

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html, Shadowrun5th/js/customRollParsing.js, Shadowrun5th/js/importSingleRepeatingWeapon.js
=> [Shadowrun5thA] import weapons in categories

rapidfire_system/Javascript/calculators.js, rapidfire_system/Javascript/clickfunctions.js, rapidfire_system/Javascript/initialchangefunctions.js, rapidfire_system/Javascript/rollfunctions.js, rapidfire_system/Javascript/setupfunctions.js, rapidfire_system/Javascript/triggeredfunctions.js, rapidfire_system/Javascript/updaters.js, rapidfire_system/Javascript/variables.js, rapidfire_system/Mixins/_Sheet Mixins.pug, rapidfire_system/scaffold/_htmlelements.pug, rapidfire_system/scaffold/_rolltemplate mixins.pug, rapidfire_system/scaffold/accessSheet.js, rapidfire_system/scaffold/attribute_proxy.js, rapidfire_system/scaffold/listeners.js, rapidfire_system/scaffold/parse_cascade.js, rapidfire_system/scaffold/sheetworker_aliases.js, rapidfire_system/scaffold/utility.js, rapidfire_system/style.css, rapidfire_system/style.scss, rapidfire_system/system.html, rapidfire_system/system.pug, rapidfire_system/translation.json
@nmbradley The original merge of the sheet doesn't seem to have ever gone live. The sheet is in the approved.yaml, but github is still giving me a new sheet error.
- Stat bonuses now apply (e.g body_mod)
- Infrastructure changed for improved maintainability
- Fixed bug with drone structure handling (drone attribute values ported
=> Rapidfire System 1.01 infrastructure and minor bug fixes

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] order attributes according to rule book

CyberpunkRED_raycw/cyberpunkred-raycw.css, CyberpunkRED_raycw/cyberpunkred-raycw.html
Added the following:
- Role Ability Skills moved to skills section with ability to mod, if needed
- Role Ability section converted to record Rank in that role ability
- Combat Awareness section added to record Solo point spend
- Journal CSS cleaned up and textarea improvements
- Removed range display for Brawling and Martial Arts attacks
- [ N ] Is this a bug fix?
- [ Y ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ See notes ] If changing or removing …
=> [CyberpunkRED-raycw] Journal, Role Ability skills, Combat Awareness updates

BESM4eExtras/BESM4eExtras.css, BESM4eExtras/BESM4eExtras.html
BESM43Extras.html
BESM43Extras.css
v1.4.12
Fixed bug where Power Flux and Power Variation were not calculating pool costs correctly (uncaught bug introduced by title case change in v1.4.6).
v1.4.11
Enhanced Senses characteristic now correctly shows "x Senses Remaining".
v1.4.10
Added support for Telekinesis Attribute as a Weapon.
Enhanced Extra Arms Attribute code to correct some activation/deactivation logic.
v.1.4.9
Enemy Attack and Enemy Defense now apply correctly to weapon/combat rolls, and ACV and DCV rolls.
v1.4.8
Maneuvers now appear in title case and with word spacing in chat.
v1.4.7
Added support for Combat Technique, Rush Attack.
If you do not know English. …
=> [BESM4eExtras] v1.4.12

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* Fixing a Bug with the calculation of skill ratings
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] Fix calculation of SR

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] rework import

The Troubleshooters/TheTroubleshooters.html
Modified TheTroubleshooters.html to fix a couple of minor errors flushed out during playtesting
=> Characte sheet for The Troubleshooters

ChroniquesOubliees/co.html
Clean-up of the armor and shield attributes.
=> Chroniques Oubliees: version 5.01

Knight/knight.html, Knight/pug/html/tab/combat.html, Knight/pug/js/_functionsWeapons.js
=> [Knight] Bugfix Suppression

Skeleton 1st Edition/skeletonsheet.html
This includes extra mental and physical injuries, as well as exhaustion and blood points for addition to the character sheet
=> [Skeleton 1st Edition] Adds additional resources

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.html, ChroniquesOublieesContemporain/sheet.json
- Added support for test mods (ie ability mods +/- buffs/debuffs) in damage modifiers for attacks
- Added support for displaying character token in chat rolls
=> ChroniquesOublieesContemporain Version 3.11

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix import of unsorted weapons

5eShaped/5eShaped.css
Issue:
It seems like many of the links that use 'cdn.rawgit.com' are starting to give 502 errors, which caused the images to not appear on the character sheet
Fix:
Replaced all links using 'cdn.rawgit.com' with updated links using 'gistcdn.githack.com'.
Other:
I also formatted 5eShaped.css to be more readable
5eShaped
- Specifically the 5eShaped.css file of the Character sheet
While this issue has not been reported on the Github yet it has been mentioned and talked about in the roll20 forums at the 
following: link https://app.roll20.net/forum/post/10599468/5e-shaped-sheet-display-error
=> [5eShaped] Fix for broken images on character sheet

Knight/knight.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/rolls/pj/combatAutre.js, Knight/pug/js/rolls/pnj/combatAutre.js, Knight/pug/js/rolls/pnj/combatContact.js, Knight/pug/js/rolls/pnj/combatDistance.js, Knight/pug/js/rolls/pnj/combatGrenade.js
=> [Knight] Bugfix Roll NPC / Other Weapons

Ragnarok 3e/ragnarok.html
=> [Ragnarok 3ed] Fix tirada de estrés

Hexxen-1733-Ulisses-Spiele(Official)/sheet.json
=> Hexxen 1733 Official - Correct Legacy Mode

Tylestel/tylestel.css, Tylestel/tylestel.html
=> [Tylestel] MAJ du type des champs de texte pour que ca se sauvegarde.

WFRP4CharSheet/WFRP4Charsheet.html
Wrong case in translation resulting in an undisplayed variable.
=> [WFRP4CharSheet] Fixed translation case error

Alien Roleplaying Game/Alien-Roleplaying-Game.html
Fixed calculated range modifier by including it on sheet opened.
Updated change log and sheet version, removed unnecessary console logging.
=> [Alien RPG] [Bugfix] Fix armament range modifier calculation

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Css fix for firefox select option background
* Minor adjustments for upcoming expansions
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.0.8

The One Ring 2e/sheet.css, The One Ring 2e/sheet.html
CSS bugfixes for the roll-templates
=> [The One Ring 2e] 2.0.2 

Black Void by Penny for a Tale/BlackVoid.css, Black Void by Penny for a Tale/BlackVoid.html, Black Void by Penny for a Tale/src/pug/pages/npc.pug, Black Void by Penny for a Tale/src/scss/pages/_npc.scss
Adding the sheet toggle to npc page
=> [Black Void] Adding the sheet toggle to npc page

Sigil-Shadow/README.md, Sigil-Shadow/sigil-shadow.html, Sigil-Shadow/sigil-shadow.json
Corrected typo on name of preview document in sigil-shadow.json
Corrected user ID name on sigil-shadow.json
Added publisher name to README.md document
Corrected html text tag errors on sigil-shadow.html
- [ x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
=> Sigil and shadow fix json

Ultima Torcia - Pagina Singola/lutps.html, Ultima Torcia - Pagina Singola/translation/en.json
Changed error in data-i18n="merit-i". Now works and tranlated all params on Crowdin
=> [Ultima Torcia - Pagina Singola] fixed merit-i problem

notequest/notequest.css, notequest/sheet.json
- update css file to remove unnecessary lines and styles
- update json file to legacy false
=> [notequest] - update css

Ultima Torcia - Pagina Singola/lutps.html
Fixed fourth weapon prop. Now works
=> [Ultima Torcia - Pagina Singola] fixed fourth weapon prop

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] escape ()

BESM4eExtras/BESM4eExtras.css, BESM4eExtras/BESM4eExtras.html
BESM4eExtras.css
* Added support for Attribute – Resilient
* Added support for Attribute – Unaffected
* Added tooltip descriptions for Enhancements and Limiters applied to Active Attributes
* Added new damage types: acid, disease, psychosomatic, and toxin.
* Weapons will now adjust the available damage types when Enhancements Insidious or Psionic are applied.
* Added new Armor Limiter – Disperse. Converts 50% of normal damage stopped to Stun and applies to character.  100% of Stun damage taken is stopped.
* Added new Forcefield Limiter – Specific. Doubles Armor Rating to 1 of 3 damage categories: chemical, energy, or physical, but does not protect against remaining 2 damage categories.
* Attribute Options menu now opens with accordion transition rather than modal.
* …
=> [BESM4eExtras] version 1.5.0

Knight/knight.html, Knight/pug/html/tab/vehicule.html, Knight/pug/js/rolls/pj/combatAutre.js
=> [Knight]Bugfix Vehicule

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix drone skilltype

Nephilim-Legende/nephilim-legende.html
Adding a new incarnation period to the existing list.
=> [Nephilim-Legende] Adding incarnation period

Against-The-Darkmaster-CoreRules/againstthedarkmaster-corerules.html
Remove a redundant CSS class from a subheading element.
=> [Against the Dark Master] Fix subheading size.

Neuroshima/sheet.json
Legacy mode fix, was set to false which resulted in broken formatting
=> Neuroshima: Fix legacy mode in sheet config, set to false

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
A new Secondary Stat called Detection has been added.
=> New Secondary Stat - Fallout VNDPNP

Neuroshima/Umiejetnosci.html
Fix missing div termination, which restores INVENTORY tab
- [v] Is this a bug fix?
=> [Neuroshima] Fix inventory page missing due to missing div termination

Mutant Year Zero/mutantyearzero.html
The check for buddy under relationships was erroneously a radio button, this has been fixed in this version (v2.04). 
=> [Mutant Year Zero] Fixed buddy checkbox

BESM4eExtras/BESM4eExtras.html
commit 4ac51fad1177e7c3e640ec9f323f187c30986e66
Author: Darth-John <77751557+Darth-John@users.noreply.github.com>
Date:   Mon Feb 7 14:24:19 2022 -0800
Resilience tooltip descriptions
Added tooltip descriptions for resilience attribute.
Minor bug fixes.
=> [BESM4eExtras] version 1.5.2

Neuroshima/Neuroshima.css, Neuroshima/Neuroshima.html, Neuroshima/readme.md
Hotfix part 2 for inventory section
=> [Neuroshima] Inventory hotfix

See You In Hell/seeyouinhell.html
Also, i have a question, can i have both names for russian and english version ("Встретимся в АДУ" for russian version and "See You In Hell" for english version?
=> [Встретимся в АДУ (See You In Hell)] fix input attributes bug

Knight/knight.html, Knight/pug/html/tab/combat.html, Knight/pug/html/tab/dossier.html, Knight/pug/html/top/right.html, Knight/pug/js/knight.js
=> [Knight] Bugfix Import + add Egide for NPC

TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add location button to template

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix weapon bonus dice not imported

BESM4eExtras/BESM4eExtras.html
v.1.5.3
* Added support for the following tooltip descriptions:
* Combat Techniques
* Special Movement
* Connected, Metamorphosis, Plant Control, Sixth Sense and Summon Creatures
* Customizations which require additional configuration
* Various other Attributes with binary value customizations
* Now when activating/deactivating Combat Technique which includes Rush Attack or Lightning Reflexes, their values will be added or removed, respectively, from rolls automatically.
* Movement will now correctly account for Special Movement, Fast, when the attribute is activated/deactivated.
* Bug fixes.
If you do not know English. Please leave a comment in your …
=> [BESM4eExtras] version 1.5.3

The Between/TheBetween.css, The Between/TheBetween.html
Fixed dawn questions for the undeniable playbook, as well as the logo
=> [The Between] - Bugfixes

Pathfinder Community/pathfinder_community.css, Pathfinder Community/pathfinder_community.html, Pathfinder Community/translation.json
- needed to adjust mythic open/close nav clickable area
- updated mythic repeating to match repeating ability section for continuity
- fixed translation key missing on the attack grid for crit confirm bonus column
=> PF Community  - small fix for mythic

Earthdawn (FASA Official)/Earthdawn.css, Earthdawn (FASA Official)/Earthdawn.html
Earthdawn v2.06
No direct change of attributes
=> Earthdawn (FASA Official) v2.06

Classified/ReadMe.md
Added information about whispering Sixth Sense rolls on the PC sheet in the read.md
Fixed a typo in the read.md
=> [Classified] Added information about whispering Sixth Sense rolls

Buried Treasures/buried-treasures.html
updating Buried Treasures character sheet to reflect the latest changes in the rules
- [YES] Does the pull request title have the sheet name(s)? Include each sheet name.
- [NO] Is this a bug fix?
- [YES] Does this add functional enhancements (new features or extending existing features) ?
- [NO] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [NOT APPLICABLE] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [NOT APPLICABLE] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
If …
=> updating Buried Treasures character sheet to reflect the latest changes in the rules

D&D_OED/sheet.json
Adding “legacy”: true flag to sheet json.
=> D&D_OED Bug Fix Adding “legacy”: true flag to sheet json.

GURPS/gurps.html
- Removed a Nullish Coelesce Operator that isn't supported by Roll20's API. This resulted in a syntax error when restarting the API Sandbox, 
- Syntaxerror unexpected token '?'
- Used eslint, typed definitions for roll20 methods, to find undeclare variables, block level variable issues, in hopes of finding why Roll20 API was returning syntax error.
- Formatted javascript using Visual Code eslint formatter
- GURPS\gurps.html
=> [GURPS] 2.7.7.0

Knight/knight.css, Knight/knight.html, Knight/pug/html/tab/armure.html, Knight/pug/html/tab/combat.html, Knight/pug/html/tab/vehicule.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/rolls/pj/combatDistance.js, Knight/pug/js/rolls/pj/combatGrenade.js, Knight/pug/js/rolls/pj/combatImprovise.js, Knight/pug/js/rolls/pj/mechaArmure.js, Knight/scss/files/tabs/armure.scss, Knight/scss/files/tabs/combat.scss, Knight/scss/files/tabs/vehicule.scss, Knight/translation.json
=> [Knight] Fix Pilonnage / Improve Pilonnage

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix import of stick-n-shock for repeating weapons

WFRP4CharSheet/WFRP4Charsheet.css
Changed images location from contributor repository to Roll20 character sheets repository.
This is only a storage enhancement (needed to first commit the images, then update CSS in order to let the things work well without interruption of the service), nothing else ;)
=> [WFRP4CharSheet] Update images URL

Supers-Revised-Edition/javascript/listeners.js, Supers-Revised-Edition/javascript/supers-revised.js, Supers-Revised-Edition/javascript/utility.js, Supers-Revised-Edition/javascript/variables.js, Supers-Revised-Edition/prepros.config, Supers-Revised-Edition/sheet.json, Supers-Revised-Edition/supers-revised.css, Supers-Revised-Edition/supers-revised.html, Supers-Revised-Edition/supers-revised.pug
- Fixed a bug that could cause rolling to fail
- Fixed a bug that caused the power point calculation to be incorrect
- Fixed a bug with how the costs section was laid out
- Fixed a layout bug for the (dis)advantages section on the base character sheet
- Added defensive and offensive rolling types to the sheet which change how the roll parsing is handled
- Added an HQ sheet
- Added a Vehicle Sheet
- Added a settings tab to the sheet
- Added a whisper setting to the sheet
- Selecting what type of character the sheet represents is now done from the settings tab
- Added a navigation tab for navigating between the various tabs.
- Mook Sheet is now labeled as Mook/Hazard Sheet
- did a basic refactor of the code to use PUG instead of HTML
- Updated the sheet styles to use CSE sanitizer instead …
=> Supers Revised Edition 1.4

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
& damage buttons rolltemplate
* Fix repeating row attacks not clickable anymore
* Roll damage button for rolltemplates
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.1.1

Twilight-2000-v2.2/Kult.css, Twilight-2000-v2.2/Kult.html
Changes to accommodate Dark Mode
=> [Twilight 2000 2.2] Changes to accommodate Dark Mode

Kult/Kult.css, Kult/Kult.html
=> [Kult 3rd  edition] Dark mode fix and CSE update

RunequestGQS/RunequestGQS.css
=> [RuneQuest:Glorantha] Dark mode fix

HarnMaster3/harnsheet.html, HarnMaster3/harnstyle.css
Styling changes to make dark theme of sheet align better with roll20 dark mode.
=> [Harnmaster3] Dark modeupdate

Palladium Rifts by Grinning Gecko/CHANGELOG.md, Palladium Rifts by Grinning Gecko/README.md, Palladium Rifts by Grinning Gecko/dist/rifts.css, Palladium Rifts by Grinning Gecko/dist/rifts.html, Palladium Rifts by Grinning Gecko/package-lock.json, Palladium Rifts by Grinning Gecko/package.json, Palladium Rifts by Grinning Gecko/rifts.css, Palladium Rifts by Grinning Gecko/rifts.html, Palladium Rifts by Grinning Gecko/src/js/armor.js, Palladium Rifts by Grinning Gecko/src/js/bonuses.js, Palladium Rifts by Grinning Gecko/src/js/magic_psionics_abilities.js, Palladium Rifts by Grinning Gecko/src/partials/datalists.html, Palladium Rifts by Grinning Gecko/src/partials/options.html, Palladium Rifts by Grinning Gecko/src/partials/repeating_modifiers_readonly.html, Palladium Rifts by Grinning Gecko/src/scss/rifts.scss
- Add "Output ISP/PPE/Damage usage to chat" option.
- Display level alongside modifier name in Modifier Picker list.
- Add Battleram, Bombard, and Space Fighter combats to the Hand to Hand & RPA Combat selector.
- Add styles for dark mode.
- Add "Show Armor warnings when damage is taken on last layer" option.
- Fix issue where adding a modifier duplicated it in the Modifier Picker.
- Remove extraneous Break Fall in a couple of places.
- Fix issue where remaining armor output was displaying the pre-damage amount.
- No attributes were changed or removed.
- Not a new sheet.
=> Palladium Rifts by Grinning Gecko v1.4 

The_Dee_Sanction/The_Dee_Sanction.css
=> [The Dee Sanction] changes to accommodate  Dark Mode

AllforOne/AllforOne.css
Adjusted some button dimensions
Adjusted position of of More Details label.
=> [All For One] changes to accommodate  dark mode

TheyCameFromBeyondTheGrave/README.md, TheyCameFromBeyondTheGrave/tcfbtg.css, TheyCameFromBeyondTheGrave/tcfbtg.html
Roll buttons added to skills and paths.
=> [They Came From Beyond The Grave] - Added roll buttons for skills and paths

Knight/knight.css, Knight/scss/files/templates.scss
=> [Knight]Fix CSS

Sengoku/Sengoku.css
changes to accommodate dark mode
change repeating section control appearance
changed length of skill name as the roll button was  wrapping 
=> [Sengoku] changes to accommodate dark mode

HeroSystem6eHeroic/HeroSystem6eHeroic.css, HeroSystem6eHeroic/HeroSystem6eHeroic.html
Changes made to preserve the appearance of the sheet and roll templates between light and dark modes.
Replaced most instances of 'label' where possible since Roll20 appears to override its text color settings.
=> [HeroSystem6eHeroic] Updates for compatibility with the new dark mode.

Runequest3/Runequest3.css
changes to accommodate dark mode 
changed appearance of repeating section controls
=> [RuneQuest 3] changes to accommodate dark mode 

Twilight-2000-v2.2/Twilight2000.css
=> [Twilight 2000 2.2] changes to accommodate dark mode 

Heroquest_Glorantha/Heroquest_Glorantha.css
=> [HeroQuest Glorantha] changes to accommodate dark mode

Pathfinder Community/pathfinder_community.css
- couple dark mode adjustments.
=> PF Community Sheet

Halo_Mythic_3dot5/HaloMythic4dot0.css, Halo_Mythic_3dot5/HaloMythic4dot0.html
🟩 5 Expandable shield and armour block values need to be seperated
🟩 6 Allow scatter macro to accept negative values through abs()
🟩 7 allow for DOS to be exact or rounded down
- [none removed] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
If you do not …
=> Halo mythic 3_dot_5 fix

BESM4eExtras/BESM4eExtras.html
Cached values framework - provides performance enhancements by collecting all sheet values on open event, then maintaining a cache of these values in a single JSON called each successive event after open.
=> [BESM4eExtras] v1.6.0

HeroSystem6eHeroic/HeroSystem6eHeroic.css
Fix to address hard to read dice rolls in custom roll templates.
=> [HeroSystem6eHeroic] Roll template styling update to fix dark mode issue.

Monster of the Week Official/MotWCSS.css, Monster of the Week Official/sheet.json
Preliminary darkmode support added. Adjusted contents of sheet.json now that this has been done, as the stylesheet no longer requires legacy css sanitization.
=> [Monster of the Week Official] Darkmode support added

World Wide Wrestling 2nd Ed/sheet.json, World Wide Wrestling 2nd Ed/wwwrpg.css, World Wide Wrestling 2nd Ed/wwwrpg.html
Minor adjustments so that text on character sheet and roll templates looks good with new dark mode changes.
Does NOT add full dark mode version of the sheet (this may be added in the future though).
=> WWWRPG 2nd Ed - Dark Mode Compatibility

Mutants and Masterminds 3E/mutants-and-masterminds.css, Mutants and Masterminds 3E/scss/files/page1.scss, Mutants and Masterminds 3E/scss/files/page23.scss
=> [M&M] CSS Fix

Palladium Fantasy 2E Sheet/palladium_fantasy_2E.css, Palladium Fantasy 2E Sheet/palladium_fantasy_2E.html, Palladium Fantasy 2E Sheet/sheet.json
Updated the css to enable CSE.
Added roll buttons in the Inventory tab.
Updated roll templates to be usable with dark mode.
=> Palladium Fantasy 2E

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Added official support for Roll20 Dark Mode
- Added Hypnotism to Advanced Skills (Power behind the Throne, EiS vol3)
- Various Bug fixes
=> [Warhammer 4e Character Sheet] Dark Mode support

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix drone phys monitor

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/sheet.json, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* Fixed crit & botch inversion
* Fixed condition "Rapture" for attacks
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.1.2

Trinity_Continuum_2ed/TC2e.css, Trinity_Continuum_2ed/TC2e.html
I would like to request that this Sheet be placed in the System Subcategory "Storypath", since this sheet belongs to this system.
It is currently in the "Trinity" system subcategory. What Doesn't Fit This Sheet. 
=> [Trinity Continuum 2e] - Minor Corrections

Thirsty Sword Lesbians/TSL.css, Thirsty Sword Lesbians/TSL.html, Thirsty Sword Lesbians/sheet.json
- Added bladesoul playbook (third party)
- Weaned CSS off legacy sanitization
- Added support for dark mode
=> [Thirsty Sword Lesbians] New playbook, no legacy CSS, dark mode support

HarnMaster3/harnsheet.html, HarnMaster3/harnstyle.css
Finetune some colors for darkmode based on user feedback.
=> [Harnmaster3] Finetune darkmode

HeroSystem6eHeroic/HeroSystem6eHeroic.css
Fix to remove white background color in dark mode.
Fix to restore readability of numeric results produced by roll templates.
=> [HeroSystem6eHeroic] Fixes for styling and readability in dark mode.

Masks - A New Generation/masks.css
To change the color of the font
=> [Masks] Darkmode

Official Savage Worlds/SavageWorldsCharSheet.css
=> Official Savage Worlds v1.00.24.1 - CSS Update for Darkmod

CWOD-V20/V20.html
Fixes:
- bug that the Dice Main and Combat dice sections were synced with each other
=> [CWOD-V20] Bug Fix for dice section

Masks - A New Generation/masks.css
Resolving some extant issues with the CSS styling for darkmode.
=> [Masks: A New Generation] Bugfix - Resolving CSS bugs

BESM4eExtras/BESM4eExtras.html
The Great Bug Hunt!
* Upgrade to 1.3.1 toString function now correctly uses underscorejs syntax (and works).
* Function createSkill() now adds new skill ID to cache.
* Function buildSkillsUI() now writes skillmap correctly.
* Fixed skill stat adjustment bug, now defaults level to 0 if NaN.
* Refactored createSkill() function: moving to writeValues() function in certain cases to resolve cache out of sync issues. POCed on createSkill() function.
* Fixed ammo/capacity persistence with new caching system.
* Stat changes are now reflected in skill rolls.
* New characters will now be able to roll 2d6 from roll menu (previously had no default value set).
* Attribute Augmented (stat) now works!
* Attack/Defense Mastery attributes will now be added/removed from ACV/DCV rolls, …
=> [BESM4eExtras] v1.6.2

Heroes-Unlimited-2E/hu2.html
Corrected a bug where lift capacity was not double carry capacity with normal strength above 17.
Corrected a bug where lift capacity was being calculated as x400 instead of x500 of ps score with supernatural strength toggled on in settings.
Corrected a bug that kept an input field from correctly retaining text (somehow a class designation had migrated to type in that line).
Added a note about the update to the documentation tab.
=> Heroes Unlimited 2E, lift calculation bug fix

BESM4eExtras/BESM4eExtras.html
v1.6.3
* Weapon attributes with 'no hands' enhancement will no longer arm weapons as if they were an 'extra arm' attribute.
* Fixed ammo persistency when arming other weapons, previously only persisted when unarming before switching weapons.
* Extra Arms attribute (and weapons with no hands enhancement) arming button now shows depressed when selected.
=> [BESM4eExtras] v1.6.3 - bug fixes

PokemonTabletopAdventures_v3/PTA3.css
- Electric type text background color was set incorrectly after last update - reverted to what it was before
- Water type backgrounds were set to the dark mode version even for light mode - corrected light mode
=> PokemonTabletopAdventures_v3 - Bugfix - Fix mistaken color changes

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
LR and Cripple Rework to the Character sheet.
=> LR and Cripple Rework - Fallout VNDPNP

Palladium Fantasy 2E Sheet/palladium_fantasy_2E.css, Palladium Fantasy 2E Sheet/palladium_fantasy_2E.html
Changed a class from divider to minmaxdivider to avoid applying a background color style to the Attributes & Abilities tab dividers.
Altered the "custom" and "spells" roll templates to display urls and macro buttons in bold text.
=> Palladium Fantasy 2E, roll templates now display links in bold font

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed visibility of Tinker, Second Sight, Warrior Born, and Wealthy Talents
=> [Warhammer 4e Character Sheet] - Fixes in talents visibility

ButterflyAspect/ButterflyAspect.html
=> [ButterflyAspect] Bugfix

BESM4eExtras/BESM4eExtras.css, BESM4eExtras/BESM4eExtras.html
BESM4eExtras.css
v1.7.1
Merged attribute options button function with attribute lock button, and removed options button.
Changed roll template to display damage label as normal or stun, rather than have a separate line entry for stun.
=> [BESM4eExtras] v1.7.1 - Simple UI Changes

BESM4eExtras/BESM4eExtras.html
v1.7.3
Consolidating options and lock functionality into a single lock button surfaced a bug previously unnoticed. Resolved issues where a newly added attribute would get out of sync with lock button state, showing the options menu when locked, and hidden when unlocked.
v1.7.2
Fixed bug where if an attribute was unlocked and options menu open when sheet upgraded to 1.7.1, the lock function would work with the lock icon open/close state reversed.  Now lock icon should display correct state with open/close options …
=> [BESM4eExtras] v1.7.2 - Open Lock Bug Fix

BESM4eExtras/BESM4eExtras.html
v1.7.4
Added support for alt-munitions limiter.
=> [BESM4eExtras] v1.7.4 - New Feature: Alt-munition Limiter Support Added

Palladium Fantasy 1E/palladium_fantasy_1e.css
Removed the extra padding around the sheet to avoid the white border in dark mode.
Fixed a few css names to bring back some missing left padding on certain sheet tabs.
=> Palladium Fantasy 1E, css padding adjustments

Heroes-Unlimited-2E/hu2.css
Removed the extra padding around the sheet to keep there from being a white border around the sheet in dark mode.
Fixed a couple css names to bring back some missing internal left padding in the sheet.
=> Heroes Unlimited 2E, css padding adjustments

Palladium Fantasy 2E Sheet/palladium_fantasy_2E.css
Removed extra padding from around the sheet to remove the white border in dark mode.
Fixed a couple class names to bring some internal left padding back to the sheet.
=> Palladium Fantasy 2E, css padding adjustments

The One Ring 2e/release-notes.md, The One Ring 2e/sheet.css, The One Ring 2e/sheet.html
=> [The One Ring 2e] - 02.11.00 - added feature: tabs for notes area

HarnMaster3/harnsheet.html, HarnMaster3/harnstyle.css
N/A
Added styling with media query to try and provide a more legible view on mobile browsers.
=> [HarnMaster3] Styling - Mobile browser view

Alien Roleplaying Game/Alien-Roleplaying-Game.html
Fixed a spelling mistake in an API roll button value
Updated the version to 4.03 and the change log
=> [Alien RPG] Minor bugfix

Palladium Fantasy 2E Sheet/palladium_fantasy_2E.css
Padding adjustment to collapsing sections
=> Palladium Fantasy 2E, padding adjustment to collapsing sections

Palladium Fantasy 1E/palladium_fantasy_1e.css
Padding adjustments to collapsing sections
=> Palladium Fantasy 1E, padding adjustments to collapsing sections

WFRP4CharSheet/WFRP4Charsheet.html, WFRP4CharSheet/translation.json
- Added new localization tags -> Issue #10332
=> [WFRP4CharSheet] - Added new localisation tags

Better-Angels/better-angels.html
Better Angels Sheet: Replaced d10sdk0 with d10mtsd because the point of the system is to find and sort matching sets, whereas the current script just dumped the dice out as is and then returned a 0 as the total result.
=> [Better Angels] Fixed roll outputs on character sheets to be more useful for system via mtsd

BESM4eExtras/BESM4eExtras.css, BESM4eExtras/BESM4eExtras.html
v1.7.6
* Improved depress button visualization
v1.7.5
* Fixed weapon arming bug.
* Enhanced cache write logic to prevent writing undefined values.
=> [BESM4eExtras] v1.7.6 - Arming Bug Fix, UI Enhancement

PokemonTabletopAdventures_v3/PTA3.css
- Ensures inline roll results embedded within notes fields do not have any border or padding, so text around them is not covered by their border
- Adjusts inline roll results styling to ensure the text matches the rest of the notes fields
=> [PokemonTabletopAdventures_v3 - New Feature]: Squashes some inline roll results

Monsters and Other Childish Things/MaOCT.html
Changed dice results to display matches instead of sums, since this system doesn't use those.
=> [Monsters and Other Childish Things] Changed Results Output

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/translation.json
- Added new psychology table to main tab
=> [Warhammer 4e Character Sheet] - Added Psychology table to main tab

HarnMaster3/harnsheet.html, HarnMaster3/harnstyle.css
Fix Tab button styling in light mode. Add changelog info for latest update.
=> [HarnMaster3] Minor updates - styling tweak and changelog bump

Coriolis Alternative/CoriolisAlternative.html
The attributes in the sensors button were incorrect as reported here: https://app.roll20.net/forum/post/10807435/coriolis-alternative-typo-in-the-sensors-command
=> Update Coriolis Alternative

etoiles/etoiles.css, etoiles/etoiles.html, etoiles/translation.json
display success or failure when throw dice
=> etoiles new feature

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix import of stick-n-shock arrow

True20/true20.css, True20/true20.html
Added a toggle to switch between Select and Input, on Background, Role, and Size, as requested here: https://app.roll20.net/forum/permalink/10817760/
=> True20 Update

Chronicles of Darkness/CofD.html
Fixing the issue with Brawl attacks not adding damage and fixing a typo where the attack number was set to 1 instead of the variable.
=> [Chronicles of Darkness] Bugfix

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix cyberware armor import

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix import of stick-n-shock arrow again

Chronicles of Darkness/CofD.html, Chronicles of Darkness/translation.json
Removed dots for Changeling Contracts in 2nd edition.
Removed Derangements and Flaws for 2nd edition games.
Added Goblin Debt stat for Changeling 2nd edition.
Added Frailties and Fae Mount to 3rd page for Changeling 2nd edition and removed Entitlements and Goblin Contracts.
Replaced Harvest for Changeling with Token.
=> [Chronicles of Darkness] Contracts Fix and Changeling 2e Additions (bugfix/new features)

Ultima Torcia - Pagina Singola/lutps.css, Ultima Torcia - Pagina Singola/lutps.html
Added a feature. Now, if the checkbox on the left of an attribute is checked, the value of the dice change
=> [Ultima Torcia - Pagina Singola] added merit function, a new feature

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix critical glitch detection

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
PR #10501 & #10512 earlier this week did not reach the roll20 website sheets. 2nd attempt.
=> [Warhammer 4e Character Sheet] Re merge attempt

ADnD_2E_Revised/2ESheet.html, ADnD_2E_Revised/html/changelog.html, ADnD_2E_Revised/javascript/sheetWorkers.js, ADnD_2E_Revised/javascript/version.js
Fixed a bug due to bad javascript code
=> [ADnD 2E Revised] Bugfix: Fixed reset spell slots for current level of spells

Ultima Torcia - Pagina Singola/lutps.html
=> [Ultima Torcia - Pagina Singola] fixed merit function

Ryuutama/Ryuutama.html
=> [Ryuutama][Fix] Fix hot using deep fog mod value

The One Ring 2e/release-notes.md, The One Ring 2e/sheet.html
- Fixed stance damagebonus should be dependent on the stance damage active checkbox (error was introduced with the grievous selectbox)
=> [The One Ring 2e] - 2.12.01 - bugfix stance damage bonus

PokemonTabletopAdventures_v3/PTA3.html, PokemonTabletopAdventures_v3/README.md
- Add support for importing character sheets by using the VTTES tool
- Community member used this to create every Pokemon, so this lets others take advantage of that work even if they can't use that tool
=> PokemonTabletopAdventures_v3 - New Feature - JSON import support for VTTES

Reign1E/reign.css, Reign1E/reign.html
Currently, it seems like the CSS isn't connecting to the HTML for the Reign 1E sheet. I'm pretty sure this is because the CSS style sheet lacked the "sheet-" header for all of the objects the CSS was trying to place and edit. There was also some random dividers that weren't really doing anything hangin about, so I deleted those while I was at it. When using the CSS sheet manually (using a header with link) it works fine, so I think this should fix it? Unsure if I can really test it myself. This seems like a pretty basic issue though, so if this isn't the correct approach hopefully someone can correct me on how to fix it.
=> Fixing lack of CSS for Reign 1E sheet

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/translation.json
- Implemented Unshakable Talent, which adds conditional bonus to Cool tests.
- Fixed Briber Talent naming, it was incorrectly named Bribery.
- Fixed Channelling test miscast indicator on Unit die 0, now occur only when roll is above the target number.
- Button Hover style no longer inverts text color, text remains white with black shadow.
=> [Warhammer 4e Character Sheet] Talents & fixes

Palladium Megaverse/palladium_megaverse.html
Minor spelling mistake fixes for the character sheet.
=> Palladium Megaverse: Bugfix (minor spelling mistake fixes) for palladium_megaverse.html

ADnD_2E_Revised/2ESheet.html, ADnD_2E_Revised/2EStyle.css, ADnD_2E_Revised/css/2EStyle-base.css, ADnD_2E_Revised/css/rolltemplates.css, ADnD_2E_Revised/html/changelog.html, ADnD_2E_Revised/html/components/rolltemplates.html, ADnD_2E_Revised/html/tabs/character-tab/attributes-tab/attributes-players-option.html, ADnD_2E_Revised/html/tabs/character-tab/attributes-tab/attributes-standard.html, ADnD_2E_Revised/javascript/sheetWorkers.js, ADnD_2E_Revised/javascript/version.js
All changes can be seen on the forum: https://app.roll20.net/forum/permalink/10866076/
=> [ADnD 2E Revised] New Feature: Ability score templates outputs

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.2.2 Bugfix

BESM4eExtras/BESM4eExtras.html
v 1.8.2
* Fixed getAttrCost() function not returning cost of Alternate Form attribute.
=> [BESM4eExtras] v1.8.2 - Bug Fix

Knight/knight.html, Knight/pug/html/templates/mechaArmure.html, Knight/pug/js/knight.js, Knight/pug/js/rolls/pj/mechaArmure.js, Knight/translation.json
=> [Knight] Bugfix Mode Wraith / Import

CP-Unofficial-Persona-TTRPG/crimsonparcelsupttrpg.html
- The name of this game is: <  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  > _(i.e. Wizards of the Coast, Evil Hat)_
A new feature will be added to the game to improve the UIs readability. As a result some names of elements will be changed. We have prepared for this by warning people two weeks earlier (the 28th of April).
Also we have changed the wording on an element from "Temp." to "Bonus" because of confusion.
=> New Feature for the Unofficial Persona TTRPG HTML 

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] glitch check for 0 success instead of no 5 or 6

Ironsworn/Ironsworn.css, Ironsworn/src/app/components/oracles/oracles.styl
A minor fix to increase the height of the columns to resolve a checker-boxing issue that was happening due to the height of the elements been too short.
=> [Ironsworn] [Fix] Increased Oracle Preview heights

Knight/knight.html, Knight/pug/html/templates/combat.html
=> [Knight] Fix translation

FightingFantasy/sheet.json
Fighting Fantasy changes in <code>sheet.json</code> file. Put "legacy":false
- The name of this game is:   Fighting Fantasy   _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Steve Jackson and Ian Licingstone _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Fighting Fantasy _(i.e. Dungeons & Dragons, FATE)_
=> FightingFantasy character sheet updated json file

HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added penalty skill levels as an option for combat skills.
The sheet will now force an update to characteristic totals when the option "Use Characteristic Maximums" is checked/unchecked.
Increased size of note text boxes in preparation for Hero Designer importer script under development.
Removed obsolete function for adding points.
=> [HeroSystem6eHeroic] Added Penalty skill levels. Option bug fix.

Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/translation.json
Add a new value to track how much would be recovered using the second wind feature as well as a button to apply the value to current hp when at or below half health
=> [Star Wars Saga Edition] New Feature Second Wind

Star Wars Saga Edition/StarWarsSagaEdition.css
Change the colour of the rolls so that when dark mode is enabled the values of the results stand out
=> Star Wars Saga Edition Bugfix Dark mode compatibility 

Star Wars Saga Edition/StarWarsSagaEdition.html
Add a new number box and heading in the HP section to allow players to track hit points on their character sheets.
=> Star Wars Saga Edition New Feature Bonus HP tracker

Star Wars Saga Edition/StarWarsSagaEdition.html
The new second wind sheet workers have an error in the code. This fixes them.
=> Star Wars Saga Edition Fix

Official Savage Worlds/SavageWorldsCharSheet.css, Official Savage Worlds/SavageWorldsCharSheet.html, Official Savage Worlds/sheet.json, Official Savage Worlds/translation.json
Bug Fixes:
1. Fixed styling causing skills, hindrances, edges, special abilities to flow off the character sheet on the condensed/statblock view
2. Fixed a missing button (unskilled) the condensed/statblock view
3. Fixed an issue with the token image not always displaying on the roll template
Updated the sheet.json to include theme options for the roll template
=> Official Savage Worlds v1.00.26 (Bug fix)

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
=> Blacksmith Skill Formula Change - Fallout VNDPNP

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html
Change second wind button to now post into the game chat, add a new template for the second wind "rolls" add a section for current and total second winds available. Added logic to lower current second winds as well as logic not to apply second wind when at 0 uses. Also cleaned up the layout a little.
=> [Star Wars Saga Edition] Feature Improves on second wind feature

Star Wars Saga Edition/StarWarsSagaEdition.css
Update the saga default css template to use white text on black background so when flipping to dark mode the rolls can be seen.
=> [Star Wars Saga Edition] Bug Rolls not readable in dark mode.

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed Spell lore effect not showing due to variable duplication
- Fixed Perception/Stealth modifiers not adding conditions correctly.
=> [Warhammer 4e Character Sheet] WoM fixes

Godsend/Godsend.html
Changed image link to roll20 repository.
Changed image link to point to the image in the roll20 repository.
=> Godsend (Update Image Link)

Star Wars Saga Edition/StarWarsSagaEdition.html
Update the address of the logo on the vehicle sheet to a working link
=> [Star Wars Saga Edition] Bug fix broken link to logo

PokemonTabletopAdventures_v3/PTA3.css, PokemonTabletopAdventures_v3/PTA3.html, PokemonTabletopAdventures_v3/README.md
- Adds some explanation text to the config page
- Adds some padding and a border-radius to the config page text background fields as well
=> [PokemonTabletopAdventures_v3] New Feature: Adds some explanation text to theh config page

Fate/FateOmni.css, Fate/FateOmni.html
Roll buttons in stunts and extras were not styling correctly after some earlier changes to accommodate the roll-out of darkmode.  This addresses that issue. (Some style work was needed in the CSS, but also a few buttons were left with an inconsistent class-name which made the CSS miss styling them entirely.)
=> [Fate] Updates to address some button styling issues

xenoscape/xenoscape.html
=> Xenoscaper - fix name attribute

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed NPC tab weapon rolls not working when Talent Integration is disabled.
- NPC Crit roll button will now follow UiA rules if active/selected.
=> [Warhammer 4e Character Sheet] NPC roll fixes

FightingFantasy/FightingFantasy.html, FightingFantasy/translation.json
- The name of this game is: Fighting Fantasy  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Steve Jackson and Ian Livingstone _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Fighting Fantasy _(i.e. Dungeons & Dragons, FATE)_
Fixed small issue regarding hero notes and backstory.
=> Small Changes in Fighting Fantasy Character Sheet

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix forced glitch template

Official Savage Worlds/SavageWorldsCharSheet.html
- Fixed an issue with the drag and drop of Races/Ancestries that prevented the name of the Race/Ancestry from populating the sheet's field
=> Official Savage Worlds fix for race drag and drop

The One Ring 2e/release-notes.md, The One Ring 2e/sheet.css, The One Ring 2e/sheet.html, The One Ring 2e/sheet.json, The One Ring 2e/translation.json
- added "fellowship focus" to pc sheet
- fixed some missing support for translations on the pc sheet (thanks to iosu Li for the spanish translation)
=> [The One Ring 2e] - 2.14.0 - better translation support and added fellowship focus

HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added missing variable declaration.
=> [HeroSystem6eHeroic] Minor bug fix

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.css, Shadowrun Sixth World/Shadowrun6thEdition.html, Shadowrun Sixth World/translation.json
Added the "Effects" Tab to the Attributes Pane
BugFix - fixed the D6 roll query to include the reason for the roll in the roll template output.
=> Shadowrun Sixth World v.52 Bugfix + New Feature

Star Wars Saga Edition/StarWarsSagaEdition.html
The if > was not working until I used the let to set the variables at first import changed all imports to be parsed at the start updated use where relevant sheet now working
=> [Star Wars Saga Edition] Bug fix on armor def check box

root/root.html
=> [Root RPG] Bugfix

BESM4eExtras/BESM4eExtras.html
v1.8.5
* Various bug fixes for weapons with ammo limiter,  no handed enhancement, and handed limiter.
=> [BESM4eExtras] Bug Fixes

FightingFantasy/FightingFantasy.css, FightingFantasy/FightingFantasy.html
- The name of this game is: Fighting Fantasy  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Steve Jackson and Ian Livingstone _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Fighting Fantasy _(i.e. Dungeons & Dragons, FATE)_
=> [Update] Fighting Fantasy Character Sheet. Added Roll Templates, changed styles.

EngineHeart/sheet.json
=> Added legacy switch to Engine Heart sheet.json.

GammaWorld7e/sheet.json
=> Added legacy switch to Gamma World 7E sheet.json.

RoleplayingIsMagic_4E/sheet.json
=> Added legacy switch to Roleplaying Is Magic 4E sheet.json.

TailsOfEquestria/sheet.json
=> Added legacy switch to Tails of Equestria sheet.json.

Pathfinder_Cazra/sheet.json
=> Added legacy switch to Pathfinder (Cazra) sheet.json.

Kult Divinity Lost/KULT Divinity Lost.css
Changed width on tab buttons so they don't wrap in different languages.
=> Kult Divinity Lost layout bugfix

Knight/pug/js/_functionsWeapons.js, Knight/pug/js/rolls/pj/ranger.js, Knight/pug/js/rolls/pj/simple.js
=> [Knight] Bugfix Longbow / Ghost / Defense

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Condition section was renamed to Health and it was redesigned to accommodate DR rework.
Armor Section was also redesigned to accommodate the DR Rework.
=> Combat Page Rework - Fallout VNDPNP

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.css, Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
Updates the Character Sheet with V1.1 ruleset.
=> Paradigm's RWBY TTRPG V1.0 - New Feature Ruleset Update V1.1

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
This is a Hotfix to fix the size of the Total DR Box.
=> DR Box Hotfix - Fallout VNDPNP

xenoscape/xenoscape.html
=> [XENOSCAPE] Bug fix

HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added "compound" as a power type.
=> [HeroSystem6eHeroic] Added compound power type.

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
SP Equation changed from 5 + (INT x 3) to 10 + (INT x 3).
=> SP Equation Changed - Fallout VNDPNP

Primal Quest/PrimalQuest.css, Primal Quest/PrimalQuest.html
- The name of this game is: Primal Quest  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Diogo Nogueira _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Primal Quest - Weird Stone & Sorcery _(i.e. Dungeons & Dragons, FATE)_
Dificulty field taken out. Added Defence Roll. Removed Weapon dices and styles.
*This sheet will improve with time.*
=> [Update] Primal Quest Character Sheet

Haunted-West-Character-Sheet/haunted_west.html, Haunted-West-Character-Sheet/sheet.json
=> [Haunted West] Bugfix - Adding default 0 value

Storypath/Storypath.html, Storypath/translation.json
- Fixed issue preventing the adding of custom health status
- Fixed issue that prevented movement and defense dice from being rolled
- Fixed an erroneous translation key
=> Storypath Fixes bug with adding health items and rolling movement/defense

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] rework technomancer wip

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
A complete overhaul of both sections to accommodate the changes to DR and change the display to rolls.
=> Weapon and Vehicle Section Redesign - Fallout VNDPNP

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Names couldn't be edited for some reason. It's been fixed.
=> Helmet and Armor Bugfix - Fallout VNDPNP

Knight/knight.css, Knight/knight.html, Knight/pug/html/tab/armure.html, Knight/pug/html/tab/subCombat/armure.html, Knight/pug/html/top/right.html, Knight/pug/js/knight.js, Knight/scss/files/_library.scss, Knight/translation.json
=> [Knight] Add Kraken

Tormenta20/tormenta20.html
The only change made was in line 254, due to the usage sab_mod instead of car_mod in the damage modifier for some attacks.
=> [T20] Bugfix: Correcting the error in line 254 where Wis was used instead of Cha

Ironsworn-Starforged/Ironsworn-starforged.html, Ironsworn-Starforged/src/app/workers/scripts/assets.js
There was a bug raised for custom ship assets where they were not being handled correctly. The asset worker functions for displaying the custom fields had been missed. Added those in now.
=> [Ironsworn - Starforged][Fix] Added missing functions for custom ship assets

Epyllion/Epyllion.css, Epyllion/Epyllion.html
Added Trickster Playbook to CSS and HTML
Revised character sheet selection to support Trickster, as well as supplemental playbooks that could be added in the future.
=> Epyllion - Added Trickster Playbook

Alternity-RPG/Alternity_RPG.html
* Added 5 more Weapon Data rows to complete the changes made in #10457
* Added Function field to Computer programs list to allow the player somewhere to detail what a program actually does
=> [Alternity RPG] Add 5 missing Weapon Data rows and Function field to Computer programs

The ADVANCED Pandemonium/the_ADVANCED_Pandemonium.css, The ADVANCED Pandemonium/the_ADVANCED_Pandemonium.html
Due to a few changes to the core system, the Bionics, Equipment and Stress feature were updated
=> ADVANCED Pandemonium sheet update due to changes in Stress Feature

TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add tools and consumables

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] minor bugfixes

Exalted2e/exalted2e.html
Added option to select Infernal Castes in the attr_Caste dropdown menu. Added Caste names to attribute columns
=> exalted2e.html  -  Added Abyssals/Infernals castes

Official Savage Worlds/SavageWorldsCharSheet.html
- Updates the drag and drop functionality to support the Soon to be released Archetypes category
=> SWADEArchetype drag and drop functionality

xenoscape/xenoscape.css, xenoscape/xenoscape.html
=> [XENOSCAPE] graphical improvment and alignment fixed

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] restore spirit/sprite data

HeroSystem6eHeroic/HeroSystem6eHeroic.html
Added type "unified" to power types.
=> [HeroSystem6eHeroic] Added unified power type.

TheWitcher/witchersheet.html
=> [TheWitcher] add weight of tools and consumables

Heroes and Hardships/hnh.css, Heroes and Hardships/hnh.html, Heroes and Hardships/sheet.json
Update the Heroes & Hardships sheet to match latest version of the core rulebook.
=> [Heroes & Hardships] Update sheet to match rulebook

Alternity-RPG/Alternity_RPG.css, Alternity-RPG/Alternity_RPG.html
* Adds separate social status fields.
* Adds repeating section for currency and their locations (to allow for bank accounts in different systems/planets)
* Fixes some layout issues
* Renames "Equipped?" column header to "Eqp?" as the former is too long and gets cut off.
=> [Alternity RPG] Layout fixes and wealth & social status additions

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
A visual update for the Health and Armor section.
=> Health and Armor Visual Update - Fallout VNDPNP

TheWitcher/sheet.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] move from legacy css

TheWitcher/translation.json
=> [TheWitcher] add missing translations

Exalted2e/README.md, Exalted2e/exalted2e.css, Exalted2e/exalted2e.html
Added Sidereal Ability lists, adjusted Terrestrial Craft to match others, corrected spelling error, corrected stat overpopulation error
I. Exalted2e.html
1. Added a Sidereals Ability section.
2. Corrected spelling of Awareness from Awarness in Dragonblooded abilties
3. Updated Dragonblooded Craft ability to have the same dropdown as all other Castes
4. Corrected error causing Solar abilities to overpopulate above other castes at max dots
II. Exalted2e.css
5. Added infernal ability sheets
6. updated other Castes to appropriate ability …
=> Exalted2e  Added Sidereals, error fixes

Heroes and Hardships/sheet.json
Legacy sanitization opt-in was missed in the last update to the Heroes and Hardships sheet.
=> [Heroes and Hardships] Bugfix: Add legacy sanitization opt-in

Alternity-RPG/Alternity_RPG.html
* Migrate data from attributes that were removed from the sheet in #10791 
* Remove Wealth "Steps" field that was incorrectly added
=> [Alternity RPG] Migrate data from old currency/social attributes to their new homes

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] melee attack from weapon template

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
New Feature - Added Notes imports to all repeating sections with a notes field except Sprites and Spirits (players should really be using separate character sheets for these)
=> Shadowrun Sixth World v.54 - 1 New Feature

HeroSystem6eHeroic/HeroSystem6eHeroic.html
Typo in PD and ED cost function led to incorrect defense costs for characters with the Takes No STUN option checked.
=> [HeroSystem6eHeroic] Bug fix: variable name typo corrected

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] first step for new npc layout

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
AP Box was added.
SQ and Damage Calculator were moved to the same line.
Fixed Critical Failure displaying.
=> Health Section Adjustments - Fallout VNDPNP

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add campaign info

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
-Fix for NPC casting not working correctly.
=> [Warhammer 4e Character Sheet] NPC cast fix

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] css improvements

approved.yaml
=> Adjust approved for Frontier Scum to match folder

BESM4eExtras/BESM4eExtras.html
v1.8.6
* Changed stat cost to reflect Core Rulebook values, i.e. 2 character points per stat value up to stat value of 12, and 4 character points per stat value above stat value of 12.  Existing sheets will upgrade to correct the stat value costs, and return overages as available character points.
=> [BESM4eExtras] v1.8.6 - Enhancement

Trinity_Continuum_2ed/TC2e.css
After the last merge of the Trinity Continuum 2e sheet for some reason, the roll templates are not showing up with a correct icon. As a result of this I'm doing a new PUSH in an attempt to solve the errors.
=> Trinity Continuum 2ed - Bug fix - RollTemplate Icon

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
Fixed Unarmed Attack's formula calculating incorrectly
Fixed Thrown Melee Weapon Attack with Gyrostabilizers
Added Vehicle Tab and Content
Covering Fire has been deprecated
Fixed Unarmed Attack's formula calculating incorrectly
Fixed Thrown Melee Weapon Attack with Gyrostabilizers
Added Vehicle Tab and Content
Covering Fire has been deprecated
=> New Feature Paradigm's RWBY TTRPG V1.12.html

Basic_Roleplaying/Basic_Roleplaying.html
Grapple Skill Value wasn't displaying on the output due to missing code
=> [Basic Roleplaying] Minor Bug Fix to Grapple Skill

Farsight RPG Community Edition/sheets.css, Farsight RPG Community Edition/sheets.html
- Fixed width of "Punti Vitalità" label: The label was more large than the sheet max-size.
- Fixed width of checkboxes: changed width from auto to 15px, there was an issue where to activate them you need to click slightly left.
- Deleted ability "Manomettere": this ability came from an alpha version of the game, now has been deleted.
- Fixed attributes in short bio: "Specie" and "Classe e Livello" was missing for attribute registration, now they will be saved properly.
=> [Farsight RPG Community Edition]css, attributes fix and skill update

AGE System/AGE System.html
I fixed a bug earlier, but only on one section of the sheet. This update fixes that bug in another section.
I was tired of inconsistent spacing, so I standardized length of indents.
I fixed a bug earlier, but only on one section of the sheet. This update fixes that bug in another section.
I was tired of inconsistent spacing, so I standardized length of indents.
=> AGE System Bugfix

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.css
Adds the vehicle tab CSS to the character sheet to allow hiding of the tab.
Adds the vehicle tab CSS to the character sheet to allow hiding of the tab.
=> CSS Update Paradigm's RWBY TTRPG V1.12

Trinity_Continuum_2ed/TC2e.css
=> BugFix - Trinity Continuum 2ed - icon Problem

Inspectress-Inc/translation.json
fix typo TECNOLOGY -> TECHNOLOGY
=> Update translation.json for Inspectress-Inc

Knight/knight.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/rolls/pj/combatDistance.js
=> [Knight]Bugfix Démoralisant & Goliath

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
Fixes melee damage and missing items on the Vehicles tab.
Fixes melee damage and missing items on the Vehicles tab.
=> Hotfix for Melee Damage Fix

GURPS/gurps.css, GURPS/gurps.html, GURPS/translation.json
- Skills Tab. Add a collapsible notes area.
- Skills Tab. Added an indicator to show a skill has **Conditional notes**
- Combat Tab. Add a collapsible notes area.
- Combat Tab. Defense sub-tab. Increased the height of the **DEFENSE BONUS (DB) NOTES** box.
- New Slam Tool. Moved to Tools sub-tab.
- Editable Wound Modifier Notes: Updated initial default notes to include **Injury to Unliving, Homegenous, and Diffuse Targets. B380**. Requested and notes provided by kawaishi. 
-
=> Gurps 2.8.1

Edge of the Verse/edgeoftheverse.css, Edge of the Verse/edgeoftheverse.html
=> [Edge of the Verse] update (add new characters) & minor bugfix & style fixes

HARP/harp.css, HARP/harp.html
- [x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) …
=> Harp roll template update 2208

Blades in the Dark/blades.css
Minor changes to fix dark mode compatibility:
* Removed dark purple inline roll highlights
* disabled z-index for cohort condition names and hold strength, as they disappeared in dark mode
=> [Blades in the Dark] Dark Mode compatibility adjustment

approved.yaml
=> Add official to Apocalypse Keys in approved

TheWitcher/witchersheet.html
=> [TheWitcher] placeholder for diagram/formula

Alien Roleplaying Game/Alien-Roleplaying-Game.html, Alien Roleplaying Game/translation.json
Internationalizations' refs where malformed in some of the panic roll descriptions.
The description for rolls 1 to 6 was missing along with all the panic rolls entries in translation.json file.
Replaced the `–` and `’` unusual unicode characters for common `-` and `'` ones, as recommended by VS Code linter.
=> Alien Roleplaying Game. Bugfix. Fix panic roll translation refs.

Magic_World/magicworld.css, Magic_World/magicworld.html, Magic_World/sheet.json
- [x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) …
=> Magic world roll template and cosmetic update 080422

HARP/harp.css, HARP/harp.html
- [x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) …
=> Harp roll template update 220804

HeroSystem6e/HeroSystem6e.css
By switching almost all of the CSS "height" properties to "min-height" properties we are able to allow fields to expand and show otherwise invisible overflow text.  With some other minor changes we have properly resizing rows to allow for long descriptions.
=> Update HeroSystem6e.css to allow long descriptions to wrap

Warpland/Warpland.css
For some reason, the size in CSS file is not taken into account. The !important keyword has to be used.
=> [Warpland] fix: force size of attribute input

The One Ring 2e/release-notes.md, The One Ring 2e/sheet.html, The One Ring 2e/sheet.json
- added json import for adversaries (please note that this is not a compendium. No copyrighted material is part of the sheet. The sheet offers only a way to populate the attributes of a single adversary by copy and pasting a json into a notes textarea).
=> [The One Ring 2e] - 3.0.0 - New feature: added adversary importer

Knight/knight.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/knight.js, Knight/pug/js/rolls/pj/combatContact.js, Knight/pug/js/rolls/pnj/combatContact.js
=> [Knight] Bugfix Wizard & Barbelee

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* Movement speed should now be properly affected by conditions
* Ranged combat should not be affected by encumbrance anymore
* Off-hand modifiers should now work properly
* Skill specializations should now be calculated properly
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.2.3 Bugfix 

Basic_Roleplaying/Basic_Roleplaying.html
The martial arts skill was outputting the wrong skill rating by adding a Combat Bonus that it wasn't suppose to have.
=> [Basic Roleplaying System ]Fixing Martial Arts skill

D6StarWars/CHANGELOG.md, D6StarWars/D6StarWars.css, D6StarWars/D6StarWars.html
All white labels on every character sheets got unreadable. This merge request try to fix that issue.
This merge request try to fix that issue.
=> [D6StarWars] 2.44 - Sheet readability fix

HeroSystem6e/HeroSystem6e.css, HeroSystem6e/HeroSystem6e.html
- Update combat maneuver notes
- Add dropdown for selecting number of attacks on Multiple Attacks maneuver
- Integrate that dropdown into the combat preview
=> Modify HeroSystem6e.html and css to improve combat maneuvers

Official Savage Worlds/SavageWorldsCharSheet.html
- Adds support for drag and drop from the upcoming `SWADE Archetypes` category.
- Fixed an error in the parsing of drag and drop vehicles and bestiary entries with vehicles.
=> Savage Worlds Official - Update for SWADE Archetypes support

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
WR was removed. FM was changed to NV. VL Equation changed from (CHA x 2) +1 to CHA +1.
=> Fallout VNDPNP - Small Adjustments

TheWitcher/witchersheet.html
=> [TheWitcher] fix fumbled by of repeating rows

Official Savage Worlds/SavageWorldsCharSheet.html
- Just removing one line of `debugger` that was left in from bug hunt
=> Remove debugger call that was left in erroneously

TheWitcher/witchersheet.css
=> [TheWitcher] fix armor figure positioning in chrome

Star Wars Saga Edition/StarWarsSagaEdition.css
Update the colours so when dark mode is enabled the text is still legible
=> [Star Wars Saga Edition] Bugfix for when dark mode is enabled

Aborea_new/aborea.html, Aborea_new/macro_templates/wildemagie.txt
wrong mana calculation corrected
=> [Aborea]bugfix

Classified/Classified.html
Fixed Bug the prevented Incapacitated wound level on pc sheet being selected.  Incorrect for value for  label.
=> [Classified] Fixed Bug the prevented Incapacitated wound level on pc sheet being selected

TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] fix some css issues and rework background tab

HeroSystem6e/HeroSystem6e.css, HeroSystem6e/HeroSystem6e.html
- Added common Martial Maneuvers from rules
- Moved Combat Skill Levels to narrow column
- Added "Pur" column to flag purchased Martial Maneuvers
=> Update HeroSystem6e.html and css to add Martial Maneuvers

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add settings page and some settings

TheWitcher/witchersheet.html
=> [TheWitcher] add athletics to weapon skills

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Removed critical rt display for Prayer spells, as they do not get dubs random criticals, only fumbles.
=> [Warhammer 4e Character Sheet] Remove Pray Crits

Knight/knight.css, Knight/knight.html, Knight/pug/html/tab/armure.html, Knight/pug/html/tab/subCombat/armure.html, Knight/pug/html/tab/subCombat/bottom.html, Knight/pug/html/tab/vehicule.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/rolls/pj/combatGrenade.js, Knight/pug/js/rolls/pj/combatImprovise.js, Knight/pug/js/rolls/pj/druid.js, Knight/pug/js/rolls/pj/mechaArmure.js, Knight/pug/js/rolls/pj/monk.js, Knight/pug/js/rolls/pj/ranger.js, Knight/pug/js/rolls/pj/wizard.js, Knight/scss/files/tabs/armure.scss, Knight/scss/files/tabs/combat.scss, Knight/translation.json
=> [Knight] Bugfix previous update

The One Ring 2e/release-notes.md, The One Ring 2e/sheet.html, The One Ring 2e/sheet.json
- target attacks calculate priercing blow correctly
=> [The One Ring 2e] - 3.02.00 - fixed piercing blow 

TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] fix used skill checkbox

DCC_Tabbed_Sheet/DCC_Tabbed_Sheet.css, DCC_Tabbed_Sheet/DCC_Tabbed_Sheet.html
In the [previous PR](https://github.com/Roll20/roll20-character-sheets/pull/10955) some code was accidentally included. This PR removes it.
=> [DCC_Tabbed_Sheet] Bugfix: Remove accidentally committed code

DnD_5e/DnD_5e.html
Top tab and info block got swapped in the last update. Fixed it here
=> Cleanup and Error Fix

TheWitcher/witchersheet.html
=> [TheWitcher] add character name correction to not break functionalities

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] attack chain

GURPS/gurps.css, GURPS/gurps.html, GURPS/translation.json
First iteration of resync button.
- Options. Sheet-options tab. Added initial <b>Resync</b> button.  First iteration resyncs Skills, Techniques, and spells, along with items linked to them.  Followed by resyncing the weight and cost of items in the inventory.
=> GURPS 2.8.2

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/translation.json
- Added translation tags for Blessings spell list.
=> [Warhammer 4e Character Sheet] Add il8n tags

Knight/knight.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/rolls/pj/combatContact.js, Knight/pug/js/rolls/pj/combatDistance.js, Knight/pug/js/rolls/pj/combatGrenade.js, Knight/pug/js/rolls/pj/combatImprovise.js, Knight/pug/js/rolls/pj/monk.js, Knight/pug/js/rolls/pj/ranger.js, Knight/pug/js/rolls/pj/simple.js, Knight/pug/js/rolls/pj/wizard.js
=> [Knight]Bugfix Shaman

Neuroshima/Neuroshima.css, Neuroshima/Neuroshima.html, Neuroshima/Script.js, Neuroshima/Umiejetnosci.html, Neuroshima/Wspolczynniki.html, Neuroshima/readme.md
1) Typo in one of the skill names caused rolls for Otwieranie Zamków (lockpicking) to not work. Credit to Jakub for finding this bug!
2) Selection of skill groups (specjalizacje) now automatically highlights skills from that specialization. There is no additional mechanic meaning to the highlight and players can override post-selection anyway
3) Minor dark mode fix
=> Neuroshima v2 feature - auto-select skills from specialization, bugfix - fix skill Otwieranie Zamków, fix dark mode visibility

TheWitcher/witchersheet.html
=> [TheWitcher] add location button to detailed spellcasting

TheWitcher/witchersheet.html
=> [TheWitcher] add weapon effect to chain

GURPS/gurps.css, GURPS/gurps.html
Options Tab. Sheet Options sub-tab. Resync button - made some improvements with data syncing for skills and spells.
Options Tab. Sheet Options sub-tab. Resync button - made some improvements with data syncing for skills and spells.
=> GURPS 2.8.3

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.2.4 Bugfix

Knight/knight.html, Knight/pug/js/rolls/pj/combatImprovise.js, Knight/pug/js/rolls/pj/simple.js
=> [Knight] Bugfix Several rolls

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
Removed Level/2 from Unarmed Attacks
Added modifiers for all Vehicle Weapons
Removed global Vehicle Heavy Caliber modifier
=> Paradigm's RWBY TTRPG V1.122 Update (9/3/22)

HARP/harp.css, HARP/harp.html
UPdates and expansions to Skill professions and species. Customization of Race and Species allowed. Extended support of multi-classing and …
=> HARP profession species and skills Update 220901

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
SQ roll changed from d20 to d10.
RS was removed.
DE equation was changed from PER x 10 to 25 + (PER x 5).
SSD and SSC were combined to be SS.
=> Fallout VNDPNP - RS Update

Tierras Quebradas/tierrasquebradas.html
=> [New feature] Tierras Quebradas

D&D_BECM/BDnDSheet.css, D&D_BECM/BDnDSheet.html
- Updates Logo and Footer image urls to point to the Roll20 master branch
- Corrects the custom abilities header css to ensure it is legible in light and dark mode
- Updates the custom abilities header to read Special Abilities
- Updates the CSS for select and input elements in repeating items to ensure they are easier to see
=> [D&D_BECM] Bug Fix: Updates image urls and corrects css

D&D_BECM/BDnDSheet.css, D&D_BECM/BDnDSheet.html
- Adds all selects to the CSS rule defining the background color
- Updates custom ability repeating field to display Special Ability instead of Custom as per the title of the repeating fields
=> [D&D_BECM] Bugfix: Ensures select elements have the right background color

ShadowbaneInquisition/Shadowbane.html
changed xp cost to fit the new updated ruleset
=> [Shadowbane Inquisition] Updated xp cost for new ruleset

Epyllion/Epyllion.html
Adds the Elementalist, Envoy, Orphan, and Rebel playbooks from Encyclopedia Draconica.  Minor fix to Trickster playbook.
=> Epyllion: Add Encyclopedia Draconica Playbooks

TheWitcher/witchersheet.html
=> The witcher punch kick attack chain

ShadowbaneInquisition/Shadowbane.html
fixed typos and values that caused wrong calculations
=> [Shadowbane Inquisition] bug-fix

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* The weight of single items can now be ignored (checkbox)
* The talent value is now included in the roll template
* Initial support for hitzones
* Information and quick access for all available expansions
* Post combat special abilities also from combat tab
* Inventory item pictures can now be enlarged by hovering on the thumbnail
* Some sections can now be collapsed
* Support for weapon and armor damage (break point rating)
* Botch rolls now have a button to repeat the roll
* The NPC-sheet now profits from armor items
* Poison can …
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.3.0 New features

World of Fantasy/wof.css, World of Fantasy/wof.html
=> [World of Fantasy] New layout aspect

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
9/16/2022
Aligned Signature Action section with new book updates. Shared Resources are now applied to each tab
=> Paradigm's RWBY TTRPG Update V1.2 - 9/16/2022 

Das_Schwarze_Auge_4-1/dsa4_1_character_sheet_roll20.html
- **Fixes**
- Initialize attributes not backed by <input> or <span>, only apply to fresh characters (8d134e935)
- **Utilities**
- Extend default value collection (3a5ee757c)
- Make `setCurrentVersion()` easier to understand (96a31b538)
- Expand safeGetAttrs() to return arrays of the names of missing or ill-valued (NaN, wrong data type) attributes (da58af2ba)
- Add sheet initialization function (96999774d)
- **Miscellaneous**
- Bump version number (62ed327a1)
- Migration function for latest version (ffe30ca58)
- Infos on the latest version/changes (212520e6)
- Remove dead code obsoleted in v20210413 (around 0360932d780d7ac147149d36183b6cd2d8f3a0a1) (bf593f927)
=> [Das_Schwarze_Auge_4-1] Bug Fixes and Future-Proofing Attribute Initialization

The Troubleshooters/TheTroubleshooters.css, The Troubleshooters/TheTroubleshooters.html, The Troubleshooters/translation.json
Moved images to GitHub
Bugfixing skill rolls
=> [The Troubleshooters] - Bugfix

Official Savage Worlds/SavageWorldsCharSheet.css, Official Savage Worlds/SavageWorldsCharSheet.html, Official Savage Worlds/sheet.json, Official Savage Worlds/translation.json
Minor enhancements to allow users to use a custom logo and custom background for the sheet.
Also provides a roll20 attribute for remaining wounds for people who want to show health decreasing (on a token) instead of wounds increasing.
=> Official Savage Worlds v1.00.29 New Features

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Making sheet:opened event async because getAttr somehow not working
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.4.1 Bugfix - sheet:opened async

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* changing sheet:opened to working sync version again (async version prevents update of token image)
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.4.2 Bugfix - sheet:opened working sync

The One Ring 2e/release-notes.md, The One Ring 2e/sheet.css, The One Ring 2e/sheet.html, The One Ring 2e/translation.json
- bonus modifier for useful items
- whisper mode for rolls
=> [The One Ring 2e] - 3.04.00 - added whisper mode and bonus modifier for useful items

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] complex forms default to Software-Skill

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] add missing method for char name correction

approved.yaml
=> change Shadowrun Sixth World name and mark as publisher

Kult Divinity Lost/KULT Divinity Lost.css, Kult Divinity Lost/KULT Divinity Lost.html, Kult Divinity Lost/translation.json
Added gm roll buttons for disadvantages.
Added toggle for modifier popups
Added a new roll disadvantage button to send rolls to the GM.
Added a checkbox to toggle displaying the modifier popup.
=> Kult: Divinity Lost - New feature - Added new buttons

ShadowbaneInquisition/Shadowbane.html
fix a fate point being removed for no reason
=> [Shadowbane Inquisition] small bug fix

Mork Borg/morkborgsheet.html, Mork Borg/morkborgstyle.css
I've updated the starting Presence value (to set to '0' like the other stats, rather than it being completely absent) and have widened the field for Silver for those PCs who might manage to rack up some wealth.
=> [Mork Borg] updates to Presence and Silver fields

Snice/snice.html
Updated attribute rolls in accordance with the updated ruleset on critical rolls and exploding dice.
=> [Snice] Updated attribute rolls

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
All checks are now displayed in a box.
=> Checks Visual Update - Fallout VNDPNP

HARP/harp.html
Adding the Fate Points field and label
=> HARP - Hand of Fate Update 20221009 

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] split spells and complex forms to avoid side effects

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Fixed error where Gambling was rolled instead of Gunsmith.
=> Bug Fix - Fallout VNDPNP

Thorg/thorg.html
- The name of this game is: Thorg  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Michael Giesendorf _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Thorg _(i.e. Dungeons & Dragons, FATE)_
- fixing movement formular
=> Thorg - small Bugfix

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.css, Shadowrun Sixth World/Shadowrun6thEdition.html, Shadowrun Sixth World/translation.json
New Feature - PC->Matrix->ASDF Roll buttons now include more options to combine them with.  None, Custom, mind attributes and ASDF.
New Feature - NPCs now have updated ASDF roll buttons as well!
New Feature - NPCs now have the newer version of the d6's roll button and the new Extended Tests capability.
=> Shadowrun Sixth World v.62 - 3 New Features (Extended Tests)

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
SQ wasn't being add to the Turn Order when the token was selected.
=> SQ Bug Fix - Fallout VNDPNP

Thorg/thorg.css, Thorg/thorg.html
- The name of this game is: Thorg  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Michael Giesendorf _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Thorg _(i.e. Dungeons & Dragons, FATE)_
- fixing some open rolls to gm rolls only
- new table to note down class exp (Archetypen)
- added weight of gold
- added option to modify attribute bonuses
- added automatic substaction of magical costs and psi costs
=> Thorg - bugfix and new features

ADnD_2E_Revised/html/changelog.html, ADnD_2E_Revised/html/tabs/character-tab/character-info-tab/character-info-tracker-tab.html, ADnD_2E_Revised/html/tabs/monster-tab.html, ADnD_2E_Revised/javascript/version.js
All changes described on the forum: https://app.roll20.net/forum/permalink/11150510/
=> [ADnD 2E Revised] Bugfix: Magic resistance calculations

The Troubleshooters/TheTroubleshooters.css, The Troubleshooters/TheTroubleshooters.html
Feature: New dice
Bugfix: NPC attack rolls not working
Bugfix: Increase initial storypoints to 4
=> [The Troubleshooters] Bugfix & Feature

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
=> SQ Small Fix - Fallout VNDPNP

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Fixed a number conversion error
* Fixed some css issues
* Added new expansions
* Added missing changelog from previous version to README
* Improved depiction of regeneration rolls a little
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.4.3 Bugfix - Number conversion error & new expansions

Knight/knight.html, Knight/pug/js/_functionsWeapons.js, Knight/pug/js/knight.js, Knight/pug/js/rolls/pj/simple.js
=> [Knight] Bugfix Pilotage / Reaction

Wyrd/sheet.json, Wyrd/wyrd.html
Atualização de Macro das jogadas de acordo com o playtest atual.
=> [WYRD] Atualização de Macro (bugfix/macro's update)

Ironsworn-Starforged/Ironsworn-starforged.css, Ironsworn-Starforged/src/app/common/stylus/dark-mode.styl, Ironsworn-Starforged/src/app/common/stylus/light-mode.styl, Ironsworn-Starforged/src/app/components/assets/assets.styl, Ironsworn-Starforged/src/app/components/connections/connections.styl
There was a minor issue where the text for darkmode was using a static value designed for light mode. Removed them and implemented the styles in the main mode sheets.
=> [Starforged] Styling fixes 

Cthulhu Eternal/sheet.json
The original sheet submission was coded to work with Legacy Sanitization but this was not recorded in the sheet.json. Accordingly, the currently checked-in version doesn't render properly.
This update adds the line: "legacy": true to the sheet.json for the Cthulhu Eternal sheet
=> Cthulhu Eternal: Update sheet.json to force Legacy Sanitization

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.css, ChroniquesOublieesContemporain/coc.html, ChroniquesOublieesContemporain/sheet.json
- Cosmetic changes to the dropdown list to compensate for the optgroup issue in Roll20
- Cosmetic changes to the Add/Modify/Done buttons in repeatable sections
- Added a release notes section to the configuration tab
=> Chroniques Oubliées Contemporain V3.13.0

Court Of Blades/CourtOfBlades.css, Court Of Blades/CourtOfBlades.html
- Repointed images to Roll20 repo
- Reduced tooltip visibility time
=> Court Of Blades: v1.0.2 changed image links to use Roll20 repo

Star Wars Saga Edition/StarWarsSagaEdition.html
=> [Star Wars Saga Edition] Fix NPC Grapple and dark_side_points titles

HARP/harp.css, HARP/harp.html
Adding minimalized NPC functionality to the sheet
=> HARP NPC update 20221027

The One Ring 2e/sheet.css, The One Ring 2e/sheet.html, The One Ring 2e/sheet.json, The One Ring 2e/translation.json
=> [The One Ring 2e] - 03-05-00 - added daunted modifier

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] add edge reroll via click on successes

TheWitcher/witchersheet.html
=> [TheWitcher] fix shield bash

approved.yaml
=> Tormenta GOTY - Correct approved.yaml 

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Health Box was reorganized to include AP. FTG and NV were removed. CND was removed.
=> Health Box Rework - Fallout VND

The One Ring 2e/sheet.html, The One Ring 2e/sheet.json, The One Ring 2e/translation.json
=> [The One Ring 2e] 03.05.01 - translation fixes

Shadowrun5th/Shadowrun5th.css
=> [Shadowrun5thA] fix reroll for 0 successes

Thorg/thorg.html
- Bug: some variables were stored as strings on roll20 instead of integers (input type="number"), which lead to some incorrect calculations
- Bugfix: included additional parsing of variables for type integer some sheetworkers
- fixed som typos
=> Thorg - Bugfixe

T2K 4e/twilight-2k-4e.css, T2K 4e/twilight-2k-4e.html
The following updates have been made to the character sheet HTML and CSS
- updated character sheet to add new tab for NPC/Allies
- updated Load Carrier specialty trait bonus to correct amount
=> T2K 4e - added NPC/Allies tab and fixed Load Carrier specialty bonus

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/sheet.json, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* LE, KE, AE section has been reworked and simplified (pain levels visible via hover on max LE or in the headerbar on LE)
* Advanced roll dialog (3d20) has now a dropdown for default difficulties
* Advanced roll dialog for regeneration now available, including all common modifiers
* Confirmation roll looks now slightly better
* The compendium data should now include hitzones. Those can be rolled on more easily with new roll buttons.
* Spell and liturgies can now include QS/QL in their roll formula. Spells with roll formulas show the roll in the chat card (can be disabled via the options)
* Ranged combat roll template has now the right botch table attached
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.0 Regeneration section rework (New Feature/Bugfix)

D&D_3-5/charsheet_3-5.html
- [*] The pull request title clearly contains the name of the sheet I am editing.
- [*] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [*] The pull request makes changes to files in only one sub-folder.
- [*] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)
Autocalculation of the filed total skill points
=> [D&D 3.5] New feature: autocalculation of the filed total skill points

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - PC Judge Intentions wasn't updating on Willpower changes.
=> Shadowrun Sixth World v.64 - 1 Bugfix

CWOD-W20/W20.css
- The name of this game is: <W20>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <White Wolf> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <World of Darkness> _(i.e. Dungeons & Dragons, FATE)_
The current font was rather difficult to read and created obstacles for people with visual impairments as well as Dyslexia. So I proposed changing it to Linik Sans because it's simple, visually consistent, and clear. My hope is to ease the burden that members of our community face when having to use this character sheet for tracking information.
=> Font Change W20.css

ShadowbaneInquisition/Shadowbane.css, ShadowbaneInquisition/Shadowbane.html
fixed maximal and forcefield not working as intended
=> [Shadowbane Inquisition] bugfixes

The Troubleshooters/TheTroubleshooters.css
=> [The Troubleshooters] Bugfix

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Fixes a wrong attribute label in hitzone calculations
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.2 Hitzone Bugfix

Anima-Beyond-Fantasy/A-BF.html
=> [Anima Beyond Fantasy] Fix Combat Aura

Chronica Feudalis/feudalis-sheet.html, Chronica Feudalis/feudalis-styles.css
Bugfix images not working - change relative urls to absolute
=> Chronica Feudalis Sheet - Bugfix images urls

DnD_5e/sheet.json
=> [D&D 5e Community] Update sheet.json to correct the wiki address

TheWitcher/witchersheet.html
=> [TheWitcher] html cleanup

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] html cleanup

Trinity_Continuum_2ed/TC2e.html
=> Trinity_Continuum_2ed - CS Menu fixed

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] new nightly: weapon stats without ammo

ShadowbaneInquisition/Shadowbane.css
fixed darkmode by adding !importants tags everywhere
=> [Shadowbane Inquisition] dark mode fix. again

WFRP4CharSheet/WFRP4Charsheet.css, WFRP4CharSheet/WFRP4Charsheet.html
Update CSS for Dark Mode compatibility.
=> [WFRP4CharSheet] Dark Mode Fix

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
-Level information will be moved to Character Information. -Skills page was combined into Prime.
-Perks page was moved to Inventory.
-Formulas will no longer be displayed on the Character Sheet. -For SPECIAL, only Base will be calculated into every stat. -Because of this change, Total will now be used for SPECIAL checks so you can now put in your bonuses and penalties into +/- without affecting the other stats.
=> Prime and Inventory Page Rework - Fallout V&D

Talessya/Talessya.css, Talessya/Talessya.html, Talessya/sheet.json
Added the ability to create NPCs with a checkbox
=> Talessya  v1.3. New Feature Allow blank NPCs

Fallout-Vaults-and-Deathclaws/Fallout-VnV.css, Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
A small hotfix to adjust the spacing for Secondary Stats, Skills, and the Tabs in the CSS.
=> Prime Page Hotfix - Fallout V&D

Knight/knight.html, Knight/pug/html/tab/armure.html, Knight/pug/html/tab/subCombat/armure.html, Knight/pug/js/library.js, Knight/pug/js/rolls/pj/ranger.js
=> [Knight] Fix Ranger's Vision

Terminator RPG/Ter.html
Updated Tech Manual to Tech Mechanical as it should be
=> Terminator RPG | Updated Tech button

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] add location to contacts

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- some minor sheet worker clean up.
=> [Warhammer 4e Character Sheet] Minor fixes

Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] import mag/res when present

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
=> Vehicles Page Update - Fallout V&D

BESM4eExtras/BESM4eExtras.css, BESM4eExtras/BESM4eExtras.html
Version 1.8.8
* Deprecated skill picker UI for simpler select driven menu for selecting skills.  Existing skills will be preserved, newly created skills will use the select driven menu.
=> [BESM4eExtras] v1.8.8 Skill UI Update

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.css, Shadowrun Sixth World/Shadowrun6thEdition.html, Shadowrun Sixth World/translation.json
Update PC -> Magic -> Meta Tradition Hermeticism now displays as "Hermeticism (Logic)" and Shamanism now displays as "Shamanism (Charisma)" for clarity
Bugfix NPC -> Vehicles - fixed vehicle/drone default actions
New Feature - added alternate melee/ranged roll buttons on npc sheets.  If there's no dicepool set the alternate button prompts for skill and attribute values.
New Feature - PC sheet Weapon Mods now allows JSON imports via Notes field.
=> Shadowrun Sixth World v.67 - 2 new features, 1 bugfix, 1 update

Pokeymanz/Pokeymanz.html
In the last update, we added a bonus value that could be set inside the sheet for the creature rolls, but ended mistakenly excluding the query for bonus value that was also useful for quick setting and variables. This quick update solves the problem.
- The name of this game is: Pokeymanz  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Chronicle Delusionist _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Pokeymanz _(i.e. Dungeons & Dragons, FATE)_
In the last update, we added a bonus value that could be set inside the sheet for the creature rolls, but ended mistakenly excluding the query for bonus value that was also useful for quick setting and variables. This quick update solves the problem.
=> Pokeymanz Sheet - Minor bugfix

Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html
- Fixed new qualities causing error until weapon reselected.
- Fixed Miscast roll issue
=> [Warhammer 4e Character Sheet] v1.65a fixes

Cyberrats/Cyberrats.css
Moved the link to paper-bg-dark to roll20's github.
=> [Cyberrats] Move image to roll20's Github

Das_Schwarze_Auge_Ilaris/ilaris_roll20.html, Das_Schwarze_Auge_Ilaris/translation.json
- fixed another translation key bug
- added a visual toggle for a larger optional field
=> [Das_Schwarze_Auge_Ilaris] [Translation + graphics] 

Official Savage Worlds/SavageWorldsCharSheet.css, Official Savage Worlds/SavageWorldsCharSheet.html, Official Savage Worlds/sheet.json, Official Savage Worlds/translation.json
Bug Fix Release. Fixed:
1. Spellcasting Weapon rolls with RoFs higher than 1 using an Unskilled die roll for all rolls except the first
2. Added support for the Survival to be Spirit-based (instead of Smarts) for Druids in Pathfinder for Savage Worlds
3. Fixed a display issue on Firefox when using Alphanumeric displays for Traits.
=> Official Savage Worlds v 1.00.30 (Bug Fixes)

Star Wars Saga Edition/StarWarsSagaEdition.css
Set the colour for skill notes so that they appear when in dark mode and light mode.
=> [Star Wars Saga Edition] Bugfix for skill notes in darkmode not displating

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> Shadowrun5thA add defense options

TheWitcher/witchersheet.css
=> [TheWitcher] fix darkmode text color

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add background info to npc sheet

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] react buttons

D&D_3-5/charsheet_3-5.css
FIX css in alternatig ronw in roll template
=> [D&D 3.5] FIX css in alternatig ronw in roll template

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Karma and Eyes were removed. Vice and Virtue boxes were added.
=> Vice & Virtue - Fallout V&D

GURPS/gurps.html
- BUGFIX: Added a quick fix to the default values when adding a new language.
=> GURP 2.9.2.1

TheWitcher/witchersheet.html
=> [TheWitcher] set start hp to 1 to fix common confusion

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - Bugfix - PC -> Modifications - changing astral_initiative_dice_mod was doing strange things to the astral initiative dice.  This has been fixed but if your character ended up with a messed up astral_initiative_dice amount look in "Attributes & Abilities" for "astral_initiative_dice" and change it to the correct ammount.
=> Shadowrun Sixth World v.68 - 1 bugfix

TheWitcher/witchersheet.html
=> [TheWitcher] additional mods can now be prefixed with +

TheWitcher/translation.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> The witcher new npc sheet improvements

Das_Schwarze_Auge_Ilaris/ilaris_roll20.css, Das_Schwarze_Auge_Ilaris/ilaris_roll20.html
Using the recommended roll20 version of tabs
- using the version of tab recommended by roll20, sicne straight css tabs do not seem to work.
=> [Das_Schwarze_Auge_Ilaris] [Graphical Fix] Changed to recommended roll20 tabs

ADnD_2E_Revised/html/changelog.html, ADnD_2E_Revised/javascript/version.js
Updated change log and version
=> [ADnD_2E_Revised] Bugfix/Updated sheet version and change log

TheWitcher/witchersheet.html
=> [TheWitcher] fix bonus_mod error when not applied

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Fixed drag and drop QSR Combat spells
Added Sprite drag and drop
Fixed Sprite sheet matrix_max
Added Complex Forms drag and drop
=> Shadowrun Sixth World v.68 - Bugfix for QSR Combat Spell drag and drop + misc

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Added compendium links to new expansions
* Minor bugfixes
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.3 New Feature/Minor Bugfix - Add new expansions

Brigandyne-V2/ReadMe.md, Brigandyne-V2/brigandyne-v2.css, Brigandyne-V2/brigandyne-v2.html, Brigandyne-V2/sheet.json
- The name of this game is: < Brigandyne  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < James Tornade.   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Brigandyne    > _(i.e. Dungeons & Dragons, FATE)_
- [ x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets# …
=> Brigandyne-V2  : Update : V1.01- New feature

D&D_3-5/charsheet_3-5.css, D&D_3-5/charsheet_3-5.html, D&D_3-5/translation.json
Add link to thread in forum
Fix css for closable section
=> [D&D 3.5] FIX minor css 

Pokerole_v2/Pokerole.css, Pokerole_v2/Pokerole.html
Fixed field labels, reducing font size to eliminate text overlapping.
Added a second popup to the damage buttons, bonus damage dice.
=> [Pokerole_v2] CSS Style fix and new damage prompt (bugfix, new feature)

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html, Shadowrun Sixth World/translation.json
Add Contacts drag and drop capability, you can now drag ANY NPC from the compendium and their name and description will be added to your contacts, also loyalty, connections and favors if the NPC has those attributes (currently none do)
NPCs->Powers text added for all NPCs not just Awakened
NPCs->Weaknesses text added for all NPCs
NPCs->Spirits added Weaknesses to the Spirts sheet auto-generation code.
Bugfix PCs->Armor didn't update DR when deleting armor entries
=> Shadowrun Sixth World v.69 - 1 Bugfix, 4 new features

Court Of Blades/CourtOfBlades.css, Court Of Blades/CourtOfBlades.html, Court Of Blades/translation.json
- Corrected typo in "Factions of Ilrein" (thanks PhDniX)
- Fixed the clocks in the (three-wide) panel on the GM Turn page so that they are properly left aligned
- Slightly increased the line height of the Playbook/House title so that the tail of the 'y' in 'The Eye' is no longer cut off
- Corrected an issue where the auto-resizing note fields didn't have a background
=> Court of blades: fixed typo, minor formatting fixes

Shadowrun5thEdition/Shadowrun5thEdition.css, Shadowrun5thEdition/Shadowrun5thEdition.html, Shadowrun5thEdition/sheet.json
I've been meaning to work on this sheet for a while, mainly cleaning it up and fixing a few quirks (maybe adding a spirit sheet or automating spirit/sprite creating on the fly, like Chummer5a does), to make that possible I realized pretty quickly things would be a lot easier with the new(-ish) paradigm, so I added a bunch of `.charsheet` and removed some `sheet-` from the css and voilà!
=> [Shadowrun5thEdition] Porting: Switch to new "Character Sheet Enhancement" style

Fifth Season/Fifth Season.css, Fifth Season/translation.json
Updated upstream & Stashed changes? I have no idea what happened, but I went through the code and got everything working again.
=> Fifth Season - Fixed Upload Errors

D&D_3-5/sheet.json
=> [D&D 3.5] Add printable option

TheWitcher/witchersheet.html
=> [TheWitcher] move profession settings below weapon template

Earthdawn (FASA Official)/Earthdawn.css, Earthdawn (FASA Official)/Earthdawn.html
=> Earthdawn (by FASA) v3.01 - Big Fixes

ShadowbaneInquisition/Shadowbane.html
=> [Shadowbane Inquisition] Added WP option to dodge

Das_Schwarze_Auge_Ilaris/ilaris_roll20.css, Das_Schwarze_Auge_Ilaris/ilaris_roll20.html
- somehow somewhere roll20 is overwriting my grid layout for attributes and ranged combat modifiers.
- Hopefully this fixes it ?
=> [Das_Schwarze_Auge_Ilaris][Bugfix] fixing layout and ranged combat

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.html, ChroniquesOubliees/sheet.json
* Added munitions in the gear tab
* Added a field to note the effect of wearing a weapon
=> Chroniques Oubliees Fantasy: version 5.02 (new features)

TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add crit location button

Into the Odd/into-the-odd-style.css, Into the Odd/sheet.json
Basically removed "sheet-" prefix nearly everywhere, and it tested ok in sandbox
=> [Into the Odd] update to migrate away from legacy sanitization

BESM4eExtras/BESM4eExtras.html
v1.8.10
* Added support for Unique Attribute cost pre level. Was previously hardcoded to 0 without any method to change.
* When modifying Unique Attribute, the attribute cost per level or attribute level will update attribute cost.
v1.8.9
* Defect categories Serious and Greater were switched to reflect true Defect costs per the Core Rule Book.
* Upgrade to 1.8.9 routine iterates through each attribute group to apply the correct cost to each defect respective to the defect rank in the group and recalculates the total group cost, and overall character cost.
=> [BESM4eExtras] v1.8.10 - Multiple fixes

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> Shadowrun5th a get rid of notes box

Cyberrats/Cyberrats.html
Now you can enter optional dice changes before a roll.
=> [Cyberrats] [New Feature] Update cyberrats to have dice modifiers for attribute rolls

Monster of the Week Official/MotWCSS.css
=> Monster of the Week - Bug Fix - Font URL

Monster of the Week Official/MotWCSS.css
=> Monster of the Week - Bugfix - Resolving Typo in CSS

Shadowrun5th/Shadowrun5th.css, Shadowrun5th/Shadowrun5th.html
=> [Shadowrun5thA] fix some technomancer css issues

Das_Schwarze_Auge_Ilaris/ilaris_roll20.css, Das_Schwarze_Auge_Ilaris/ilaris_roll20.html, Das_Schwarze_Auge_Ilaris/translation.json
roll20 is overwriting my style even when i put it directly into the div. maybe using charsheet helps? makes it impossible to test locally again, so likely its what they want...
=> [Das_Schwarze_Auge_Ilaris] [Graphic fix]

BESM4eExtras/BESM4eExtras.html
v1.8.11
* Added support to define Unique Defect category as per the core rulebook.
* Fixed doUpgrade(), will no longer repeat upgrades when build number is greater than 9.
=> [BESM4eExtras] v1.8.11 multiple fixes

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> [SalvageUnion] update sheet for alpha core book

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.css, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - PC Condition Monitor boxes broke if the maximum value was below 8.  Changed the minimum to 6 which is 0 body with Neoteny so should be unattainable.
=> Shadowrun Sixth World v.70 - 1 Bugfix

Das_Schwarze_Auge_Ilaris/ilaris_roll20.css, Das_Schwarze_Auge_Ilaris/ilaris_roll20.html
maybe this finally lets me put my css in the right place?
It's so fun to work with all the invisible stuff getting added and removed from my html ....
=> [Das_Schwarze_Auge_Ilaris] [Graphics-Bug] Fixing css not applied

D&D_3-5/charsheet_3-5.html
=> [D&D 3.5] Showed correct label

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> [SalvageUnion] add crew and upgrade progress to crawler

Das_Schwarze_Auge_Ilaris/ilaris_roll20.css
=> [Das_Schwarze_Auge_ilaris] Ilaris layout fix

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.html, ChroniquesOublieesContemporain/sheet.json
- The name of this game is: Chroniques Oubliées Contemporain
- The publisher of this game is: Black Book Editions
- The name of this game system/family is: d20/OGL3.5
- Added optional counters 2 & 3 with functionality to create/update attributes named cptr_xxx where xxx is the short/abreviated name of the counters
=> ChroniquesOublieesContemporain Version 3.14.0

Earthdawn (FASA Official)/Earthdawn.css, Earthdawn (FASA Official)/Earthdawn.html
- [X ] This sheet has been made on behalf of, or by, the game's publisher.
=> Earthdawn 4th Edition (FASA OFficial) v3.02

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
A skill was calculating from the Total and not the Base.
=> Fallout V&D - Bug Fix

AvatarLegendsMagpie/avatarlegends.html
Button Right Fixed
- The name of this game is: <Avatar Legends>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Magpie Games> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Avatar Legends> _(i.e. Dungeons & Dragons, FATE)_
=> [Avatar Legends By Magpie] - Button Right Fixed

Castles&Crusades/C&C.html, Castles&Crusades/CHANGELOG.md
**2023-02-14 ** v.2.1 Paul V
Bug fixes - fixed weapon buttons for weapons 3,4,5 and main AC visible to macros
**2023-02-14 ** v.2.1 Paul V
Bug fixes - fixed weapon buttons for weapons 3,4,5 and main AC visible to macros
=> [Castles&Crusades] Bug fixes

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> [SalvageUnion] add weapon heat automation

Das_Schwarze_Auge_Ilaris/ilaris_roll20.css, Das_Schwarze_Auge_Ilaris/ilaris_roll20.html
=> [Das_schwarze_Auge_Ilaris] CSS improvements

TheWitcher/sheet.json, TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> The witcher more details instead of pseudo arrows

YellowKing/YellowKing.html
- Fixed wrong and missing data-i18n in some terms
=> Yellow King - Minor fixes on translatable tags

Magical-Kitties/sheet.json
Adding myself to the `authors` section of the _Magical Kitties Save the Day!_ sheet.json.
@Anduh signed off on adding me as an author in a PM on the Roll20 site, but tagging as well just to be open about the addition.
Also tagging the other author @apsalari, though I never heard back about #11420, so I'm not sure whether they're checking Github at all.
=> Magical Kitties Save the Day! sheet.json updates

ChroniquesOubliees/ReadMe.md, ChroniquesOubliees/co.html
Support parsing of JSON statblocks for NPCs, as produced by the DRS site for Chronique Oubliees, https://www.co-drs.org.
=> Chroniques Oubliees: support parsing of JSON statblocks from co-drs.org

Trinity_Continuum_2ed/TC2e.css, Trinity_Continuum_2ed/TC2e.html
=> Trinity-Continuum_2ed - Bugfix

D&D_OED/DnD_OED.css, D&D_OED/DnD_OED.html, D&D_OED/sheet.json
Update to new CSV environment:
- Remove the many "sheet-" prefixes in CSS
- Fix a few bugs that uncovered
- Remove commented-out background styling
=> D&D_OED: Update to new CSE environment

PokemonTabletopUnited/ptu.css
Added a workaround to hide duplicated repitems of the moves repeating section.
=> PokemonTabletopUnited - Bugfix

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.css, Shadowrun Sixth World/Shadowrun6thEdition.html, Shadowrun Sixth World/translation.json
Bugfix - PC Initiatives - Fixed a condition where if a dice mod is set and then the initiative base is changed it keeps adding the dice mod repeatedly.
=> Shadowrun Sixth World v.73 - Bugfix to initiative mods

City Of Mist Official/city-of-mist.html
Add some missing translation strings
=> [City of Mist Official] Add Translation Strings

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> [SalvageUnion] put system and module settings in settings details

Shadowrun5th/Shadowrun5th.css
=> [Shadowrun5th Advanced] fix autopilot missing buttons

ICON RPG [MassifPress]/sheet.json
- Fixed 'tipee' to 'tipeee' so that the donation link actually appears correctly in sheet selection
=> [ICON] Typo fix (Update sheet.json)

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Fix for matrix device stats on drag and drop for NPCs
Fix for Sprite drag and drop issue
NPCs->Grunts added a stun monitor and flag to display it (it is hidden by default)
=> Shadowrun Sixth World v.74 - 1 new feature, 2 bugfixes

TheWitcher/witchersheet.html
=> [TheWitcher] fix shield bash quick button

they_came_from/they_came_from.html
Updated image sources to reference github instead of personal roll20 image library.
=> Update image urls to github source

RunequestGQS/RunequestGQS.css, RunequestGQS/RunequestGQS.html
=> [RuneQuest:Glorantha] Tided up roll template display. 

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.css, Shadowrun Sixth World/Shadowrun6thEdition.html, Shadowrun Sixth World/translation.json
New Feature - PC-Magic-Conjuring Added Astral Reputation and added AsRep to Summon Spirit button output
New Feature - Added Heat, Reputation and AsRep to the Social Pane
Added Drag and Drop support for Gear-Ammunition-Grenades Gear-Ammunition-Rockets to place them in the Arms-Grenades section instead of Gear
Added Grenade dicepool calculations
=> Shadowrun Sixth World v.75 - 4 new features

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.css, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/translation.json
* Compendium data has been updated with new spell extensions available through the new book "Grimorum Cantiones". The sheet can now import 5 extensions instead of 3
* Support for Patron Category
* Support for Demonmark Category
* Support for Magical Sign Category
* Support for Pact Special Abilities
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.4 - New Feature - Grimorum Cantiones Update

Star Wars Saga Edition/StarWarsSagaEdition.html
Removed the condition tracker penalties when helpless 
https://swse.fandom.com/wiki/Conditions#The_Condition_Track
https://app.roll20.net/forum/post/11349303/star-wars-saga-edition-character-sheet-helpless-step-on-condition-track-should-not-have-penalties/?pageforid=11354724#post-11354724
=> [Star Wars Saga Edition] Bugfix Change helpless condition to remove all penalties from condition tack

Iron Kingdoms RPG/IKPRG.css
Copied as many images as I could from their existing links into a new images folder in this repository. Some images were re-sized and renamed as part of this process. A couple images could not be found anymore, even on the wayback machine. 
Minor tweaks to the way some of the action headers render for consistency across different actions and to add text clarity with the background images.
=> Iron Kingdoms RPG - Bugfix - Move/Replace external images to roll20 repo, CSS tweaks

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - Fixed Spirit Astral initiative dice had been reduced to mere metahumanity levels, they've been returned to their previous exceptionalism.
=> Shadowrun Sixth World v.76 - 1 bug fix

ADnD_2E_Revised/html/components/datalists.html
Described in the title of the PR
=> [ADnD_2E_Revised] Bugfix/ Updated PSP progression to use ned psionic only fields for Con, Int, Wis

Forge/Forge.html
Stat name changes. Dex adds to Def, IQ adds to Mana. Added more detail to notes section.
=> Forge Stat name changes. Dex adds to Def, IQ adds to Mana

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> Salvage union importer

City Of Mist Official/city-of-mist.html
Add miss translation strings and some adjusts on HTML
=> [City of Mist Official] Minor Adjusts on Translation Strings

EnGarde/EnGarde.html, EnGarde/ReadMe.md
=> [En Garde]  Removed poltroon plunder fixed field ops plunder

Tormenta20 - Jogo do Ano/tormenta20.html
Fixed Menace Skills Calculation;
Fixed Menace Attacks;
=> [Tormenta20 - Jogo do Ano]Fixing Menace Character Sheet Bugs

D&D_3-5/charsheet_3-5.html, D&D_3-5/translation.json
=> [D&D 3.5] Change Action tab description

Forge/Forge.html
Damage system updated, small typo fixes.
=> Forge, updated the dmg system. Small typo fixes.

EnGarde/EnGarde.css, EnGarde/EnGarde.html
=> [En Garde] Fixed display in Firefox

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/README.MD, Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Ranged weapons show now the final roll value including the modifiers
=> [Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.5 - New Feature - Ranged attack roll preview

Star Wars Saga Edition/StarWarsSagaEdition.html
Added a hideable section for notes on speed, such as for alternate movement forms.
=> [Star Wars Saga Edition] Added notes for speed

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - (?) Trying to fix some dicepool bugs on NPC and Vehicle sheets tied to grunt groups.
Bugfix - Vehicle physical and matrix condition monitors weren't updating right on drag and drop
=> Shadowrun Sixth World v.77

Level Up - Advanced 5th Edition/levelup.html
=> [Level Up - Advanced 5th Edition] - Macro Wording Updates

EnGarde/EnGarde.css, EnGarde/EnGarde.html
=> [En Garde] More Firefox display fixes and reset weekly allocation Descriptions

DeusVault/DeusVault.css, DeusVault/DeusVault.html, DeusVault/sheet.json
Change legacy to false in the sheet.json.
Update sheet to v0.6 of the rules version.
- Merge masteries and talents
- New skill check formula
=> [DeusVault] Update sheet to v0.6

Fantasy Age/Fantasy AGE.html
Change made on behalf of Green Ronin Publishing
=> [Fantasy Age] Hotfix

Castle Falkenstein/falkenstein.html, Castle Falkenstein/sheet.json
Added sheet workers to calculate money and current wounds.
=> [Castle Falkenstein] Add sheet workers

Star Wars Saga Edition/StarWarsSagaEdition.html
=> [Star Wars Saga Edition] Bugfixes

DeusVault/DeusVault.css, DeusVault/DeusVault.html
Skills of T1 are now rolled with disadvantage (2d100kl1) and T3 with advantage (2d100kh1).
Add "advanced" roll btn (can be shown or hidden in options section) to roll 'n' dice with advantage or disadvantage
=> [DeusVault] Roll skills with advantage or disadvantage

Star Wars Saga Edition/sheet.json
=> [Star Wars Saga Edition] Added print functionality to sheet.json

Splittermond/Sheet.html
-  I added a method to parse any spell copied from the rulebook to directly add it to the character sheet
=> [Splittermond] Spell Parser implemented

Broken Compass/README.md, Broken Compass/brokencompass.css, Broken Compass/brokencompass.html
=> [Broken Compass] fix path for assets

Fabula Ultima/FabulaUltima.html, Fabula Ultima/sheet.json
Names in the sheet.json have been updated on the request of the devs.
CSS was not made in Legacy, so sheet.json have been updated to fix the error
Template has been added on Initiative roll
=> Fabula Ultima bugfix (sheet.json update to fix CSS)

Tormenta20 - Jogo do Ano/sheet.json, Tormenta20 - Jogo do Ano/tormenta20.html
Fixed the Domain Default Setting in Tormenta20 Character Sheet
Removed the Extra Space in Default Setting variable.
=> [Tormenta20 - Jogo do Ano] Bug Fixing - Extra Space in variable in Default Settings

Tesoro-y-Gloria-2E/tesoroygloria2e.css, Tesoro-y-Gloria-2E/tesoroygloria2e.html
Fix a couple of issues regarding the CSS styles of some elements of the sheet.
=> Fix small CSS issues of Tesoro y Gloria 2 Edition

Unisystem-Buffy or Angel/Buffy_or_Angel.css
=> changed the font. The old one did not load

Unisystem-Buffy or Angel/Buffy_or_Angel.html
Wrong tables, calculations and other issues.
=> Fixed a lot of errors

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.css, ChroniquesGalactiques/cog.html, ChroniquesGalactiques/sheet.json
- Added logic to import starship and mechas statblocks from the manual's PDF
- Correction to include the armor malus to the INIT attribute, DEX and ranged attacks tests
- Added details of hit points per level on PC sheet configuration tab
=> ChroniquesGalactiques Version 4.1.0

Basic_Roleplaying/sheet.json
Conversion to CSE, and allow the sheet to work without Legacy Sanitization Opt-in.
- [ X ] The pull request title clearly contains the name of the sheet I am editing.
- [ X ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
=> Basic Roleplaying System JSON Conversion to CSE

Basic_Roleplaying/Basic_Roleplaying.html
Conversion to CSE, and allow the sheet to work without Legacy Sanitization Opt-in.
- [ X ] The pull request title clearly contains the name of the sheet I am editing.
- [ X ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
=> Basic Roleplaying System HTML Conversion to CSE

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> Salvage union import multi ep items

DeusVault/DeusVault.css, DeusVault/DeusVault.html
Merge masteries and attacks (See [rules](https://github.com/gauthen/JDR/blob/main/DeusVault/Rules.pdf) for more details)
=> [DeusVault] Update sheet : Merge masteries and attacks

GURPS/gurps.html
Bugfix: Stress and Derangement wasn't being divided by 2, rounded up.
=> GURPS 2.9.7

Terminator RPG/Ter.html
When you select a Positive Trait Natural Aptitude ____ which will add 1 to Max (Stat). corrected strategist.
Working on rolls and re-rolls next
=> Added Natural Aptitude Mod

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> [SalvageUnion] import denizens

Duels of Dreams - DODAS/DODAS.css, Duels of Dreams - DODAS/DODAS.html
- [ x] This sheet has been made on behalf of, or by, the game's publisher.
1. Attribute table: Added icons and colored numbers for better …
=> Early April 2023 DODAS sheet update, math update and beautifying

forgedInDungeon/forgedInDungeon.css, forgedInDungeon/forgedInDungeon.html, forgedInDungeon/sheet.json
- The name of this game is: < Forged In Dungeon >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Forged In The Dice > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Forged In Dungeon, FID > _(i.e. Dungeons & Dragons, FATE)_
1. update sheet.json : delete legacy row
2. changes all image path
=> [Forged In Dungeon] sheet updates

Hyperborea/hyperborea.html
This change improves the "number spells memorized" column by changing it's type from string to number.
=> [Hyperborea] Change num spell col to number.

HarnMaster3/harnsheet.html, HarnMaster3/harnstyle.css
Fix 2 minor styling issues in dark mode (illegible text in notes field and horse speed select) and clarified riding EML description
=> [Harnmaster3] Styling and description tweaks

ChroniquesGalactiques/ReadMe.md, ChroniquesGalactiques/cog.css, ChroniquesGalactiques/cog.html, ChroniquesGalactiques/sheet.json
- Removed the buggy auto-calculation of hit-points when changing level or CON 
- Added an optional field for Psy Instability (psionics)
- Added a new tab for charsheet version with release notes and a read-only log of data migrations if any
=> ChroniquesGalactiques Version 4.2.0

Edge of the Verse/edgeoftheverse.css, Edge of the Verse/edgeoftheverse.html
- [] This sheet has been made on behalf of, or by, the game's publisher.
=> [Edge of the Verse] Bugfix: fix image urls

alien_rpg/alien_rpg.css, alien_rpg/alien_rpg.html
- Resolved an issue that prevented the hostile name and stage from being edited by the user
- Resolved an issue that prevented the whisper option from being respected
- Resolved an issue that caused hostile ability descriptions to be compacted to the left
- Updated image references to point to image assets in Roll20 repo
=> Alien RPG: Fixes issues reported to sigil, redirects image refs

CWOD-Exalted/EXvWOD.css, CWOD-Exalted/EXvWOD.html
Modified EXvWOD.css to prevent the sheet from running out of room for Backgrounds and Charms. Updated EXvWOD.html to reflect revised essences recovery values.
=> Bugfix & Update to CWOD-Exalted EXvWOD

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> [SalvageUnion] add traits to weapons, rework buttons

TheWitcher/witchersheet.css, TheWitcher/witchersheet.html
=> [TheWitcher] add to chat button to npc

Kids on Brooms Official/kobrooms.html
Updated the kids on brooms character sheet to auto-roll a 1d4 when the character is doing a magic roll
As a player, it was annoying to …
=> kobrooms bugfix - 1d4 is now auto-rolled for magic rolls

Star Wars Saga Edition/StarWarsSagaEdition.html
=> [Star Wars Saga Edition] Adding encumbrance multiplier

Broken Compass/brokencompass.html
=> [Broken Compass] inputs bugfix

SalvageUnion/SalvageUnion.css, SalvageUnion/SalvageUnion.html
=> Salvage union add missing traits fields

ChroniquesOubliees/co.html
Corrected 2 wrong attribute names in the sheet worker.
=> Chroniques Oubliees: bug fix.

SalvageUnion/SalvageUnion.html
=> [SalvageUnion] fix push of normal roll

Earthdawn (FASA Official)/Earthdawn.html
=> Earthdawn Edition 4 FASA Official - V.312

CODEOWNERS
=> Updating Codeowners

Paradigm's RWBY TTRPG V1.0/Paradigm's RWBY TTRPG.html
04/18/2023
Added Barrier as a modifier for Characters.
Added Barrier as a modifier for Characters.
=> Update Paradigm's RWBY TTRPG with New Feature.html

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html
Changed "Last updated" date
Removed a bunch of semicolons from the statBlock template
Changed the wiki URL to a disabled text input
Changed roll templates so that the common properties were grouped together.
Fixed the corners of roll templates so that corners didn't poke out of the rounded borders.
Rounded the corners of the inline rolls and did some slight color changes.
Adjusted the statBlock …
=> [Star Wars Saga Edition] Code cleanup and small visual tweaks

Liminal/liminal.css, Liminal/liminal.html
Set label colours so dark mode doesn't make them hard to read. Fixed an unnecessarily wide label making the sheet scrollable. Added a roll template and styling.
=> Liminal: label colour fixes and new roll template

blade_runner_rpg/bladerunner_rpg.html
=> Blade runner RPG: Fix npcs being dropped without names

Star Wars Saga Edition/StarWarsSagaEdition.html
And I fixed THAT DARN NPC GRAPPLE TEXTHEAD!
=> [Star Wars Saga Edition] Fixed minor spacing issues on sheet

HarnMaster3/harnsheet.html, HarnMaster3/harnstyle.css
N/A
Various layout adjustments for mobile web layout (note: not styling for mobile app, not enough documentation available to do that).
=> [Harnmaster3] Mobile web styling enhancements

forgedInDungeon/forgedInDungeon.css
=> Resolving CSS Issue in Forged In Dungeon

AnimeWasAMistake/AWaM.css, AnimeWasAMistake/AWaM.html
* Add support of Roll20 darkmode.
* Create darkmode CSS styles for each element, including rolltemplate. Several styling refinements.
=> AnimeWasAMistake: darkmode update

forgedInDungeon/sheet.json
1. sheet doesn't changed anything.
2. roll20userid changed as me on sheet.json file.
=> [Forged In Dungeon] edit json

ChroniquesOublieesContemporain/README.md, ChroniquesOublieesContemporain/coc.css, ChroniquesOublieesContemporain/coc.html, ChroniquesOublieesContemporain/sheet.json
- Removed auto-calculation of hit points per level
- Added a Version tab to the PC sheet, with notes et migrations log
- Minor cosmetic enhancements
=> ChroniquesOublieesContemporain Version 3.15.0

CoeursVaillants-2/CoeursVaillants-2.css, CoeursVaillants-2/CoeursVaillants-2.html
* handle darkmode with CSS styling.
* add aggravated input for points de vie.
* add max input for points d’aventure and xp.
* correct macro input for capacites.
* several styling updates.
=> CoeursVaillants2: darkmode update

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - PC/NPC Defense rolls throwing an error for the armor_rating, updated PC sheets to use defense_rating so they match NPC sheets.
=> Shadowrun Sixth World v.80 - 1 Bugfix

Pathfinder Community/pathfinder_community.html
- fixed errant line break inside textarea that was causing extra macro code to be displayed when using the NPC saves rolls.
=> Pathfinder Community Sheet - small bug fix

Reboot The Future/rebootthefuture.html
Fixed skill point calculation - added in change triggers for new skills to the sheetworkers and set the values for these skills.
=> Reboot The Future: bugfix for skill count calculation

Fallout-Vaults-and-Deathclaws/Fallout-VnV.html
Added Computer Science and Engineer for skills to use in the weapons section.
=> Weapon Section Update - Fallout V&D

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/translation.json
Added support for one of the most common house rules in the system
Added a few more words on the sheet to those that will show up as translated
=> [Star Wars Saga Edition] Added Athletics skill house rule

Ordem Paranormal/ordemparanormal.css, Ordem Paranormal/ordemparanormal.html, Ordem Paranormal/sheet.json
- The name of this game is: Ordem Paranormal
- The publisher of this game is: Jambo
- The name of this game system/family is: Ordem Paranormal
Fixing sheet css styling and setting `legacy` flag as `false`.
=> [Bugfix] Fixing sheet CSE - Ordem Paranormal

The Troubleshooters/TheTroubleshooters.html
Replaced lines 214/215 (NPC soak and recovery rolls) with working versions copied from the PC Combat tab.
=> The Troubleshooters - Bugfix - Using correct roll

Ordem Paranormal/ordemparanormal.css, Ordem Paranormal/ordemparanormal.html
- The name of this game is: Ordem Paranormal
- The publisher of this game is: Jambo
- The name of this game system/family is: Ordem Paranormal
Just fixing some css style names that passed without fixing on the last PR
=> [Ordem Paranormal] Bugfix - Sheet styles name fixing

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
Bugfixes
* Energyfactor and other tradition details should now be initialized properly
=> Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.6 - Bugfix (traditions)

RunequestGQS/RunequestGQS.css, RunequestGQS/translation.json
=> [RuneQuest:Glorantha] Missing updated CSS and translation files

Splittermond/Sheet.html
- Fixed the arrows in the new feature
=> [Splittermond] Small CSS fix

RunequestGQS/ReadMe.md, RunequestGQS/RunequestGQS.css, RunequestGQS/RunequestGQS.html, RunequestGQS/translation.json
Scorpion men Thorax hit location roll fix
Centered THP loss header
Added magical damage bonus to missile weapons
=> [RuneQuest:Glorantha] Added magical damage bonus to missile weapons and fixes

Star Wars Saga Edition/README.md, Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/sheet.json
Changed color of checkboxes and radio buttons
Fixed CT so that it synced and displayed on both PC and NPC sheets
Added myself as sheet maintainer
Updated readme to reflect the status of the sheet
=> [Star Wars Saga Edition] Fixed minor CT and checkbox issues

Shadowrun Sixth World/CHANGELOG.md, Shadowrun Sixth World/Shadowrun6thEdition.html
Bugfix - PC Qualities were always showing up as Negative regardless of the actual type.
Bugfix - PC->Spells Ranges of Touch were showing up as LOS.
=> Shadowrun Sixth World v.80 - 2 Bugfixes

HeroSystem6eHeroic/HeroSystem6eHeroic.html
A Lowshot roll is 2d6+7, with a 19 hitting the feet. This was left out of the case selection.
=> HeroSystem6eHeroic: Bugfix - Lowshot

Beacon by PGG/beacon.html
-Remove underlines
Removing underlines that were breaking some interactions
=> Beacon by PGG: One-line fix for char sheet error

Ordem Paranormal/ordemparanormal.html
- The name of this game is: Ordem Paranormal
- The publisher of this game is: Jâmbo
- The name of this game system/family is: Ordem Paranormal
Adding a missing class to the Sanidade points container
=> [Ordem Paranormal] Bugfix - Adding missing class to Sanidade

Official Savage Worlds/SavageWorldsCharSheet.css
Adding additional fonts to the character sheet CSS file.
=> Official Savage Worlds v1.00.31 Additional Fonts

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html
- Roll template: Added {{subtitle2}} ie Subtitle without quotes.
- Roll template: Added {{free-text-center}} and {{free-text-right}} ie Should allow a little more flexibility for macros.
- Removed an errant extra space that was pushing the last Misc+/- modifier to a new line in the roll template.
=> Forbidden Lands v1.81 small update

RunequestGQS/ReadMe.md, RunequestGQS/RunequestGQS.html
Fixed 2 Headed Dragonsnail Hit Location
=> [RuneQuest:Glorantha] Fixed 2 Headed Dragonsnail Hit Location

Ordem Paranormal - Oficial Jambo Editora/ordemparanormal.html
=> [Ordem Paranormal - Oficial Jambo Editora] Fixing Bug in Attacks Macro

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html, Forbidden_Lands/translation.json
- Fixed a bug where the localized "Roll" button popover could prevent pre-loading the dice pool.
- Fixed a bug with Negative Dice where negative dice would not be included in the roll unless they were the last dice selected in the pool.
- Expanded the Talent and Spell ranks selector up to 6. Should allow more flexibility for homebrew/expansion rules.
- Added repeating rows to Stronghold notes.
- Added custom repeating stockpile items.
- Extended the Talents and Gear column and added a scrollbar to each sub-section to help contain the sheet's layout.
- removed 90% of the sheet's log output.
- added a check for repeating rows to ensure at least one row is always included.
- The publisher of …
=> Forbidden Lands v1.82

Ordem Paranormal - Oficial Jambo Editora/ordemparanormal.css, Ordem Paranormal - Oficial Jambo Editora/ordemparanormal.html
Added Block and Evade Fields 
Fixed a bug with actual PV is being replied in actual PE
Fixed a bug where Origin was been replied in Background field.
=> [Ordem Paranormal - Oficial Jambo Editora] Added Block and Evade Fields, Fixed Bugs where fields are being replied in others.

Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses/dsa5official.html
* Fixes calcualtion of unarmed combat damage bonus
=> Das Schwarze Auge (TDE) 5 OFFICIAL by Ulisses] v1.5.6 - Bugfix (unarmed combat damage bonus)

Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/sheet.json
Reverted changes to second wind variable names to avoid bugs with second wind, size, and equipment weight not working properly
Synchronized CTIgnoreDT between PC and NPC tabs to avoid a bug when the NPC value is checked but the PC value isn't.
Added clarity in the tooltip for Pilot-operated checkbox
Added tags for the vehicle attack formula to clarify what each number is.
Made the Is Droid checkbox unchecked by default.
Made each repeating equipment section Carry box checked and Qty 1 as default
=> [Star Wars Saga Edition] Bug Fixes, minor QoL changes

Castles&Crusades/C&C.css, Castles&Crusades/C&C.html, Castles&Crusades/CHANGELOG.md, Castles&Crusades/sheet.json
**2023-06-05 ** v.2.5 Paul V
Fixed issue with the weapon rolls, they will now correctly add the total mod, if 'modifiers on rolls' is disabled
Fixed issue with stat rolls, they will now correctly add the modifier if 'modifiers on rolls' is disabled
**2023-06-05 ** v.2.5 Paul V
Fixed issue with the weapon rolls, they will now correctly add the total mod, if 'modifiers on rolls' is disabled
Fixed issue with stat rolls, they will now correctly add the modifier if 'modifiers on rolls' is disabled
=> [Castles&Crusades] Bug fix

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html
- Swap imgur images for polyhedral dice to github.
- Further adjustments to try and get the Swedish logo to display properly. It appears this is still a roll20 bug.
=> Forbidden Lands v1.851

ADnD_1E/1ESheet.css, ADnD_1E/1ESheet.html
- A little more help for the roll templates in darkmode.
=> AD&D1e - darkmode roll template update

Low Fantasy Gaming/LFGSheet.css, Low Fantasy Gaming/LFGSheet.html
Fixed dark mode working in the sheet sandbox but not in the repository
Changes / Description
Fixed dark mode working in the sheet sandbox but not in the repository
=> Low Fantasy Gaming - Minor fix to dark mode

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html
- Reputation roll wasn't clearing artifact dice.
=> Forbidden Lands - fix for reputation roll

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/sheet.json
Corrected formulas for vehicle skills, using sheetworkers for some
Added Perception as vehicle skill
Hid pilot-only skills from non-pilots
Added crew quality defaults
Added section for emplacement points
Minor CSS cleanup and fixes
=> [Star Wars Saga Edition] Updated vehicle skills and crew

Star Wars Saga Edition/StarWarsSagaEdition.html
=> [Star Wars Saga Edition] Vehicle skill bugfix

Dark_Heresy/DarkHeresy.html
Removed checkboxes for tracking characteristics advances. They disrupted the sheet's display, and that information can be tracked with the Advancements Taken at the bottom of the sheet.
=> [Dark Heresy] Update DarkHeresy.html

Star Wars Saga Edition/StarWarsSagaEdition.html
=> [Star Wars Saga Edition] Minor Vehicle tab changes

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/translation.json
- Added the Norse Race (Sea of Claws), same attribute as humans with default size average.
- Fixed some rolls not working under certain conditions.
- Fixed some failed roll Talent modifier text not displaying correctly. eg - You may Reverse Dice
=> [Warhammer 4e Character Sheet] v1.65c

A Song of Ice and Fire/SIFRPNew.html
Line 1434: Missing d1 after d6. Which causes to roll d(60+[specialty value]) on Roll20 for the Dedication Specialty of the Will Ability.
=> [SIFRP/Bugfix] Update SIFRPNew.html - Dedication Roll Fix

A Song of Ice and Fire/SIFRPNew.html
Line 1434: Changed "d6d1" to "d6dl" as it should've been. My mistake.
=> [SIFRP/Bugfix] Update SIFRPNew.html - Dedication Roll Fix #2 (Electric Boogaloo) 

Ars_Magica_5th/Ars_Magica_5th.css, Ars_Magica_5th/source/Ars_Magica_5th.scss
- tentative fix for  roll20/roll20-character-sheets#11951
=> [Ars Magica 5th] tentative fix for #11951

D&D_3-5/charsheet_3-5.css, D&D_3-5/charsheet_3-5.html
- Add 5 rows in class section
- Update the thread link
=> [D&D 3.5] add 5 rows in class section

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html
- added attribute column to skills
=> Forbidden Lands - small updates to layout

Ars_Magica_5th/Ars_Magica_5th.css, Ars_Magica_5th/Ars_Magica_5th.html, Ars_Magica_5th/source/Ars_Magica_5th.scss, Ars_Magica_5th/source/helpers/_helpers.scss, Ars_Magica_5th/source/legacy/tabs/1_details.pug
- fix Roll20/roll20-character-sheets#11956
=> [Ars Magica 5th] Fix virtue&flaw type not saving

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html
- renamed action buttons in html and sheetworkers that included "_" to use "-" instead.
=> Forbidden Lands - small change to settings tab

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html, Forbidden_Lands/translation.json
- added Grip to weapon attacks
=> Forbidden Lands - small update to roll template

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/sheet.json
Adjust spacing of Condition Track
Added attribute names to hover text for all non-repeating fields on the sheet
Removed all mentions of NPC-grapple
Added skill notes to the NPC Perception roll,
NPC statblock now actually pulls stats from the NPC sheet
Removed extraneous } from NPC ability checks
Changed vehicle attack default values to more common values (including changing the placeholder text, which was often confused for a filled-in value)
Fixed text color of Second Wind rolltemplate
Added color variables to CSS
Prevented skill modifiers and "Trained in Pilot" checkbox from being changed with a default crew.
=> [Star Wars Saga Edition] Minor cleanup

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html, Forbidden_Lands/translation.json
- Added an "Action" field to attacks. You can setup different actions of the same weapon. Currently, the action field only attaches a label to the attack. You should manually adjust the attack in accordance to the action chosen.
- Removed the "Parry" roll from attacks.
=> Forbidden Lands - "actions" field added to attacks

Ars_Magica_5th/Ars_Magica_5th.css, Ars_Magica_5th/source/Ars_Magica_5th.scss, Ars_Magica_5th/source/_themes.scss
- Move the sheet's font `@import` in first position, apparently the rolltemplate `<style>` only keeps the first
=> [Ars Magica 5th] Try aother fix for rolltemplate fonts

Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.css, Achtung!_Cthulhu_2d20/Achtung!_Cthulhu_2d20.html
Support for dark mode.
Added "Mental" to weapon Type.
Added "Throwing" to weapon Focus.
Updated spells skill list to include all skills (Fixed spelling on Persuasion).
=> Achtung! Cthulhu 2d20 Bugfix/New Feature

Warhammer 4e Character Sheet/README.md, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.css, Warhammer 4e Character Sheet/Warhammer 4e Character Sheet.html, Warhammer 4e Character Sheet/translation.json
- Fixed Legs plate armor penalty when modified with pracitcal quality. It will now reduce the -20 pen to stealth to -10, instead of to 0.
=> [Warhammer 4e Character Sheet] v1.66a Leg Armor penalty fix

TheWitcher/witchersheet.html
=> [TheWitcher] fix spell type

SalvageUnion/SalvageUnion.html
=> [SalvageUnion] denizen dropdown importer

Forbidden_Lands/Forbidden_Lands.css, Forbidden_Lands/Forbidden_Lands.html, Forbidden_Lands/translation.json
- Extended the Attribute range indicators(clickable skulls) to 7 to account for artifacts or...? that might raise a score above 6.
=> Forbidden Lands - attribute score increase

Star Wars Saga Edition/StarWarsSagaEdition.css, Star Wars Saga Edition/StarWarsSagaEdition.html, Star Wars Saga Edition/sheet.json
- Added revealable Organization section
- The button for removing attacks will not hide/show the attack information behind it.
- Adjusted clickable text to match the area that could be clicked.
- Added toggles to the Status button that would include or remove SR and DR.
- Changed NPC weapon damage from a phantom placeholder to an actual value.
- Removed Pilot from NPC skills (because NPC pilots should always be rolling from the vehicle sheet). Added Acrobatics, Deception, and Persuasion.
- Changed "Pilot-operated weapon" checkbox to "Trained in Pilot" and added a sheetworker to only give the bonus if the Pilot position is selected.
- Fixed bug that prevented removing the last crew member.
=> [Star Wars Saga Edition] Added Organization section, minor cleanup

PortesMonstresTresors/pmt.css, PortesMonstresTresors/pmt.htm
- updated images urls to point to the images on the sheet's directory on the repo
=> PortesMonstresTresors - update image urls to repo

CDR/cdr.css, CDR/cdr.html
=> [New Feature][CDR] Added Attribute Rolls

Conan_2d20_Adventures_In_An_Age_Undreamed_Of/Conan_Undreamed.html, Conan_2d20_Adventures_In_An_Age_Undreamed_Of/translation.json
Due to the wrong data-i18n tag (and missing entry in translation.json), Weight was being replaced by a duplicate Condition label.
=> Conan-2d20-Adventures:  Fix weight translation tag

Elemental/elemental.html
The logo wasn't displaying in the character sheet due to a broken link. Updated link works locally, so should be good to go.
=> Update elemental.html to update link to logo on sheet (Bugfix)

SalvageUnion/SalvageUnion.html
=> [SalvageUnion] add skillpoint tracker

3DeT_VICTORY/3detvictory.css, 3DeT_VICTORY/3detvictory.html
Fixed the Custom rolling Type. Changed to a model with 3d6 and how the crit is rolled.
=> [BugFix][3deT Victory] Fixed the Custom Rolling

HARP/harp.css, HARP/harp.html
NPC switch was not working correctly. Issue was caused by an unmatched html tag and a duplicate class name. fixed the tag and renamed the …
=> HARP - NPC Fix
